### ISSUE TITLE
Working with PacBio HiFi reads

### ISSUE THREAD

**Issue by proteinosome** [jtamames/SqueezeMeta#101]
Hi, thanks for making this amazing pipeline to run through a whole set of metagenomics analysis tools! I have one question, is it possible to provide an override option for minimap2 to use the "asm20" mode? This mode is specifically designed to work with long and accurate PacBio HiFi reads (Q20 minimum accuracy, Q30 on average). 

Do you think there's any step after the assembly step that could potentially be tuned to also take advantage of the high accuracy? I will use assembly from other tools tuned to assemble HiFi reads and there's already an extassembly parameter than I can use (Really appreciate that!).

Thank you so much!

**Comment by jtamames** [comment]
Hello
Thank you for you nice comments and for using our tool. There is no way to specify particular options for the mappers, as we do with the assemblers. Maybe we should allow that. In the meantime, you can change the lines 162 and 163 in the script 10.mapsamples.pl in the SqueezeMeta/scripts directory. Just put there the options you need.

I cannot think of any imporovement after the assembly step to get advantage of the HiFi reads. Any suggestion will be very welcomed.

Hope it helps. Best,
Javier

**Comment by proteinosome** [comment]
Hi thanks for the very quick reply and suggestion (This is probably the fastest reply I've ever gotten from a developer!). I think override option would be useful both for assemblers and mapping. For example Canu also has a "pacbio-hifi" mode for assembling HiFi reads. Meanwhile I will try to modify the source and let you know if there's any issue. 

Oh ya I would also like to check that If I would like to use the "merged" mode, there's no way I can supply my own contigs assembled for each of the samples, right? I.e. I have already assembled 6 samples in Canu and I would like to run it through the merged mode. Is there a script to merge the 6 contigs?

I will discuss with you if I can think of any improvement as well, thank you!

**Comment by jtamames** [comment]
Hello
The pipeline does not allow to import your individual assemblies for merging, but we can trick it in the following way:
-Start the project as usual, in merged mode
-When it starts the assembly of the first sample (step 1), stop it
-Put the fasta from the individual assemblies in the `intermediate` directory. Make sure thay have the same names than in the samples file. That is, if you listed the samples "A" and "B" in the samples file, your files should be named `01.A.fasta` and `01.B.fasta`.
-Run the 01.merge_assemblies.pl as usual: `perl 01.merge_assemblies.pl <projectname>`
-If all went well, the result should be the merged assembly. Then restart the normal pipeline with `perl restart.pl -step 2` 

I never did this, hope it works! Let me know the result if you try it

Best,
Javier

**Comment by proteinosome** [comment]
Hi thanks for the reply. Unfortunately I had another issue at step 2 where I see the error:
```
Can't find database: /localdisk/home/user/references/SqueezeMeta_db/db/bac.hmm
```
I created the db using "downloaded_databases.pl" and it was fine all the way until the end where I saw an error:
```
gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
```

I manually downloaded SqueezeMetaDB.tar.gz and untar it but I received the same error message. After the failed extraction I can see the following in the database folder (bac.hmm is not there):
```
distributions
hmms_ssu
hmms
test_data
taxon_marker_sets.tsv
selected_marker_sets.tsv
pfam
img
marker.hmm
bacar_marker.hmm
mito.hmm
euk.hmm
bac.scg.lookup
bac.scg.faa
bac.all.faa
arc.scg.lookup
arc.scg.faa
arc.all.faa
keggdb.dmnd
eggnog.dmnd
nr.dmnd
```

Is the tar gz file corrupted? I will try to use make_databases.pl but it's really painful to redownload everything...

Thank you!

**Comment by fpusan** [comment]
Sorry for the inconvenience. I have confirmed it is indeed corrupted. Will upload the proper one ASAP. Meanwhile `make_databases.pl` should still work ok.

**Comment by proteinosome** [comment]
Hi all, thanks I managed to redownload the database and finished running a batch of samples in sequential mode following @jtamames advice to modify minimap2 parameter in source script. I am also trying to manually merge multiple assemblies using the script:
`perl 01.merge_assemblies.pl <projectname>
`
The script started running fine but cd-hit-est seems like it's only using one CPU even thou the command showed "-T 64". It's been 2 days and the merging is still running (Total of 9 samples, 37k contigs so maybe that's why?). Not sure if it will ever finish but I will take a look at the sequential results for now. I note that many tables here output TPM already, so I assume that comparing at pathway levels it should be fine to compare across samples using TPM (With software like DESeq2 for example)? Thank you!

**Comment by fpusan** [comment]
Hi!
See a bit of discussion on the use of TPM in #62.

**Comment by jtamames** [comment]
Indeed the cd-hit step would not be neccesary, but we do it for saving computing time in the minimus2 merging, that is usually slower. Let me know if it takes more time.
best,

**Comment by proteinosome** [comment]
Hi, thanks for the answer. I have no more question for now so I will close the issue. cd-hit is still running after two days so I've terminated it as I am not sure if it will actually finish. If you have a faster way of merging a lot of contigs please do let me know! Thank you!

**Comment by jtamames** [comment]
Sorry about this... Did you try the `seqmerge` mode? This will merge metagenomes recursively in pairs, so it will deal with less contigs.

Best
