### ISSUE TITLE
Database unzip fail

### ISSUE THREAD

**Issue by qianxun8331** [jtamames/SqueezeMeta#103]
Hi, I'm trying to use SqueezeMeta but not able to download the complete database. 
I tried "download_databases.pl" as well as manually download the database with the command and link inside "download_databases.pl". The database can be downloaded without error message, but it gave:
"gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now"

I've tried several times, it seems that I can get different size of database each time but never able to download the complete file. Can you help with the issue? Thank you.

**Comment by fpusan** [comment]
Hi!

We were updating the database, which explains the fact that you got different sizes every time. It should be ok if you retry now. Please let me know if the issue persists.

Best,

Fernando

**Comment by qianxun8331** [comment]
Thanks for your quick response, will try and let you know if it works.

**Comment by qianxun8331** [comment]
> Hi!
> 
> We were updating the database, which explains the fact that you got different sizes every time. It should be ok if you retry now. Please let me know if the issue persists.
> 
> Best,
> 
> Fernando

The Database now works perfectly. Thank you.

**Comment by fpusan** [comment]
Nice, glad to hear!
