### ISSUE TITLE
ORF with internal stop codons warning during anvi-load-sqm.py

### ISSUE THREAD

**Issue by fconstancias** [jtamames/SqueezeMeta#111]
Dear SqueezeMeta developers,

Thanks  again and sorry to bother you again with my questions.

I got the following anvio-6.2 warning message when running anvi-load-sqm.py. 

> WARNING
> ===============================================
> Please read this carefully: Your external gene calls contained open reading
> frames with internal stop codons, and you asked anvi'o to ignore those. Anvi'o
> replaced internal stop codons with 'X' characters, and stored them in the
> contigs database that way. 33898 of your genes, which corresponded to 0.98% of
> the total 3472934 genes, had internal stop codons. We hope you are happy.

I can't really figure out why ORF could contain internal stop codons? do you have any idea?

**Comment by jtamames** [comment]
Hello

Did you run SqueezeMeta with the --D flag? Because that identifies some ORFs using Blastx searches, and they could indeed contain internal stop codons product of incorrect sequencing or assembly. More likely if you are working with nanopore reads.

**Comment by fconstancias** [comment]
Hey @jtamames, yes indeed, I run with the --D flag. This makes sense. And at the first sight I read 98% so I was a bit confused, 0.98% makes more sense here along with the --D flag.
Thanks again.
