### ISSUE TITLE
export KEGG abundance and KEGG_names to .tsv

### ISSUE THREAD

**Issue by EricRaes** [jtamames/SqueezeMeta#112]
Hi there,

First of all many thanks for the SqueezeMeta and SQMtools development and support!

Is there a possibility to export both the functional abundances (KEGG/COGs ids) along with their full names.

eg., Do you know whether it is possible to combine **1)** and **2)** and export them to a single .tsv file, which would be a matrix which has both abundances and full KEGG names?

Currently SQMtools allows just 1) or 2) but not both
e.g.,
test = loadSQMlite (/path/)
**1)** exportTable(test$functions$KEGG$abund, 'test_KEGG_abund.tsv')
**2)** exportTable(test$misc$KEGG_names, 'test_KEGG_names.tsv')

Many thanks!
Best regards,
Eric

**Comment by fpusan** [comment]
Hi!

It can be done with a little bit of R knowledge

```
ta = test$functions$KEGG$abund
rownames(ta) = test$misc$KEGG_names[rownames(ta)]
exportTable(ta, 'test_abund_with_nice_names.tsv')
```

Let me know if this works for you,

Fernando

**Comment by EricRaes** [comment]
Like a charm! Thanks a lot Fernando. "with_nice_names" :-)
