### ISSUE TITLE
which file to use for further analysis prokfilter.abund.tsv or allfilter.abund.tsv

### ISSUE THREAD

**Issue by kassammohamed** [jtamames/SqueezeMeta#114]
Hello,

I would like to make some statiscal analysis using the abund file outside Squeezemata R code.
What is the best to use the prokfilter.abund.tsv or allfilter.abund.tsv ?

Thanks,

Mohamed

**Comment by fpusan** [comment]
Hi again,

Please refer to the discussion in #79 (the --euk flag would make the same effect as using the prokfilter files).

Best,

Fernando

**Comment by kassammohamed** [comment]
Hi Fernando,

Thank you for the message.
I am a bit confused with the results that I get with the table 11.***.mcount and the table that I get after sqm2tables.
Which one I should use for analysis ? I will use my own R script outside SQM R package.

**Comment by fpusan** [comment]
They mostly have the same information, organized in a different way (check the PDF manual for details on what the mcount file contains).
I personally find the tables from sqm2tables easier to use within R, but it's mostly a matter of personal preference.
