### ISSUE TITLE
Functional hierarchies - going up

### ISSUE THREAD

**Issue by EricRaes** [jtamames/SqueezeMeta#117]
Good morning,

Hope you are having a good day!

Is there a possibility to aggregate the functional COG and KEGG outputs to their respective higher functional categories? e.g., Carbohydrates biosynthesis, Protein Metabolism, Cofactors and Vitamins, biosynthesis, etc..

Either during the SquuezeMeta workflow or later in SQMtools?

Again, many thanks for your help and advice!
Best regards,
Eric

**Comment by EricRaes** [comment]
Apologies!

KEGG_path - has the higher functional categories

ta = test$functions$KEGG$abund
rownames(ta) = test$misc$KEGG_path[rownames(ta)]
exportTable(ta, 'test_KEGG_Paths_with_nice_names.tsv')

**Comment by RitaBogorad** [comment]
Hello! I am using SQMtools to process my results, however, when I try to access the higher hierarchy of KEGG/COG paths, they do not exist. Did I forget to do something on the way? The KEGG_names and COG_names annotations do exist. 

Thank you!
Rita


> data$misc$KEGG_paths
NULL
> data$misc$COG_paths
NULL

**Comment by fpusan** [comment]
Hi!
Looks like a bug. Are you loading the data with `loadSQM` or `loadSQMlite`? Which version of SQMtools are you using?

**Comment by RitaBogorad** [comment]
Loading with loadSQM.
The package version is ‘0.3.3’.
I guess it is time to update?

**Comment by fpusan** [comment]
Definitely! I think that I fixed that bug at some point between 0.3.3 and the current version.
After updating, make sure to remove the `/path/to/my/project/results/tables` directory before running SQMtools again

**Comment by RitaBogorad** [comment]
I have updated SQMtools and also deleted the tables folder from the results. However, another error pops up now, using the loadSQM function:

> data = loadSQM('/path/metatranscriptome/2019/', tax_mode = "nofilter", trusted_functions_only = F, engine = "data.frame")

Loading orfs
    table...
    abundances...
    sequences
    taxonomy...
Loading contigs
    table...
    abundances...
    sequences...
    taxonomy...
    binning info...
Loading bins
    table...
    abundances...
    taxonomy...
Loading taxonomies
Loading functions
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/home/mbogorad/2019_metatrans_exp/metatranscriptome/2019//results/tables/2019.KO.cov.tsv': No such file or directory


I can see a similar error in https://github.com/jtamames/SqueezeMeta/issues/85#issue-598317510, where activating conda environment solved the problem.
I used the GitHub tarball to install and run squeezemeta, not conda. Could that be an issue?
My Squeezemeta version is v1.2.0

Thank you!

**Comment by fpusan** [comment]
Hi,
After calling `loadSQM`, it should have emmited a message saying that it's creating the tables again.
It should not be a problem to use the tarball, but maybe it's easier to just install the latest version from conda.

Anyways, now I realize that you would need a few extra steps.
1) In addition to the new version of SQMtools, you will also need the new version of SqueezseMeta (1.3) to create the tables.
2) You will need to edit the '/path/metatranscriptome/2019/SqueezeMeta_conf.pl` file as described in #196. You might also want to change the `$installpath` variable in that file to point to the new installation (pretty sure this will work even if you don't, but better safe than sorry).
3) You can create the tables manually with `/path/to/new/SqueezeMeta/utils/sqm2tables.py /path/metatranscriptome/2019/ '/path/metatranscriptome/2019/results/tables`. Make sure that you are using the latest version for this.

Let me know how it goes!

**Comment by RitaBogorad** [comment]
Thank you very much for the detailed replies. Everything works now smoothly!
