### ISSUE TITLE
Can you load sqm_reads output with SQMtools?

### ISSUE THREAD

**Issue by EricRaes** [jtamames/SqueezeMeta#119]
Good morning,

Hope you had a good week!

Apologies for bugging again. But I just wanted to ask if you can load sqm_read outputs into R with SQMtools.

When I make tabular formats from the sqm_read outputs I can load them using SQMlite 
E.g.,
>library(SQMtools)
>B3 = loadSQMlite('/scratch1/rae02e/Tables_Derwent_Sites/results_NTB5/tables')
Loading taxonomies
Loading functions
This works fine.

However, when I try to load a sqm_reads file:
>library(SQMtools)
> NTB5 = loadSQM('/scratch1/rae02e/Derwent_NTB5/)

Error in loadSQM("/scratch1/rae02e/Derwent_NTB5/ ") : 
Directory "/scratch1/rae02e/Derwent_NTB5/Derwent_62724_NTB5_14062020_new" does not seem to contain a valid SqueezeMeta project

Looking at the docs https://github.com/jtamames/SqueezeMeta/wiki/Using-R-to-analyze-your-SQM-results I understand from the Figure that all SqueezeMeta projects can be loaded via the loadSQM function.

Is this correct?

Many thanks!
Cheers,
Eric

**Comment by fpusan** [comment]
Hi,

The `loadSQM` function will only work with projects generated with the `SqueezeMeta.pl` scripts (projects following the whole pipeline of assembly/annotation/etc).

This said, results from `sqm_reads.pl` can indeed be loaded into SQMtools by using the `loadSQMlite` function. This is a general purpose function that will load tables generated by `sqm2tables.py`, `sqmreads2tables.py` and `combine-sqm-tables.py`.

I don't think we have this illustrated in the wiki yet, but the SQMtools PDF documentation has details and usage examples.

Have a nice weekend!

Fernando

**Comment by EricRaes** [comment]
Thanks a lot Fernando!!

**Comment by jtamames** [comment]
Closing now, feel free to reopen
