### ISSUE TITLE
combine-sqm-tables.py error with PFAM

### ISSUE THREAD

**Issue by nebfield** [jtamames/SqueezeMeta#123]
Hello,

If you try to use `combine-sqm-tables.py` on tables generated from projects with `$nopfam = 1;` you get the following error:

```
FileNotFoundError: [Errno 2] No such file or directory: 'depression/results/tables/depression.PFAM.abund.tsv
```

From the `combine-sqm-tables.py` script I think it's hard coded to check for KEGG, COG, and PFAM. Ideally the script should respect `SqueezeMeta_conf.pl`

Thanks,
Ben

**Comment by fpusan** [comment]
Indeed it should.  Will fix ASAP.

**Comment by fpusan** [comment]
Hopefully fixed in 7750bac.

If you'd like to apply the fix, just replace the `combine-sqm-tables.py` script for the one in the `SQMtoolsImprovements` branch.

Let me know if this works for you.

**Comment by nebfield** [comment]
I can confirm this works perfectly. Thank you for such an amazingly quick response :smile:

**Comment by fpusan** [comment]
You too. Thanks for testing it so quickly!
