### ISSUE TITLE
Error running sqm_longreads.pl

### ISSUE THREAD

**Issue by Praosobsook** [jtamames/SqueezeMeta#126]
I am trying to use the provided script sqm_longreads.pl with my long nanopore reads.
I got some error which showed up as below:
Cannot open m8 file /home/prasobsook/squeezemeta/unassembledAssigned1/Soil/soil.passed.filtered.trimmed.fq.kegg.m8
Cannot open consensus annotation in /home/prasobsook/squeezemeta/unassembledAssigned1/Soil/readconsensus.txt
It would be appreciated by me if you could provide some suggestions.
Thank you so much,
Prasobsook

**Comment by jtamames** [comment]
Hello Prasobsook
Could you please send me the syslog file that must be in your /home/prasobsook/squeezemeta/unassembledAssigned1 directory, and the result of the following command:
`tree -h -D /home/prasobsook/squeezemeta/unassembledAssigned1`

Best,
Javier

**Comment by Praosobsook** [comment]
Hello Javier,

Thank you for your email.
Please find an attached file below

Thank you so much for your helps,

Best regards,
Prasobsook Paenkaew

**Comment by jtamames** [comment]
Hello
I cannot see the file. Maybe you attached it directly to the email but that does not work. You must compress the file with gzip and then upload in github (https://github.com/jtamames/SqueezeMeta/issues/126). Also do not forget the result of the tree command: `tree -h -D /home/prasobsook/squeezemeta/unassembledAssigned1`. This one you can just copy and paste it

**Comment by Praosobsook** [comment]
Hello Javier,
Please find the new attached file below.
I have tried to run your provided command but seem to be "tree" not working.
The results are shown below

(SqueezeMeta2) [prasobsook@amino SqueezeMeta]$ tree -h -D
/home_sbi_cold/prasobsook/sc-squeezemeta/unassembledAssigned1/

bash: tree: command not found...

Best regards,
Prasobsook

**Comment by jtamames** [comment]
Hello again
I am afraid the syslog file was again not attached correctly. Please send it to me by email to `jtamames@cnb.csic.es`

It also seems that the tree command is not installed in your system (btw, which OS are you using?). For installing it, you can use:
`sudo apt-get install tree`
If you cannot do this, then please do:
`ls -ltr /home/prasobsook/squeezemeta/unassembledAssigned1/Soil/`

Best,

**Comment by Praosobsook** [comment]
Hello,
Thank you so much for your email to attempt to help me.
I installed SqueezeMeta in HPC which was operated by linux.
Using apt-get install tree which I am not allowed to use.
But I instead used conda to install tree and the results are shown below

(SqueezeMeta2) [prasobsook@glutamic2 unassembledAssigned1]$ tree -h -D ./

./

|-- [4.0K Jul 13 19:14]  chemSoil

|   |-- [255M Jul 13 19:13]  chemSoil.fun3.blastx.tax_nofilter.wranks

|   |-- [233M Jul 13 19:13]  chemSoil.fun3.blastx.tax.wranks

|   |-- [4.1G Jul 13 17:55]  chemSoil.nr.blastx

|   |-- [705M Jul 13 17:58]  chemSoil.nr.blastx.collapsed.m8

|   |-- [703M Jul 13 18:02]  chemSoil.nr.blastx.collapsed.merged.m8

|   |-- [   0 Jul 13 18:02]  chemSoil.nt.fasta

|   |-- [7.5G Jul 12 23:26]  chemsoil.passed.filtered.trimmed.l1500.q9.1.fq

|   |-- [   0 Jul 13 19:14]
chemsoil.passed.filtered.trimmed.l1500.q9.1.fq.cogs

|   |-- [   0 Jul 13 19:14]
chemsoil.passed.filtered.trimmed.l1500.q9.1.fq.kegg

|   `-- [   0 Jul 13 18:02]  syslog

|-- [ 424 Jul 13 19:14]  methods.txt

|-- [5.6K Jul 13 19:14]  syslog

|-- [ 190 Jul 12 23:25]  unassembledAssigned1.out.allreads

`-- [ 285 Jul 13 19:14]  unassembledAssigned1.out.mappingstat


1 directory, 14 files
Results from running ls -ltr was as below

(SqueezeMeta2) [prasobsook@glutamic2 unassembledAssigned1]$ ls -ltr

total 24

-rw-rw-r--. 1 prasobsook prasobsook  190 Jul 12 23:25
unassembledAssigned1.out.allreads

-rw-rw-r--. 1 prasobsook prasobsook  424 Jul 13 19:14 methods.txt

-rw-rw-r--. 1 prasobsook prasobsook  285 Jul 13 19:14
unassembledAssigned1.out.mappingstat

drwxrwxr-x. 2 prasobsook prasobsook 4096 Jul 13 19:14 chemSoil

-rw-rw-r--. 1 prasobsook prasobsook 5691 Jul 13 19:14 syslog

Thank you so much

Best regards
Prasobsook Paenkaew

**Comment by jtamames** [comment]
Hello
Thanks for the data. It seems something went wrong when extracting ORFs from the reads, and I think I have found why. Please replace your sqm_longreads.pl by the one I am attaching here (gunzip it first) and check if it works for your dataset.
Best, 
Javier
[sqm_longreads.pl.gz](https://github.com/jtamames/SqueezeMeta/files/4913444/sqm_longreads.pl.gz)

**Comment by jtamames** [comment]
Hopefully fixed in 013765eb4c9deeb524a51ec5504d377c06bf1f2f

**Comment by Praosobsook** [comment]
Hello Javier,
Thank you so much for helping me.
I am afraid that I got some other errors when I tried to run the new
sqm_longreads.pl
The errors are shown as below

(base) [prasobsook@amino bin]$ ./sqm_longreads.pl

./sqm_longreads.pl: line 6: =1: command not found

./sqm_longreads.pl: line 6: $: command not found

./sqm_longreads.pl: line 8: syntax error near unexpected token `('

./sqm_longreads.pl: line 8: `my $commandline=$0 . " ". (join " ", @ARGV);'

I am so sorry for disturbing you many times because I am very new about
coding.
Thank you so much,
Best regards,
Prasobsook Paenkaew

**Comment by jtamames** [comment]
Hello
It seems that the script is being run by bash rathen than by Perl. We must investigate this. Meanwhile, you can run it specifying that it is a perl program. You can do that using the command `perl`, like:
`perl sqm_longreads.pl`

Best,
Javier

**Comment by Praosobsook** [comment]
Hello Javier,
That is very kind of you. Thank you so much.
After I ran the command by specifying perl and it seemed to work at the
beginning and then got some error messages more.

Can't open perl script
"/home_sbi_cold/prasobsook/miniconda2/envs/SqueezeMeta2/lib/SQM_reads/
lca_collapse.pl": No such file or directory

Cannot open file
/home_sbi_cold/prasobsook/sc-squeezemeta/unassembledAssigned3/chemSoil/chemSoil.fun3.blastx.tax.wranks

Thank you so much,
Best wishes,
Prasobsook Paenkaew

**Comment by fpusan** [comment]
Hi!

We have uploaded a new version to conda which should fix the issue without you needing to change files manually.

Just create a new conda environment with

`conda create -n SqueezeMeta-dev -c bioconda -c fpusan squeezemeta-dev`

and activate it with `conda activate SqueezeMeta-dev` 

Let me know if this works for you!

Fernando

**Comment by Praosobsook** [comment]
Hello Fernando,
I did create a new conda environment from your suggestions and the
*sqm_longreads.pl
<http://sqm_longreads.pl>* are executed.
If the whole process finishes I will let you know.
Thank you so much
Best wishes,
Prasbsook

**Comment by Praosobsook** [comment]
Hello Fernando & Javier
Thank you so much for your kind support.
The script has done without any errors with three samples.
Thank you for your prompt reply. I really appreciate it.

Thank you so much
Best regards,
Prasobsook

**Comment by fpusan** [comment]
Glad to hear!
