### ISSUE TITLE
error running loadSQM

### ISSUE THREAD

**Issue by bresyd** [jtamames/SqueezeMeta#128]
Hello,

I am getting an error when I try to load my dataset into SQMtools.
Here is my command and the output I am getting in Rstudio:
```
> # load the sqm project
> so245 = loadSQM('/home/btschits/SO245_metagenomes/squeezemeta_min1000/r_directories/metabat-concoct-1616/sqm_so245_metagenome_min1000', engine = 'data.table')
Generating tabular outputs for project in /home/btschits/SO245_metagenomes/squeezemeta_min1000/r_directories/metabat-concoct-1616/sqm_so245_metagenome_min1000
Loading orfs
    table...
|--------------------------------------------------|
|==================================================|
    abundances...
    sequences
|--------------------------------------------------|
|==================================================|
    taxonomy...
|--------------------------------------------------|
|==================================================|
Loading contigs
    table...
    abundances...
    sequences...
|--------------------------------------------------|
|==================================================|
    taxonomy...
|--------------------------------------------------|
|==================================================|
    binning info...
Aggregation function missing: defaulting to length
Error in dim(ordered) <- ns : 
  dims [product 981440] do not match the length of object [19628761]
```
I am wondering if this has something to do with me restarting SqueezeMeta.pl multiple times at step 16. I did the binning using metabat and concoct (see #69) then ran DAS tool; afterwards I restarted from step 16 only using the metabat output; then I restarted again from step 16 using a different `$score_tres16` value for DAS Tool (the reason I did this was to compare how many bins I am getting with different tools/settings). The files in the result directory (and those in the intermediate directory) I am analysing with SQMtools and where I am getting this error, are from only one of those 3 runs I just explained. However, I noticed that there is also some additional output created in the binning directories every time I restarted at step 16. So I wondering if my error has something to do with the files in the binning directories and that it is mixing up output from the different restarts I did.  

Thanks in advance for your help

**Comment by fpusan** [comment]
Hi! Just in case, does it keep happening when you remove the `engine="data.table"` part?

**Comment by fpusan** [comment]
Thanks for trying! Just wanted to double-check that the new engine was not the problem.
Can you send me the the following file?

`/super/long/path/sqm_so245_metagenome_min1000/intermediate/19.sqm_so245_metagenome_min1000.contigsinbins`

**Comment by bresyd** [comment]
Hi,

thanks again.

Here is the file
[19.sqm_so245_metagenome_min1000.contigsinbins.gz](https://github.com/jtamames/SqueezeMeta/files/4936990/19.sqm_so245_metagenome_min1000.contigsinbins.gz)

**Comment by fpusan** [comment]
Weird,
I'm pretty sure that the problem arises while parsing that file, but I have no problem when parsing it in my machine.
Can you run the following code?

```
inBins=read.table("19.sqm_so245_metagenome_min1000.contigsinbins", header=T, sep='\t', quote='', comment.char='', skip=1, as.is=T)
inBins = reshape2::dcast(inBins, X..Contig~Method, value.var="Bin.ID")
rownames(inBins) = inBins[,1]
result = as.matrix(inBins[,-1,drop=F])
```

If it fails, please let me know what version of the reshape2 package are you using.

**Comment by bresyd** [comment]
this seemed to work:
```

inBins=read.table("/home/btschits/SO245_metagenomes/squeezemeta_min1000/r_directories/metabat-concoct-1616/sqm_so245_metagenome_min1000/intermediate/19.sqm_so245_metagenome_min1000.contigsinbins", header=T, sep='\t', quote='', comment.char='', skip=1, as.is=T)
inBins = reshape2::dcast(inBins, X..Contig~Method, value.var="Bin.ID")
rownames(inBins) = inBins[,1]
result = as.matrix(inBins[,-1,drop=F])
result

               DASTool                       
megahit_1000    "concoct.346.fa_sub.contigs"  
megahit_1000004 "concoct.157.fa.contigs"      
megahit_1000011 "concoct.183.fa_sub.contigs"  
megahit_1000015 "concoct.277.fa.contigs"      
megahit_1000017 "concoct.183.fa_sub.contigs"  
megahit_1000019 "concoct.42.fa_sub.contigs"   
megahit_1000021 "concoct.177.fa.contigs"  
```

**Comment by fpusan** [comment]
Are you in the same R environment you used to run the failed `loadSQM` command? (e.g. different conda environments?)
Anyways, please also send me the `../sqm_so245_metagenome_min1000/results/19.sqm_so245_metagenome_min1000.bintable` file.

**Comment by bresyd** [comment]
Hi,

I am actually also having some R issues that I am currently trying to solve. Need to update ZLIB otherwise I am getting errors when I am starting R studio from the SqueezeMeta conda environment. So maybe don't put further effort into trying to solve my issue until I have my R and Rstudio things sorted.
Here is the the .bintable file though:
[19.sqm_so245_metagenome_min1000.bintable.gz](https://github.com/jtamames/SqueezeMeta/files/4937934/19.sqm_so245_metagenome_min1000.bintable.gz)

**Comment by bresyd** [comment]
Hi Fernando,
over the last few days I unsuccessfully tried solving my R issue. When I am in the SqueezeMeta conda environment and open Rstudio, I get the following error when I try to plot something (comes up already when I try to plot the "car" example that always comes up in a new rstudio session):

```
unable to load shared object '/home/btschits/miniconda3/envs/SQM1.2/lib/R/library/grDevices/libs//cairo.so':
  /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /home/btschits/miniconda3/envs/SQM1.2/lib/R/library/grDevices/libs//../../../../libpng16.so.16)failed to load cairo DLL
 Show Traceback
Error in dev.control(displaylist = "enable") : dev.control() called without an open graphics device
```

It is complaining about the old zlib version that is installed on the cluster I am using (linux debian 9). However, and please correct me if I am wrong, SQMtools comes with its own zlib package and the tools needing zlib actually point to the SQM zlib. But according to the error, r is only looking and finding the old zlib version in my system's path `/lib/x86_64-linux-gnu/libz.so.1`. Do you have any idea how I can solve this issue (tell r to use the zlib package that comes with SQM)? My system admin and myself have run out of ideas.

Thanks heaps for your help

**Comment by fpusan** [comment]
Hi!
SQMtools does not come with its own zlib. It rather looks like an issue with conda. I assume it conda should provide its own zlib/cairo libraries, but I'm not sure it does (our conda package has worked so far in debian10, but maybe the debian9 library is too outdated?).

Maybe try installing cairo from conda?   `conda install -c anaconda zlib cairo`

If this doesn't work, maybe you can install SQMtools outside conda, in your local R environment.

```
R
install.packages("doMC")
install.packages("ggplot2")
install.packages("data.table")
install.packages("reshape2")
install.packages("BiocManager")
BiocManager::install("pathview")
quit(save="no")
R CMD INSTALL <installpath>/SqueezeMeta/bin/DAS_Tool/package/DASTool_1.1.1.tar.gz
R CMD INSTALL <installpath>/SqueezeMeta/lib/SQMtools
```
Let me know if this works

**Comment by bresyd** [comment]
Hi,

installing cairo via conda made no difference but installing SQMtools in my local R environment worked! I followed all your instructions with one exception, I also had to install XML which I did like this
`install.packages("XML", repos = "http://www.omegahat.net/R")` (from https://stackoverflow.com/questions/26042751/cannot-install-package-xml-to-r).

Using SQMtools in my local R env I was just able to load the test project (Hadza) and make some plots so all looks good. 
I am currently trying something with my own dataset (the one for which I created this issue), after which I will try to import it again using SQMtools. I will let you know how that goes and if the initial issue still exists.

Thanks so much for your help with this issue

**Comment by bresyd** [comment]
Hi Fernando,

unfortunately I ran into another issue trying to load my project using SQMtools.

Using my local R environment (as described above) I get the following error when I try to load my project:
```
so245 = loadSQM('/home/btschits/SO245_metagenomes/squeezemeta_min1000/r_directories/maxbin-metabat-concoct/sqm_so245_metagenome_min1000', engine = 'data.table')
Generating tabular outputs for project in /home/btschits/SO245_metagenomes/squeezemeta_min1000/r_directories/maxbin-metabat-concoct/sqm_so245_metagenome_min1000
Traceback (most recent call last):
  File "/home/btschits/miniconda3/envs/SQM1.2_concoct/SqueezeMeta/utils/sqm2tables.py", line 33, in <module>
    from utils import parse_conf_file, parse_orf_table, parse_tax_table, parse_contig_table, parse_bin_table, parse_tax_string, read_orf_names, aggregate_tax_abunds, normalize_abunds, write_orf_seqs, write_contig_seqs, write_row_dict, TAXRANKS 
  File "/home/btschits/miniconda3/envs/SQM1.2_concoct/SqueezeMeta/utils/../lib/utils.py", line 7, in <module>
    from numpy import array, isnan, seterr
ImportError: No module named 'numpy'
Error in loadSQM("/home/btschits/SO245_metagenomes/squeezemeta_min1000/r_directories/maxbin-metabat-concoct/sqm_so245_metagenome_min1000",  : 
  An error occurred while running sqm2tables.py
```
BUT at the same time, in another Rnotebook in the same Rstudio session, I can load a different project without issue
```
so245 = loadSQM('/home/btschits/SO245_metagenomes/squeezemeta_min1000/r_directories/metabat-concoct-1616/sqm_so245_metagenome_min1000', engine = 'data.table')
Loading orfs
    table...
|--------------------------------------------------|
|==================================================|
    abundances...
    sequences
|--------------------------------------------------|
|==================================================|
    taxonomy...
|--------------------------------------------------|
|==================================================|
Loading contigs
    table...
|--------------------------------------------------|
|==================================================|
    abundances...
    sequences...
|--------------------------------------------------|
|==================================================|
    taxonomy...
|--------------------------------------------------|
|==================================================|
    binning info...
Loading bins
    table...
    abundances...
    taxonomy...
Loading taxonomies
Loading functions
Loading total reads
```
The difference between the two projects is that for the one that causes the error, I use the output of 3 binning tools (metabat2, maxbin and concoct), and for the one that works I only used 2 binning tools (metabat2 and concoct).

Do you have an idea what is going wrong here?

Thanks for your help

**Comment by fpusan** [comment]
Yup.
First time a project is loaded with loadSQM, it actually calls a python script to generate some required tables.
Since you are now outside conda you lack the required python dependencies, hence `ImportError: No module named 'numpy'`

Can easily be circumvented.

First, inside the conda environment (in which R didn't work for you, but the rest should work fine).

`sqm2tables.py /path/to/your/PROJECT /path/to/your/PROJECT/results/tables`

Then go outside conda and try to load the project normally with SQMtools. It will find the `tables` folder and go on from there.

**Comment by bresyd** [comment]
Great, I did what you said and now it is working!

Thanks heaps

**Comment by fpusan** [comment]
So are the results with the 3 binning tools loading correctly now?
Is the issue with reshape2 (referenced below) gone too? 

> Hi,
> thanks for your quick response.
> 
> ```
> 
> so245 = loadSQM('/home/btschits/SO245_metagenomes/squeezemeta_min1000/r_directories/metabat-concoct-1616/sqm_so245_metagenome_min1000')
> Loading orfs
>     table...
>     abundances...
>     sequences
>     taxonomy...
> Loading contigs
>     table...
>     abundances...
>     sequences...
>     taxonomy...
>     binning info...
> Aggregation function missing: defaulting to length
> Error in dim(ordered) <- ns : 
>   dims [product 981440] do not match the length of object [19628781]
> ```
> 
> So leaving out the `engine="data.table"` did not solve the issue.
> 
> I have previously loaded another project successfully; for that previous project I never restarted at step 16 using different binning directories/settings (which I did for this current project), hence why I am suspicious that this could be the issue now.

**Comment by bresyd** [comment]
It looks all good now, there was no more error loading the project
```
Loading orfs
    table...
|--------------------------------------------------|
|==================================================|
    abundances...
    sequences
|--------------------------------------------------|
|==================================================|
    taxonomy...
|--------------------------------------------------|
|==================================================|
Loading contigs
    table...
    abundances...
    sequences...
|--------------------------------------------------|
|==================================================|
    taxonomy...
|--------------------------------------------------|
|==================================================|
    binning info...
Loading bins
    table...
    abundances...
    taxonomy...
Loading taxonomies
Loading functions
Loading total reads
```
And from what I can see all the bins are there too.

**Comment by fpusan** [comment]
Glad to hear, closing issue.
