### ISSUE TITLE
annotated 16S sequences in SQM project?

### ISSUE THREAD

**Issue by bresyd** [jtamames/SqueezeMeta#130]
Hi,

I am using SQMtools to explore my SQM project and I was wondering if it was possible to access annotated 16S sequences within my dataset?

I noticed that for bins, there is an object ```bins$table$`Tax `16S``` which gives me a taxonomy string. Is this taxonomy based on a 16S sequence present in the bin? And if so, is there a way to extract this 16S sequence?

If ```bins$table$`Tax 16S``` is indeed a 16S based taxonomy, I assume that ```bins$table$Tax``` is the taxonomy based on the ORF/contigs present in the bin?

Thanks for your help.

**Comment by fpusan** [comment]
> I noticed that for bins, there is an object bins$table$`Tax `16S which gives me a taxonomy string. Is this taxonomy based on a 16S sequence present in the bin? And if so, is there a way to extract this 16S sequence?
> 
> If bins$table$`Tax 16S is indeed a 16S based taxonomy, I assume that bins$table$Tax is the taxonomy based on the ORF/contigs present in the bin?

All your assumptions are correct.

Getting the 16S sequences is not straightforward but not very difficult either.

```
# 1) Load your data.
SQM = loadSQM('/path/to/your/project')
# 2) Get your bin.
bin = subsetBins(SQM, 'bin_of_interest')
# 3) Which ORFs are annotated as 16S rRNA genes?
rRNAorfs = rownames(bin$orfs$table)[bin$orfs$table$`Gene name`=='16S rRNA']
#4) What are the sequences for those ORFs?
rRNAseqs = bin$orfs$seqs[rRNAorfs]
```

Enjoy!

**Comment by bresyd** [comment]
Hi, 
apologize for getting back to you so late.
Thanks for your instructions. I noticed that I need to refresh my R skills a bit in order to get the most out of my data.

Cheers

**Comment by jtamames** [comment]
Closed because of inactivity, feel free to reopen
