### ISSUE TITLE
Error in assembly

### ISSUE THREAD

**Issue by alopgar** [jtamames/SqueezeMeta#132]
Hello
I am performing SqueezeMeta pipeline with test dataset you provide, both with megahit and canu assemblers to see if it works correctly:
```
SqueezeMeta.pl -m coassembly -p SQMtest -s $DB/test/test.samples -f $DB/test/raw --nopfam -miniden 60
SqueezeMeta.pl -m coassembly -p SQMtest -s $DB/test/test.samples -f $DB/test/raw -a canu -map minimap2-ont --nopfam -miniden 60
```
But an error appears in both cases:
```
Error running command:    /mnt/netapp2/Store_uni/home/otras/ini/alg/ENVS/conda/envs/SqueezeMeta/SqueezeMeta/bin/megahit/megahit  -1 /mnt/lustre/scratch/home/otras/ini/alg/Results/SQMtest/SQMtest/data/raw_fastq/par1.fastq.gz -2 /mnt/lustre/scratch/home/otras/ini/alg/Results/SQMtest/SQMtest/data/raw_fastq/par2.fastq.gz -t 12 -o /mnt/lustre/scratch/home/otras/ini/alg/Results/SQMtest/SQMtest/data/megahit >> /mnt/lustre/scratch/home/otras/ini/alg/Results/SQMtest/SQMtest/syslog 2>&1 at /mnt/netapp2/Store_uni/home/otras/ini/alg/ENVS/conda/envs/SqueezeMeta/SqueezeMeta/scripts/01.run_assembly.pl line 107.
Stopping in STEP1 -> 01.run_assembly.pl (megahit)
Died at /home/otras/ini/alg/.conda/envs/SqueezeMeta/bin/SqueezeMeta.pl line 612.
```

Any ideas of what is happening?
Thanks!

**Comment by jtamames** [comment]
Hello!
Could we have the `syslog` file for these runs?
Also, could you paste the result of the following command?:
`ls -ltr  /mnt/lustre/scratch/home/otras/ini/alg/Results/SQMtest/SQMtest/data/raw_fastq`

Best,
Javier

**Comment by alopgar** [comment]
The syslog:
[syslog.txt](https://github.com/jtamames/SqueezeMeta/files/5015506/syslog.txt)

And the output for the command:
```
(SqueezeMeta) [alg SQMtest]$ ls -ltr /mnt/lustre/scratch/home/otras/ini/alg/Results/SQMtest/SQMtest/data/raw_fastq
total 3822176
lrwxrwxrwx 1 otinialg otras         77 Aug  3 12:29 SRR1929485_2.fastq.gz -> /mnt/lustre/scratch//home/otras/ini/alg/SQM_DB/test/raw/SRR1929485_2.fastq.gz
lrwxrwxrwx 1 otinialg otras         77 Aug  3 12:29 SRR1929485_1.fastq.gz -> /mnt/lustre/scratch//home/otras/ini/alg/SQM_DB/test/raw/SRR1929485_1.fastq.gz
lrwxrwxrwx 1 otinialg otras         77 Aug  3 12:29 SRR1927149_2.fastq.gz -> /mnt/lustre/scratch//home/otras/ini/alg/SQM_DB/test/raw/SRR1927149_2.fastq.gz
lrwxrwxrwx 1 otinialg otras         77 Aug  3 12:29 SRR1927149_1.fastq.gz -> /mnt/lustre/scratch//home/otras/ini/alg/SQM_DB/test/raw/SRR1927149_1.fastq.gz
-rw-r--r-- 1 otinialg otras 1975759806 Aug  3 12:30 par1.fastq.gz
-rw-r--r-- 1 otinialg otras 1938119079 Aug  3 12:30 par2.fastq.gz
```

**Comment by jtamames** [comment]
Hello

The files look good. The error is related to this:
`sbatch: error: Batch job submission failed: Time limit specification required, but not provided`
Again related to the usage of your cluster. I would like to check the `syslog` file that SqueezeMeta creates in the project directory (I think you sent me the one produced by Canu instead).
Best,
Javier

**Comment by alopgar** [comment]
This is the syslog inside the project directory:
[syslog.txt](https://github.com/jtamames/SqueezeMeta/files/5015590/syslog.txt)
And this is the log created inside project/data/megahit:
[log.txt](https://github.com/jtamames/SqueezeMeta/files/5015591/log.txt)

Thanks for the help

**Comment by alopgar** [comment]
Hello again. 
As you said, it seemed to be a cluster error, as I managed to solve it. So this thread can be closed now.

Thanks a lot!
Adrian
