### ISSUE TITLE
the tool cant find the samples in fastq

### ISSUE THREAD

**Issue by rissidaniel** [jtamames/SqueezeMeta#139]
When I start to run the pipeline, the tool cant find the samples in the fast file, even after checking the Samples File

How can I solve this problem, please? 

@12-RD-FREEZE_S5.9 M03353:75:000000000-J6CKK:1:1101:15048:1773 1:N:0:ATTCAGAA+TATATCCT
CTTAATCATTACTTCAGTCCTACAGACCAACAAGATAGGCCGAAGTCCTATTGTGTTATTCCATGCTAATGTATTCAGAGCGTAAGCTTGCTTTGAACACTCTAATTTACTCAAAGTAACCTCGCCGACTCTAGGTCTCAGACAGTAAAGCCTAAGATCCCATTTCCGGCAGAAAGATAGGCAGCAACAGTACACAGCGAACCGGACCATTGCTACCCATCCGAAATCCAACTACGAGCTTTTTAACTGC
+
1>A11BB3DF3DGGGB1FEEGBA111BA00A0000B1101B00//BFFGBGHBGBFH2FHDF2F1FG2AFDGFGHFE221B/EC?0BGHEGHHHD21@1>GGHFBGHHHGHHB111FDGGGHHEEE?/<EGHEBDGFHFE21B0CGH222BGHFEB1FFDGHHHHHHC?@@/.<B10GG10>C.<</CACGFDFDF.C--A@C?--A@EFFFFFFFFA9FFF?..?EFBFBBFEF--9@BFFFFFFBF9B
@12-RD-FREEZE_S5.13 M03353:75:000000000-J6CKK:1:1101:12331:1783 1:N:0:ATTCAGAA+TATAGCCT
CCCCAGAGTACCTTTTATCCGTTGAGCGATGGCCCTTCCATACAGAACCACCGGATCACTTTGTCCTACTTTCGTACCTGCTCGACTTGTCAGTCTCGCAGTCAAGCACGCTTATGCCAATGCACTATCAACACGATTTCCGACCGTATTTAGCGTACCTTCGAACTCCTCCGTTACACTTTGGGAGGAG
+
1>>>1111B3DDGGGGBGEF1FG0A1A00G?0AFFGHFGBG2GF1BEFFFFF///EECGHHH1GGGHFHHHHHEHFFFHBEGG??EGGBGGFBGHHHBF??FGFFFFFH?EFGFHFFGBBG1FGGHFHHFFGFFC?GHGHH??BCCEEHHHF1DCECCFHHGAAFGHHGHHHGHHFECGHHHFB..:-..

**Comment by jtamames** [comment]
Hello
Could you please paste here your command line, your samples file, and the output messages when you run SqueezeMeta?

Best,
Javier

**Comment by rissidaniel** [comment]
Hello Javier,
SqueezeMeta.pl -m coassembly -p ridodeplete_results -s sample_12_ribo_smetat.txt -f raw/

SqueezeMeta v1.2.0 - (c) J. Tamames, F. Puente-Sánchez CNB-CSIC, Madrid, SPAIN

Please cite: Tamames & Puente-Sanchez, Frontiers in Microbiology 9, 3349 (2019). doi: https://doi.org/10.3389/fmicb.2018.03349

Run started Fri Aug 14 07:50:12 2020 in coassembly mode
Now creating directories
Reading configuration from /home/drissi/Metatranscriptomes/ribodeplete_RNA/ridodeplete_results/SqueezeMeta_conf.pl
/home/drissi/Metatranscriptomes/ribodeplete_RNA/ridodeplete_results/data/00.ridodeplete_results.samples
6 samples found: PURE-CULTURE-RD_S12 12-RD-RLATER_S7 12-RD-FREEZE_S5 FIELD-BLANK-RD_S13 NEG-CONTROL-RD_S14 12-RD-ZYMO_S6

Now merging files
There must be at least one 'pair1' sequence file in your samples file /home/drissi/Metatranscriptomes/ribodeplete_RNA/ridodeplete_results/data/00.ridodeplete_results.samples, and there is none!


Sample File 
12-RD-FREEZE_S5 12-RD-FREEZE_S5_L001_R1_001.fastq.gz    pair1
12-RD-FREEZE_S5 12-RD-FREEZE_S5_L001_R2_001.fastq.gz    pair2
12-RD-RLATER_S7 12-RD-RLATER_S7_L001_R1_001.fastq.gz    pair1
12-RD-RLATER_S7 12-RD-RLATER_S7_L001_R2_001.fastq.gz    pair2
12-RD-ZYMO_S6   12-RD-ZYMO_S6_L001_R1_001.fastq.gz      pair1
12-RD-ZYMO_S6   12-RD-ZYMO_S6_L001_R2_001.fastq.gz      pair2
FIELD-BLANK-RD_S13      FIELD-BLANK-RD_S13_L001_R1_001.fastq.gz pair1
FIELD-BLANK-RD_S13      FIELD-BLANK-RD_S13_L001_R2_001.fastq.gz pair2
NEG-CONTROL-RD_S14      NEG-CONTROL-RD_S14_L001_R1_001.fastq.gz pair1
NEG-CONTROL-RD_S14      NEG-CONTROL-RD_S14_L001_R2_001.fastq.gz pair2
PURE-CULTURE-RD_S12     PURE-CULTURE-RD_S12_L001_R1_001.fastq.gz        pair1
PURE-CULTURE-RD_S12     PURE-CULTURE-RD_S12_L001_R2_001.fastq.gz        pair2

**Comment by jtamames** [comment]
Hello
Apparently is all good. We have had similar problems before with samples files created in Excel, because Windows OS inserts additional codes for carriage return that are not visible when you edit the file. Could you do the following command:

`dos2unix /home/drissi/Metatranscriptomes/ribodeplete_RNA/ridodeplete_results/data/00.ridodeplete_results.samples`

and then try again?
I think dos2unix is not installed by default, so maybe you have to install it first. If you cannot do this, just send me your samples file and I will dos2unix it for you.

Best,
Javier

**Comment by rissidaniel** [comment]
Hey Javier,
The trick with the sample file worked but now I am having error in the assembler for both megahit and spades

(smetat) drissi@gmbs17:~/Metatranscriptomes/ribodeplete_RNA$ SqueezeMeta.pl -m coassembly -p ribo_results -s samples_file.txt -f raw/ -t 30

SqueezeMeta v1.2.0 - (c) J. Tamames, F. Puente-Sánchez CNB-CSIC, Madrid, SPAIN

Please cite: Tamames & Puente-Sanchez, Frontiers in Microbiology 9, 3349 (2019). doi: https://doi.org/10.3389/fmicb.2018.03349

Run started Fri Aug 14 14:33:51 2020 in coassembly mode
Now creating directories
Reading configuration from /home/drissi/Metatranscriptomes/ribodeplete_RNA/ribo_results/SqueezeMeta_conf.pl
/home/drissi/Metatranscriptomes/ribodeplete_RNA/ribo_results/data/00.ribo_results.samples
6 samples found: PURE-CULTURE-RD_S12 NEG-CONTROL-RD_S14 FIELD-BLANK-RD_S13 12-RD-ZYMO_S6 12-RD-FREEZE_S5 12-RD-RLATER_S7

Now merging files
[1 seconds]: STEP1 -> RUNNING CO-ASSEMBLY: 01.run_assembly.pl (megahit)
  Running assembly with megahit
Error running command:    /home/drissi/miniconda3/envs/smetat/SqueezeMeta/bin/megahit/megahit  -1 /home/drissi/Metatranscriptomes/ribodeplete_RNA/ribo_results/data/raw_fastq/par1.fastq.gz -2 /home/drissi/Metatranscriptomes/ribodeplete_RNA/ribo_results/data/raw_fastq/par2.fastq.gz -t 30 -o /home/drissi/Metatranscriptomes/ribodeplete_RNA/ribo_results/data/megahit >> /home/drissi/Metatranscriptomes/ribodeplete_RNA/ribo_results/syslog 2>&1 at /home/drissi/miniconda3/envs/smetat/SqueezeMeta/scripts/01.run_assembly.pl line 107.
Stopping in STEP1 -> 01.run_assembly.pl (megahit)
Died at /home/drissi/miniconda3/envs/smetat/bin/SqueezeMeta.pl line 612.
(smetat) drissi@gmbs17:~/Metatranscriptomes/ribodeplete_RNA$

**Comment by jtamames** [comment]
Hello
Could you please attach the `syslog` file in the project directory?
Thanks!

**Comment by rissidaniel** [comment]
Hey Javier,
This is the file:

[syslog.txt](https://github.com/jtamames/SqueezeMeta/files/5082454/syslog.txt)

**Comment by rissidaniel** [comment]
Dear Javier,
I manage to find the problem. After better editing the fastq read names, and improve quality control the tool worked very well.  I appreciate your help
