### ISSUE TITLE
Coassembly mode

### ISSUE THREAD

**Issue by QQ8488** [jtamames/SqueezeMeta#143]
Hello, 

I have 10 samples (Sample01-Sample10) running through Coassembly mode.

When I checked the results, it only obtained the results for the first sample (Sample01).  

However,  based on the description of "Coassembly mode",  it should have the results (e.g., gene abundances in each sample. 

Here is the command that I ran.  Do I miss something?

SqueezeMeta.pl -m coassembly -p Project_name -s fileName.samples -f /../raw_directory --cleaning --nopfam --D -miniden 60 -e 1e-5

Thanks  a lot,
Q.

**Comment by fpusan** [comment]
Hi!
I should have worked as you said. I suspect there was a problem with your samples file.
Can you please send me the `fileName.samples` file?
Best,
Fernando

**Comment by QQ8488** [comment]
Hi Fernando, 

I found that there was a format issue in the fineName.sample file.  There was **^M** in each line when I checked the sample file from the terminal. 
I agreed with you that the sample file maybe the reseason caused the problem. 

I fixed the format and re-run the project.  I will update once I have the results. 

Thanks a lot,
QQ.

**Comment by fpusan** [comment]
Closing this as per #152 the user was able to run SqueezeMeta
