### ISSUE TITLE
pipe stop after step 3

### ISSUE THREAD

**Issue by QQ8488** [jtamames/SqueezeMeta#145]
Dear Fernando,

I ran SqueezeMeta by using my own data. However, the pipe was stopped after step 3. 

When I checked the syslog (see attached), looks like there was no error.  I don't know why it happened. 
[Archive.zip](https://github.com/jtamames/SqueezeMeta/files/5123544/Archive.zip)

Thanks a lot,
Q.

**Comment by jtamames** [comment]
Hello
Apparently is all good. Could you copy here the screen output? Could this be related to your system, like a connectivity failure if you are running the pipeline remotely?
Best,
Javier

**Comment by QQ8488** [comment]
Thanks Javier, 

Looks like I did not set up well in our supercomputer.  It only used 8 Gb memories in the previous. 
I rerun the samples by using large memories (128 G). It is still running.  
I have 10 samples and the size of total raw data is about 148 G. Looks like it needs to take a while.  Does it make sense taking around 40 hours in step 6?   "[1 days, 16 hours, 45 minutes, 3 seconds]: STEP6 -> 06.lca.pl" 



SqueezeMeta v1.2.0 - (c) J. Tamames, F. Puente-Sánchez CNB-CSIC, Madrid, SPAIN

Please cite: Tamames & Puente-Sanchez, Frontiers in Microbiology 10.3389 (2019). doi: https://doi.org/10.3389/fmicb.2018.03349

Run started Wed Aug 26 03:30:19 2020 in coassembly mode
Command: /home/SqueezeMeta.pl -m coassembly -p Mu -s /panfs/roc/scratch/q/Mu_test/fileName.samples -f /panfs/roc/scratch/q/Mu --cleaning --nopfam --D -miniden 60 -e 1e-5
Project: Mu
Map file: /panfs/roc/scratch/q/Mu_test/fileName.samples
Fastq directory: /panfs/roc/scratch/q/Mu
Options: threads=12; contiglen=200; assembler=megahit; mapper=bowtie; evalue=1e-5; miniden=60; COGS; KEGG; EXT_DB: /panfs/roc/scratch/q/Mu_test; DOUBLEPASS;
[0 seconds]: STEP0 -> SqueezeMeta.pl
[11 minutes, 25 seconds]: STEP1 -> 01.run_assembly.pl (megahit)
[18 hours, 31 minutes, 16 seconds]: STEP2 -> 02.rnas.pl
[19 hours, 5 minutes, 13 seconds]: STEP3 -> 03.run_prodigal.pl
[22 hours, 17 minutes, 42 seconds]: STEP4 -> 04.rundiamond.pl
[1 days, 16 hours, 45 minutes, 3 seconds]: STEP6 -> 06.lca.pl

**Comment by fpusan** [comment]
Yeah, step 6 can take a long time, specially if your disk read speeds are not super fast. Has it finished now?

**Comment by fpusan** [comment]
Closing, as in #152 the user states that the project finished successfully
