### ISSUE TITLE
Does SqueezeMeta remove the host reads?

### ISSUE THREAD

**Issue by leannmlindsey** [jtamames/SqueezeMeta#147]
I have just run my first test of 6 samples and I do not see any host reads in the output.  Can you direct me to any documentation on how you remove the host DNA?

Also, I am now running two different jobs, one with 14 samples and one with 24 samples.  They are running on a CHPC cluster with one node, 16 threads and 128 GB memory.  So far the smaller job has taken 44 hrs and the larger job, which I started later has taken 10 hrs.  They are both still running and the smaller job is on step 10.mapsamples.pl.

Is it normal to take this long to process?  The initial job with 6 samples, ran in 23 hrs.

**Comment by jtamames** [comment]
Hello!
SqueezeMeta does nothing to remove any DNA, it just process your raw initial input. If you don´t see traces of the host in the results it means either that the host was not assembled (its abundance is low), or it was not possible to taxonomically assign it (this would be weird)
Regarding the times, yes, it is possible to spend 2 or 3 days, or even more, in the complete analysis. You must consider that at the end you will have hundred of thousands of contigs, and millions of genes. Processing all that takes time, and it is a small fraction of the time you will spend analysing the results.
Best,
Javier

**Comment by leannmlindsey** [comment]
Thanks for the quick response. Our host is a wild black eared mouse that does not yet have a published genome.  I will look again in the results but I would have expected it to be the high abundance, based on results from the same data Set using humann3.  Is it possible that the host would appear here as Unmapped or unknown ?

**Comment by jtamames** [comment]
It could be. Maybe it is related to the identitiy filters. We set those for avoiding overprediction in prokaryotes but they could be too stringent for eukaryotes. You can run the analysis with the --euk flag that will drop the filters for eukaryotes. You can also inspect the 06.*.nofilter.wranks file in the results directory, it contains the report of assignments not applying the filters. Check if your host can be found there.
Best,

**Comment by leannmlindsey** [comment]
Will do. Thanks for the help !
