### ISSUE TITLE
Help with output and error in step 16

### ISSUE THREAD

**Issue by mradz19** [jtamames/SqueezeMeta#148]
I have run squeezeeta but I am finding that the process stops at step 16:

```
[1 days, 16 hours, 7 minutes, 30 seconds]: STEP14 -> MAXBIN BINNING: 14.bin_maxbin.pl
[1 days, 17 hours, 1 minutes, 52 seconds]: STEP15 -> METABAT BINNING: 15.bin_metabat2.pl
[1 days, 17 hours, 5 minutes, 54 seconds]: STEP16 -> DAS_TOOL MERGING: 16.dastool.pl
Execution halted
Can't open /scratch_mollison/users/30041036/squeezemeta/databases/wound_RNA_group_1/results/DAS/wound_RNA_group_1_DASTool_bins directory, no DAStool results
WARNING: File /scratch_mollison/users/30041036/squeezemeta/databases/wound_RNA_group_1/results/DAS/wound_RNA_group_1_DASTool_bins/ is empty!. DAStool did not generate results
Skipping BIN TAX ASSIGNMENT: DAS_Tool did not predict bins.
Died at /mnt/nfs/home/30041036/.conda/envs/SqueezeMeta/bin/SqueezeMeta.pl line 999.
```

This is the last few lines of the syslog file:

```
Calling sqm_counter
Creating cog coverage output in /scratch_mollison/users/30041036/squeezemeta/databases/wound_RNA_group_1/results/12.wound_RNA_group_1.cog.funcover
Creating kegg coverage output in /scratch_mollison/users/30041036/squeezemeta/databases/wound_RNA_group_1/results/12.wound_RNA_group_1.kegg.funcover
Creating cog raw reads output in /scratch_mollison/users/30041036/squeezemeta/databases/wound_RNA_group_1/ext_tables/12.wound_RNA_group_1.cog.stamp
Creating kegg raw reads output in /scratch_mollison/users/30041036/squeezemeta/databases/wound_RNA_group_1/ext_tables/12.wound_RNA_group_1.kegg.stamp
Creating abundance file in /scratch_mollison/users/30041036/squeezemeta/databases/wound_RNA_group_1/results/maxbin/abund.list
Running Maxbin: perl /mnt/nfs/home/30041036/.conda/envs/SqueezeMeta/SqueezeMeta/bin/MaxBin/run_MaxBin.pl -thread 44 -contig /scratch_mollison/users/30041036/squeezemeta/databases/wound_RNA_group_1/temp/bincontigs.fasta -abund_list /scratch_mollison/users/30041036/squeezem$
Creating abundance file in /scratch_mollison/users/30041036/squeezemeta/databases/wound_RNA_group_1/results/metabat2/contigs.depth.txt
Running metabat2 : /mnt/nfs/home/30041036/.conda/envs/SqueezeMeta/SqueezeMeta/bin/metabat2 -t 44 -i /scratch_mollison/users/30041036/squeezemeta/databases/wound_RNA_group_1/temp/bincontigs.fasta -a /scratch_mollison/users/30041036/squeezemeta/databases/wound_RNA_group_1/r$
Creating abundance file in /scratch_mollison/users/30041036/squeezemeta/databases/wound_RNA_group_1/results/DAS/maxbin.table
Creating abundance file in /scratch_mollison/users/30041036/squeezemeta/databases/wound_RNA_group_1/results/DAS/metabat2.table
Running DAS Tool for maxbin,metabat2: das_command
Restarting project wound_RNA_group_1, Wed Aug 26 06:43:08 2020 
[0 seconds]: STEP17 -> 17.addtax2.pl
Restarting project wound_RNA_group_1, Wed Aug 26 06:43:40 2020
[0 seconds]: STEP18 -> 18.checkM_batch.pl
Restarting project wound_RNA_group_1, Wed Aug 26 06:43:52 2020 
[0 seconds]: STEP19 -> 19.getbins.pl
```

At the moment I just want to look at the taxonomic abundances but running the sqm2tables.py fails with this message:

```
sqm2tables.py --ignore-unclassified --force-overwrite wound_RNA_group_1/ wound_group_1_tables/
Traceback (most recent call last):
  File "/mnt/nfs/home/30041036/.conda/envs/SqueezeMeta/bin/sqm2tables.py", line 180, in <module>
    main(parse_args())
  File "/mnt/nfs/home/30041036/.conda/envs/SqueezeMeta/bin/sqm2tables.py", line 137, in main
    contig_abunds, contig_tax, contig_tax_wranks = parse_contig_table(perlVars['$contigtable'])
  File "/mnt/nfs/home/30041036/.conda/envs/SqueezeMeta/SqueezeMeta/utils/../lib/utils.py", line 235, in parse_contig_table
    with open(contig_table) as infile:
FileNotFoundError: [Errno 2] No such file or directory: 'wound_RNA_group_1//results/20.wound_RNA_group_1.contigtable'
```

It outputs all of the function tables and the RecA tables then stops, is there any way I can skip the contig table and generate the taxanomic abundance tables?

**Comment by fpusan** [comment]
Hi!

It seems that DAStool is crashing in your system.
If you are not interested in binning information, you can launch SqueezeMeta with the `--nobins` flag.

In order to avoid repeating all the initial steps, you can do the following.
1) Edit the file `wound_RNA_group_1/SqueezeMeta_conf.pl`
2) Change the value of the `$nobins` variable from 0 to 1.
3) Restart the project from step 20 with `restart.pl wound_RNA_group_1 -step 20`

This should generate the contig table and let you run `sqm2tables.py`.

Let me know if this works for you,

Fernando

**Comment by fpusan** [comment]
Also note that binning makes no sense on metatranscriptomics data anyway (I assume that you are working with metatranscriptomics data since your project is named `wound_RNA_group_1`).

Roughly, binning will group together contigs with similar abundance profiles across samples, assuming they come from the same genome.

This makes sense in metagenomics, were contig abundances are related to the abundance of their parent genomes in the population. In metatranscriptomics, however, contig abundances represent expression levels and, as such, contigs from the same parent genome can have very different abundances (since the genes contained in those contigs can have very different expression levels).

**Comment by mradz19** [comment]
Hi Fernando,

Correct it is metatranscriptomic data. Given that, do I need to re run the analysis with the --nobins tag? Or could I use the current data and do what you suggested above?

**Comment by fpusan** [comment]
Both should work, my suggestion is a little trick that will save time.

**Comment by mradz19** [comment]
I did what you suggested above and it worked, the run completed and the sqm2tables.py script worked. Thanks!

**Comment by fpusan** [comment]
Yay.
Can you confirm that the complete pipeline worked with our test data, so I can close #134?

**Comment by mradz19** [comment]
Hi Fernando, the test samples did also fail at step 16:

```
[7 hours, 5 minutes, 11 seconds]: STEP16 -> DAS_TOOL MERGING: 16.dastool.pl
Execution halted
Can't open /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/test_data_DASTool_bins directory, no DAStool results
WARNING: File /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/test_data_DASTool_bins/ is empty!. DAStool did not generate results
Skipping BIN TAX ASSIGNMENT: DAS_Tool did not predict bins.
Died at /mnt/nfs/home/30041036/.conda/envs/SqueezeMeta/bin/SqueezeMeta.pl line 999.
```

This is the last few lines of the syslog file:

```
Diamond block size set to 8 (Free Mem 240.84 Gb)
Running Diamond for taxa: /mnt/nfs/home/30041036/.conda/envs/SqueezeMeta/SqueezeMeta/bin/diamond blastp -q /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/03.test_data.faa -p 44 -d /scratch_mollison/users/30041036/squeezemeta/databases/db/nr.$
Running Diamond for COGs: /mnt/nfs/home/30041036/.conda/envs/SqueezeMeta/SqueezeMeta/bin/diamond blastp -q /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/03.test_data.faa -p 44 -d /scratch_mollison/users/30041036/squeezemeta/databases/db/egg$
Running Diamond for KEGG: /mnt/nfs/home/30041036/.conda/envs/SqueezeMeta/SqueezeMeta/bin/diamond blastp -q /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/03.test_data.faa -p 44 -d /scratch_mollison/users/30041036/squeezemeta/databases/db/keg$
Running HMMER3 for Pfam: /mnt/nfs/home/30041036/.conda/envs/SqueezeMeta/SqueezeMeta/bin/hmmer/hmmsearch --domtblout /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/intermediate/05.test_data.pfam.hmm -E 1e-10 --cpu 44 /scratch_mollison/users/30041036/$
Creating Bowtie reference: /mnt/nfs/home/30041036/.conda/envs/SqueezeMeta/SqueezeMeta/bin/bowtie2/bowtie2-build --quiet /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/01.test_data.fasta /scratch_mollison/users/30041036/squeezemeta/databases/$
Getting raw reads for SRR1927149: cat /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/data/raw_fastq/SRR1927149_1.fastq.gz > /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/temp/test_data.SRR1927149.current_1.gz; cat /scratch_mo$
Aligning with bowtie: /mnt/nfs/home/30041036/.conda/envs/SqueezeMeta/SqueezeMeta/bin/bowtie2/bowtie2 -x /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/data/test_data.bowtie  -1 /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/te$
Calling sqm_counter
Getting raw reads for SRR1929485: cat /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/data/raw_fastq/SRR1929485_1.fastq.gz > /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/temp/test_data.SRR1929485.current_1.gz; cat /scratch_mo$
Aligning with bowtie: /mnt/nfs/home/30041036/.conda/envs/SqueezeMeta/SqueezeMeta/bin/bowtie2/bowtie2 -x /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/data/test_data.bowtie  -1 /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/te$
Calling sqm_counter
Creating cog coverage output in /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/12.test_data.cog.funcover
Creating kegg coverage output in /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/12.test_data.kegg.funcover
Creating cog raw reads output in /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/ext_tables/12.test_data.cog.stamp
Creating kegg raw reads output in /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/ext_tables/12.test_data.kegg.stamp
Creating abundance file in /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/maxbin/abund.list
Running Maxbin: perl /mnt/nfs/home/30041036/.conda/envs/SqueezeMeta/SqueezeMeta/bin/MaxBin/run_MaxBin.pl -thread 44 -contig /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/temp/bincontigs.fasta -abund_list /scratch_mollison/users/30041036/squeezemeta$
Creating abundance file in /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/metabat2/contigs.depth.txt
Running metabat2 : /mnt/nfs/home/30041036/.conda/envs/SqueezeMeta/SqueezeMeta/bin/metabat2 -t 44 -i /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/temp/bincontigs.fasta -a /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results$
Creating abundance file in /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/maxbin.table
Creating abundance file in /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/metabat2.table
Running DAS Tool for maxbin,metabat2: das_command
```

**Comment by mradz19** [comment]
It is a single server (I believe) running Ubuntu 16.04.7. I tried what you said and it failed with this message:
```
[0 seconds]: STEP16 -> DAS_TOOL MERGING: 16.dastool.pl
mkdir: cannot create directory ‘/scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS’: File exists
Execution halted
Can't open /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/test_data_DASTool_bins directory
```

Syslog file:
```
Restarting project test_data, Tue Sep  1 18:29:01 2020
[0 seconds]: STEP16 -> 16.dastool.pl
Creating abundance file in /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/maxbin.table
Creating abundance file in /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/metabat2.table
Running DAS Tool for maxbin,metabat2: LD_LIBRARY_PATH=/mnt/nfs/home/30041036/.conda/envs/SqueezeMeta/SqueezeMeta/lib PATH=/mnt/nfs/home/30041036/.conda/envs/SqueezeMeta/SqueezeMeta/bin:$PATH /mnt/nfs/hom$
```

**Comment by fpusan** [comment]
The last line of the syslog file seems incomplete. Maybe you didn't paste the full thing?

**Comment by jtamames** [comment]
Hello
Could yo do:
`ls -l /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/*table`
and paste the result?
Also, did you see any warning message in the trace log saying that maxbin and metabat could not get any bins?

Thanks!

**Comment by mradz19** [comment]
[syslog.gz](https://github.com/jtamames/SqueezeMeta/files/5154966/syslog.gz)

**Comment by mradz19** [comment]
This sis the output:
```
-rw-r--r-- 1 30041036 1243859 Sep  1 18:29 /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/maxbin.table
-rw-r--r-- 1 30041036  171632 Sep  1 18:29 /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/metabat2.table
```

**Comment by fpusan** [comment]
Thanks for the logfile! So the actual command that is failing is the following

`LD_LIBRARY_PATH=/mnt/nfs/home/30041036/.conda/envs/SqueezeMeta/SqueezeMeta/lib PATH=/mnt/nfs/home/30041036/.conda/envs/SqueezeMeta/SqueezeMeta/bin:$PATH /mnt/nfs/home/30041036/.conda/envs/SqueezeMeta/SqueezeMeta/bin/DAS_Tool/DAS_Tool -i /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/maxbin.table,/scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/metabat2.table -l maxbin,metabat2 -c /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/01.test_data.fasta --write_bins 1 --score_threshold 0.25 --search_engine diamond -t 44 -o /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/test_data --db_directory /scratch_mollison/users/30041036/squeezemeta/databases/db`

Can you run it and paste the output?

**Comment by mradz19** [comment]
I ran that code and this was the output:

```
Running DAS Tool using 44 threads.
predicting genes using Prodigal V2.6.3: February, 2016
identifying single copy genes using diamond version 0.9.22
evaluating bin-sets
Execution halted
```

**Comment by fpusan** [comment]
Ok, that bug is new. Let me see if I can reproduce it in my end.
I would need you to send me the following files:
1) `/scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/01.test_data.fasta`
2) The whole `/scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS` directory
Thanks!

**Comment by mradz19** [comment]
What is the best way to attach those files? They are too big even when compressed

**Comment by fpusan** [comment]
How large are they? Maybe wetransfer/dropbox/drive will be enough?

**Comment by mradz19** [comment]
Here is a link to a drive with the files:

https://drive.google.com/drive/folders/1FWC2eQ3jF37hd59QHqDbSlY6cdZpjiXu?usp=sharing

**Comment by fpusan** [comment]
I just tested the command with your data in our server and it worked.

```
LD_LIBRARY_PATH=/home/fer/opt/SqueezeMeta/lib PATH=/home/fer/opt/SqueezeMeta/bin:$PATH /home/fer/opt/SqueezeMeta/bin/DAS_Tool/DAS_Tool -i /home/fer/test_DAS/DAS/maxbin.table,/home/fer/test_DAS/DAS/metabat2.table -l maxbin,metabat2 -c /home/fer/test_DAS/01.test_data.fasta --write_bins 1 --score_threshold 0.25 --search_engine diamond -t 44 -o /home/fer/test_DAS/DAS/test_data --db_directory /home/fer/Disk7/SqueezeMeta/db/
Running DAS Tool using 44 threads.
predicting genes using Prodigal V2.6.3: February, 2016
identifying single copy genes using diamond version 0.9.22
evaluating bin-sets
starting bin selection from 87 bins 
|||||||||||||||||||||||
bin selection complete: 23 bins above score threshold selected. 
extracting bins to /home/fer/test_DAS/DAS/test_data_DASTool_bins
```

The only things that might be different (and the shouldn't) are the reference files used by DAStool.
Can you send me the following files from `/scratch_mollison/users/30041036/squeezemeta/databases/db`?
- bac.all.faa
- bac.scg.faa
- bac.scg.lookup
- arc.scg.faa
- arc.scg.lookup

I honestly don't think this would be the issue (that part seems correct in the logs you sent me) but let's discard it just in case.

**Comment by mradz19** [comment]
I have added all of those files to the folder I linked above

**Comment by fpusan** [comment]
Hi again,

I have verified that your files are identical to mine and that DAStool still runs fine on my end. We routinely run SqueezeMeta a server with Ubuntu16 installed, and we have never found that issue. On top of that you are using conda, which should negate installation issues.

Everything works right for you until DAStool gets into the R subprocess. Lets first try to isolate the problem. Could you please
1) Activate your SqueezeMeta conda environment.
2) Run the following command.

```
LD_LIBRARY_PATH=/mnt/nfs/home/30041036/.conda/envs/SqueezeMeta/SqueezeMeta/lib PATH=/mnt/nfs/home/30041036/.conda/envs/SqueezeMeta/SqueezeMeta/bin:$PATH Rscript /mnt/nfs/home/30041036/.conda/envs/SqueezeMeta/SqueezeMeta/bin/DAS_Tool\/src/DAS_Tool.R //scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/maxbin.table,/scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/metabat2.table maxbin,metabat2 /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/01.test_data.fasta /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/test_data_proteins.faa.bacteria.scg /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/test_data_proteins.faa.archaea.scg /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/test_data 0.25 44 /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/test_data.seqlength TRUE TRUE false 0.6 0.5
```

3) Let me know what the output is

Sorry for the inconveniences!

**Comment by mradz19** [comment]
Output is simply "Execution Halted"

**Comment by fpusan** [comment]
My bad, that was the wrong command. Please try:

 `Rscript /mnt/nfs/home/30041036/.conda/envs/SqueezeMeta/SqueezeMeta/bin/DAS_Tool\/src/DAS_Tool.R /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/maxbin.table,/scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/metabat2.table maxbin,metabat2 /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/01.test_data.fasta /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/test_data_proteins.faa.bacteria.scg /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/test_data_proteins.faa.archaea.scg /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/test_data 0.25 44 /home/fer/test_DAS /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/test_data.seqlength TRUE TRUE false 0.6 0.5`

**Comment by mradz19** [comment]
No worries, same result though I just get "Execution halted"

**Comment by fpusan** [comment]
It is likely that you'll have to contact the DAStool creators themselves, as I can not reproduce your error in my system. I suspect that it has to do with some R versioning problem, but they should know better than anyone how their software works.

Anyways, let's do our best to isolate the subprocess that is actually failing, so as to give them as much information as possible.

1) Make sure that the SqueezeMeta conda environment is activated.
2) Open the script in `/mnt/nfs/home/30041036/.conda/envs/SqueezeMeta/SqueezeMeta/bin/DAS_Tool/DAS_Tool`
3) Below line 418 (" # 4. Run DAS Tool) paste the following line (one line only)
`echo "Rscript $DIR\/src/DAS_Tool.R $scaffoldstobins $binlabels $contigs $bscg $ascg $outputbasename $score_threshold $threads $thisdir $length_table $write_bin_evals $create_plots $debug $b_weight $c_weight"`
4) Now re-run DAS tool with
`LD_LIBRARY_PATH=/mnt/nfs/home/30041036/.conda/envs/SqueezeMeta/SqueezeMeta/lib PATH=/mnt/nfs/home/30041036/.conda/envs/SqueezeMeta/SqueezeMeta/bin:$PATH /mnt/nfs/home/30041036/.conda/envs/SqueezeMeta/SqueezeMeta/bin/DAS_Tool/DAS_Tool -i /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/maxbin.table,/scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/metabat2.table -l maxbin,metabat2 -c /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/01.test_data.fasta --write_bins 1 --score_threshold 0.25 --search_engine diamond -t 44 -o /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/test_data --db_directory /scratch_mollison/users/30041036/squeezemeta/databases/db`

This will print out a new command, which is actually the DAS tool subprocess that is failing. This, together with the files you sent me before, should be enough for them to check what's going wrong.

Sorry I couldn't be of more help here.

**Comment by mradz19** [comment]
This was the output:

```
Running DAS Tool using 44 threads.
predicting genes using Prodigal V2.6.3: February, 2016
identifying single copy genes using diamond version 0.9.22
Rscript /mnt/nfs/home/30041036/.conda/envs/SqueezeMeta/SqueezeMeta/bin/DAS_Tool\/src/DAS_Tool.R /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/maxbin.table,/scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/metabat2.table maxbin,metabat2 /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/01.test_data.fasta /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/test_data_proteins.faa.bacteria.scg /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/test_data_proteins.faa.archaea.scg /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/test_data 0.25 44 /mnt/nfs/home/30041036/my_local_scratch/squeezemeta/databases/wound_RNA_runs /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/test_data.seqlength TRUE TRUE false 0.6 0.5
evaluating bin-sets
Execution halted
```

**Comment by fpusan** [comment]
Ok, so this:

`Rscript /mnt/nfs/home/30041036/.conda/envs/SqueezeMeta/SqueezeMeta/bin/DAS_Tool\/src/DAS_Tool.R /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/maxbin.table,/scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/metabat2.table maxbin,metabat2 /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/01.test_data.fasta /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/test_data_proteins.faa.bacteria.scg /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/test_data_proteins.faa.archaea.scg /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/test_data 0.25 44 /mnt/nfs/home/30041036/my_local_scratch/squeezemeta/databases/wound_RNA_runs /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/test_data.seqlength TRUE TRUE false 0.6 0.5`

is the command that is actually failing. I double checked the files you sent me and up to that point everything seems correct.

Just as a final test, please try the following:
1) Make sure that the SqueezeMeta conda environment is activated.
2) Run `which Rscript` and paste here the output.
3) Run the command I provided at the beginning of this message, but add the `--verbose` flag at the beginning. It would go `Rscript --verbose /mnt/nfs/lots/of/stuff/...`.

Actually, this reminds me a lot of #51 , but in that case the user was using a different version of DAStool than the one we provide with SqueezeMeta. Just in case let's test your version too.

1) Make sure that the SqueezeMeta conda environment is activated.
2) Create a small script maned `test.R`with the following content (just paste this in a text file).
```
library(methods)
packages <- list('doMC','data.table','ggplot2','DASTool')
foo <- lapply(packages,function(x){suppressPackageStartupMessages(library(x,character.only=TRUE))})
print(.libPaths())
print(sessionInfo())
```
3) Run it with `Rscript test.R` and let me know what the output is.

**Comment by mradz19** [comment]
Sorry for the delay.

1. Which rscript:

```
/mnt/nfs/home/30041036/.conda/envs/SqueezeMeta/bin/Rscript
```

2. Rscript with verbose:

```
running
  '/mnt/nfs/home/30041036/.conda/envs/SqueezeMeta/lib/R/bin/R --slave --no-restore --file=/mnt/nfs/home/30041036/.conda/envs/SqueezeMeta/SqueezeMeta/bin/DAS_Tool/src/DAS_Tool.R --args /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/maxbin.table,/scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/metabat2.table maxbin,metabat2 /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/01.test_data.fasta /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/test_data_proteins.faa.bacteria.scg /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/test_data_proteins.faa.archaea.scg /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/test_data 0.25 44 /mnt/nfs/home/30041036/my_local_scratch/squeezemeta/databases/wound_RNA_runs /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/test_data.seqlength TRUE TRUE false 0.6 0.5'

evaluating bin-sets
Execution halted
```

3. Running test.R

```
[1] "/mnt/nfs/home/30041036/.conda/envs/SqueezeMeta/lib/R/library"
R version 3.6.3 (2020-02-29)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: Ubuntu 16.04.7 LTS

Matrix products: default
BLAS/LAPACK: /mnt/nfs/home/30041036/.conda/envs/SqueezeMeta/lib/libopenblasp-r0.3.10.so

locale:
 [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_AU.UTF-8        LC_COLLATE=en_AU.UTF-8    
 [5] LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_AU.UTF-8   
 [7] LC_PAPER=en_AU.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
[1] DASTool_1.1.1     ggplot2_3.3.2     data.table_1.12.8 doMC_1.3.6       
[5] iterators_1.0.12  foreach_1.5.0    

loaded via a namespace (and not attached):
 [1] codetools_0.2-16 withr_2.2.0      crayon_1.3.4     grid_3.6.3      
 [5] R6_2.4.1         lifecycle_0.2.0  gtable_0.3.0     magrittr_1.5    
 [9] scales_1.1.1     pillar_1.4.6     rlang_0.4.7      vctrs_0.3.2     
[13] ellipsis_0.3.1   glue_1.4.1       munsell_0.5.0    compiler_3.6.3  
[17] pkgconfig_2.0.3  colorspace_1.4-1 tibble_3.0.3    
```

**Comment by fpusan** [comment]
Your environment seems ok (minor version differences, possibly due to the different ubuntu versions).

I forgot a small part, in the RScript command change the last `false` to `TRUE` so we get more debug information.

`Rscript --verbose /mnt/nfs/home/30041036/.conda/envs/SqueezeMeta/SqueezeMeta/bin/DAS_Tool\/src/DAS_Tool.R /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/maxbin.table,/scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/metabat2.table maxbin,metabat2 /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/01.test_data.fasta /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/test_data_proteins.faa.bacteria.scg /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/test_data_proteins.faa.archaea.scg /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/test_data 0.25 44 /mnt/nfs/home/30041036/my_local_scratch/squeezemeta/databases/wound_RNA_runs /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/test_data.seqlength TRUE TRUE TRUE 0.6 0.5`

**Comment by mradz19** [comment]
This is the output:

```
evaluating bin-sets
Error in mcfork() : 
  unable to fork, possible reason: Cannot allocate memory
Calls: cherry_pick ... %dopar% -> <Anonymous> -> mclapply -> lapply -> FUN -> mcfork
Execution halted
```

**Comment by fpusan** [comment]
Finally some information.
From reading that it would seem that you don't have enough memory. You can try running it in an instance with more memory.

Just to confirm this is the issue, let's try running it with only 1 core (problem arises while trying to fork the process to multiple cores).

`Rscript --verbose /mnt/nfs/home/30041036/.conda/envs/SqueezeMeta/SqueezeMeta/bin/DAS_Tool\/src/DAS_Tool.R /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/maxbin.table,/scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/metabat2.table maxbin,metabat2 /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/01.test_data.fasta /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/test_data_proteins.faa.bacteria.scg /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/test_data_proteins.faa.archaea.scg /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/test_data 0.25 1 /mnt/nfs/home/30041036/my_local_scratch/squeezemeta/databases/wound_RNA_runs /scratch_mollison/users/30041036/squeezemeta/databases/test/test_data/results/DAS/test_data.seqlength TRUE TRUE TRUE 0.6 0.5`

**Comment by mradz19** [comment]
Hi Fernando, this is the output:

```
evaluating bin-sets
starting bin selection from 87 bins 
|||||||||||||||||||||||
bin selection complete: 23 bins above score threshold selected. 
```

**Comment by fpusan** [comment]
So it works! I'm surprised that you are running into memory issues there while the rest of the pipeline had no issues.

You will need to to find a sweet spot between the number of processors you request and the memory available in your system. If things come to the worst case, you'll have to run the DAStool step using a single thread.

You can change the number of threads used by an existing SqueezeMeta project by editing the `$numthreads` variable in the `/path/to/the/Project/SqueezeMeta_conf.pl` file.

So the way to do it would be

1) Run SqueezeMeta normally.
2) If it dies in step 16,lower the number of threads by editing the `SqueezeMeta_conf.pl` file inside the project dir, and re-run step 16 with `16.dastool.pl /path/to/the/Project`.
3) After it finishes successfully, reset the number of threads to the original value, and continue with `restart.pl /path/to/the/Project -step 17`
