### ISSUE TITLE
Error in loadSQM

### ISSUE THREAD

**Issue by leannmlindsey** [jtamames/SqueezeMeta#149]
Hello, I have successfully ran 6 samples through the visualization examples listed on the GitHub page.  I ran a second job with 14 samples and I get this error when I try to load in the data.

> MonarchFull=loadSQM('/Users/leannmlindsey/Dropbox/University_of_Utah/MonarchFull14')
Loading orfs
    table...
    abundances...
    sequences
    taxonomy...
Error in `[.data.frame`(SQM$orfs$table, , method) : 
  undefined columns selected
> plotTaxonomy(MonarchFull, rank='phylum', count='percent')
Error in class(SQM) %in% c("SQM", "SQMlite") : 
  object 'MonarchFull' not found

do you have any idea what this could be caused by?

UPdate:  I had missed one file when I downloaded results to run through R on my laptop....all fixed.  Sorry to trouble you.

**Comment by fpusan** [comment]
Glad to hear, closing issue!
