### ISSUE TITLE
Issue with merging files

### ISSUE THREAD

**Issue by oyac** [jtamames/SqueezeMeta#15]
Hello, 
I am having a problem right in the beginning of the pipeline: it seems it its not merging the raw files, even though I can see the links in the raw_fastq folder. I already tried changing the names of the raw files to make them simpler, and I run it with the test data and worked normally.

SqueezeMeta v0.4.2, Jan 2019 

Working for sample Control
rm: cannot remove 'home/squeezem/dbs/sip/SIP3/temp/par*fast*': No such file or directory
Now merging files
cat  >
sh: 1: Syntax error: end of file unexpected
rm: cannot remove 'home/squeezem/dbs/sip/SIP3/data/megahit': No such file or directory
Running Megahit for Control: ../../SqueezeMeta/scripts/../bin/megahit/megahit  -r  --k-list 29,39,59,79,99,119,141 -t 12 -o home/squeezem/dbs/sip/SIP3/data/megahit
1007.0Gb memory in total.
Using: 907.006Gb.
megahit: Cannot find file --k-list
Error running command:    ../../SqueezeMeta/scripts/../bin/megahit/megahit  -r  --k-list 29,39,59,79,99,119,141 -t 12 -o home/squeezem/dbs/sip/SIP3/data/megahit at ../../SqueezeMeta/scripts/../scripts/01.run_assembly_merged.pl line 101.
Stopping in STEP1 -> 01.run_assembly_merged.pl (megahit)

can you help me, please?
thanks

**Comment by jtamames** [comment]
Hello!

Could you please paste your command line, and attach your samples file?

Best,

Javier

**Comment by oyac** [comment]
Hello, here are the information asked:

perl ../../SqueezeMeta/scripts/SqueezeMeta.pl -m merged -p SIP3  -s sip_meta.samples -f raw/

(i couldn`t attach the file only with .samples extension)
[sip_meta.samples.txt](https://github.com/jtamames/SqueezeMeta/files/3007263/sip_meta.samples.txt)

Thanks,

**Comment by jtamames** [comment]
Hello again!

Could you please upload also the SqueezeMeta_conf.pl file that should be in the project directory? I am puzzled because the paths seem to lack a leading "/" (they look like "home/squeezem/dbs/sip/SIP3/", without the leading slash)
Thanks!

**Comment by oyac** [comment]
Hello, 
Maybe I did something wrong while pasting stuff here, here is again the error, and the .pl file.
[SqueezeMeta_conf.pl.txt](https://github.com/jtamames/SqueezeMeta/files/3007714/SqueezeMeta_conf.pl.txt)


SqueezeMeta v0.4.2, Jan 2019 - (c) J. Tamames, F. Puente-Sánchez CNB-CSIC, Madrid, SPAIN

Please cite: Tamames & Puente-Sanchez, bioRxiv 347559 (2018); doi: https://doi.org/10.1101/347559; Tamames & Puente-Sanchez, Frontiers in Microbiology (2019), in       press

Run started Mon Mar 25 17:57:38 2019 in merged mode
Now creating directories
Reading configuration from /mnt/nfs/bioinfdata/home/NIOO/ohanac/squeezem/dbs/sip/SIP3/SqueezeMeta_conf.pl
Now moving read files
3 samples found
[0 seconds]: STEP1 -> RUNNING ASSEMBLY: 01.run_assembly_merged.pl (megahit)
Working for sample Control
rm: cannot remove '/mnt/nfs/bioinfdata/home/NIOO/ohanac/squeezem/dbs/sip/SIP3/temp/par*fast*': No such file or directory
Now merging files
cat  >
sh: 1: Syntax error: end of file unexpected
rm: cannot remove '/mnt/nfs/bioinfdata/home/NIOO/ohanac/squeezem/dbs/sip/SIP3/data/megahit': No such file or directory
Running Megahit for Control: ../../SqueezeMeta/scripts/../bin/megahit/megahit  -r  --k-list 29,39,59,79,99,119,141 -t 12 -o /mnt/nfs/bioinfdata/home/NIOO/ohanac/      squeezem/dbs/sip/SIP3/data/megahit
megahit: Output directory ./megahit_out/ already exists, please change the parameter -o to another value to avoid overwriting.
Error running command:    ../../SqueezeMeta/scripts/../bin/megahit/megahit  -r  --k-list 29,39,59,79,99,119,141 -t 12 -o /mnt/nfs/bioinfdata/home/NIOO/ohanac/squ      eezem/dbs/sip/SIP3/data/megahit at ../../SqueezeMeta/scripts/../scripts/01.run_assembly_merged.pl line 101.
Stopping in STEP1 -> 01.run_assembly_merged.pl (megahit). File /mnt/nfs/bioinfdata/home/NIOO/ohanac/squeezem/dbs/sip/SIP3/results/01.SIP3.fasta is empty!

Thanks!

**Comment by jtamames** [comment]
Hello again

Ok, I've found the problem. You probably created your samples file in a Windows SO machine, that put a invisible CR (carriage return) code at the end of the lines which causes trouble when read under Linux. One easy way to solve this is to use the "dos2unix" command, running it as  "dos2unix sip_meta.samples". That will transform DOS format into Unix. I am attaching here the corrected samples file. Please tell me if that works for you.

Btw, I noticed that your filenames contain "16S". Just remind you that SqueezeMeta is designed to work with metagenomic/metatrancriptomic sequences, and it is of little use for studying amplicon sequences. If your sequences are 16S, you better use a dedicated pipeline suach as Qiime or Mothur to analyze them.

Best,
Javier
[sip_meta.samples.txt](https://github.com/jtamames/SqueezeMeta/files/3008581/sip_meta.samples.txt)

**Comment by oyac** [comment]
Hello Javier, 

Thanks, it solved the problem! Yes, indeed, i created the file with Excel. Btw, the samples are frommetagenomic shotgun, the 16S is because I also have 16S from the same samples.

Thanks!

Ohana

**Comment by jtamames** [comment]
Great Ohana, nice to hear it worked!

**Comment by jtamames** [comment]
Closed (solved)
