### ISSUE TITLE
SQMlite objects do not support subset functions

### ISSUE THREAD

**Issue by fpusan** [jtamames/SqueezeMeta#150]
Just confirming from the other thread that step 16 is failing with the test data.

Also I am using the SQMtools R package to look at taxonomy, is there a way to filter for bacteria only? I am getting homosapien (as expected) appearing and a lot of unclassified reads. Can I remove the unclassified as well?

EDIT: I am attempting subset only bacteria using subsetTAX with this code:
```
bac = subsetTax(RNA.group1, 'domain', tax='Bacteria', rescale_copy_number=F)
```
However I get this error:
```
Error in SQM$contigs$tax[, rank] : subscript out of bounds
```

I also tried with 'kingdom' instead of 'domain' and get the same error

I also used combine-sqm-tables.py as I split the project over two runs, it worked fine so I used loadSQMlite to load the data into R. However when I try to subsetTax with the merged data I get an error saying:
```
The first argument must be a SQM project
```
Do I need to do anything else to the SQMlite data before I start using it?

_Originally posted by @mradz19 in https://github.com/jtamames/SqueezeMeta/issues/134#issuecomment-684123266_

**Comment by fpusan** [comment]
Hey, @mradz19
1) Try `bac = subsetTax(RNA.group1, 'superkingdom', tax='Bacteria', rescale_copy_number=F)`. Also, if you are removing human contamination you'd likely want to use `rescale_copy_number=T`.
2) SQMlite objects are intended for visualization only, and currently they don't support the use of subset functions. Depending on what you want to do with your data (e.g. remove human reads and then plot taxonomy charts) there might be some workarounds to get you there.

**Comment by mradz19** [comment]
Ok I will try, is there a way to combine two Squeezemeta projects for use in R that includes subset functions?

**Comment by fpusan** [comment]
If you only need to select bacterial reads and get taxonomic/functional abundance tables (and plots) the best way would be to remove them from the individual projects and then manually combine the tables. I could guide you through that.

If you need more advanced features (e.g. krona charts or kegg pathways) I'm afraid that would not be possible. In that case you should run all your samples in the same project.

How many samples do you have? If the data is too complex to be assembled at once there are different avenues you could follow.

1) Remove reads mapping to the human genome before running SqueezeMeta. This is apparently rather easy using bbsplit (http://seqanswers.com/forums/showthread.php?t=41288) although I haven't personally used it. Another solution following https://www.biostars.org/p/418692/ would be to directly use bowtie2 + samtools (which we actually redistribute with SqueezeMeta).

2) Try to use SqueezeMeta in the `seqmerge` mode, which relieves memory usage during assembly.

**Comment by mradz19** [comment]
I have 14 samples but I was finding that the system was running out of memory. These fastq files have already been host depleted by a colleague as we are doing combined host and microbial analysis, so it is a little strange that such a large proportion of the reads are identified as human.

**Comment by mradz19** [comment]
Also one other question which output would best be used for DEG analysis of functional and taxanomic differences between groups?

**Comment by fpusan** [comment]
For differential expression analysis you'd want to use the raw reads, and let the program doing the analysis (e.g. DESeq2) perform normalization on its own.

You can do this to get the tables you need (example here is for class-level taxonomic annotations, but it will work similarly for other ranks or for functional categories).

```
library(SQMtools)

### Load your data
P1 = loadSQM('/path/to/the/first/project')
P2 = loadSQM('/path/to/the/second/project')

### Get the bacterial reads
P1_bact = subsetTax(P1, 'superkingdom', 'Bacteria')
P2_bact = subsetTax(P2, 'superkingdom', 'Bacteria')

### Get abundances from the desired taxonomic rank / functional category
class1 = P1_bact$taxa$class$abund # In this example we use classes
class2 = P2_bact$taxa$class$abund

### Combine the data
combined = merge(class1, class2, by='row.names', all=T)
rownames(combined) = combined$Row.names
combined=combined[,-1]
combined[is.na(combined)] = 0
```

The resulting abundance matrix can then be used as the input for the program of your liking.

**Comment by fpusan** [comment]
Added commit a826001, which simplifies this. It will be made available for everyone in the next release, but I can instruct you on how to update your SQMtools so you can use it.

Fair warning, we still do not support the use of subset functions on SQMlite objects.

However, this patch adds a new function called `combineSQMlite` which allows to merge SQM or SQMreads objects even when they originate from different projects.

So now you could do something along the lines of

```
### Load your data
P1 = loadSQM('/path/to/the/first/project')
P2 = loadSQM('/path/to/the/second/project')

### Get the bacterial reads
P1_bact = subsetTax(P1, 'superkingdom', 'Bacteria')
P2_bact = subsetTax(P2, 'superkingdom', 'Bacteria')

### Combine the data and do fancy stuff
combined = combineSQMlite(P1, P2)
plotTaxonomy(combined)
exportKrona(combined)
exportPathway(combined, '00910', 'percent')
```

**Comment by mradz19** [comment]
Thanks for that! How do I go about updating SQMtools to use this?

**Comment by fpusan** [comment]
1) Download the develop branch from here (https://github.com/jtamames/SqueezeMeta/archive/develop.zip) and uncompress it wherever.
2) If you are using conda, activate the SqueezeMeta environment.
3) Run `R CMD INSTALL /path/to/SQM_develop/lib/SQMtools`.

**Comment by mradz19** [comment]
Thanks for that I will give it a go.

I've tried several pipelines for metatrancriptomic analysis and the results from Squeezemeta seem to be most representative of what we would expect for our samples so I plan on doing full taxanomic and functional analysis, I have a couple of questions:

1. If I want to do DEG analysis of the function results what would be the best way to do it? I was hoping to do a global analysis initially rather than focusing on specific categories or taxa, would that be possible?

2. If I can do global DEG analysis and I identify some differentially expressed proteins, is there a way to also identify what bacteria those proteins originated from? 

3. Can I filter for certain species/genus and collect all of their functional annotations to perform DEG analysis on?

**Comment by fpusan** [comment]
Glad to hear SQM is working for you!

Regarding your questions.
1) Yes, just get the raw abundance tables for KEGG, COG or PFAM from SQMtools and use them as the input for your preferred statistical method.
2) Yes. See the following example.
```
# Let `DE_function_IDs` be a vector with the names of the differentially expressed functions (e.g c("K02014", "K01931").
# Let `myProj`  be the SQM object with your project.

# First create a regular expression for your differentially expressed functions
pattern = paste(DE_function_IDs, collapse='|')
# Now create a second SQM object containing only the DE functions
myProj.DE = subsetFun(myProj, pattern, fixed=F)
# Profit
plotTaxonomy(myProj.DE)

### If you have a vector of DE genes (`DE_ORFs_IDs`) instead of a vector DE functional categories it becomes even easier
myProj.DE = subsetORFs(myProj, DE_ORFs_IDs)
```
3) I'm not sure whether that would be correct or not, and it might be best to check that with the creator of whatever statistical package you end up using for calculating differential expression.

Cheers,

Fernando

**Comment by mradz19** [comment]
Thanks for that. Would the abundance tables I want be the ones generated from running sqm2tables.py?

For example for COG functions would I use the output "project".COG.abund.tsv?

Is there a way to merge these tables as I have one from each project? Also I would assume there would be a lot of non-bacterial annotations as well, can I select for only the bacterial functional annotations?

I would also be interested in looking at DE genes, what output would I use for that?

Sorry for all the questions I'm still relatively new to R, I learnt mainly using another program but I think I will be shifting to Squeezemeta from now on.

**Comment by fpusan** [comment]
> For example for COG functions would I use the output "project".COG.abund.tsv?

Yes, but if the package you are using for statistics is an R package I would rather use SQMtools and use R for everything. COG results would be stored in `myProj$functions$COG$abund`, check the [wiki](https://github.com/jtamames/SqueezeMeta/wiki/Using-R-to-analyze-your-SQM-results) for lots of examples.

>Is there a way to merge these tables as I have one from each project? Also I would assume there would be a lot of non-bacterial annotations as well, can I select for only the bacterial functional annotations?

Yes, and yes, code examples are provided above, in my previous answers.

>I would also be interested in looking at DE genes, what output would I use for that?

When you load your project in R using SQMtools, they can be found in `myProj$orfs$abund`.

**Comment by mradz19** [comment]
Thanks for all of your help, am I able to reorder my samples? I've noticed in figures the samples on the x axis are not in the order I am after

**Comment by fpusan** [comment]
It is possible in the development version you just downloaded.
Just do
plotTaxonomy(myProj, samples=my_vector_with_correct_sample_order)

**Comment by mradz19** [comment]
I was having another issue. Say I want to extract any functions relating to "virulence", how can I do this from the combined data? I've noticed when I use the subsetFun command on data combined using this method:

```
library(SQMtools)

### Load your data
P1 = loadSQM('/path/to/the/first/project')
P2 = loadSQM('/path/to/the/second/project')

### Get the bacterial reads
P1_bact = subsetTax(P1, 'superkingdom', 'Bacteria')
P2_bact = subsetTax(P2, 'superkingdom', 'Bacteria')

### Get abundances from the desired taxonomic rank / functional category
class1 = P1_bact$function$COG$abund # In this example we use classes
class2 = P2_bact$funciton$COG$abund

### Combine the data
combined = merge(class1, class2, by='row.names', all=T)
rownames(combined) = combined$Row.names
combined=combined[,-1]
combined[is.na(combined)] = 0
```

I get an error that 'combined' is not a SQM object, is there another way I could do this? I guess after the combining the projects it is no longer the same structure as a SQM object. I have also tried the same method on data combined using CombineSQMlite but I get the same error.

**Comment by fpusan** [comment]
Sure. Just do whatever subsets you need to do (taxonomic or functional) in the individual projects before combining them.

**Comment by fpusan** [comment]
That would suck, wouldn't it? :)

By default, `subsetFun` searches on the following columns from the ORF table (values provided as an example).

- Gene name: _narL_
- KEGG ID: _K07684_ 
- KEGGFUN: _two-component system, NarL family, nitrate/nitrite response regulator NarL_
- KEGGPATH: _Environmental Information Processing; Signal transduction; Two-component system | Brite Hierarchies; Protein families: signaling and cellular processes; Two-component system_
- COG ID: _COG2197_
- COGFUN: _Response regulator containing a CheY-like receiver domain and an HTH DNA-binding domain_
- COGPATH: _Transcription|Signal transduction mechanisms_
- PFAM: _PF00196 [Bacterial regulatory proteins, luxR family]_

As well as extra ID and name fields if you used custom databases for annotation in your project. You can control the columns that will be used with the `columns` parameter of `subsetFun`.
