### ISSUE TITLE
SQMtools errors in the analysis

### ISSUE THREAD

**Issue by QQ8488** [jtamames/SqueezeMeta#152]
Hey, 

I successfully ran my data through SqueezeMeta pipeline on our University's remote cluster.

Then, I downloaded all of the results in my iMac.

Now, I plan to subsequently analyze the data on my iMac by using SQMTools (https://github.com/jtamames/SqueezeMeta/wiki/Using-R-to-analyze-your-SQM-results).

I successfully installed "SQMtools" on my iMac. 

When I ran in Rstudio, I received some error. I do not know how to fix it. 

> Muru=loadSQM('Muru',engine='data.table')
Generating tabular outputs for project in Muru
sh: /panfs/roc/groups/qq/.conda/envs/SqueezeMetaTest/SqueezeMeta/utils/sqm2tables.py: No such file or directory
Error in loadSQM("Muru", engine = "data.table") : 
  An error occurred while running sqm2tables.py

PS: I installed SqueezeMeta in our University's remote cluster (/panfs/roc/groups/qq/.conda/envs/SqueezeMetaTest/)

Thanks a lot,
QQ

**Comment by fpusan** [comment]
Hi! 
You have to generate the tabular outputs in your cluster. 

sqm2tables.py /path/to/your/project /path/to/your/project/results/Tables

Then move the whole project directory to your Mac and try to load it with SQMtools, it should work.

**Comment by QQ8488** [comment]
Hi Fernando,

I followed your suggestion and ran sqm2tables.py. 
I tried to load it with SQMtools; it shows another error.

> Muru=loadSQM('Muru',engine='data.table')
Error in loadSQM("Muru", engine = "data.table") : 
  unused argument (engine = "data.table")

What should I have to do?

Thanks a lot,
QQ.

**Comment by QQ8488** [comment]
Hi Fernando,

I found that if I remove the argument  (engine = "data.table"), I can load the project. But it takes time. 

BTW,  in the plotTaxonomy function, is there a way that I can argue to rearrange the samples in the x-axis?  
I checked the SQMtools_0.5.0.pdf, and I did not find an argument. 

Thanks a lot,
QQ

**Comment by fpusan** [comment]
Hi!

Are you sure you are using the SQMtools version included in SqueezeMeta v1.2? The latest version should accept the `engine` argument.

Regarding the second question `plotTaxonomy` will stick to the order that you specified in your samples file. If I needed a custom order I would do something along the lines of:

```
# Let newSamplesOrder be a character vector with the desired order for your samples
Muru=loadSQM('Muru')
ta = mostAbundant(Muru$taxa$family$percent, others=T)
ta = ta[,newSamplesOrder]
plotBars(ta)
```

**Comment by QQ8488** [comment]
Thanks Fernando,

It is SqueezeMeta v1.2.  

I don't know why the engine argument does not work. 

Thanks a lot,
Qian

**Comment by QQ8488** [comment]
Thanks Fernando, 

Could you please send a link to download the new version (0.5.3)?

Thanks a lot,
QQ

**Comment by fpusan** [comment]
Download the develop branch from here (https://github.com/jtamames/SqueezeMeta/archive/develop.zip) and follow the instructions from my last message.

**Comment by QQ8488** [comment]
Thanks much! 

It is brilliant! 

plotTaxonomy works now!

In the tutorial, there is a function. 
# 2.4.2. Export Krona
    #    exportKrona(Hadza)

When I ran this function, there was an error.  
Error in exportKrona(Muru) : 
  ktImportText (from KronaTools) is not present in your PATH. KronaTools can be downloaded from https://github.com/marbl/Krona
In addition: Warning message:
In system("ktImportText", ignore.stdout = T, ignore.stderr = T) :
  error in running command

Do I need to download the Krona, and build a _Krona_ package for r?

Thanks a lot,
QQ

**Comment by fpusan** [comment]
Yes, you have to download and install Krona from that direction. No need to build an R package, but the Krona executables must be available on your PATH.

**Comment by QQ8488** [comment]
Thanks Fernando!

**Comment by fpusan** [comment]
Closing since it seems solved, feel free to reopen if that's not the case
