### ISSUE TITLE
huge proportion of unclassified

### ISSUE THREAD

**Issue by QQ8488** [jtamames/SqueezeMeta#157]
Hello, 

I conducted my metagenomics data by using SqueezeMeta and further analyzed the data by using SQMtools.

When I checked the results, I found that there is a huge proportion of unclassified results.   
I don't know where the huge "unclassified" came from. It does not make sense to me. 

Here I attached the command using in SqueezeMeta and the results from SQMtools. 
SqueezeMeta.pl -m coassembly -p Muru -s fileName.samples -f Muru --cleaning --nopfam --D -miniden 60 -e 1e-5

Could someone help? 

Thanks a lot,
QQ

**Comment by fpusan** [comment]
Hi!
When loading the data with `loadSQM` can you add the flag `tax_mode = "prokfilter"` and see if it improves?
`Muru = loadSQM("/path/to/the/project", tax_mode = "prokfilter")`

**Comment by jtamames** [comment]
Hello
What kind of sequencing did you do? Could you send us the `syslog` file, and also the `22.*.stats` file?

**Comment by QQ8488** [comment]
Hello All, 

I added the flag tax_mode = "prokfilter", and it did not improve (see attached).
There was a warning.
Warning message:
In loadSQM("Murulee", tax_mode = "prokfilter") :
      There are no PFAM results in your project. Skipping... 


We used shotgun metagenomic sequencing.  I also attached "syslog"  and "22.*.stats"


It does not make sense to me that there are huge "unclassified" by using Shotgun approach. 

Did I miss something when I performed the data?


Thanks much for the help. 

Sincerely,
QQ.
[Archive.zip](https://github.com/jtamames/SqueezeMeta/files/5201558/Archive.zip)

**Comment by jtamames** [comment]
But which instrument did you use? it was Illumina, MinION?

**Comment by QQ8488** [comment]
We used Illumina.

**Comment by QQ8488** [comment]
Thanks much Javier, 

I will start a new project.   Here is the command. 
What do you think if it makes sense?
I also use -e 1e-5,  will it be too strict?
SqueezeMeta.pl -m coassembly -p Muru_new -s fileName.samples -f Muru --cleaning --euk --D -miniden 60 -e 1e-5  -extassembly /PATH/results/01.Muru.fasta

Thanks a lot,
QQ

**Comment by jtamames** [comment]
The command line looks good. Notice that miniden at 60% and evalue at 1e-5 both will reduce the number of usable hits. Hence you will have more orphans. I didn't notice that you were using these settings before but it is a likely explanation for having more unclassified ORFs. I think you can safely use default values for incresaing the number of annotations.
Best,
Javier

**Comment by QQ8488** [comment]
Thanks Javier. 

I follow your suggestion, use the default,  and remove _-miniden 60 -e 1e-5._  
I will also update the results once the new project is done. 

Thanks a lot,
QQ

**Comment by QQ8488** [comment]
Hi Javier, 

I also have an additional questions related to prokaryotes.

Including bacteria and archaea, is it also possible to target _algae, and blue-green bacteria_. in "prokaryotes"?

Thanks a lot,
QQ

**Comment by fpusan** [comment]
Hi!
The best way to study subsets of taxa would be to run SqueezeMeta normally, load it in R using SQMtools and then use the `subsetTax` method.
Find more information in our [paper](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-020-03703-2) and in the [wiki](https://github.com/jtamames/SqueezeMeta/wiki/Using-R-to-analyze-your-SQM-results).

**Comment by QQ8488** [comment]
Thanks Fernando, 

I read through your paper and wiki. I have several questions.

1. Did you rarefy/normalize your data when you produce Figure 2.B&C in your paper? When I check the wiki, I did not find this step.  Also, I do not find the step to generate the ellipse in this Figure 2B&C.

2.  do you have arguments in plotFunctions() to generate the Figure 3.C in your paper? Looks like you adjusted the font and legends in the paper.  Or you adjusted the font manually. 

Thanks a lot,
QQ

**Comment by ggnatalia** [comment]
Hi!

1. To produce Figure 2B, we use the information in Hadza$taxa$genus$percent. You can find the code in the Supplementary Material of the paper. To plot the ellipses, you just need to add the last line to the code:

```R
    library('vegan')
    # Metadata is a data.frame whose rownames are the sample names, and each column is a vector of factors.
    # E.g. In this example, the factor (condition) is the country: Hadza or Italy
    metadata = as.data.frame(c(rep('Hadza', 8), rep('Italy', 8)))
    rownames(metadata) = colnames(Hadza$taxa$genus$percent)
    colnames(metadata) = 'condition'
    # Transpose the matrix to have samples in rows.
    genus_pc = t(Hadza$taxa$genus$percent)
    MDS = metaMDS(genus_pc)
    colvec = c('#006682','#c26e00') # colors
    plot(MDS, display = 'sites')
    with(metadata, points(MDS, display = 'sites', col = colvec[condition], pch = 19))
    with(metadata, legend('topright', legend = levels(condition), col = colvec, pch = 21, pt.bg = colvec))

    with(metadata, ordiellipse(MDS, condition, col = colvec, alpha = 70, draw = 'polygon', border = colvec)) # Plot the ellipse
````

In the case of Figure 2C, is the same procedure. We use the table Hadza$functions$KEGG$tpm:

```R
    library('vegan')    
    metadata = as.data.frame(c(rep('Hadza', 8), rep('Italy', 8)))
    rownames(metadata) = colnames(Hadza$functions$KEGG$tpm)
    colnames(metadata) = 'condition'
    # Transpose the matrix to have samples in rows.
    kegg_tpm = t(Hadza$functions$KEGG$tpm)
    MDS = metaMDS(kegg_tpm)
    colvec = c('#006682','#c26e00') # colors
    plot(MDS, display = 'sites')
    with(metadata, points(MDS, display = 'sites', col = colvec[condition], pch = 19))
    with(metadata, legend('topright', legend = levels(condition), col = colvec, pch = 21, pt.bg = colvec))

    with(metadata, ordiellipse(MDS, condition, col = colvec, alpha = 70, draw = 'polygon', border = colvec)) # Plot the ellipse

```

2. In Figure 3.C, you can adjust the font size using the option "base_size" in plotFunctions (as well as in plotTaxonomy). Also, we manually add colors to the x-axis according to the origin of the sample and asterisks based on the results of DESEQ2.


I hope this helps you,

Natalia

**Comment by QQ8488** [comment]
Thanks Natalia!

QQ

**Comment by QQ8488** [comment]
Hey Javier,

I followed your suggestion to re-run the project. 
Finally, it is done. 
When I check the new result, looks like it does not change much. 
Do you have any idea about it? 
Here is the command that I used. 
SqueezeMeta.pl -m coassembly -p Muru_new -s fileName.samples -f Muru --cleaning --euk --D -extassembly /PATH/results/01.Muru.fasta

I also attached the figures (new vs old superkingdom).

Thanks a lot,
QQ
[New_Superkingdom.pdf](https://github.com/jtamames/SqueezeMeta/files/5252848/New_Superkingdom.pdf)
[Old_superkingdom_percent.pdf](https://github.com/jtamames/SqueezeMeta/files/5252849/Old_superkingdom_percent.pdf)

**Comment by jtamames** [comment]
Hello
And the number of orphans, is it the same before and after? Could I see your 22.stats files, both of them?
Best,

**Comment by QQ8488** [comment]
Hey Javier,

Here you go. 

[old.22.Muru.stats.txt](https://github.com/jtamames/SqueezeMeta/files/5257086/old.22.Muru.stats.txt)
[new.22.Muru_new.stats.txt](https://github.com/jtamames/SqueezeMeta/files/5257087/new.22.Muru_new.stats.txt)

Thanks a lot,
QQ.

**Comment by jtamames** [comment]
Ok ok... So the number of orphans is almost exactly the same... which was not expected.

Looking into this I have spotted a bug in `SqueezeMeta.pl` that ignores the effect of the `miniden` and `evalue` parameters in command line. So basically when you run the pipeline with your custom values, the pipeline is running with default values. That explains why there is no difference between your old and new results. The settings are the same for both.

So thank you for giving us the chance to find this one bug! I am attaching here a modified SqueezeMeta.pl that fixes the bug and admits custom values for identity and evalue. We will release this one asap.

And regarding your question on orphans, I guess it is hard to (safely) improve the number of annotations. You can try to decrease further the requirements, but I wouldn't recommend it.

Best,
Javier
[SqueezeMeta.pl.gz](https://github.com/jtamames/SqueezeMeta/files/5262315/SqueezeMeta.pl.gz)

**Comment by QQ8488** [comment]
Hey Javier, 

Thank you for the feedback. 

Looks like I need to replace this updated SqueezeMeta.pl to my old one.  Is it correct?

So,  both of results were conducted by the same parameters (default values);  
Looks like I can't fix the huge "unclassified". Am I right?  


Thanks a lot,
QQ

**Comment by jtamames** [comment]
Hello
Yes, that's correct. Replace the old one with this one.

I insist: you don´t have a "huge" number of unclassified. You have a normal number of unclassified. You can find similar resuls in other metagenomic datasets (not analyzed by SqueezeMeta, btw), like these ones:

https://pubmed.ncbi.nlm.nih.gov/22772835
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4508852

Of course we all would like to have 100% of classified sequences, but every technique has limitations, and these are the ones of metagenomics.

Best,
Javier

**Comment by QQ8488** [comment]
Hey Javier,

I really appreciated your help and explanation! 

Thanks a lot,
QQ.
