### ISSUE TITLE
Error on step 1

### ISSUE THREAD

**Issue by jilldv** [jtamames/SqueezeMeta#158]
Hello,

At step 1 I got this error:

sh: 1: cannot create ./transcriptomics/intermediate/01./home/jill/transcriptomics/squeezemeta/transcriptomics.stats: Directory nonexistent
Error running command:    /home/bioadmin/Downloads/squeezeMeta/SqueezeMeta-1.0.0/bin/prinseq-lite.pl -fasta ./transcriptomics/results/01.transcriptomics.fasta -stats_len -stats_info -stats_assembly > ./transcriptomics/intermediate/01./home/jill/transcriptomics/squeezemeta/transcriptomics.stats at /home/bioadmin/Downloads/squeezeMeta/SqueezeMeta-1.0.0/scripts/01.run_assembly.pl line 98.
Stopping in STEP1 -> 01.run_assembly.pl (megahit)

I looked in the code but I can't figure out what the problem might be. Can someone help me with this error?

**Comment by jtamames** [comment]
Hello
I am almost sure that you put a full path (/home/jill/transcriptomics/squeezemeta/transcriptomics) as project name. Could you copy your command line for verifying it?
The project name must be just a name, any characters but blank spaces or slashes.
Best,
Javier

**Comment by jilldv** [comment]
This is my command line

/home/bioadmin/Downloads/squeezeMeta/SqueezeMeta-1.0.0/scripts/SqueezeMeta.pl -m coassembly -p transcriptomics -s transcriptomics.samples -f /home/jill/transcriptomics
/raw_data --cleaning -cleaning_options 'SLIDINGWINDOW:10:15 MINLEN:50 ILLUMINACLIP:/usr/bin/Trimmomatic-0.38/adapters/TruSeq2-PE.fa:2:30:10'

I just used the name transcriptomics as project name, maybe it's because that's also the name of a folder earlier in the path?

**Comment by jtamames** [comment]
Looks good... Could you please copy your syslog file?

**Comment by jilldv** [comment]
The syslog file

SqueezeMeta v1.2.0 - (c) J. Tamames, F. Puente-Sánchez CNB-CSIC, Madrid, SPAIN

Please cite: Tamames & Puente-Sanchez, Frontiers in Microbiology 10.3389 (2019). doi: https://doi.org/10.3389/fmicb.2018.03349

Run started Wed Sep  9 12:57:55 2020 in coassembly mode
Command: /home/bioadmin/Downloads/squeezeMeta/SqueezeMeta-1.0.0/scripts/SqueezeMeta.pl -m coassembly -p transcriptomics -s transcriptomics.samples -f /home/jill/transcriptomics/raw_data --cleaning -cleaning_options SLIDINGWINDOW:10:15 MINLEN:50 ILLUMINACLIP:/usr/bin/Trimmomatic-0.38/adapters/TruSeq2-PE.fa:2:30:10
Project: transcriptomics
Map file: transcriptomics.samples
Fastq directory: /home/jill/transcriptomics/raw_data
Options: threads=12; contiglen=200; assembler=megahit; mapper=bowtie; evalue=; miniden=; COGS; KEGG; PFAM; EXT_DB: /home/jill/transcriptomics/squeezemeta;
[0 seconds]: STEP0 -> SqueezeMeta.pl
[9 seconds]: STEP1 -> 01.run_assembly.pl (megahit)

**Comment by jtamames** [comment]
What happens if you change the project name to transcriptomics2 and run the pipeline again?

**Comment by jilldv** [comment]
I changed the project name and run it again. So this is my new command

/home/bioadmin/Downloads/squeezeMeta/SqueezeMeta-1.0.0/scripts/SqueezeMeta.pl -m coassembly -p transcriptomics2 -s transcriptomics.samples -f /home/jill/transcriptomic
s/raw_data --cleaning -cleaning_options 'SLIDINGWINDOW:10:15 MINLEN:50 ILLUMINACLIP:/usr/bin/Trimmomatic-0.38/adapters/TruSeq2-PE.fa:2:30:10'

But I still got the same error

sh: 1: cannot create ./transcriptomics2/intermediate/01./home/jill/transcriptomics/squeezemeta/transcriptomics2.stats: Directory nonexistent
Error running command:    /home/bioadmin/Downloads/squeezeMeta/SqueezeMeta-1.0.0/bin/prinseq-lite.pl -fasta ./transcriptomics2/results/01.transcriptomics2.fasta -stats_len -stats_info -stats_assembly > ./transcriptomics2/intermediate/01./home/jill/transcriptomics/squeezemeta/transcriptomics2.stats at /home/bioadmin/Downloads/squeezeMeta/SqueezeMeta-1.0.0/scripts/01.run_assembly.pl line 98.
Stopping in STEP1 -> 01.run_assembly.pl (megahit)

**Comment by QQ8488** [comment]
Hi Jilldv, 

I can share my experiences to figure out the first step problem. 

1. Test if you can run through the demo data
2. Make sure the format of the sample.file as the same as the tutorial.
3. How big is your raw data? If your data is huge,  make your PC/ working system have enough memory. 

Hope it helps.

**Comment by jtamames** [comment]
Hello
Could you please send to me the file `SqueezeMeta_conf.pl` that is in the project directory?
Also, I am puzzled because the line in which the script dies (line 98) does not correspond to a line in which it could die. Dis you modified the script? Could you also send it to me, your 01.run_assembly.pl in the scripts directory?
Best,
Javier

**Comment by jilldv** [comment]
[SqueezeMeta_conf.pl.txt](https://github.com/jtamames/SqueezeMeta/files/5219463/SqueezeMeta_conf.pl.txt)
[01.run_assembly.pl.txt](https://github.com/jtamames/SqueezeMeta/files/5219480/01.run_assembly.pl.txt)

I didn't modify the script, so normally it should be the original one.

**Comment by jtamames** [comment]
OK, could it be that you had a previous version of SqueezeMeta (1.0.0) and tried to update it to 1.2.0? The 01.run_assembly.pl is very old, and the paths in SqueezeMeta_conf.pl point to version 1.0.0

Anyway, I think the best solution is to reinstall SqueezeMeta. Download the latest version and install it. If you downloaded the databases, you don't need to do it again, but remember to run the `configure_nodb.pl` script in the `utils/install_utils` directory

Best,
Javier

**Comment by jilldv** [comment]
I installed SqueezeMeta using conda now and the assembly step runned without any problems. But now I get an error message running barrnap:

Running barrnap (Seeman 2014, Bioinformatics 30, 2068-9) for predicting RNAs:  Bacteria[17:06:39] Can't find database: /media/disk7/fer/SqueezeMeta/db/bac.hmm
Error running command:    /home/jill/.conda/envs/SqueezeMeta/SqueezeMeta/bin/barrnap --quiet --threads 12 --kingdom bac --reject 0.1 /home/jill/transcriptomics/squeezemeta/transcriptomicsT1/intermediate/02.transcriptomicsT1.maskedrna.fasta --dbdir /media/disk7/fer/SqueezeMeta/db > /home/jill/transcriptomics/squeezemeta/transcriptomicsT1/temp/bac.gff at /home/jill/.conda/envs/SqueezeMeta/SqueezeMeta/scripts/02.rnas.pl line 54.
Stopping in STEP2 -> 02.rnas.pl

I got no error message during the installation of SqueezeMeta, so I would think all the databases have been downloaded. 
Do you have any idea or suggestion what might be the problem now?

Thank you for the help

**Comment by jtamames** [comment]
Hello

Can you run the `configure_nodb.pl` script in the `utils/install_utils` directory, and see if that solves the problem?

Best,

**Comment by jilldv** [comment]
Stupid question, but where can I find `/path/to/db` needed to run `configure_nodb.pl`? I am quite new to all this

**Comment by jilldv** [comment]
I runned the `configure_nodb.pl` script and got this output `Usage: perl install_nodb.pl <database dir>`
Then I restarted the squeezemeta run using this command:
restart.pl transcriptomicsT1 -step 2
But I got the same error message

**Comment by jtamames** [comment]
It is the directory in which you downloaded the databases. If you don´t remember it, try using the unix find command:

`find . -name "bac.hmm" -print`

That would look in the directory where you are and all the directories below it, so you can try running it from your home directory.

The database directory would be the one in which `bac.hmm` was found. Give that to `configure_nodb.pl`

**Comment by jtamames** [comment]
You will also need to set up properly the database directory in the SqueezeMeta_conf.pl in the project directory. For making it easier, I reccomend you to use your existing assembly (should be in `transcriptomicsT1/results/01.transcriptomicsT1.fasta`). Just start a new run providing that file using the `-extassembly` option. You would need to use a new project name. 

Best,

**Comment by jilldv** [comment]
I have run the `configure_nodb.pl` script and started a new run. Everything seems to be working now.
Thank you for all the help!
