### ISSUE TITLE
Error running --cleaning argument

### ISSUE THREAD

**Issue by 3ccasto** [jtamames/SqueezeMeta#160]
I tried to perform the cleanning of my samples directly with Squeeze. However the program gave me the error:
ERROR: input file for -fasta is in UNKNOWN format not in FASTA format.

I run the command line:
$SQUEEZEDIR/scripts/SqueezeMeta.pl -p maternos -m seqmerge -s samples_SG.txt -f $FILTERDIR -t 15 -b 30 --cleaning --nopfam --nocog

And my sample file has the following format:
SM002365-10_S10 SM002365-10_S10_filter_R2.fastq.gz      pair2
SM002365-11_S11 SM002365-11_S11_filter_R1.fastq.gz      pair1

prinseq-lite.pl allows compressed files, so I do not know what is happening.

**Comment by fpusan** [comment]
Hi!

After checking the syslog you sent me via email, it seems that prinseq crashes because you are not getting any contigs, and you are not getting any contigs because you are not actually inputing any reads to megahit.

So either:
1) Your input files were empty from the beginning.
2) There was an error when merging your input files.
3) Trimmomatic removed all your reads.

Can you run the following command `tree -hD maternos` so we can look at all the files present in your project directory?

**Comment by 3ccasto** [comment]
How exactly do I have to run this command?

**Comment by fpusan** [comment]
Is a unix command. Just go to `/SCRATCH/cricasre/MERGE_MATERNO/` and run it there.

**Comment by 3ccasto** [comment]
It's gave me the error "command not found". I executed it directly in the console and in the node of CENTOS7 and the error was the same.

**Comment by fpusan** [comment]
Then it is not installed in your system. Can you get it installed (maybe via conda?) or should we look for another solution?

**Comment by 3ccasto** [comment]
Here I have attached the file with the output of the command. I installed it with conda, as you said me.
[tree_maternos.txt](https://github.com/jtamames/SqueezeMeta/files/5217872/tree_maternos.txt)

**Comment by fpusan** [comment]
Thanks! Can you also run
`ls -ltrh /SCRATCH/cricasre/MERGE_MATERNO/host_filter/` and let us know?

**Comment by 3ccasto** [comment]
Here is the file!
[ls_maternos.txt](https://github.com/jtamames/SqueezeMeta/files/5217907/ls_maternos.txt)

**Comment by fpusan** [comment]
```
total 768K
-rw-rw-r-- 1 cricasre gente 60 Sep  9 18:05 SM002365-31_S31_filter_R2.fastq.gz
-rw-rw-r-- 1 cricasre gente 60 Sep  9 18:05 SM002365-31_S31_filter_R1.fastq.gz
-rw-rw-r-- 1 cricasre gente 60 Sep  9 18:05 SM002365-32_S32_filter_R2.fastq.gz
-rw-rw-r-- 1 cricasre gente 60 Sep  9 18:05 SM002365-32_S32_filter_R1.fastq.gz
-rw-rw-r-- 1 cricasre gente 60 Sep  9 18:05 SM002365-15_S15_filter_R2.fastq.gz
-rw-rw-r-- 1 cricasre gente 60 Sep  9 18:05 SM002365-15_S15_filter_R1.fastq.gz
-rw-rw-r-- 1 cricasre gente 60 Sep  9 18:05 SM002365-30_S30_filter_R2.fastq.gz
-rw-rw-r-- 1 cricasre gente 60 Sep  9 18:05 SM002365-30_S30_filter_R1.fastq.gz
-rw-rw-r-- 1 cricasre gente 60 Sep  9 18:07 SM002365-71_S71_filter_R2.fastq.gz
[...]
```

It would seem that the files are empty (or at least very small)... is that the case?

**Comment by 3ccasto** [comment]
I think that something was wrong when I filtered the host. I had 288 GB in the raw samples and then only 768 Kb. I will check and run Squeeze again. Thanks! =)

**Comment by fpusan** [comment]
Sure! Closing issue
