### ISSUE TITLE
Selecting table in SQMtools

### ISSUE THREAD

**Issue by rissidaniel** [jtamames/SqueezeMeta#162]
Dear Javier,

How can I select this table in the SQMtools?

Hadza$orfs$table$Gene name

> exportTable(Hadza$orfs$table$Gene name, "gene_name.tsv")
Fehler: unerwartetes Symbol in "exportTable(Hadza$orfs$table$Gene name"

I believe that because of the space between "Gene" and "name" I am not being able to export this specific table

**Comment by fpusan** [comment]
Hi,
Either
```
Hadza$orfs$table$`Gene name`
```
or
```
Hadza$orfs$table[,"Gene name"]
```
Best,
Fernando
