### ISSUE TITLE
sqm_longreads.pl output tables include same orf multiple times

### ISSUE THREAD

**Issue by mirimarine** [jtamames/SqueezeMeta#166]
Hi,
I used the sqm_longreads.pl script to simultaneously analyse PacBio reads of 4 different samples.
At first, everything seemed fine, the syslog reported “Normal termination, all good apparently”.
When I was going through the results, I realized that some orfs (but not all) are included multiple times in the resulting tables (out.allreads) each time apparently originating from a different sample.

For example orf “m64078_200820_142428/101580823/ccs_1-691”:
Table out.allreads:
SampleI 4656_I_CCS.fastq m64078_200820_142428/101580823/ccs_1-691 c_Deltaproteobacteria COG1348* K02588
SampleL 4656_I_CCS.fastq m64078_200820_142428/101580823/ccs_1-691 c_Deltaproteobacteria COG1348 K02588
SampleR 4656_I_CCS.fastq m64078_200820_142428/101580823/ccs_1-691 c_Deltaproteobacteria COG1348 K02588
SampleO 4656_I_CCS.fastq m64078_200820_142428/101580823/ccs_1-691 c_Deltaproteobacteria COG1348 K02588

The respective read originates from SampleI.
As far as I can tell, these “false occurrences” are also counted and included in the out.allreads.funcog and out.allreads.funkegg tables.

I used SqueezeMeta version 1.2:
sqm_longreads.pl -p msm89_lr -s samplesfile -f ../01_rawreads -t 50 –euk

The samplesfile looks like this:
SampleI 4656_I_CCS.fastq pair1
SampleL 4656_L_CCS.fastq pair1
SampleR 4656_R_CCS.fastq pair1
SampleO 4656_O_CCS.fastq pair1

Please let me know if you need any additional information.

All the best and thank you for your help,
Miriam

**Comment by jtamames** [comment]
Hello Miriam
That's weird... I will check it out. Probably I will be ask you for some additional information when I have a clear idea of the possible problem here.
Thanks for reporting!
Best,
Javier

**Comment by jtamames** [comment]
Hello!

Sorry for taking so long, I was pretty busy the last week and had no time to check this one. Indeed there was a bug producing duplicate counts in the summaries of `sqm_longreads.pl`. I fixed it now and upload the fix to the branch `develop`. Could you please replace your `sqm_longreads.pl` with that one (the one in `develop` branch) and rerun the results? When you run it, add the flag `--nodiamond` to avoid running the homology searches again.

Thanks for reporting this one, you helped us a lot!
Best,
Javier

**Comment by mirimarine** [comment]
Hi Javier,

Thank you for looking into it.
I will rerun the the analysis with the new script and let you know how it went.

All the best,
Miriam

**Comment by mirimarine** [comment]
Hi Javier,
I did the longread analysis with the new sqm_longreads.pl script.
Everything looks good now and I couldn't find any duplicates any more.
Thanks a lot for your help.
All the best,
Miriam

**Comment by jtamames** [comment]
Great news! Thanks for reporting.
Best,
Javier
