### ISSUE TITLE
Error on step 1

### ISSUE THREAD

**Issue by oyac** [jtamames/SqueezeMeta#17]
Hello, 
I was recently running the pipeline and got this error:

sh: 1: cannot create /01.EPS_1.stats: Permission denied
Error running command:    /mnt/nfs/bioinfdata/home/NIOO/ohanac/squeezem/SqueezeMeta/scripts/../bin/prinseq-lite.pl -fasta /mnt/nfs/bioinfdata/home/NIOO/ohanac/squeezem/dbs/sPS_1/results/01.EPS_1.fasta -stats_len -stats_info -stats_assembly > /01.EPS_1.stats at /mnt/nfs/bioinfdata/home/NIOO/ohanac/squeezem/SqueezeMeta/scripts/../scripts/01.run_ably.pl line 98.
Stopping in STEP1 -> 01.run_assembly.pl (megahit)

I did a git pull to run the pipeline again in my samples (sequential mode), since I`d like to use the
script  sqm2tables.py and summarize my results, but I had this error.

Thanks, 
Ohana

**Comment by fpusan** [comment]
Dear Ohana,

Apart from doing the git pull, did you run the *configure_nodb.pl* script as described in the "Updating SqueezeMeta" section of the ReadMe?

If you did, and it's still not working, could you send us the SqueezeMeta_conf.pl that is present inside the project folder?

Also, currently the sqm2tables.py script won't work in the sequential mode. Merged or coassembly modes should be ok. 

The sequential mode will run SqueezeMeta on each of your samples, but will not merge the results. If you really need to use it, you could run the sqm2tables.py independently for each of your samples, and combine the resulting tables.

**Comment by oyac** [comment]
Dear Fernando, 

It worked, thanks! But then I got a new error:
STEP13 -> CREATING GENE TABLE: 13.mergeannot2.pl
Reading GFF in /mnt/nfs/bioinfdata/home/NIOO/ohanac/squeezem/dbs/sip/EPS_1/results/03.EPS_1.gff
Reading Diamond hits
Can't open /mnt/nfs/bioinfdata/home/NIOO/ohanac/squeezem/dbs/sip/EPS_1/temp/08.EPS_1.nr.blastx.collapsed.merged.m8
Stopping in STEP13 -> 13.mergeannot2.pl

It seems that it skipped script/step 8:

STEP7 -> FUNCTIONAL ASSIGNMENT: 07.fun3assign.pl
Assigning COGS KEGG PFAM
[4 hours, 50 minutes, 3 seconds]: STEP9 -> CONTIG TAX ASSIGNMENT: 09.summarycontigs3.pl

Here is my conf file.
Thanks
Ohana

[SqueezeMeta_conf.pl.txt](https://github.com/jtamames/SqueezeMeta/files/3117895/SqueezeMeta_conf.pl.txt)

**Comment by fpusan** [comment]
*Mea culpa*

Step 8 was skipped because you didn't request the doublepass mode, so that part is fine.
However the 13.mergeannot2.pl was wrongly expecting those results due to a quite recent patch I pushed...

Please pull the latest version from master and restart the project from step 13. Let me know if you experience further errors.

**Comment by oyac** [comment]
I did git pull, and it worked, but then: (i am running in sequential mode)

[44 seconds]: STEP20 -> CREATING CONTIG TABLE: 20.getcontigs.pl
Reading taxa for contigs information...done!
Reading GC & length... done!
Reading number of genes... done!
Reading coverages... done!
Reading bins... Can't open /mnt/nfs/bioinfdata/home/NIOO/ohanac/squeezem/dbs/sip/EPS_1/intermediate/19.EPS_1.contigsinbins
Stopping in STEP20 -> 20.getcontigs.pl

Cheers,
Ohana

**Comment by fpusan** [comment]
Similar issue, the binning file won't be there because no bins are generated in sequential mode.
Should be fixed now, let me know if it works

**Comment by fpusan** [comment]
(git pull the latest commit)

**Comment by oyac** [comment]
Dear Fernando, 

It worked, thanks! However, after finishing the analysis of sample 1, it stopped. Shouldn`t it continue with the analysis of the other samples? I have twelve, and when the run started, it found 12 metagenomes.

Thanks, 
Ohana

**Comment by fpusan** [comment]
Right now, using restart in the sequential mode only finishes the current metagenome. Please launch again SqueezeMeta with the remaining samples, it should go through all of them in one go.

**Comment by oyac** [comment]
Hi, It`s working, thanks! 
I also used the script sqm2tables.py script in the sample that finished and it`s also fine. 
Cheers, 
Ohana

**Comment by fpusan** [comment]
Excellent, closing issue and thanks for reporting! :)
