### ISSUE TITLE
[Regarding SQMtools] Error in loadSQM......: An error occurred while running sqm2tables.py

### ISSUE THREAD

**Issue by razz1618** [jtamames/SqueezeMeta#170]
Hi,
I have finished the squeezemeta pipeline with binning on my lab server. Next, to analyze in SQMtools, I compressed the sqmtools directory from "install path/SqueezeMeta/lib/SQMtools" and installed it In Rstudio on my personal PC with all the dependencies  (as on the server I do not have sudo rights). Next, I copied the whole squeezemeta created project (named as original_bottle) except the temp, data, and raw fastq files directory to the desired location on my personal PC (i.e. /home/ahail/Documents/squeezemeta_analysis/original_bottle), 

When I run (in Rstudio), 
Hadza = loadSQM('/home/ahail/Documents/squeezemeta_analysis/original_bottle')

I get the following error:

**Error in loadSQM("/home/ahail/Documents/squeezemeta_analysis/original_bottle") : An error occurred while running sqm2tables.py**
**2.stop("An error occurred while running sqm2tables.py")**
**1.loadSQM("/home/ahail/Documents/squeezemeta_analysis/original_bottle")**

I did not find the sqm2tables.py in sqmtools R package (to debug the problem). 

Here, is the list of all files in my squeezementa project (original_bottle) copied to my personal PC
[original_bottle.txt](https://github.com/jtamames/SqueezeMeta/files/5359010/original_bottle.txt)

**Comment by fpusan** [comment]
Hi!
- You don't really need sudo rights to install SQMtools.
- If you are analyzing your project in a different computer, make sure to run sqm2tables.py before in your lab server in this way:
`sqm2tables.py <PROJECT> <PROJECT>/results/tables`. Then copy the project directory to the second computer (you can indeed  skip the temp, data, and raw_fastq directories as they are not used by SQMtools) and you should be good to go!

**Comment by razz1618** [comment]
Thanks, prompt reply. That's, the point I missed regarding first running sqm2tables.py.
Yes, for Installing SQMtools itself doesn't require administrative privileges but the dependency package Pathview requires XML package to be installed which prerequisites some Linux files (libtool-ltdl) which require root/sudo access to install (somehow our lab server do not have this files. i will talk with the server manager guy and next time can directly use sqmtools on the server).

Thanks:thumbsup::thumbsup::thumbsup:

**Comment by fpusan** [comment]
Alternatively, if you install it via conda SQMtools should be ready to go, all libraries included. If it isn't, then let me know!

**Comment by razz1618** [comment]
Does that mean i do not need to install it on R?  I have installed squeezemeta via conda, which working good.

**Comment by fpusan** [comment]
1. No, and it is not planned on the short term. I'm not familiar with the biom format myself, what would it be needed?
2. plotTaxonomy is not a ggplot2 function, just a wrapper around a ggplot function. So if you want custom plots you'll have to make them yourself. However we slowly add more customization options, custom widths might as well be the next one. Maybe next week we can squeeze (heh) some time for that.

**Comment by razz1618** [comment]
That's awesome, looking forward to the next update. Thanks.
RAegarding biom file..It is not that necessary. ..some R visualization packages start with biom file. But I can make it if necessary ,as sqeezemeta have already provided with nice taxa tables.
