### ISSUE TITLE
Error loading run into SQMtools

### ISSUE THREAD

**Issue by seppedm** [jtamames/SqueezeMeta#171]
Hi there,

I'm trying to load a completed SqueezeMeta run into SQMtools, where I get the following error. 

 > testT1 <- loadSQM("/home/seppe/squeezemeta/run2")
 Loading orfs
     table...
     abundances...
     sequences
     taxonomy...
 Loading contigs
     table...
     abundances...
     sequences...
     taxonomy...
     binning info...
 Loading bins
     table...
     abundances...
     taxonomy...
 Loading taxonomies
 Loading functions
 Loading total reads
 Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
   line 14 did not have 5 elements

With the following traceback in RStudio:

>4 | scan(file = file, what = what, sep = sep, quote = quote, dec = dec, nmax = nrows, skip = 0, na.strings = na.strings, quiet = TRUE, fill = fill, strip.white = strip.white, blank.lines.skip = blank.lines.skip, multi.line = FALSE, comment.char = comment.char, allowEscapes = allowEscapes, ...
>3 | read.table(sprintf("%s/results/10.%s.mappingstat", project_path, project_name), header = T, sep = "\t", row.names = 1, skip = 1, comment.char = "")
>2 | as.matrix(read.table(sprintf("%s/results/10.%s.mappingstat", project_path, project_name), header = T, sep = "\t", row.names = 1, skip = 1, comment.char = ""))
>1 | loadSQM("/home/seppe/squeezemeta/run2")

Does anyone have an idea what would be the cause? Thanks in advance!

**Comment by seppedm** [comment]
With the following traceback in RStudio:

4 | scan(file = file, what = what, sep = sep, quote = quote, dec = dec,      nmax = nrows, skip = 0, na.strings = na.strings, quiet = TRUE,      fill = fill, strip.white = strip.white, blank.lines.skip = blank.lines.skip,      multi.line = FALSE, comment.char = comment.char, allowEscapes = allowEscapes,  ...
3 | read.table(sprintf("%s/results/10.%s.mappingstat", project_path,      project_name), header = T, sep = "\t", row.names = 1, skip = 1,      comment.char = "")
2 | as.matrix(read.table(sprintf("%s/results/10.%s.mappingstat",      project_path, project_name), header = T, sep = "\t", row.names = 1,      skip = 1, comment.char = ""))
1 | loadSQM("/home/seppe/squeezemeta/run2")

**Comment by fpusan** [comment]
Hi! We've had a bug like that in the past, but it should be fixed by now.
- What version of SqueezeMeta/SQMtools are you using? 
- Can you send me the `/home/seppe/squeezemeta/run2/results/10.run2.mappingstat` file?

**Comment by seppedm** [comment]
Somehow I indeed had an old SQMtools version, I managed to update it and this solved my problem. Sorry to bother you with such a basic problem and thanks for the reminder!
