### ISSUE TITLE
Megahit - error STEP 1

### ISSUE THREAD

**Issue by EricRaes** [jtamames/SqueezeMeta#173]
Hey guys,

Hope you are having a good week, and you are all well.

I am running through the pipeline with 20 paired 150bp shotgun samples and run into the attached Megahit error.

Stopping in STEP1 -> 01.run_assembly.pl (megahit)
Died at ~/.conda/envs/SqueezeMeta/SqueezeMeta/scripts/SqueezeMeta.pl line 612.

Would you have ideas?

Many thanks in advance!!
Best regards,
Eric

[megahit_log.txt](https://github.com/jtamames/SqueezeMeta/files/5364858/megahit_log.txt)
[syslog.txt](https://github.com/jtamames/SqueezeMeta/files/5364862/syslog.txt)

ps. sorry forgot to say I did a clean conda install this morning

**Comment by EricRaes** [comment]
Sorry, I see memory issue..I am rerunning the pipeline with 350Gb and 12 threads. Hopefully that would do it. Would you have any suggestions how to deal with the memory megahit error? Thanks a lot!

**Comment by EricRaes** [comment]
Apologies I should have framed my question as well. I would like to look at functional bacterial change (differential abundances) across a large latitudinal study. Hence I thought co-assembly would be a good idea. I understood that the memory requirements were automatically capped. Would you recommend (due to the high memory allocation using co-assembly) using the "merge" or "seqmerge" modes? Thanks again!

**Comment by jtamames** [comment]
Hello Eric
Yes, these should use less memory, especially the seqmerge. An user is having trouble with 50+ samples. I guess that with your 20 samples will be ok, but please be patient.
Best,
Javier
