### ISSUE TITLE
Stopping in STEP4 -> 04.rundiamond.pl

### ISSUE THREAD

**Issue by ARiou-zd** [jtamames/SqueezeMeta#175]
Hello,

I run for the first time SqueezeMeta and got the following error message : 
Setting block size for Diamond
  AVAILABLE (free) RAM memory: 12.53 Gb
  We will set Diamond block size to 2.5 (Gb RAM/5, Max 8).
  You can override this setting using the -b option when starting the project, or changing
  the $blocksize variable in SqueezeMeta_conf.pl
  Running Diamond (Buchfink et al 2015, Nat Methods 12, 59-60) for taxaError running command:    /home/ariou/anaconda3/envs/SqueezeMeta/SqueezeMeta/bin/diamond blastp -q /home/ariou/anaconda3/envs/SqueezeMeta/SqueezeMeta/database/test/Hadza/results/03.Hadza.faa -p 12 -d /home/ariou/anaconda3/envs/SqueezeMeta/SqueezeMeta/database/db/nr.dmnd -e 0.001 --id 40 -f tab -b 2.5 --quiet -o /home/ariou/anaconda3/envs/SqueezeMeta/SqueezeMeta/database/test/Hadza/intermediate/04.Hadza.nr.diamond at /home/ariou/anaconda3/envs/SqueezeMeta/SqueezeMeta/scripts/04.rundiamond.pl line 57.
Stopping in STEP4 -> 04.rundiamond.pl
Died at /home/ariou/anaconda3/envs/SqueezeMeta/bin/SqueezeMeta.pl line 711.

I don't know if it's because of the RAM memory (enough ?).

Any help/ideas are appreciated.
Thanks.

Antoine

**Comment by fpusan** [comment]
Yes, it might be because of the RAM memory, we routinely try it with 16Gb, but 12.5 Gb of free memory might be too low.
Try to launch SqueezeMeta again, adding the `-b 1` flag.

**Comment by ARiou-zd** [comment]
Thank you for your response. I have added RAM memory to reach 32 GB. The program worked until the end!

**Comment by fpusan** [comment]
Glad to hear it worked! Closing issue
