### ISSUE TITLE
Stopping in STEP10 -> 10.mapsamples.pl

### ISSUE THREAD

**Issue by tboonf** [jtamames/SqueezeMeta#179]
Thank you for sharing this amazing program with the community. I have recently run into one issue at step 10.
I received the following error when the analysis was half way through a few samples: 

Calculating contig coverage
Illegal division by zero at /home/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/10.mapsamples.pl line 376.
Stopping in STEP10 -> 10.mapsamples.pl
Died at /home/miniconda3/envs/SqueezeMeta/bin/SqueezeMeta.pl line 839.

**Comment by jtamames** [comment]
Hello
Could you please send us your `syslog` file please?

**Comment by tboonf** [comment]
Thanks for the quick support. Below is the message in syslog. I have tried with or without --map, but both gave me the same error message. 
###############################################################################
SqueezeMeta v1.2.0 - (c) J. Tamames, F. Puente-Sánchez CNB-CSIC, Madrid, SPAIN

Please cite: Tamames & Puente-Sanchez, Frontiers in Microbiology 10.3389 (2019). doi: https://doi.org/10.3389/fmicb.2018.03349

Run started Fri Oct  9 11:26:43 2020 in coassembly mode
Command: /home/miniconda3/envs/SqueezeMeta/bin/SqueezeMeta.pl -m coassembly -p ProjectReport2 -s mapping.samples -f Raw -a megahit -c 1000 -t 60 -map bwa
Project: ProjectReport2
Map file: mapping.samples
Fastq directory: /media/Project/trimmed/Raw
Options: threads=60; contiglen=1000; assembler=megahit; mapper=bwa; evalue=; miniden=; COGS; KEGG; PFAM; EXT_DB: /media/Project/trimmed;
[0 seconds]: STEP0 -> SqueezeMeta.pl
[25 minutes, 10 seconds]: STEP1 -> 01.run_assembly.pl (megahit)
[20 hours, 43 minutes, 17 seconds]: STEP2 -> 02.rnas.pl
[20 hours, 56 minutes, 21 seconds]: STEP3 -> 03.run_prodigal.pl
[22 hours, 35 minutes, 19 seconds]: STEP4 -> 04.rundiamond.pl
[1 days, 4 hours, 21 minutes, 29 seconds]: STEP5 -> 05.run_hmmer.pl
[1 days, 20 hours, 7 minutes, 39 seconds]: STEP6 -> 06.lca.pl
[1 days, 20 hours, 32 minutes, 45 seconds]: STEP7 -> 07.fun3assign.pl
[1 days, 20 hours, 35 minutes, 3 seconds]: STEP9 -> 09.summarycontigs3.pl
[1 days, 20 hours, 36 minutes, 20 seconds]: STEP10 -> 10.mapsamples.pl
Convert reads to binary library
2020-10-09 12:01:29 - b'INFO  sequence/io/sequence_lib.cpp  :   77 - Lib 0 (/media/Project/trimmed/ProjectReport2/data/raw_fastq/par1.fastq,/media/Project/trimmed/ProjectReport2/data/raw_fastq/par2.fastq): pe, 312873382 reads, 150 max length'
2020-10-09 12:01:29 - b'INFO  utils/utils.h                 :  152 - Real: 576.3086\tuser: 323.5852\tsys: 84.3359\tmaxrss: 245572'
2020-10-09 12:01:29 - k-max reset to: 141 
2020-10-09 12:01:29 - Start assembly. Number of CPU threads 60 
2020-10-09 12:01:29 - k list: 21,29,39,59,79,99,119,141 
2020-10-09 12:01:29 - Memory used: 243324912844
2020-10-09 12:01:29 - Extract solid (k+1)-mers for k = 21 
2020-10-09 12:16:23 - Build graph for k = 21 
2020-10-09 12:43:25 - Assemble contigs from SdBG for k = 21
2020-10-09 19:44:02 - Local assembly for k = 21
2020-10-09 19:51:50 - Extract iterative edges from k = 21 to 29 
2020-10-09 22:02:11 - Build graph for k = 29 
2020-10-09 22:19:14 - Assemble contigs from SdBG for k = 29
2020-10-09 23:40:32 - Local assembly for k = 29
2020-10-10 00:17:48 - Extract iterative edges from k = 29 to 39 
2020-10-10 00:26:02 - Build graph for k = 39 
2020-10-10 00:36:31 - Assemble contigs from SdBG for k = 39
2020-10-10 01:37:18 - Local assembly for k = 39
2020-10-10 02:25:23 - Extract iterative edges from k = 39 to 59 
2020-10-10 02:30:10 - Build graph for k = 59 
2020-10-10 02:39:01 - Assemble contigs from SdBG for k = 59
2020-10-10 03:10:38 - Local assembly for k = 59
2020-10-10 04:19:00 - Extract iterative edges from k = 59 to 79 
2020-10-10 04:22:02 - Build graph for k = 79 
2020-10-10 04:27:09 - Assemble contigs from SdBG for k = 79
2020-10-10 04:47:30 - Local assembly for k = 79
2020-10-10 05:47:10 - Extract iterative edges from k = 79 to 99 
2020-10-10 05:49:19 - Build graph for k = 99 
2020-10-10 05:53:22 - Assemble contigs from SdBG for k = 99
2020-10-10 06:08:58 - Local assembly for k = 99
2020-10-10 06:52:03 - Extract iterative edges from k = 99 to 119 
2020-10-10 06:53:40 - Build graph for k = 119 
2020-10-10 06:56:51 - Assemble contigs from SdBG for k = 119
2020-10-10 07:09:54 - Local assembly for k = 119
2020-10-10 07:50:19 - Extract iterative edges from k = 119 to 141 
2020-10-10 07:51:22 - Build graph for k = 141 
2020-10-10 07:54:10 - Assemble contigs from SdBG for k = 141
2020-10-10 08:06:15 - Merging to output final contigs 
2020-10-10 08:07:02 - 4346021 contigs, total 2922593222 bp, min 200 bp, max 193681 bp, avg 672 bp, N50 708 bp
2020-10-10 08:07:04 - ALL DONE. Time elapsed: 72910.532752 seconds 
Running prinseq for selecting contigs longer than 1000: /home/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/prinseq-lite.pl -fasta /media/Project/trimmed/ProjectReport2/data/megahit/final.contigs.fa -min_len 1000 -out_good /media/Project/trimmed/ProjectReport2/results/prinseq; mv /media/Project/trimmed/ProjectReport2/results/prinseq.fasta /media/Project/trimmed/ProjectReport2/results/01.ProjectReport2.fasta > /dev/null 2>&1
  Running prinseq for contig statistics: /home/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/prinseq-lite.pl -fasta /media/Project/trimmed/ProjectReport2/results/01.ProjectReport2.fasta -stats_len -stats_info -stats_assembly > /media/Project/trimmed/ProjectReport2/intermediate/01.ProjectReport2.stats
  Running barrnap for Bacteria: /home/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/barrnap --quiet --threads 60 --kingdom bac --reject 0.1 /media/Project/trimmed/ProjectReport2/intermediate/02.ProjectReport2.maskedrna.fasta --dbdir /media/Metasqueeze/db > /media/Project/trimmed/ProjectReport2/temp/bac.gff
Running barrnap for Archaea: /home/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/barrnap --quiet --threads 60 --kingdom arc --reject 0.1 /media/Project/trimmed/ProjectReport2/intermediate/02.ProjectReport2.maskedrna.fasta --dbdir /media/Metasqueeze/db > /media/Project/trimmed/ProjectReport2/temp/arc.gff
Running barrnap for Eukaryote: /home/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/barrnap --quiet --threads 60 --kingdom euk --reject 0.1 /media/Project/trimmed/ProjectReport2/intermediate/02.ProjectReport2.maskedrna.fasta --dbdir /media/Metasqueeze/db > /media/Project/trimmed/ProjectReport2/temp/euk.gff
Running barrnap for Mitochondrial: /home/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/barrnap --quiet --threads 60 --kingdom mito --reject 0.1 /media/Project/trimmed/ProjectReport2/intermediate/02.ProjectReport2.maskedrna.fasta --dbdir /media/Metasqueeze/db > /media/Project/trimmed/ProjectReport2/temp/mito.gff
Running RDP classifier: java -jar /home/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/classifier.jar classify /media/Project/trimmed/ProjectReport2/temp/16S.fasta -o /media/Project/trimmed/ProjectReport2/temp/16S.out -f filterbyconf
Running Aragorn: /home/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/aragorn -w /media/Project/trimmed/ProjectReport2/intermediate/02.ProjectReport2.maskedrna.fasta -o /media/Project/trimmed/ProjectReport2/temp/trnas.aragorn
Creating new gff file: cat /media/Project/trimmed/ProjectReport2/temp/*gff.mod > /media/Project/trimmed/ProjectReport2/temp/02.ProjectReport2.rna.gff
Running prodigal for predicting ORFs: /home/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/prodigal -q -m -p meta -i /media/Project/trimmed/ProjectReport2/intermediate/02.ProjectReport2.maskedrna.fasta -a /media/Project/trimmed/ProjectReport2/results/03.ProjectReport2.faa -d /media/Project/trimmed/ProjectReport2/results/03.ProjectReport2.fna -f gff -o /media/Project/trimmed/ProjectReport2/temp/02.ProjectReport2.cds.gff.temp
Diamond block size set to 8 (Free Mem 226.45 Gb)
Running Diamond for taxa: /home/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/diamond blastp -q /media/Project/trimmed/ProjectReport2/results/03.ProjectReport2.faa -p 60 -d /media/Metasqueeze/db/nr.dmnd -e 0.001 --id 40 -f tab -b 8 --quiet -o /media/Project/trimmed/ProjectReport2/intermediate/04.ProjectReport2.nr.diamond
Running Diamond for COGs: /home/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/diamond blastp -q /media/Project/trimmed/ProjectReport2/results/03.ProjectReport2.faa -p 60 -d /media/Metasqueeze/db/eggnog -e 0.001 --id 30 --quiet -b 8 -f 6 qseqid qlen sseqid slen pident length evalue bitscore qstart qend sstart send -o /media/Project/trimmed/ProjectReport2/intermediate/04.ProjectReport2.eggnog.diamond
Running Diamond for KEGG: /home/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/diamond blastp -q /media/Project/trimmed/ProjectReport2/results/03.ProjectReport2.faa -p 60 -d /media/Metasqueeze/db/keggdb -e 0.001 --id 30 --quiet -b 8 -f 6 qseqid qlen sseqid slen pident length evalue bitscore qstart qend sstart send -o /media/Project/trimmed/ProjectReport2/intermediate/04.ProjectReport2.kegg.diamond
Running HMMER3 for Pfam: /home/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/hmmer/hmmsearch --domtblout /media/Project/trimmed/ProjectReport2/intermediate/05.ProjectReport2.pfam.hmm -E 1e-10 --cpu 60 /media/Metasqueeze/db/Pfam-A.hmm /media/Project/trimmed/ProjectReport2/results/03.ProjectReport2.faa > /dev/null 2>&1
Creating BWA reference: /home/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/bwa index -p /media/Project/trimmed/ProjectReport2/data/ProjectReport2.bowtie /media/Project/trimmed/ProjectReport2/results/01.ProjectReport2.fasta
Getting raw reads for T1A3: cat /media/Project/trimmed/ProjectReport2/data/raw_fastq/T1A3_R1.fastq > /media/Project/trimmed/ProjectReport2/temp/ProjectReport2.T1A3.current_1; cat /media/Project/trimmed/ProjectReport2/data/raw_fastq/T1A3_R2.fastq > /media/Project/trimmed/ProjectReport2/temp/ProjectReport2.T1A3.current_2;
Aligning with bwa: /home/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/bwa mem /media/Project/trimmed/ProjectReport2/data/ProjectReport2.bowtie /media/Project/trimmed/ProjectReport2/temp/ProjectReport2.T1A3.current_1 /media/Project/trimmed/ProjectReport2/temp/ProjectReport2.T1A3.current_2 -v 1 -t 60 > /media/Project/trimmed/ProjectReport2/data/sam/ProjectReport2.T1A3.sam
Calling sqm_counter
Getting raw reads for T1B2: cat /media/Project/trimmed/ProjectReport2/data/raw_fastq/T1B2_R1.fastq > /media/Project/trimmed/ProjectReport2/temp/ProjectReport2.T1B2.current_1; cat /media/Project/trimmed/ProjectReport2/data/raw_fastq/T1B2_R2.fastq > /media/Project/trimmed/ProjectReport2/temp/ProjectReport2.T1B2.current_2;
Aligning with bwa: /home/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/bwa mem /media/Project/trimmed/ProjectReport2/data/ProjectReport2.bowtie /media/Project/trimmed/ProjectReport2/temp/ProjectReport2.T1B2.current_1 /media/Project/trimmed/ProjectReport2/temp/ProjectReport2.T1B2.current_2 -v 1 -t 60 > /media/Project/trimmed/ProjectReport2/data/sam/ProjectReport2.T1B2.sam
Calling sqm_counter
Getting raw reads for T2A1: cat /media/Project/trimmed/ProjectReport2/data/raw_fastq/T2A1_R1.fastq > /media/Project/trimmed/ProjectReport2/temp/ProjectReport2.T2A1.current_1; cat /media/Project/trimmed/ProjectReport2/data/raw_fastq/T2A1_R2.fastq > /media/Project/trimmed/ProjectReport2/temp/ProjectReport2.T2A1.current_2;
Aligning with bwa: /home/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/bwa mem /media/Project/trimmed/ProjectReport2/data/ProjectReport2.bowtie /media/Project/trimmed/ProjectReport2/temp/ProjectReport2.T2A1.current_1 /media/Project/trimmed/ProjectReport2/temp/ProjectReport2.T2A1.current_2 -v 1 -t 60 > /media/Project/trimmed/ProjectReport2/data/sam/ProjectReport2.T2A1.sam
Calling sqm_counter
Getting raw reads for T2B1: cat /media/Project/trimmed/ProjectReport2/data/raw_fastq/T2B1_R1.fastq > /media/Project/trimmed/ProjectReport2/temp/ProjectReport2.T2B1.current_1; cat /media/Project/trimmed/ProjectReport2/data/raw_fastq/T2B1_R2.fastq > /media/Project/trimmed/ProjectReport2/temp/ProjectReport2.T2B1.current_2;
Aligning with bwa: /home/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/bwa mem /media/Project/trimmed/ProjectReport2/data/ProjectReport2.bowtie /media/Project/trimmed/ProjectReport2/temp/ProjectReport2.T2B1.current_1 /media/Project/trimmed/ProjectReport2/temp/ProjectReport2.T2B1.current_2 -v 1 -t 60 > /media/Project/trimmed/ProjectReport2/data/sam/ProjectReport2.T2B1.sam
Calling sqm_counter
Getting raw reads for T3A1: cat /media/Project/trimmed/ProjectReport2/data/raw_fastq/T3A1_R1.fastq > /media/Project/trimmed/ProjectReport2/temp/ProjectReport2.T3A1.current_1; cat /media/Project/trimmed/ProjectReport2/data/raw_fastq/T3A1_R2.fastq > /media/Project/trimmed/ProjectReport2/temp/ProjectReport2.T3A1.current_2;
Aligning with bwa: /home/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/bwa mem /media/Project/trimmed/ProjectReport2/data/ProjectReport2.bowtie /media/Project/trimmed/ProjectReport2/temp/ProjectReport2.T3A1.current_1 /media/Project/trimmed/ProjectReport2/temp/ProjectReport2.T3A1.current_2 -v 1 -t 60 > /media/Project/trimmed/ProjectReport2/data/sam/ProjectReport2.T3A1.sam

**Comment by jtamames** [comment]
Hello
Did you try mapping with bowtie?

Best,

**Comment by jtamames** [comment]
I am seeing that you have an old version of the script. Could you download the current `10.mapsamples.pl`, and run it again, just that script?  I think that can solve your issue. If not, please tell me.

Best,
Javier

**Comment by tboonf** [comment]
Hi Javier,
Unfortunately, even after replacing the script with the latest version (
10.mapsamples.pl), I have still encountered the same issue:

..........
Working with sample 5: XXX
Getting raw reads
Aligning to reference with bowtie
Calculating contig coverage
Illegal division by zero at
/home/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/10.mapsamples.pl line
379.
Stopping in STEP10 -> 10.mapsamples.pl
Died at /home/miniconda3/envs/SqueezeMeta/bin/SqueezeMeta.pl line 839

Is it possible that there is a bad mapping of reads that have resulted in 0
mapping? What does it mean by "illegal division by zero"?

**Comment by jtamames** [comment]
Hello
Sorry for the delay in getting back to you.
Could you please check if you sam file was created correctly? Just do:
`ls -l /media/Project/trimmed/ProjectReport2/data/sam/ProjectReport2.T3A1.sam`

The other samples were aligned and counted correctly (then the procedure works), and I am thinking there can be something odd regarding that particular sample T3A1.

Best,
Javier

**Comment by tboonf** [comment]
Thanks, Javier.
I have checked and apparently the files were not copied properly, but after
rectifying that, it works like a charm.

Thank you,

**Comment by jtamames** [comment]
Nice! Closing issue, feel free to reopen.
