### ISSUE TITLE
Erro in SQMtools:The first argument must be a SQM object

### ISSUE THREAD

**Issue by razz1618** [jtamames/SqueezeMeta#180]
Hi, recently i ran individual projects and then combined them with combine-sqm-tables.py. Further, I loaded the data into SQMtools using 
MG  = loadSQMlite (path/to/combined/results)   

Here I got a warning message:
**Loading taxonomies
Loading functions
Column sums are not the same in the taxonomy and function tables. This is ok as long as the project was generated with sqm_longreads.pl**

Next, I went with exploring the data and plotting visualization plots..  it went smoothly with  bar plots and heat plots but when i try to subset a particular function i get error  saying first argument must be a SQM object

Here, i wanted to find all genes with nitrogenase word in their annotation
NF = subsetFun(MG, fun = 'Nitrogenase', rescale_copy_number = F) 
plotTaxonomy(NF, 'genus','percent', N = 10, rescale = T, others = T)

**Error in subsetFun(MG, fun = "Nitrogenase", rescale_copy_number = F) : The first argument must be a SQM object**

Traceback:
2.
stop("The first argument must be a SQM object")
1.
subsetFun(MG, fun = "Nitrogenase", rescale_copy_number = F)

**Comment by fpusan** [comment]
Hi!
1) You can disregard the warning message, I've actually removed it in the latest developement version,
2) As per the documentation, SQMlite objects do not support subsetting. If your individual projects you want to combine were run with SqueezeMeta (as opposed to `sqm_reads.pl` ) there will be a way to do what you want in the upcoming next version. You can try it now, as long as you install the `SQMtools` package from the `develop` branch. You can find more info in #150, but the general idea would be as in the example below:

```
### Load your data
P1 = loadSQM('/path/to/the/first/project')
P2 = loadSQM('/path/to/the/second/project')

### Get the bacterial reads (subsetFun would also work)
P1_bact = subsetTax(P1, 'superkingdom', 'Bacteria')
P2_bact = subsetTax(P2, 'superkingdom', 'Bacteria')

### Combine the data and do fancy stuff
combined = combineSQMlite(P1, P2)
plotTaxonomy(combined)
exportKrona(combined)
exportPathway(combined, '00910', 'percent')
```

Let me know if this is what you needed.

**Comment by razz1618** [comment]
Hi, thanks. I will try this. So, the basic idea is i need to first apply the subset and then combine and work with sqmlite. so that means,  If i want to know a specific function and its related taxonomy (in combined samples) i use 
P1_funct = subsetFun(P1, 'specific_function')
P2_funct =  subsetFun(P2, 'specific_function')
p_fun = combineSQMlite(P1, P2)
plotTaxonomy(p_fun)

Is that correct?

**Comment by fpusan** [comment]
That's right!

**Comment by fpusan** [comment]
Well, not exactly right, it would be

`p_fun = combineSQMlite(P1_funct, P2_funct)`

**Comment by razz1618** [comment]
oh yes.. that was a typing error. it should be p_fun = combineSQMlite(P1_funct, P2_funct). Thanks

**Comment by razz1618** [comment]
HI,
Does SQMlite not include ORF reads info?
 I combined multiple projects into one:
 P1 = loadSQM('/path/to/the/first/project')
P2 = loadSQM('/path/to/the/second/project')
P_comb=combineSQMlite(P1, P2)

Summerized:
sum_P_comb = summaryP_comb)

When I check:
sum_P_cob$reads_in_orfs

It says: **NULL**

Similarly, When I subset function from above and save the data into a table, I can get the info about taxa and function but not about orfs
**exportTable(combined_NIF$orfs$table,** "combined_NIFGenes.orftable.tsv")** 

gives an empty file.



Secondly, I see when I subset a function with a specific term (for say, all identified functions having Nif word)

nif_p1=subsetFun(P1, fun = 'Nif', rescale_copy_number = F, ignore_case = 'FALSE')    (tried with ignore_case='T' too)
nif_p2=subsetFun(P2, fun = 'Nif', rescale_copy_number = F, ignore_case = 'FALSE')
combined_NIF = combineSQMlite(nif_p1, nif_p2)

plotFunctions(combined_NIF, fun_level = 'COG',count = 'tpm', N=10)

**Along with the interesting function the results shows some other functions wherein there is no matching term with Nif **

![00000f](https://user-images.githubusercontent.com/59241611/97097305-08a1b980-16aa-11eb-8a48-badf3acb16e4.png).

**Comment by fpusan** [comment]
> Does SQMlite not include ORF reads info?

No, as per the documentation.

> Secondly, I see when I subset a function with a specific term (for say, all identified functions having Nif word) [Along with the interesting function the results shows some other functions wherein there is no matching term with Nif]

Note that by default `subsetFun` will perform a regex search in ALL the columns containing functional annotation. This behaviour can be controlled in many ways. See the last answer in #150 for more details.

**Comment by razz1618** [comment]
Ok. thanks. i will check.
