### ISSUE TITLE
Regarding squeezemeta version

### ISSUE THREAD

**Issue by razz1618** [jtamames/SqueezeMeta#181]
Hi,
This is exactly not a major issue. I have installed squuezemeta following the provided instructions. When I run the pipeline everything works perfectly. Thanks for the great hard work you people are doing.  The only problem I am having is that the version command does not return the version number. It just gives a blank output.

(SqueezeMeta) [mcs@mcs1 ~]$ SqueezeMeta.pl -v
(SqueezeMeta) [mcs@mcs1 ~]$

**Comment by fpusan** [comment]
Thanks for reporting! This was already fixed and will work in the upcoming version.
