### ISSUE TITLE
step 2 - nhmmer failed to run

### ISSUE THREAD

**Issue by RitaBogorad** [jtamames/SqueezeMeta#183]
Good morning!
After successfully using squeezemeta for my previous projects, the new metatranscriptome dataset is giving an error at step 2 - 
Running barrnap (Seeman 2014, Bioinformatics 30, 2068-9) for predicting RNAs:  Bacteria Archaea[22:42:08] nhmmer failed to run - Error: Invalid alphabet type in target for nhmmer. Expect DNA or RNA.

When I take a look at the  02.2019.maskedrna.fasta, I see a lot of reads with Ns. My previous squeezemeta runs on other datasets seem to be having only meaningful sequences (non Ns).
I am using SqueezeMeta version 1.2.0.
The initial command was -
/home/bioadmin/Downloads/squeezeMeta/SqueezeMeta-master/scripts/SqueezeMeta.pl -m coassembly -p 2019 -s 2019.samples -f /mnt/userhome/we11_pae2_bulk/Rita_unzipped_metatranscriptome_2019 --cleaning

Can you please suggest to me how to solve this?

Thank you!

Rita

the part of the 02.2019.maskedrna.fasta file where the program is stopping:

head 02.2019.maskedrna.fasta
>megahit_1
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
>megahit_2
GGGGAGATAAGCCTGTTATCCCCGGGGTAGCTTTTATCCGTTGAGCGATGGCCCTTCCATGCGGAACCACCGGATCACTAAGCCCGACTTTCGTCCCTGCTCGACTTGTAGGTCTCGCAGTCAAGCTCCCTTGTGCCTTTAGTCTCTGCGAATGATTTCCAACCATTCTGAGGGAACCTTTGGGCGCCTCCGTTACCTTTT
>megahit_3
GAGGCGCTGCGCGACCCTCGGCTCGGCCGCGTGATCGCCGCACTGCACCGGGAACCGGGGCGCAACTGGACGCTCGTCGACATGGCGCACGAAATGGGCAGCTCCCGCTCGGTCTTCGCCAAGCGCTTCGTCGAGGTGACGGGAATGACGCCGCAGCGCTACGTGCTGGCAATGCGCATGCGGCTCGCCGAGCAATGGTTCCGCCGCGACAAGCTGCCGATCGACACCGTCTCCCGCCGCCTCGGCTTCGGCTCCCAAGCCGCCTTCACCCGCGCCTTCAAACGCGTCGTCGGCCAACCGCCCGGTCAGGC
>megahit_4
CTGAGATGGAATCGGCGGTGTTCTTGGGGAATCCACGAAAATACTTGGCTTTAACCAGGAGCTTATATTGCGAATCAGAGCAGGAGGGCCCTGAACTTGTAATTCATTAGATTTCAGAGTTTCCTTATAGCTTCTGACACCCATCCAGACATTCGTCATGACTTTCACAGTTGATACAAAGAAAATATCCACATCTTTTGCGGGGTCTTTAATGCAGAGATCAACCCTGTCGCCGTTTACCAGCAGCCACCATTTTTTTTGCTGCATAAGATCAGTAAACTCAAACTGGATAACAGTTTCATTGCCAATCAGTTTCGTTGGGTCGATGCTGCGTTCCAGATAATACATTAGGAATT

**Comment by jtamames** [comment]
Dear Rita
Step 2 does not run using `02.2019.maskedrna.fasta`. Instead it creates it (all scripts create files with its same number). The N´s are the result of masking contigs once barrnap has run. Barrnap runs on `01.2019.fasta` in the results directory. Did you do anythig with the files, like copying, moving, renaming them? Could you sens me also the `syslog` file?

**Comment by jtamames** [comment]
It would be also very good if we could have your `01.2019.fasta` file. Any chance that you can send it to us that one via wetransfer or dropbox?

**Comment by RitaBogorad** [comment]
I did not modify manually the results folder. The raw files are stored on a virtual (unfortunately windows-based) cloud and results are outputted to our Linux-based cluster. I did this already with a small metagenome dataset and it worked ok.
I had to interrupt and restart the initial run because our server was running on full memory with other people's tasks.

[syslog.txt](https://github.com/jtamames/SqueezeMeta/files/5438092/syslog.txt)

Can I send you the wetransfer file to jtamames@cnb.csic.es?

**Comment by jtamames** [comment]
> Can I send you the wetransfer file to jtamames@cnb.csic.es?

Sure! It will help me to reproduce the error.

Thanks!

**Comment by jtamames** [comment]
I cannot reproduce the issue, for me it is working fine with your fasta file and provides the expected results. I can send you the results, but I would also like to understand what is going on.

**Comment by RitaBogorad** [comment]
thank you for sending me the step 2 output, the next steps seem to be working fine at the moment.
very curious as well on what could have gone wrong..
