### ISSUE TITLE
Less number of reads in assembly

### ISSUE THREAD

**Issue by razz1618** [jtamames/SqueezeMeta#184]
Hi, Recently I ran squeezemeta on 5 samples (with technical replicates i.e. after DNA extraction from the sample, the DNA was divided into two batches and sequenced separately resulting in total 10 sequenced samples). Before running the squeezemeta pipeline the reads were cleaned with final reads having a PHRED score of more than 30. When I ran squeezemeta (coassembly mode) individually on each sample (with replicate) .

 I found that the total number of reads of one of the samples is far less than its technical replicate.

![capture-20201026-213829](https://user-images.githubusercontent.com/59241611/97179385-bbba0200-17d3-11eb-9f46-4cb28121ee9f.png)

For other samples, the number of reads are almost similar with their technical replicate.

The same when plotted for taxonomy depicting raw abundances:

![raw_abund](https://user-images.githubusercontent.com/59241611/97178563-9bd60e80-17d2-11eb-8ed3-5c8322f494ce.png)

 It is very clear that sample 100_1 have some problem.

**Comment by fpusan** [comment]
Hi.

It would seem that the input files you provided to SqueezeMeta contained less reads for that sample. You can check the `results/10.*.mappingstat` file, or ultimately just count the number of lines in the different fastq files to be sure.

If the input fastq files really have a very different number of reads for each sample, then there is really not much that we can do, and you should probably contact your sequencing provider.

Best,

Fernando

**Comment by razz1618** [comment]
Yes. there was a problem with one of the READS (R1). Before running squeezemeta i gzipped the fastq file.  Guess, one of the files was not successfully compressed because the cleaned reads (before compressing) seems to be ok. Thanks
