### ISSUE TITLE
Samples file error

### ISSUE THREAD

**Issue by ilkaybuysal** [jtamames/SqueezeMeta#186]
Hello everyone,
I'm getting this error about the samples file: "Please do not use blank spaces in the samples file
Died at SqueezeMeta.pl line 194, <infile1> line 0.000000."

-My samples file look like this: 
MG176020 MG_176020.R1.fq pair1
MG176020 MG_176020.R2.fq pair2
MG176795 MG_176795.R1.fq pair1
MG176795 MG_176795.R2.fq pair2
MG193866 MG_193866.R1.fq pair1
MG193866 MG_193866.R2.fq pair2

-and here is the cmd I've ran:
perl SqueezeMeta.pl -m coassembly -p 2020_10_28_test_w_JR_MG -s /usr/local/miniconda3/envs/SqueezeMeta-1.1.1/database/db/2020_10_28_test_JR_MG/sample_2_MG176020 -f /usr/local/miniconda3/envs/SqueezeMeta-1.1.1/database/db/2020_10_28_test_JR_MG/

Thanks in advance for the help!

**Comment by fpusan** [comment]
Hi,
- Did you use spaces instead of tabs to separate the fields in your samples file?
- Did you perhaps create the samples file using windows?

**Comment by ilkaybuysal** [comment]
Yes, that was the mistake! Thanks a lot.

**Comment by fpusan** [comment]
Glad to hear, closing issue
