### ISSUE TITLE
unable to run external database

### ISSUE THREAD

**Issue by tboonf** [jtamames/SqueezeMeta#188]
When set up an external database according to user manual, and ran accordingly, I have received the following error messages: 

Running Diamond for CAZyDB /media//Metasqueeze/db/CAZyDB: /home/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/diamond blastp -q /media/Metasqueeze/test/Project7/results/03.Project7.faa -p 60 -d  -e 0.001 --id 30 --quiet -b 8 -f 6 qseqid qlen sseqid slen pident length evalue bitscore qstart qend sstart send -o /media/nova//Metasqueeze/test/Project7/intermediate/04.Project7.CAZyDB /media/Metasqueeze/db/CAZyDB.diamond

Note there is not input for -d in the syslog, although the database and the -extdb mydb.list file was used according to the user manual. Any help to resolve this is very much appreciated.

**Comment by jtamames** [comment]
Hello
May I take a look at your mydb.list file?
Also, did you create that file in a Windows system? If so, have you tried to run dos2unix on it as to remove Windows CR codes, as in #59? This should be a solved issue, but can be happening to you if you are using a old SqueezeMeta version

Best,
Javier

**Comment by tboonf** [comment]
Hi Javier,
 I have tried a few ways of making the mydb.list file:
A) CAZyDB /media/Metasqueeze/db/CAZyDB
B) CAZyDB /media/Metasqueeze/db/CAZyDB.dmnd
C) CAZyDB
/media/Metasqueeze/db/CAZyDB.dmnd /media/Metasqueeze/db/CAZyDB.Annotation


All files were created in linux, and the file name should read CAZyDB.dmnd.
As per your previous advice on using newer script, i actually replaced the
04. script two days ago as well just in case but this did not solve the
problem.

**Comment by jtamames** [comment]
The correct one should be:
CAZyDB      /media/Metasqueeze/db/CAZyDB    /media/Metasqueeze/db/CAZyDB.Annotation

The second column is the location of the database without the final .dmnd
All fields must be tab separated. Please send me the actual file so that I can take a look.

Best,
Javier

**Comment by tboonf** [comment]
Thanks Javier- resolved after putting the file list in tab deliminated format.
