### ISSUE TITLE
kegg and metacyc patwhays's bin prediction

### ISSUE THREAD

**Issue by fconstancias** [jtamames/SqueezeMeta#190]
Dear SqueezeMeta developers,

Thanks one more time for developping SqueezeMeta.

I have questions regarding the 'Prediction of kegg and metacyc patwhays for each bin' - I have check on the manual but could not find the information.

-Is there any estimation of pathway completness ? Is gap filling is performed and i
-Is it possible to get a list of KEGG KO per bin as well?
-Wich version of metacyc and kegg are used ?

Thanks.

**Comment by jtamames** [comment]
Hello

1) In the 21.kegg or 21.metacyc files, the first row lists the number of genes in each of the pathways. The number in the columns for each of the bins indicates how many of these genes can be found in that bin. No gap filling is performed. You can find find details on the algorithm in the MinPath paper [here](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1000465)
2) We don't provide that in the tables, but I think sqmtools can help you to get that, let's ask @fpusan 
3) KEGG version is the last public one, 58.0. Metacyc (Biocyc) version is 24.0

Best,
Javier

**Comment by fpusan** [comment]
Regarding the list of KEGG per bin, you can select individual (or several) bins in SQMtools using the `subsetBins` function. The functional tables in the resulting object will contain only the functions identified in those bins.

**Comment by fconstancias** [comment]
worked perfectly, thanks.
