### ISSUE TITLE
An error occurred while running sqm2tables.py

### ISSUE THREAD

**Issue by nksjpl** [jtamames/SqueezeMeta#195]
Hi Squeezemeta devlopers,

I am trying to run SQMtools on my project and receiving following error, please help:

Traceback (most recent call last):
  File "/home/bio3990/anaconda3/envs/SqueezeMeta/SqueezeMeta/utils/sqm2tables.py", line 35, in <module>
    from utils import parse_conf_file, parse_mappingstat, parse_orf_table, parse_tax_table, parse_contig_table, parse_bin_table, parse_tax_string, read_orf_names, aggregate_tax_abunds, normalize_abunds, write_orf_seqs, write_contig_seqs, write_row_dict, TAXRANKS, TAXRANKS_SHORT 
  File "/home/bio3990/anaconda3/envs/SqueezeMeta/SqueezeMeta/utils/../lib/utils.py", line 7, in <module>
    from numpy import array, isnan, seterr
ModuleNotFoundError: No module named 'numpy'
Error in loadSQM("ISS") : An error occurred while running sqm2tables.py

**Comment by fpusan** [comment]
Hi,
How did you install SqueezeMeta?
If you are using conda, make sure to activate the conda environment before running SQMtools.
Best,
Fernando

**Comment by nksjpl** [comment]
Hi Fernando, 

Thanks for the prompt reply
Yes, I did install it with Conda. Also, Installed SQMtools using R-studio on my local system, transferred full project from the cluster to my local system to avoid any doubt of error.

Then I followed following steps:
1) Installing squeezemeta on my local system
2)Activate it using conda
3)Then run SQMtools on R-studio

still getting the same error. Please help.

thanks Nitin

**Comment by fpusan** [comment]
Hi,
Is the SqueezeMeta conda environment also installed and activated in your local system?
Best,
Fernando

**Comment by nksjpl** [comment]
Yes, I did activate it before using R studio. 
Looks like, its not able to call numpy in conda environment, a possible solution can be installing R-studio in the conda env and doing the drill again. Do you agree:

Nitin

**Comment by fpusan** [comment]
Maybe it has to do with it being run inside RStudio, as the conda environment includes numpy.

You can run `sqm2tables.py` outside RStudio like this.
`sqm2tables.py /path/to/your/project /path/to/your/project/results/tables`

Then go to RStudio again, try to load the project with `loadSQM("/path/to/your/project")`. It won't try to create the tables again if they can be found at the right place.

**Comment by nksjpl** [comment]
that worked perfectly. Thank you for the support. This is one of the smoothest and prompt interaction I have ever had with a developer team. Keep it up and keep developing :+1:

**Comment by fpusan** [comment]
Glad to hear it worked, and thanks for the kind words. Closing issue
