### ISSUE TITLE
issues with sqm2tables.py 

### ISSUE THREAD

**Issue by yjiakang** [jtamames/SqueezeMeta#196]
After running SqueezeMeta.pl smoothly, I used SQMtools R package for further analysis and visualization in v1.3.0 version.
Error I met, hoping for help. 
Here is the syslog of the project "A57RS1T1", and the error that R print.

[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/5577567/syslog.zip)

```
> test <- loadSQM("A57RS1T1")
Generating tabular outputs for project in A57RS1T1
Traceback (most recent call last):
  File "/public/home/jkyin/miniconda3/envs/SqueezeMeta/SqueezeMeta/utils/sqm2tables.py", line 195, in <module>
    main(parse_args())
  File "/public/home/jkyin/miniconda3/envs/SqueezeMeta/SqueezeMeta/utils/sqm2tables.py", line 58, in main
    total_reads, total_bases = parse_mappingstat(perlVars['$mappingstat'])
KeyError: '$mappingstat'
Error in loadSQM("A57RS1T1") : 
  An error occurred while running sqm2tables.py
```
Best

**Comment by fpusan** [comment]
Totally our fault. This is because you created the project using an older version of SqueezeMeta. We're not good at backwards compatibility...

Edit the SqueezeMeta_conf.pl file inside the project's directory.
Below line 55 add the following:
$mappingstat = "$resultpath/10.$projectname.mappingstat";
Save and run sqm2tables again. It should work

**Comment by yjiakang** [comment]
Worked perfectly. Thanks.

**Comment by yjiakang** [comment]
Hello, now I am doing visualization with SQMtools of the SqueezeMeta pipeline v1.3.0, however, loadSQM occurred an error again:
```
> p <- loadSQM("~/yjk/tomato_micro/T1/four_cultivars_T1")
Generating tabular outputs for project in ~/yjk/tomato_micro/T1/four_cultivars_T1
Traceback (most recent call last):
  File "/public/home/jkyin/miniconda3/envs/SqueezeMeta/SqueezeMeta/utils/sqm2tables.py", line 195, in <module>
    main(parse_args())
  File "/public/home/jkyin/miniconda3/envs/SqueezeMeta/SqueezeMeta/utils/sqm2tables.py", line 68, in main
    args.trusted_functions, args.ignore_unclassified, customMethods, data_dir)
  File "/public/home/jkyin/miniconda3/envs/SqueezeMeta/SqueezeMeta/utils/../lib/utils.py", line 195, in parse_orf_table
    orfs['bases'][orf] = bases
MemoryError
Error in loadSQM("~/yjk/tomato_micro/T1/four_cultivars_T1") :
  An error occurred while running sqm2tables.py
```
Can you help?
Thank you.

**Comment by yjiakang** [comment]
Totally 125G, free 20G. I have 12 samples.

**Comment by fpusan** [comment]
And how many contigs/orfs are in the assembly? I'm a bit surprised that it runs out of memory. Maybe you can try again when more memory is free?

**Comment by yjiakang** [comment]
(base) [jkyin@mn02 results]$ grep -c "^>" 03.four_cultivars_T1.fna
23895635
I tried when more available memory can be used, but failed. 
```
> p <- loadSQM("~/yjk/tomato_micro/T1/four_cultivars_T1/")
Generating tabular outputs for project in ~/yjk/tomato_micro/T1/four_cultivars_T1/
Error in loadSQM("~/yjk/tomato_micro/T1/four_cultivars_T1/") :
  An error occurred while running sqm2tables.py
> Terminated
```

**Comment by fpusan** [comment]
Hi!
The assembly is indeed very large. It may be running out of memory, depending on how large are the contigs.
Can you run sqm2tables manually?
`sqm2tables.py ~/yjk/tomato_micro/T1/four_cultivars_T1/ ~/yjk/tomato_micro/T1/four_cultivars_T1/results/tables`

**Comment by yjiakang** [comment]
Yes, it worked. Thanks a lot.
