### ISSUE TITLE
Removed reads still mapped?

### ISSUE THREAD

**Issue by seppedm** [jtamames/SqueezeMeta#202]
Hey there, 

I've been running a few test runs on my data in merged mode, including a filtering step with Trimmomatic and I noticed that in the mappingstat files, the number of 'total reads' is still the same as in the original data. Does this mean that for the mapping, the original data is used without filtering? Wouldn't this give problems with the considerable amount of adapter sequences and faulty bases still present? 

Thanks in advance!

**Comment by jtamames** [comment]
Ups..
Yep, this is a bug. We use the filtered reads for the assembly, but not for the mapping. I will fix this asap. Thank you very much for warning us about this one.

Best,
Javier

**Comment by jtamames** [comment]
Hello
I have just fixed this issue. You can download the new scripts:

01.run_assembly.pl
01.run_assembly_merged.pl
SqueezeMeta.pl

from the development branch. https://github.com/jtamames/SqueezeMeta/tree/develop

Replace the old ones with these and rerun the project.
Best,
Javier

**Comment by seppedm** [comment]
Thank you very much!
