### ISSUE TITLE
cover.pl issue

### ISSUE THREAD

**Issue by eperezv** [jtamames/SqueezeMeta#203]
Hello,

I tried the cover.pl function and I found strange results. It seems all OTUs remained unclassified. However, mothur correctly classifies most of them. I am running the latest git version. This is the output:
```
(base) my@my-PC:~/mydata$ /home/user/tools/SqueezeMeta/utils/cover.pl -i sample.fna -t 12 -cl mothur

COVER is part of SqueezeMeta - (c) J. Tamames, F. Puente-Sánchez CNB-CSIC, Madrid, SPAIN

Please cite: Tamames & Puente-Sanchez, Frontiers in Microbiology 9, 3349 (2019). doi: https://doi.org/10.3389/fmicb.2018.03349; Tamames et al, Environ Microbiol Rep. 4:335-41 (2012). doi: 10.1111/j.1758-2229.2012.00338.x

Looking for coverage 5x for 4th OTU, classifying with mothur

Running cd-hit-est (Schmieder et al 2011, Bioinformatics 27(6):863-4)
  Results created in cover/sample.fna.cdhit
  Number of sequences: 51452
  Number of OTUs: 5688
  Singletons: 2887
  Unobserved fraction: 0.06
Running mothur classifier (Schloss et al, Appl Environ Microbiol, 2009. 75(23):7537-41)
  Results created in cover/16S.mothur.out

Needed 980.97 Mb, uncorrected
Correcting by unobserved: 1039.29 Mb

Finished! Results in cover/cover.out
WARNING:
  Some OTUs (5688 out of 5688) could not be classified
  For these OTUs, default values of size (4 Mb) and copy number (1) were used
  This can substantially affect the results, especially if these OTUs are abundant
```

**Comment by jtamames** [comment]
Hello!

Could you please replace your cover.pl with the one in the `development` branch of this repo (https://github.com/jtamames/SqueezeMeta/blob/develop/utils/cover.pl)?
I fixed some issues there and probably it will solve your problem.

Please let me know if it works for you.
Best,
Javier

**Comment by eperezv** [comment]
Thanks for your reply.
I've tried with the one from the develop branch and it did not produce any weird output. It seems it worked fine.

**Comment by jtamames** [comment]
Great! Did you get the proper Mothur results? I would be very interested in hearing your feedback about this program, especially if you do the actual sequencing

**Comment by eperezv** [comment]
I didn't know there exists something like this so I already have both 16S and shotgun from the same sample. The shotgun data is still unprocessed but I like the idea! and I would like to evaluate it to use in an upcoming experiment. 

I have some questions. I guess it mainly applies to bacteria. But what about eukaryotes? they might be an important fraction of the DNA in some cases, making the estimation unrealistic.
Could it be chosen a different OTU picking program or strategy? or supply an external OTU table? I have the OTU table and it seems cd-hit overestimated the number of OTUs (double).

**Comment by jtamames** [comment]
Hello

Indeed just prokaryotic OTUs are considered. I cannot see the way of estimating eukaryotic or viral contribution, as we would need other information than 16S. The user must be aware that, if there is substantial non-prokaryotic presence, the precision of the estimate could be affected.

Regarding the external OTU table, that is a good idea and I will probably implement it in upcoming versions of the program. But notice that we will need both the OTU table and the abundances of each of the OTUs.

I am surprised that you had double number of OTUs using cd-hit than using other methods. I can expect some differences but not to that amount. Which software were you using to collect your OTUs? 
As we are using mothur for classifying, we could also use it for OTU picking, but it will be much slower. 

Thanks for your feedback!
Best,
Javier

**Comment by eperezv** [comment]
Thanks for your answer. I understand about the eukaryotes.
Great to read that there might be implemented another way of choosing OTUs. I used Uparse v7 for OTU picking with a cutoff of 97%, but together with 20 more samples. Using DADA2 on the same dataset provided comparable OTU numbers.

Best regards
