### ISSUE TITLE
Error with flye

### ISSUE THREAD

**Issue by ARiou-zd** [jtamames/SqueezeMeta#204]
[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/5616686/syslog.zip)
Hi, 

I wanted to try flye as an assembler for SqueezeMeta. However the workflow stopped at the first step. 
I tried to run flye separately on the same data used for testing the workflow and the program worked.

You can find the syslog attached to this message.

Do you have a solution ?

Thanks in advance!

**Comment by jtamames** [comment]
Hello!

Flye complains about the fastq file:

[2020-11-30 15:56:16] ERROR: parse error in /home/ariou/anaconda3/envs/SqueezeMeta/SqueezeMeta/database/test/MinIONflye/data/raw_fastq/par1.fastq.gz on line 374834: Fastq fromat error

Could you please zcat this file and check the first lines to check if it is correct? Please do `zcat home/ariou/anaconda3/envs/SqueezeMeta/SqueezeMeta/database/test/MinIONflye/data/raw_fastq/par1.fastq.gz | more` and paste the result

Best

**Comment by ARiou-zd** [comment]
Thanks for your response.

Here is the result : 
`(SqueezeMeta) ariou@UC150-UBU:~/anaconda3/envs/SqueezeMeta/SqueezeMeta/database/test$ zcat /home/ariou/anaconda3/envs/SqueezeMeta/SqueezeMeta/database/test/MinIONflye/data/raw_fastq/par1.fastq.gz | more
@SRR7947168.1.1 1 length=985
CTCTTTGTTGCGGGCGCTCGCACCGTTTCCCTGGCCGCTGTTGGACTGGCCATTTGCTTGACCGCTTTGCTGCCCAGACGCTGTACCGCCATTCGTCGTGGACTGCCCGCTTTGTTTTTGAGCCTCAGTGACAGCGCTGTCCTTTTGATAACTTCCCGCGCGGTCAATCCGGGAGGGCATAGATTAGGCCCACGCCAGCCACAGCAAACAA
CGCAAAGCCCGCAGCACCATAATAATGATGTTGCGAGTGCGCTTGCCCATGGATCCCGCCCGCCGCGTTGCGGACGAGGAAACGCTCACCGAAAACGTCCTCGTCGACCTCGCCCTCAAATCCTGCGGGCAATAGCGAAGACGCCGGCCACGGGCATCGCAACCGTCTCGCCCACCACCGTACCAGGTTGCGCAGGCGACGAACCCTTTGC
TACGGCAGCGTTTGGGAACACCGTGGTCTCCGCCGTATCCGCCTTAGCCGCATCCCATTATCTGCGCGGGCGGTCTCCGCGCCGTCGTACCTTCGATGCGTCATCGATACTGGACATGCCCTAGCCTTGGTCTTCTCAAGAGCCTCCGGCGAGGGATCAAGTACCTCCAGCGACATAGTCCTCTTAACGAGCGACCAAAGTTGCCGTAGCA
AGGTTCGTCGCCTGCCAACGATTGGGCGAGACGGTTGCGATGCCGGCCCGGCGCTCCACTGCCCCGGCAGGATTTGAGGGCAGGTCGGCACGAGGACGTTGCGAGCGTTCTCGTCCTGACGCGGCGGCATCCAGGGGCAAGCGCACTTCCGCAGCATCATTATTCCGGCGGCGAACTTTGCGTTGACTGACCAGTGGCGATAATTACCTGC
CACGATTATTCACGTGGAGCGTCCTGCTTGTCTGAATTGAGCGAATCGGCGCGACTCCCGTCTGGGCAATAACGTCTTCAGCAATAGCGGTAGGTACTTTATCGTGTCTTTGTGTTAACTGCTGCTTTCTGTCGTTTTGCA
+SRR7947168.1.1 1 length=985
((,/5/00:221;78787922-581*://8,*-.704580908.0/3.82:0091*),0+.161,22*'*+,--(),975453765;/22-.73.01278;1/542;3-+/))$+042*,($*(*+,12/31-.-(*1562%'-0+,+,&#%*,/8)')'*(,-//944+&)+$))('(()/'.'(&)*/.(,+,.*&(())&',4<882+
2*2*,))-42+,%,-'0.'$+%&(4+00303333..00351//8+-5.(+*-++,,'#00++26++)',)..:4--(-))-/,'(1*&-*()-/,,42-,'*),-8824334880,..9-,79657/0/()'$''))/0')5-03.12,*,330--13114.--+.0278377**+%(,+1249/3..,+,(,%,*.--..)+)-)(-*(,
.-()%''010341/351.0)32/7226:9;;34:.4/550+0-+,*),*$&()3,(',3,.04/0/+0457789704%#%&'&&(-&&&.,233243,)+-02:887.'.+-0-'*-705.'')+)*--1170;000)(('(,/-+(*)'($+-3)*('($'%6523../13+*'()7/5/*''&1,7-&+//02'83**80/77+02354
3*40995689:;724()-**&.(39;8524343829'/,*,.2/2.63)3/.,1457/111518,**+()'(-75*,.5,.(2632.'+%',(+.,-4834400111::/+/277+('-)+1/:.2..--5(*',)(+.8..+.&&))+-+--'1125.8.&+'&(*1-,))&%'')+))/+/*%%(()&%#$$$&%''&(&'+(%/30'-
'#$&&+%%&'&%**--&($&''((%%(*('))'%'%)&%$*(*)$%&%%('))(((+00,/2*0*&%+('(#%%'&(/,&&&%$$$&&&(*+('(&++.)&'-*+(+*/1*'+*+3,,*()++&%)('&'&('#%%$#$%%
@SRR7947168.2.1 2 length=850
GTCCGCCAGGGGACTTCTGGAAGATGTCACCGCCCGAGCAACGCACAGACCGCAAGCTATCCTGTATACCCACATCCCGAAGCAATACAAGCATCTGGCAGATTCGCCGGAAAACGTCAAACGGATGGCTGAATATGAGAAAGCATTGTCCGGAAAGAGGTGCACTGGCTGCCTAAAACAAACTGCCCGACACGGGACTCCCGTGGATCAT
GGACGGAGACGTGATTGCTATCACCACGAAGCTTCGGGACTGGATATAGCTCATGGGATAGCCCTTTGTAAACAGAGTTTGCATTTTAACCATGCTTCTTTCTACTCTGGGCAAGGAGTTGTCCTCAGCGAAGAGCCTCTCCAGCCAAATGCTCAACAATAACAAATCGTGGACGGGCATGCGTGTCGTCGGATGTCTCACCCAGCAAAAC
AAATGATTGTAAAGGAAACAGAGTACAAGCATTTCAACTCTCGCCTCGTGTTTGTTGCCTGCTTTCTGGAAGGGCACAAAGGAACGGCAAACGCCTCTTTTCACCAGTGCACTCCGGATTTGCCCAATCGGCGAAATTTATGGCCGGCACAGGATTAGCTATCGCTGACAGCAGGTACGGCTAACTTTCACATAACGCTTCCACCATCACG
CTTTTCTCACAGGATGTAGGTGCCAGCTACTCATGCAGCGAGCATAAATAAGAACTATGGTATGCACAGCGCTTCCCTCTTCTACCATCGGACGGAAGGGGAAACATGGATTTACCGTAGGATTCCGTCATTATAAAGATGCTGATTTTCATTGGAGGATGGTCCGAGACCATGCCCGTGCTACCTGGAATCTGGGCTGCTTCTTTCCAGA
AGCTTA
+SRR7947168.2.1 2 length=850
),3/-..*+306.22806536-,-..87479205+*((++'.)-/0157::,/2/-..420+&$(%%$*''()+5/5*%+)),08/-/+2,/13554;6201473451+2,482/.468<999<895;666;<1/(''%)*+(++7,+*5,3-26*%(**+)))-209431/'%-583599530007*+/6451:9:89/9,,.7/-//49
:;89831117+2.+2.-.59:1116+.&')((158+85/.1588:7/10214/0+'-*21,1+''--'./-+'%'%&-/**1.243)*,,0+-.557//60,+)*+-3/0(*+,(,&&.))*5402--+),,)-,262011-,--80;/--5771)**.)/,019822-4,0*+*(&)$$%'&.),.518,:2:9888401.)%$&+626.
3;4/,&*$#''-*%%'*'*'(%&''%)&%(/1:3.&%%*%).)-../'(0089+-7+-5++-078+++&&'&&&*,.69)**%$$'%)&/4,-563,235-1'('%(-'+&+*/(2-+.(&%)'&+)*+&1,%%%%,-*)*4/2,+.*+2.291--*))+./+(($&%,.+,(1+-..3(&$**)*-.)*+,/14.),.0.6/0:8:6)1+
*.48--,-%+)156,,(&(-)(*60.-.,.1215..%%%(''*)+,-.,0--3../-.20233/.&('())12/24.,218/,*,,'()+*($&&&&,+)&(--)&*)0+07,+18-6)1*)0266/16/50/*78-*898:9992994*+/3/4(*003::16%')**./..*26,+20/,*-/,,.)/,-.,.&%%$'&.)17,4*,'*
*&%%&%
@SRR7947168.3.1 3 length=1239
CCGGGCTGACGCTGACGCCGTGAACGCTGGCCGAAGCCGCGTCCCAGCGTTGCTGCTGAAGCCGCCGCTGCTGCCGCTGCCTCCGCCGCCGCTTCCTCAGAAGCTGCTGGCTGATACTGCCGCCTCCAGCGCTGCTGCCTTGATAATCAGTCCTAGCACTGTTGGTCAAAAACCCGACAGTTTCTACGACTGTCCGGGTTTTCTTTACTAT
AGCGCTGACTACGGCCTTTCAAGCGTCTGCATCGGTACAATGGCTGGCTCATTGGCTTTTCTGATGGAGTTTGTTGATATGAGTTCTGCCGTCATTAACCGGCGATTACCAGGAACCCGCCTTCCGCGTGGAAAACATCAACTTGGTTTTCAATCTGGACCCCGTCACCACGACGGTTTTACAACACGATGCGCATTGAGCCGCTCGCGGA
TTCAGACCGCGATCTGGTGCTGAACGAGTGAACTCGAGCTTGCTTCCGTTTTTGAGAACGGCAGCCCGCTCCACGGAACGCAGGTTACGCCACGAGGAGAGCATACTCTCATCATCCGTGGGATCCCGCCAGAAGACCACGATGCTATCTATAAGTTCCATCCGCAGGCAACACACACTGCTTTCTCAGGCATCTATATGTCCAGCAGAAC
TTCATGTCGAGGTGAATCGGAAGGCTTCCGCCGGATCACCTATTTCGGATCACCCGGACGTAGCGGCCCGATTCCATGTTGAAATCCGGGCTGACAAAGAGCAGTATCCGATCCTTCTCTCAAACGGCAGCCTCATTGAGCAGCGGGGGGATCTGGATAACGGACGGCTTTTCGCCATCTAGGAGTGATCCCTCTCTCAAGCCCTGCTACC
TCTTCGCGCTTGTCGCCGGAAAGCTGGTGAAGCGTGAGGAAGTCTATAAGCTCGCAAACGGCAAGGACTGCCTGCTTCAGGTCTGGATTTGAGCCTCAGAATGCTGATAAGACTGAGCACACGATGGAGTGCATCAAGCGGAAGCCATCCGCTGGGATGAAACCCGCTGGGGACTCGAGTATATTGACCTGGACCGCTTCATGGCATTACG
CCACCGACGACCTTCAATTTCCGGAGCCATGGGGGAATAAGGGGCCTGAACATGCTTCAATACGCGCTATGGCCGAAACCGCGCGACACCGAAGATGGCGACGGACCTCGATTACTTCAATATTGAATCCGTTGTCGGTCGAATACTTCCATAACTGGACGGGCGACCAGGTCCTCTGAGAGAC
+SRR7947168.3.1 3 length=1239
1()/--++),%%%((.)-5554220%',,.,$'),*-5,-.-2/-*-.124.-//06110-261475::310+,+(+.369579883031.1716214)(*,,-75/*)%%#$%+%,(*,3-/3/30,,/./321,,0''$&#*/912%67-,*&++)-0/-5+&/50787//:0046122<4,'&(,/269.4'24+8,0&$$&'&&'('
*%('))*,,+()+'%$%)')***+,0992211.&'$%&*.*,(&$*),-0*1+4,-7;:-8-,+,0/)+,9()46001'''&++:5335.077/40/./5-4--&33*.1//94;5;5/2,.00624004*+*+*(-14.9-,30/15:-0,9./.6;-581+-,..3/')++;709:<.2322.',+,/2288/8/.*458./.2%))**
7.6'(,88*..0/-()13*+(''-0(%('&)--25)),+--*,4/77..871)(%*%))+85//.55*++31...77.,$%#&'+,%(&*(%&)'++(&'$'%'&&'&)*+;:7763-/*/*&))2))./.()*(*23)+-,*''(*,*'&&,(()869740+&)'+(-&)(,,)*'**+)'&'+)+'4565876675753-2.(+32,-,
+3,./32/()**---368+4./,21484:2/(2)-/0+.0,',0-5)7.96+6*,-2/2(,$('*&%&)(.25;808058/)+/)+),4.--.-4.4(((./(&5,-,)),12126/00/3+8--),**(3/22,-4/++.%+)-6:830/**%'+.-,70)3.4-1,)*)-*1264650'-(%&%*)+.+((,-0/0*3%*+)')+++/5
/0274/.%)++-/39::0-+($$(-,(,')*((25+)+(',)+-)**2.%,-51657851-(+)*-./12393//07-2-2.0+*/%'%#&%)03342+...-/../14923222312.0*./030/*(('(*.754)/0*)($&20,7+')+*5656--4'/+&$'(&.73-2,+'%&(&+'(*))8-56::82+/222-4'')%-(),-
04-03/%41'33))*,*9;.-(+,%&675642(*')/--,177/99543*'&(&(343082,000,24454*2(%+/*,4..-,.25258-5-++22533/55:3..1+.%+'(&&)*,1-,/0-1/.363/7//0.5-0'&*'$('*0/+)-3478;9:69800'4/&.-00-,-//)((()-
@SRR7947168.4.1 4 length=886
AATTATTTTCTTTAGTAAGCGGCACGCTTATTCTTTCAGGTCTGTCTGCCAATGCGCAGAAAAACAACACAAAACCGAATATGCTTTTCATCCTCTGCGGTAGTATGGGATACCGGTGATCTGGGATGTTACGGTCAGCCATACATCCGCACCCCATCGAATGCGATGGCAGAAGCGAGGCGCTTCACACAGGCATACGCAGGAAGTCCTG
TCAGTGCTCCTTCCAGAGCCTCCTTTATGACAGGACAGCATACAGGACGTACTGCAGTACGAGGTAACAAGGAATATTGGACGAGTGCGCCACAATCATGTATAGCAATAATAAGGAGGTAATACGTGGTGGGGCAACATCCTTGATCCCGACCACATCATCTTACCCGAAATAATGAAGGGGTGGATGCGCTACCGGCATGTTCGGCAAA
TGGGCGGGAGGCTGAGGGTTCCTGTTCTCGGACAAACGTGGGTGGATGAATACTACGGCTACATCTGCCAGTTCCAGGCCCACCTCTACTATCCCTAACTTCCTCAACCGCTACAGCAAGGCGCTTTCGTTGATACGGGAGTGGGTACGTGTCGTTATGGACGGAACATCAAAGTATCCGATGTACGGCCCCGATTATCATAAGCGTCCCG
CAATATTCCGCCGACATGATTCCACGAGCGATGATGGAATGGCTGGACGGACTGGGACGGCAACAACCTTTCTTCGGGTACTAACTTACACCCTTCCCCACGCCGCGGGGAACTAGCCAGCCGGAAGATTCTATCTTAAATGGGCCACAAGGGGAGGTTTCGAAATCCGGACCAAAGGCTATGGCGGCAGCAGGATCCCACGATACAATGC
GGTCACACATGGCACGCACGGTATTGCGCTTCGTTCCGGTAG
+SRR7947168.4.1 4 length=886
6*-)&+47;-09-')*58-,(/*),+-*6).4+&)-,2../*)('+65/509/57001-1.780/6.-,-.69249)(:542,.*389.7499.,-)**%''&)-.2:3..(*,''.+,-237;600-.822-60/-*+/++)-//37-.)2/.'(),)(/.*////051(&-(*)+(*&&$&1+/((&)*1732114/700+)'()76//
55*-+)+/72.03*--*)(,+-2,64-//3.*-6.40.1100/-280)$%%(+)*'&&'+%%(&*/7-2).'.+-+425456,(+-054.,'(++,-64468,)++40-*%&(+'&%%&),++*3.(&(+,693*),'+.0.+(&'*,2*()6/,,,/07761:,0/)),46....//..-+(*3:0,(,,.035:18//04:<:7:219/
,498:/40),/*++*(/+69.1--+0++--5096::9775-().8;96,61+/,+,)-00-///0889;99;0:,+8-99-*6:756334508/)('('*'*')).115031)(&--2324+'&%%&&)))%#&%))2.&'(/2()-;38577.03/03:9822-**25141'&)*,0,*-.011.*,277../.:.11/,04(*(((.*(
)2++-::0.+0965623584:-0(%')&$+()(')0+(,.,8..01044-*$-+2*,-1,10,-,'-*15+)488&/(,*/001('&&'(-,'&()+,&&)&&$%%&,,')*()%%()*+10/70//.2901./.,32:/,-)%$%&','--,'&(*(5))%('%)**,0)0-)**)'()())1./66044),.+,8,)%*(--+--0+''
(&*/&*).'(%%'$&#%#$)&*$*&$&$&+'+&).0,()#$&
@SRR7947168.5.1 5 length=733
TTAATATTACCTATTTTCTTGTATGGTCTAAAGAAAATTACTTTGCTCAAAAATATTCAAAGCAATGTGCAATTTGTAACCTATGACGTATCAAGACAAAGCCAAATTAGTAGATGTAGCCCGTCAGCTTTTGCGAAGATGGGTAAGAAACACAGCCATGAATGATATCGCTCTGCTTGCTTCCTAAAAAGGGTAGACGAACGCTCTATAC
TTATTTTAAAGTAAGGATGAAATTTATTTGAAACATTGTGGAATCAGGTGGATATTCACTGTGGTCGCGATGAAGCGGGTGTACGAAAATATCTGGACGAGGGAATTGTTGGAGATGATATATACCAGTTGGACGCGGTAAAAGAGTGGTCTATCGGAAACGGAACATTGCATTTGTATTGCTTCGTGATATGGCGGCGGGTGGAAAGAAG
TTCGCAAAGTTGATGCAAAAGGAGTCGCTCTTTAAAGCACATTTCTTCTAGAAAAGGACAAAGGCAAAGGAGTTTTCCATATTGGTAATGCAGGATGACTGCCGACTTGATACATTATTGTGTAGAAAGAATTGAAGTTTACACATTCGTGGCAGCATAGTTGCACATCTGGATGAAGATACGAGAAATAGATATGTATTACAACATTGTG
TTTGGCACCCTGCGCTAGAACAATTTAATTGATAACTTTTAGTATGGGATTTATTAGACGGAAAAAGGCAGCTACATTGTGACCGGTGCTGCGCCGGTGC
+SRR7947168.5.1 5 length=733`

It's just a part of the output. I can send you a file containing all the output.

Best.

**Comment by jtamames** [comment]
Yep indeed there are some weird things in the fastq file... could you please copy the full syslog file, and some lines of the original fastq files by doing `zcat /home/ariou/anaconda3/envs/SqueezeMeta/SqueezeMeta/database/test/MinION/SRR7947168.fastq.gz | more`? If you can send me that file `SRR7947168.fastq.gz` via wetransfer would be great.

Best,
Javier

**Comment by jtamames** [comment]
Please send me also the `par1.fastq.gz` file

**Comment by ARiou-zd** [comment]
Here is the link : 

[https://we.tl/t-Wo4jp3HGLj](url)

Thanks for your help.

Best,
Antoine

**Comment by jtamames** [comment]
Thanks a lot. I see the problem now. It seems that your original fastq files have an extra blank line at the end. Then, when concatenating the files for the assembly, that blank line goes into the merged fastq file `pair1.fastq` and Flye doesn't like it.

Indeed we are not checking for blank lines in the fastq files. I will make a patch for it. In the meantime, if you want to work with these files, you can remove blank lines using sed or awk, see for instance https://stackoverflow.com/questions/16414410/delete-empty-lines-using-sed

Best,
Javier

**Comment by ARiou-zd** [comment]
Hi !

I cleaned up the fastq files with sed to remove the white lines and flye worked well!

Thanks again!

I close the issue.
