### ISSUE TITLE
"poor" Bin Taxonomy 

### ISSUE THREAD

**Issue by aatxaerandio** [jtamames/SqueezeMeta#205]
Hi there, 

First of all, congratulate developers for such complete pipeline.

Secondly, I have troubles when assigning taxonomic ranks to bins. As long as bin taxonomy is assigned based on contig taxonomy, and contigs taxonomy on the taxonomy of genes within them, I obtain bins with very “poor” taxonomy. I mean, I get bins assigned to phylum or class level rather than to family or genus levels.

The aim of my study is to analyse the biodiversity of my environment (wetland) and to try to obtain MAGs. Even if SQM runs (Coassembly mode) smoothly and finishes, I obtain bins with no “clear” taxonomy. 

I checked the manual and it comes to my mind that maybe reducing the e-value cut-off (1e-03) could assign bins to genus level. Is it recommendable, or will it “solve” my issue? What should I do to obtain bins at family/genus level?

Thanks in advance.

**Comment by jtamames** [comment]
Hello
Thanks for your kind words and for using our pipeline.
The taxonomy of SqueezeMeta is probably conservative since we attempt to not making (many) mistakes. Therefore the system only annotates a taxon when it is pretty confident of it. For doing so, we implemented several checks and filters. The e-value of the homology searches is just one of them (and probably will not impact much the results, at least when you keep it in "reasonable" limits, between 1e-03 and 1e-10). The filters we use to  annotate genes ensure that the annotation is done for a  credible rank, but of course can impact how deep the annotation is  (see an explanation [here](https://github.com/jtamames/SqueezeMeta/wiki/A-discussion-on-taxonomic-annotation-and-the-meaning-of-disparity-values-of-contigs)). And also we use the consensus approach for annotate contigs and bins. That consensus tries to avoid annotating contigs and bins to unsupported ranks.

If you want to skip the filters for the taxonomic annotation, you will see that in the results directory you have two 06 files, one called noidfilter.wranks (no filters) and other simply wranks (with filters). The second is used for all subsequent annotations. The just backup the wranks file, rename the noidfilter.wranks to wranks, and redo the annotations running step 9 (contig annotation) and 17 (bin annotation). If you are happy with the result, then you better restart the project from step 8 to update all the rest of files.
If you want to alter the consensus (this is what I would try first), just alter the values in the parameters.pl file that is in yur projexct directory. You need to change $mingenes9, $minconsperc_asig9 and $minconsperc_total9 for contig annotation, and $mincontigs17, $minconsperc_asig17 and $minconsperc_total17 for bin annotation. Then run again steps 9 and/or 17.

**Comment by aroc110** [comment]
Hello,

I love this pipeline. Very useful and easy use. Thank you so much for developing it.

I  have a  question related  to this one. Most of my contigs are  ending "Unclassified", so I  decided to take a look at these two 06 files, the noidfilter.wranks  and the wranks. Interestingly, the wranks file seem to have more and deeper annotation  than the noidfilter.wranks file.

In my case, prodigal identified 105,891 ORFs. 85,838 ORFs are present in the 06 files, some with taxonomic annotation some without, I assume that the remaining genes (105,891 - 85,838) had no diamond hits (?). 

The interesting part is that  80,144  genes get a taxonomic annotation in the  wranks file, but  only  45,607 have a taxonomic annotation in the noidfilter.wranks. I would expect the opposite behavior, that the filtered file had fewer annotation as it is more stringent. Here is a screenshot showing an example of a gene that gets a taxonomy annotation in the wranks file but not in the noidfilter.wranks file:

wranks:
<img width="872" alt="image" src="https://user-images.githubusercontent.com/4120895/101230782-35a79b80-365c-11eb-8a26-0b40185c6761.png">

noidfilter.wranks:
<img width="872" alt="image" src="https://user-images.githubusercontent.com/4120895/101230791-4e17b600-365c-11eb-94d8-ebcb2780f2c8.png">

As you can see gene: megahit_5_2-310 is annotated as 'k_Archaea;n_DPANN group;p_Candidatus Woesearchaeota;s_Candidatus Woesearchaeota archaeon' in the wranks file, but is not annotated in the noidfiltered.wranks file. 

I'm sorry if I'm missing something obvious here, but is this behavior expected?

Thanks for your help and for developing this program.

**Comment by jtamames** [comment]
Hello!

Thank you for your kind words, and for providing this detailed and interesting example of annotation.

It is not obvious at all. It is also not the expected result, but I think it is correct. Let me explain the possible situation here. When you drop the identity filters in the nofilter file, you are considering all hits above the default identity level, which if I remember correctly is set to 40%. Your Archaea gene probably has bacterial homologs that are filtered when you keep filters on. But with no filters, then you get with a mix of bacterial and archaeal hits for which there is no last common ancestor. And therefore you end up with no annotation for the gene. With filters on, as bacterial hits will have lower identity, they will be not considered for annotating at the species level and you see the archaeal annotation.

Your dataset looks like the prefect storm for this kind of situation. It seems to come from some kind of thermal source or extreme environment where you have a mix of bacteria and archaea, probably poorly characterized. You will have a low number of hits for each gene,  making this situation more likely. Also you have the opposite example in the genes from megahit_2 and megahit_3, where you have a more complete annotation when filters are not considered. For instance, the case of megahit_2 is probably a gene with just one hit with a distant homolog. That´s why you get "Bacteria" with filters, but all the way to species when not using filters, which is most probably incorrect. This is the behaviour that you see in programs like Megan and that we wanted to avoid strongly, and the reason for introducing identity filters.

So, you can see that not having annotation does not mean not having hits. Indeed you can check that in the 22.stats file, where you can see the number of ORFs with hits and the number of orphans (no hits). This will be lower when you use the nofilter set. If not, then we would have to inspect it.

Any way, if you can send me the first 1000 lines of the diamond result (result file 04 in the intermediate directory), I can check if this my lengthy explanation is correct.

Best,
Javier

**Comment by fpusan** [comment]
Hi,

> In my case, prodigal identified 105,891 ORFs. 85,838 ORFs are present in the 06 files, some with taxonomic annotation some without, I assume that the remaining genes (105,891 - 85,838) had no diamond hits (?).

Yes, but to be sure you can check the 13.*.orftable file, which contains information for all the ORFs.

> The interesting part is that 80,144 genes get a taxonomic annotation in the wranks file, but only 45,607 have a taxonomic annotation in the noidfilter.wranks. 

This is a big difference, and perhaps we should look into that a bit more

>  Here is a screenshot showing an example of a gene that gets a taxonomy annotation in the wranks file but not in the noidfilter.wranks file:

The screenshot itself is not that weird. The rest of the genes get deeper annotations in the noidfilters file than in the standard one.  Regarding the one that's missing, what comes to mind is that it might have one or several low identity hits assigned to a superkingdom other than archaea. When those hits are discarded by the identity filter, the LCA algorithm assigns the gene to Archaea. However, if those genes are included, the LCA algorithm finds no consensus at the superkingdom level, hence the lack of annotation.

You can check the hits for `megahit_5_2-310` in the `intermediate/04.*.nr.diamond` file. If you find hits with < 40% identity assigned to taxa other than archaea, then I'd say that's pretty likely to happen (you can also check the LCA algorithm description in the PDF manual, which also describes the default parameters).

The same can happen to contig annotation: dropping the identity filter might cause ORFs that were not previously annotated to break the taxonomic consensus for that contig. Our experience is that dropping the identity filters improves classifiacation at lower (genus, species) taxonomic ranks, but has no positive effect on higher ones.

Let us know what you find!

**Comment by jtamames** [comment]
Ha! I was there first, Fernando! lol

**Comment by aroc110** [comment]
@jtamames 

Dear Javier,

Thank you for your prompt answer You are correct in all points.

> Your dataset looks like the prefect storm for this kind of situation. It seems to come from some kind of thermal source or extreme environment where you have a mix of bacteria and archaea, probably poorly characterized. 

Yes. These data come from hot mud volcanos and are very poorly characterized.

> So, you can see that not having annotation does not mean not having hits. Indeed you can check that in the 22.stats file, where you can see the number of ORFs with hits and the number of orphans (no hits). This will be lower when you use the nofilter set. If not, then we would have to inspect it.

I didn't think of looking at the orphans (no hit) data in file 22. That  is correct the total number of ORFs (107,021) minus the number of orphans (21,183) is the number of entries in files 06 (85,838).

> Any way, if you can send me the first 1000 lines of the diamond result (result file 04 in the intermediate directory), I can check if this my lengthy explanation is correct.

I ran:  `grep 'megahit_5_2-310' 04.Results2.nr.diamond` and your explanation is correct. Here are  the hits  for megahit_5_2-310:

```
megahit_5_2-310 HGY75643.1      94.2    103     6       0       1       103     359     461     1.8e-52 215.3
megahit_5_2-310 NMB80469.1      78.6    103     22      0       1       103     329     431     8.9e-44 186.4
megahit_5_2-310 HGJ66028.1      74.8    103     26      0       1       103     361     463     3.5e-40 174.5
megahit_5_2-310 NUN69984.1      54.5    101     46      0       1       101     359     459     8.4e-26 126.7
```

The first hit is for the Archaeal species, while the other 3 are for bacteria, which have identities lower that  the 85% htreshold for species. But they have a higher identity than the threshold for superkingdom (40%), shouldn't that  be enough to remove the annotation from the best hit? I'm attaching the first 1000 lines from the  diamond file.

[1000lines.txt](https://github.com/jtamames/SqueezeMeta/files/5647405/1000lines.txt)

@fpusan 

> Yes, but to be sure you can check the 13.*.orftable file, which contains information for all the ORFs.

Thanks for pointing me to this file. I confirmed that  the numbers  match.

>You can check the hits for megahit_5_2-310 in the intermediate/04.*.nr.diamond file. If you find hits with < 40% identity assigned to taxa other than archaea, then I'd say that's pretty likely to happen (you can also check the LCA algorithm description in the PDF manual, which also describes the default parameters).

I  checked the hits and the  situation is as you mention. The best hit for an Archaea, and the other hits to bacteria. However,  the second and third hits have identities higher than 70%.

Thank you for your clear answer,  I now understand the method better.

Best,

Andre

**Comment by aatxaerandio** [comment]
Thank you for your time Javier.

On the one hand I checked the consensus % (set to 50% and 70% by default) and modified them both to 20% and run both steps just in case I obtained “better” results for contig & bin assignment.  
On the other hand, I run contig and bin assignment steps without filters and compared the results. Here I attach two screenshots of a handmade comparison of the high quality bins (>90% completeness and <5% contamination). 
 
![imagen](https://user-images.githubusercontent.com/75436856/101793538-3467ea00-3b06-11eb-995b-d473814f9d89.png)

In the case of no filters, some “no consensus” appear which is quite logical. With modified consensus %, taxonomy gets a bit “deeper”, even if it improves, I still get bins on Bacteria Kingdom, with huge heterogeneity. 
 
![imagen](https://user-images.githubusercontent.com/75436856/101793638-4f3a5e80-3b06-11eb-9344-fcf08e825537.png)

What it comes to my mind is that maybe I have many genes without prediction (as shown in the screenshot below) and that it could affect the contig taxonomy assignment and indeed bin assignment. Should I use the extra sensitive detection of ORFs with - - D option? 

![imagen](https://user-images.githubusercontent.com/75436856/101793735-67aa7900-3b06-11eb-8b18-e470909f1138.png)

 Thanks in advance.

**Comment by jtamames** [comment]
Hello
The usage of --D can improve the results because sometimes it corrects wrongly predicted genes, and that helps. But do not expect too much improvement. In our experience that gets 2-5% more annotations. Your ratio of orphans is perhaps a bit high (we usually get 20-30%) but in the range of what I would expect. Of course this is dependent of the environment, with higher ratio of orphans in "rare" or extreme environments.
You can check the taxonomic annotation for all contigs in the bins to get the feeling and probably curate the annotation manually. That information is in the `results/DAS/<project>_DASTool_bins` directory. There you can find a .tax file for each bin, with the annotation of each contig in it. Maybe it can clarify things and let you know how to proceed.

Best,
Javier

**Comment by jtamames** [comment]
Should you want to try the --D in the project you already have, you must run the 08, 09, 10, 12, 13, 17, 18, 19, 20 and 22 scripts, to remake all files.

**Comment by aatxaerandio** [comment]
Hello Javier, 

I used - - D and run all the following steps after. Results seem to improve a little bit as you said in the previous message. Now, with the assigned bin taxonomy I decided to debug and clean the obtained bins. I moved to “utilities: binning refinement” section and wanted to try both scripts. First, I decided to try finding_missing_markers.pl to improve completeness and afterwards remove_duplicate_markers.pl.

Once I run finding_missing_markers.pl, I see this error just a couple of minutes after:

Illegal division by zero at find_missing_markers.pl line 314.

That is the following one in the script (see permalink):
https://github.com/jtamames/SqueezeMeta/blob/4957661cf97451241adf40f3cd419725bad1b337/utils/binning_utils/find_missing_markers.pl#L314

How can I fix this error?

Thanks in advance.

**Comment by jtamames** [comment]
Hello

I will check this, it worked last time I tried.

For curating bins, I also reccomend you to import the data into Anv'io using our sqm2anvio utility (See [here](https://github.com/jtamames/SqueezeMeta/wiki/Loading-SQM-results-into-anvi'o)), because these guys have really wonderful curation tools

Best,
Javier

**Comment by jtamames** [comment]
Can reproduce

**Comment by jtamames** [comment]
Just replace line 286 reading 
`$bin=~s/\.fa$|\.fasta$//g;`
by 
`$bin=~s/\.fa.*|\.fasta.*//g;`

That should fix your problem.
Best,
Javier

**Comment by aatxaerandio** [comment]
Hello, 
Now it works perfectly, thank you.
I will check Anvi´o and see how it works just to know and see different curation methods.

Thank you Javier, 

Aitor.
