### ISSUE TITLE
Merged mode

### ISSUE THREAD

**Issue by eperezv** [jtamames/SqueezeMeta#207]
Hello,

I am trying to use SqueezeMeta in a case not described in the documentation. I have several samples that cannot be coassembled (memory issue). However, I've merged fastq files across treatments (3 samples combined in one), performed the assembly for merged files and plan to use squeezemeta in merged mode.

However, since I have around 51 samples, and 17 contig files, I wonder how to code this into squeezemeta to run the pipeline. Is that possible? It could be just as the merge mode but supplying several external assembly files.

Thanks,
E.

**Comment by jtamames** [comment]
I am afraid that is not possible actually. What you could do is to make the assembly apart and then provide it to SqueezeMeta with the -extassembly option. Did you try the `seqmerge` mode? It is intended to provide a solution to scenarios like yours.

Best,
J

**Comment by eperezv** [comment]
I was playing with the scripts and think I found a way. Since SqueezeMeta in merged mode is individually assembling samples, then, combining all contigs in one file, I did the same and supplied it as external assembly. I stopped the program, edited the configuration to remove the external assembly and individually run 01.merge_samples.pl. It seems it's working (but it's taking ages), trying to get one unique assembly. Probably, I would have to be more restrictive and include longer (+500 nt) contigs.

I was checking the code of the merge_samples script and I saw that all assemblages were combined in one, which inspired me to do it in this way.

**Comment by seppedm** [comment]
Hi there, I'm in a situation somewhat faraway similar to yours and I'm wondering how long 'ages' is. This to decide whether I should kill my process and restart in seqmerged mode. 
my case: 36 samples, all assemblies added up into a file of 16gb

**Comment by seppedm** [comment]
To respond to this, for my 36 samples I estimated that it would take at least 3 months to do the merging step, so I cut it down to 3 batches of 12 samples, which of course greatly improves the speed.

**Comment by jtamames** [comment]
Closing issue, feel free to reopen
