### ISSUE TITLE
Coassembly mode with 12 samples corrupted at step 1

### ISSUE THREAD

**Issue by yjiakang** [jtamames/SqueezeMeta#208]
Hello, I am using your wonderful pipeline for the metagenomic analysis of 12 samples. It corrupted. Is it probably because the memory limitation? Here is the syslog, thanks for checking.
[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/5649922/syslog.zip)

**Comment by jtamames** [comment]
Hello
In the log, megahit output listed this:

`2020-12-06 14:03:59 - Error occurs, please refer to /public/home/jkyin/yjk/tomato_micro/T1/four_cultivars_T1/data/megahit/log for detail
`

Did you check that file? Can you paste it here?

Best,
J

**Comment by yjiakang** [comment]
Here is the file, I have no idea about dealing with it.  Thanks.

[log.zip](https://github.com/jtamames/SqueezeMeta/files/5665646/log.zip)

**Comment by jtamames** [comment]
Here is the thing:

2020-12-09 12:52:43 - b'FATAL assembly/unitig_graph.cpp     :  126 - Too many vertices in the unitig graph (4561190258 >= 4294967294), you may increase the kmer size to remove tons of erroneous kmers.'

Basically it means that the assembly is too big to be handled. Try the suggestion of increasing kmer size adding `-assembly_options "--k-list 59,79,99,119,141"`

You could also try `-assembly_options "--presets meta-large"`

Best,
J

**Comment by yjiakang** [comment]
Yes, it perfectly worked. Thanks.
Best

**Comment by jtamames** [comment]
Hello

Just for our knowledge, which one worked, seeting k-mers or using presets meta-large?

Best,
Javier

**Comment by yjiakang** [comment]
setting k-mers
