### ISSUE TITLE
DASTool 

### ISSUE THREAD

**Issue by kinosham** [jtamames/SqueezeMeta#211]
Good day 

I keep getting cut off at step 16 the errors are not always the same, I have run the program before with different data and had no issue with the server now there are problems. Here are some of the problems it comes up with 

-p destination: Broken pipe
which: no Rscript in (/apps/SqueezeMeta/scripts/../bin:/usr/local/bin:/usr/local/sbin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/bin/SMCIPMITool:/usr/local/maui/bin:::::)
Can't find Rscript. Please make sure R (>= 3.2.3) is installed on your system. Aborting.
Error running command:    LD_LIBRARY_PATH=/apps/SqueezeMeta/scripts/../lib PATH=/apps/SqueezeMeta/scripts/../bin:$PATH /apps/SqueezeMeta/scripts/../bin/DAS_Tool/DAS_Tool -i /home/kinosha/res_coassembly/results/DAS/maxbin.table,/home/kinosha/res_coassembly/results/DAS/metabat2.table -l maxbin,metabat2 -c /home/kinosha/res_coassembly/results/01.res_coassembly.fasta --write_bins 1 --score_threshold 0.25 --search_engine diamond -t 24 -o /home/kinosha/res_coassembly/results/DAS/res_coassembly --db_directory /nlustre/data/SqueezeMeta/db at /apps/SqueezeMeta/scripts/../scripts/16.dastool.pl line 66.
Stopping in STEP16-> 16.dastool.pl

If I try run it from where it stopped its saying

kinosha@wonko:~/ >/apps/SqueezeMeta/scripts/restart.pl res
Can't open progress file file /home/kinosha/res/progress
kinosha@wonko:~/ >/apps/SqueezeMeta/scripts/restart.pl res_coassembly
[0 seconds]: STEP16 -> DAS_TOOL MERGING: 16.dastool.pl
mkdir: cannot create directory ‘/home/kinosha/res_coassembly/results/DAS’: File                                                                                                                                                              exists
^CError running command:    LD_LIBRARY_PATH=/apps/SqueezeMeta/scripts/../lib PAT                                                                                                                                                             H=/apps/SqueezeMeta/scripts/../bin:$PATH /apps/SqueezeMeta/scripts/../bin/DAS_To                                                                                                                                                             ol/DAS_Tool -i /home/kinosha/res_coassembly/results/DAS/maxbin.table,/home/kinos                                                                                                                                                             ha/res_coassembly/results/DAS/metabat2.table -l maxbin,metabat2 -c /home/kinosha                                                                                                                                                             /res_coassembly/results/01.res_coassembly.fasta --write_bins 1 --score_threshold                                                                                                                                                              0.25 --search_engine diamond -t 24 -o /home/kinosha/res_coassembly/results/DAS/                                                                                                                                                             res_coassembly --db_directory /nlustre/data/SqueezeMeta/db at /apps/SqueezeMeta/                                                                                                                                                             scripts/../scripts/16.dastool.pl line 66.
Stopping in STEP16-> 16.dastool.pl

I am not sure what the probelm is, do you think you canhelp

**Comment by fpusan** [comment]
Hi!
It seems that your R environment is not properly configured.
Did you install SqueezeMeta using conda? If so, did you activate the environment before running the program?

**Comment by kinosham** [comment]
Good day thanks for your response we use a universal server at the univserity and there is someone incharge of loading and installing the programms can I perhaps suggest something to him to help with the pipleine 

Regards 

Kinosha Moodley
PhD Student
Division of Microbiology
Department of Biochemistry, Genetics and Microbiology
Lab 9-40
Natural and Agricultural Sciences Building
Lunnon Street
University of Pretoria
Pretoria
0001
South Africa 
 

    On Thursday, December 10, 2020, 12:36:18 PM GMT+2, Fernando Puente-Sánchez <notifications@github.com> wrote:  
 
 


Hi!
It seems that your R environment is not properly configured.
Did you install SqueezeMeta using conda? If so, did you activate the environment before running the program?

**Comment by jtamames** [comment]
Hello!
You say that the program was working correctly but somehow it stopped doing so. Do you know if they did something with the server in between? Could you asked if they reinstalled or removed some software, especially R?
If not, I suggest reinstalling SqueezeMeta using conda
Best,
Javier

**Comment by jtamames** [comment]
Closed because of inactivity, feel free to reopen
