### ISSUE TITLE
Can't open mappingstat file  for writing : STEP10 -> MAPPING READS: 10.mapsamples.pl

### ISSUE THREAD

**Issue by LeeNicha** [jtamames/SqueezeMeta#217]
Hi
I got an error, it shows below: 

[0 seconds]: STEP10 -> MAPPING READS: 10.mapsamples.pl
  Reading mapping file from /home_bif/onnicha/enterobacter_project/metagenome/ecInfants/data/00.ecInfants.samples
  Metagenomes found: 262
  Mapping with Bowtie2 (Langmead and Salzberg 2012, Nat Methods 9(4), 357-9)
Can't open mappingstat file  for writing
Died at /home_sbi_cold/onnicha/anaconda2/envs/squeezemeta/bin/restart.pl line 585.

 I used SqueezeMeta version 1.3.0
Thank you in advanced.

**Comment by jtamames** [comment]
Hello
Did you check that you have disk space available? 262 metagenomes must need a lot of space. Also, are they metagenomes or 16S amplicons?
Please attach the `syslog` file found in the project directory

Best,
Javier

**Comment by LeeNicha** [comment]
Thank you for your reply. I have around 5 TB left and it's metagenome data. 
I've fixed it by adding
$mappingstat     = "$resultpath/10.$projectname.mappingstat"; 
in SqueezeMeta_conf.pl and it worked!!

However, I got a new error as shown below

  Output in /home_bif/onnicha/enterobacter_project/metagenome/ecInfants/intermediate/10.ecInfants.mapcount
sort: write failed: /tmp/sort5suIKT: No space left on device
Stopping in STEP10 -> 10.mapsamples.pl. File /home_bif/onnicha/enterobacter_project/metagenome/ecInfants/intermediate/10.ecInfants.mapcount is empty!

I've checked the space and it has 4.9 TB left. Please look at the syslog file 

[syslog.txt](https://github.com/jtamames/SqueezeMeta/files/5753300/syslog.txt)

**Comment by fpusan** [comment]
Hi!

According to the syslog you sent, the program seems to have finished abnormally in step 2.

```
[0 seconds]: STEP2 -> 02.rnas.pl
Running barrnap for Bacteria: /home_sbi_cold/onnicha/anaconda2/envs/SqueezeMeta/SqueezeMeta/bin/barrnap --quiet --threads 18 --kingdom bac --reject 0.1 /home_bif/onnicha/enterobacter_project/metagenome/ecInfants/intermediate/02.ecInfants.maskedrna.fasta --dbdir /home_bif2/onnicha/squeezemeta_db/db > /home_bif/onnicha/enterobacter_project/metagenome/ecInfants/temp/bac.gff
Running barrnap for Archaea: /home_sbi_cold/onnicha/anaconda2/envs/SqueezeMeta/SqueezeMeta/bin/barrnap --quiet --threads 18 --kingdom arc --reject 0.1 /home_bif/onnicha/enterobacter_project/metagenome/ecInfants/intermediate/02.ecInfants.maskedrna.fasta --dbdir /home_bif2/onnicha/squeezemeta_db/db > /home_bif/onnicha/enterobacter_project/metagenome/ecInfants/temp/arc.gff
Running barrnap for Eukaryote: /home_sbi_cold/onnicha/anaconda2/envs/SqueezeMeta/SqueezeMeta/bin/barrnap --quiet --threads 18 --kingdom euk --reject 0.1 /home_bif/onnicha/enterobacter_project/metagenome/ecInfants/intermediate/02.ecInfants.maskedrna.fasta --dbdir /home_bif2/onnicha/squeezemeta_db/db > /home_bif/onnicha/enterobacter_project/metagenome/ecInfants/temp/euk.gff
Running barrnap for Mitochondrial: /home_sbi_cold/onnicha/anaconda2/envs/SqueezeMeta/SqueezeMeta/bin/barrnap --quiet --threads 18 --kingdom mito --reject 0.1 /home_bif/onnicha/enterobacter_project/metagenome/ecInfants/intermediate/02.ecInfants.maskedrna.fasta --dbdir /home_bif2/onnicha/squeezemeta_db/db > /home_bif/onnicha/enterobacter_project/metagenome/ecInfants/temp/mito.gff
Running RDP classifier: java -jar /home_sbi_cold/onnicha/anaconda2/envs/SqueezeMeta/SqueezeMeta/bin/classifier.jar classify /home_bif/onnicha/enterobacter_project/metagenome/ecInfants/temp/16S.fasta -o /home_bif/onnicha/enterobacter_project/metagenome/ecInfants/temp/16S.out -f filterbyconf
Stopping in STEP2 -> 02.rnas.pl. Program finished abnormally
```

However in your latest message you say that the program failed at step 10. Did you attach the right syslog file?

It seems that the sort command is running directly over `/tmp`. So maybe your data partition has a lot of free space but the partition in which `/tmp` is mounted does not. Can you check? Let us know, we should be able to fix it if that's the case.

**Comment by LeeNicha** [comment]
That's the correct file. If you scroll down, you will see this message
`[[0 seconds]: STEP10 -> 10.mapsamples.pl
Getting raw reads for P10441_S2: cp /home_bif/onnicha/enterobacter_project/metagenome/ecInfants/data/raw_fastq/P10441_S2_trimmed_1.fastq.gz /home_bif/onnicha/enterobacter_project/metagenome/ecInfants/temp/ecInfants.P10441_S2.current_1.gz; cp /home_bif/onnicha/enterobacter_project/metagenome/ecInfants/data/raw_fastq/P10441_S2_trimmed_2.fastq.gz /home_bif/onnicha/enterobacter_project/metagenome/ecInfants/temp/ecInfants.P10441_S2.current_2.gz; 
Aligning with bowtie2: cp /home_bif/onnicha/enterobacter_project/metagenome/ecInfants/data/raw_fastq/P10441_S2_trimmed_1.fastq.gz /home_bif/onnicha/enterobacter_project/metagenome/ecInfants/temp/ecInfants.P10441_S2.current_1.gz; cp /home_bif/onnicha/enterobacter_project/metagenome/ecInfants/data/raw_fastq/P10441_S2_trimmed_2.fastq.gz /home_bif/onnicha/enterobacter_project/metagenome/ecInfants/temp/ecInfants.P10441_S2.current_2.gz; 
Stopping in STEP10 -> 10.mapsamples.pl. Program finished abnormally](url)`

**Comment by fpusan** [comment]
Ok, so did you check the available free space in the partition where `/tmp` is mounted?

**Comment by LeeNicha** [comment]
I've checked the space of /tmp directory. It's 100G, which it might not enough. So I exported the temporary directory in /home_bif/ , which space has 4.9 TB left. Now it worked. 

Thank you for helping. :)

**Comment by jtamames** [comment]
Great to hear! Closing issue

**Comment by andreiprodan** [comment]
Hi!  I have the same problem, my SqueezeMeta run crashed at the end of step 10 with the same error "sort: write failed: /tmp/sort5suIKT: No space left on device.".
I restarted after updating to v1.3.1 but I'm concerned it will crash again at the same step. 
I have 5 TB of space but only 40 GB on the partition where /tmp is. 

How can i export the /tmp directory to the partition where I have enough space?

**Comment by jtamames** [comment]
Hello
Just copy the full project to the new location and restart. 
Best,

**Comment by LeeNicha** [comment]
Hi, @andreiprodan 
These are command that I used to export tmp directory
`mkdir tmp_dir`
`export TMPDIR='/home/user/tmp_dir'`
`export JOBLIB_TEMP_FOLDER='/home/user/tmp_dir'`

**Comment by andreiprodan** [comment]
@LeeNicha, thanks!
