### ISSUE TITLE
An error occurred while running sqm2tables.py

### ISSUE THREAD

**Issue by regisjr42** [jtamames/SqueezeMeta#222]
Hello,

I've run some publicly available metatranscriptome samples through SqueezeMeta, and that went very smoothly, but now I'm trying to analyze the results by following the SQMTools guide and I'm facing an error right at the beginning.

Whenever I try to run "loadSQM" it identifies my folder as a valid SqueezeMeta project, but when I try to start for real it gives out the error "An error occurred while running sqm2tables.py". I tried finding more information on this but to no luck, does anyone have an answer for me?

Some possible issues might be the fact that I used SqueezeMeta through my university server, but copied the resulting folder to my personal PC to use SQMTools here as I will not be able to analyze it via the server. But even that doesn't make much sense as I copied all the files and, at least as far as I know, followed the correct directory structure.

**Comment by fpusan** [comment]
> Some possible issues might be the fact that I used SqueezeMeta through my university server, but copied the resulting folder to my personal PC

Yes, it's because of that. But it can be easily fixed.

1) On your university server, run `sqm2tables.py /path/to/your/project /path/to/your/project/results/tables`
2) Copy the whole `/path/to/your/project` directory to your personal PC
3) SQMtools should now work fine, let me know if it doesn't

Happy new year!

Fernando

**Comment by regisjr42** [comment]
Hi!

Sorry for the delay in the answer, but I finally tested your solution and it did work fine, now everything is going smoothly. Thank you, Fernando!

**Comment by fpusan** [comment]
Glad to hear, closing issue!
