### ISSUE TITLE
Problems getting SQMtools working on windows

### ISSUE THREAD

**Issue by gruningerrj** [jtamames/SqueezeMeta#224]
I am trying to get SQMtools working with R but have been having problems installing the package in R. Sqeezemeta is running great on my server but I need to copy over the results from the remote server to my local windows computer to use R to analyze the results and I am having problems installing it. If I type install.packages("SQMtools") I get the following error: 
    
     "Installing package into ‘C:/Users/gruningerr.AAFC-AAC/Documents/R/win-library/4.0’
       (as ‘lib’ is unspecified)  
           Warning in install.packages :
             package ‘SQMtools’ is not available for this version of R

             A version of this package for your version of R might be available elsewhere,
             see the ideas at
             https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages"

I then tried to use Git to install the package but get the error below:

>>> C:/Users/###/AppData/Local/Programs/Git/cmd/git.exe clone --progress https://github.com/jtamames/SqueezeMeta/tree/master/lib/SQMtools SQMtools
Cloning into 'SQMtools'...
fatal: repository 'https://github.com/jtamames/SqueezeMeta/tree/master/lib/SQMtools/' not found

I am not sure what to do now and would appreciate if you have any guidance. I also saw an issue post about having to modify some other settings to get SQMtools to work properly when you copy it from a server where the job was run to a local computer but will tackle that once I get SQMtools installed in R.
Thanks for you help,
Rob

**Comment by fpusan** [comment]
Hi!

We haven't tried installing SQMtools in windows, I guess it should work.

SQMtools is not available in CRAN. The easiest way to get it is to install SqueezeMeta with conda, but since you are using windows I'm not sure that will work.

Alternatively, you can just clone the whole SqueezeMeta repository (`git clone https://github.com/jtamames/SqueezeMeta`) and install SQMtools manually.

```
R
# First install the dependencies
install.packages("doMC")
install.packages("ggplot2")
install.packages("data.table")
install.packages("reshape2")
install.packages("BiocManager")
BiocManager::install("pathview")
quit(save="no") # And exit R
# Then from the command line install SQMtools
R CMD INSTALL /path/to/SqueezeMeta/lib/SQMtools
```

This might not work out of the box in windows (I'm not familiar with the Windows command line) but something along these lines should do the trick. You can also install it using RStudio, but if memory serves you'll need to compress the `/path/to/SqueezeMeta/lib/SQMtools` directory first.

Let me know if this works for you,

Fernando

**Comment by gruningerrj** [comment]
This didn't work for me. I wasn't able to get SQMtools installed and doMC is not available for windows. I am not sure if that is an essential package but if it is I don't know if this will work at all on windows.

**Comment by fpusan** [comment]
An alternative under windows would be to use WSL2 (https://docs.microsoft.com/windows/wsl/install-win10), or a standard VM with linux.

**Comment by gruningerrj** [comment]
The issue is that the organization I work for locks down our computer systems and will only allow approved software to be installed. I don't have the ability to use Rstudio on our remote system and my local resources are windows so my options are pretty limited. I guess this is just one of the challenges of being in an organization that keeps tight control of our computers and network.

**Comment by fpusan** [comment]
Yeah, I did my Ph.D. on one of those, I feel your pain ;)
Is there any way you can get access to an interactive linux server? So you can run SQMtools there via ssh (no RStudio, just the terminal, but you can still see the figures via X11 forwarding).

**Comment by jtamames** [comment]
Hey
Working in your personal laptop is not an option?

**Comment by gruningerrj** [comment]
I will look into the X11 forwarding and get in touch with our server admin folks. I was under the impression you needed to use R/Rstudio to generate the plots. 

@jtamames, I have more control of installing programs like SqueezeMeta using Conda and have been encouraging others in the organization to try it. So far running the pipeline has been very painless (although I have a job running that has been going for over a month due to the size of the job). I just need to figure out now how to start interpreting the results which seem to require visualization which has been causing me headaches.

**Comment by fpusan** [comment]
Yes you need R for the plots, just not necessarily Rstudio. So if you open an R session from your console (just type `R` when the conda environment is activated) you should be able to work interactively just fine.

**Comment by gruningerrj** [comment]
I am still learning how to use R efficiently and consider myself a newbie with experience limited to Rstudio but I will look into using R on cmd line.

**Comment by regisjr42** [comment]
Hello, sorry for intruding here, but I am also using RStudio on Windows to go over my SqueezeMeta output and faced the same issue when trying to install SQMtools.

The way I got over that was by following this topic [here](https://github.com/jtamames/SqueezeMeta/issues/60) where our friend Fernando linked in his last post there a .tar.gz file for the SQMtools package folder and using that to directly install via RStudio worked wonders for me!

**Comment by fpusan** [comment]
Thanks for the contribution @regisjr42! I wasn't sure whether anyone had succeeded running SQMtools in Windows. @gruningerrj maybe you can try that, start by trying to install SQMtools, and if it asks for a dependency install that too.

**Comment by gruningerrj** [comment]
I downloaded the tar.gz file and was able to install SQMtools with Rstudio! Thanks for the help with this everyone.

Can you verify whether I need to have the entire Squeezemeta output folder moved over from the remote server to my laptop or can I just move over the 'Results' directory that is embedded in the main output directory?

**Comment by fpusan** [comment]
Quite sure it will work if you move the `SqueezeMeta_conf.pl` file, and the `results` and `intermediate` directories.
Make sure to run `sqm2tables.py` in your organization's cluster before moving the project to you personal laptop, as described in #222.
Let me know how it goes.

**Comment by gruningerrj** [comment]
Do I also need to run sqmreads2tables.py as well? I am not clear what the difference between these is

**Comment by fpusan** [comment]
Nope, no need. `sqmreads2tables.py` is for projects generated using the `sqm_reads.pl` script. Yours (I assume) was generated using the standard `SqueezeMeta.pl` pipeline.

**Comment by gruningerrj** [comment]
Great. I'll let you know how things go and will try and put together a document to summarize how to analyze results in Rstudio on windows after running the pipeline on a remote server.

**Comment by gruningerrj** [comment]
It is working! Last thing I needed to do after running sqm2tables.py on the server was moving SqueezeMeta_conf.pl, results and intermediate directories to my local computer AND ensuring the directory structure on my local computer was the same as that on the remote server and then I was able to load the project into Rstudio and I can follow the wiki tutorial for exploring the data. Thanks a lot for the help

**Comment by fpusan** [comment]
Glad to hear! Closing issue
