### ISSUE TITLE
18. Project_Name.DASTool.checkM is empty

### ISSUE THREAD

**Issue by sua474** [jtamames/SqueezeMeta#225]
[Log and Screenshot.zip](https://github.com/jtamames/SqueezeMeta/files/5791179/Log.and.Screenshot.zip)
Please take a look at the attached logs and error screenshot. I have tried executing the steps multiple times, but it has been failing over Step-18. All the folder permissions are 777.

**Comment by jtamames** [comment]
Hello!

I would say that checkM is not properly configured, and it is not finding its profile files. Could you run the script `test_install.pl` in the `utils/install_utils/` directory of SqueezeMeta?

**Comment by jtamames** [comment]
Ok, I realize now that you have a single bin, and it is from Eukarya. CheckM does now work for eukaryotes. Should you have any other prokaryotic bin, it would get some results and go ahead, but since this is the only one, it stops because of not finding any result in that step. Try restarting in step 19, I think it should work:
`perl restart.pl MetaGenome_D2000129 -step 19`

**Comment by sua474** [comment]
Thank you for your invaluable suggestion!

I ran test_install.pl script and it shows success for each test. Also, I restarted from Step-19 and the pipeline has completed successfully. One question though, how do I set the number of bins? The program provides only below mentioned parameters, which don't pertain to the number of Eukarya bins. I was thinking of nobins=yes should suffice.

Available Parameters:
--nobins: Skip binning (Default: no)
--nomaxbin: Skip MaxBin binning (Default: no)
--nometabat: Skip MetaBat2 binning (Default: no)

**Comment by jtamames** [comment]
Hello again
The user does not set the number of bins, the binning programs are providing them. You could try to set to zero the variable `$score_tres16` in file `parameters.pl`, in the scripts directory. That variable sets a threshold for completeness used to keep or discard bins. Setting it to zero will keep all bins. By default is set to 0.25, so if you get more bins, these will be very small. 
Notice the --nobins flag (it is not needed to set it to 'yes', just invoke it as '--nobins') will not change the binning behaviour, instead it will skip it completely.

Best,
Javier

**Comment by sua474** [comment]
Thank you so much Javier for the comprehensive explanation!
