### ISSUE TITLE
Fraction of eukaryotic reads from sqm_reads run ?

### ISSUE THREAD

**Issue by EricRaes** [jtamames/SqueezeMeta#227]
Hi guys,

Happy new year!

I hope you would be able to give some advice in regards my question below.

I ran the sqm_reads script to get functional assignments (fun3 algorithm) for a number of shotgun samples along a transect. My data analyses predominately focus on prokaryotes, but, no doubt, some of the functional pathways will be eukaryotic. 

A reviewer asked me to provide the percentage of the reads that are Eukaryotic. Would you suggest that the best way to tackle this question is to look at the taxonomy output (from the LCA) ?

Or would you have another suggestion that would allow me to estimate/calculate the percentage of eukaryotic reads ?

Again, many thanks for advice!
Best regards,
Eric

**Comment by fpusan** [comment]
Yes, that's what I would do!

**Comment by jtamames** [comment]
Hello!

You just need to look at the 11.*.mapcount file, which lists how many reads and bases mapped to the contigs that were taxonomically assigned.
You will be missing the reads that were unmapped or these mapping to the few unassigned contigs, but I think it is enough for your purposes (I would be happy with that if I was your reviewer).
Another way will be to run sqm_reads which gives a direct classification of reads, but I won´t bother.

Best,
Javier

**Comment by EricRaes** [comment]
Thank you!!

**Comment by jtamames** [comment]
Hey Eric! We just saw your nice Nat Comms paper. Congratulations!! And thanks for using SQM for that.
Best,
Javier

**Comment by EricRaes** [comment]
Thanks Javier! And for your help and advice :-) !!
