### ISSUE TITLE
How to subset bins based on percent completeness and contamination

### ISSUE THREAD

**Issue by gruningerrj** [jtamames/SqueezeMeta#228]
I'm working through some results of my SqueezeMeta.pl run and am having trouble figuring out how to subset the SQM object in R to select all High Quality bins. For this I am using a cutoff of greater than or equal to 90% completeness and < 10% contamination. I can't find out how to write the subsetBin() command in SQMtools to define these cutoffs. 

Thanks!
Rob

**Comment by fpusan** [comment]
Hi! `subsetBins` works with a vector of bin names, which you have to create beforehand. SO
```
goodBinNames = rownames(SQM$bins$table)[SQM$bins$table$Completeness>90 & SQM$bins$table$Contamination<10]
goodBins = subsetBins(SQM, goodBinNames )
```

**Comment by gruningerrj** [comment]
Perfect! Thank you
