### ISSUE TITLE
sqm_counter very slow

### ISSUE THREAD

**Issue by kassammohamed** [jtamames/SqueezeMeta#230]
Hello,

I was checking the sqm_counter step and it is very slow, it used only one cpu for reading the mapping file.
Is it normal ?

**Comment by jtamames** [comment]
Hello

Please update to 1.3.0, as it includes a multithreading counting step.

Best,
Javier

**Comment by kassammohamed** [comment]
Hello 
Actually I am using the v1.3 and using the threads option but when reading the sam file with minimap at the sqm-counter it is only using one cpu .

**Comment by jtamames** [comment]
Hello again

Apparently this feature was not included in the last release. We will be relasing 1.3.1 next week, and this will be included. In the meantime, you can switch to the development branch, download the script 10.mapsamples_multi.pl, and replace your 10.mapsamples.pl with that one (just rename 10.mapsamples_multi.pl to 10.mapsamples.pl). That will make it.

Best,
Javier

**Comment by kassammohamed** [comment]
Ok thanks, will try that
