### ISSUE TITLE
subset Taxa from SQMlite object

### ISSUE THREAD

**Issue by mradz19** [jtamames/SqueezeMeta#233]
I was wondering what the best way is to subset taxonomy from sqmlite objects? I ran squeezemeta on RNA reads using sqm_reads.pl as my mapping rate was poor (<50%) for a lot of samples. I just wanted to subset the bacteria only at the species level but I'm not sure the best way to do this when dealing with a sqmlite object.

**Comment by fpusan** [comment]
Hi. Subsets are not supported in SQMlite objects, and this is unlikely to change in the near future.
If your project originates from `sqm_reads.pl`, you can actually make it happen outside SQMtools with some scripting. See #127 for some details on that.

**Comment by mradz19** [comment]
I see you mention using <project_name>.out.allreads, do you have any advice on scripting to pull out just the bacterial annotations?

**Comment by fpusan** [comment]
Yes, here's an example on what the file looks like:

```
# Sample	File	Read	Tax	COG	KEGG	CAS
H1s	SRR1927149.1000	pair1	k_Bacteria		COG1530*	K08301*	
H1s	SRR1927149.1000	pair2	k_Bacteria		COG1530*	K08301*	
H1s	SRR1927149.1001	pair1	c_Gammaproteobacteria		ENOG410YJEW*		
H1s	SRR1927149.1001	pair2	f_Succinivibrionaceae				
H1s	SRR1927149.1002	pair1	g_Prevotella		COG2310*	K05791*	
H1s	SRR1927149.1003	pair1	s_Lachnospiraceae bacterium				
H1s	SRR1927149.1003	pair2	s_Lachnospiraceae bacterium				
H1s	SRR1927149.1005	pair1	s_Bacteroidaceae bacterium
```

So for each read you have together the taxonomy and the function, you can filter the reads from the taxonomies of interest and then aggregate the data to obtain the abundances of each function in the subset.

In this file taxonomies are only shown at the lowest possible level: e.g. `f_Succinivibrionaceae` indicates that the read could only be classified at the family level. If you wanted to consider that read e.g. at the phylum level you would have to go to the `path/to/databases/db/LCA_tax/parents.txt` file and search for Succinivibrionaceae. You will get a line like this:

`Succinivibrionaceae    superkingdom:Bacteria;phylum:Proteobacteria;class:Gammaproteobacteria;order:Aeromonadales;family:Succinivibrionaceae``
Containing the higher-rank taxonomy. In this case the phylum would be `Proteobacteria`

**Comment by fpusan** [comment]
Also, I would not subset the data at the species level. In general, unless the actual species in your data are well represented in the reference database, any method that makes speciel-level predictions from metagenomic data is being overconfident. SqueezeMeta will for the most part mark those as Unclassified. See my rant in #172 for more info on this.

**Comment by mradz19** [comment]
Ahh thanks for that. Do you have a script that I could use to only pull out bacteria annotations? There is quite a few reads which are classified as eukaryotic or viral

**Comment by fpusan** [comment]
No, sorry, I don't have the script at the moment. You'll have to use grep or code something yourself :(

**Comment by mradz19** [comment]
Hi fpusan, I've been having trouble working out how I can pull out taxonomy and function for bacteria only from that output file. As the taxonomies are at all levels I'm not sure how to write a script to pull out all "bacteria" when a lot of the annotations are at other levels (phylum, genus, etc).

Is there a major concern with using the output of the normal squeezemeta run if the mapping rate for a few samples is between 40 and 50%? It's much easier using the output from a full squeezemeta run

**Comment by mradz19** [comment]
I was wondering could the -singletons options be used to help with this in a normal run? When would you use that option?

**Comment by fpusan** [comment]
Hi! Sorry for the late answer, been a couple crazy weeks :)
The singletons option would indeed help you with this. Only downside is that the results table might be really big, but maybe it's worth trying.
