### ISSUE TITLE
Getting Unclassified species

### ISSUE THREAD

**Issue by kassammohamed** [jtamames/SqueezeMeta#234]
Hello,

When I look to the prop of my species, I see mostly unclassified species annotation. Is it due to the reference db or id percent during the mapping ?

**Comment by jtamames** [comment]
Hello!

Do you mean that the ORFs/contigs are not annotated at the species rank? That is pretty usual because of the filters that we put for taxonomic assignment (see [this post](https://github.com/jtamames/SqueezeMeta/wiki/A-discussion-on-taxonomic-annotation-and-the-meaning-of-disparity-values-of-contigs) for a detailed explanation). In summary, you will get species annotation only when you have a very reliable hit. This behaviour can be skipped if you use the 06*noidfilter.wranks file instead of the 06*wranks, but I wouldn´t recommend it, since I would go for quality better than quantity.

Best,
Javier

**Comment by kassammohamed** [comment]
Hello Javier, thank you very much for your input.
From my understanding the score option is in here :

`$scoreratio6=0.8;   #-- STEP6/8: Ratio first score/currsent score for the hit to be considered
$diffiden6=10;       #-- STEP6/8: Maximim identity difference with the first
$flex6=0.2;           #-- STEP6/8: Allows this PERCENTAGE (if less than one) or NUMBER (if greater than one) of hits from different taxa than LCA
$minhits6=2;        #-- STEP6/8: Minimum number of hits for the taxa (if there is only one valid hit, this value sets to one automatically
$noidfilter6=1;	#-- STEP6/8: Set to 1, creates a new set of results with no identity filters

$mindif7=0.1;		     #-- STEP7: Percentage of difference in scores for assigning bestaver
$maxhits7=3;	     #-- STEP7: Maximum number of hits for averaging
$minolap7=30;		     #-- STEP7: Minimum alignment percentage between query and hit

$mingenes9=1;			     #-- STEP9: Minimum number of genes for the contig 
$minconsperc_asig9=0.7;      #-- STEP9: Ratio genes for the taxon/sum(genes all taxa). Therefore it only considers assigned genes
$minconsperc_total9=0.5;     #-- STEP9: Ratio genes for the taxon/number of genes. Therefore it considers all (assigned+unassigned) genes
			     #-- THIS ONE can be set by arguments, because of its influence when using long reads
	`

**Comment by jtamames** [comment]
Sorry, I don't understand your question precisely.. You mean how to use the results without filters? If so, rename your `06.<project>.fun3.tax.noidfilter.wranks` file to `06.<project>.fun3.tax.wranks` (keep a copy of the original one), and run scripts 09, 11, 13 and 22.
Best,
J

**Comment by kassammohamed** [comment]
Dear Javier,

thank you for pointing to me the files to change.
So I checked the 06.lca file, is this the percentage THT we use for classification ?


my @ranks=('species','genus','family','order','class','phylum','superkingdom');
my %idenrank=('species',85,'genus',60,'family',55,'order',50,'class',46,'phylum',42,'superkingdom',40);

**Comment by jtamames** [comment]
Yes, exactly

**Comment by jtamames** [comment]
Closing issue, feel free to reopen
