### ISSUE TITLE
Does pipeline run QC on sample read files by default?

### ISSUE THREAD

**Issue by gruningerrj** [jtamames/SqueezeMeta#235]
Hi Javier,

I am not sure if I should be providing SqueezeMeta with reads that have already been through a QC step or if it does this automatically prior to assembly? I see there is an option to run Trimmomatic but it appears this is not done unless you add "--cleaning Yes" to the command. In this case, would you also have to include -cleaning_options [string] as well or would it use the default cleaning option string? 

Thanks,
Rob

**Comment by jtamames** [comment]
Hello
I always recommend the users to do their own QC control and cleaning before feeding the reads to SqueezeMeta. But of course you can use the trimmomatic embedded. It suffices saying "--cleaning". If you do not activate cleaning_options, it will run with default parameters. For customizing, add --cleaning_options "trimmomatic options here". Do not forget the quotes.

Best,
J
