### ISSUE TITLE
Cannot download database

### ISSUE THREAD

**Issue by michoug** [jtamames/SqueezeMeta#24]
Hi
Here is the error I got when downloading the main database

`Downloading and unpacking database tarball...
--2019-07-01 11:31:34--  http://silvani.cnb.csic.es/SqueezeMeta/SqueezeMetaDB.tar.gz
Resolving silvani.cnb.csic.es (silvani.cnb.csic.es)... 150.244.82.96
Connecting to silvani.cnb.csic.es (silvani.cnb.csic.es)|150.244.82.96|:80... failed: Connection timed out.
Retrying.`

Best
Greg

**Comment by fpusan** [comment]
Yeah. Our institutions internet is down at the moment. Hopefully it will
get fixed soon

**Comment by fpusan** [comment]
Should be working now

**Comment by wangjiawen2013** [comment]
I met this error too now. Perhaps the internet is down again. Hope to fix that as soon as possible.

**Comment by fpusan** [comment]
Did you manage to download it? It appeared to be working this afternoon.

**Comment by wangjiawen2013** [comment]
I managed to download test.tar.gz and classifier.tar.gz, while cannot download SqueezeMetaDB.tar.gz, here is the output:
--2019-10-14 09:00:22--  http://silvani.cnb.csic.es/SqueezeMeta/SqueezeMetaDB.tar.gz
Resolving silvani.cnb.csic.es (silvani.cnb.csic.es)... 150.244.82.96
Connecting to silvani.cnb.csic.es (silvani.cnb.csic.es)|150.244.82.96|:80... failed: Connection timed out.
Retrying.

--2019-10-14 09:02:36--  (try: 2)  http://silvani.cnb.csic.es/SqueezeMeta/SqueezeMetaDB.tar.gz
Connecting to silvani.cnb.csic.es (silvani.cnb.csic.es)|150.244.82.96|:80... failed: Connection timed out.
Retrying.

--2019-10-14 09:04:45--  (try: 3)  http://silvani.cnb.csic.es/SqueezeMeta/SqueezeMetaDB.tar.gz
Connecting to silvani.cnb.csic.es (silvani.cnb.csic.es)|150.244.82.96|:80... failed: Connection timed out.
Retrying.

--2019-10-14 09:06:55--  (try: 4)  http://silvani.cnb.csic.es/SqueezeMeta/SqueezeMetaDB.tar.gz
Connecting to silvani.cnb.csic.es (silvani.cnb.csic.es)|150.244.82.96|:80... failed: Connection timed out.
Retrying.

--2019-10-14 09:09:06--  (try: 5)  http://silvani.cnb.csic.es/SqueezeMeta/SqueezeMetaDB.tar.gz
Connecting to silvani.cnb.csic.es (silvani.cnb.csic.es)|150.244.82.96|:80... failed: Connection timed out.
Retrying.

--2019-10-14 09:11:19--  (try: 6)  http://silvani.cnb.csic.es/SqueezeMeta/SqueezeMetaDB.tar.gz
Connecting to silvani.cnb.csic.es (silvani.cnb.csic.es)|150.244.82.96|:80... failed: Connection timed out.
Retrying.

--2019-10-14 09:13:32--  (try: 7)  http://silvani.cnb.csic.es/SqueezeMeta/SqueezeMetaDB.tar.gz
Connecting to silvani.cnb.csic.es (silvani.cnb.csic.es)|150.244.82.96|:80... failed: Connection timed out.
Retrying.

--2019-10-14 09:15:46--  (try: 8)  http://silvani.cnb.csic.es/SqueezeMeta/SqueezeMetaDB.tar.gz
Connecting to silvani.cnb.csic.es (silvani.cnb.csic.es)|150.244.82.96|:80... failed: Connection timed out.
Retrying.

--2019-10-14 09:18:02--  (try: 9)  http://silvani.cnb.csic.es/SqueezeMeta/SqueezeMetaDB.tar.gz
Connecting to silvani.cnb.csic.es (silvani.cnb.csic.es)|150.244.82.96|:80... failed: Connection timed out.
Retrying.

--2019-10-14 09:20:18--  (try:10)  http://silvani.cnb.csic.es/SqueezeMeta/SqueezeMetaDB.tar.gz
Connecting to silvani.cnb.csic.es (silvani.cnb.csic.es)|150.244.82.96|:80... failed: Connection timed out.
Retrying.

--2019-10-14 09:22:35--  (try:11)  http://silvani.cnb.csic.es/SqueezeMeta/SqueezeMetaDB.tar.gz
Connecting to silvani.cnb.csic.es (silvani.cnb.csic.es)|150.244.82.96|:80... failed: Connection timed out.
Retrying.

--2019-10-14 09:24:52--  (try:12)  http://silvani.cnb.csic.es/SqueezeMeta/SqueezeMetaDB.tar.gz
Connecting to silvani.cnb.csic.es (silvani.cnb.csic.es)|150.244.82.96|:80... failed: Connection timed out.
Retrying.

--2019-10-14 09:27:10--  (try:13)  http://silvani.cnb.csic.es/SqueezeMeta/SqueezeMetaDB.tar.gz
Connecting to silvani.cnb.csic.es (silvani.cnb.csic.es)|150.244.82.96|:80... ^C

**Comment by wangjiawen2013** [comment]
I could downloaded it several days ago in China. But now I cannot connect to the link. My friend in America told me that he could downloaded it. So perhaps it was caused by our Internet.

**Comment by fpusan** [comment]
An alternatively would be to compile the databases from scratch using make_databases.pl
That script does not download anything from silvani.cnb.csic.es, so it might work.

**Comment by wangjiawen2013** [comment]
I finally download the database after several time's failure with the help of my American friends. I think the large database hinder the promotion of SqueezeMeta. After all, not all regions own a high quality internet connection. May be you can move the large files to NCBI or other servers.

**Comment by wangjiawen2013** [comment]
It takes me about one month to download the database. It depended on lucy. Sometimes it's fast and sometimes not.

**Comment by fpusan** [comment]
Download speed is usually fast (less than two hours) but it might be region dependent.
Please note that, as stated in my previous mail, you can download the large files directly from NCBI using the _make_databases.pl_ script instead of _download_databases.pl_

**Comment by chilltrout** [comment]
I think your hosting is down again, Its kinda annoying that even the make_databases.pl script still uses your university hosting for 

- http://silvani.cnb.csic.es/SqueezeMeta/db.tar.gz

- http://silvani.cnb.csic.es/SqueezeMeta/kegg.db.gz

is there some way to build without these or move to AWS/Google?

**Comment by fpusan** [comment]
Hi,
Both links are working for me right this moment. Are you perhaps behind a firewall?

**Comment by chilltrout** [comment]
Im guessing its your routing, was working last night/today on the uni supercomputer but not now on super computer or my local device.
I just get a weird apache page on chrome
Hosting might be banning my IP for using too much bandwidth?

**Comment by fpusan** [comment]
It shouldn't be banning it, but I am no expert in web hosting.

You say it worked in your uni server yesterday? Did it manage to complete? If it keeps failing let me know and I'll upload them to an alternative server

**Comment by fpusan** [comment]
Hi again,
As per 4957661, we have added an alternative `make_databases.pl` script pointing to a different download server. This might fix your issues.
If you want to test it, please download the `SqueezeMeta/utils/install_utils/make_databases_alt.pl` and `SqueezeMeta/utils/install_utils/configure_nodb_alt.pl` from the master branch, place them in the corresponding directories of your local installation, and try running `make_databases_alt.pl`.
