### ISSUE TITLE
SqueezeMeta database error

### ISSUE THREAD

**Issue by anilchauhanhp9** [jtamames/SqueezeMeta#240]
Hi, I dowloaded the squeezemeta and its database. However when i ran test_install.pl command i got this error
WARNING: Some SqueezeMeta dependencies could not be found in your environment!
	SqueezeMeta_conf.pl says that databases are located in /home/hamlab/SqueezemetaDB but we can't find nr.db there, or it is corrupted
please help me in resolving the issue

**Comment by jtamames** [comment]
Hello
Could you run `configure_nodb.pl /path/to/your/database` and see if that solves the problem?
Best,
J

**Comment by anilchauhanhp9** [comment]
Hello Sir,
I ran the above command and got the same error again.

**Comment by anilchauhanhp9** [comment]
Hello,
I ran the above command and the issue is now resolved.
Thank you...
