### ISSUE TITLE
sqm2tables.py: FileNotFoundError: [Errno 2] (...) 09.projectname.contiglog.noidfilter

### ISSUE THREAD

**Issue by seppedm** [jtamames/SqueezeMeta#243]
Hi there,

I'm trying to load a run from version 1.2 into SQMtools v.0.6.1, but I get the following error. I already applied the $mappingstat = "$resultpath/10.$projectname.mappingstat" tweak, which worked perfectly. The pc is right, in none of my projects there is a 09.projectname.contiglog.noidfilter file. What to do, what to do? 

I previously successfully loaded it into SQMtools v0.5, but I would specifically would like to use the combineSQMlite function in v0.6, combining multiple sqm runs. If possible, the noidfilter would be a nice plus, but definitely not necessary. 

> Traceback (most recent call last):
>   File "/path/SqueezeMeta-master/utils/sqm2tables.py", line 214, in <module>
>     main(parse_args())
>   File "/path/SqueezeMeta-master/utils/sqm2tables.py", line 125, in main
>     contig_tax_nofilter, contig_tax_nofilter_wranks = parse_contig_tax(perlVars['$interdir'] + '/09.' + perlVars['$projectname'] + '.contiglog.noidfilter')
>   File "/path/SqueezeMeta-master/utils/../lib/utils.py", line 321, in parse_contig_tax
>     with open(contiglog) as infile:
> FileNotFoundError: [Errno 2] No such file or directory: '/path/to/project//intermediate/09.final_run_batch1.contiglog.noidfilter'

Thanks in advance!!

**Comment by fpusan** [comment]
Yeah, we mentioned this in the release notes, but it's better to have it in the issues section too

- `loadSQM` (from SQMtools) and `sqm2tables.py` will fail when trying to parse projects created with versions prior to v1.3.1. To make the project work in 1.3.1, please:
    1) Run step 9 again (`perl 09.summarycontigs3.pl /path/to/your/project`).
    2) Remove the `/path/to/your/project/results/tables`, if present.

Let me know if this works for you!

**Comment by seppedm** [comment]
Thanks for the quick response, I'll try that!

**Comment by fpusan** [comment]
I will keep this issue open, as I suspect it will be helpful for more people.

**Comment by fpusan** [comment]
Also make sure you use the `09.summarycontigs3.pl` and `sqm2tables.py` scripts from version 1.3.1 (or higher, if reading this in the future).

**Comment by seppedm** [comment]
Hi Fernando,

I tried your advice and it works fine, I can load my data now. Thanks for that!

There is one odd thing left. The resulting assignment is different from the previous one I made. Not very dramatically in one run, but quite more so in another, where I had a huge amount of Eukaryote reads (Chinese hamster, utterly unexpected in permafrost samples and I expect there is definitely something wrong there), which had lowered considerably after rerunning step 9 and using the new SQMtools. What is the cause of this and should other steps maybe also be rerun? 

Best,
Seppe

**Comment by fpusan** [comment]
Hi! Sorry for the late answer.
We made some changes/fixes on how the consensus taxonomies are calculated. In general they had a negligible impact, but it could become noticeable if you have a lot of Eukaryote reads.

What specific change have you noticed? Less chinese hamster reads? (which sounds like a good thing to me). Are those reads now assigned to something else?

No need to re-run anything other than step 9 and sqm2tables, which you already did.

**Comment by seppedm** [comment]
Indeed, the only major difference seems to be less chinese hamster, although they are still quite some left. I think these reads have mostly turned into 'unassigned'. There is still something curious going on with these samples, but my gut tells me that's not related to the pipeline

**Comment by jtamames** [comment]
Closing issue, feel free to reopen
