### ISSUE TITLE
SQMtools: Error in subsetTax

### ISSUE THREAD

**Issue by seppedm** [jtamames/SqueezeMeta#245]
Dear developers,

When trying `subsetTax(batch1, rank = "superkingdom", tax = "Bacteria")` in SQMtools v0.6.1, I get the following error: `Error in t.default(subSQM$bins$tpm) : argument is not a matrix`. In my run I used the --nobins option, this might have something to do with it? Other functions like `subsetORFs` work fine. 

Traceback looks like this: 
```
6. | t.default(subSQM$bins$tpm)
5. | t(subSQM$bins$tpm)
4. | t(t(subSQM$bins$tpm)/colSums(subSQM$bins$tpm))
3. | subsetORFs(SQM, goodORFs, tax_source = "contigs", trusted_functions_only = trusted_functions_only,      ignore_unclassified_functions = ignore_unclassified_functions,      rescale_tpm = rescale_tpm, rescale_copy_number = rescale_copy_number)
2. | subsetContigs(SQM, goodContigs, trusted_functions_only = trusted_functions_only,      ignore_unclassified_functions = ignore_unclassified_functions,      rescale_tpm = rescale_tpm, rescale_copy_number = rescale_copy_number)
1. | subsetTax(batch1, "superkingdom", "Bacteria")
```

Thanks in advance!
Seppe

**Comment by fpusan** [comment]
Hi!
I think I already fixed this last week in 42ddeb8.
Maybe you can clone the master branch from our repo and install the latest SQMtools from there?
`R CMD INSTALL /path/to/SqueezeMeta_master/lib/SQMtools`. Version should show as 0.6.2.
Let me know if it works afterwards.

**Comment by seppedm** [comment]
It works perfectly, thank you very much!!

**Comment by fpusan** [comment]
Glad to hear! Closing issue
