### ISSUE TITLE
Cannot download database

### ISSUE THREAD

**Issue by FilipeMatteoli** [jtamames/SqueezeMeta#246]
I installed SqueezeMeta but after trying the download scripts several times I just gave up using them. My internet is very slow and may be interrupted at any time, the expected download time for me was 30h. Thus, third-world users like me would benefit from a manual download/install of the required databases.

How can this be accomplished?

**Comment by jtamames** [comment]
Hello
Did you try the make_databases.pl script? That will attempt to download the databases from their sources, but it probably won´t solve the your problems with a slow connection. Don´t you know anybody with a better connection than yours? He/she could download the databases and pass them to you in a USB drive, for instance

**Comment by fpusan** [comment]
If this does not work, try the following
- Download the databases with `wget http://silvani.cnb.csic.es/SqueezeMeta/SqueezeMetaDB.tar.gz`
- If it stops midway, resume as described in https://www.cyberciti.biz/tips/wget-resume-broken-download.html
- When finished, uncompress the tar.gz. You will obtain a directory called `db`
- Run `perl /path/to/SqueezeMeta/utils/install_utils/configure_nodb.pl /download/path/db`, where `db` is the directory you obtained in the previous step.
- Run `perl /path/to/SqueezeMeta/utils/install_utils/test_install.pl`. It should locate the databases.

**Comment by FilipeMatteoli** [comment]
Thanks, it is good to know that I can either download it elsewhere then paste in my PC or download it through wget. Trying right now and resumed safely using -c. One of the main problems is that my internet stops for seconds and come back, to fix this in such a huge download I am using the following:
wget -c --tries=0 --read-timeout=20 http://silvani.cnb.csic.es/SqueezeMeta/SqueezeMetaDB.tar.gz
