### ISSUE TITLE
Step2 Error: GLIBC_2.14 not found

### ISSUE THREAD

**Issue by sturne29** [jtamames/SqueezeMeta#247]
I installed the Conda version of SqueezeMeta and am consistently getting the same error on the tRNA/tmRNA prediction step with Aragorn. Error message below. 

`/mnt/store2/home/sturne29/miniconda3_clean/envs/squeezemeta/SqueezeMeta/bin/arag                                     orn: /lib64/libc.so.6: version 'GLIBC_2.14' not found (required by /mnt/store2/h                                     ome/sturne29/miniconda3_clean/envs/squeezemeta/SqueezeMeta/bin/aragorn)`

I tried installing a glibc-2.14 conda package, but it didn't help the problem. Any ideas what I can do about this? Thank you in advance and let me know if there is other info I can provide.

**Comment by jtamames** [comment]
Hello
The problem seems to be in libc6. If you google the error "version 'GLIBC_2.14' not found" you will find many responses to the issue, pointing to diferent solutions, mostly updating libc6 or installing libc-devel. Try if any of these work for you.
Best,
Javier

**Comment by fpusan** [comment]
Hi again!
What OS / conda version / SqueezeMeta version are you using?

**Comment by sturne29** [comment]
OS: centos-release-6-9.el6.12.3.x86_64
Conda: 4.7.10
SqueezeMeta: 1.3.1

**Comment by fpusan** [comment]
Oof, yep, we only support CentOS7. Some binaries might fail. I think that you might be able to get everything up and running, but you will need to manually compile some of the programs. The idea would be:

1) Run SQM until a binary fails.
2) Locate the failing binary (in this case `/mnt/store2/home/sturne29/miniconda3_clean/envs/squeezemeta/SqueezeMeta/bin/aragorn`).
3) Our ReadMe file has links to all the external software (in this case http://www.ansikte.se/ARAGORN/)
4) Download the source code and compile it, replace SqueezeMeta's default binary by the new one. Hopefully it will work.

Some programs might be a bit more tricky (e.g. they are not a single binary, but a collection of binaries and shared libraries). But let's try to fix ARAGORN first, and see what else fails.

Alternatively, if you have a system with CentOS7 or Ubuntu 14+, everything should work out of the box for you.

**Comment by jtamames** [comment]
Closing issue, feel free to reopen
