### ISSUE TITLE
Issue with combineSQM in R

### ISSUE THREAD

**Issue by mradz19** [jtamames/SqueezeMeta#248]
I am trying to look at annotations associated with Biofilm and quorum sensing together. I first subset bacteria from my project:
```
bacteria <- subsetTax(spades, 'superkingdom','Bacteria', rescale_copy_number=F)
```
I then subset my functions:
```
biofilm<-subsetFun(bacteria, fun='Biofilm', rescale_copy_number=F)
quorum<-subsetFun(bacteria, fun="Quorum", rescale_copy_number=F)
```
Then I try combining them:
```
combined<-combineSQM(biofilm, quorum, rescale_copy_number=F)
```
And I get this error:
```
Error in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),  : 
  'data' must be of a vector type, was 'NULL'
```
I have also tried adding the tax_source=T or =contigs but I get the same error. Am I doing something in the wrong order?

Also one other question, this is RNA data and I was hoping to graph the total number of reads associated with quorum sensing and biofilm to each individual sample. What is the best way to do this? I understand I cannot just sum all of the reads aligned to each function then map that as it should be normalized some way. Is there a way to combined the TPM results? Or calculate TPM for the combined raw counts?

**Comment by fpusan** [comment]
Hi!

Can you clone the master branch from the repository, install SQMtools from there (`R CMD INSTALL /path/to/SqueezeMeta-master/lib/SQMtools`) and see if it fixes it?

Regarding the second section, would `subsetFun` from SQMtools be enough? The TPM's per sample of the subsetted object should be what you need.

**Comment by jtamames** [comment]
Closing issue, feel free to reopen
