### ISSUE TITLE
STEP16 -> DAS_TOOL MERGING: 16.dastool.pl

### ISSUE THREAD

**Issue by anilchauhanhp9** [jtamames/SqueezeMeta#250]
Hi,
I ran the pipeline on my nanopore data and got the error at step 16. the full error message is as follow
**Can't open /home/hamlab/sample2/results/DAS/sample2_DASTool_bins directory, no DAStool results
WARNING: File /home/hamlab/sample2/results/DAS/sample2_DASTool_bins/ is empty!. DAStool did not generate results
Skipping BIN TAX ASSIGNMENT: DAS_Tool did not predict bins.
Skipping CHECKM: DAS_Tool did not predict bins.
Skipping BIN TABLE CREATION: (You already know: DAS_Tool did not predict bins.)**

**WARNINGS:
DAS Tool abnormal termination: file /home/hamlab/sample2/results/DAS/sample2_DASTool_bins/ is empty. There are NO BINS!**
The commands before the step 16 ran smoothly as there were no error messages at step 15 and 16
**[7 hours, 22 minutes, 43 seconds]: STEP15 -> METABAT BINNING: 15.bin_metabat2.pl
[7 hours, 22 minutes, 46 seconds]: STEP16 -> DAS_TOOL MERGING: 16.dastool.pl**
please help me in resolving the issue

**Comment by anilchauhanhp9** [comment]
also i ran command **/home/hamlab/miniconda/envs/SqueezeMeta/SqueezeMeta/scripts/16.dastool.pl /home/hamlab/sample2** and it gave me following error
**Creating tables of contigs in bins... done
Running DAS Tool (Sieber et al 2018, Nat Microbiol 3(7), 836-43) for maxbin,metabat2
Running DAS Tool using 12 threads.
predicting genes using Prodigal V2.6.3: February, 2016
identifying single copy genes using diamond version 0.9.22
evaluating bin-sets
No bins with bin-score >0.25 found. Adjust score_threshold to report bins with lower quality.
 Aborting**.

**Comment by jtamames** [comment]
Hello
Your dataset did not generate any bins. A likely reason is that it is too small for binning.
Best,

**Comment by anilchauhanhp9** [comment]
ok,
Thank you
