### ISSUE TITLE
--empty flag not recognized

### ISSUE THREAD

**Issue by alopgar** [jtamames/SqueezeMeta#251]
Hello!
I encountered an issue with the --empty option:

```
(SqueezeMeta1.3) [user@fs6802 Assembly]$ SqueezeMeta.pl -m seqmerge -p Emptyproject -s some.samples -f input/dir/samples --empty
Unknown option: empty
SqueezeMeta v1.3.0 - (c) J. Tamames, F. Puente-Sánchez CNB-CSIC, Madrid, SPAIN

Please cite: Tamames & Puente-Sanchez, Frontiers in Microbiology 9, 3349 (2019). doi: https://doi.org/10.3389/fmicb.2018.03349

Run started Tue Feb 23 13:55:40 2021 in seqmerge mode
Now creating directories
Reading configuration from Assembly/Emptyproject/SqueezeMeta_conf.pl
...

```
And then it keeps running with the standard procedure.
Any clues?

**Comment by jtamames** [comment]
That's weird... Could you download the current version of the SqueezeMeta.pl script (1.3.1) from this repo and try it?

**Comment by jtamames** [comment]
I can assure that it is working in 1.3.1:

> SqueezeMeta.pl -m seqmerge -p Emptyproject -s H4.samples -f . --empty
> 
> SqueezeMeta v1.3.1 - (c) J. Tamames, F. Puente-Sánchez CNB-CSIC, Madrid, SPAIN
> 
> Please cite: Tamames & Puente-Sanchez, Frontiers in Microbiology 9, 3349 (2019). doi: https://doi.org/10.3389/fmicb.2018.03349
> 
> Run started Tue Feb 23 14:19:38 2021 in seqmerge mode
> Now creating directories
> Reading configuration from /media/disk5/tamames/Emptyproject/SqueezeMeta_conf.pl
> Reading samples from /media/disk5/tamames/Emptyproject/data/00.Emptyproject.samples
>   Directory structure and conf files created. Exiting
>

**Comment by alopgar** [comment]
Solved! It was indeed a version problem.
