### ISSUE TITLE
Stopping in STEP2 -> 02.rnas.pl. Program finished abnormally

### ISSUE THREAD

**Issue by phlatphish** [jtamames/SqueezeMeta#252]
STDERR:

Now merging files
[10 hours, 40 minutes, 3 seconds]: STEP1 -> RUNNING CO-ASSEMBLY: 01.run_assembly.pl (megahit)
  Running assembly with megahit
  Running prinseq (Schmieder et al 2011, Bioinformatics 27(6):863-4) for selecting contigs longer than 200
Input and filter stats:
        Input sequences: 302,007
        Input bases: 158,189,730
        Input mean length: 523.79
        Good sequences: 302,007 (100.00%)
        Good bases: 158,189,730
        Good mean length: 523.79
        Bad sequences: 0 (0.00%)
        Sequences filtered by specified parameters:
        none
  Renaming contigs
  Counting length of contigs
  Contigs stored in /home/projects/redgillite/cjb_metagenome/squeeze/nodules_3/results/01.nodules_3.fasta
  Number of contigs: 302007
[16 hours, 10 minutes, 25 seconds]: STEP2 -> RNA PREDICTION: 02.rnas.pl
  Running barrnap (Seeman 2014, Bioinformatics 30, 2068-9) for predicting RNAs:  Bacteria Archaea[13:35:45] Can't find database: /home/projects/redgillite/cjb_metagenome/squeeze/db/arc.hmm
Error running command:    /home/cjb/miniconda3/envs/squeeze/SqueezeMeta/bin/barrnap --quiet --threads 64 --kingdom arc --reject 0.1 /home/projects/redgillite/cjb_metagenome/squeeze/nodules_3/intermediate/02.nodules_3.maskedrna.fasta --dbdir /home/projects/redgillite/cjb_metagenome/squeeze/db > /home/projects/redgillite/cjb_metagenome/squeeze/nodules_3/temp/arc.gff at /home/cjb/miniconda3/envs/squeeze/SqueezeMeta/scripts/02.rnas.pl line 54.
Stopping in STEP2 -> 02.rnas.pl. Program finished abnormally

  If you don't know what went wrong or want further advice, please look for similar issues in https://github.com/jtamames/SqueezeMeta/issues
  Feel free to open a new issue if you don't find the answer there. Please add a brief description of the problem and upload the /home/projects/redgillite/cjb_metagenome/squeeze/nodules_3/syslog file (zip it first)
Died at /home/cjb/miniconda3/envs/squeeze/bin/SqueezeMeta.pl line 1359.

[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/6071988/syslog.zip)

```
ls -l db

total 228202400
-rw-rw-r-- 1 cjb projects          56 Sep 24 21:26 DB_BUILD_DATE
drwxrwsr-x 2 cjb projects          83 Sep 24 21:26 LCA_tax
-rw-rw-r-- 1 cjb projects  1459135873 Sep 24 09:21 Pfam-A.hmm
-rw-rw-r-- 1 cjb projects         335 May 21  2018 ReadMe
-rw-rw-r-- 1 cjb projects 68549217431 Feb 26 02:27 SqueezeMetaDB.tar.gz
-rw-r--r-- 1 cjb projects     1324749 Nov 16  2018 arc.scg.faa
-rw-r--r-- 1 cjb projects      202175 Nov 16  2018 arc.scg.lookup
-rw-r--r-- 1 cjb projects    16173613 Nov 16  2018 bac.all.faa
-rw-r--r-- 1 cjb projects      808656 Apr 27  2018 bac.hmm
-rw-r--r-- 1 cjb projects      249620 Nov 16  2018 bac.scg.faa
-rw-r--r-- 1 cjb projects       36700 Nov 16  2018 bac.scg.lookup
-rw-r--r-- 1 cjb projects     3671082 Apr 27  2018 bacar_marker.hmm
drwxrwsr-x 2 cjb projects          87 Jan 13  2015 distributions
-rw-rw-r-- 1 cjb projects  3510404928 Sep 24 09:21 eggnog.dmnd
-rw-r--r-- 1 cjb projects     1038507 Apr 27  2018 euk.hmm
drwxrwsr-x 4 cjb projects         304 Jan 13  2015 genome_tree
drwxrwsr-x 2 cjb projects         118 Jan 13  2015 hmms
drwxrwsr-x 2 cjb projects         127 Jan 13  2015 hmms_ssu
drwxrwsr-x 2 cjb projects          34 Jan 13  2015 img
-rw-rw-r-- 1 cjb projects  2867640345 Sep 24 02:47 keggdb.dmnd
-rw-r--r-- 1 cjb projects    15929643 Apr 27  2018 marker.hmm
-rw-r--r-- 1 cjb projects      456264 Apr 27  2018 mito.hmm
-rw-rw-r-- 1 cjb projects 87785746432 Feb 26 16:58 nr.dmnd
drwxrwsr-x 2 cjb projects          66 Jan 13  2015 pfam
-rw-r--r-- 1 cjb projects 10680384402 Sep 25 03:27 silva.nr_v132.align
-rw-r--r-- 1 cjb projects    22266447 Sep 25 03:24 silva.nr_v132.tax
-rw-rw-r-- 1 cjb projects    21521855 Jan 13  2015 taxon_marker_sets.tsv
drwxrwsr-x 3 cjb projects          51 May 21  2018 test
drwxrwsr-x 2 cjb projects          31 Jan 13  2015 test_data
```

**Comment by jtamames** [comment]
Hello
See the answer to your issue in #253, same cause.
Best
