### ISSUE TITLE
Installation Error on Debian 9 (stretch)

### ISSUE THREAD

**Issue by lordness4** [jtamames/SqueezeMeta#255]
Hello!
First of all, thanks for the amazing work!

I've run into a installation problem on Debian 9:
When running:
```conda create -n SqueezeMeta -c bioconda -c conda-forge -c fpusan squeezemeta```
the installation stalls at the  conda "Executing transaction" step with the following error message (full installation output is attached. 
```
ERROR conda.core.link:_execute(698): An error occurred while installing package 'bioconda::bioconductor-org.hs.eg.db-3.10.0-r36_0'.
Rolling back transaction:
...
```
Afterwards the installation is cancelled and while a squeezMeta environment exists, its not functional.

Additional Info:
conda version: conda 4.9.2
R version*: 3.4.4                                       <-- (this could potentially be the issue?)
OS: Debian 9 (stretch)

[SqueezeMeta_installation_error.txt](https://github.com/jtamames/SqueezeMeta/files/6083872/SqueezeMeta_installation_error.txt)

Any idea why this would happen? 
If you need any additional information, I'll gladly post more.

Thanks!

**Comment by fpusan** [comment]
Hard to tell, conda is sometimes sketchy.
I just tried the same command in my Ubuntu 18 system and worked without errors.
Maybe you install the latest version of miniconda3 (a fresh conda install can help with some bugs) and try again?
Also we've never tried SqueezeMeta in Debian9 (we've had some success with Debian10) so I expect some binaries might need recompiling. But let's go step by step. Let me know if a fresh conda install helps.

**Comment by lordness4** [comment]
Will try with a new conda install. I've asked our in house IT to have a look as well, but they'll only manage to get to it on monday. Will keep you updated. 

Thanks for the quick reply!

**Comment by lordness4** [comment]
Hey,

I tried with a new conda installation, which unfortunately did not solve the problem. 

Since the error is connected to the bioconda::bioconductor-org.hs.eg.db-3.10.0-r36_0 package, I manually tried to install it in R by installing "pathways" from BioManager (which has then the package as a dependency). That did work. But the install of SqueezeMeta still fails. 
I'm actively searching for solutions, so if you've got another idea, let me know!

Cheers

**Comment by lordness4** [comment]
Quick update:
The problem seems similar to this https://github.com/bioconda/bioconda-recipes/issues/13846 , so I tried to do what they did and pin the wget version, but that failed due to a conflict with pysam. And of course they claim its done when using a newer conda version, which I have, so it might not be related at all.

**Comment by fpusan** [comment]
Hi,
That seems nasty. They also mention some workarounds with the ca certificates, maybe that'll do the trick?
If it doesn't, maybe you can install the packages manually. `org.hs.eg.db` is only needed for pathview, which is only used by one function in `SQMtools`, so the standard SqueezeMeta pipeline and most of `SQMtools` should work even if it's not present.
Here's the full list of packages

```
    - python=3.6
    - numpy
    - scipy
    - pandas
    - cython
    - future
    - matplotlib
    - dendropy
    - pysam
    - perl=5.26
    - perl-tie-ixhash
    - perl-dbd-mysql
    - perl-dbd-sqlite
    - perl-lwp-simple
    - perl-xml-libxml
    - perl-xml-parser
    - openjdk
    - ruby=2.5
    - r=3.6
    - r-ggplot2
    - r-reshape2
    - r-doMC
    - r-data.table
    - bioconductor-pathview
    - tree
 ```
I would create a new environment and try to set those up manually. Then you can download the latest release of SqueezeMeta from our github page, and set it up with
```
R CMD INSTALL /path/to/SqueezeMeta/bin/DAS_Tool/package/DASTool_1.1.1.tar.gz
R CMD INSTALL /path/to/SqueezeMeta/lib/SQMtools
```
If everything goes ok, running `perl /path/to/SqueezeMeta/utils/install_utils/test_install.pl` should give no errors.
I still suspect that some binaries will fail in Debian9, but that should become a problem after the installation.

**Comment by fpusan** [comment]
That's something! Did it pass the `test_install.pl` step?

**Comment by lordness4** [comment]
Well, it does not complain too much: It says that the nr.db is not available and that its missing pathview, SQMtools and the perl library Linux::MemInfo. 

```
(SqueezeMeta) [10:47:51] ~/bin/SqueezeMeta/utils/install_utils $ perl test_install.pl 

Checking the OS
	linux OK

Checking that tree is installed
	tree --help OK

Checking that ruby is installed
	ruby -h OK

Checking that java is installed
	java -h OK

Checking that all the required perl libraries are available in this environment
	perl -e 'use Term::ANSIColor' OK
	perl -e 'use DBI' OK
	perl -e 'use DBD::SQLite::Constants' OK
	perl -e 'use Time::Seconds' OK
	perl -e 'use Tie::IxHash' OK
	perl -e 'use Linux::MemInfo' NOT OK
		Missing perl library "Linux::MemInfo"
	perl -e 'use Getopt::Long' OK
	perl -e 'use File::Basename' OK
	perl -e 'use DBD::SQLite' OK
	perl -e 'use Data::Dumper' OK
	perl -e 'use Cwd' OK
	perl -e 'use XML::LibXML' OK
	perl -e 'use Term::ANSIColor' OK

Checking that all the required python libraries are available in this environment
	python3 -h OK
	python3 -c 'import numpy' OK
	python3 -c 'import scipy' OK
	python3 -c 'import matplotlib' OK
	python3 -c 'import dendropy' OK
	python3 -c 'import pysam' OK
	python3 -c 'import pandas' OK
	python3 -c 'import cython' OK
	python3 -c 'import future' OK

Checking that all the required R libraries are available in this environment
	R -h OK
	R -e 'library(doMC)' OK
	R -e 'library(ggplot2)' OK
	R -e 'library(data.table)' OK
	R -e 'library(reshape2)' OK
	R -e 'library(pathview)' NOT OK
		Missing R library "pathview"
	R -e 'library(DASTool)' OK
	R -e 'library(SQMtools)' NOT OK
		Missing R library "SQMtools"

Checking that SqueezeMeta is properly configured... checking database in /home/dlueckin/dbs/squeezemeta_db/db
	SqueezeMeta_conf.pl says that databases are located in /home/dlueckin/dbs/squeezemeta_db/db but we can't find nr.db there, or it is corrupted

------------------------------------------------------------------------------

WARNING: Some SqueezeMeta dependencies could not be found in your environment!
	- Missing perl library "Linux::MemInfo"
	- Missing R library "pathview"
	- Missing R library "SQMtools"
	SqueezeMeta_conf.pl says that databases are located in /home/dlueckin/dbs/squeezemeta_db/db but we can't find nr.db there, or it is corrupted

(SqueezeMeta) [10:48:19] ~/bin/SqueezeMeta/utils/install_utils $ ls /home/dlueckin/dbs/squeezemeta_db/db/
arc.all.faa  arc.scg.lookup    bac.hmm         DB_BUILD_DATE  euk.hmm      hmms_ssu     kegg.db.md5  mito.hmm  Pfam-A.hmm                silva.nr_v132.align      silva.nr_v132.tax.md5
arc.hmm      bac.all.faa       bac.scg.faa     distributions  genome_tree  img          LCA_tax      nr.gz     ReadMe                    silva.nr_v132.align.md5  taxon_marker_sets.tsv
arc.scg.faa  bacar_marker.hmm  bac.scg.lookup  eggnog.dmnd    hmms         keggdb.dmnd  marker.hmm   pfam      selected_marker_sets.tsv  silva.nr_v132.tax        test_data 
```

**Comment by lordness4** [comment]
I already installed the Linux::MemInfo with CPAN, looks like that resolved the issue. 
Before I'll continue I'll install the DB like described in https://github.com/jtamames/SqueezeMeta/issues/246 (which #253 points at). 
Thanks for the quick responses, I'll report back if that has worked!

**Comment by lordness4** [comment]
Alright, I think I've got the installation done. I'm running into another problem with the pipeline (somehow megahit does work, spades doesn't), but that seems like a different issue. So I'm closing the issue.

Thanks for helping me out!

**Comment by fpusan** [comment]
Glad to hear!
Most errors you'll encounter from now on will be due to pre-compiled binaries not working in Debian9. I would now test the main pipeline with the test dataset we provide, and see where it fails and how. At that point you will have to download the source code of the program, compile it to make sure it works in your Debian9 system, and use it to replace the pre-compiled binary we ship with SqueezeMeta.

In https://github.com/jtamames/SqueezeMeta/blob/master/VENDORED-TOOLS.md you have a description of all the software we redistribute, and whether it can be directly replaced by the original version without further modifications. In any case, let me know if you run into something that doesn't work for you, I might be able to help.
