### ISSUE TITLE
query 

### ISSUE THREAD

**Issue by kinosham** [jtamames/SqueezeMeta#256]
Good day 

Could you please assist. 

I am running squeezemeta and it is leaving steps out on its own. 

This my command line .
/apps/SqueezeMeta/scripts/SqueezeMeta.pl -m coassembly -p Kinosha_res_samples_2 -s /nlustre/users/kinosha/res_sequences/coassembly_res -f /nlustre/users/kinosha/res_sequences -t 24

This is my output file of what is running .
Interactive session for user: kinosha
Node: alf.bi.up.ac.za
*** Your session parameters ***
Queue: bigmem
Walltime: 2592000 seconds
CPU's allocated: 24

SqueezeMeta v1.0.0beta - (c) J. Tamames, F. Puente-SÃ¡nchez CNB-CSIC, Madrid, SPAIN

Please cite: Tamames & Puente-Sanchez, Frontiers in Microbiology 10.3389 (2019). doi: https://doi.org/10.3389/fmicb.2018.03349

Sample1
SA73_20_GTGAAA_L001_R1_000.fastq
pair1
------------------
Sample1
SA73_20_GTGAAA_L001_R2_000.fastq
pair2
------------------
Sample2
SB73_8_AGTCAA_L001_R1_000.fastq
pair1
------------------
Sample2
SB73_8_AGTCAA_L001_R2_000.fastq
pair2
------------------
Sample3
SC73_7_CTTGTA_L001_R1_000.fastq
pair1
------------------
Sample3
SC73_7_CTTGTA_L001_R2_000.fastq
pair2
------------------
Sample4
SD41_21_ACTTGA_L001_R1_000.fastq
pair1
------------------
Sample4
SD41_21_ACTTGA_L001_R2_000.fastq
pair2
------------------
Sample5
SE41_20_CAGATC_L001_R1_000.fastq
pair1
------------------
Sample5
SE41_20_CAGATC_L001_R2_000.fastq
pair2
------------------
Run started Mon Mar  8 14:02:27 2021 in coassembly mode

Interactive session for user: kinosha
Node: alf.bi.up.ac.za
*** Your session parameters ***
Queue: bigmem
Walltime: 2592000 seconds
CPU's allocated: 24

SqueezeMeta v1.0.0beta - (c) J. Tamames, F. Puente-SÃ¡nchez CNB-CSIC, Madrid, SPAIN

Please cite: Tamames & Puente-Sanchez, Frontiers in Microbiology 10.3389 (2019). doi: https://doi.org/10.3389/fmicb.2018.03349

Sample1
SA73_20_GTGAAA_L001_R1_000.fastq
pair1
------------------
Sample1
SA73_20_GTGAAA_L001_R2_000.fastq
pair2
------------------
Sample2
SB73_8_AGTCAA_L001_R1_000.fastq
pair1
------------------
Sample2
SB73_8_AGTCAA_L001_R2_000.fastq
pair2
------------------
Sample3
SC73_7_CTTGTA_L001_R1_000.fastq
pair1
------------------
Sample3
SC73_7_CTTGTA_L001_R2_000.fastq
pair2
------------------
Sample4
SD41_21_ACTTGA_L001_R1_000.fastq
pair1
------------------
Sample4
SD41_21_ACTTGA_L001_R2_000.fastq
pair2
------------------
Sample5
SE41_20_CAGATC_L001_R1_000.fastq
pair1
------------------
Sample5
SE41_20_CAGATC_L001_R2_000.fastq
pair2
------------------
Run started Mon Mar  8 14:07:30 2021 in coassembly mode

Now creating directories

Reading configuration from /home/kinosha/Kinosha_res_samples_2/SqueezeMeta_conf.pl

Now moving read files

5 samples found

Now merging files

[6 minutes, 19 seconds]: STEP1 -> RUNNING CO-ASSEMBLY: 01.run_assembly.pl (megahit)

Running assembly with megahit: /apps/SqueezeMeta/scripts/../bin/megahit/megahit  -1 /home/kinosha/Kinosha_res_samples_2/data/raw_fastq/par1.fastq -2 /home/kinosha/Kinosha_res_samples_2/data/raw_fastq/par2.fastq -t 24 -o /home/kinosha/Kinosha_res_samples_2/data/megahit
Running prinseq: /apps/SqueezeMeta/scripts/../bin/prinseq-lite.pl -fasta /home/kinosha/Kinosha_res_samples_2/data/megahit/final.contigs.fa -min_len 200 -out_good /home/kinosha/Kinosha_res_samples_2/results/prinseq; mv /home/kinosha/Kinosha_res_samples_2/results/prinseq.fasta /home/kinosha/Kinosha_res_samples_2/results/01.Kinosha_res_samples_2.fasta
Counting length of contigs
Contigs stored in /home/kinosha/Kinosha_res_samples_2/results/01.Kinosha_res_samples_2.fasta
[2 hours, 2 minutes, 25 seconds]: STEP2 -> RNA PREDICTION: 02.run_barrnap.pl

Running barrnap for Bacteria
Running barrnap for Archaea
Running barrnap for Eukaryote
Running barrnap for Mitochondrial
Running RDP classifier: java -jar /apps/SqueezeMeta/scripts/../bin/classifier.jar classify /home/kinosha/Kinosha_res_samples_2/temp/16S.fasta -o /home/kinosha/Kinosha_res_samples_2/temp/16S.out -f filterbyconf
[2 hours, 3 minutes, 30 seconds]: STEP3 -> ORF PREDICTION: 03.run_prodigal.pl

Running prodigal
[2 hours, 28 minutes, 39 seconds]: STEP4 -> HOMOLOGY SEARCHES: 04.rundiamond.pl

Running Diamond for COGS (This can take a while, please be patient)
Running Diamond for KEGG (This can take a while, please be patient)
Running Diamond for taxa (This can take a long while, please be even more patient)
[3 hours, 45 minutes, 1 seconds]: STEP5 -> HMMER/PFAM: 05.run_hmmer.pl

Running hmmer search
[7 hours, 5 minutes, 37 seconds]: STEP6 -> TAXONOMIC ASSIGNMENT: 06.lca.pl

Tax assignment done! Result stored in file /home/kinosha/Kinosha_res_samples_2/results/06.Kinosha_res_samples_2.fun3.tax
[7 hours, 26 minutes, 57 seconds]: STEP7 -> FUNCTIONAL ASSIGNMENT: 07.fun3assign.pl

Assigning COGS KEGG PFAM
[7 hours, 27 minutes, 20 seconds]: STEP9 -> CONTIG TAX ASSIGNMENT: 09.summarycontigs3.pl

Reading /home/kinosha/Kinosha_res_samples_2/results/06.Kinosha_res_samples_2.fun3.tax.wranks
Writing output to /home/kinosha/Kinosha_res_samples_2/intermediate/09.Kinosha_res_samples_2.contiglog
[7 hours, 27 minutes, 53 seconds]: STEP10 -> MAPPING READS: 10.mapsamples.pl

Reading mapping file from /home/kinosha/Kinosha_res_samples_2/data/00.Kinosha_res_samples_2.samples
Metagenomes found: 5
Creating reference.
Working with 1: Sample1
  Getting raw reads
  Aligning to reference with bowtie
  Calculating contig coverage
  Counting with sqm_counter
    1000000 reads counted
    2000000 reads counted
    3000000 reads counted
    4000000 reads counted
    5000000 reads counted
    6000000 reads counted
    7000000 reads counted
    8000000 reads counted
    9000000 reads counted
    10000000 reads counted
    11000000 reads counted
    12000000 reads counted
Working with 2: Sample2
  Getting raw reads
  Aligning to reference with bowtie
  Calculating contig coverage
  Counting with sqm_counter
    1000000 reads counted
    2000000 reads counted
    3000000 reads counted
    4000000 reads counted
    5000000 reads counted
    6000000 reads counted
    7000000 reads counted
    8000000 reads counted
    9000000 reads counted
    10000000 reads counted
    11000000 reads counted
    12000000 reads counted
Working with 3: Sample3
  Getting raw reads
  Aligning to reference with bowtie
  Calculating contig coverage
  Counting with sqm_counter
    1000000 reads counted
    2000000 reads counted
    3000000 reads counted
    4000000 reads counted
    5000000 reads counted
    6000000 reads counted
    7000000 reads counted
    8000000 reads counted
    9000000 reads counted
    10000000 reads counted
    11000000 reads counted
Working with 4: Sample4
  Getting raw reads
  Aligning to reference with bowtie
  Calculating contig coverage
  Counting with sqm_counter
    1000000 reads counted
    2000000 reads counted
    3000000 reads counted
    4000000 reads counted
    5000000 reads counted
    6000000 reads counted
    7000000 reads counted
    8000000 reads counted
    9000000 reads counted
    10000000 reads counted
    11000000 reads counted
    12000000 reads counted
    13000000 reads counted
    14000000 reads counted
    15000000 reads counted
Working with 5: Sample5
  Getting raw reads
  Aligning to reference with bowtie
  Calculating contig coverage
  Counting with sqm_counter
    1000000 reads counted
    2000000 reads counted
    3000000 reads counted
    4000000 reads counted
    5000000 reads counted
    6000000 reads counted
    7000000 reads counted
    8000000 reads counted
    9000000 reads counted
Output in /home/kinosha/Kinosha_res_samples_2/intermediate/10.Kinosha_res_samples_2.mapcount
[8 hours, 54 minutes, 22 seconds]: STEP11 -> COUNTING TAX ABUNDANCES: 11.mcount.pl

[8 hours, 54 minutes, 32 seconds]: STEP12 -> COUNTING FUNCTION ABUNDANCES: 12.funcover.pl

Calculating coverage for functions
Reading coverage in /home/kinosha/Kinosha_res_samples_2/intermediate/10.Kinosha_res_samples_2.mapcount
Reading rpkm in /home/kinosha/Kinosha_res_samples_2/intermediate/10.Kinosha_res_samples_2.mapcount
Now creating cog coverage output in /home/kinosha/Kinosha_res_samples_2/results/12.Kinosha_res_samples_2.cog.funcover
Now creating kegg coverage output in /home/kinosha/Kinosha_res_samples_2/results/12.Kinosha_res_samples_2.kegg.funcover
Now creating cog raw reads output in /home/kinosha/Kinosha_res_samples_2/ext_tables/12.Kinosha_res_samples_2.cog.stamp
Now creating kegg raw reads output in /home/kinosha/Kinosha_res_samples_2/ext_tables/12.Kinosha_res_samples_2.kegg.stamp
[8 hours, 55 minutes, 3 seconds]: STEP13 -> CREATING GENE TABLE: 13.mergeannot2.pl

Reading GFF in /home/kinosha/Kinosha_res_samples_2/results/03.Kinosha_res_samples_2.gff
Reading Diamond hits
Reading COG list
Reading KEGG list
Reading aa sequences
Reading nt sequences
Reading RNA sequences
Reading ORF information
Calculating GC content for genes
Calculating GC content for RNAs
Reading contig information
Reading KEGG annotations
Reading COGs annotations
Reading Pfam annotations
Reading RPKMs and Coverages
Creating table
============
GENE TABLE CREATED: /home/kinosha/Kinosha_res_samples_2/results/13.Kinosha_res_samples_2.orftable
============

[8 hours, 56 minutes, 45 seconds]: STEP14 -> MAXBIN BINNING: 14.bin_maxbin.pl

[9 hours, 2 minutes, 32 seconds]: STEP15 -> METABAT BINNING: 15.bin_metabat2.pl

[9 hours, 4 minutes, 20 seconds]: STEP16 -> DAS_TOOL MERGING: 16.dastool.pl

[9 hours, 6 minutes, 48 seconds]: STEP17 -> BIN TAX ASSIGNMENT: 17.addtax2.pl

[9 hours, 7 minutes, 6 seconds]: STEP18 -> CHECKING BINS: 18.checkM_batch.pl

Creating /home/kinosha/Kinosha_res_samples_2/temp/checkm_batch
Reading /apps/SqueezeMeta/scripts/../data/alltaxlist.txt
Looking for DASTool bins in /home/kinosha/Kinosha_res_samples_2/results/DAS/Kinosha_res_samples_2_DASTool_bins
28 bins found

Bin 1/28: maxbin.007.fasta.contigs.fa.tax
 Using profile for family rank : Sphingomonadaceae
Bin 2/28: maxbin.019.fasta.contigs.fa.tax
 Using profile for genus rank : Hyphomicrobium
Bin 3/28: maxbin.020.fasta_sub.contigs.fa.tax
 Using profile for class rank : Alphaproteobacteria
Bin 4/28: maxbin.022.fasta_sub.contigs.fa.tax
 Using profile for class rank : Alphaproteobacteria
Bin 5/28: metabat2.53.fa.contigs.fa.tax
 Using profile for genus rank : Hyphomicrobium
Bin 6/28: metabat2.32.fa.contigs.fa.tax
 Using profile for order rank : Rhizobiales
Bin 7/28: maxbin.026.fasta.contigs.fa.tax
 Using profile for family rank : Sphingomonadaceae
Bin 8/28: maxbin.017.fasta.contigs.fa.tax
 Using profile for genus rank : Methylotenera
Bin 9/28: maxbin.018.fasta.contigs.fa.tax
 Using profile for family rank : Acetobacteraceae
Bin 10/28: metabat2.54.fa_sub.contigs.fa.tax
 Using profile for phylum rank : Proteobacteria
Bin 11/28: metabat2.15.fa.contigs.fa.tax
 Using profile for genus rank : Hyphomicrobium
Bin 12/28: maxbin.004.fasta.contigs.fa.tax
 Using profile for genus rank : Sphingomonas
Bin 13/28: maxbin.029.fasta_sub.contigs.fa.tax
 Using profile for order rank : Rhizobiales
Bin 14/28: maxbin.023.fasta.contigs.fa.tax
 Using profile for family rank : Erythrobacteraceae
Bin 15/28: maxbin.005.fasta.contigs.fa.tax
 Using profile for genus rank : Nitrosomonas
Bin 16/28: maxbin.025.fasta_sub.contigs.fa.tax
 Using profile for genus rank : Porphyrobacter
 Using profile for family rank : Erythrobacteraceae
Bin 17/28: maxbin.010.fasta.contigs.fa.tax
 Using profile for genus rank : Methylobacterium
Bin 18/28: maxbin.009.fasta.contigs.fa.tax
 Using profile for class rank : Alphaproteobacteria
Bin 19/28: maxbin.027.fasta.contigs.fa.tax
 Using profile for genus rank : Sphingomonas
Bin 20/28: maxbin.028.fasta.contigs.fa.tax
 Using profile for order rank : Burkholderiales
Bin 21/28: maxbin.011.fasta.contigs.fa.tax
 Using profile for phylum rank : Nitrospirae
Bin 22/28: maxbin.003.fasta.contigs.fa.tax
 Using profile for phylum rank : Proteobacteria
Bin 23/28: maxbin.032.fasta.contigs.fa.tax
 Using profile for order rank : Nitrosomonadales
Bin 24/28: maxbin.015.fasta.contigs.fa.tax
 Using profile for phylum rank : Proteobacteria
Bin 25/28: maxbin.012.fasta.contigs.fa.tax
 Using profile for family rank : Sphingomonadaceae
Bin 26/28: maxbin.021.fasta.contigs.fa.tax
 Using profile for class rank : Betaproteobacteria
Bin 27/28: maxbin.002.fasta.contigs.fa.tax
 Using profile for genus rank : Nitrosomonas
Bin 28/28: metabat2.77.fa.contigs.fa.tax
 Using profile for order rank : Rhizobiales

Storing results for DASTool in /home/kinosha/Kinosha_res_samples_2/intermediate/18.Kinosha_res_samples_2.DASTool.checkM
[9 hours, 42 minutes, 22 seconds]: STEP19 -> CREATING BIN TABLE: 19.getbins.pl

Method:DASTool
Reading checkM results in /home/kinosha/Kinosha_res_samples_2/intermediate/18.Kinosha_res_samples_2.DASTool.checkM
Reading data for bin maxbin.007.fasta.contigs           
Reading data for bin maxbin.019.fasta.contigs           
Reading data for bin maxbin.020.fasta_sub.contigs           
Reading data for bin maxbin.022.fasta_sub.contigs           
Reading data for bin metabat2.53.fa.contigs           
Reading data for bin metabat2.32.fa.contigs           
Reading data for bin maxbin.026.fasta.contigs           
Reading data for bin maxbin.017.fasta.contigs           
Reading data for bin maxbin.018.fasta.contigs           
Reading data for bin metabat2.54.fa_sub.contigs           
Reading data for bin metabat2.15.fa.contigs           
Reading data for bin maxbin.004.fasta.contigs           
Reading data for bin maxbin.029.fasta_sub.contigs           
Reading data for bin maxbin.023.fasta.contigs           
Reading data for bin maxbin.005.fasta.contigs           
Reading data for bin maxbin.025.fasta_sub.contigs           
Reading data for bin maxbin.010.fasta.contigs           
Reading data for bin maxbin.009.fasta.contigs           
Reading data for bin maxbin.027.fasta.contigs           
Reading data for bin maxbin.028.fasta.contigs           
Reading data for bin maxbin.011.fasta.contigs           
Reading data for bin maxbin.003.fasta.contigs           
Reading data for bin maxbin.032.fasta.contigs           
Reading data for bin maxbin.015.fasta.contigs           
Reading data for bin maxbin.012.fasta.contigs           
Reading data for bin maxbin.021.fasta.contigs           
Reading data for bin maxbin.002.fasta.contigs           
Reading data for bin metabat2.77.fa.contigs           
Calculating coverages
Creating table in /home/kinosha/Kinosha_res_samples_2/results/19.Kinosha_res_samples_2.bintable
Done!
=============
BIN TABLE CREATED: /home/kinosha/Kinosha_res_samples_2/results/19.Kinosha_res_samples_2.bintable
=============

[9 hours, 42 minutes, 47 seconds]: STEP20 -> CREATING CONTIG TABLE: 20.getcontigs.pl

Reading taxa for contigs information...done!
Reading GC & length... done!
Reading number of genes... done!
Reading coverages... done!
Reading bins... done!
Creating contig table...done!
============
CONTIG TABLE CREATED: /home/kinosha/Kinosha_res_samples_2/results/20.Kinosha_res_samples_2.contigtable
============

[9 hours, 43 minutes, 48 seconds]: STEP21 -> CREATING TABLE OF PATHWAYS IN BINS: 21.minpath.pl

Running MinPath for kegg: maxbin.002.fasta.contigs         
Running MinPath for kegg: maxbin.003.fasta.contigs         
Running MinPath for kegg: maxbin.004.fasta.contigs         
Running MinPath for kegg: maxbin.005.fasta.contigs         
Running MinPath for kegg: maxbin.007.fasta.contigs         
Running MinPath for kegg: maxbin.009.fasta.contigs         
Running MinPath for kegg: maxbin.010.fasta.contigs         
Running MinPath for kegg: maxbin.011.fasta.contigs         
Running MinPath for kegg: maxbin.012.fasta.contigs         
Running MinPath for kegg: maxbin.015.fasta.contigs         
Running MinPath for kegg: maxbin.017.fasta.contigs         
Running MinPath for kegg: maxbin.018.fasta.contigs         
Running MinPath for kegg: maxbin.019.fasta.contigs         
Running MinPath for kegg: maxbin.020.fasta_sub.contigs         
Running MinPath for kegg: maxbin.021.fasta.contigs         
Running MinPath for kegg: maxbin.022.fasta_sub.contigs         
Running MinPath for kegg: maxbin.023.fasta.contigs         
Running MinPath for kegg: maxbin.025.fasta_sub.contigs         
Running MinPath for kegg: maxbin.026.fasta.contigs         
Running MinPath for kegg: maxbin.027.fasta.contigs         
Running MinPath for kegg: maxbin.028.fasta.contigs         
Running MinPath for kegg: maxbin.029.fasta_sub.contigs         
Running MinPath for kegg: maxbin.032.fasta.contigs         
Running MinPath for kegg: metabat2.15.fa.contigs         
Running MinPath for kegg: metabat2.32.fa.contigs         
Running MinPath for kegg: metabat2.53.fa.contigs         
Running MinPath for kegg: metabat2.54.fa_sub.contigs         
Running MinPath for kegg: metabat2.77.fa.contigs         
Running MinPath for metacyc: maxbin.002.fasta.contigs         
Running MinPath for metacyc: maxbin.003.fasta.contigs         
Running MinPath for metacyc: maxbin.004.fasta.contigs         
Running MinPath for metacyc: maxbin.005.fasta.contigs         
Running MinPath for metacyc: maxbin.007.fasta.contigs         
Running MinPath for metacyc: maxbin.009.fasta.contigs         
Running MinPath for metacyc: maxbin.010.fasta.contigs         
Running MinPath for metacyc: maxbin.011.fasta.contigs         
Running MinPath for metacyc: maxbin.012.fasta.contigs         
Running MinPath for metacyc: maxbin.015.fasta.contigs         
Running MinPath for metacyc: maxbin.017.fasta.contigs         
Running MinPath for metacyc: maxbin.018.fasta.contigs         
Running MinPath for metacyc: maxbin.019.fasta.contigs         
Running MinPath for metacyc: maxbin.020.fasta_sub.contigs         
Running MinPath for metacyc: maxbin.021.fasta.contigs         
Running MinPath for metacyc: maxbin.022.fasta_sub.contigs         
Running MinPath for metacyc: maxbin.023.fasta.contigs         
Running MinPath for metacyc: maxbin.025.fasta_sub.contigs         
Running MinPath for metacyc: maxbin.026.fasta.contigs         
Running MinPath for metacyc: maxbin.027.fasta.contigs         
Running MinPath for metacyc: maxbin.028.fasta.contigs         
Running MinPath for metacyc: maxbin.029.fasta_sub.contigs         
Running MinPath for metacyc: maxbin.032.fasta.contigs         
Running MinPath for metacyc: metabat2.15.fa.contigs         
Running MinPath for metacyc: metabat2.32.fa.contigs         
Running MinPath for metacyc: metabat2.53.fa.contigs         
Running MinPath for metacyc: metabat2.54.fa_sub.contigs         
Running MinPath for metacyc: metabat2.77.fa.contigs         
[9 hours, 45 minutes, 12 seconds]: STEP22 -> MAKING FINAL STATISTICS: 22.stats.pl

Output in /home/kinosha/Kinosha_res_samples_2/results/22.Kinosha_res_samples_2.stats
[9 hours, 45 minutes, 36 seconds]: FINISHED -> Have fun!

And this is what my error file is saying at the end  .

Input and filter stats:
	Input sequences: 206,363
	Input bases: 219,220,965
	Input mean length: 1062.31
	Good sequences: 206,363 (100.00%)
	Good bases: 219,220,965
	Good mean length: 1062.31
	Bad sequences: 0 (0.00%)
	Sequences filtered by specified parameters:
	none
-p destination: Broken pipe
-p destination: Broken pipe

I have run this before and didnt have this problem before. I am not sure why it just leaves some of the commands or steps out. 

Could you please help. 

Regards and thank you 

Kinosha Moodley

**Comment by jtamames** [comment]
Perphaps you are referring to step 8? That one is done only when the user specifies the --D flag. A reading of the manual can clarify this further. For the rest, I also think the run is comlete and correct.

Best,

**Comment by kinosham** [comment]
Thank you for your feedbacks I am just confused because my output files seem to be missing like output 8, 9, 11,14, 15,16,17,18, and one or two more are left out

**Comment by jtamames** [comment]
Some scripts produce results in the `results` directory (the ones we consider more important). Some other output to the `intermediate` or `temp` directory. The manual lists all outputs and their corresponding directories. Please read it carefully to understand how the pipeline works.
Best,
J

**Comment by kinosham** [comment]
Thank you
