### ISSUE TITLE
Issue with Spades RNA output transcripts.fasta merged mode

### ISSUE THREAD

**Issue by mradz19** [jtamames/SqueezeMeta#261]
Hi.

This is actually an extension form another issue:
https://github.com/jtamames/SqueezeMeta/issues/200#issuecomment-779265020

Using an extassembly worked fine in that case. However the run I am doing now is too large and memory hungry to be run as a coassembly so I am trying to run in merged assembly mode. However it fails after assembling the first sample because of spades outputting transcripts.fasta instead of contigs.fasta.

Is there a fix for this issue?

**Comment by fpusan** [comment]
There might be, since yesterday. See discussion in #226

**Comment by mradz19** [comment]
Thanks @fpusan this works for me
