### ISSUE TITLE
combineSQM error?

### ISSUE THREAD

**Issue by QQ8488** [jtamames/SqueezeMeta#262]
Hi All,  
I am trying to combine to subset by using combineSQM.  
However, I got an error. I am not sure why it happened

> Bacteria_Archaea=combineSQM(Bacteria,Archaea,rescale_copy_number = F)
Error: vector memory exhausted (limit reached?)

**Comment by fpusan** [comment]
Ouch,
Which SQMtools version are you using?

**Comment by QQ8488** [comment]
Version 0.5.3

**Comment by fpusan** [comment]
Maybe the issue is related to this?
https://stackoverflow.com/questions/51295402/r-on-macos-error-vector-memory-exhausted-limit-reached
To me it seems like it's running out of memory (maybe the project is too big for your laptop, or you have a lot of objects in your R environment).

**Comment by QQ8488** [comment]
Thanks much!

I will try another supercomputer.
