### ISSUE TITLE
strange loadSQM error

### ISSUE THREAD

**Issue by QQ8488** [jtamames/SqueezeMeta#264]
Hey,

I tried to load my data in supercomputer
When I used loadQSM in R,  I received three errors.
1.
Error in file(file, "rt") : cannot open the connection.
In file(file, "rt") :
 cannot open file 'Mu_new/results/tables/Mu_new.contig.tax.allfilter.tsv': No such file or directory.  
2.
Error in file(file, "rt") : cannot open the connection
In file(file, "rt") :
  cannot open file 'Mu_new/results/tables/Mu_new.KO.cov.tsv': No such file or directory
3.
Error in file(file, "rt") : cannot open the connection
In file(file, "rt") :
  cannot open file 'Mu_new/results/tables/Mu_new.COG.cov.tsv': No such file or directory
4.
Error in file(file, "rt") : cannot open the connection
In file(file, "rt") :
cannot open file 'Mu_new/results/tables/Mu_new.PFAM.cov.tsv': No such file or directory

When I  checked the results in "tables" folder,  I did not have those files.   
I used SQMtools version 0.6.1., R version 3.6.3

However,  when I loaded the same dataset on my iMac, I did not receive any error.  I used SQMtools version 0.5.0,  R version 3.3.1

I can rename _Mu_new.contig.tax.tsv_ in my data to _Mu_new.contig.tax.allfilter.tsv_ and fixed the first error. But I am not sure about the rest of errors.

I also tried to change  the name Mu_new.KO.copyNumber.tsv to _Mu_new.KO.cov.tsv_ , Mu_new.COG.copyNumber.tsv to _Mu_new.COG.cov.tsv_  , and Mu_new.PFAM.copyNumber.tsv to _Mu_new.PFAM.cov.tsv,_ respectively.

However, once I changed all of the names, I received the following error.

**Error in SQM$functions[[method]]$tpm["Unmapped", ] : 
  subscript out of bounds**

These errors are very strange.

How could I fix these strange errors?

Regards,
QQ

**Comment by fpusan** [comment]
Hi! Let me know if #243 fixes it!

**Comment by QQ8488** [comment]
I tried  09.summarycontigs3.pl. 
However,  I got an error. 
**Can't open /Mu_test/Mu_new/results/08.Mu_new.fun3.tax.noidfilter.noidfilter.wranks**

**Comment by fpusan** [comment]
Hi again,
Did you change the name of any file or modified the `SqueezeMeta_conf.pl` file?
Does this happen with a newly created project using v1.3.1?
Alternatively, you can work with SQMtools 0.5.0

**Comment by jtamames** [comment]
Hello
Could you paste your SqueezeMeta_conf.pl file here, please?

**Comment by QQ8488** [comment]
The project was created by the old version and worked on SQTool 0.5.0. 
Now, I tried to analyze my data by using supercomputers. I install the new version V1.3.1 and SQMTools 0.6 on supercomputer.  Now it doesn't work.

**Comment by QQ8488** [comment]
Sure. Here is SqueezeMeta_conf.pl.
[SqueezeMeta_conf.pl.zip](https://github.com/jtamames/SqueezeMeta/files/6156881/SqueezeMeta_conf.pl.zip)

**Comment by fpusan** [comment]
Yes, that's a known backwards compatibility issue that was described in the release notes for 1.3.1.
Normally the link I sent before should be enough to fix it. But in this case you are using the `--euk` mode, and have run into a new bug. We will look into it, it shouldn't be too difficult to fix.

**Comment by jtamames** [comment]
> I tried 09.summarycontigs3.pl.
> However, I got an error.
> **Can't open /Mu_test/Mu_new/results/08.Mu_new.fun3.tax.noidfilter.noidfilter.wranks**

Hello
Could you copy the entire error message? I need to know in which line the script is reporting the error.
Best

**Comment by QQ8488** [comment]
[/panfs/roc/scratch/QQ/Murulee/Mu_test] % perl /panfs/roc/groups/4/SS/.conda/envs/SqueezeMeta/SqueezeMeta/scripts/09.summarycontigs3.pl /panfs/roc/scratch/QQ/Mu/Mu_test/Mu_new
  Reading /panfs/roc/scratch/QQ/Mu/Mu_test/Mu_new/results/08.Mu_new.fun3.tax.wranks
  Writing output to /panfs/roc/scratch/QQ/Mu/Mu_test/Mu_new/intermediate/09.Mu_new.contiglog
  Reading /panfs/roc/scratch/QQ/Mu/Mu_test/Mu_new/results/08.Mu_new.fun3.tax.noidfilter.wranks
Can't open /panfs/roc/scratch/QQ/Mu/Mu_test/Mu_new/results/08.Mu_new.fun3.tax.noidfilter.noidfilter.wranks

**Comment by fpusan** [comment]
Can you also attach the syslog file?

**Comment by QQ8488** [comment]
sure.
[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/6157050/syslog.zip)

**Comment by jtamames** [comment]
Could you download the actual version of the 09.summarycontigs3.pl script, the one that it is in the repo? That bug should be fixed. Please try it and tell us if it solves the problem.
Best,

**Comment by QQ8488** [comment]
Where can I download it?  Could you send me a link?

**Comment by fpusan** [comment]
https://raw.githubusercontent.com/jtamames/SqueezeMeta/master/scripts/09.summarycontigs3.pl

**Comment by jtamames** [comment]
https://github.com/jtamames/SqueezeMeta/blob/master/scripts/09.summarycontigs3.pl

**Comment by jtamames** [comment]
Lol

**Comment by QQ8488** [comment]
Thanks both of you.   
I am testing now.

**Comment by QQ8488** [comment]
I tested it.  I did not recieve the error when ran 09.summarycontigs3.pl. 

However, I still got the errors,  when I used  loadQSM.

**Comment by QQ8488** [comment]
Looks like I need to remove tables before running loadSQM.

**Comment by fpusan** [comment]
yes, follow the steps from the other issue I linked, and remove the tables before doing anything else!

**Comment by QQ8488** [comment]
> Mu_new=loadSQM('Mu_new')
Generating tabular outputs for project in Murulee_new
Error in loadSQM("Mu_new") : 
  An error occurred while running sqm2tables.py

**Comment by QQ8488** [comment]
Traceback (most recent call last):
  File "/home/.conda/envs/SqueezeMeta/bin/sqm2tables.py", line 214, in <module>
    main(parse_args())
  File "/home/.conda/envs/SqueezeMeta/bin/sqm2tables.py", line 60, in main
    total_reads, total_bases = parse_mappingstat(perlVars['$mappingstat'])
KeyError: '$mappingstat'

**Comment by fpusan** [comment]
Ah! A different backwards compatibility issue (you're jumping several versions at once)
Follow #197

**Comment by fpusan** [comment]
Yay. Closing issue
