### ISSUE TITLE
Unable to install SQMtools

### ISSUE THREAD

**Issue by leehwmj** [jtamames/SqueezeMeta#265]
I installed R to use SQMtools.
In reference to #60, I typed "sudo RCMD INSTALL ~/anaconda3/envs/SquezeMeta/lib/SQMtools".

And the following results were obtained.
```
$ sudo R CMD INSTALL ~/anaconda3/envs/SqueezeMeta/lib/SQMtools
Warning: invalid package '/home/hwlee/anaconda3/envs/SqueezeMeta/lib/SQMtools'
Error: ERROR: no packages specified
```

Do I need another step to install SQMtools?

**Comment by fpusan** [comment]
No, but the right location would be `~/anaconda3/envs/SqueezeMeta/SqueezeMeta/lib/SQMtools`

**Comment by fpusan** [comment]
Also note that, if you are using the conda version, you shouldn't need to install SQMtools

**Comment by leehwmj** [comment]
But, I typed and run `library('SQMtools')` on R,
It returns the following error.
`Error in library("SQMtools") : there is no package called ‘SQMtools’ `


So I tried to install it as below, but it was not successful.
```
> install.packages(SQMtools)
Error in install.packages : object 'SQMtools' not found
```


Although the location was modified, the following results were obtained:
```
$ sudo R CMD INSTALL ~/anaconda3/envs/SqueezeMeta/SqueezeMeta/lib/SQMtools
* installing to library ‘/home/hwlee/R/x86_64-pc-linux-gnu-library/4.0’
ERROR: dependencies ‘reshape2’, ‘ggplot2’, ‘pathview’, ‘data.table’ are not available for package ‘SQMtools’
* removing ‘/home/hwlee/R/x86_64-pc-linux-gnu-library/4.0/SQMtools’
```

I approached the location for removing
The /home/hwlee/R/x86_64-pc-linux-gnu-library/4.0/SQMtools folder did not exist.

**Comment by leehwmj** [comment]
Unfortunately...

```
(SqueezeMeta) hwlee@bio:~$ sudo R CMD INSTALL ~/anaconda3/envs/SqueezeMeta/SqueezeMeta/lib/SQMtools
* installing to library ‘/home/hwlee/R/x86_64-pc-linux-gnu-library/4.0’
ERROR: dependencies ‘reshape2’, ‘ggplot2’, ‘pathview’, ‘data.table’ are not available for package ‘SQMtools’
* removing ‘/home/hwlee/R/x86_64-pc-linux-gnu-library/4.0/SQMtools’
```

(SqueezeMeta) is activated



And I've run `test_install.pl` again, I got the `All checks successful`

What more needs to be done to help you identify the problem?

**Comment by fpusan** [comment]
You don't need to run it as sudo. That makes use the wrong interpreter (`/home/hwlee/R` instead of the one from conda).
What happens when you type `which R` having activated the SqueezeMeta environment?

**Comment by leehwmj** [comment]
Oh, gosh!

Excluding sudo, it worked.

I was so silly. Thank you.

**Comment by fpusan** [comment]
:)
