### ISSUE TITLE
Numpy not found when running checkm step under conda

### ISSUE THREAD

**Issue by fpusan** [jtamames/SqueezeMeta#268]
I actually got the following error:
```
Running DAS Tool for maxbin,metabat2: LD_LIBRARY_PATH=/home/constancias/miniconda3/envs/SqueezeMeta160321/SqueezeMeta/lib PATH=/home/constancias/miniconda3/envs/SqueezeMeta160321/SqueezeMeta/bin:$PATH /home/constancias/miniconda3/envs/SqueezeMeta160321/SqueezeMeta/bin/DAS_Tool/DAS_Tool -i /datadrive05/Flo/Saliva/Saliva2/squeezemeta/squ
eezmeta_4thstrategy/K9_SALIVA_DNA/results/DAS/maxbin.table,/datadrive05/Flo/Saliva/Saliva2/squeezemeta/squeezmeta_4thstrategy/K9_SALIVA_DNA/results/DAS/metabat2.table -l maxbin,metabat2 -c /datadrive05/Flo/Saliva/Saliva2/squeezemeta/squeezmeta_4thstrategy/K9_SALIVA_DNA/results/01.K9_SALIVA_DNA.fasta --write_bins 1 --score_threshold 0.2
5 --search_engine diamond -t 10 -o /datadrive05/Flo/Saliva/Saliva2/squeezemeta/squeezmeta_4thstrategy/K9_SALIVA_DNA/results/DAS/K9_SALIVA_DNA --db_directory /datadrive05/Flo/db/SqueezeMeta/db --debug
  Reading taxonomic assignments for contigs from /datadrive05/Flo/Saliva/Saliva2/squeezemeta/squeezmeta_4thstrategy/K9_SALIVA_DNA/intermediate/09.K9_SALIVA_DNA.contiglog
  Looking for DASTool bins in /datadrive05/Flo/Saliva/Saliva2/squeezemeta/squeezmeta_4thstrategy/K9_SALIVA_DNA/results/DAS/K9_SALIVA_DNA_DASTool_bins
  Output created in /datadrive05/Flo/Saliva/Saliva2/squeezemeta/squeezmeta_4thstrategy/K9_SALIVA_DNA/intermediate/17.K9_SALIVA_DNA.bintax
PATH=/home/constancias/miniconda3/envs/SqueezeMeta160321/SqueezeMeta/bin:/home/constancias/miniconda3/envs/SqueezeMeta160321/SqueezeMeta/bin/pplacer:/home/constancias/miniconda3/envs/SqueezeMeta160321/SqueezeMeta/bin/hmmer:$PATH /home/constancias/miniconda3/envs/SqueezeMeta160321/SqueezeMeta/bin/checkm taxon_set genus Streptococcus /da
tadrive05/Flo/Saliva/Saliva2/squeezemeta/squeezmeta_4thstrategy/K9_SALIVA_DNA/data/checkm_markers/Streptococcus.ms >> /datadrive05/Flo/Saliva/Saliva2/squeezemeta/squeezmeta_4thstrategy/K9_SALIVA_DNA/syslog 2>&1
Traceback (most recent call last):
  File "/home/constancias/miniconda3/envs/SqueezeMeta160321/SqueezeMeta/bin/checkm", line 45, in <module>
    from checkm import main
  File "/home/constancias/miniconda3/envs/SqueezeMeta160321/SqueezeMeta/bin/../lib/checkm/main.py", line 23, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Linux scelse 5.4.0-66-generic #74~18.04.2-Ubuntu SMP Fri Feb 5 11:17:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

I installed Squeezemeta on  160321 using the conda reciepe and when trying to install numpy whithin the conda environment I got the following message: 

```
(SqueezeMeta160321) $ pip3 install numpy
Requirement already satisfied: numpy in /home/constancias/.local/lib/python3.6/site-packages (1.18.5)
```

I am using Squeezemeta in coassembly mode with the same dataset to explore different approaches and did not get any error.

Any idea what is happening here?

Thanks!

Flo

_Originally posted by @fconstancias in https://github.com/jtamames/SqueezeMeta/issues/266#issuecomment-803286917_

**Comment by fpusan** [comment]
@fconstancias let's continue here.
You say that the `test_install.pl` correctly locates numpy. However checkm does not.
What is the output of the following?
1) `which python3
2) `PATH=/home/constancias/miniconda3/envs/SqueezeMeta160321/SqueezeMeta/bin:/home/constancias/miniconda3/envs/SqueezeMeta160321/SqueezeMeta/bin/pplacer:/home/constancias/miniconda3/envs/SqueezeMeta160321/SqueezeMeta/bin/hmmer:$PATH /home/constancias/miniconda3/envs/SqueezeMeta160321/SqueezeMeta/bin/checkm taxon_set genus Streptococcus /datadrive05/Flo/Saliva/Saliva2/squeezemeta/squeezmeta_4thstrategy/K9_SALIVA_DNA/data/checkm_markers/Streptococcus.ms >> /datadrive05/Flo/Saliva/Saliva2/squeezemeta/squeezmeta_4thstrategy/K9_SALIVA_DNA/syslog`
3) `PATH=/home/constancias/miniconda3/envs/SqueezeMeta160321/SqueezeMeta/bin:/home/constancias/miniconda3/envs/SqueezeMeta160321/SqueezeMeta/bin/pplacer:/home/constancias/miniconda3/envs/SqueezeMeta160321/SqueezeMeta/bin/hmmer:$PATH python3 /home/constancias/miniconda3/envs/SqueezeMeta160321/SqueezeMeta/bin/checkm taxon_set genus Streptococcus /datadrive05/Flo/Saliva/Saliva2/squeezemeta/squeezmeta_4thstrategy/K9_SALIVA_DNA/data/checkm_markers/Streptococcus.ms >> /datadrive05/Flo/Saliva/Saliva2/squeezemeta/squeezmeta_4thstrategy/K9_SALIVA_DNA/syslog`

**Comment by fconstancias** [comment]
Dear @fpusan,

The workstation actually crashed during the test. All is good now with the sequential mode.

Thanks for the support.

**Comment by fpusan** [comment]
Ok, closing issue! Can I also close #266 ?
