### ISSUE TITLE
PacBio long reads

### ISSUE THREAD

**Issue by wangjiawen2013** [jtamames/SqueezeMeta#27]
Dear,
Canu is designed to be universal on a large range of PacBio (C2, P4-C2, P5-C3, P6-C4) and Oxford Nanopore (R6 through R9) data. And, SqueezeMeat uses Canu for assembly of the long, error-prone MinION reads. So, does SqueezeMeat support PacBio long reads ?

**Comment by fpusan** [comment]
It should!
Just make sure to use canu as the assembler (`-a canu`) and minimap in pacbio mode for mapping (`-map minimap2-pb`).

If you need to pass any specific option to canu, you can do so by adding `-assembly_options "string_with_extra_options"`.

**Comment by fpusan** [comment]
Closing this. Let me know if you need further assistance
