### ISSUE TITLE
Disparity in input sequences

### ISSUE THREAD

**Issue by mradz19** [jtamames/SqueezeMeta#270]
I am running Squeezemeta in merged mode using rnaspades as the assembler:
```
SqueezeMeta.pl -m merged -f files/ -s test.samples -p dfi -t 30 --nobin  --singletons --doublepass -c 150 -a rnaspades -assembly_options "--only-assembler"
```
 I noticed that the input sequences seem low for my samples compared to what is actually in the fastq files.

For example counting one samples fastq files gives me this:
```
zcat MR90_unmappedtohg38_R1.fastq.gz | echo $((`wc -l`/4))
3100137
```
However this is the summary from the assembly:
```
Sample 1
  Running Spades (Li et al 2015, Bioinformatics 31(10):1674-6) for 1
  Running prinseq (Schmieder et al 2011, Bioinformatics 27(6):863-4) for selecting contigs longer than 150
Input and filter stats:
        Input sequences: 122,386
        Input bases: 24,087,606
        Input mean length: 196.82
        Good sequences: 118,805 (97.07%)
        Good bases: 23,584,119
        Good mean length: 198.51
        Bad sequences: 3,581 (2.93%)
        Bad bases: 503,487
        Bad mean length: 140.60
        Sequences filtered by specified parameters:
        min_len: 3581
  Renaming contigs
  Counting contig lengths
  Contigs for sample 1 stored in /scratch_mollison/users/30041036/squeezemeta/databases/wound_RNA_runs/dfi/intermediate/01.dfi.1.fasta
```
Why is the input sequences 122,386 rather than 3,100,137?

**Comment by jtamames** [comment]
Hello
That prinseq numbers are relative to the contigs. You can notice it is being done after the assembly and it says "selecting contigs longer than 150". So 122,386 is the number of contigs, and it is normal that you have a lower number than that of raw reads.

Best,
Javier

**Comment by mradz19** [comment]
Hi @jtamames. Ahh so it's not the number of reads input to the assembly but it's the number of contigs following assembly? OK that makes sense
