### ISSUE TITLE
Insufficient memory problem - Step 4 Diamond

### ISSUE THREAD

**Issue by pruethemann** [jtamames/SqueezeMeta#274]
Hello,

We have a problem running SqueezeMeta. We use the following settings:
memory: 125 GB
Threads: 24
b: 8
samples: test samples

The process crashes at step 4 while creating intermediate/04.final.nr.diamond.
The log indicates that it will require 614.63 GB of memory. So we restarted the workflow with a lower b setting and it stilled failed.

By just executing the critical step, we were also not successful:

`diamond blastp -q 03.final.faa -p 4 -d nr.dmnd -e 0.001 --id 60 -f tab -b 1  -o 04.final.nr.diamond`

Here is the syslog of SqueezeMeta:

[syslog.log](https://github.com/jtamames/SqueezeMeta/files/6235861/syslog.log)

And here the error message just executing the critical step:

[Error.log](https://github.com/jtamames/SqueezeMeta/files/6235867/Error.log)

It's worth mentioning that we were able to run the whole process in the past (few weeks ago) without problem and we are not really sure what changed.

the test_install.pl runs successfully and the database has also been re downloaded for testing purposes.

Thanks for feedback

**Comment by fpusan** [comment]
Hard to tell. I'd say there's some kind of problem with your cluster, since the whole process worked ok before. I'm not so familiar with clusters myself...

```
Resource usage summary:

    CPU time :                                   16.91 sec.
    Max Memory :                                 3477 MB
    Average Memory :                             104.44 MB
    Total Requested Memory :                     128000.00 MB
    Delta Memory :                               124523.00 MB
    Max Swap :                                   -
    Max Processes :                              11
    Max Threads :                                12
    Run time :                                   203 sec.
    Turnaround time :                            228 sec.
```

Why is the max memory of only 3477 MB? 
Also what happens if you raise -b a bit, e.g. to 3?
We will include the latest version of diamond in our next release (scheduled for next week if all goes well), that might also make a difference.

**Comment by pruethemann** [comment]
We were able to resolve the issue.

For some reason, the database nr.dmnd got corrupted. The problem had therefore nothing to do with a memory problem. 

The test_install.pl did not indicate any errors. But it turned out that the size of nr.dmnd was too small. Redownloading the database solved the problem.

Thanks for the support.

**Comment by fpusan** [comment]
Thanks for the info! What version of SqueezeMeta were you using? In  861c2f1 (which got into v1.3.1) we added a check for exactly that kind of thing. If you were using v1.3.1 and `test_install.pl` did not complain we should give it another look.
