### ISSUE TITLE
SQMtools : Remove unmapped

### ISSUE THREAD

**Issue by leehwmj** [jtamames/SqueezeMeta#276]
Hi!
I analyzed plotTaxonomy using SQMtools and checked the wide range of unmapped areas. I want to know if there is a way to analyze except unmapped.
<img width="525" alt="스크린샷 2021-04-01 오후 10 52 49" src="https://user-images.githubusercontent.com/22087964/113305128-aeceab00-933d-11eb-97b3-4b1b514de2b8.png">

**Comment by fpusan** [comment]
Hi! As per the SQMtools documentation, you can ignore unmapped reads when making taxonomy plots. Just add `ignore_unmapped=T` when calling `plotTaxonomy`.

**Comment by leehwmj** [comment]
Thank you.
I succeeded in keeping the unmapped invisible, but I want the percentage to be recalculated from the result.
Is there a way to change 40 in a red circle to 100?

<img width="460" alt="스크린샷 2021-04-02 오전 12 37 27" src="https://user-images.githubusercontent.com/22087964/113319123-17248900-934c-11eb-8716-b12523e46c2e.png">

**Comment by leehwmj** [comment]
Rescale=T was applied to solve the problem. Thank you.
