### ISSUE TITLE
Seqmerge mode stops at minimus2

### ISSUE THREAD

**Issue by seppedm** [jtamames/SqueezeMeta#277]
Hi there,

Some issue that happened to me a while ago. I have run three batches of 12 transcriptomics samples. One of them worked excellent in seqmerge mode, but the other two stopped somewhere when trying to merge the first sample pairs. The terminal shows the following error after displaying "merging with minimus2" step:

`Error running command:    /home/bioadmin/Downloads/SqueezeMeta-master_february_2021_update/bin/AMOS/minimus2_mod /home/seppe/squeezemeta/final_run_batch3_noT50/temp/mergedassemblies.final_run_batch3_noT50 -D OVERLAP=100 -D MINID=95 -D THREADS=8 > /dev/null 2>&1 at /home/bioadmin/Downloads/SqueezeMeta-master_february_2021_update/scripts/01.merge_sequential.pl line 103.`

This occurred on both v1.2.0 and v1.3.1. Any ideas how to fix this? Merged mode worked for one of the batches, but takes forever for the other batch, so I therefore wanted to try seqmerge again. 

Here you find the syslog:
[syslog_batch3.txt](https://github.com/jtamames/SqueezeMeta/files/6245464/syslog_batch3.txt)

Note: I made the individual assemblies before, and copied them into the "intermediate" folder after creating this project. This worked for the one project, so I see no reason why it shouldn't work for this one.

**Comment by jtamames** [comment]
Hello!

Could you take a look at this file: /home/seppe/squeezemeta/final_run_batch3_noT50/temp/mergedassemblies.final_run_batch3_noT50.afg.1 and paste it here? (I think it is pretty small and it should not be). 

I am suspecting that the problem is that the assemblies in the intermediate directory are symbolic links to files in your /home/seppe/assemblies directory. Did you try to copy them to the intermediate directory instead of linking?

Best,
Javier

**Comment by seppedm** [comment]
[mergedassemblies.final_run_batch3_noT50.afg.1.txt](https://github.com/jtamames/SqueezeMeta/files/6257422/mergedassemblies.final_run_batch3_noT50.afg.1.txt)

There you go! I will try it with copying the files. I just assumed it would work, since it did work for one group of samples. 

Thanks!!,
Seppe

**Comment by jtamames** [comment]
Yes please, try it that way. It is weird anyway, I will look into it.

Best,
Javier

**Comment by seppedm** [comment]
Hi Javier,

I tried restarting it with the copies and it gives exactly the same result. Maybe I just shouldn't be trying what I am trying to do, restarting the pipeline halfway with copied files...

**Comment by jtamames** [comment]
No no, it should work, you are doing it fine. 
Let´s see if it is something with these particular sequence files. 
First, count how many sequences you have in them: `grep -c ">" 01.final_run_batch3_noT50.T266.fasta; grep -c ">" 01.final_run_batch3_noT50.T14.fasta`. 
Then, remove `01.final_run_batch3_noT50.T266.fasta` and `01.final_run_batch3_noT50.T14.fasta`, and try again. If it fails, please copy the syslog file here again.
Best,
Javier

**Comment by seppedm** [comment]
That gives me 1087479 (T266) and 1655685 (T14) sequences. Restarted without these two files now, you get the update as soon as I get somewhere!

**Comment by seppedm** [comment]
Okayy, now it has merged the first pair! I'm curious to see if all of them will get merged now. Is there a way I can later on merge the two missing files to the whole assembly?

**Comment by jtamames** [comment]
Ok, then it was something related to these files. You can wait until the seqmerge is finished, then run another seqmerge with the final result and one of the files, and the same with the other. 
Could you send me the two conflicting files via wetransfer or similar? I would like to check this issue and see if I can reproduce it.
Best,
Javier

**Comment by seppedm** [comment]
I sent you an email! For the final merging (after this is finished in hopefully a few days), how do I do that? Make another run with the same samples, and just copy the resulting fasta file in the intermediate folder along with the samples that didn't work? 
Thank you and good luck with reproducing the errors. 
Best,
Seppe

**Comment by jtamames** [comment]
Hello Seppe
Thanks for the files! I will try them and see if I can catch the problem. Yes, you can do as you say, wait for the process to finish, then run another seqmerge with the result and the two rogue files.

Best,
Javier

**Comment by jtamames** [comment]
Can reproduce

**Comment by jtamames** [comment]
Ok, I could fix it. It has to do with the different naming os SPAdes contigs. Change line 204 in 01.merge_sequential.pl, reading:

`$ts=join("_",@m);`

by

`$ts=$m[$#m];`

This worked for me with your two files that were having problems.
Best,
Javier

**Comment by seppedm** [comment]
Hi Javier, 

The run without the "corrupt" samples has finished without problems, and the second run where I added the two samples is now running smoothly as well, past the steps where it used to crash. This was done without the adjustment you provided, so it seems the problem only occurred in the first merging step. 

If everything goes well, this will deliver me assemblies that I have been struggling with for a long time, so thank you very much for your help in solving this issue!!! I close this issue now, if you don't hear from me again, you can assume everything went well after this.
