### ISSUE TITLE
anvi-load-sqm

### ISSUE THREAD

**Issue by anilchauhanhp9** [jtamames/SqueezeMeta#283]
Hi,
I ran the following command 
 **python3 /home/hamlab/miniconda/envs/SqueezeMeta/SqueezeMeta/utils/anvio_utils/anvi-load-sqm.py -p /media/hamlab/c191ebf9-60f8-475d-8435-8193920ec7ed/Anil/My_data/Nanopore/whole_genome_metagenome/chota_shigri/Analysis/Squeezemeta/CSG -o /media/hamlab/c191ebf9-60f8-475d-8435-8193920ec7ed/Anil/My_data/Nanopore/whole_genome_metagenome/chota_shigri/Analysis/Squeezemeta/CSG/Anvio_results --num-threads 30 --run-HMMS --force-overwrite --profile-SCVs**

It gave me following outputs-

Loading results from SQM in anvi'o.
/media/hamlab/c191ebf9-60f8-475d-8435-8193920ec7ed/Anil/My_data/Nanopore/whole_genome_metagenome/chota_shigri/Analysis/Squeezemeta/CSG/results/sqm2anvio does not exist
Creating sqm2anvio directory with all the input files for anvi'o
======== sqm2anvio.pl, v1.2 ========
Created anvio gene file (import with anvi-gene-contigs-database): /media/hamlab/c191ebf9-60f8-475d-8435-8193920ec7ed/Anil/My_data/Nanopore/whole_genome_metagenome/chota_shigri/Analysis/Squeezemeta/CSG/results/sqm2anvio/CSG_anvio_genes.txt
Created anvio contig file (import with anvi-gene-contigs-database): /media/hamlab/c191ebf9-60f8-475d-8435-8193920ec7ed/Anil/My_data/Nanopore/whole_genome_metagenome/chota_shigri/Analysis/Squeezemeta/CSG/results/sqm2anvio/CSG_anvio_contigs.txt
Created anvio functions file (import with anvi-import-functions): /media/hamlab/c191ebf9-60f8-475d-8435-8193920ec7ed/Anil/My_data/Nanopore/whole_genome_metagenome/chota_shigri/Analysis/Squeezemeta/CSG/results/sqm2anvio/CSG_anvio_functions.txt
Created anvio taxonomy file (import with anvi-import-taxonomy-for-genes): /media/hamlab/c191ebf9-60f8-475d-8435-8193920ec7ed/Anil/My_data/Nanopore/whole_genome_metagenome/chota_shigri/Analysis/Squeezemeta/CSG/results/sqm2anvio/CSG_anvio_taxonomy.txt
Created anvio-SQM equivalence (just for reference, don't import this): /media/hamlab/c191ebf9-60f8-475d-8435-8193920ec7ed/Anil/My_data/Nanopore/whole_genome_metagenome/chota_shigri/Analysis/Squeezemeta/CSG/results/sqm2anvio/CSG_anvio_SQMequivalence.txt
Added SAM files: CSG.CSGS1.sam CSG.CSGS2.sam
 and converted them to the BAM format
/media/hamlab/c191ebf9-60f8-475d-8435-8193920ec7ed/Anil/My_data/Nanopore/whole_genome_metagenome/chota_shigri/Analysis/Squeezemeta/CSG/results/sqm2anvio
The file ended in '_anvio_contig_taxonomy.txt' seems not to exist. This file should have been generated by sqm2qnvio.pl . If it is not present, remove the directory and this script will create a new one
The process stops with this message
**The file ended in '_anvio_contig_taxonomy.txt' seems not to exist. This file should have been generated by sqm2qnvio.pl . If it is not present, remove the directory and this script will create a new one**

Please help me in resolving the issue...

**Comment by anilchauhanhp9** [comment]
The contents of SQM2Anvio directory is as follows
bam                           CSG_anvio_taxonomy.txt
CSG_anvio_bins.txt            CSG.contig.tax.allfilter.tsv
CSG_anvio_contigs.txt         CSG.contig.tax.nofilter.tsv
CSG_anvio_functions.txt       CSG.contig.tax.prokfilter.tsv
CSG_anvio_genes.txt           CSG.orf.tax.nofilter.tsv
CSG_anvio_SQMequivalence.txt  CSG.orf.tax.prokfilter.tsv

**Comment by ggnatalia** [comment]
Hi!

I think that we solved that bug after making the release, could you replace your version of the script sqm2anvio.pl with the version that is in the branch master (within utils/anvio_utils)?

As you're using conda, you should replace the script located in: 
    
    /home/hamlab/miniconda/envs/SqueezeMeta/SqueezeMeta/utils/anvio_utils/sqm2anvio.pl

with the latest version.

Let me know if this does not fix the issue!

**Comment by anilchauhanhp9** [comment]
Hi,
I implemented you suggestion and now it's working fine
Thank you for your quick response...
