### ISSUE TITLE
Color change of plotTaxonomy graph

### ISSUE THREAD

**Issue by leehwmj** [jtamames/SqueezeMeta#284]
Hi

I am using sqmtools.
I want to change each element to the own color I want. I would like to know how to apply it.
I've already tried as below, but I didn't get the result I wanted

Thanks.

```
> palette <- c('#FF0000', '#800000', '#F08080', '#FF4500', '#FFA500', '#FF8C00', '#FAFAD2', '#EEE8AA', '#7CFC00', '#00FF00', '#808000', '#006400', '#90EE90', '#008080', '#AFEEEE', '#00FFFF')

> plotTaxonomy(chul, rank='phylum', count='percent', color = palette )
Warning message in plotTaxonomy(chul, rank = "phylum", count = "percent", color = palette):
“You passed less/more colors than taxa. Using default colors”
```
![index](https://user-images.githubusercontent.com/22087964/114826341-58b03c00-9e02-11eb-9c95-a2b37bb85534.png)

**Comment by ggnatalia** [comment]
Hi!
It seems that your 'color' vector has one more color than N (plotTaxonomy parameter). N is 15 taxa by default and you're passing 16 colors. You can use a vector with 15 colors, the color of 'Other' has been set by default and it shouldn't be included in your vector.

Let me know if this does not fix the issue!

**Comment by leehwmj** [comment]
thanks a lot.
