### ISSUE TITLE
Deseq2 before or after regroup KO(KEGG ORTHOLOGY) number

### ISSUE THREAD

**Issue by yjiakang** [jtamames/SqueezeMeta#285]
Hello, I am a little confused about when should I perform statistically differential function pathways? Just use the 12.$project.kegg.stamp file? Then regroup the differential KO into pathways using a script (here I found  pathway_pipeline.py contained in the picrust2 pipeline). Or should I regroup it first, then preform deseq2? Thanks.

**Comment by fpusan** [comment]
Hi!
See some examples in our [wiki](https://github.com/jtamames/SqueezeMeta/wiki/Using-R-to-analyze-your-SQM-results)
2.5.1. Diferencial abundances with DESeq2

**Comment by fpusan** [comment]
Also, aggregating KO into pathways can be done relatively easily within SQMtools, but I don't think that the results would be trustworthy.

See [this answer](https://github.com/jtamames/SqueezeMeta/issues/212#issuecomment-765576249) in #212, an issue which discusses doing pathway-level statistics as you propose here.

**Comment by yjiakang** [comment]
Yeah, thanks for your kind reply.
