### ISSUE TITLE
Using merged mode to run metagenome and metatranscriptome at the same time

### ISSUE THREAD

**Issue by regisjr42** [jtamames/SqueezeMeta#287]
Hello, it's me again,

After the amazing help you guys gave me, I managed to find much more reliable results with metatranscriptomic data, but now I also have access to metagenome and wanted to combine both these approaches. I checked the brief tutorial that was presented to me on the subject [here](https://github.com/jtamames/SqueezeMeta/wiki/Combining-metagenomes-and-metatranscriptomes-with-SqueezeMeta) and have a better understanding of how it works.

The problem here arises from the fact that the metatranscriptomic data, as discussed extensively in my [previous](https://github.com/jtamames/SqueezeMeta/issues/226) issue that we solved, has some very specific options required for it to work properly, while merged mode will assume that you are running both datasets with the same configuration. I made a test run with default settings and the results were quite dreadful with less than 50% mapping in some samples and just barely over in that others.

My question is: is it possible for me to run merged mode while specifying certain options specifically for transcriptome and some for the genome?

**Comment by jtamames** [comment]
Hello!
What we could do is: 1) Making independent assemblies with different settings/parameters, and then 2) Merge them together. Would that be ok for your purposes? I can teach you how to trick SqueezeMeta to do that.
Best,
Javier

**Comment by regisjr42** [comment]
Hi Javier,

Sorry for the delay, our server had some issues and we were trying to go over that. Yes, I think the option you suggested could work for us!

What do we need to do so we can run it?

**Comment by jtamames** [comment]
Hello
The user in #288 had a similar issue. Could you take a look at the recipe there and see if you can follow it? Feel free to ask if you find troubles.
Best,
Javier
