### ISSUE TITLE
Merge externally provided assemblies?

### ISSUE THREAD

**Issue by eolesin** [jtamames/SqueezeMeta#288]
Hi, I'm trying to evaluate whether SqueezeMeta will allow me to have individual sample assemblies (produced using MEGAHT) as input for the 01.merge_assemblies.pl ... I'm already performing these so it would be nice to not have to restart those individual sample assemblies. Apologies if this is in the manual but I am not finding it!

**Comment by jtamames** [comment]
Hello
Not directly... buy we can trick it to do it. Basically it will merge all fasta files that are present in the intermediate directory. 
First, create an empty project using the --empty flag in the SqueezeMeta.pl command. For instance SqueezeMeta.pl -p myproject -s mysamplefile -f /path/to/reads -m merged --empty. That will create all directories and conf files. Then, let´s cheat. Suppose you have the following samples file:

A      reads1.fastq   pair1
A      reads2.fastq   pair2
B      reads1.fastq   pair1
B      reads2.fastq   pair2

, where you are saying that you have two samples A and B that are to be assembled separately. Then you have to put in the intermediate directory the fasta files produced in these external assemblies. The name MUST be 01.<sample>.fasta, that is, 01.A.fasta and 01.B.fasta in the example above.
Then run 01.merge_assemblies.pl and it should merge assemblies A and B. After it finishes, you can restart in step 02 for running the rest of the analysis if you want it so.
Just a thing: Contig names need to be different in 01.A.fasta and 01.B.fasta. If they are not, you need to change them or minimus2 will be confused and will not work.
Let me know if it works. I realize this is a frequently weanted feature so probably I will code a workaround for this.
Best,
Javier

**Comment by eolesin** [comment]
Oh, nice! OK, I will come back to you if I have troubles but it sounds like I should be set. Thanks for your quick and thorough reply!
