### ISSUE TITLE
Error at DAS tool step (16)

### ISSUE THREAD

**Issue by morien** [jtamames/SqueezeMeta#29]
I'm working on a system that didn't have doMC installed (my oversight, but I'm not admin), so the first time I encountered it, I had the admins install doMC, but the error persists. I've logged out and logged back in to restart the job, and the error is the same. We added a R.Version() command to the dastool R script, and sunk it to a tmp file to check once the error pops up. When I check that file, the R version is 3.5 (the default on the system). When I start R (default, 3.5) in the terminal and load the libarary(doMC), it loads just fine. Devs, any suggestions on what to check next?

Below is my command, edited for brevity:

```
perl /Linux/SqueezeMeta/scripts/16.dastool.pl projectname
Creating tables of contigs in bins... done
Running DAS Tool for maxbin,metabat2
LD_LIBRARY_PATH=/Linux/SqueezeMeta/scripts/../lib PATH=/Linux/SqueezeMeta/scripts/../bin:$PATH /Linux/SqueezeMeta/scripts/../bin/DAS_Tool/DAS_Tool -i projectname/results/DAS/maxbin.table,projectname/results/DAS/metabat2.table -l maxbin,metabat2 -c projectname/results/01.projectname.fasta --write_bins 1 --score_threshold 0.25 --search_engine diamond -t 32 -o projectname/results/DAS/projectname --db_directory /Archive/Cluster/SqueezeMeta/db
Running DAS Tool using 32 threads.
predicting genes using Prodigal V2.6.3: February, 2016
identifying single copy genes using diamond version 0.9.22
**Error in library(x, character.only = TRUE) :
  there is no package called ‘doMC’
Calls: lapply ... suppressPackageStartupMessages -> withCallingHandlers -> library
Execution halted**
```

Here is the relevant output of the R.Version command we added to the DAStool R script:
> $version.string
> [1] "R version 3.5.1 (2018-07-02)"

**Comment by fpusan** [comment]
It seems that either you have more than one installation of R, or doMC is installed in a non-standard path.

DAStool uses Rscript to call its R code.

Does `which R` and `which Rscript` point to the same installation?

What happens if you create a short script

```
.libPaths()
library(doMC)
````

and run it with `Rscript test.R`?

Does it find the package? (it should not)
Does it show the same paths as running `.libPaths()` from the interactive R console?

**Comment by morien** [comment]
You are quite right, and although there was only one version of R visible in the path, there was another one used by Rscript on the system (3.5.1). The libpaths suggestion helped establish the fix, and I applied it in my .Rprofile, and doMC is visible to all system versions of R. All is working now, thanks for your help!
