### ISSUE TITLE
 SqueezeMeta to annotate eukaryotic rrna operon?

### ISSUE THREAD

**Issue by DeniRibicic** [jtamames/SqueezeMeta#290]
Just wondering whether I can use SqueezeMeta (specifically sqm_longreads.pl workflow) to map ONT long eukaryotic rrna opern amplicon reads against NCBI (or any other taxonomic db within SqueezeMeta), and get out taxonomy counts?

**Comment by jtamames** [comment]
Hello
No. SqueezeMeta uses protein databases, so you should not get good results running rrnas.
Best,
J

**Comment by DeniRibicic** [comment]
Ok, thanks for timely feedback.
