### ISSUE TITLE
Error in Step 17

### ISSUE THREAD

**Issue by manjumoorthy95** [jtamames/SqueezeMeta#293]
I am facing an error in step 17 of Bin Tax Assignment. After few minutes of execution it throws an error, telling “ Killed”. 

What could be the reason? In step 16, I had reduced the bin score cut off to 0, would that be the reason of the above mentioned error?

**Comment by jtamames** [comment]
Hello
Could you please send us the syslog file in the project directory?
Best,
Javier

**Comment by manjumoorthy95** [comment]
[syslog.txt](https://github.com/jtamames/SqueezeMeta/files/6441057/syslog.txt)

**Comment by jtamames** [comment]
Could you run this command and paste the output?

LD_LIBRARY_PATH=/home/akinola/Downloads/SqueezeMeta-master/lib PATH=/home/akinola/Downloads/SqueezeMeta-master/bin:$PATH /home/akinola/Downloads/SqueezeMeta-master/bin/DAS_Tool/DAS_Tool -i /home/akinola/Downloads/SqueezeMeta-master/database/test/fmicrobiome/results/DAS/maxbin.table,/home/akinola/Downloads/SqueezeMeta-master/database/test/fmicrobiome/results/DAS/metabat2.table -l maxbin,metabat2 -c /home/akinola/Downloads/SqueezeMeta-master/database/test/fmicrobiome/results/01.fmicrobiome.fasta --write_bins 1 --score_threshold 0 --search_engine diamond -t 4 -o /home/akinola/Downloads/SqueezeMeta-master/database/test/fmicrobiome/results/DAS/fmicrobiome --db_directory /home/akinola/Downloads/SqueezeMeta-master/database/db --debug

**Comment by manjumoorthy95** [comment]
Running DAS Tool using 4 threads.
predicting genes using Prodigal V2.6.3: February, 2016
identifying single copy genes using diamond version 0.9.22
evaluating bin-sets
starting bin selection from 5 bins 
||
bin selection complete: 2 bins above score threshold selected. 
Error: Faceting variables must have at least one value
Backtrace:
     █
  1. └─DASTool::DER_Plot(bin_evaluations, output_basename)
  2.   └─ggplot2::ggsave(...)
  3.     ├─grid::grid.draw(plot)
  4.     └─ggplot2:::grid.draw.ggplot(plot)
  5.       ├─base::print(x)
  6.       └─ggplot2:::print.ggplot(x)
  7.         ├─ggplot2::ggplot_build(x)
  8.         └─ggplot2:::ggplot_build.ggplot(x)
  9.           └─layout$setup(data, plot$data, plot$plot_env)
 10.             └─ggplot2:::f(..., self = self)
 11.               └─self$facet$compute_layout(data, self$facet_params)
 12.                 └─ggplot2:::f(...)
 13.                   └─ggplot2::combine_vars(data, params$plot_env, cols, drop = params$drop)
Execution halted
extracting bins to /home/akinola/Downloads/SqueezeMeta-master/database/test/fmicrobiome/results/DAS/fmicrobiome_DASTool_bins
akinola@akinola:~/Downloads$

**Comment by manjumoorthy95** [comment]
also just to give you a background information, once we run the Dastools step ( step 16), we would be getting a tax file for all bins inside the Dastool high quality bins dir. But for the total 2 bins I Got , the tax file was created for only 1 bin. So I manually added the tax file in the same folder and tried to run the next step. But all of the steps related to bin, further are failing, like step 17,18,19.

**Comment by jtamames** [comment]
Hello
I can see some inconsistencies in the files. For instance, the .tax file that you copied seems to be misnamed, since the bin in the DAS directory is named metabat2.5.fa.contigs.fa, while the tax file is metabat.001.fasta.contigs.fa.tax (it should be metabat2.5.fa.contigs.fa.tax). You probably copìed it from a different project?
But first things first: DASTool is crashing, perphaps because the metabat coverage table is not correct (I am seeing that it is very small). Could you paste it? It is in `results/DAS/metabat2.table
`
Best,
J

**Comment by manjumoorthy95** [comment]
yes, as i have mentioned above, the .tax file that automatically gets created for every .fa file inside Dastool_bins/ folder was absent in my case. So for the fasta bin file from metabat, I created the .tax file manually and pasted it inside the folder. And I noticed I named in wrong, so later changed it to "metabat2.5.fa.contigs.fa.tax". But this didnt solve the issue. 

And yes will post the result of metabat2.table file below

**Comment by manjumoorthy95** [comment]
[metabat2.table.txt](https://github.com/jtamames/SqueezeMeta/files/6479422/metabat2.table.txt)

**Comment by jtamames** [comment]
No idea of what is going on here. The error you cite is produced in the ggplot library used by DAS, probably because of some inconsistences in the names. Anyway, if the fasta and tax files resulting from step 16 are correct, the following steps must run ok, so I would advice to check these two fasta and two tax files looking for inconsistences. You can also send them to me for inspection.
Also I would like to know how you changed the bn cut-off, and what happened keeping the original cutoff value.
Best,
J

**Comment by manjumoorthy95** [comment]
Please find the required files below :
[maxbin.001.fasta.contigs.fa.tax.txt](https://github.com/jtamames/SqueezeMeta/files/6505758/maxbin.001.fasta.contigs.fa.tax.txt)
[metabat2.5.fa.contigs.fa.tax.txt](https://github.com/jtamames/SqueezeMeta/files/6505759/metabat2.5.fa.contigs.fa.tax.txt)
[metabat2.5.fa.contigs.fa.txt](https://github.com/jtamames/SqueezeMeta/files/6505761/metabat2.5.fa.contigs.fa.txt)
[maxbin.001.fasta.contigs.fa.txt.gz](https://github.com/jtamames/SqueezeMeta/files/6505762/maxbin.001.fasta.contigs.fa.txt.gz)

The bin score cut-off was changed using the "$score_tres16" variable in parameter file, which by default is 0.25 , but was brought down to 0 to include all bins.This was done because when using the default cut-off, there was an error generated in the step 16, mentioning that there are no bins that satisfy the bin score criterion.

**Comment by jtamames** [comment]
Hello
I assume that the file `maxbin.001.fasta.contigs.fa.txt.gz` was compressed by you for uploading it, but the original one was uncompressed, is that correct?
What I can see is that the file `maxbin.001.fasta.contigs.fa.tax.txt`, which contains the taxonomic annotation of the contigs, has a lower number of contigs than the `maxbin.001.fasta.contigs.fa.txt`, containing the sequences. I don't know if that is causing the failure. For trying, could you remove all contigs from `megahit_201855` (included) from `maxbin.001.fasta.contigs.fa.txt`, and restart step 16?
Best,
Javier
