### ISSUE TITLE
Error Step 9 --> Can't open 08.[sample].fun3.tax.noidfilter.noidfilter.wranks 

### ISSUE THREAD

**Issue by BoyerTheo** [jtamames/SqueezeMeta#294]
Hi SqueezeMeta team,

I'm having an issue with the step 9, it says :
```
[3 days, 17 hours, 3 minutes, 35 seconds]: STEP9 -> CONTIG TAX ASSIGNMENT: 09.summarycontigs3.pl
  Reading /shared/ifbstor1/projects/oran_lake_meta/results/squeezemeta/sample_1-5_2/results/08.sample_1-5_2.fun3.tax.wranks
  Writing output to /shared/ifbstor1/projects/oran_lake_meta/results/squeezemeta/sample_1-5_2/intermediate/09.sample_1-5_2.contiglog
  Reading /shared/ifbstor1/projects/oran_lake_meta/results/squeezemeta/sample_1-5_2/results/08.sample_1-5_2.fun3.tax.noidfilter.wranks
Stopping in STEP9 -> 09.summarycontigs3.pl. Program finished abnormally

Can't open /shared/ifbstor1/projects/oran_lake_meta/results/squeezemeta/sample_1-5_2/results/08.sample_1-5_2.fun3.tax.noidfilter.noidfilter.wranks
Died at /shared/ifbstor1/software/miniconda/envs/squeezemeta-1.3.1/bin/SqueezeMeta.pl line 1359.
```
I found it weird that .noidfilter was doubled because i only had 08.sample_1-5_2.fun3.tax.noidfilter.wranks in my results folder however i decided to restart the software after renaming 08.sample_1-5_2.fun3.tax.noidfilter.wranks --> 08.sample_1-5_2.fun3.tax.noidfilter.noidfilter.wranks just to see if it was a naming problem, but it stopped again.

Here is the command i ran : 

SqueezeMeta.pl -m sequential -s $path_data -f $path_reads --euk --D -t $SLURM_CPUS_PER_TASK -b 20
I disabled the assembly step as well as the binning in the sample_file. 

I'm working on a cluster under slurm control. The software have been installed with conda. 
Here is the system log. you have the normal run and then the restart with the change of name at the end.
[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/6441360/syslog.zip)

Have you ever encountered such a problem ? Thank you for any help you might provide me.

**Comment by jtamames** [comment]
Hello!
I will take a look. But I can tell you that it is not a good idea to use "_" in the name of the project (or samples). We use that character for separating fields and could backfire at some point. I am not sure that this is causing your problem tho.
Best,
Javier

**Comment by jtamames** [comment]
Hello again
I think this bug is fixed in the most recent versions of SqueezeMeta. This is similar to #264. Try downloading the most recent version of the 09 script (https://raw.githubusercontent.com/jtamames/SqueezeMeta/master/scripts/09.summarycontigs3.pl) and run it for your project.
Best,
Javier

**Comment by BoyerTheo** [comment]
Thank you very much Javier,
I'll give it a try and come back to you as soon as possible.
Have a good day.
Théo

**Comment by BoyerTheo** [comment]
Hi @jtamames,

I just wanted to keep you up to date, we installed the current version of the sofware 1.4.0beta1 on the cluster.

I first try to only run the 09 script on the buggy project without succes (same error).

I then ran the software for my second sample with the 1.3.1 version. I renamed my sample : sample-6-12 in order to avoid "_", as you said it might have caused the probleme. The sofware crashed at the exact same step, so the issue is probably comming from the version.

Finally, I ran my sample with the current version and with the change of name. Everything worked fine for step9, however, it crashed at step10 maybe due to a lack of space disk or because of RAM (i'm working on it to better understand where it's comming from).

Thank you very much for your help, I wish you a good day,

Théo

**Comment by jtamames** [comment]
Hello Théo
Thanks for the update! Can you verify that the number of contigs is the same in both runs with 1.3.1 and 1.4.0beta1? We did not make any change to 08 in the 1.4.0 version. Also, did you change or update the database between runs?
Best,
J

**Comment by BoyerTheo** [comment]
Hi Javier, 

I'm really sorry, i was running out of space and I needed to run my second sample as fast as possible (my internship report is due early June). I discard the 1.3.1 run... even the standard output (with the time needed for every step).
However, we did not update or make any change with the database between the version, so the problem does not seem to come from there.

Théo

**Comment by jtamames** [comment]
Hello
My guess is that your shorter Diamond run could died because of lack of disk space. Let me know if you have further problems.
Best,
J
