### ISSUE TITLE
sqm_counter

### ISSUE THREAD

**Issue by chandnisidhu** [jtamames/SqueezeMeta#297]
Hi,

Is there any way to increase the number of threads in the pipeline for counting the mapped reads by sqm_counter in step 10? By default, the pipeline is set to use a single thread and the process is very slow while counting the mapped reads. Usually, I use 50 thread for my project but these are only used while mapping and not for counting. 

Best,

Chandni

**Comment by chandnisidhu** [comment]
I updated it to new version and it worked with multithreading :)

**Comment by sdoms** [comment]
I'm having the same 'problem'. I've given SqueezeMeta 48 threads and sqm_counter only opens 12. Step 10 has been running for 1 week now; only 87 samples have been completed. I have 368 in total, so I would like to know if I can speed up the process or if I'm doomed to wait for 3 more weeks for step 10 to finish.

**Comment by fpusan** [comment]
Strange. What's the value of `$numthreads` in the `SqueezeMeta_conf.pl` file within the output directory?

**Comment by sdoms** [comment]
12, so I guess that's the problem. Weird, because other parts of the pipeline did run with 48 threads I think. I did have to restart from step 10 but also gave -t 48 to the restart command.

**Comment by fpusan** [comment]
Restarting will not change the parameters, so I suspect you didn't pass `-t 48` to the initial `SqueeeMeta.pl` call (as 12 is the default value). The `syslog` file records the different system calls made by the pipeline and thus will have details on how many threads were used in the different steps.

**Comment by fpusan** [comment]
If you want to change parameters mid-run you can edit the project's `SqueezeMeta_conf.pl` file before restarting.

**Comment by sdoms** [comment]
Okay, thanks! I had a typo in the initial call it seems like (no space between -t and 48). Thanks for your super quick response! I guess if I would restart step 10 it would start from sample 1 again?

**Comment by fpusan** [comment]
Yes. I think it would skip read mapping but not the counting.

**Comment by fpusan** [comment]
Btw, if you restart with a higher thread count let me know if you see a higher memory usage when counting than before

**Comment by sdoms** [comment]
Hmm, changing the $num_threads in the Squeezemeta_config.pl file did not change the number of threads when restarting. I also tried running the config script. Could it be that the number of threads is also taken from somewhere else?

**Comment by fpusan** [comment]
Have you changed it in the `SqueezeMeta_conf.pl` file inside the project directory? (not the one inside the installation path)

**Comment by sdoms** [comment]
I 'spoke' too soon. It is running with 48 threads now. It didn't kill the old bowtie-align process when I killed the main processes. So I was still looking at that... 
I can confirm that it does skip the alignment to the reference when a bam file is being found. 

For memory usage, it does scale up roughly with the amount of threads being used. With 12 threads, it used up 3.4% of our memory or 55 698 176K to 12.7% or  210 349 204K with 48 threads.

**Comment by fpusan** [comment]
v1.6.3 (released hopefully tomorrow) will reduce memory usage and increase speed of sqm_counter.
