### ISSUE TITLE
Can 16S taxonomic annotation use Greengenes database

### ISSUE THREAD

**Issue by yjiakang** [jtamames/SqueezeMeta#301]
Hello, I noticed that the default database for 16S annotation is RDP database, is it possible to use Greengenes? 
Thanks in advance.

**Comment by fpusan** [comment]
Hi! Not easily. We use RDP classifier which comes built in with its own training dataset for classification. I think you might be able to use an alternate training dataset (maybe based in Greengenes) but we do not support that at the moment, nor plan to do it in the foreseaable future.
You can of course get the 16S rRNA sequences predicted by barrnap and classify them manually with mothur+SILVA, sina+silva, greengenes or whatever other alternative you may think of.

**Comment by yjiakang** [comment]
Thanks for the prompt reply. Another question hitted me, were the fungus sequences omitted when doing taxonomic annotation?

**Comment by jtamames** [comment]
Hello
You mean to annotate the contigs? No, they are not, they are included.
Best,
J
