### ISSUE TITLE
Stopping in STEP1 -> 01.run_assembly.pl. Program finished abnormally

### ISSUE THREAD

**Issue by oyac** [jtamames/SqueezeMeta#302]
Hi SqueezeMeta team,

I am trying to run my samples in coassembly mode and I am having trouble on the first step. I have 69 large samples (par1.fastq.gz is ~215gb and par2.fastq.gz is ~254 gb). Btw, I tried to run them in merged mode, but it also stopped in step 1 after assembling 1 sample.
I am using Ubuntu, and SqueezeMeta 1.3.1. Thanks for your help.

Here is how I run it, the error and syslog.
[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/6546677/syslog.zip)

SqueezeMeta.pl -m coassembly -p rice_meta_co -s Samples_metagenomics.txt -f ./raw/ --nobins

SqueezeMeta v1.3.1 - (c) J. Tamames, F. Puente-Sánchez CNB-CSIC, Madrid, SPAIN

Please cite: Tamames & Puente-Sanchez, Frontiers in Microbiology 9, 3349 (2019). doi: https://doi.org/10.3389/fmicb.2018.03349

Run started Tue May 25 17:06:12 2021 in coassembly mode
Now creating directories
Reading configuration from /home/nioo/ohanac/squeezem/analyses/rice_metagenome/rice_meta_co/SqueezeMeta_conf.pl
Reading samples from /home/nioo/ohanac/squeezem/analyses/rice_metagenome/rice_meta_co/data/00.rice_meta_co.samples
69 samples found: CF5 CC4 CD3 CC2 CA4 WC4 CB4 CE3 CCK3 CC5 WB2 WB5 CC3 CA2 WC2 WCK2 WE5 CC1 CG1 CE1 CA5 CG3 CG4 WD3 CF4 WE1 WCK5 WA2 WA3 WCK4 CB3 CF2 CA1 WC5 CB5 CE2 CC4 WC1 WB4 CB1 WA4 WE3 WA1 CCK5 WD1 WD4 CCK1 WCK3 WB3 CE5 WE2 WC3 CD2 CE4 CCK2 CA3 CB2 CG2 WD2 WCK1 CF3 WA5 CD1 CG5 WE4 CD5 CF1 WB1

Now merging files
[1 hours, 19 minutes, 9 seconds]: STEP1 -> RUNNING CO-ASSEMBL                                                                                                           Y: 01.run_assembly.pl (megahit)
  Running assembly with megahit
Error running command:    /home/nioo/ohanac/.conda/envs/squee                                                                                                           zemetanew/SqueezeMeta/bin/megahit/megahit  -1 /home/nioo/ohan                                                                                                           ac/squeezem/analyses/rice_metagenome/rice_meta_co/data/raw_fa                                                                                                           stq/par1.fastq.gz -2 /home/nioo/ohanac/squeezem/analyses/rice                                                                                                           _metagenome/rice_meta_co/data/raw_fastq/par2.fastq.gz -t 12 -                                                                                                           o /home/nioo/ohanac/squeezem/analyses/rice_metagenome/rice_me                                                                                                           ta_co/data/megahit >> /home/nioo/ohanac/squeezem/analyses/ric                                                                                                           e_metagenome/rice_meta_co/syslog 2>&1 at /home/nioo/ohanac/.c                                                                                                           onda/envs/squeezemetanew/SqueezeMeta/scripts/01.run_assembly.                                                                                                           pl line 115.
Warning: unable to close filehandle properly: Disk quota exce                                                                                                           eded during global destruction.
Stopping in STEP1 -> 01.run_assembly.pl. Program finished abn                                                                                                           ormally
uname: write error: Input/output error

  If you don't know what went wrong or want further advice, p                                                                                                           lease look for similar issues in https://github.com/jtamames/                                                                                                           SqueezeMeta/issues
  Feel free to open a new issue if you don't find the answer                                                                                                            there. Please add a brief description of the problem and uplo                                                                                                           ad the /home/nioo/ohanac/squeezem/analyses/rice_metagenome/ri                                                                                                           ce_meta_co/syslog file (zip it first)
Died at /home/nioo/ohanac/.conda/envs/squeezemetanew/bin/Sque                                                                                                           ezeMeta.pl line 1359.

**Comment by jtamames** [comment]
Hello
There is a message saying "Disk quota exceeded during global destruction", so that is why: you don't have enough disk space in your cluster to run that.
Best,
J

**Comment by oyac** [comment]
I`ll talk to the system admin, then! Thanks!
