### ISSUE TITLE
Expected time for sqm_reads.pl & advice for speeding up? 

### ISSUE THREAD

**Issue by blostein** [jtamames/SqueezeMeta#303]
I'm currently running SqueezeMeta in coassembly mode on 60 samples, but I'm also interested in running sqm_reads.pl to do taxonomic and functional assignments on individual reads. I started a run but even after ~20 hours the first sample wasn't done. The last message in the log file indicated that the multithread LCA was being run on 12 threads, and the *.wranks files all were still being updated. I was running it on slurm HPC with 1 node & 12 cpus per task but CPU efficiency was only 11.97% according to seff.  Is this within the expected run times per sample? Any suggestions on speeding it up?

For example, I was considering using a slurm job array to submit on job of sqm_reads.pl per sample, but wasn't sure how that would feed in to the global tables portion of the sqm_reads.pl script. 

If I restart a run of sqm_reads.pl will it start back from where it ended or overwrite the previous progress? 

Thanks!

**Comment by jtamames** [comment]
Hello!
In my computer, I am getting around 200.000 ORFs annotated per hour per thread. Usually it takes one day or more in processing a single sample. Take into account that you are doing a very heavy work. If you want to analyze 60 (big) samples this way, it will take some time to complete. 
You can split the work in parts, as you say. You will have several result files that you can merge into a single one.
If you restart and interrupted run, I think it will overwrite previous results. But I can fix that for you. I will tell you asap.
Best,
Javier

**Comment by fpusan** [comment]
Also, is the database mounted in a network drive, rather than in a physical drive in the same computer? We have received other reports suggesting that the SQL queries in the LCA go much slower in network drives.

**Comment by jtamames** [comment]
This one should skip Diamonds, LCAs, assignments that were already done. It will still reread results for creating tables tho.

[sqm_reads.pl.gz](https://github.com/jtamames/SqueezeMeta/files/6560204/sqm_reads.pl.gz)

**Comment by blostein** [comment]
Thank you both for your responses!

@fpusan  I'm running it on my university's computing cluster and I have a limited background in computing, but I assume in that configuration that the database is not on the same physical drive as the running job. 

@jtamames awesome thank you so much for your response and the script! It makes sense that it takes a long time.

**Comment by cliffbueno** [comment]
On similar note with regards to runtime, I am simply interested in a KEGG functional profile, so I am going to set the `–-nocog` flag. Would it be possible and make sense to also add a `–-notax` flag to skip the taxonomic assignment, if someone just wants to look at the KEGG output? 

Thanks,
Cliff

**Comment by cliffbueno** [comment]
There also appears to be a `--nopfam` flag for `SqueezeMeta.pl` but I don't see that option for `sqm_reads.pl`

**Comment by fpusan** [comment]
`sqm_reads.pl` will not use pfam whatsoever so no flag is needed.
It would make sense to add a `--notax` flag (to this and to other scripts too), but it not be entirely trivial as many other parts of the pipeline are counting on a taxonomy being available.
I'll add it to my list nonetheless
