### ISSUE TITLE
Error running assembly with spades

### ISSUE THREAD

**Issue by leehwmj** [jtamames/SqueezeMeta#304]
Hello

I am a user who is using SqueezeMeta well.
I am inquiring because an error occurred during the process of accepting with spades using the -a option.

```
Error running command:    /home/hwlee/anaconda3/envs/SqueezeMeta/SqueezeMeta/bin/SPAdes/spades.py  --meta --pe1-1 /home/hwlee/analysis/collect-temp-sequencing/HN00149294_Rawdata/HN00149294_RawData_squeezemeta_spades/data/raw_fastq/par1.fastq.gz --pe1-2 /home/hwlee/analysis/collect-temp-sequencing/HN00149294_Rawdata/HN00149294_RawData_squeezemeta_spades/data/raw_fastq/par2.fastq.gz -m 400 -k 21,33,55,77,99,127  -t 40 -o /home/hwlee/analysis/collect-temp-sequencing/HN00149294_Rawdata/HN00149294_RawData_squeezemeta_spades/data/spades >> /home/hwlee/analysis/collect-temp-sequencing/HN00149294_Rawdata/HN00149294_RawData_squeezemeta_spades/syslog 2>&1 at /home/hwlee/anaconda3/envs/SqueezeMeta/SqueezeMeta/scripts/01.run_assembly.pl line 115.

Stopping in STEP1 -> 01.run_assembly.pl. Program finished abnormally
```

It worked well when using megahit assembly as the default option, but the analysis does not proceed when `-a spades` is applied.

I entered it as follows.
`SqueezeMeta.pl -m coassembly -p HN00149294_RawData_squeezemeta_spades -s HN00149294_RawData.samples -f ./seq --cleaning -a spades --singletons --nocog --nokegg --nopfam -t 40 &> sqeeze_spades.out`

Attach the syslog below.

Thank you.
[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/6589508/syslog.zip)

**Comment by fpusan** [comment]
Hi!
According to the syslog file
` 1:22:42.880     6G / 131G  ERROR  K-mer Counting           (kmer_data.cpp             : 354)   The reads contain too many k-mers to fit into available memory. You need approx. 512.857GB of free RAM to assemble your dataset
`
SPAdes consumes more memory than Megahit, so it's not surprising that it worked with megahit but fails here.
Best,
Fernando

**Comment by leehwmj** [comment]
Thank you

Following your advice, I added `-aspades-assemble_options"--meta--memory 520"` to the command and it worked fine.

However, after more than 60 hours, the assembly was terminated after returning an error.

I couldn't understand well from the error message.
Likewise, I attached syslog.zip, so please review it.

[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/6613069/syslog.zip)

**Comment by leehwmj** [comment]
Hello jtamames.

I didn't check it and attach the file here.
Please review it.
Thanks.

[spades.log.zip](https://github.com/jtamames/SqueezeMeta/files/6614652/spades.log.zip)

**Comment by jtamames** [comment]
Hello
I just can say that it is an internal SPAdes error, I cannot get anything else from the log. Since this is a SPAdes issue, why don´t you email to the SPAdes guys (spades.support@cab.spbu.ru), attaching that log and the params.txt file in the same data/spades directory? They are very nice and helpful.
Best,
Javier

**Comment by jtamames** [comment]
Yes, they requesrt that: the spades.log and params.txt files
Let me know their answer please
Best,

**Comment by leehwmj** [comment]
Thank you, everyone.

I just found a message on the log to ask SPAdes.

The future process will be with SPAdes guys.

Thank you always.
I'll close the issue.
