### ISSUE TITLE
Error during make databases

### ISSUE THREAD

**Issue by kassammohamed** [jtamames/SqueezeMeta#305]
Hello,

I am getting an error when making new reference db with make database:

`Proxy request sent, awaiting response... 404 Not Found
2021-06-04 06:13:51 ERROR 404: Not Found.
Error running command: wget -U '' -P SqDBMay2021 http://andes.cnb.csic.es/SqueezeMeta//db.tar.gz at /home/kassammo/miniconda3/envs/SqueezeMeta_v1.4.0/SqueezeMeta/lib/install_utils/download_confirm.pl line 37.`

It seems that the file http://andes.cnb.csic.es/SqueezeMeta//db.tar.gz does not exist

**Comment by fpusan** [comment]
I'm checking it, maybe our server was temporarily down? Is the issue still persisting?

**Comment by jtamames** [comment]
Try to download the database again, please

**Comment by kassammohamed** [comment]
HI,

Getting another error :

`No host could be reached! at /home/miniconda3/envs/SqueezeMeta_v1.4.0/SqueezeMeta/lib/install_utils/get_host.pl line 11.`

I checked the webpage  of http://andes.cnb.csic.es/ and http://silvani.cnb.csic.es/, don't know if that should be on the website.

![image](https://user-images.githubusercontent.com/65945304/121117670-15df7300-c84b-11eb-97b4-3ccbc1579bd6.png)

**Comment by fpusan** [comment]
So weird. That is indeed what you should be seeing if you can reach the website.
In fact, if you just go to `http://andes.cnb.csic.es/SqueezeMeta/SqueezeMetaDB.tar.gz` you should be able to download the DB directly from your browser.
I just tried to run the scripts from Sweden, and the downloads were successful. What country are you located in? Could it be some firewall problem?

**Comment by kassammohamed** [comment]
Hi 

So problem can be from my side but I have no clue why suddenly the IT change the permissions.
However I am able to download via make_databases_alt.pl, is there a major difference with make_databases.pl ?


Thanks

**Comment by fpusan** [comment]
No difference, only that make_databases_alt points to a server outside our institute
