### ISSUE TITLE
Stopping in STEP4 -> 04.rundiamond.pl. Program finished abnormally. line 66

### ISSUE THREAD

**Issue by marius44** [jtamames/SqueezeMeta#306]
Hello:

I was running the script using a pre-assembled metagenome (a single sample). The first three steps were correct and suddenly it stopped in step 4 saying: 04.rundiamond.pl line 66. Stopping in STEP4 -> 04.rundiamond.pl. Program finished abnormally.

I have an ssh connection to my server. Some info about its system:
Server: Dell PowerEdge T440.
RAM: 48 GB.
Processor: Intel Xeon Silver 4214 3.2 GHz. 
Cores: 12.
Threads: 24.
OS: Ubuntu 20.04.

Hope you can help me.

Best regards, 
Mario.

[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/6627847/syslog.zip)

**Comment by fpusan** [comment]
Hi!
I can see that you passed the `-b 35` flag to `SqueezeMeta.pl`. This is most likely causing DIAMOND to run out of memory. Please use the default parameters, it will try to adjust `b` automatically based on your available memory.

**Comment by marius44** [comment]
¡Manos a la obra, Fernando! I'll try it using the default settings. I'll be back with some news about the results.
Thanks!

**Comment by marius44** [comment]
Here the update. The problem was solved, and it's still working (Step 18). It hasn't shown any problem.

Thanks!
