### ISSUE TITLE
Stopping in STEP18

### ISSUE THREAD

**Issue by comingkms** [jtamames/SqueezeMeta#309]
I tired to run SqueezeMeta on my own data for multiple times using different modes, but it always stop at STEP 18:

 -> 18.checkM_batch.pl. File /intermediate/18.test.DASTool.checkM is empty!

Could you please let me know what is wrong ?

Thanks,

**Comment by fpusan** [comment]
Hi!
Can you share your syslog file with us?
Does the issue happen also with the test data?
Are you running it in a computing cluster with a queue system?

**Comment by comingkms** [comment]
no issue with test samples. But my data is obtained from Nanopore MK1C 
[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/6633456/syslog.zip)

**Comment by jtamames** [comment]
Hello

Did you check that everything is functional (especially checkM which is the one crashing) by running `test_install.pl`?

Also, which is your SqueezeMeta version?

Best,
J

**Comment by jtamames** [comment]
Hello
Which version are you using?
Best,
J

**Comment by comingkms** [comment]
1.4

**Comment by jtamames** [comment]
Could you please run the script 18.checkM_batch.pl and send me the syslog again? i am missing ant checkm error message in the log. Remember that the syntax is 18.checkM_batch.pl <projectname> ('B' in your case)
Best,
J
