### ISSUE TITLE
Error classifier.jar

### ISSUE THREAD

**Issue by 3ccasto** [jtamames/SqueezeMeta#31]
I'm an error when SqueezeMeta try to use the classifier.jar. It say that the jarfile is corrupt.

Running prinseq: /home/grupos/gen/SqueezeMeta/scripts/../bin/prinseq-lite.pl -fasta /SCRATCH/cricasre/Metagenomic/Squeeze/C-6710/data/megahit/final.contigs.fa -min_len 200 -out_good /SCRATCH/cricasre/Metagenomic/Squeeze/C-6710/results/prinseq; mv /SCRATCH/cricasre/Metagenomic/Squeeze/C-6710/results/prinseq.fasta /SCRATCH/cricasre/Metagenomic/Squeeze/C-6710/results/01.C-6710.fasta
Input and filter stats:
	Input sequences: 149,582
	Input bases: 93,788,907
	Input mean length: 627.01
	Good sequences: 149,582 (100.00%)
	Good bases: 93,788,907
	Good mean length: 627.01
	Bad sequences: 0 (0.00%)
	Sequences filtered by specified parameters:
	none
Counting length of contigs
Contigs stored in /SCRATCH/cricasre/Metagenomic/Squeeze/C-6710/results/01.C-6710.fasta
[26 minutes, 8 seconds]: STEP2 -> RNA PREDICTION: 02.run_barrnap.pl
Running barrnap for Bacteria
Running barrnap for Archaea
Running barrnap for Eukaryote
Running barrnap for Mitochondrial
Running RDP classifier: java -jar /home/grupos/gen/SqueezeMeta/scripts/../bin/classifier.jar classify /SCRATCH/cricasre/Metagenomic/Squeeze/C-6710/temp/16S.fasta -o /SCRATCH/cricasre/Metagenomic/Squeeze/C-6710/temp/16S.out -f filterbyconf
Error: Invalid or corrupt jarfile /home/grupos/gen/SqueezeMeta/scripts/../bin/classifier.jar
Error running command:    java -jar /home/grupos/gen/SqueezeMeta/scripts/../bin/classifier.jar classify /SCRATCH/cricasre/Metagenomic/Squeeze/C-6710/temp/16S.fasta -o /SCRATCH/cricasre/Metagenomic/Squeeze/C-6710/temp/16S.out -f filterbyconf at /home/grupos/gen/SqueezeMeta/scripts/../scripts/02.run_barrnap.pl line 120.
Stopping in STEP2 -> 02.run_barrnap.pl

**Comment by fpusan** [comment]
Hi!
what is the md5 checksum of the /home/grupos/gen/SqueezeMeta/scripts/../bin/classifier.jar file?

**Comment by 3ccasto** [comment]
This is the md5 checksum:

d41d8cd98f00b204e9800998ecf8427e  classifier.jar

**Comment by fpusan** [comment]
Yeah, it seems that the file might be corrupt, mine is`babfb701e91eb197eadee71eef8ec6e5`

Try re-downloading it with 

`perl /home/grupos/gen/SqueezeMeta/scripts/preparing_databases/configure_nodb.pl <DBPATH>`

Where <DBPATH> is the path to the SqueezeMeta database (the directory containing "nr.dmnd" amongst others).

**Comment by 3ccasto** [comment]
That worked. Thank you!

**Comment by fpusan** [comment]
Marking as closed, thanks for reporting!
