### ISSUE TITLE
How to get an OTU table

### ISSUE THREAD

**Issue by leehwmj** [jtamames/SqueezeMeta#310]
Hello, I have a question about using SqueezeMeta. 

While analyzing using our sample, we need to get OTU table. 
I tried to use QIIME, but I thought about it because there was no 16srRNA sequence. I was asked by the professor if it can be made in SqueezeMeta. 
We have a whole genome sequence, and SQMtools and anvi'o know how to use it. 
In addition, I wonder if there is a way to make an OTU table using SqueezeMeta. 

Thank you.

**Comment by fpusan** [comment]
Hi!

You can't get your tipical OTU table without having amplicon data and using software such as mothur, QIIME, DADA2...

You could get something conceptually similar if you clustered your bins into metagenomic OTUs (or mOTUs) based on ANI similarity. This is not yet included in SqueezeMeta, and anyways the results of that process should be taken with more caution that those of a standard 16S rRNA gene clustering.

You have phylotype-level tables (phylum, class, family, etc...) as the output of `sqm2tables.py`
