### ISSUE TITLE
Continue assembly from next sample

### ISSUE THREAD

**Issue by oyac** [jtamames/SqueezeMeta#311]
Hello, 

I`ve been using SqueezeMeta in seqmerge mode for my samples (~70), and while it was doing the individual assemblies, my pc lost connection to the server, so it stopped. If I restart the process, it will restart from the 1st sample. Is there any way to make it continue from where it stopped?

Thanks

**Comment by oyac** [comment]
Thanks for your answer! Now I have another problem, in step 1.5  - I already reinstalled SqueezeMeta, as asked in issue   #289

Starting assembly merge
  MERGE 1, 01.rice_meta_sq.WD3.fasta and 01.rice_meta_sq.CA4.fasta (dist 1.00) -> merged_1.rice_meta_sq.fasta
  Running cd-hit-est
  Transforming to afg format
Can't locate XML/Parser.pm in @INC (you may need to install the XML::Parser module) (@INC contains: /home/nioo/ohanac/.conda/envs/squeezemetanew/SqueezeMeta/bin/AMOS/../../lib /home/nioo/ohanac/.conda/envs/squeezemetanew/lib/site_perl/5.26.2//x86_64-linux-thread-multi /home/nioo/ohanac/.conda/envs/squeezemetanew/lib/site_perl/5.26.2/ /home/nioo/ohanac/.conda/envs/squeezemetanew/lib/site_perl/5.26.2/x86_64-linux-thread-multi/ /home/nioo/ohanac/.conda/envs/squeezemetanew/lib/5.26.2//x86_64-linux-thread-multi /home/nioo/ohanac/.conda/envs/squeezemetanew/lib/5.26.2/ /home/nioo/ohanac/.conda/envs/squeezemetanew/lib/5.26.2/x86_64-linux-thread-multi/ /home/nioo/ohanac/.conda/envs/squeezemetanew/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home/nioo/ohanac/.conda/envs/squeezemetanew/lib/site_perl/5.26.2 /home/nioo/ohanac/.conda/envs/squeezemetanew/lib/5.26.2/x86_64-linux-thread-multi /home/nioo/ohanac/.conda/envs/squeezemetanew/lib/5.26.2 .) at /home/nioo/ohanac/.conda/envs/squeezemetanew/SqueezeMeta/bin/AMOS/toAmos line 19.
BEGIN failed--compilation aborted at /home/nioo/ohanac/.conda/envs/squeezemetanew/SqueezeMeta/bin/AMOS/toAmos line 19.
Error running command:    /home/nioo/ohanac/.conda/envs/squeezemetanew/SqueezeMeta/bin/AMOS/toAmos -s /home/nioo/ohanac/squeezem/analyses/rice_metagenome/rice_meta_sq/temp/mergedassemblies.rice_meta_sq.99.fasta -o /home/nioo/ohanac/squeezem/analyses/rice_metagenome/rice_meta_sq/temp/mergedassemblies.rice_meta_sq.afg at /home/nioo/ohanac/.conda/envs/squeezemetanew/SqueezeMeta/scripts/01.merge_sequential.pl line 90.
Stopping in STEP1.5 -> 01.merge_sequential.pl. Program finished abnormally

Thanks for your help, here is the syslog file.
[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/6770607/syslog.zip)

**Comment by jtamames** [comment]
Hello
Sorry for the delay, vacation time for me. Did you run the `test_install.pl` script to check your installation?

**Comment by oyac** [comment]
Hi, 
I had tested the install before and even run another dataset before the problem, but then I was able to solve it by doing another environment an installing the newest version of SqueezeMeta. 

Thanks,

**Comment by jtamames** [comment]
Glad to hear that. I am closing the issue now, feel free to reopen if you experience further problems.
Best,
J
