### ISSUE TITLE
Stopping in STEP18: file 18.project_name.DASTool.checkM is empty

### ISSUE THREAD

**Issue by jilldv** [jtamames/SqueezeMeta#312]
Hello,

I am running squeezemeta in sequential mode but I am getting some errors during the run. In step 15 I get the following message: 
ERROR in STEP15 -> 15.bin_metabat2.pl
wc: /home/jill/biogeo/squeezemeta/biogeo_sequential/13KAP6/results/metabat2/: Is a directory
WARNING in STEP15 -> 15.bin_metabat2.pl. No Metabat2 results!

However, the run continues until step 18. At step 18 the run stops with the following message:
wc: /home/jill/biogeo/squeezemeta/biogeo_sequential/13KAP6/intermediate/18.13KAP6.DASTool.checkM: No such file or directory
Stopping in STEP18 -> 18.checkM_batch.pl. File /home/jill/biogeo/squeezemeta/biogeo_sequential/13KAP6/intermediate/18.13KAP6.DASTool.checkM is empty!

Attached you can find the syslog file for the run.
[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/6688482/syslog.zip)

I have successfully run other samples in sequential mode using the same command. This makes me think my command and squeezemeta installation (I am using version 1.3.1) are ok. So I am not quite sure what the problem may be. Could it have anything to do with the fact that only 2 bins were found (with maxbin)?

Any help would be appreciated very much!

**Comment by jtamames** [comment]
Hello
Yep, metabat does not give any result, then maxbin produces two bins. I guess that these are perhaps eukaryotic bins, then checkM does not give results. If you restart the project in step 19 it should finish ok (but with no bin information about completeness/contamination)
Best,
Javier

**Comment by jilldv** [comment]
The bins were indeed eukaryotic and restarting in step 19 worked. Thank you for the help!

Best,
Jill
