### ISSUE TITLE
The principle of annotating bins' taxonomy and function?

### ISSUE THREAD

**Issue by yjiakang** [jtamames/SqueezeMeta#314]
Hi,  I did not find the methods used for annotating bins' taxonomy and function? Could you be kind to explain it?
And is it possible to use SqueezeMeta pipeline to annotate the bins's taxonomy and their functions (KEGG/COG) standalone? Then produce tables containing the bins, their taxonomy and functions,  and the corresponding abundances. Thanks in advance.
Best
Jk Yin

**Comment by jtamames** [comment]
Hello
For bin taxonomy, we use the consensus taxonomic annotation for the contigs belonging to it (which in turn is the consensus of the taxa for the genes in it). You can find details on how we do the consensus in the manual, in the section "explanation of algorithms". The functions in the bin are the functions for the genes. This is also explained in the manual.
Next release will include a sqm_annot.pl script which will annotate taxa and functions for the genes in standalone mode. We hope to release it in the coming weeks.
Best,
J

**Comment by yjiakang** [comment]
Yeah, thanks for the explanation and hoping for the coming release.
Best
Jk Yin
