### ISSUE TITLE
Can we delete the original raw fastq directory

### ISSUE THREAD

**Issue by slambrechts** [jtamames/SqueezeMeta#318]
After starting a new SQM run, you can delete the raw fastq folder you provided with `-f <raw fastq dir>`, right? Because the fastq files get copied over to the `project/data` folder?

**Comment by fpusan** [comment]
I'm pretty sure you can, but not 100% sure (I didn't code that part of the pipeline)
Maybe try starting a test run and moving the `raw` directory after it starts, if it doesn't crash you're golden!

**Comment by jtamames** [comment]
Hello
Yes, you can delete it safely. You could not redo/restart parts of the analysis, but if you are happy with the results, go ahead.
Best,
J
