### ISSUE TITLE
Subsetting more than one parameter at the same time using SQMTools

### ISSUE THREAD

**Issue by regisjr42** [jtamames/SqueezeMeta#321]
Hello,

As the devs are very familiar at this point, I have data from marine sediment metratranscriptomic. What I wanted now was to subset the taxonomy but instead of, for example, picking up just the phylum, just the order, or just the genus, I wanted to get the whole path to that taxonomy level on the same table. Getting to something like this at the end (doesn't need to be exactly this, but something to this extent):

![image](https://user-images.githubusercontent.com/53579398/124687560-84940880-deab-11eb-8746-02b6c25e48bc.png)

I also noticed looking through the results folder of the SqueezeMeta project that there are tables (`project.order.nofilter.abund.tsv` and others)with such information just like this:

![image](https://user-images.githubusercontent.com/53579398/124687647-af7e5c80-deab-11eb-801b-d6b78d019882.png)

With this in mind, another thought that occurred to me was using these tables to get the information I want, but I did various SqueezeMeta runs for my different treatment groups as I did not have enough memory to run it all at the same time, so it is a little bit fragmented, something that indeed could be solved with some R magic. But since using my SQM objects I was able to merge it all in the end, I wanted to know if there was a way of doing this using my SQM object and a mix of the package and some other R functions.

Hopefully, I was clear enough as this is a very specific and kinda convoluted question.

**Comment by fpusan** [comment]
Not sure I get it, but I'll try my best.
If what you want is to get the long taxa names in SQMtools, this would be easy.
```
genusTable = SQM$taxa$genus$abund
rownames(genusTable) = SQM$misc$tax_names_long$genus[rownames(genusTable)]
# Now genusTable has the full taxonomy path as row names
```
If what you want is to subset by more than one parameter
1) You can just chain different calls to the subset functions:
`subsetFun(subsetTax(SQM, 'phylum', 'Proteobacteria'), 'Nitrogenase')`
2) In the case of subsetFun, you can use regular expressions.

Hope this helps!

**Comment by regisjr42** [comment]
> If what you want is to get the long taxa names in SQMtools, this would be easy.

genusTable = SQM$taxa$genus$abund
rownames(genusTable) = SQM$misc$tax_names_long$genus[rownames(genusTable)]
# Now genusTable has the full taxonomy path as row names

This fits more along the lines of what I wanted. The end result of this method was nice, and I just tinkered a bit with it and got closer to the model I was trying to get.

Thanks!

**Comment by fpusan** [comment]
Glad it helped. Closing issue
