### ISSUE TITLE
Error when subsetting functions based on a regular expression in SQMTools

### ISSUE THREAD

**Issue by regisjr42** [jtamames/SqueezeMeta#325]
Hello,

I tried subsetting some of my DEGs to plot their function in one of my projects but I was met with an error and I don't quite know what might've been wrong here. I successfully did this with others before but now I got stuck in this one. Here is the error:

`Oil222_DEG_IDs <- rownames(degT222Sig)
pattern <- paste(Oil222_DEG_IDs, collapse = '|')
Oill222_blueDEG.DE <- subsetFun(Oil222, pattern, fixed = F)
Error in grepl(fun, SQM$orfs$table[, col], ignore.case = ignore_case,  : 
  invalid regular expression 'K03234|K01069|K03821|K03406|K09550|K02925|K05692|K00113|K00248|K00104|K00249|K08264|K07814|K04371|K03347|K13886|K04392|K03257|K03286|K22462|K00033|K02406|K02895|K02985|K02936|K04536|K03522|K05919|K02542|K07374|K10413|K00194|K02671|K10359|K05946|K02938|K12405|K07803|K11853|K08796|K20478|K03545|K17230|K11180|K02927|K04646|K11584|K22350|K07003|K03694|K00626|K01539|K02666|K17255|K15102|K02941|K02115|K04752|K02388|K00411|K00265|K13587|K00326|K03236|K02729|K00505|K01938|K03006|K03265|K10355|K00632|K02482|K03942|K12314|K02874|K01902|K11262|K07877|K21395|K02973|K13924|K03083|K03073|K06413|K11181|K07466|K01674|K10586|K02407|K10046|K02918|K02877|K12393|K13770|K02940|K04085|K16137|K00652|K12392|K09490|K02674|K02930|K02910|K03413|K17275|K00383|K00404|K07040|K02964|K02991|K03064|K01960|K03231|K10609|K03283|K18740|K20000|K03065|K07897|K12761|K02022|K17050|K10839|K13303|K03178|K04087|K10418|K02889|K03569|K11251|K02932|K00666|K18245|K01682|K02021|K17222|K22068|K079
In addition: Warning message:
In grepl(fun, SQM$orfs$table[, col], ignore.case = ignore_case,  :
  TRE pattern compilation error 'Out of memory'`

It says that was an invalid regular expression but I did just the same as I was doing before, and had no errors prior to that. Any opinions on what might've happened?

**Comment by fpusan** [comment]
The expression seems to be ok (I've actually done similar things in the past). But it seems that you are running out of memory (`TRE pattern compilation error 'Out of memory'`)

**Comment by fpusan** [comment]
Since you are using `|`, can you try doing two partial subset operations and then combining the results with `combineSQM`?

**Comment by regisjr42** [comment]
Just now I noticed my example code was all unformatted, sorry about that. Glad you managed to understand it anyways.

But yeah, by separating it in two it worked. It was the memory indeed. But I didn't think this should have happened here, this shouldn't be very taxing on memory, right?

**Comment by fpusan** [comment]
I don't think so, unless your project is very large... but this is related to regexps and the internals of `grep` in R, with which I am not really familiar...

**Comment by regisjr42** [comment]
At least I got it to work, the problem is probably my laptop that has been acting up recently. Thanks a lot for the help, as always!

**Comment by fpusan** [comment]
Glad it worked, closing issue
