### ISSUE TITLE
error in script 10

### ISSUE THREAD

**Issue by inmagh** [jtamames/SqueezeMeta#329]
Maybe I am wrong but in the script 10.mapsamples.pl on line 449, I think there are a mistake in the way to calculate rpkm:

my $rpkm=($readcount{$rc}{reads}*1000000000)/(($longt/1000)*$totalreadcount); #-- Length of contig in Kbs

so you multiply by 1000 millions so the value is 1000 higher. For genes the formula is ok.

**Comment by jtamames** [comment]
Hello
Yep, you are correct, thank you for pointing out this mistake. I have already corrected this in the release. Just change the 1000000000 by 1000000 in line 449.
Best,
Javier
