### ISSUE TITLE
Error in step 22

### ISSUE THREAD

**Issue by mradz19** [jtamames/SqueezeMeta#330]
My run finished all the way to step 22 then I got this error:

```
[1 days, 13 hours, 18 minutes, 46 seconds]: STEP22 -> 22.stats.pl
Stopping in STEP22 -> 22.stats.pl. Program finished abnormally  
```

**Comment by mradz19** [comment]
Just to expand, I was hoping I still may be able to open the project in SQMtools but I got this error:

```
> final_run<-loadSQM('final_run/')
Loading orfs
    table...
    abundances...
    sequences
    taxonomy...
Loading contigs
    table...
    abundances...
    sequences...
    taxonomy...
Loading taxonomies
Loading functions
Error in colSums(SQM$functions[[method]]$tpm) : 
  'x' must be an array of at least two dimensions
In addition: Warning message:
In loadSQM("final_run/") :
      There are no PFAM results in your project. Skipping...
```

I assume that would be related to step 22 not running?

**Comment by fpusan** [comment]
Not necessarily...
What version of SQM are you using? Can you attach the `syslog` file?
Any chance you can share the project (minus the `data` directory) with me?

**Comment by mradz19** [comment]
[syslog.txt](https://github.com/jtamames/SqueezeMeta/files/6814349/syslog.txt)

I've attached the syslog file. What would be the best way to share the project?

**Comment by mradz19** [comment]
And it is version 0.6.1 of SQMtools

**Comment by fpusan** [comment]
Try updating to the latest version, the bug when loading the data was fixed in v0.6.2 of SQMtools. You may also need to upgrade SqueezeMeta from 1.3.1 to 1.4.

**Comment by mradz19** [comment]
What is the best way for me to update both? I won't need to redo the pipeline will I?

**Comment by fpusan** [comment]
Hopefully not. Just create a new conda environment with the latest version...

**Comment by mradz19** [comment]
I updated to latest version of Squeezemeta and SQMtools and I still get the same error at step 22:

```
[0 seconds]: STEP22 -> 22.stats.pl
Stopping in STEP22 -> 22.stats.pl. Program finished abnormally
```

But I am able to generate a SQM object using load SQM.

**Comment by mradz19** [comment]
I am trying to subsetTax for bacteria only but I am getting the following error:

```
bacteria <- subsetTax(DFI, rank = "superkingdom", tax = "Bacteria", ignore_unclassified_functions = T)
Error in aggregate.fun(subSQM, "PFAM", trusted_functions_only, ignore_unclassified_functions) : 
  fun %in% names(SQM$functions) is not TRUE
```

Can I not do it because I skipped pfam annotations?

**Comment by mradz19** [comment]
Disregard that last comment issue was fixed when I updated to latest version of SQMtools

**Comment by jtamames** [comment]
The error in 22 is weird. Should it be caused by a missing result file, SqueezeMeta should have reported a "Cannot find" error. Instead, the error you get looks like a crash in a external dependence. The only external stuff we are running in 22 is prinseq. Could you try commenting lines 65 and 66 in the script 22, and run it again?

Best,
J
