### ISSUE TITLE
Can't locate Tie/IxHash.pm in @INC when using conda

### ISSUE THREAD

**Issue by aalkin2001** [jtamames/SqueezeMeta#332]
Starting script: perl /home/aalafiatayo/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/SqueezeMeta.pl -m coassembly -p analysis_results -s nanopore_data.txt -f nanopore --miniden 60--minion -t 12

Result: Can't locate Tie/IxHash.pm in @INC (you may need to install the Tie::IxHash module) (@INC contains: /gpfs/home/aalafiatayo/miniconda3/lib/site_perl/5.26.2/x86_64-linux-thread-multi /gpfs/home/aalafiatayo/miniconda3/lib/site_perl/5.26.2 /gpfs/home/aalafiatayo/miniconda3/lib/5.26.2/x86_64-linux-thread-multi /gpfs/home/aalafiatayo/miniconda3/lib/5.26.2 .) at /home/aalafiatayo/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/SqueezeMeta.pl line 12.

**Comment by fpusan** [comment]
Hi,
Is the `SqueezeMeta` environment activated? It seems that it is only searching for libraries in your base environment...

**Comment by fpusan** [comment]
Also
1) What exact command did you use to install SqueezeMeta
2) What messages you get when you run `test_install.pl`?

**Comment by aalkin2001** [comment]
Hi,
Thanks for your reply.

Yes, the SqeezeMeta environment was activated.

Response 1.
conda create -n SqueezeMeta -c conda-forge -c bioconda -c fpusan squeezemeta

Response 2.
(SqueezeMeta) [aalafiatayo@login2 ~]$ /home/aalafiatayo/miniconda3/envs/SqueezeMeta/SqueezeMeta/utils/install_utils/test_install.pl

Checking the OS
	linux OK

Checking that tree is installed
	tree --help OK

Checking that ruby is installed
	ruby -h OK

Checking that java is installed
	java -h OK

Checking that all the required perl libraries are available in this environment
	perl -e 'use Term::ANSIColor' OK
	perl -e 'use DBI' OK
	perl -e 'use DBD::SQLite::Constants' OK
	perl -e 'use Time::Seconds' OK
	perl -e 'use Tie::IxHash' OK
	perl -e 'use Linux::MemInfo' OK
	perl -e 'use Getopt::Long' OK
	perl -e 'use File::Basename' OK
	perl -e 'use DBD::SQLite' OK
	perl -e 'use Data::Dumper' OK
	perl -e 'use Cwd' OK
	perl -e 'use XML::LibXML' OK
	perl -e 'use XML::Parser' OK
	perl -e 'use Term::ANSIColor' OK

Checking that all the required python libraries are available in this environment
	python3 -h OK
	python3 -c 'import numpy' OK
	python3 -c 'import scipy' OK
	python3 -c 'import matplotlib' OK
	python3 -c 'import dendropy' OK
	python3 -c 'import pysam' OK
	python3 -c 'import pandas' OK
	python3 -c 'import cython' OK
	python3 -c 'import future' OK

Checking that all the required R libraries are available in this environment
	R -h OK
	R -e 'library(doMC)' OK
	R -e 'library(ggplot2)' OK
	R -e 'library(data.table)' OK
	R -e 'library(reshape2)' OK
	R -e 'library(pathview)' OK
	R -e 'library(DASTool)' OK
	R -e 'library(SQMtools)' OK

Checking that SqueezeMeta is properly configured... checking database in /gpfs/home/aalafiatayo/miniconda3/envs/SqueezeMeta/SqueezeMeta/databases/db
	nr.db OK
	CheckM manifest OK
	LCA_tax DB OK

All checks successful

(SqueezeMeta) [aalafiatayo@login2 ~]$

**Comment by fpusan** [comment]
This is weird...
` perl -e 'use Tie::IxHash' OK`

The test script is actually trying to load `Tie/IxHash.pm` and succeeding. So I don't understand why it's not working when you try to run SqueezeMeta...

Can you try the following?
1) Load the SqueezeMeta conda environment.
2) Run `test_install.pl`. It should give no errors, as you showed before.
3) Run ` perl -e 'use Tie::IxHash` manually in the command prompt. Do you get the error here?
4) Run `SqueezeMeta.pl -m coassembly -p analysis_results -s nanopore_data.txt -f nanopore --miniden 60--minion -t 12`. Do you get the error here?

**Comment by aalkin2001** [comment]
Thanks for your inputs; it's now working fine. Unfortunately, I encountered another issue at step 1. See details below.

mv: cannot stat ‘/gpfs/home/aalafiatayo/miniconda3/envs/SqueezeMeta/SqueezeMeta/databases/test/analysis_results/data/canu/analysis_results.contigs.fasta’: No such file or directory
Error running command:    /gpfs/home/aalafiatayo/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/canu/canu  -p analysis_results -d /gpfs/home/aalafiatayo/miniconda3/envs/SqueezeMeta/SqueezeMeta/databases/test/analysis_results/data/canu genomeSize=5m corOutCoverage=10000 corMhapSensitivity=high corMinCoverage=0 redMemory=44.8 oeaMemory=44.8 batMemory=44.8 mhapThreads=60 mmapThreads=60 ovlThreads=60 ovbThreads=60 ovsThreads=60 corThreads=60 oeaThreads=60 redThreads=60 batThreads=60 gfaThreads=60 merylThreads=60  -nanopore-raw  /gpfs/home/aalafiatayo/miniconda3/envs/SqueezeMeta/SqueezeMeta/databases/test/analysis_results/data/raw_fastq/par1.fastq.gz > /gpfs/home/aalafiatayo/miniconda3/envs/SqueezeMeta/SqueezeMeta/databases/test/analysis_results/syslog 2>&1; mv /gpfs/home/aalafiatayo/miniconda3/envs/SqueezeMeta/SqueezeMeta/databases/test/analysis_results/data/canu/analysis_results.contigs.fasta /gpfs/home/aalafiatayo/miniconda3/envs/SqueezeMeta/SqueezeMeta/databases/test/analysis_results/data/canu/contigs.fasta at /gpfs/home/aalafiatayo/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/01.run_assembly.pl line 119.

Died at /home/aalafiatayo/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/SqueezeMeta.pl line 1367.
[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/6851523/syslog.zip)

**Comment by fpusan** [comment]
Closing this, will continue in a new issue
