### ISSUE TITLE
Canu error

### ISSUE THREAD

**Issue by fpusan** [jtamames/SqueezeMeta#333]
Thanks for your inputs; it's now working fine. Unfortunately, I encountered another issue at step 1. See details below.

mv: cannot stat ‘/gpfs/home/aalafiatayo/miniconda3/envs/SqueezeMeta/SqueezeMeta/databases/test/analysis_results/data/canu/analysis_results.contigs.fasta’: No such file or directory
Error running command:    /gpfs/home/aalafiatayo/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/canu/canu  -p analysis_results -d /gpfs/home/aalafiatayo/miniconda3/envs/SqueezeMeta/SqueezeMeta/databases/test/analysis_results/data/canu genomeSize=5m corOutCoverage=10000 corMhapSensitivity=high corMinCoverage=0 redMemory=44.8 oeaMemory=44.8 batMemory=44.8 mhapThreads=60 mmapThreads=60 ovlThreads=60 ovbThreads=60 ovsThreads=60 corThreads=60 oeaThreads=60 redThreads=60 batThreads=60 gfaThreads=60 merylThreads=60  -nanopore-raw  /gpfs/home/aalafiatayo/miniconda3/envs/SqueezeMeta/SqueezeMeta/databases/test/analysis_results/data/raw_fastq/par1.fastq.gz > /gpfs/home/aalafiatayo/miniconda3/envs/SqueezeMeta/SqueezeMeta/databases/test/analysis_results/syslog 2>&1; mv /gpfs/home/aalafiatayo/miniconda3/envs/SqueezeMeta/SqueezeMeta/databases/test/analysis_results/data/canu/analysis_results.contigs.fasta /gpfs/home/aalafiatayo/miniconda3/envs/SqueezeMeta/SqueezeMeta/databases/test/analysis_results/data/canu/contigs.fasta at /gpfs/home/aalafiatayo/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/01.run_assembly.pl line 119.

Died at /home/aalafiatayo/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/SqueezeMeta.pl line 1367.
[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/6851523/syslog.zip)

_Originally posted by @aalkin2001 in https://github.com/jtamames/SqueezeMeta/issues/332#issuecomment-883741893_

**Comment by fpusan** [comment]
Are you running SqueezeMeta in a cluster?
If so, please try adding `-assembly_options  "useGrid=false"` when calling SqueezeMeta.
In case this also fails, please share the new `syslog` file with us.

**Comment by aalkin2001** [comment]
Hi, 
Thanks for the feedback. Yes, I'm running SqueezeMeta on a cluster, and after adding -assembly_options "useGrid=false" to the command as suggested, I still get an error output. Attached is the syslog file.
[syslog2.zip](https://github.com/jtamames/SqueezeMeta/files/6856223/syslog2.zip)

**Comment by fpusan** [comment]
```
-- ERROR
-- ERROR
-- ERROR  Found 1 machine configuration:
-- ERROR    class0 - 1 machines with 32 cores with 63 GB memory each.
-- ERROR
-- ERROR  Task meryl can't run on any available machines.
-- ERROR  It is requesting:
-- ERROR    merylMemory=4-12 memory (gigabytes)
-- ERROR    merylThreads=60 threads
-- ERROR
-- ERROR  No available machine configuration can run this task.
-- ERROR
-- ERROR  Possible solutions:
-- ERROR    Change merylMemory and/or merylThreads
-- ERROR
```

It seems that you are requesting 60 threads but your node only supports 32.  Please make sure that the number of threads you use when launching SqueezeMeta is concordant with the resources you will be getting from your cluster.

**Comment by aalkin2001** [comment]
Thank you so much, It's now working fine. I'm still a novice in bioinformatics.

**Comment by fpusan** [comment]
Glad it worked! Closing issue
