### ISSUE TITLE
Step 8 missed out

### ISSUE THREAD

**Issue by aalkin2001** [jtamames/SqueezeMeta#334]
SqueezeMeta completed all the runs from 1 to 22, but Step 8 was omitted, and the resulting out did not produce a result for Blastx on parts of the contigs with no gene prediction or no hits. Kindly find the attached syslog. Thank you.

[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/6857937/syslog.zip)

**Comment by fpusan** [comment]
Did you add the `-D` flag whan calling `SqueezeMeta.pl` as stated in the documentation?

**Comment by aalkin2001** [comment]
Problem solved. Thank you.
