### ISSUE TITLE
Dealing with combine metagenome and metatranscriptome data

### ISSUE THREAD

**Issue by mradz19** [jtamames/SqueezeMeta#335]
I noticed in the wiki you have a tutorial on working with rna and dna data simultaneously, but I am not too keen on doing a merged run as I have found that minimus2 is just too slow. 

Can you recommend any other workflows for when you have dna and rna data for each samples? Ideally I'd like to do the binning for the dna data as well.

**Comment by mradz19** [comment]
On top of that, I saw this really nice figure on a paper which used Squeezemeta. Would you know how to get this brite pathway summary using squeezemeta output?

https://www.frontiersin.org/files/Articles/624070/fenvs-09-624070-HTML-r1/image_m/fenvs-09-624070-g006.jpg

**Comment by fpusan** [comment]
In that case I would assemble and bin the metagenomes and use the metatranscriptomes just for mapping and abundance estimation.
You can do that by adding `noassembly,nobinning` to the RNA samples in the samples file, like in

```
RNA_sample_1      foo_1_1.fastq.gz       pair1   noassembly,nobinning
RNA_sample_1      foo_1_2.fastq.gz       pair2   noassembly,nobinning
```

The BRITE data for each KEGG ID are stored in SQMtools under `SQM$misc$KEGG_paths`

**Comment by mradz19** [comment]
Thanks!

How do I get access to that?

```
kegg_path<-bacteria$misc$KEGG_paths
```

Just gives me Values in R which I can't look at.

**Comment by fpusan** [comment]
`KEGG_paths` is a named vector. So if you want to get the path for a specific KO you would go like `KEGG_paths['K02014']`
That way you can get the information relevant for the functions you plan on including in your figure.
You'll have to write custom R code in order to get everything you need for a custom figure such as the one you attached.

**Comment by mradz19** [comment]
Hi @fpusan. Sorry for coming back to this, but like in the figure above is there a way I can subset the data so that I can plot the taxa and function together on a heatmap rather than the default sample and function? I have 7 taxa I am interested in and I would like to plot their most abundant functions irrespective of the actual sample.

**Comment by mradz19** [comment]
![fenvs-09-624070-g009](https://user-images.githubusercontent.com/50640383/158501427-e3280c65-734b-4554-9fdf-cd798893e2cf.jpeg)
Something similar to this where it is taxa by function rather than sample by funciton

**Comment by fpusan** [comment]
It is possible but not directly.
You can for sure get the functions present in a given taxa by running `subsetTaxa`. If you run this for all the taxa of interest, you can manually build a matrix of functions per taxa that you can then plot using `plotHeatmap` (or the more advanced plotting functions in R or ggplot2).
