### ISSUE TITLE
Error in Step 18

### ISSUE THREAD

**Issue by gogol96** [jtamames/SqueezeMeta#337]
The process for my data is giving error at Step 18, details of Which are quoted below:

**0 seconds]: STEP18 -> CHECKING BINS: 18.checkM_batch.pl
  Evaluating bins with CheckM (Parks et al 2015, Genome Res 25, 1043-55)

  Reading /media/arnab/4B7104350A3E6C35/SqueezeMeta-master/data/alltaxlist.txt
  Looking for DASTool bins in /media/arnab/4B7104350A3E6C35/okhlalandfill/results/DAS/okhlalandfill_DASTool_bins
  26 bins found

  Bin 1/26: metabat2.27.fa.contigs.fa.tax
  Bin 2/26: maxbin.001.fasta.contigs.fa.tax
  Bin 3/26: maxbin.006.fasta.contigs.fa.tax
  Bin 4/26: maxbin.010.fasta_sub.contigs.fa.tax
  Bin 5/26: maxbin.012.fasta.contigs.fa.tax
  Bin 6/26: maxbin.015.fasta_sub.contigs.fa.tax
  Bin 7/26: maxbin.031.fasta_sub.contigs.fa.tax
  Bin 8/26: maxbin.037.fasta.contigs.fa.tax
  Bin 9/26: maxbin.038.fasta_sub.contigs.fa.tax
  Bin 10/26: maxbin.046.fasta.contigs.fa.tax
  Bin 11/26: maxbin.047.fasta.contigs.fa.tax
  Bin 12/26: maxbin.048.fasta.contigs.fa.tax
  Bin 13/26: maxbin.052.fasta.contigs.fa.tax
  Bin 14/26: maxbin.053.fasta.contigs.fa.tax
  Bin 15/26: maxbin.054.fasta.contigs.fa.tax
  Bin 16/26: maxbin.055.fasta.contigs.fa.tax
  Bin 17/26: metabat2.13.fa.contigs.fa.tax
  Bin 18/26: metabat2.19.fa.contigs.fa.tax
  Bin 19/26: metabat2.25.fa.contigs.fa.tax
  Bin 20/26: metabat2.4.fa_sub.contigs.fa.tax
  Bin 21/26: metabat2.41.fa.contigs.fa.tax
  Bin 22/26: metabat2.45.fa.contigs.fa.tax
  Bin 23/26: metabat2.49.fa.contigs.fa.tax
  Bin 24/26: metabat2.55.fa.contigs.fa.tax
  Bin 25/26: metabat2.57.fa.contigs.fa.tax
  Bin 26/26: metabat2.6.fa.contigs.fa.tax

  Storing results for DASTool in /media/arnab/4B7104350A3E6C35/okhlalandfill/intermediate/18.okhlalandfill.DASTool.checkM
wc: /media/arnab/4B7104350A3E6C35/okhlalandfill/intermediate/18.okhlalandfill.DASTool.checkM: No such file or directory
Stopping in STEP18 -> 18.checkM_batch.pl. File /media/arnab/4B7104350A3E6C35/okhlalandfill/intermediate/18.okhlalandfill.DASTool.checkM is empty!

  If you don't know what went wrong or want further advice, please look for similar issues in https://github.com/jtamames/SqueezeMeta/issues
  Feel free to open a new issue if you don't find the answer there. Please add a brief description of the problem and upload the okhlalandfill/syslog file (zip it first)
Died at /media/arnab/4B7104350A3E6C35/SqueezeMeta-master/scripts/restart.pl line 584.**

When I separately run 18.checkM_batch.pl, there shows no error, but the output file is not found in the directory.

However, in the first case, the process ran okay from Step 19.

I am attaching the syslog
[syslog.txt.zip](https://github.com/jtamames/SqueezeMeta/files/6894931/syslog.txt.zip)

**Comment by jtamames** [comment]
Hello
Could it be that your bins are all eukaryotic? Could you copy here the the 17.okhlalandfill.bintax file in the intermediate directory?

Best,
J
