### ISSUE TITLE
cannot work with SQMtools in my local machine

### ISSUE THREAD

**Issue by khidalgo85** [jtamames/SqueezeMeta#339]
Hi @fpusan @jtamames 

Im trying to work with SQMtools in my local machine. I used the `SQMtools.tar.gz` that @fpusan attached in the [#60 ](https://github.com/jtamames/SqueezeMeta/issues/60) and it was installed successfully in my laptop. Additionally I got my project directory from the server that I used to run SQM. But when I try to load the project with `loadSQM()` in RStudio, it was displayed the next message:

`Generating tabular outputs for project in 07.SQM_area4/
sh: /opt/Miniconda3/envs/SqueezeMeta.V1.3/SqueezeMeta/utils/sqm2tables.py: No such file or directory
Error in loadSQM("07.SQM_area4/") : 
  An error occurred while running sqm2tables.py
In addition: Warning message:
In system(command) : error in running command``

 My system info: 
`               _                           
platform       x86_64-apple-darwin17.0     
arch           x86_64                      
os             darwin17.0                  
system         x86_64, darwin17.0          
status                                     
major          4                           
minor          0.5                         
year           2021                        
month          03                          
day            31                          
svn rev        80133                       
language       R                           
version.string R version 4.0.5 (2021-03-31)
nickname       Shake and Throw `

Can you help me? please!

**Comment by jtamames** [comment]
Hello Kelly!
Why don't you use the SQMtools that is shipped with your SqueezeMeta distribution? The one you are pointing to is pretty old, surely that is the cause for your trouble

Best,
Javier

**Comment by khidalgo85** [comment]
Hi @fpusan 

Thanks for your answer. Im compress the directory `~/SqueezeMeta/SqueezeMeta/lib/SQMtools` to `SQMtools.tar.gz` but R displays the next message 

```
ERROR: dependency ‘pathview’ is not available for package ‘SQMtools’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/SQMtools’
Warning in install.packages :
  installation of package ‘/Volumes/GoogleDrive/Mi unidad/Doutorado/Projeto_REMA_PETROBRAS_UNICAMP/Coleta_junho_2020/Shotgun/squeezemeta/SQMtools.tar.gz’ had non-zero exit status
```

**Comment by khidalgo85** [comment]
Solved. I installed 'pathview' dependency. Thanks!
