### ISSUE TITLE
Krona Visualization

### ISSUE THREAD

**Issue by aalkin2001** [jtamames/SqueezeMeta#343]
Hi there,

I tried to visualize my SqueezeMeta output result using Krona tool, but I got the below error message. Please, do you have suggestion on how I could navigate this problem?

Thank you.

Error in exportKrona(fmicrobiome) : 
  ktImportText (from KronaTools) is not present in your PATH. KronaTools can be downloaded from https://github.com/marbl/Krona
In addition: Warning message:
In system("ktImportText", ignore.stdout = T, ignore.stderr = T) :
  error in running command

**Comment by fpusan** [comment]
Hi there!
` ktImportText (from KronaTools) is not present in your PATH. KronaTools can be downloaded from https://github.com/marbl/Krona`
This means that you have to download and install KronaTools from the provided webpage `https://github.com/marbl/Krona`.
It will also work if you install it with conda, as long as the conda environment is active.

**Comment by aalkin2001** [comment]
Thank you so much. Problem solved.
