### ISSUE TITLE
Can SqueezeMeta.pl be run on a GPU basis?

### ISSUE THREAD

**Issue by leehwmj** [jtamames/SqueezeMeta#345]
Hello

I'm a researcher with a lot of help from SqueezeMeta.

Our laboratory uses server computers with high performance GPUs.
We use that computer to run Squeezemeta, and I wonder if there is an option to analyze it using GPUs instead of CPU and RAM for faster analysis.

Thank you.

**Comment by fpusan** [comment]
No, for the most part the software we redistribute in SqueezeMeta has no good GPU alternative.

**Comment by leehwmj** [comment]
Thanks a lot. fpusan.
