### ISSUE TITLE
I have run my data in Sequential mode then after running...i did these following steps.

### ISSUE THREAD

**Issue by dutta237** [jtamames/SqueezeMeta#346]
# Combine your tables
combine-sqm-tables.py /path/to/proj1 /path/to/proj2 -o output_dir
# Now load the data into R
R
library(SQMtools)
combi = loadSQMlite("output_dir")

 But I am unable to use further commands for taxonomy (family, genus) , KEGG, COG etc 
I tried using the commmands in SqueezeMeta downstream analysis by R commands in the manual... but I am getting error. It would be great if I could use some help regarding the commands.

**Comment by fpusan** [comment]
What errors are you getting exactly?

**Comment by dutta237** [comment]
See i have run sequential mode...i dont have any project name..so its showing my project file doesnt exist..

**Comment by dutta237** [comment]
> What errors are you getting exactly?

As i have run sequential mode...i dont have any project name..so its showing my project file doesnt exist..And instead giving project name there...i tried using the output dir name obtained by (combine-sqm-table.py)  which i loaded in R.

**Comment by fpusan** [comment]
Hi,
Sorry for the late response, this somehow slipped under my radar.
If you ran the sequential mode you should have one project per sample, created in the directory in which you ran SqueezeMeta. The directory for each project will be named after its sample.
So you can combine those by running

```combine-sqm-table.py /path/to/dir/sample1 /path/to/dir/sample2 -o output_dir```

And then you can load that in R with

```
library(SQMtools)
SQM = loadSQMlite("/path/to/output_dir")
```

Does that work for you?
