### ISSUE TITLE
Restarting assembly with spades from vertain kmer

### ISSUE THREAD

**Issue by mradz19** [jtamames/SqueezeMeta#347]
Is is possible to restart an assembly with rnaspades using the --continue option that spades can run? The time I allocated wasn't enough to complete my assembly and it stopped on the last -k number. Rather than restarting the entire assembly with restart.pl, I was hoping to continue the assembly from the kmer it was up to.

Is this possible? I could I run into downstream issues with the pipeline?

**Comment by jtamames** [comment]
Hello
The easiest way would be: Finish the assembly externally as you say (using the continue option). Then start a new Squeezemeta run providing the assemby with the -extassembly option.
Best,
J
