### ISSUE TITLE
Rescaling tpm

### ISSUE THREAD

**Issue by mradz19** [jtamames/SqueezeMeta#348]
If I am subsetting my data by taxonomy (bacteria) should I be rescaling the tpm data or leaving it?

**Comment by mradz19** [comment]
Also I have another question. This is my current workflow for bacterial analyis:

```
bacteria=subsetTax(DFI, rank='superkingdom', tax='bacteria', rescale_tpm=T, ignore_unclassified_functions=T)
kegg=bacteria$functions$kegg$abund
```

I then use the kegg abundance table as count data for DEG analysis with edgeR. However what I am finding is a lot of the enriched genes in my infection group are human. For example, the most enriched gene is K12567 which is TTN and functions in cardiomyopathy. Am I doing something wrong which is causing non bacterial annotations to be retained in the kegg functions after I have subset for bacteria?

**Comment by fpusan** [comment]
1) It depends on what you want it to represent. If you rescale it, it will represent the features per kilobase per million reads of bacteria. You have more information here (https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-020-03703-2)
2) No, you are not doing anywthing wrong. It's hard to tell without having the data, but it looks like K12567 was the best match for that protein in the KEGG database, even if its homologous in the nr database were from bacteria. I would get the proteins annotated with K12567 and take a better look into them (their COG/PFAM annotations, and maybe some manual blast to see what the best hits are).

**Comment by mradz19** [comment]
How do I do that for step 2?

I've tried this:

```
orf = bacteria$orfs$table[bacteria$orfs$table$`KEGG ID` == 'K12567', 1:15]
sequence=bacteria$orfs$seqs[rownames(orf)]
sequence
named character(0)
```

But it isn't returning anything

**Comment by fpusan** [comment]
subsetFun(bacteria, "K12567")

**Comment by mradz19** [comment]
Thanks for that I'll give it a go.

Also is the squeezemeta output compatible with programs to look at differences in taxa abundance? For example test like anova, permanova etc

**Comment by mradz19** [comment]
For example I noticed this in the R tutorial:

```
library('vegan')
metadata = as.data.frame(c(rep('Hadza', 8), rep('Italy', 8)))
rownames(metadata) = colnames(Hadza$functions$KEGG$tpm)
colnames(metadata) = 'condition'
# Tranpose the matrix to have samples in rows.
kegg_tpm = t(Hadza$functions$KEGG$tpm)
country = c(rep('Hadza', 8), rep('Italy', 8))
adonis(kegg_tpm~country)
Call :
    adonis (formula = kegg_tpm ~ country)
    Permutation : free
    Number of permutation: 999
    Terms added sequentially (first to last)
              Df SumsOfSqs  MeanSqs F.Model  R2      Pr(>F)
country       1  0.034942   0.034942 7.9894 0.36333 0.001 ***
Residuals     14 0.061231   0.004374        0.63667
Total         15 0.096173                   1.00000
---
Signif. codes:
0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
```

But I was wondering can you use TPM as input for the vegan adonis test? Or would you need a distance matrix?

**Comment by fpusan** [comment]
As per the adonis [documentation](https://www.rdocumentation.org/packages/vegan/versions/2.4-2/topics/adonis):

> Formula: Model formula. The LHS must be either a community data matrix or a dissimilarity matrix, e.g., from vegdist or dist. If the LHS is a data matrix, function vegdist will be used to find the dissimilarities. The RHS defines the independent variables. These can be continuous variables or factors, they can be transformed within the formula, and they can have interactions as in a typical formula. If a dissimilarity object is supplied, no species coefficients can be calculated in adonis (see Value below).

As you saw in the example you pasted above, it's quite easy to use the results exposed by SQMtools with other R packages in order to perform advanced plotting, statistical tests or other custom analyses. However, also note that, while we provide some (hopefully correct!) examples in our wiki, we do not claim that those are the best possible way to analyze your data (statistics are hard, and there are people with far more experience than us). Questions regarding the correct usage of other R packages should be directed to their developers.

**Comment by jtamames** [comment]
> I then use the kegg abundance table as count data for DEG analysis with edgeR. However what I am finding is a lot of the enriched genes in my infection group are human. For example, the most enriched gene is K12567 which is TTN and functions in cardiomyopathy. Am I doing something wrong which is causing non bacterial annotations to be retained in the kegg functions after I have subset for bacteria?

You can also take a look at the annotions for that KEGG in the 13*orftable. Simply grep "K12567". Check if the annotations have a "*" sign at the end. If not, it means that the annotation is not that reliable because there are other homologous KEGG familes.

**Comment by mradz19** [comment]
Ahh OK, so if I wanted to run tests on the taxonomic output from squeezemeta. Would I use the abundance or percentage output? And if it is the abundance would I normalise it to logCPM or something similar?

Im not super familiar with vegan but as far as I know there is normally a rarefy/normalising step to count data isn't there?

**Comment by fpusan** [comment]
Depending on the test you might want to use abundances or percentages. Some vegan functions will try to normalize for you (I find metaMDS reasonably safe to use because of this). However I strongly recommend that you read carefully vegan's own guides and go through their examples.

**Comment by mradz19** [comment]
Just following up to the original issue. I managed to subset for k12567. I looked at the seqs in orfs$seqs and found 2. I did a manual blastp of both of them and neither matched with any bacteria, both seqs primarily matched with primates. 

How could it have picked out that function as bacterial when subsetting? There appears to be several like that and it sort of makes the analysis moot if a large amount of the annotations when looked at individually end up being form eukaryotes.

**Comment by jtamames** [comment]
Hello
First, be sure that they are classified as Bacterial in the results, to exclude possible mistakes in the subsetting. Just grep the names of the sequences in the 13*orftable file. If they are indded bacterial, you can find the hits used for the annotation in the 04*diamond file in the intermediate directory. Also grep the names in that file. Please send the result to me, together with the sequences for these genes (in the 03*faa file).
I am currently on vacation but I will check it as soon as I can.
Best,
Javier

**Comment by mradz19** [comment]
Sorry I'm not very good with grep. How would I do it?

**Comment by jtamames** [comment]
Suppose the name of your sequence is "test_seq". Just type `grep "test_seq" 13.project.orfname`, replacing project with your project name.

**Comment by mradz19** [comment]
[13.grep.txt](https://github.com/jtamames/SqueezeMeta/files/7029861/13.grep.txt)
[04.grep.txt](https://github.com/jtamames/SqueezeMeta/files/7029862/04.grep.txt)
[03.grep.txt](https://github.com/jtamames/SqueezeMeta/files/7029864/03.grep.txt)

I've attached the files for one of the sequences

**Comment by jtamames** [comment]
Ok, as you see in the 13 file, this one is classified as eukaryotic, and therefore it should not be present in your bacterial subset. Are you sure you are subsetting correctly?

**Comment by mradz19** [comment]
[04.grep_2.txt](https://github.com/jtamames/SqueezeMeta/files/7029900/04.grep_2.txt)
[03.grep_2.txt](https://github.com/jtamames/SqueezeMeta/files/7029901/03.grep_2.txt)
[13.grep_2.txt](https://github.com/jtamames/SqueezeMeta/files/7029902/13.grep_2.txt)
These are the files for the second sequence for that annotation.

This is how I did it:
```
bacteria=subsetTax(DFI, rank='superkingdom', tax='bacteria', rescale_tpm=T, ignore_unclassified_functions=T)
kegg=bacteria$functions$kegg$abund
```

**Comment by jtamames** [comment]
Same thing, eukaryotic. So the problem is not in the annotation but in the subsetting

**Comment by mradz19** [comment]
Is there anything wrong with the script I used?

**Comment by fpusan** [comment]
Your code looks fine to me. How did you look for the actual ORFs afterwards?

**Comment by mradz19** [comment]
I just extracted the kegg annotations as above and used that DEG analysis using edgeR

**Comment by fpusan** [comment]
Any chance you can share your project with us via wetransfer or something similar?

**Comment by mradz19** [comment]
Sure I have an rds file I can send. It's the output of loadSQM just before I subsetTax for bacteria.

Here is the link:

https://we.tl/t-5bjAFb4fpM

**Comment by fpusan** [comment]
Now I see what's happening.
```
SQM=readRDS("spades_2.rds")
x=subsetFun(SQM, "K12567")
plotTaxonomy(x, 'superkingdom') # All eukaryotes
b=subsetTax(SQM, "superkingdom", "Bacteria")
'K12567' %in% rownames(b$functions$KEGG$abund) # TRUE, K12567 was included when subsetting bacteria
# Which are the offending genes?
rownames(b$orfs$table)[grepl('K12567',b$orfs$table$`KEGG ID`)] 
# They are "rnaspades_115233_2059-2148" "rnaspades_560434_301-582"

# Which other genes appear in the same contig as "rnaspades_115233_2059" and what is their taxonomy?

b$orfs$table[b$orfs$table$`Contig ID` == 'rnaspades_115233', 'Tax', drop=F]
# rnaspades_115233_3-647    k_Bacteria;p_Proteobacteria;c_Gammaproteobacteria;o_Pasteurellales;f_Pasteurellaceae;g_Haemophilus
# rnaspades_115233_944-1315    k_Bacteria;p_Proteobacteria;c_Gammaproteobacteria;o_Pasteurellales;f_Pasteurellaceae
# rnaspades_115233_1367-1858    k_Bacteria;p_Proteobacteria;c_Gammaproteobacteria;o_Pasteurellales;f_Pasteurellaceae
# rnaspades_115233_2059-2148    k_Eukaryota;n_Opisthokonta;n_Metazoa;n_Eumetazoa;n_Bilateria;n_Deuterostomia;p_Chordata;n_Craniata;n_Vertebrata;n_Gnathostomata;n_Teleostomi;n_Euteleostomi;superc_Sarcopterygii;n_Dipnotetrapodomorpha;n_Tetrapoda;n_Amniota;n_Mammalia

b$orfs$table[b$orfs$table$`Contig ID` == 'rnaspades_560434', 'Tax',drop=F]
# rnaspades_560434_2-64    k_Bacteria;n_Terrabacteria group;p_Firmicutes;c_Bacilli;o_Bacillales;f_Staphylococcaceae;g_Staphylococcus;s_Staphylococcus pseudintermedius
# rnaspades_560434_301-582    k_Eukaryota;n_Opisthokonta;n_Metazoa;n_Eumetazoa;n_Bilateria;n_Deuterostomia;p_Chordata;n_Craniata;n_Vertebrata;n_Gnathostomata;n_Teleostomi;n_Euteleostomi;superc_Sarcopterygii;n_Dipnotetrapodomorpha;n_Tetrapoda;n_Amniota;n_Mammalia
```

So what is happening here is that SqueezeMeta reports the taxonomy at the contig level, running a Last Common Ancestor algorithm over the taxonomy of the ORFs in order to find a consensus taxonomy for each contig. So in the first case the first three proteins of the contig are clearly bacterial (I checked manually) while the last one looks eukaryotic (a perfect, but very short hit). Since bacteria clearly outweights eukaryotes, SqueezeMeta determines that the whole contig is of bacterial origin, so it gets selected when you run the subset. In the second case you are getting again a mixed annotations in the contig, but in this case it is the bacterial sequence is very short.

So why are eukaryotic and bacterial ORFs coexisting in the same contig? Hard to tell, it might be an assembly/annotation problem or something with an actual biological meaning. In the second case, I'd actually suspect that prodigal and/or DIAMOND are to blame, but the first one looks "cleaner" to me.

In any case, the actual effect of this problem is minimal. If I do the plotting on the bacterial subset using the per-ORF taxonomy instead of the contig taxonomy
```
b2 = subsetORFs(SQM, rownames(b$orfs$table), tax_source='orfs')
plotTaxonomy(b2, "superkingdom")
```
![imagen](https://user-images.githubusercontent.com/8419198/130438529-1de70b38-eeb4-4c15-b6bf-fe556aa352fe.png)
it can be seen that the problem affects a very small fraction of the reads, and only in a few samples.

We can maybe tweak our LCA algorithm so it disregards hits below a certain length threshold (though choosing that threshold is another problem on its own). Nonetheless, you can easily get rid of the offending ORFs the following way.

```
SQM=readRDS("spades_2.rds")
b = subsetTax(SQM, "superkingdom", "Bacteria")
goodORFs = rownames(b$orfs$tax)[b$orfs$tax[,'superkingdom']=='Bacteria']
b.good = subsetORFs(b, goodORFs, tax_source='orfs')
'K12567' %in% rownames(b.good$functions$KEGG$abund) # FALSE, the offending ORFs are no longer here
```

**Comment by mradz19** [comment]
That's great thank you for the work around! I will redo my analysis and see how it looks

**Comment by mradz19** [comment]
I'm having a look at the data now. The main ones I mentioned previously are no longer present, however I am still finding a few non bacterial genes, for example K19020 and K13098

**Comment by fpusan** [comment]
If you look e.g. at K13098 you find "rnaspades_587712_168-413" which when blasting it looks like a perfect hit to a bacteroidetes proteins. So in that case the annotations is likely wrong (and actually when looking at the ORF table you'll find that it does not have the asterisk that denotes a trusted annotation).

You can add `trusted_functions_only=T` when subsetting to try to discard those. It will get rid of some (likely not all) of the remaining problematic ORFs. In the end, it's hard to obtain perfect annotations in all cases, so it's important that you keep checking the results for inconsistencies.

**Comment by mradz19** [comment]
OK thank you for your help with this. I will close the issue.
