### ISSUE TITLE
Total number of reads listed in mappingstatfile does not match number of input reads

### ISSUE THREAD

**Issue by jilldv** [jtamames/SqueezeMeta#349]
Hello,

When looking at the mappingstat file I noticed that the number of total reads listed does not match the number of input reads (checked with fastqc). For example, with fastqc I get total number of sequences 65017740. But in the mappingstat file the total number of reads are 65116842. Any ideas on why the number of reads does not match or am I misinterpreting something?

Some details about my run:
Data quality trimming was done with trimmomatic. The paired output files of trimmomatic were then used as input for squeezemeta (coassembly mode with spades assembler and bwa mapper)

Attached you can find the syslog file, mappingstat file and the fastqc report
[run_info.zip](https://github.com/jtamames/SqueezeMeta/files/7006612/run_info.zip)

Thank you!

**Comment by jtamames** [comment]
Hello!
Could you download the script `10.mapsamples.pl` from the current version (1.4.0) and run it again? Just calling it with the project name (arctic) will suffice. Then check the mappingstat file and see if it changed.
Best,
Javier

**Comment by jilldv** [comment]
Thank you for the quick reply!
I ran the script from the current version but unfortunately the mappingstat file did not change
[10.arctic.mappingstat.txt](https://github.com/jtamames/SqueezeMeta/files/7007467/10.arctic.mappingstat.txt)

**Comment by jtamames** [comment]
Ok, I am running a test myself using BWA to look for possible inconsistencies. I will let you know

Best,
Javier

**Comment by jtamames** [comment]
Hello again
BWA's manual says this:

> The BWA-MEM algorithm performs local alignment. It may produce multiple primary alignments for different part of a query sequence. This is a crucial feature for long sequences.

This is the reason for that inflated number of reads. Some reads are mapping to more than one location and are being counted twice. No easy solution for this. Luckily the difference is small (0.15% in your example) and I wouldn't expect it to bias the results very much. I am marking this as a know issue and will try to find the best way to deal with it.
Thanks a lot for the warning!
Best,
Javier

**Comment by jilldv** [comment]
Ok, now I understand. Thank you for looking into this!
