### ISSUE TITLE
Continue assembly merging

### ISSUE THREAD

**Issue by oyac** [jtamames/SqueezeMeta#351]
Hello,

I`ve been using SqueezeMeta in seqmerge mode for my samples (~70), and the individual assemblies finished, but while merging the assemblies, my pc may lose connection to the server  and stop it (which happened once). If I restart the process from step 1.5, it will restart from the beginning again. Is there any way to make it continue from where it stopped? I asked before for the individual assemblies, but now it is about the merging of the assemblies.

Thanks

**Comment by jtamames** [comment]
Hello
You can try moving the assemblies that were already merged, and restarting. In that way it will skip the ones that were already merged. Check a file called `mergelog` in the temp directory. That keeps track of the files already merged, but it is removed when restarting, so if you tried restarting you won't be able to find it. In that case, you can use the `syslog` file. Move the assemblies that were already merged to a different directory, and then restart or run `01.merge_sequential.pl`

Let me know if it works
Best,
Javier

**Comment by oyac** [comment]
Dear Javier, 

I am sorry it took too long to answer. Thanks, it is working. I moved the archives, and now I am running 01.merge_sequential.pl. Then, when it finishes, what should I do? Move back the 1st archives to the intermediate and rename them?
Thanks again,

**Comment by jtamames** [comment]
Hello
Glad to hear it is working. No need to do anything else with the original assemblies. At the end, you will have a 01.project.fasta file in the results directory, containing the final contigs. Just run restart.pl -step 2
Best,
Javier

**Comment by jtamames** [comment]
Hello!
You should have a `mergelog` file in the `temp` directory of your project, specifying the merger orger and the merged files. That info should be also in the `syslog` file. But I can tell you rigth away that if you have 69 samples but 27 merges, the procedure did not finish correctly. There should be the same number of merges than that of samples. Could you share your syslog file with me, please?
Best,
J

**Comment by oyac** [comment]
Yes, in a way. I removed the previous individual assemblies and restarted the process (but i did not move the merged archives).  Here is the mapping stat - still running.

[10.rice_meta_sq.mappingstat.zip](https://github.com/jtamames/SqueezeMeta/files/7390509/10.rice_meta_sq.mappingstat.zip)
Cheers,

**Comment by jtamames** [comment]
Low mapping percentages for all samples. If some samples have not been merged, I would expect unequal mappings, with samples left out mapping less reads. Let´s see when it finishes. 
Could you try to run just one of these samples in sequential mode? That will tell us how much mapping we should expect.
Best,
Javier
