### ISSUE TITLE
Problem with loading projects into SQMTools 

### ISSUE THREAD

**Issue by fweinberger** [jtamames/SqueezeMeta#354]
Having used SqueezeMeta on a remote cluster I now try to load two different projects into SQMTools on my local workstation. In the SqueezeMeta_conf.pl of both projects I have adapted the $installpath to the new location. Trying then to load the projects I receive the same error message: 
sqmtables.py: error: unrecognized arguments: /my_project_data_path/results/tables
Do you have any suggestions how to handle this? Do I need to adapt additional path definitions in one of the scripts? I did not install the SqueezeMeta database on my workstation because I suppose it's not needed by SQMTools - can this have created the error?
Any help would be most appreciated!
Florian

**Comment by fpusan** [comment]
Hi!
Please run `sqm2tables.py /path/to/your/project /path/to/your/project/results/tables` in your remote cluster.
You can also do it in your local workstation provided you install SqueezeMeta there (no need for the databases, just the conda environment).
In any case, the project should load in SQMtools after you run sqm2tables.
Let me know if this works for you.

**Comment by lmurray09185** [comment]
I am also having issues with loading my project using loadSQM. I receive the error message: Error in loadSQM("/home/Downloads/Castle") : Directory "/home/Downloads/Castle" does not seem to contain a valid SqueezeMeta project
This directory is the output of SqueezeMeta.pl -sequential mode so I'm not sure why it is not a valid SqueezeMeta project. Any help would be appreciated! 
Laura

**Comment by fpusan** [comment]
Hi!
If you ran the sequential mode you should have one project per sample, created in the directory in which you ran SqueezeMeta. The directory for each project will be named after its sample.

So you should do e.g.
```
library(SQMtools)
p1 = loadSQM('/path/to/project1/')
p2 = loadSQM('/path/ro/project2')

combi = combineSQMlite(p1,p2) # If you want combined functional and taxonomy tables
```

**Comment by fweinberger** [comment]
Hi, 
Thank you for the superfast support! It works now!

**Comment by fpusan** [comment]
No problem!
I'll make a note to try to improve the documentation when using the sequential mode, maybe it's not so clear.
Closing issue
