### ISSUE TITLE
 STEP4 -> 04.rundiamond.pl. Program finished abnormally

### ISSUE THREAD

**Issue by dorton21** [jtamames/SqueezeMeta#355]
Currently running into " STEP4 -> 04.rundiamond.pl. Program finished abnormally" during the testing phase.
I am attempting to put SqueezeMeta into a singularity container where execution is done like `singularity exec --bind /scratch/ squeezemeta.img SqueezeMeta.pl -m coassembly -p Hadza -s /scratch/squeezedb/test/test.samples -f /scratch/squeezedb/test/raw/`

I don't believe I can run the `configure_nodb_alt.pl` due to how I am setting up squeezemeta so I added the following to try and replicate its effects in the container:
`# Replacing Squeezemeta's default db installation location`
`wget -U '' -P $SQUEEZEMETAPATH/lib http://silvani.cnb.csic.es/SqueezeMeta/classifier.tar.gz`
`tar xvzf $SQUEEZEMETAPATH/lib/classifier.tar.gz -C $SQUEEZEMETAPATH`
`rm $SQUEEZEMETAPATH/lib/classifier.tar.gz`
`cd $SQUEEZEMETAPATH/bin/`
`ln -s $SQUEEZEMETAPATH/classifier/classifier.jar . > /dev/null 2>&1`
`cd /`
`sed 's/\/media\/disk5\/tamames\/SqueezeMeta\/db/\/scratch\/squeezedb\/db/g' $SQUEEZEMETAPATH/scripts/SqueezeMeta_conf_original.pl > $SQUEEZEMETAPATH/scripts/SqueezeMeta_conf.pl
`
The reason for the scratch binding is the DB is stored in a position other than the default file path (I believe it was downloaded via `/path/to/SqueezeMeta/utils/install_utils/preparing_databases/download_databases.pl /download/path`) I have the DB preinstalled into /scratch/squeezedb/ when I run `<installpath>/SqueezeMeta/utils/install_utils/test_install.pl` I get the error _SqueezeMeta_conf.pl says that databases are located in /scratch/squeezedb/db but we can't find nr.db there, or it is corrupted_

**Comment by dorton21** [comment]
`nr.db` doesn't appear to exist at all. I thought maybe an easy fix would be to delete the db I had downloaded and reinstall it. But the new install didn't include nr.db either. I don't know if it is something that comes with the db installation or if it is something generated via some script I need to call.

**Comment by fpusan** [comment]
Now I realize...
Did you actually download the database at all? (i.e. run `download_databases.pl`?)
`configure_nodb.pl` would write the necessary configuration files, but you still need to have the database downloaded.

**Comment by dorton21** [comment]
I ran download_databases.pl outside of the container in order to separately download the DB.

**Comment by dorton21** [comment]
I see there is a nr.dmnd that is generated. Is this file supposed to be mutated into the nr.db somehow?

**Comment by fpusan** [comment]
Yes, sorry, `nr.dmnd` is the correct one. Where is it located?

**Comment by dorton21** [comment]
`nr.dmnd` is inside the path `/scratch/squeezedb/db`

**Comment by fpusan** [comment]
What happens if you run `/path/to/SqueezeMeta/bin/diamond dbinfo --db /scratch/squeezedb/db/nr.dmnd`?

**Comment by dorton21** [comment]
That returns the following:

diamond v2.0.8.146 (C) Max Planck Society for the Advancement of Science
Documentation, support and updates available at http://www.diamondsearch.org

Database type  Diamond database
Database format version  3
          Diamond build  146
              Sequences  371327556
                Letters  134857927905

**Comment by fpusan** [comment]
Ok, so the database is there and fine.
And what output do you get from `/path/to/SqueezeMeta/utils/install_utils/test_install.pl`?

**Comment by dorton21** [comment]
Running that command gives `SqueezeMeta_conf.pl says that databases are located in /scratch/squeezedb/db but we can't find nr.db there, or it is corrupted`. Like I said before, that file is not there. I don't know if it needs to be generated or what the deal is. I do, however, have the nr.dmnd file.

**Comment by fpusan** [comment]
The `nr.db` part is a typo in the error message (hadn't noticed before, will patch it). It's really looking for `nr.dmnd` which is there, right?
The script is internally running `/path/to/SqueezeMeta/bin/diamond dbinfo --db /scratch/squeezedb/db/nr.dmnd` and complaining if the command fails.

So I'm surprised that it worked when you ran it manually before, but `test_install.pl` is not working...

1) What shell interpreter are you using?
2) Can you manually edit `/path/to/SqueezeMeta/utils/install_utils/test_install.pl`?
- In L129: `my $ecode = system("$installpath/bin/diamond dbinfo --db $databasepath/nr.dmnd >/dev/null 2>&1");`
- change it to `my $ecode = system("$installpath/bin/diamond dbinfo --db $databasepath/nr.dmnd");`
And see what's the output then...

**Comment by dorton21** [comment]
Yes, nr.dmnd is in the proper location. For some more perspective. I'm trying to build this in a singularity container using a centos8 image. I can probably use sed to make the modifications you specified and I'll report back the results. Thank you for the continued help.

**Comment by fpusan** [comment]
Also let me know what is your shell interpreter? You can check with
`echo $0`
and 
`echo $SHELL`

**Comment by dorton21** [comment]
Bash is the shell interpreter. 

Running Diamond (Buchfink et al 2015, Nat Methods 12, 59-60) for taxaError running command:    /opt/conda/envs/SqueezeMeta-2020.11/SqueezeMeta/bin/diamond blastp -q /home/las_djorton/singularity-squeezemeta/Hadza/results/03.Hadza.faa -p 12 -d /scratch/squeezedb/db/nr.dmnd -e 0.001 --id 40 -f tab -b 2.7 --quiet -o /home/las_djorton/singularity-squeezemeta/Hadza/intermediate/04.Hadza.nr.diamond at /opt/conda/envs/SqueezeMeta-2020.11/SqueezeMeta/scripts/04.rundiamond.pl line 66.
Stopping in STEP4 -> 04.rundiamond.pl. Program finished abnormally

  If you don't know what went wrong or want further advice, please look for similar issues in https://github.com/jtamames/SqueezeMeta/issues
  Feel free to open a new issue if you don't find the answer there. Please add a brief description of the problem and upload the /home/las_djorton/singularity-squeezemeta/Hadza/syslog file (zip it first)
Died at /opt/conda/envs/SqueezeMeta-2020.11/bin/SqueezeMeta.pl line 1367.

**Comment by dorton21** [comment]
The above is the new error message after an attempt to make the changes you suggested.

**Comment by fpusan** [comment]
But that output is for running SqueezeMeta, and the changes were made in `test_install.pl`, right?
What is the output of `test_install.pl` after the changes?

**Comment by dorton21** [comment]
Alright. I did some messing around. It can detect nr.db now but I have landed on a new error.

Checking that SqueezeMeta is properly configured... checking database in /scratch/squeezedb/db
        nr.db OK

CRITICAL ERROR: Can not find the checkm DATA_CONFIG file in /opt/conda/envs/SqueezeMeta-2020.11/SqueezeMeta/lib/checkm. This indicates a broken installation. If the error persists after reinstalling from scratch please open an issue at http://github.com/jtamames/SqueezeMeta

**Comment by fpusan** [comment]
Hi again! Sorry for the delay, I was on a much needed holiday break.
That one comes from not running `configure_nodb.pl`but is easy to fix.
Manually create the `/opt/conda/envs/SqueezeMeta-2020.11/SqueezeMeta/lib/checkm/DATA_CONFIG` file, with the following content
```
{"dataRoot": "/scratch/squeezedb/db/", "remoteManifestURL": "https://data.ace.uq.edu.au/public/CheckM_databases/", "manifestType": "CheckM", "localManifestName": ".dmanifest", "remoteManifestName": ".dmanifest"}
```
In general, `"dataRoot"` should point to wherever you have the SqueezeMeta databases installed (I copied that path from your previous answers, but double-check just in case)

**Comment by dorton21** [comment]
`Singularity local:~> /opt/conda/envs/SqueezeMeta-2020.11/SqueezeMeta/bin/diamond blastp -q /root/HadzaTest/results/03.HadzaTest.faa -p 12 -d /scratch/squeezedb/db/nr.dmnd -e 0.001 --id 40 -f tab -b 2.6 --quiet -o /root/HadzaTest/intermediate/04.HadzaTest.nr.diamond`
Responds with...
`Killed`

No other errors.

**Comment by dorton21** [comment]
`srun --time=12:00:00 --nodes=4 --cpus-per-task=8 --mem=32G --pty /usr/bin/bash` this is what I am booking to run this. I think the exact error message is `Died at /opt/conda/envs/SqueezeMeta-2020.11/bin/SqueezeMeta.pl line 1367.`

**Comment by dorton21** [comment]
[1 hours, 27 minutes, 53 seconds]: STEP4 -> HOMOLOGY SEARCHES: 04.rundiamond.pl
  Setting block size for Diamond
  AVAILABLE (free) RAM memory: 364.98 Gb
  We will set Diamond block size to 8 (Gb RAM/5, Max 8).
  You can override this setting using the -b option when starting the project, or changing
  the $blocksize variable in SqueezeMeta_conf.pl
  Running Diamond (Buchfink et al 2015, Nat Methods 12, 59-60) for taxaError running command:    /opt/conda/envs/SqueezeMeta-2020.11/SqueezeMeta/bin/diamond blastp -q /work/las-research/students/las_djorton/Hadza/results/03.Hadza.faa -p 12 -d /work/LAS/BioDatabase/squeezedb/db/nr.dmnd -e 0.001 --id 40 -f tab -b 8 --quiet -o /work/las-research/students/las_djorton/Hadza/intermediate/04.Hadza.nr.diamond at /opt/conda/envs/SqueezeMeta-2020.11/SqueezeMeta/scripts/04.rundiamond.pl line 66.
Stopping in STEP4 -> 04.rundiamond.pl. Program finished abnormally

  If you don't know what went wrong or want further advice, please look for similar issues in https://github.com/jtamames/SqueezeMeta/issues
  Feel free to open a new issue if you don't find the answer there. Please add a brief description of the problem and upload the /work/las-research/students/las_djorton/Hadza/syslog file (zip it first)
Died at /opt/conda/envs/SqueezeMeta-2020.11/bin/SqueezeMeta.pl line 1367.

**Comment by fpusan** [comment]
Ok, here's what I think it's happening.
1) You book 32Gb of memory
2) SqueezeMeta, when running in the computing node, has no way of knowing that. It looks at the system and sees that there are 364.98 Gb free (the whole amount of memory free in the node at the time). It thus sets diamond blocksize to 8, which is expected to use 40 Gb of memory.
3) When the process exceeds 32 Gb usage, it gets killed by slurm.

So I think that the answer might be setting up -b manually. Can you add `-b 1.5` in the initial call to SqueezeMeta? Also make sure to keep requesting those 32Gb (or ideally more).

**Comment by dorton21** [comment]
[10 hours, 32 minutes, 4 seconds]: STEP18 -> 18.checkM_batch.pl
PATH=/opt/conda/envs/SqueezeMeta-2020.11/SqueezeMeta/bin:/opt/conda/envs/SqueezeMeta-2020.11/SqueezeMeta/bin/pplacer:/opt/conda/envs/SqueezeMeta-2020.11/SqueezeMeta/bin/hmmer:$PATH /opt/conda/envs/SqueezeMeta-2020.11/SqueezeMeta/bin/checkm taxon_set phylum Elusimicrobia /work/las-research/students/las_djorton/Hadza/data/checkm_markers/Elusimicrobia.ms >> /work/las-research/students/las_djorton/Hadza/syslog 2>&1

*******************************************************************************
 [CheckM - taxon_set] Generate taxonomic-specific marker set.
*******************************************************************************

It seems that the CheckM data folder has not been set yet or has been removed. Running: 'checkm data setRoot'.
You do not seem to have permission to edit the checkm config file
located at /opt/conda/envs/SqueezeMeta-2020.11/SqueezeMeta/lib/checkm/DATA_CONFIG
Please try again with updated privileges. Error was:

[Errno 30] Read-only file system: '/opt/conda/envs/SqueezeMeta-2020.11/SqueezeMeta/lib/checkm/DATA_CONFIG'
Sorry, CheckM cannot run without a valid data folder.

Unexpected error: <class 'FileNotFoundError'>
Traceback (most recent call last):
  File "/opt/conda/envs/SqueezeMeta-2020.11/SqueezeMeta/bin/checkm", line 718, in <module>
    checkmParser.parseOptions(args)
  File "/opt/conda/envs/SqueezeMeta-2020.11/SqueezeMeta/bin/../lib/checkm/main.py", line 1239, in parseOptions
    self.taxonSet(options)
  File "/opt/conda/envs/SqueezeMeta-2020.11/SqueezeMeta/bin/../lib/checkm/main.py", line 262, in taxonSet
    bValidSet = taxonParser.markerSet(options.rank, options.taxon, options.marker_file)
  File "/opt/conda/envs/SqueezeMeta-2020.11/SqueezeMeta/bin/../lib/checkm/taxonParser.py", line 82, in markerSet
    taxonMarkerSets = self.readMarkerSets()
  File "/opt/conda/envs/SqueezeMeta-2020.11/SqueezeMeta/bin/../lib/checkm/taxonParser.py", line 40, in readMarkerSets
    for line in open(DefaultValues.TAXON_MARKER_SETS):
FileNotFoundError: [Errno 2] No such file or directory: 'taxon_marker_sets.tsv'
Stopping in STEP18 -> 18.checkM_batch.pl. Program finished abnormally


The latest in this series of issues. Thank you for your continued support with this.

**Comment by fpusan** [comment]
Moved the answer to the last question to a different issue, as it is no longer related to STEP4.
However, I am curious to what was causing the problem in step 4, as it seems that it worked ok for you in the end...

**Comment by dorton21** [comment]
You were correct in you suspicion that I wasn't booking enough memory. Once again thank you for your continued support.

**Comment by fpusan** [comment]
Ok, glad it worked! Closing issue
