### ISSUE TITLE
Issue loading sequential samples into R with loadSQM

### ISSUE THREAD

**Issue by lmurray09185** [jtamames/SqueezeMeta#358]
Hi there, 

I am attempting to load my sequentially run samples into R using the loadSQM command. When I do, I recieve this error: 
Loading orfs
    table...
    abundances...
    sequences
    taxonomy...
Loading contigs
    table...
    abundances...
    sequences...
    taxonomy...
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/home/lmurray/Castle/results/tables/Castle.contig.tax.tsv': No such file or directory
Before loading the samples I ran the sqm2tables.py script and had no issues. After looking in the table directory, there are three files that are .contig.tax.tsv files: Castle.contig.tax.allfilter.tsv, Castle.contig.tax.nofilter.tsv, or Castle.conti.tax.prokfilter.tsv. Which of these files is correct? Should I rename one of these files to castle.contig.tax.tsv? 

Thank you! 
Laura

**Comment by fpusan** [comment]
Hi!
I'd say that you don't have the latest version of SQMtools installed... is that the case?

**Comment by lmurray09185** [comment]
It looks like I have version 0.4.5 installed. I tried compressing the latest SQMtools directory into .tar.gz but when trying to install the package in R I recieved an error: 

install.packages("~/SQMtools.tar.gz", repos = NULL, type = "source")
Installing package into ‘/home/lmurray/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
ERROR: cannot extract package from ‘/home/lmurray/SQMtools.tar.gz’
Warning in install.packages :
  installation of package ‘/home/lmurray/SQMtools.tar.gz’ had non-zero exit status

Thanks for your help!
Laura

**Comment by fpusan** [comment]
Is this the `SqueezeMeta/lib/SQMtools` directory compressed?
Can you try compressing it into the zip format instead?

**Comment by lmurray09185** [comment]
Yes, it is the SqueezeMeta/lib/SQMtools directory compressed. I also tried compressing into a zip format and that did not work either.

**Comment by fpusan** [comment]
Are you using normal R or RStudio?

**Comment by lmurray09185** [comment]
I am using R studio.

**Comment by fpusan** [comment]
Then there should be a menu somewhere for installing the package

**Comment by fpusan** [comment]
Maybe this helps
https://stackoverflow.com/questions/22279190/offline-installation-of-packages-in-rstudio

**Comment by lmurray09185** [comment]
When I try to install the package using the instructions in that link, it gives me the same error I received previously. Is there an updated compressed SQMtools you could send? Thank you so much for all of your help!

**Comment by fpusan** [comment]
Did you try "Tools>Install Packages > Select "Package Archive File" with the zip and the tar.gz files?

**Comment by fpusan** [comment]
or `install.packages("~/SQMtools.tar.gz", repos = NULL)` without the `type='source'`

**Comment by lmurray09185** [comment]
Yes, when I tried "Tools>Install Packages" I receive the error that the package cannot be extracted. When I tried the install.packages I get an error that this package is not available for this version of R (I am using R studio version 1.2.5033).

**Comment by fpusan** [comment]
So what's the output of typing `version` inside the R console?

**Comment by fpusan** [comment]
Also what's your OS?

**Comment by lmurray09185** [comment]
I am using Ubuntu Linux x86_64. Here is my version output: 

platform       x86_64-apple-darwin17.0     
arch           x86_64                      
os             darwin17.0                  
system         x86_64, darwin17.0          
status                                     
major          4                           
minor          0.3                         
year           2020                        
month          10                          
day            10                          
svn rev        79318                       
language       R                           
version.string R version 4.0.3 (2020-10-10)
nickname       Bunny-Wunnies Freak Out

**Comment by fpusan** [comment]
I see, SQMtools requires R version 3.6

**Comment by lmurray09185** [comment]
Got it, I'll try downgrading and see if that works. Thank you!

**Comment by fpusan** [comment]
Can you try the following before downgrading?
1) Clone the repo with `git clone http://github.com/jtamames/SqueezeMeta`
2) Try to install manually with `R CMD INSTALL SqueezeMeta/lib/SQMtools` and see if it complains. It might ask for missing dependencies, but you might be able to get them...

**Comment by lmurray09185** [comment]
When trying to clone the repo I am getting the following error:
Unable to locate package https://github.com/jtamames

**Comment by lmurray09185** [comment]
Actually, I got it to work! Thank you so much!

**Comment by fpusan** [comment]
So it's SQMtools installed for you now? can I close the issue?

**Comment by lmurray09185** [comment]
Yes, it is installed and you can close the issue. Thank you so much again for all of your help!

**Comment by fpusan** [comment]
Ok great! Have fun with the analyses

**Comment by yasiromics** [comment]
> 

But that's not the case I think. As I am doing it it says SQMtools is not available for R3.6

**Comment by fpusan** [comment]
Hi! Is this happening when inside our conda environment? We should provide all the required dependencies there, and the packages are definitely available...
