### ISSUE TITLE
Deleting some large files after a run 

### ISSUE THREAD

**Issue by ATVincent** [jtamames/SqueezeMeta#362]
Hello,

I have a SqueezeMeta run that just finished. Some large data has been generated. I am thinking for example of the sam files. Can these files be needed for further analysis, for example with SQMtools, or is it "safe" to delete them? 

Thank you !

Antony

**Comment by jtamames** [comment]
Hello Antony
You can delete them, they are no longer required. But, if you want to redo the analysis, then they will have to be recreated.
Best,
Javier

**Comment by ATVincent** [comment]
Thank you !

Antony
