### ISSUE TITLE
Not all samples are used for mapping

### ISSUE THREAD

**Issue by mirimarine** [jtamames/SqueezeMeta#366]
Hi all,
I ran into a problem in SqueezeMeta version 1.4.
I have a large dataset of 24 metagenomes and 12 metatranscriptomes which I would like to use in one project (coassembly mode with external assembly).
Once the run was finished (without any errors), I noticed that the TMP/Coverage/Count Data of 8 of the samples was missing in the results tables. I checked the data/raw_fastq directory and could find all the reads there, including the 8 samples that were missing in the results table. Yet, in the data/sam directory, the respective sam files of these 8 samples were missing.
In the samplesfile, the missing 8 samples were mentioned last.
So I was wondering, is there any limit on the number of samples/read files that SqueezeMeta accepts per project?
All the best and thank you for your help,
Miriam

**Comment by mirimarine** [comment]
Hi Javier,
thanks for the fast response. Disk space is not an issue on the server that I'm using. I also re-ran the analysis once, with the same result that 8 samples were not used for mapping.
I will try to run step 10 separately and see how this goes.
All the best,
Miriam

**Comment by jtamames** [comment]
Hi
Send me the syslog file, please
Best,
J

**Comment by mirimarine** [comment]
Hi Javier,
here is the syslog file.
Best,
Miriam
[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/7265570/syslog.zip)

**Comment by jtamames** [comment]
Ok, can you try to run bowtie externally, like this:
```
cp /scratch/mphilipp/Jan_Barbados/02_sqm/s3/data/raw_fastq/5146_L_R1_paired.fq.gz /scratch/mphilipp/Jan_Barbados/02_sqm/s3/temp/s3.M161_L.current_1.gz; cp /scratch/mphilipp/Jan_Barbados/02_sqm/s3/data/raw_fastq/5146_L_R2_paired.fq.gz /scratch/mphilipp/Jan_Barbados/02_sqm/s3/temp/s3.M161_L.current_2.gz;
/home/mphilipp/anaconda3/envs/SQM1.4/SqueezeMeta/bin/bowtie2/bowtie2 -x /scratch/mphilipp/Jan_Barbados/02_sqm/s3/data/s3.bowtie  -1 /scratch/mphilipp/Jan_Barbados/02_sqm/s3/temp/s3.M161_L.current_1.gz -2 /scratch/mphilipp/Jan_Barbados/02_sqm/s3/temp/s3.M161_L.current_2.gz --quiet -p 25 -S /scratch/mphilipp/Jan_Barbados/02_sqm/s3/data/sam/s3.M161_L.sam 
```

**Comment by fpusan** [comment]
Hi!
By looking at your syslog file, SqueezeMeta seems to think that you only have 28 samples.
```
Coppying files: cp /scratch/mphilipp/barbados_reads//5147_L_R2_paired.fq.gz /scratch/mphilipp/Jan_Barbados/02_sqm/s3/data/raw_fastq/5147_L_R2_paired.fq.gz
Samples:28
Mode:coassembly
Merging files for coassembly: cat /scratch/mphilipp/Jan_Barbados/02_sqm/s3/data/raw_fastq/5085_A_R1_trimmed_l.fastq.gz 
```
According to your first post, you expect to have 24 metagenomes and 12 metatranscriptomes  (so 36 samples).
Can you share your `samplesfile.txt` with us?

**Comment by mirimarine** [comment]
Hi, 
Since you suggested it, I had a quick look into the samples file again and I found a stupid mistake!
I'm very sorry, I don't know why I did not notice this before...
Thank you very much for your help!
Best,
Miriam
