### ISSUE TITLE
release dates of databases downloaded

### ISSUE THREAD

**Issue by chandnisidhu** [jtamames/SqueezeMeta#367]
Hi,

Is there any way to know about the release dates/versions of nr, eggNOG and KEGG databases downloaded with squeezemeta version 1.3.1 by download_databases.pl script?

Thank you in advance,

Chandni

**Comment by jtamames** [comment]
Hello

KEGG requires a licensing, so we are using the last public version released, which I think it was 58. If I remember correctly, that corresponds to 2011.
eggNOG is v5.0.
nr depends of if you created it using make_databases.pl (then it will be the last one), or you downloaded it with download_databases. Check the DB_BUILD_DATE file in the directory where you put the databases, and then find the appropriate release in https://www.ncbi.nlm.nih.gov/genbank/release/

Best,
Javier

**Comment by chandnisidhu** [comment]
Hi,

Thanks a lot for this information.

Best,
Chandni

**Comment by fpusan** [comment]
Just a correction here, we use eggNOG v4.5, not 5 (yet)
