### ISSUE TITLE
anvi-load-sqm.py issue with DAS collection

### ISSUE THREAD

**Issue by bresyd** [jtamames/SqueezeMeta#368]
Hi,

I was trying to load the DAS collection into anvio with anvi-load.sqm.py but it looks like there is an issue with the DAS collection.

```conda activate anvio-6.2
python3 ~/miniconda3/envs/SqueezeMeta_1.4.0/SqueezeMeta/utils/anvio_utils/anvi-load-sqm.py -p sqm_B_hybrid -o sqm_B_hybrid/results/anvio --num-threads 40 --min-contig-length 1000 --run-scg-taxonomy --run-HMMS |& tee anvi-load-sqm.log
sqm_B_hybrid/results/sqm2anvio does not exist
Creating sqm2anvio directory with all the input files for anvi'o
/bioinf/home/btschits/barbados/sqm_runs/sqm_B_hybrid/results/sqm2anvio
Preparing contigs database: loading contigs, genes, functions and taxonomy!
Contigs database is CONTIGS.db. Contigs and genes have been loaded
Running HMMS to detect SCGs
Functions have been loaded
Taxonomy has been loaded
Loading bam files
Loading DAS collection
There must be some problem with "anvi-import-collection sqm_B_hybrid/results/sqm2anvio/sqm_B_hybrid_anvio_bins.txt -c sqm_B_hybrid/results/anvio/CONTIGS.db -p sqm_B_hybrid/results/anvio/temp/PROFILE.db -C DAS --contigs-mode".
It's better to stop and check it
```

I thought I try using the anvio interactive mode anyway but it looks like there really is no DAS collection
```anvi-interactive -p /bioinf/home/btschits/barbados/sqm_runs/sqm_B_hybrid/results/anvio/temp/PROFILE.db -c /bioinf/home/btschits/barbados/sqm_runs/sqm_B_hybrid/results/anvio/CONTIGS.db -C DAS
Contigs DB ...................................: Initialized: /bioinf/home/btschits/barbados/sqm_runs/sqm_B_hybrid/results/anvio/CONTIGS.db (v. 14)
Splits taxonomy ..............................: Initiated for taxonomic level for "t_genus"                                            
Interactive mode .............................: collection


Config Error: DAS is not a valid collection name. See a list of available ones with '--list-
              collections' flag                                                             

```
But there definitely is a directory with the DAStool bins
```
sqm_B_hybrid/results/DAS/sqm_B_hybrid_DASTool_bins$ ls |head
total 1054943
drwxr-sr-x 2 btschits biogeo       328 Sep 30 15:45 .
drwxr-sr-x 3 btschits biogeo        19 Sep 30 15:43 ..
-rw-r--r-- 1 btschits biogeo   1952501 Sep 30 15:44 26.fa_sub.contigs.fa
-rw-r--r-- 1 btschits biogeo     38827 Sep 30 15:45 26.fa_sub.contigs.fa.tax
-rw-r--r-- 1 btschits biogeo   2491672 Sep 30 15:44 36.fa_sub.contigs.fa
-rw-r--r-- 1 btschits biogeo     38487 Sep 30 15:45 36.fa_sub.contigs.fa.tax
-rw-r--r-- 1 btschits biogeo   1437662 Sep 30 15:44 81.fa.contigs.fa
-rw-r--r-- 1 btschits biogeo     34972 Sep 30 15:45 81.fa.contigs.fa.tax
-rw-r--r-- 1 btschits biogeo    378861 Sep 30 15:44 121.fa_sub.contigs.fa

```

Do you maybe have an idea about what is going wrong here?

Thanks a lot for your help

**Comment by bresyd** [comment]
Hi,

thanks for your reply.

The file sqm_B_hybrid_anvio_bins.txt is not empty
```
head sqm_B_hybrid_anvio_bins.txt 
megahit_197	metabat2_283_fa_sub_contigs
megahit_702	metabat2_283_fa_sub_contigs
megahit_921	metabat2_283_fa_sub_contigs
megahit_992	metabat2_283_fa_sub_contigs
megahit_1021	metabat2_283_fa_sub_contigs
megahit_1096	metabat2_283_fa_sub_contigs
megahit_1173	metabat2_283_fa_sub_contigs
megahit_1194	metabat2_283_fa_sub_contigs
megahit_1274	metabat2_283_fa_sub_contigs
megahit_1385	metabat2_283_fa_sub_contigs

```
I am using anvio version 6.2 (installed via conda) and SqueezeMeta 1.4.
I have previously successfully loaded the results of SQM runs into anvio with the same anvio, but different SqueezeMeta versions. I could try running anvi-load-sqm.py again but using the script from an older SqueezeMeta installation.

cheers

**Comment by ggnatalia** [comment]
Ok! Thanks, it is true that is not empty, so it should have  worked. I'll try your versions.
Nevertheless, the bins names are not the same in your *sqm_B_hybrid_anvio_bins* that you have within your folder *results/DAS/sqm_B_hybrid_DASTool_bins* so I found it really weird:

It means, according to your sqm_B_hybrid_anvio_bins: your bins are named as 'metabat2_283_fa_sub_contigs', but then within your DAS folder, they are called '26.fa_sub.contigs.fa' Are the same files?

**Comment by bresyd** [comment]
Hi,
regarding the bin names: from what I see, the bin names are the same. In addition to maxbin and metabat2 I also used concoct externally and then combined the output of the three binning tools with the SQM DAStool script. When I `ls` in the DAS directory, it outputs the concoct bins first (which start with a number) but when I 'head' the sqm_B_hybrid_anvio_bins.txt file it outputs the metabat bins first. But the concoct bins are also present in the sqm_B_hybrid_anvio_bins.txt file as you can see here:

```
grep "26.fa_sub.contigs" sqm_B_hybrid_anvio_bins.txt | head
megahit_763     26_fa_sub_contigs
megahit_997     26_fa_sub_contigs
megahit_1306    26_fa_sub_contigs
megahit_1454    26_fa_sub_contigs
megahit_1857    26_fa_sub_contigs
megahit_2045    26_fa_sub_contigs
megahit_2288    26_fa_sub_contigs
megahit_2526    26_fa_sub_contigs
megahit_3213    26_fa_sub_contigs
megahit_3224    26_fa_sub_contigs

```

```
anvi-import-collection sqm_B_hybrid/results/sqm2anvio/sqm_B_hybrid_anvio_bins.txt -c sqm_B_hybrid/results/anvio/CONTIGS.db -p sqm_B_hybrid/results/anvio/temp/PROFILE.db -C DAS --contigs-mode
Contig/split name conversion .................: 372952 contig names converted into 373515 split names.
Item names in input ..........................: 373,515
Num bins in input ............................: 163

WARNING
===============================================
Since you are working with a blank proifle, anvi'o is not going to check whether
the names item names in your collections file matches to the item names in other
databases of yours. It is all fine for now, but this requires you to be even
extra careful with your downstream analyses in case stuff hits the fan later.

Items in profile database ....................: 373,515
Item names shared between input and db .......: 373,515


Config Error: Sorry, bin name can't start with a digit. Long story. Please specify a name that
              starts with an ASCII letter.     
```
Now this is interesting. Maybe the issue all along was that my concoct bins start with a number?

**Comment by ggnatalia** [comment]
Yes, it will be that. For instance, in the case of the contigs name I know that only underscores as special character are allowed. So just add a *concoct* label before concoct names at least in the sqm_B_hybrid_anvio_bins.txt and probably the problem will be solved. Just let me know it is not!

**Comment by bresyd** [comment]
Hi,
I just wanted to let you know that I followed your first suggestion (`(my $bam = $sam) =~ s/\.sam$/-RAW.bam/;`) and then I was able to successfully load the project into anvio and visualize my bins; thanks again for figuring this out,

I do have one more question regarding loading bin collections to anvio: because the different binning tools and dastools do produce different bins (as nicely illustrated here (https://merenlab.org/2020/01/02/visualizing-metagenomic-bins/) and dastool does not always have to be the "best" one;), I would also be curious to look at the bins produced by the binning tools (maxbin and metabat) in anvio. Is there a straight forward way to also load the maxbin and metabat collections into anvio using the anvi-load-sqm.py script?

Thanks again

**Comment by ggnatalia** [comment]
Hi!

There is not a straight forward way to do that, although it isn't very difficult.
You should import any other bin collection using the command (repeat it as many times as binning results you want to load into anvi'o):

    anvi-import-collection <*anvio_bins.txt>  -c CONTIGS.db -p PROFILE.db -C <collection_name> --contigs-mode

For it, you will need a file analogous to the <project_name_anvio_bins.txt> that you find within the folder sqm2anvio.

    megahit_558	maxbin_028_fasta_contigs
    megahit_1458	maxbin_028_fasta_contigs
    megahit_1774	maxbin_028_fasta_contigs
    megahit_1810	maxbin_028_fasta_contigs
    megahit_2311	maxbin_028_fasta_contigs
    megahit_2441	maxbin_028_fasta_contigs

As you can observe, it is a tab-file, in which the first column is the name of the contig, and the second column is the name of the bin it belongs to.

If I'm not wrong, within your results, there may be a DAS folder. In this folder there are maxbin.table 
 and metabat2.table files (or more if you have run more binners) which are the results of these two binning tools. You can copy them to your anvio folder and replace '.' by '_'  (because anvi'o doesn't like special characters but the '_') and use them like the <*anvio_bins.txt> file.

Please let me know if it works for you, maybe I can add it for the next release.

**Comment by bresyd** [comment]
Hi,
thanks for your quick response. I will give this a try and let you know how it works.
cheers

**Comment by bresyd** [comment]
Hi,
just wanted to let you know that your above instructions to visualize the other collections work perfectly. 
Thanks again for your help.

**Comment by ggnatalia** [comment]
Ok! Thank you! I'm going to close this issue now, but please, feel free to open a new one if you have more questions!
