### ISSUE TITLE
Database versions

### ISSUE THREAD

**Issue by ebhollister** [jtamames/SqueezeMeta#372]
Is it possible to have the database versions explicitly labeled (e.g., for KEGG, COG, Pfam)? The manual indicates that the KEGG db is the last free version, and the make_databases_alt.pl script calls for a current version of Pfam and specifies version 132 for SILVA, but it's not clear what the versioning for nr and COG/EggNog look like. Thanks for clarifying!

**Comment by fpusan** [comment]
Hi!
The eggNOG version is 4.5.
Regarding nr, they don't do official releases I think. Rather, you can look at the DB_BUILD_DATE file in the databases directory to see when the nr database was downloaded.
Hope this helps,
Fernando

**Comment by ebhollister** [comment]
Great! Thanks so much for confirming the eggNOG version and updating the documentation.
