### ISSUE TITLE
sqm2itol.pl

### ISSUE THREAD

**Issue by sskoldas** [jtamames/SqueezeMeta#373]
Hi,

Thanks to your help I've managed to run my project on Squeezemeta. Now I have the data to work on visual results, but I'm running into some problems. As you can see below, 

`(SqueezeMeta) sskoldas@sskoldas-Summit-E15-A11SCST:~/mambaforge/envs/SqueezeMeta/SqueezeMeta$ sqm2itol.pl samples

Reading bins in /home/sskoldas/mambaforge/envs/SqueezeMeta/SqueezeMeta/samples/results/19.samples.bintable...
Cannot open /home/sskoldas/mambaforge/envs/SqueezeMeta/SqueezeMeta/samples/results/19.samples.bintable at /home/sskoldas/mambaforge/envs/SqueezeMeta/bin/sqm2itol.pl line 95.`

my samples are in samples folder but when I try to run the `sqm2itol.pl samples` I've been getting the error for not being able to generate bintable. Do you know what might cause this problem? I'll be happy to provide additional info if you need.
Below, you can see my conf.pl:

`$mode = "merged";

$installpath = "/home/sskoldas/mambaforge/envs/SqueezeMeta/SqueezeMeta";
#-- Project dir (calculated dinamically on execution, DO NOT MODIFY)

use File::Basename;
use Cwd 'abs_path';
$projectdir   = abs_path(dirname(__FILE__));

#-- Generic paths

#$databasepath = "/media/disk7/fer/SqueezeMeta/db";
$databasepath = "/home/sskoldas/mambaforge/envs/SqueezeMeta/SqueezeMeta/db";
$extdatapath  = "$installpath/data";
$scriptdir    = "$installpath/scripts";   #-- Scripts directory

#-- Paths relative to the project

$projectname = "samples";
$datapath    = "$projectdir/data";                                       #-- Directory containing all datafiles
$resultpath  = "$projectdir/results";                                    #-- Directory for storing results
$extpath     = "$projectdir/ext_tables";                                 #-- Directory for storing tables for further analysis
$tempdir     = "$projectdir/temp";                                       #-- Temp directory
$interdir    = "$projectdir/intermediate";                               #-- Temp directory
%bindirs = ("metabat2","$resultpath/metabat2","maxbin","$resultpath/maxbin");
%dasdir      = ("DASTool","$resultpath/DAS/$projectname\_DASTool\_bins");	   #-- Directory for DASTool results

#-- Result files

$mappingfile     = "$datapath/00.$projectname.samples";         #-- Mapping file (samples -> fastq)
$methodsfile     = "$projectdir/methods.txt";		        #-- File listing the  methods used and their citation info
$syslogfile      = "$projectdir/syslog";                        #-- Logging file
$contigsfna      = "$resultpath/01.$projectname.fasta";         #-- Contig file from assembly
$contigslen      = "$interdir/01.$projectname.lon";             #-- Length of each contig
$rnafile         = "$resultpath/02.$projectname.rnas";          #-- RNAs from barrnap
$trnafile        = "$resultpath/02.$projectname.trnas";         #-- tRNAs from aragorn
$gff_file        = "$resultpath/03.$projectname.gff";           #-- gff file from prodigal
$aafile          = "$resultpath/03.$projectname.faa";           #-- Aminoacid sequences for genes
$ntfile          = "$resultpath/03.$projectname.fna";           #-- Nucleotide sequences for genes
$taxdiamond      = "$interdir/04.$projectname.nr.diamond";      #-- Diamond result
$cogdiamond      = "$interdir/04.$projectname.eggnog.diamond";  #-- Diamond result, COGs
$keggdiamond     = "$interdir/04.$projectname.kegg.diamond";    #-- Diamond result, KEGG
$pfamhmmer       = "$interdir/05.$projectname.pfam.hmm";        #-- Hmmer result for Pfam
$fun3tax         = "$resultpath/06.$projectname.fun3.tax";      #-- Fun3 annotations, KEGG
$fun3kegg        = "$resultpath/07.$projectname.fun3.kegg";     #-- Fun3 annotations, KEGG
$fun3cog         = "$resultpath/07.$projectname.fun3.cog";      #-- Fun3 annotation, COGs
$fun3pfam        = "$resultpath/07.$projectname.fun3.pfam";     #-- Fun3 annotation, Pfams
$gff_file_blastx = "$resultpath/08.$projectname.gff";           #-- gff file from prodigal & blastx
$fun3tax_blastx  = "$resultpath/08.$projectname.fun3.tax";      #-- Fun3 annotations prodigal & blastx, KEGG
$fun3kegg_blastx = "$resultpath/08.$projectname.fun3.kegg";     #-- Fun3 annotations prodigal & blastx, KEGG
$fun3cog_blastx  = "$resultpath/08.$projectname.fun3.cog";      #-- Fun3 annotation prodigal & blastx, COGs
$fna_blastx      = "$interdir/08.$projectname.blastx.fna";      #-- Secuencias nt obtenidas por blastx
$allorfs         = "$tempdir/09.$projectname.allorfs";          #-- From summary_contigs.pl, allorfs file
$alllog          = "$interdir/09.$projectname.contiglog";       #-- From summary_contigs.pl, contiglog file (formerly alllog file)
$mapcountfile    = "$interdir/10.$projectname.mapcount";        #-- From mapsamples.pl, rpkm and coverage counts for all samples
$contigcov       = "$interdir/10.$projectname.contigcov";       #-- From mapbamsamples.pl, coverages of  for all samples
$mappingstat     = "$resultpath/10.$projectname.mappingstat";   #-- From mapsamples.pl, mapping statistics for all samples
$mcountfile      = "$resultpath/11.$projectname.mcount";        #-- From mcount.pl, abundances of all taxa
$mergedfile      = "$resultpath/13.$projectname.orftable";      #-- Gene table file
$bintax          = "$interdir/17.$projectname.bintax";          #-- From addtax2.pl
$bincov          = "$interdir/19.$projectname.bincov";          #-- Coverage of bins, from getbins.pl
$bintable        = "$resultpath/19.$projectname.bintable";      #-- Mapping of contigs in bins, from getbins.pl
$contigsinbins   = "$interdir/19.$projectname.contigsinbins";   #-- Bin to which each contig belongs
$contigtable     = "$resultpath/20.$projectname.contigtable";   #-- From getcontigs.pl, contigs table

#-- Datafiles

$coglist   = "$extdatapath/coglist.txt";        #-- COG equivalence file (COGid -> Function -> Functional class)
$kegglist  = "$extdatapath/keggfun2.txt";       #-- KEGG equivalence file (KEGGid -> Function -> Functional class)
$pfamlist  = "$extdatapath/pfam.dat";           #-- PFAM equivalence file
$taxlist   = "$extdatapath/alltaxlist.txt";     #-- Tax equivalence file 
$nr_db     = "$databasepath/nr.dmnd";
$cog_db    = "$databasepath/eggnog";
$kegg_db   = "$databasepath/keggdb";
$lca_db    = "$databasepath/LCA_tax/taxid.db";
$bowtieref = "$datapath/$projectname.bowtie";   #-- Contigs formatted for Bowtie
$pfam_db   = "$databasepath/Pfam-A.hmm";
$mothur_r  = "$databasepath/silva.nr_v132.align";
$mothur_t  = "$databasepath/silva.nr_v132.tax";

#-- Variables

$blocksize       = NF;
$nocog           = 0;
$nokegg          = 0;
$nopfam          = 1;
$euknofilter     = 0;
$nobins          = 1;
$doublepass      = 0;
$singletons      = 0;
$cleaning        = 0;
$cleaningoptions = "";
$mapper          = "bowtie";
$mapping_options = "";

#-- External software

$metabat_soft       = "$installpath/bin/metabat2";
$maxbin_soft        = "$installpath/bin/MaxBin/run_MaxBin.pl";
$spades_soft        = "$installpath/bin/SPAdes/spades.py";
$barrnap_soft       = "$installpath/bin/barrnap";
$rdpclassifier_soft = "java -jar $installpath/bin/classifier.jar";
$bowtie2_build_soft = "$installpath/bin/bowtie2/bowtie2-build";
$bowtie2_x_soft     = "$installpath/bin/bowtie2/bowtie2";
$bwa_soft           = "$installpath/bin/bwa";
$minimap2_soft      = "$installpath/bin/minimap2";
$diamond_soft       = "$installpath/bin/diamond";
$hmmer_soft         = "$installpath/bin/hmmer/hmmsearch";
$megahit_soft       = "$installpath/bin/megahit/megahit";
$prinseq_soft       = "$installpath/bin/prinseq-lite.pl";
$prodigal_soft      = "$installpath/bin/prodigal";
$cdhit_soft         = "$installpath/bin/cd-hit-est";
$toamos_soft        = "$installpath/bin/AMOS/toAmos";
$minimus2_soft      = "$installpath/bin/AMOS/minimus2";
$checkm_soft        = "PATH=$installpath/bin:$installpath/bin/pplacer:$installpath/bin/hmmer:\$PATH $installpath/bin/checkm";
$minpath_soft       = "python3 $installpath/bin/MinPath1.4.py";
$canu_soft          = "$installpath/bin/canu/canu";
$flye_soft          = "$installpath/bin/Flye-2.8.1/bin/flye";
$trimmomatic_soft   = "java -jar $installpath/bin/trimmomatic-0.38.jar";
$dastool_soft       = "LD_LIBRARY_PATH=$installpath/lib PATH=$installpath/bin:\$PATH $installpath/bin/DAS_Tool/DAS_Tool";
$kmerdb_soft        = "LD_LIBRARY_PATH=$installpath/lib $installpath/bin/kmer-db";
$aragorn_soft       = "$installpath/bin/aragorn";
$mothur_soft        = "$installpath/bin/mothur";

#-- Options

$numthreads         = 12;
$mincontiglen       = 200;
$assembler          = "megahit";
$canumem            = NF;`

**Comment by jtamames** [comment]
Hello!
It seems that you ran SqueezeMeta with the --nobins option, because the variable `$nobins` is set to 1 in `SqueezeMeta_conf.pl`. Therefore binning was not done and therefore the bin table is missing. That table is needed for sqm2itol (it plots the taxonomy or functions in bins).
You can produce bins setting $nobins=0 in `SqueezeMeta_conf.pl`, and then restart from step 14 (restart.pl -step 14).
Best,
Javier

**Comment by sskoldas** [comment]
oh! I understand. So does that mean my `sqm2ipath.pl `not working is related to the same `$nobins` option?

**Comment by sskoldas** [comment]
I got this problem, this is my project path: /home/sskoldas/mambaforge/envs/SqueezeMeta/SqueezeMeta/samples/results/
```
(SqueezeMeta) sskoldas@sskoldas-Summit-E15-A11SCST:~/mambaforge/envs/SqueezeMeta/SqueezeMeta/samples$ sqm2ipath.pl /home/sskoldas/mambaforge/envs/SqueezeMeta/SqueezeMeta/samples/results/13.samples.orftable

Please provide a valid project name or project path
```

**Comment by jtamames** [comment]
Just specify the name of the project. Your project is "samples", so it could be:

`sqm2ipath.pl samples`

If you run it from the directory containing it. From any location, you can also specify the full path for the project:

`sqm2ipath.pl /home/sskoldas/mambaforge/envs/SqueezeMeta/SqueezeMeta/samples`

Best,
J

**Comment by sskoldas** [comment]
I tried as you mentioned but it gave me same error: `Please provide a valid project name or project path`

**Comment by sskoldas** [comment]
Sorry again, it's me,
I had run merge option for all my samples, It gave me some bad mapping results therefore I run `sqm_reads.pl`. Their outputs are into "samples" folder and for each sample has separate folder name into "samples" folder. 
Like this: /home/sskoldas/mambaforge/envs/SqueezeMeta/SqueezeMeta/samples/"sample1", "sample2", "sample3" ....

I run this comment:
`$ sqmreads2tables.py /home/sskoldas/mambaforge/envs/SqueezeMeta/SqueezeMeta/samples ReadsTables` 
and it gave me this error: 
`Traceback (most recent call last):
  File "/home/sskoldas/mambaforge/envs/SqueezeMeta/bin/sqmreads2tables.py", line 252, in <module>
    main(parse_args())
  File "/home/sskoldas/mambaforge/envs/SqueezeMeta/bin/sqmreads2tables.py", line 71, in main
    samples[sample] += int(total_reads)
ValueError: invalid literal for int() with base 10: '438350.75'`

How can I fix this error?

**Comment by fpusan** [comment]
I don't quite get it. This seems like an output from SqueezeMeta, not sqm_reads.pl
