### ISSUE TITLE
error in step 10

### ISSUE THREAD

**Issue by sskoldas** [jtamames/SqueezeMeta#374]
Hi!
Do you know, what should I do for this error? Is it important?
```
Aligning to reference with bowtie
Error: Read ERR4129703.438351 NB551160:170:HFL2HBGX5:1:13110:12595:10923:N:0:GAGATTCC+TCAGAGCC#0/1 has more read characters than quality values.
terminate called after throwing an instance of 'int'
Aborted (core dumped)
(ERR): bowtie2-align exited with value 134
```
Thanks in advance

**Comment by chowonkyong** [comment]
I found that raw fastq files had problems for mapping with bowtie.
I used the fastq files in which host sequences were removed.
I replaced the raw data files with original fastq files and conducted restart.pl. 
It seems that it is now working well.

**Comment by jtamames** [comment]
Then please check your input sequence files, apparently trimmomatic messed with them in some way.
