### ISSUE TITLE
SAMPLE FILES(TEST SAMPLE FORMAT)

### ISSUE THREAD

**Issue by kak8** [jtamames/SqueezeMeta#38]
Hello. I am trying to run a single end  whole genome metagenome sample sequenced on nanopore and trying to analyze on squeezemeta.
Can someone guide me on the exact format and correct file format of the test.sample file.

**Comment by fpusan** [comment]
As specified in the ReadMe, the samples file must contain the samples, the names of their corresponding raw read files and the sequencing pair represented in those files, separated by tabulators.

For single end datasets, just include all files as "pair1" like

```
Sample1	readfile1.fastq.gz	pair1
Sample2	readfile2.fastq.gz	pair1
Sample3	readfile3.fastq.gz	pair1
```

**Comment by kak8** [comment]
Thank you for your help.
I have made the sample file as
a	a.fastq.gz	pair 1
I am still getting the error as-
 Can't open samples file (-s) in samplefile. Please check that it is the correct file. Where is this file supposed to be placed? In the folder where the fastq file is placed or in some other folder?
Kindly assist as I am unable to proceed further. 
Secondly, is there any source where SqueezeMeta commands can be obtained?

**Comment by kak8** [comment]
Hello,
I am facing another issue- I am getting the following error-
Please do not use blank spaces in the samples file
Kindly assist.
