### ISSUE TITLE
Squeezemeta stops in 01.run_assembly.pl.

### ISSUE THREAD

**Issue by analopezlopez** [jtamames/SqueezeMeta#380]
Hi,

I'm using SqueezeMeta for the first time to perform assemblies in my metagenome data from Nanopore sequencing. My command is:
SqueezeMeta.pl -m coassembly -p test_coassembly -s samples.file.txt -f /home/analopez/snic2020-6-60/AnaLopez/barcoding/RUN_3/merged_files --euk --minion

If I understood correctly, by using the --minion flag, the software switches to Canu as a reference assembler and minimap for the downstream mapping. It seems to be stopping at the very beginning of the pipeline and I must say that I've had problems using Canu in the past, so it seems to be happening again. I also did another small test using Megahit (removing the --minion flag) and the pipeline was completed although no bins were generated, I guess because it is not optimized for long reads. 

I attach the [syslog.zip](https://github.com/jtamames/SqueezeMeta/files/7476235/syslog.zip) from the run with Canu so you can take a look at it.

Any suggestions would be highly appreciated! Thank you very much in advance.
Ana

**Comment by fpusan** [comment]
Hi Ana,

Your interpretation is correct, the `--minion` will use minion for assembly and minimap2 for mapping.

The issue seems to be related to the way MinION is trying to spawn it's own jobs in the cluster. See discussions in https://github.com/marbl/canu/issues/1113.

Adding `useGrid=false` to the canu call _might_ solve it. You can easily pass it when calling SqueezeMeta by adding `-assembly_options "useGrid=false"`

And of course you can try using flye as Javier said!

**Comment by analopezlopez** [comment]
Hi Fernando and Javier,

Thank you for your very much appreciated suggestions. I'm already trying with Flye.

The computational service that I'm currently using to run the jobs seems to have the useGrid=false option activated by default when using Canu. Would you recommend me to try it anyway?

**Comment by fpusan** [comment]
They might have configured that way for _their_ canu, but this is SqueezeMeta's own copy and it will run with default parameters unless you tell it otherwise. So it might still worth trying.
Then again, maybe flye does the trick. Let us know!

**Comment by analopezlopez** [comment]
Ok! Now I understand. I think I'll try both options and I'll let you know.

Thank you again!

**Comment by analopezlopez** [comment]
Hi Javier and Fernando,

I just wanted to let you know that I tried to run the pipeline using Flye and it went smoothly!

Thanks for the tip!

Best, 
Ana

**Comment by fpusan** [comment]
Glad to hear! Closing issue
