### ISSUE TITLE
Map File options being ignored and possible bug with --assembly_options flag

### ISSUE THREAD

**Issue by shawndoyle** [jtamames/SqueezeMeta#383]
I am experiencing some peculiar behavior with the pipeline.

I have a combined dataset of 16 metagenomes and 16 metatranscriptomes. I decided to use seqmerge mode because my datasets are very large (~20-40 Gbytes in raw paired reads per sample). I am assembling only the metagenomes and will use the metatranscriptomes for mapping, so i've added noassembly,nobinning to the map file:

> S10dna	S10dna_trimmed_1P.fq.gz	pair1	
> S10dna	S10dna_trimmed_2P.fq.gz	pair2	
> S10rna	S10rna_trimmed_1P.fq.gz	pair1	noassembly,nobinning
> S10rna	S10rna_trimmed_2P.fq.gz	pair2	noassembly,nobinning

I also tried to use custom kmer list for megahit using -assembly_options --k-list 23, 43, 63, 83, 103, 123.

> SqueezeMeta.pl -m seqmerge -p Meso7 -s M7_MetaSqueeze.samples -f /data/process/Shawn/Meso7/4_Trimmomatic/trimmed_reads/paired/ -c 500 -t 24 -assembly_options --k-list 23, 43, 63, 83, 103, 123.

The first run failed right after it finished copying the raw data during the first Megahit call. SqueezeMeta ended up duplicating the k-list when calling megahit. It would use both my custom kmer list and the default one simultaneously, leading to an error:

> Running Megahit for S10dna: /home/sdoyle22/anaconda3/envs/SqueezeMeta/SqueezeMeta/bin/megahit/megahit --k-list 23, 43, 63, 83, 103, 123 -1 /data/process/Shawn/Meso7/5_MetaSqueeze/Meso7/temp/par1..gz -2 /data/process/Shawn/Meso7/5_MetaSqueeze/Meso7/temp/par2..gz --k-list 29,39,59,79,99,119,141 -t 24 -o /data/process/Shawn/Meso7/5_MetaSqueeze/Meso7/data/megahit >> /data/process/Shawn/Meso7/5_MetaSqueeze/Meso7/syslog 2>&1
> Traceback (most recent call last):
>   File "/home/sdoyle22/anaconda3/envs/SqueezeMeta/SqueezeMeta/bin/megahit/megahit", line 1039, in <module>
>     main()
>   File "/home/sdoyle22/anaconda3/envs/SqueezeMeta/SqueezeMeta/bin/megahit/megahit", line 978, in main
>     parse_option(argv[1:])
>   File "/home/sdoyle22/anaconda3/envs/SqueezeMeta/SqueezeMeta/bin/megahit/megahit", line 370, in parse_option
>     opt.k_list = list(map(int, value.split(',')))
> ValueError: invalid literal for int() with base 10: ''

To solve this, I modified the SqueezeMeta_conf.pl file, removing the $assemblyoptions line at the bottom, and restarted the pipeline. It is now assembling fine using the default kmer-list and then using prinseq to cull short contigs <500bp. The issue I'm having now is that it is also assemblying my metatranscriptome samples, despite the noassembly flag in the map file.

> Running Megahit for S14dna: /home/sdoyle22/anaconda3/envs/SqueezeMeta/SqueezeMeta/bin/megahit/megahit  -1 /data/process/Shawn/Meso7/5_MetaSqueeze/Meso7/temp/par1..gz -2 /data/process/Shawn/Meso7/5_MetaSqueeze/Meso7/temp/par2..gz --k-list 29,39,59,79,99,119,141 -t 24 -o /data/process/Shawn/Meso7/5_MetaSqueeze/Meso7/data/megahit >> /data/process/Shawn/Meso7/5_MetaSqueeze/Meso7/syslog 2>&1

> Running Megahit for S14rna: /home/sdoyle22/anaconda3/envs/SqueezeMeta/SqueezeMeta/bin/megahit/megahit  -1 /data/process/Shawn/Meso7/5_MetaSqueeze/Meso7/temp/par1..gz -2 /data/process/Shawn/Meso7/5_MetaSqueeze/Meso7/temp/par2..gz --k-list 29,39,59,79,99,119,141 -t 24 -o /data/process/Shawn/Meso7/5_MetaSqueeze/Meso7/data/megahit >> /data/process/Shawn/Meso7/5_MetaSqueeze/Meso7/syslog 2>&1

[syslog.txt](https://github.com/jtamames/SqueezeMeta/files/7514145/syslog.txt)
[M7_MetaSqueeze.samples.txt](https://github.com/jtamames/SqueezeMeta/files/7514156/M7_MetaSqueeze.samples.txt)

**Comment by jtamames** [comment]
Hello 
Did you try putting the assembly options between quotes? 

> SqueezeMeta.pl -m seqmerge -p Meso7 -s M7_MetaSqueeze.samples -f /data/process/Shawn/Meso7/4_Trimmomatic/trimmed_reads/paired/ -c 500 -t 24 -assembly_options "--k-list 23, 43, 63, 83, 103, 123".

**Comment by fpusan** [comment]
However the issue with the `noassembly` flag being ignored should be independent of this I think?

**Comment by shawndoyle** [comment]
Thanks! I did not use quotes.

Yes, I believe the noassembly issue is independent. Do you think it might be related to using restart.pl instead of SqueezeMeta.pl? The only reason I avoided the latter, as I was still on Step1, is my raw data takes several hours to copy to the project directory.

**Comment by jtamames** [comment]
Yep, it should be an independent issue. I will check this asap

**Comment by jtamames** [comment]
Sorry for my very delayed answer to this issue. I did lost track of it.
For making the "noassembly" option work, replace the line 44 in 01.run_assembly_merged.pl:
`next if($flag eq "noassembly")`;
by
`next if($flag=~"noassembly")`;

That should do it.
Best,
Javier
