### ISSUE TITLE
Multiple external assemblies?

### ISSUE THREAD

**Issue by Ahmed-Shibl** [jtamames/SqueezeMeta#384]
First, thanks for this very useful tool.
Second, I have two metagenomic assemblies (let's call them `F3_contigs.fa` & `F4_contigs.fa`) that are each made of pair-end reads, i.e. `F3_contigs.fa` was assembled from F3_R1.fastq and F3_R2.fastq while `F4_contigs.fa` was assembled from F4_R1.fastq, and F4_R2.fastq.

Is it possible to call for these two assemblies using `-extassembly` when I run `SqueezeMeta.pl` so that only their corresponding reads are mapped against them downstream? I would like to visualize both samples in the same barplot at the end. Of course, my samples file (`-s`) would look something like this:
```
F3	F3_R1.fastq	pair1
F3	F3_R2.fastq	pair2
F4	F4_R1.fastq	pair1
F4	F4_R2.fastq	pair2
```

Please let me know if my question isn't clear or if you'd want more information from my end. Thanks.

**Comment by fpusan** [comment]
Hi!
If what you want is to process both assemblies independently and then visualize together in the same plot, what I would do is:

```
# Run two separate SqueezeMeta projects, each assembly together with its samples.
# Let's say those projects are called "F3" and "F4
# After running both, get into R
library(SQMtools)
F3 = loadSQM("F3")
F4 = loadSQM("F4")
combi = combineSQMlite(F3, F4)
plotTaxonomy(combi)
plotFunctions(combi)
```
