### ISSUE TITLE
SQMtools output files

### ISSUE THREAD

**Issue by analopezlopez** [jtamames/SqueezeMeta#385]
Hi!

I'm using the SQMtools package in R for the first time, working in a conda environment through my university server. This question might be silly but where do all the graphs from the `plotTaxonomy` function get stored? 

I did a small test with one of my experiments and all of a sudden, an Rplots.pdf appeared in a random place, way higher from the directory where I keep the SQM object and the rest of the project data. Now I'm trying to re-do the test, customizing the plots and I can't seem to find any pdf file containing the output.

I tried to find the answer within your closed issues section but couldn't find it anywhere.

Thank you very much in advance.

Regards, 
Ana

**Comment by fpusan** [comment]
Hi!
Most are standard ggplot2 graphs and can be saved as such.

**Comment by analopezlopez** [comment]
Okay! But are they supposed to be generated in a specific folder?

Sorry for the question. I'm working with R through the terminal and I can't find them anywhere, so for all I know I could be doing the whole process wrong.

**Comment by fpusan** [comment]
You have to explicitly save them somewhere.
```
plotTaxonomy(SQM)
ggsave("/path/to/output/name.jpg")
```

**Comment by analopezlopez** [comment]
Okay, yes! Now I see it at your Wiki page as well. 
Thank you very much!
