### ISSUE TITLE
GUIDANCE FOR FURTHER ANALYSIS

### ISSUE THREAD

**Issue by kak8** [jtamames/SqueezeMeta#39]
/SqueezeMeta/scripts/SqueezeMeta.pl -m Sequential -s test.samples -f raw/ --minion

SqueezeMeta v1.0.0 - (c) J. Tamames, F. Puente-Sánchez CNB-CSIC, Madrid, SPAIN

Please cite: Tamames & Puente-Sanchez, Frontiers in Microbiology 10.3389 (2019). doi: https://doi.org/10.3389/fmicb.2018.03349

Run started Wed Oct 30 11:26:47 2019 in Sequential mode
Now reading samples
1 metagenomes found
Working with gut
Run started Wed Oct 30 11:26:47 2019 in SEQUENTIAL mode
Now creating directories
Reading configuration from /SqueezeMeta/databases/test/abc/SqueezeMeta_conf.pl
Now linking read files
Now preparing files
ln -s /SqueezeMeta/databases/test/abc/data/raw_fastq/abc.fastq.gz  /SqueezeMeta/databases/test/abc/data/raw_fastq/par1.fastq.gz
[0 seconds]: STEP2 -> RNA PREDICTION: 02.run_barrnap.pl
cp: cannot stat '/SqueezeMeta/databases/test/abc/results/01.abc.fasta': No such file or directory
Running barrnap for Bacteria
[11:26:47] Usage: barrnap <file.fasta>
Error running command:    /SqueezeMeta/scripts/../bin/barrnap --quiet --threads 12 --kingdom bac --reject 0.1 /SqueezeMeta/databases/test/abc/intermediate/02.abc.maskedrna.fasta --dbdir /SqueezeMeta/databases > /SqueezeMeta/databases/test/abc/temp/bac.gff at /SqueezeMeta/scripts/../scripts/02.run_barrnap.pl line 44.
Stopping in STEP2 -> 02.run_barrnap.pl

I would like to understand two things-
Command for assembly with Canu as it is minion and commands for further analysis.
Kindly help

**Comment by kak8** [comment]
Also When i entered the following command for assembly-
/SqueezeMeta/scripts/01.run_assembly.pl -m Sequential -s test.samples -f raw/ --minion
Error- Can't find SqueezeMeta_conf.pl in -m. Is the project path ok? at /SqueezeMeta/scripts/01.run_assembly.pl line 15.

**Comment by fpusan** [comment]
The flag --minion makes SqueezeMeta use the canu assembler, as well as the minimap2 mapper for minion reads.

In order to run single steps of the pipeline, you only need to include the project path.
In this case you are using the sequential mode, which will generate an independent project for each sample. There will be a folder named after each sample, so if a sample is named `abc` in the samples file, the command would be

`/SqueezeMeta/scripts/01.run_assembly.pl abc`

It would seem that SqueezeMeta skipped the assembly step. Could you send me the samples file, and the output of the 01.run_assembly.pl script?

**Comment by fpusan** [comment]
Ok, I see it now. In your first command
`/SqueezeMeta/scripts/SqueezeMeta.pl -m Sequential -s test.samples -f raw/ --minion`
You used `-m Sequential` and it should have been `-m sequential` (without capitalization).

SqueezeMeta should have provided a proper error message there, sorry about that. Will be fixed in the next patch.

**Comment by kak8** [comment]
/SqueezeMeta/scripts/01.run_assembly.pl gut
Running assembly with canu: rm -r
/SqueezeMeta/databases/test/gut/data/canu;
/SqueezeMeta/scripts/../bin/canu/canu  -p gut -d
/SqueezeMeta/databases/test/gut/data/canu genomeSize=5m
corOutCoverage=10000 corMhapSensitivity=high corMinCoverage=0 redMemory=32
oeaMemory=32 batMemory=32 mhapThreads=12 mmapThreads=12 ovlThreads=12
ovbThreads=12 ovsThreads=12 corThreads=12 oeaThreads=12 redThreads=12
batThreads=12 gfaThreads=12 merylThreads=12 -nanopore-raw
 /SqueezeMeta/databases/test/gut/data/raw_fastq/par1.fastq.gz;mv
/SqueezeMeta/databases/test/gut/data/canu/gut.contigs.fasta
/SqueezeMeta/databases/test/gut/data/canu/contigs.fasta
rm: cannot remove '/SqueezeMeta/databases/test/gut/data/canu': No such file
or directory
-- Canu 1.8
--
-- CITATIONS
--
-- Koren S, Walenz BP, Berlin K, Miller JR, Phillippy AM.
-- Canu: scalable and accurate long-read assembly via adaptive k-mer
weighting and repeat separation.
-- Genome Res. 2017 May;27(5):722-736.
-- http://doi.org/10.1101/gr.215087.116
-- 
-- Koren S, Rhie A, Walenz BP, Dilthey AT, Bickhart DM, Kingan SB,
Hiendleder S, Williams JL, Smith TPL, Phillippy AM.
-- De novo assembly of haplotype-resolved genomes with trio binning.
-- Nat Biotechnol. 2018
-- https//doi.org/10.1038/nbt.4277
-- 
-- Read and contig alignments during correction, consensus and GFA building
use:
--   Šošic M, Šikic M.
--   Edlib: a C/C ++ library for fast, exact sequence alignment using edit
distance.
--   Bioinformatics. 2017 May 1;33(9):1394-1395.
--   http://doi.org/10.1093/bioinformatics/btw753
-- 
-- Overlaps are generated using:
--   Berlin K, et al.
--   Assembling large genomes with single-molecule sequencing and
locality-sensitive hashing.
--   Nat Biotechnol. 2015 Jun;33(6):623-30.
--   http://doi.org/10.1038/nbt.3238
-- 
--   Myers EW, et al.
--   A Whole-Genome Assembly of Drosophila.
--   Science. 2000 Mar 24;287(5461):2196-204.
--   http://doi.org/10.1126/science.287.5461.2196
-- 
-- Corrected read consensus sequences are generated using an algorithm
derived from FALCON-sense:
--   Chin CS, et al.
--   Phased diploid genome assembly with single-molecule real-time
sequencing.
--   Nat Methods. 2016 Dec;13(12):1050-1054.
--   http://doi.org/10.1038/nmeth.4035
-- 
-- Contig consensus sequences are generated using an algorithm derived from
pbdagcon:
--   Chin CS, et al.
--   Nonhybrid, finished microbial genome assemblies from long-read SMRT
sequencing data.
--   Nat Methods. 2013 Jun;10(6):563-9
--   http://doi.org/10.1038/nmeth.2474
-- 
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_222' (from 'java') with
-d64 support.
--
-- WARNING:
-- WARNING:  Failed to run gnuplot using command 'gnuplot'.
-- WARNING:  Plots will be disabled.
-- WARNING:
--
-- Detected 16 CPUs and 63 gigabytes of memory.
-- No grid engine detected, grid disabled.
--
--                            (tag)Concurrency
--                     (tag)Threads          |
--            (tag)Memory         |          |
--        (tag)         |         |          |     total usage     algorithm
--        -------  ------  --------   --------  -----------------
 -----------------------------
-- Local: meryl     12 GB   12 CPUs x   1 job     12 GB   12 CPUs  (k-mer
counting)
-- Local: hap        8 GB    4 CPUs x   4 jobs    32 GB   16 CPUs
 (read-to-haplotype assignment)
-- Local: cormhap    6 GB   12 CPUs x   1 job      6 GB   12 CPUs  (overlap
detection with mhap)
-- Local: obtovl     4 GB   12 CPUs x   1 job      4 GB   12 CPUs  (overlap
detection)
-- Local: utgovl     4 GB   12 CPUs x   1 job      4 GB   12 CPUs  (overlap
detection)
-- Local: ovb        4 GB   12 CPUs x   1 job      4 GB   12 CPUs  (overlap
store bucketizer)
-- Local: ovs        8 GB   12 CPUs x   1 job      8 GB   12 CPUs  (overlap
store sorting)
-- Local: red       32 GB   12 CPUs x   1 job     32 GB   12 CPUs  (read
error detection)
-- Local: oea       32 GB   12 CPUs x   1 job     32 GB   12 CPUs  (overlap
error adjustment)
-- Local: bat       32 GB   12 CPUs x   1 job     32 GB   12 CPUs  (contig
construction with bogart)
-- Local: gfa        8 GB   12 CPUs x   1 job      8 GB   12 CPUs  (GFA
alignment and processing)
--
-- Found Nanopore uncorrected reads in the input files.
--
-- Generating assembly 'gut' in '/SqueezeMeta/databases/test/gut/data/canu'
--
-- Parameters:
--
--  genomeSize        5000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.3200 ( 32.00%)
--    obtOvlErrorRate 0.1200 ( 12.00%)
--    utgOvlErrorRate 0.1200 ( 12.00%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.5000 ( 50.00%)
--    obtErrorRate    0.1200 ( 12.00%)
--    utgErrorRate    0.1200 ( 12.00%)
--    cnsErrorRate    0.2000 ( 20.00%)
--
--
-- BEGIN CORRECTION
--
----------------------------------------
-- Starting command on Wed Oct 30 14:13:23 2019 with 2641.361 GB free disk
space

    cd .
    /SqueezeMeta/bin/canu/sqStoreCreate \
      -o ./gut.seqStore.BUILDING \
      -minlength 1000 \
      ./gut.seqStore.ssi \
    > ./gut.seqStore.BUILDING.err 2>&1

-- Finished on Wed Oct 30 14:13:24 2019 (one second) with 2641.348 GB free
disk space
----------------------------------------
--
-- WARNING:  Potential problems with your input reads were detected.
-- WARNING:
-- WARNING:  Please review the logging in files:
-- WARNING:
 /SqueezeMeta/databases/test/gut/data/canu/gut.seqStore.BUILDING.err
-- WARNING:
 /SqueezeMeta/databases/test/gut/data/canu/gut.seqStore.BUILDING/errorLog
-- 
-- Proceeding with assembly because stopOnReadQuality=false.
--
-- WARNING: gnuplot failed.
--
----------------------------------------
--
-- ERROR:  Read coverage (1.51) is too low to be useful.
-- ERROR:
-- ERROR:  This could be caused by an incorrect genomeSize or poor quality
reads that could not
-- ERROR:  be sufficiently corrected.
-- ERROR:
-- ERROR:  You can force Canu to continue by decreasing parameter
stopOnLowCoverage=10,
-- ERROR:  however, the quality of corrected reads and/or contiguity of
contigs will be poor.
-- 

ABORT:
ABORT: Canu 1.8
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
mv: cannot stat
'/SqueezeMeta/databases/test/gut/data/canu/gut.contigs.fasta': No such file
or directory
Error running command:    rm -r /SqueezeMeta/databases/test/gut/data/canu;
/SqueezeMeta/scripts/../bin/canu/canu  -p gut -d
/SqueezeMeta/databases/test/gut/data/canu genomeSize=5m
corOutCoverage=10000 corMhapSensitivity=high corMinCoverage=0 redMemory=32
oeaMemory=32 batMemory=32 mhapThreads=12 mmapThreads=12 ovlThreads=12
ovbThreads=12 ovsThreads=12 corThreads=12 oeaThreads=12 redThreads=12
batThreads=12 gfaThreads=12 merylThreads=12 -nanopore-raw
 /SqueezeMeta/databases/test/gut/data/raw_fastq/par1.fastq.gz;mv
/SqueezeMeta/databases/test/gut/data/canu/gut.contigs.fasta
/SqueezeMeta/databases/test/gut/data/canu/contigs.fasta at
/SqueezeMeta/scripts/01.run_assembly.pl line 83.
(base) mim@mim-SVR-TS700-E9-RS8:/SqueezeMeta/databases/test$
/SqueezeMeta/scripts/01.run_assembly.pl gut
Running assembly with canu: rm -r
/SqueezeMeta/databases/test/gut/data/canu;
/SqueezeMeta/scripts/../bin/canu/canu  -p gut -d
/SqueezeMeta/databases/test/gut/data/canu genomeSize=5m
corOutCoverage=10000 corMhapSensitivity=high corMinCoverage=0 redMemory=32
oeaMemory=32 batMemory=32 mhapThreads=12 mmapThreads=12 ovlThreads=12
ovbThreads=12 ovsThreads=12 corThreads=12 oeaThreads=12 redThreads=12
batThreads=12 gfaThreads=12 merylThreads=12 -nanopore-raw
 /SqueezeMeta/databases/test/gut/data/raw_fastq/par1.fastq.gz;mv
/SqueezeMeta/databases/test/gut/data/canu/gut.contigs.fasta
/SqueezeMeta/databases/test/gut/data/canu/contigs.fasta
-- Canu 1.8
--
-- CITATIONS
--
-- Koren S, Walenz BP, Berlin K, Miller JR, Phillippy AM.
-- Canu: scalable and accurate long-read assembly via adaptive k-mer
weighting and repeat separation.
-- Genome Res. 2017 May;27(5):722-736.
-- http://doi.org/10.1101/gr.215087.116
-- 
-- Koren S, Rhie A, Walenz BP, Dilthey AT, Bickhart DM, Kingan SB,
Hiendleder S, Williams JL, Smith TPL, Phillippy AM.
-- De novo assembly of haplotype-resolved genomes with trio binning.
-- Nat Biotechnol. 2018
-- https//doi.org/10.1038/nbt.4277
-- 
-- Read and contig alignments during correction, consensus and GFA building
use:
--   Šošic M, Šikic M.
--   Edlib: a C/C ++ library for fast, exact sequence alignment using edit
distance.
--   Bioinformatics. 2017 May 1;33(9):1394-1395.
--   http://doi.org/10.1093/bioinformatics/btw753
-- 
-- Overlaps are generated using:
--   Berlin K, et al.
--   Assembling large genomes with single-molecule sequencing and
locality-sensitive hashing.
--   Nat Biotechnol. 2015 Jun;33(6):623-30.
--   http://doi.org/10.1038/nbt.3238
-- 
--   Myers EW, et al.
--   A Whole-Genome Assembly of Drosophila.
--   Science. 2000 Mar 24;287(5461):2196-204.
--   http://doi.org/10.1126/science.287.5461.2196
-- 
-- Corrected read consensus sequences are generated using an algorithm
derived from FALCON-sense:
--   Chin CS, et al.
--   Phased diploid genome assembly with single-molecule real-time
sequencing.
--   Nat Methods. 2016 Dec;13(12):1050-1054.
--   http://doi.org/10.1038/nmeth.4035
-- 
-- Contig consensus sequences are generated using an algorithm derived from
pbdagcon:
--   Chin CS, et al.
--   Nonhybrid, finished microbial genome assemblies from long-read SMRT
sequencing data.
--   Nat Methods. 2013 Jun;10(6):563-9
--   http://doi.org/10.1038/nmeth.2474
-- 
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_222' (from 'java') with
-d64 support.
--
-- WARNING:
-- WARNING:  Failed to run gnuplot using command 'gnuplot'.
-- WARNING:  Plots will be disabled.
-- WARNING:
--
-- Detected 16 CPUs and 63 gigabytes of memory.
-- No grid engine detected, grid disabled.
--
--                            (tag)Concurrency
--                     (tag)Threads          |
--            (tag)Memory         |          |
--        (tag)         |         |          |     total usage     algorithm
--        -------  ------  --------   --------  -----------------
 -----------------------------
-- Local: meryl     12 GB   12 CPUs x   1 job     12 GB   12 CPUs  (k-mer
counting)
-- Local: hap        8 GB    4 CPUs x   4 jobs    32 GB   16 CPUs
 (read-to-haplotype assignment)
-- Local: cormhap    6 GB   12 CPUs x   1 job      6 GB   12 CPUs  (overlap
detection with mhap)
-- Local: obtovl     4 GB   12 CPUs x   1 job      4 GB   12 CPUs  (overlap
detection)
-- Local: utgovl     4 GB   12 CPUs x   1 job      4 GB   12 CPUs  (overlap
detection)
-- Local: ovb        4 GB   12 CPUs x   1 job      4 GB   12 CPUs  (overlap
store bucketizer)
-- Local: ovs        8 GB   12 CPUs x   1 job      8 GB   12 CPUs  (overlap
store sorting)
-- Local: red       32 GB   12 CPUs x   1 job     32 GB   12 CPUs  (read
error detection)
-- Local: oea       32 GB   12 CPUs x   1 job     32 GB   12 CPUs  (overlap
error adjustment)
-- Local: bat       32 GB   12 CPUs x   1 job     32 GB   12 CPUs  (contig
construction with bogart)
-- Local: gfa        8 GB   12 CPUs x   1 job      8 GB   12 CPUs  (GFA
alignment and processing)
--
-- Found Nanopore uncorrected reads in the input files.
--
-- Generating assembly 'gut' in '/SqueezeMeta/databases/test/gut/data/canu'
--
-- Parameters:
--
--  genomeSize        5000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.3200 ( 32.00%)
--    obtOvlErrorRate 0.1200 ( 12.00%)
--    utgOvlErrorRate 0.1200 ( 12.00%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.5000 ( 50.00%)
--    obtErrorRate    0.1200 ( 12.00%)
--    utgErrorRate    0.1200 ( 12.00%)
--    cnsErrorRate    0.2000 ( 20.00%)
--
--
-- BEGIN CORRECTION
--
----------------------------------------
-- Starting command on Wed Oct 30 14:16:33 2019 with 2641.361 GB free disk
space

    cd .
    /SqueezeMeta/bin/canu/sqStoreCreate \
      -o ./gut.seqStore.BUILDING \
      -minlength 1000 \
      ./gut.seqStore.ssi \
    > ./gut.seqStore.BUILDING.err 2>&1

-- Finished on Wed Oct 30 14:16:34 2019 (one second) with 2641.348 GB free
disk space
----------------------------------------
--
-- WARNING:  Potential problems with your input reads were detected.
-- WARNING:
-- WARNING:  Please review the logging in files:
-- WARNING:
 /SqueezeMeta/databases/test/gut/data/canu/gut.seqStore.BUILDING.err
-- WARNING:
 /SqueezeMeta/databases/test/gut/data/canu/gut.seqStore.BUILDING/errorLog
-- 
-- Proceeding with assembly because stopOnReadQuality=false.
--
-- WARNING: gnuplot failed.
--
----------------------------------------
--
-- ERROR:  Read coverage (1.51) is too low to be useful.
-- ERROR:
-- ERROR:  This could be caused by an incorrect genomeSize or poor quality
reads that could not
-- ERROR:  be sufficiently corrected.
-- ERROR:
-- ERROR:  You can force Canu to continue by decreasing parameter
stopOnLowCoverage=10,
-- ERROR:  however, the quality of corrected reads and/or contiguity of
contigs will be poor.
-- 

ABORT:
ABORT: Canu 1.8
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
mv: cannot stat
'/SqueezeMeta/databases/test/gut/data/canu/gut.contigs.fasta': No such file
or directory
Error running command:    rm -r /SqueezeMeta/databases/test/gut/data/canu;
/SqueezeMeta/scripts/../bin/canu/canu  -p gut -d
/SqueezeMeta/databases/test/gut/data/canu genomeSize=5m
corOutCoverage=10000 corMhapSensitivity=high corMinCoverage=0 redMemory=32
oeaMemory=32 batMemory=32 mhapThreads=12 mmapThreads=12 ovlThreads=12
ovbThreads=12 ovsThreads=12 corThreads=12 oeaThreads=12 redThreads=12
batThreads=12 gfaThreads=12 merylThreads=12 -nanopore-raw
 /SqueezeMeta/databases/test/gut/data/raw_fastq/par1.fastq.gz;mv
/SqueezeMeta/databases/test/gu

**Comment by fpusan** [comment]
From this 
```
-- ERROR: Read coverage (1.51) is too low to be useful.
-- ERROR:
-- ERROR: This could be caused by an incorrect genomeSize or poor quality reads that could not -- ERROR: be sufficiently corrected.
-- ERROR:
-- ERROR: You can force Canu to continue by decreasing parameter stopOnLowCoverage=10,
-- ERROR: however, the quality of corrected reads and/or contiguity of contigs will be poor.
```

It seems like canu complains because your read coverage is too low.
You can pass a quoted string with whatever flag you want to canu via the `-a` parameter in SqueezeMeta.pl.

E.g.

`/SqueezeMeta/scripts/SqueezeMeta.pl -m Sequential -s test.samples -f raw/ --minion -a "stopOnLowCoverage=5"`

This can help you tune parameters if your data is difficult to assemble. However, as stated by canu's message, results might be unreliable.

**Comment by fpusan** [comment]
Edited, the flag for passing options to the assembler is `-assembly_options`, not `-a`

**Comment by kak8** [comment]
Thank you so much. Sadly, the value of 5 is also not sufficient. I may have
to put a lower value.

**Comment by jtamames** [comment]
If the assembly is not working well because of low coverage, you can always switch to analyze the reads themselves, using the sqm_reads.pl script in the utils directory of your SqueezeMeta installation
