### ISSUE TITLE
Modifying the source files to rearrange samples order in SQMtools graphs

### ISSUE THREAD

**Issue by analopezlopez** [jtamames/SqueezeMeta#390]
Hi, 

I'm using the latest version of SQMtools to obtain taxonomical, functional and pathway plots from my metagenome data. When we performed the sequencing experiments we weren't careful enough to group together some of the samples from the same cohort in barcodes one after the other and it ended up being quite messy to analyze. I tried to modify the order directly in the input files (orftable, bintable, contigtable and so on) and load the project again but I saw no change in the output charts. Would you suggest any way I could fix this?

Thank you!

Best, 
Ana

**Comment by fpusan** [comment]
Hi,

No need for that! Just pass the right order to `plotTaxonomy` when plotting.

`plotTaxonomy(SQM, samples=vector_with_sample_names_in_the_right_order)`

This should do it. You can find more info by checking the PDF manual or typing `?plotTaxonomy` in R.

Let me know if this helps,

Fernando

**Comment by analopezlopez** [comment]
Oh! I see! It did work now. 

Thank you very much,
Ana

**Comment by fpusan** [comment]
Glad it worked! Closing issue
