### ISSUE TITLE
01.run_assembly.pl. Program finished abnormally

### ISSUE THREAD

**Issue by sskoldas** [jtamames/SqueezeMeta#391]
Hello!
I have a problem at step1. I checked previous issues but I couldn't find appropriate answer. 
My datasets consist of short reads of airway microbiome (Illumine/Nextseq 550). Therefore, I decided to use spades as assembler.

I run SqueezeMeta with that command: 
 `SqueezeMeta.pl -m coassembly -p new_try -s samples_file.tsv -f /home/sskoldas/mambaforge/envs/SqueezeMeta/SqueezeMeta/samples/test -a spades -map bwa -t 5`. I got this error : **Stopping in STEP1 -> 01.run_assembly.pl. Program finished abnormally** 

How can I fix this error? 

Here I attached my syslog file.
[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/7620120/syslog.zip)

Thank you for all your help!

**Comment by fpusan** [comment]
Hi!
From the syslog

```
== Error ==  system call for: "['/home/sskoldas/mambaforge/envs/SqueezeMeta/SqueezeMeta/bin/SPAdes/spades-core', '/home/sskoldas/mambaforge/envs/SqueezeMeta/SqueezeMeta/samples/new_try/data/spades/K21/configs/config.info', '/home/sskoldas/mambaforge/envs/SqueezeMeta/SqueezeMeta/samples/new_try/data/spades/K21/configs/mda_mode.info', '/home/sskoldas/mambaforge/envs/SqueezeMeta/SqueezeMeta/samples/new_try/data/spades/K21/configs/meta_mode.info']" finished abnormally, OS return value: 2

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

SPAdes log can be found here: /home/sskoldas/mambaforge/envs/SqueezeMeta/SqueezeMeta/samples/new_try/data/spades/spades.log
```

I suspect you may have run out of memory. What does the `/home/sskoldas/mambaforge/envs/SqueezeMeta/SqueezeMeta/samples/new_try/data/spades/spades.log` say?

Also it is not a recommended practice to run your project in the SqueezeMeta installation directory (although it should be unrelated to this error).

**Comment by sskoldas** [comment]
[spades.log](https://github.com/jtamames/SqueezeMeta/files/7620224/spades.log)
Here spades.log file.

**Comment by fpusan** [comment]
Is this disk space or total RAM?

**Comment by sskoldas** [comment]
total ram is 64 gb, disk space is now 376 gb

**Comment by fpusan** [comment]
You might not have enough RAM...do you get the same issue with the test data we provide when downloading the databases? 

Also you can try using megahit instead of spades...
