### ISSUE TITLE
loadSQM needing more then 200 GB RAM

### ISSUE THREAD

**Issue by slambrechts** [jtamames/SqueezeMeta#393]
Hi,

I realize I have a pretty big dataset (43 samples), but is it possible loadSQM needs more then 200 GB RAM, or is this not normal and is there probably something wrong?

Kind regards,
Sam

**Comment by slambrechts** [comment]
ok I can close and answer this myself, I think it was normal, it maxed out at 332 GB RAM and was able to finish

**Comment by fpusan** [comment]
Glad to hear, but still it's a super high memory usage. Can I ask how many contigs/orfs were in your project? I have managed to load projects coming from similar number of samples, using much less RAM that that

**Comment by slambrechts** [comment]
Not sure yet how to check how many contigs/orfs it contains, but the SQM object in R is 186 GB in size when I save it as a .RData file

**Comment by fpusan** [comment]
Ouch, yeah it seems that your project was a big one.
