### ISSUE TITLE
-extdb question: Can a function be represented by multiple AA sequences as long as they have different IDs?

### ISSUE THREAD

**Issue by slambrechts** [jtamames/SqueezeMeta#394]
Hi,

I have a custom database (fasta file of amino acid sequences, different metabolic markers) that I would like to use with the `-extdb` option in SQM, in which the sequences have a header in the format:
`>ID|....|Function`

My question is, Can a function be represented by multiple AA sequences as long as they have different IDs? Example:

>WP_015407385.1|Dehalococcoides_mccartyi|[NiFe]_Group_1a
MQKIVIDPITRIEGHLKIEATVDGGEVKDAKCVGTLFRGFEIFMKDRDPRDAVHITQRICGVCPTSHGTTAALNLDAAFGVADKIPNNGRILRNLIQGANYIASHIVHFYHLAALDYVDVTEVADYDGTDPELLKVKDFISRALAAGDMSMLAPFYPRYEGDYRLPKKVAQAAVAHYVEALNMRRLAHELSAIYSGRMPHSVAVVAGGVTSHPSIDSISSFMSKLNTLRHFIDNVYLPDVIAVAETYPDYFGIGVGCGNLLSYGVFDLEANGTNLATRQRLFTQGTVSASDLTLHTFDPNKITEDIKYGWFKGETNEYPLNEVTEPDHTKAEGYSWLKAPRYENTPYEVGPLARMVVNYVAGDPVVQKMVNDTLAHFGAGPAALFSTLGRHAARALECKIVADEMVKWVMELKIGEPVCADYEIPESAEGMGLWEAPRGALGHWIKIENHKISNYQCVVPTTWNCSPKDGQGVYGPVEQALIGTKVRDNDNPFELVRIVRSFDPCLACAVHLVSPTGNEISRFRVY
>WP_013217520.1|Dehalogenimonas_lykanthroporepellens|[NiFe]_Group_1a
MAKIVIDPISRIEGHLKIEVVVENGVVKDAHSSGTMFRGFEIFLKGHNPTDAQHYTQRICGVCPTSHGMTAVLNLDSAFGVDDKIPDNGRIIRNLIQGANYIQSHILHFYHLAALDYVDVTAVADYSGNDAGLTKVQQFISRALAAGDYSMLGPFWPRYEGDYRLSKAINVKAVQDYVEALNMRRIAHEMSAIFSGRMPHSPALVVGGATQGPTEDNIVAFRAKLTKLRKFTDEVYIPDVIAVAEAYSDHFDQGFGTGNVLSYGVFDLDGKEKDLAKRQRFLPQGIASGLSLGTFDPQKITEDVKYGWFSSGSGYPGDTDTVDDPNKTGAYTWLKAPRYGGDVYEVGPLPRVLVAYLSGDPTAQKLVNDTLAHFGAPASALFSTLGRHAARALECKMVADAMDKWLDELKPGEPVNVTADIPDSAQGMGLWEAPRGALGHWISIKDQKIERYQCVVPSTWNCSPRDNNDQPGALEQALIGAKVKDEANPFEVVRIVRAFDPCLACAVHVVSPKGTEKGRFQIC
>WP_013218717.1|Dehalogenimonas_lykanthroporepellens|[NiFe]_Group_1a
MTRIVVDPLTRIEGHLRIEVEVENGVITDAWSAGTMARGWEKILQGRDPWDAPYVTSRVCGVCEGVHTIASNQAIEDAFGIELTEAGRLMRNLFSAGYYVHDHFIHFYVLSALDFLDIMAIASYEGSDPGLLAVKSKIVGLVSAGDTSPFTPRYTPDEFSVNDPETVTTLVSHYLKAIELKAKSQKMLSYLTGIQPHPNALMPGGCTATPSVEVLQDLRKLWQEQADFVNNVYVPDVMAVGYGPLLPLAASGFGATNGNYLAFPMLPQGGSASAGDISFGGSNPMFRGGVVKANGERASRTDISNLTVEDVDYSQITESVTYSWYDYPAGVDALHPSEGVTDFNLQKQDAYSFLKAPRYNAETMEVGPLARGMVNQFPELVDFFNAGGREGVVARHLSRAVISKQIINDGLAWIDRLIEMRLAGPLVGMNEKPVPKTGRGMGVWDAPRGALGHWIEVDNWRIKNYQMVVPSTWNAGPRDENGVKGPYEQALIGAPVPDLDNPINVVRIIRSFDPCIACAVHLIDPHTNQRKVVKVA

So in this case `[NiFe]_Group_1a` would be the function that is represented by these 3 sequences

**Comment by jtamames** [comment]
Hello
Yes of curse, indeed that is the expected usage.
Best,
J

**Comment by slambrechts** [comment]
Ok thanks, will try!
