### ISSUE TITLE
Extra column sspecifying noassemly not working

### ISSUE THREAD

**Issue by mradz19** [jtamames/SqueezeMeta#395]
I am trying to run squeezemeta on a mix of RNA and DNA samples. I don't want to do the run as "merged" as I have found the merging step takes too long to be feasible. Instead I added a fourth column to my samples file which specified noassembly,nobinning for the RNA files and completed a coassembly run. However when I look at the binning results I can see that the RNA files were still used for binning and I'm assuming coassembly as well. Do I need to have quotation marks around nobinning,noassembly?

**Comment by jtamames** [comment]
Hello
Quotes should not be neccesary. Coud you send me the syslog file, please?
Thanks!

**Comment by mradz19** [comment]
[syslog.txt](https://github.com/jtamames/SqueezeMeta/files/7656785/syslog.txt)
Syslog file attached

**Comment by mradz19** [comment]
Also, if I was to try a merged run would it be possibly to specify that the RNA samples be assembled with RNAspades and the DNA samples with spades?

**Comment by jtamames** [comment]
No, it is not possible right now (but I take note of that for future versions). You can do the assemblies of DNA and RNA separately (running them as separate projects, coassembly mode, stopping after step 1 with the option `-test 1`) , then add the resulting fasta files to the intermediate directory (renaming them as 01.dna.dasta and 01.rna.fasta), and then run `01.mergeassemblies.pl`. Then restart in step 2.
Best,
Javier

**Comment by mradz19** [comment]
I had considered that, would that be a viable method for comparing metatranscriptomes and metagenomes from the same samples?

**Comment by jtamames** [comment]
Yes indeed, you can find an example of a similar approach in the wiki.

**Comment by mradz19** [comment]
Yes I did look at that wiki. I just wasn't too keen on using spades or megahit for the RNA data. Just to clarify, what intermeidate folder should I add the two assemblies to? Just pick one of the projects? Or should I start a new project directory?

**Comment by mradz19** [comment]
Ok  I ran two separate projects for the initial assembly. I then moved one of the assembly .fasta files from the results directory of both projects into the intermediate directory of the first project and ran the mergeassemblies script. That has now finished, where would the merged assembly be? I can find any newly generated files in any of the directories

**Comment by mradz19** [comment]
I tried restarting from step 16 and this is the error I get:

```
[0 seconds]: STEP16 -> DAS_TOOL MERGING: 16.dastool.pl
mkdir: cannot create directory ‘/kusers/ancillary/mradzieta/squeezemeta/bone/bone_dna/results/DAS’: File exists
Error: package or namespace load failed for ‘ggplot2’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/kusers/ancillary/mradzieta/R/x86_64-redhat-linux-gnu-library/4.0/rlang/libs/rlang.so':
  /kusers/ancillary/mradzieta/R/x86_64-redhat-linux-gnu-library/4.0/rlang/libs/rlang.so: undefined symbol: R_removeVarFromFrame
In addition: Warning messages:
1: package ‘foreach’ was built under R version 4.0.5 
2: package ‘iterators’ was built under R version 4.0.5 
3: package ‘ggplot2’ was built under R version 4.0.5 
Execution halted
Can't open /kusers/ancillary/mradzieta/squeezemeta/bone/bone_dna/results/DAS/bone_dna_DASTool_bins directory
```

**Comment by jtamames** [comment]
Hello
It looks like DASTool is not properly installed. Did you run the test_install script?

**Comment by mradz19** [comment]
Yes I did test_install did not find any issues

**Comment by mradz19** [comment]
Hi @jtamames, after merging where would I find the merged assambly fasta? I was thinking it might just be easier to start a new run and use that as an extassembly

**Comment by mradz19** [comment]
Also I believe the error in step 16 is due to ggplot2 not being able to be loaded in the squeezemeta conda environment for some reason

**Comment by jtamames** [comment]
Hello!
The merged assambly fasta should be in the results directory, with the name 01.projectname.fasta
Regarding step 16 and ggplot2, let's see if @fpusan has any ideas.
Best,
J

**Comment by mradz19** [comment]
And thanks for that I will use that as an external assembly. Just for anyone in future working with RNA and DNA reads together. I got better mapping percentages when assembling the DNA and RNA reads separately with spades and rnaspades, respectively, then merging them with minimus compared to when I assembled all reads together using spades or megahit as the assembler.
