### ISSUE TITLE
Problem with sqmreads2tables.py

### ISSUE THREAD

**Issue by sskoldas** [jtamames/SqueezeMeta#397]
Hi!

I run this command `sqmreads2tables.py /home/sskoldas/samples/sqmreads Read_Tables` 
It gave me this error :
`Traceback (most recent call last):
  File "/home/sskoldas/mambaforge/envs/SqueezeMeta/bin/sqmreads2tables.py", line 252, in <module>
    main(parse_args())
  File "/home/sskoldas/mambaforge/envs/SqueezeMeta/bin/sqmreads2tables.py", line 71, in main
    samples[sample] += int(total_reads)
ValueError: invalid literal for int() with base 10: '7728346.75'` 

How can I handle it?  Can I change the integer value?
Thank you for help!

**Comment by fpusan** [comment]
Hi!
I see that you closed it. What had happened?

**Comment by sskoldas** [comment]
I change the float number to the integer, then it worked.

**Comment by fpusan** [comment]
It's weird that a float was there...
Just in case, can you share your `*.out.mappingstat` file with us? It should be in the `sqmreads` directory.

**Comment by sskoldas** [comment]
[sqmreads.out.zip](https://github.com/jtamames/SqueezeMeta/files/7663023/sqmreads.out.zip)

**Comment by fpusan** [comment]
Hm, indeed there is a float, the number seems otherwise reasonable...
@jtamames any idea?

**Comment by jtamames** [comment]
Very weird, this line counting is done via the grep command, that should not return a float

**Comment by fpusan** [comment]
Hi, just noticed that this was still open. @sskoldas any chance that you can share the input fastq files and the command you used to run `sqmreads.pl` with us?
