### ISSUE TITLE
SqueezeMeta/lib/SQMtools installation issue

### ISSUE THREAD

**Issue by aalkin2001** [jtamames/SqueezeMeta#399]
Hi, 
I am trying to install the Sequeezemeta tool on a remote server, but when I ran this command "sudo R CMD INSTALL <installpath>/SqueezeMeta/lib/SQMtools", it produces an this error: 
* installing to library ‘/usr/local/lib/R/site-library’
Error: ERROR: no permission to install to directory ‘/usr/local/lib/R/site-library’.

Also, I tried to test that all the dependencies can be located in this environment, and I got these errors:
WARNING: Some SqueezeMeta dependencies could not be found in your environment!
	- Missing R library "pathview"
	- Missing R library "SQMtools"

I am a novice in all these. Could you please advice on possible solutions.
Thank you.

**Comment by fpusan** [comment]
Hi!

Do you have admin access to that computer? It seems that you don't have write permissions in that directory.

Alternatively, you can remove the "sudo" and it will install locally. It will not be available for other users but maybe that's not a problem.

Finallt can try with the conda version, which does not require admin privileges.

**Comment by aalkin2001** [comment]
Thanks for your reply. Yes, I do have permission to write on the directory. I tried it again and I got the below response:
* installing to library ‘/usr/local/lib/R/site-library’
ERROR: dependency ‘pathview’ is not available for package ‘SQMtools’
* removing ‘/usr/local/lib/R/site-library/SQMtools’

**Comment by fpusan** [comment]
Oh, ok. It seems like you need to install pathview before.

**Comment by aalkin2001** [comment]
Here are all my trials and responses:

* installing *source* package ‘openssl’ ...
** package ‘openssl’ successfully unpacked and MD5 sums checked
** using staged installation
Using PKG_CFLAGS=
--------------------------- [ANTICONF] --------------------------------
Configuration failed because openssl was not found. Try installing:
 * deb: libssl-dev (Debian, Ubuntu, etc)
 * rpm: openssl-devel (Fedora, CentOS, RHEL)
 * csw: libssl_dev (Solaris)
 * brew: openssl@1.1 (Mac OSX)
If openssl is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a openssl.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
-------------------------- [ERROR MESSAGE] ---------------------------
tools/version.c:1:10: fatal error: openssl/opensslv.h: No such file or directory
    1 | #include <openssl/opensslv.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
--------------------------------------------------------------------
ERROR: configuration failed for package ‘openssl’
* removing ‘/usr/local/lib/R/site-library/openssl’
ERROR: dependency ‘openssl’ is not available for package ‘httr’
* removing ‘/usr/local/lib/R/site-library/httr’
ERROR: dependency ‘httr’ is not available for package ‘KEGGREST’
* removing ‘/usr/local/lib/R/site-library/KEGGREST’
ERROR: dependency ‘KEGGREST’ is not available for package ‘pathview’
* removing ‘/usr/local/lib/R/site-library/pathview’

The downloaded source packages are in
	‘/tmp/Rtmp2ESQ8a/downloaded_packages’
Old packages: 'RSQLite'
Update all/some/none? [a/s/n]: n
Warning messages:
1: In .inet_warning(msg) :
  installation of package ‘openssl’ had non-zero exit status
2: In .inet_warning(msg) :
  installation of package ‘httr’ had non-zero exit status
3: In .inet_warning(msg) :
  installation of package ‘KEGGREST’ had non-zero exit status
4: In .inet_warning(msg) :
  installation of package ‘pathview’ had non-zero exit status
> install.packages("libssl-dev")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Warning message:
package ‘libssl-dev’ is not available (for R version 3.6.3)

**Comment by fpusan** [comment]
```
Configuration failed because openssl was not found. Try installing:
deb: libssl-dev (Debian, Ubuntu, etc)
rpm: openssl-devel (Fedora, CentOS, RHEL)
csw: libssl_dev (Solaris)
brew: openssl@1.1 (Mac OSX)
```
What is your OS/distribution? It seems like openssl is missing from your system. You can try installing it as indicated in the message. 

I'd recommend you to use the conda version of SqueezeMeta instead. Hopefully it should work out of the box for you.

**Comment by aalkin2001** [comment]
Thank you so much for your reply. I will go with the conda version as suggested.
