### ISSUE TITLE
Is it possible to run 04.rundiamond.pl only with external databases? 

### ISSUE THREAD

**Issue by slambrechts** [jtamames/SqueezeMeta#400]
Hi,

I was wondering whether it's possible to use `04.rundiamond.pl` with `-extdb` without also (re)running diamond on the standard databases? If I understood the manual correctly, that is currently not possible? Or is it?

To clarify, I have a finished SQM project, but I would like to run  `04.rundiamond.pl` with `-extdb` to add diamond results from a few custom databases.

Also, if you would rerun `04.rundiamond.pl`, what steps further down the pipeline do you also have to rerun to get a finished SQM project again?

**Comment by jtamames** [comment]
Hello
Not directly. But you can do the following:
-Edit the SqueezeMeta_conf.pl file in the project directory. Set variables $nocog and $nokegg to 1, and add your new database:
```
$nocog           = 1;
$nokegg          = 1;
$nopfam          = 1;
$opt_db           ="/path/to/db/listfile"
```
This listfile is the file specified in the documentation where you specify the name and location of your new databases.
Then run script 04 like:

`04.rundiamond.pl <project name> 1`

That '1' at the end will make it skip the taxonomic annotation. When it finishes, restart the SqueezeMeta_conf.pl to original values (but keeping the $opt_db that you added). Then you should rerun scripts 07, 12, 13, and 22 to add the new results to existing ones.
Best,
Javier

**Comment by slambrechts** [comment]
Ok great, thank you! Will try and report back

**Comment by slambrechts** [comment]
Ok this worked, thanks! 

If I now rerun `sqm2tables.py`, will SQM only add the table(s) for the new external database, or will it regenerate all the tables?

I'm asking because previously generating the tables for my project took up to 332 GB RAM, and I have to take care not to crash the server :)

**Comment by fpusan** [comment]
I think that the RAM consumption will occur when loading the project into `SQMtools`, rather than when running `sqm2tables.py`. `SQMtools` will try to create the tables if it doesn't find them but you can just create them beforehand.
`sqm2tables.py /path/to/project /path/to/project/results/tables`.

**Comment by slambrechts** [comment]
For me it does not seem to make a difference, I just ran `sqm2tables.py`, and like last time RAM consumption gradually increased over the course of 3 hours or something to around 330 GB.

**Comment by jtamames** [comment]
Next release 1.5, expected in a few days, will include the `add_database.pl `script that will automatize the addition of a new database to an existing project, according to the recipe given above.
Best,
Javier

**Comment by slambrechts** [comment]
That's great, thanks!
