### ISSUE TITLE
How to use SQMtools on linux rstudio

### ISSUE THREAD

**Issue by agg437** [jtamames/SqueezeMeta#405]
Hi,

I was exploring  the results of SqueezeMeta with SQMtools and I was wandering if it would be possible to use the package in linux rstudio. I saw the post about windows but it would be really nice to have the same with linux.

Best regards,
Ana

**Comment by fpusan** [comment]
I'm pretty sure it can be done, but you might need to install the package
and the dependencies manually.

**Comment by agg437** [comment]
Hello again,
After making some proofs I found that it is possible to use rstudio on linux following these steps:
1) Install rstudio (whichever r version you wish, that will be the default one rstudio use unless you say otherwise)
2) Activate Squeezemeta environment with conda 
3) Type rstudio in terminal. Rstudio will open with r version and packages from squeezemeta environment.

Unfortunately, this only work with Rstudio installation and not Rstudio server, but still, it is really helpful. In case someone else need it.
Best regards,
Ana

**Comment by fpusan** [comment]
Thanks for the input!
