### ISSUE TITLE
configuration issue samples not found

### ISSUE THREAD

**Issue by soilmicrobiome** [jtamames/SqueezeMeta#409]
I am running on a HPC with version 1.4.0 (just a side note - i could not install 1.5.0 as it got stuck trying to resolve the environment with conda).  I have run test_install.pl and everything is validated.  I have also check that the test samples work. 

When it comes to my own samples however i get the error
"Can't open samples file (-s) in test.samples. Please check that it is the correct file"

I am running as:
SqueezeMeta.pl -m merged -p lakes -s sampleids.samples -f /scratch/user/lake/rawreads/ -cleaning -cleaning_options "LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36" -t 24 -b 18

i created the sampleids.samples file using vim and made sure that i have tabs.  I also used dos2unix on my sample id file and i still get the same error. 

Here is what the sample file looks like:

M1  M1_Combined_R1.fastq.gz     pair1
M1  M1_Combined_R1.fastq.gz     pair2
T1 T1_R1.fastq.gz pair1
T1 T1_R1.fastq.gz pair2
T2 T2_R1.fastq.gz pair1
T2 T2_R2.fastq.gz pair2

Or do you think its the actual files?  I have checked that they transferred correctly (correct size, not corrupted)

Any thoughts much appreciated.

**Comment by fpusan** [comment]
Regarding the installation of version 1.5, have you tried using mamba?
```
conda install -c conda-forge mamba
mamba create -n SqueezeMeta -c conda-forge -c bioconda -c fpusan squeezemeta
```
Regarding the issue with the samples file
```
 "Can't open samples file (-s) in test.samples. Please check that it is the correct file"
```
SqueezeMeta seems to think that your samples file is named `test.samples`. We normally don't have issues with that. You sure you put the right name when running the command?

**Comment by soilmicrobiome** [comment]
forgot about mamba - i'll try that thanks!

my directory looks like this:
```
drwxrws--- 2 user-rw 4.0K Jan  8 11:20 rawreads
-rw-rw---- 1 user-rw  254 Jan  8 11:18 sampleids.samples
-rw-rw---- 1 suer-rw  365 Jan  8 11:17 squeezemeta.sh
```

and my .sh file looks like this:
```
#!/bin/bash
#PBS -l walltime=71:00:00,select=1:ncpus=24:mem=6gb
#PBS -N logfile
#PBS -A user

module load miniconda3
source activate /home/user/squeezemeta_v140/
SqueezeMeta.pl -m merged -p lakes -s sampleids.samples -f /scratch/user/lake/rawreads/ -cleaning -cleaning_options "LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36" -t 24 -b 18
```

Then i get this when i try to run it:
`Can't open samples file (-s) in sampleids.samples. Please check that it is the correct file`

I had posted an old logfile output above with the `test.samples` (i have been trying a bunch of different ways to get it to run, including copying the test.samples file and replacing with my sample names).

**Comment by soilmicrobiome** [comment]
Contacted the HPC admin - i had missed adding `cd $PBS_O_WORKDIR` to my .sh file

it was trying to locate to to a my home directory not scratch (where my files are).  Hence it could not find the samples. 

Sorry!  but thanks for the help!

**Comment by fpusan** [comment]
Glad to hear. Closing issue

**Comment by jtamames** [comment]
Also, notice that you are specifying thew same name for pair1 and pair2 files:
```
M1 M1_Combined_R1.fastq.gz pair1
M1 M1_Combined_R1.fastq.gz pair2

```
In case that you have a single reads file for a sample, just list it once as 'pair1'. I assume that you did it because you have a mixture of single and paired reads (sample T2 seems to be paired), but merged mode should work fine.
Best,
J

**Comment by soilmicrobiome** [comment]
yip correct.  thanks for pointing that out.
