### ISSUE TITLE
Conda stuck solving environment when installing v1.5

### ISSUE THREAD

**Issue by fpusan** [jtamames/SqueezeMeta#410]
If this happens, just use mamba instead of conda to create the environment (I use it for everything nowadays, so I didn't notice the problems with the original conda command). Mamba is much faster replacement for conda, and should solve the environment in less than a minute.

```
# Install mamba in your base conda environment
conda install -c conda-forge mamba
# Then use the mamba command as you would use the conda command
mamba create -n SqueezeMeta -c conda-forge -c bioconda -c fpusan squeezemeta
```
I will make a post-release with updated installation instructions sometime this weekend.

**Comment by bresyd** [comment]
Hi,

thanks for putting that info out upfront. I have the problem you are mentioning, that conda gets stuck while solving the environment. I then tried using mamba as you suggested but then I am getting the following error:
```
mamba create -n SqueezeMeta_1.5.0 -c conda-forge -c bioconda -c fpusan squeezemeta

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        Supported by @QuantStack

        GitHub:  https://github.com/QuantStack/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

Getting  conda-forge linux-64
Getting  conda-forge noarch
Getting  bioconda linux-64
Getting  bioconda noarch
Getting  fpusan Getting  fpusanlinux-64
 noarch
Getting  Getting  pkgs/main linux-64pkgs/main
 noarch
Getting  pkgs/r linux-64
Getting  pkgs/r noarch

Looking for: [u'squeezemeta']

78855 packages in https://conda.anaconda.org/conda-forge/noarch
234422 packages in https://conda.anaconda.org/conda-forge/linux-64
40153 packages in https://conda.anaconda.org/bioconda/linux-64
33963 packages in https://conda.anaconda.org/bioconda/noarch
23775 packages in https://repo.anaconda.com/pkgs/main/linux-64
5025 packages in https://repo.anaconda.com/pkgs/r/noarch
4550 packages in https://repo.anaconda.com/pkgs/main/noarch
6637 packages in https://repo.anaconda.com/pkgs/r/linux-64
6 packages in https://conda.anaconda.org/fpusan/linux-64
17 packages in https://conda.anaconda.org/fpusan/noarch

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/btschits/miniconda3/lib/python2.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/btschits/miniconda3/lib/python2.7/site-packages/mamba/mamba.py", line 522, in exception_converter
        raise e
    RuntimeError: Did not find key as expected!

`$ /home/btschits/miniconda3/condabin/mamba create -n SqueezeMeta_1.5.0 -c conda-forge -c bioconda -c fpusan squeezemeta`

  environment variables:
                ALL_PROXY=<set>
                 CIO_TEST=<not set>
                CONDA_EXE=/home/btschits/miniconda3/bin/conda
         CONDA_PYTHON_EXE=/home/btschits/miniconda3/bin/python
               CONDA_ROOT=/home/btschits/miniconda3
              CONDA_SHLVL=0
                FTP_PROXY=<set>
              HTTPS_PROXY=<set>
               HTTP_PROXY=<set>
           LD_LIRARY_PATH=/home/btschits/lib/
                  MANPATH=:/opt/puppetlabs/puppet/share/man:/home/btschits/bin
                     PATH=/home/btschits/apps:/home/btschits/apps/Prodigal-2.6.3:/home/btschits/
                          usr/bin:/home/btschits/apps/perl-5.30.1:/home/btschits/bin:/home/btsch
                          its/apps/MUMmer3.23:/home/btschits/perl5/bin:/home/btschits/.local/bin
                          :/home/btschits/miniconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/
                          local/games:/usr/games:/opt/puppetlabs/bin:/home/btschits/bin:/home/bt
                          schits/apps/ncbi-blast-2.9.0+/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
                all_proxy=<set>
                ftp_proxy=<set>
               http_proxy=<set>
              https_proxy=<set>
                 no_proxy=<set>

     active environment : None
            shell level : 0
       user config file : /home/btschits/.condarc
 populated config files : /home/btschits/.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 2.7.16.final.0
       virtual packages : __glibc=2.24
       base environment : /home/btschits/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/fpusan/linux-64
                          https://conda.anaconda.org/fpusan/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/btschits/miniconda3/pkgs
                          /home/btschits/.conda/pkgs
       envs directories : /home/btschits/miniconda3/envs
                          /home/btschits/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.24.0 CPython/2.7.16 Linux/4.9.0-13-amd64 debian/9.13 glibc/2.24
                UID:GID : 60785:1120
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

```
Do you have any idea about what might go wrong here?

Thanks again and of course also thanks for making the new release available. Having concoct integrated as additional binning tool is fantastic.

cheers

**Comment by fpusan** [comment]
By any chance are you using miniconda2 instead of miniconda3? 

https://github.com/mamba-org/mamba/issues/640

**Comment by fpusan** [comment]
`File "/home/btschits/miniconda3/lib/python2.7/site-packages/conda/exceptions.py", line 1079, in __call__`

Ok apparently you are using miniconda3 BUT somehow it is using python 2 instead of 3, so I still believe it might be related. Can you try again in a fresh miniconda3 install?

**Comment by bresyd** [comment]
thanks for your response.
I will give it a try with a fresh miniconda3 installation and let you know how it goes.

**Comment by fpusan** [comment]
There is a problem with your conda/mamba installation.
https://github.com/mamba-org/mamba/issues/512
https://github.com/mamba-org/mamba/issues/947
According to the devs some causes might be mamba being installed in an environment different from the base environment, or `/tmp` being full.
It's probably better if check this and try again in a clean miniconda3 + mamba install.

**Comment by bresyd** [comment]
Hi,

sorry for getting back to you so late on that issue
I noticed that I screwed up my conda base env a while back when I made the mistake and installed a package into base requiring python 2.7. 
So I did a fresh miniconda3 installation as you suggested and then installed SqueezeMeta_1.5.0 using Mamba and everything worked fine. One thing I noticed was that the first fresh miniconda3 installation I did was using the latest version available, which had python 3.9. However, using that version I always ended up with error messages when trying to install mamba (or any package for that matter) in the base env. Only when I installed miniconda3 with python 3.7 I was able to install Mamba. 

Thanks again for your help.

cheers

**Comment by fpusan** [comment]
Hm, the problem with the latest version of miniconda seems weird, but if it happens with all the packages I'll let the conda guys figure it out :P. Glad that it's working for you!

**Comment by blostein** [comment]
Hey! I've use SqueezeMeta before but installed it a while ago (version 1.4.0). I was trying to reinstall using mamba to get the newest version.
When I run mamba create -n SqueezeMeta1.5 -c conda-forge -c bioconda -c fpusan squeezemeta, I successfully get version 1.4.0 again. 
While listing pacakges to install, mamba prints out squeezemeta 1.4.0  pl526r36_0           fpusan/noarch            Cached. Also the VERSION file lists 1.4.0

So I tried  mamba create -n SqueezeMeta1.5 -c conda-forge -c bioconda -c fpusan squeezemeta=1.5.1 but get "Encountered problems while solving:
  - nothing provides mkl 2019.1.* needed by libblas-3.8.0-4_mkl"
I'm using python 3.7, mamba 0.22.1
