### ISSUE TITLE
Squeezmeta unable to find R packages

### ISSUE THREAD

**Issue by mradz19** [jtamames/SqueezeMeta#411]
I did a fresh install of SqueezeMeta v1.5 using conda but running test.install.pl fails to find ggplot2, reshape2 and pathview. When I go into R and look at .libpaths() I see that the env library path for squeezemeta is second, if I prioritise that within R it will load these packages, but it only works within the session. Once I quit and test the install it will again fail to find the packages. 

Do you have any advice with this?

**Comment by fpusan** [comment]
Hm, I can not reproduce it in my system. Was it working for you in 1.4? I didn't change anything in the conda recipe that was related to R.

Does it work if you install 1.4  in a fresh environment?

What do you see when you run `.libpaths()` at startup?

Anyways I think you can try editing the `/path/to/miniconda3/envs/SqueezeMeta/lib/R/library/base/R/Rprofile` to make the fix permanent for your environment.

**Comment by fpusan** [comment]
Just a guess... do you have some sort of `RProfile` at your home dir that is somehow overriding conda's?
What do you get when you type `file.path(Sys.getenv("HOME"), ".Rprofile")`?
What is the content of that file?

**Comment by mradz19** [comment]
Hi, this is the content of that file:

```
>file.path(Sys.getenv("HOME"), ".Rprofile")
[1] "/kusers/ancillary/mradzieta/.Rprofile"
```

**Comment by fpusan** [comment]
And what is the content of `/kusers/ancillary/mradzieta/.Rprofile`?

**Comment by mradz19** [comment]
Sorry how do I access that to look at the contents?

**Comment by fpusan** [comment]
`cat /kusers/ancillary/mradzieta/.Rprofile`

**Comment by mradz19** [comment]
Ok for some reason it isnt finding the file:

```
(squeezemeta) [mradzieta@sc-prod-01 ~]$ cat /kusers/ancillary/mradzieta/.Rprofile
cat: /kusers/ancillary/mradzieta/.Rprofile: No such file or directory
```
This is the content of the directory:

```
(squeezemeta) [mradzieta@sc-prod-01 ~]$ ls -a
.   10.bone_project.mappingstat         anaconda3      .bash_logout   .bashrc  bdmi    .conda   dataDrive   .python_history  .Renviron  spades_2.rds  syslog
..  20.bone_project_spades.contigtable  .bash_history  .bash_profile  bbmap    .cache  .config  .gitconfig  R                Rpackages  squeezemeta   .wget-hsts
```

There is an Renviron file present which contains this:

```
#R_LIBS=/kusers/ancillary/mradzieta/Rpackages
R_LIBS=/kusers/ancillary/mradzieta/R/x86_64-redhat-linux-gnu-library/4.0
```

**Comment by mradz19** [comment]
Also this is what I see when for .libPaths() when starting R:
```
> .libPaths()
[1] "/kusers/ancillary/mradzieta/R/x86_64-redhat-linux-gnu-library/4.0"
[2] "/data/mradzieta/anaconda3/envs/squeezemeta/lib/R/library"
```

**Comment by mradz19** [comment]
Ok, so within the Renviron file I changed it to:
```
R_LIBS=/data/mradzieta/anaconda3/envs/squeezemeta/lib/R/library
```

Doing so, squeezemeta can now find ggplot and reshape but not pathview

**Comment by mradz19** [comment]
Ok I reinstalled pathview and it is now all working. It seems like the .Renviron file specifying the home library was stopping squeezemeta from finding the packages.

**Comment by fpusan** [comment]
Ok, glad to hear it now works. This is more of a conda issue than a SqueezeMeta issue, as conda's R should not use configuration files outside the environment (or at least it should prioritize its own packages!). I'll look around and see if there's an easy way to make it enforce this
