### ISSUE TITLE
Missing R libs after default install of 1.5.0

### ISSUE THREAD

**Issue by nucleoli2** [jtamames/SqueezeMeta#412]
Coming up on version 1.5.0
Installed with conda/mamba on anaconda3; install was quick;  no error messages or warnings seen.   

(fyi: mamba fails for me on anaconda2 without prior warning/doc. presumed anaconda2 not supported by something... not a critical issue for me.)

Successfully downloaded/configured latest databases from your server using the SqueezeMeta 1.5.0 database install script from within the created 1.5.0 conda environment.

test_install.pl reports that none of the needed R libraries are installed (see below)... or did I miss needed additional config instructions along the way?  

As expected, 15.dastool.pl fails for the Hadza test dataset.

Attempted to use R to see if I could manually import the missing libs, but R fails to start.

From within the squeezemeta 1.5.0 conda environment (called SQM150), typing "R" as a command gives this message (edited for brevity):

~/anaconda3/envs/SQM150/lib/R/bin/exec/R: symbol lookup error: ~/anaconda3/envs/SQM150/lib/R/bin/exec/../../lib/../../libreadline.so.8: undefined symbol: tputs

This exact message is emitted from 15.dastool.pl when running the Hadza test dataset.

This exact message is also the response to the command "R -g Tk &".

The commands "R -h" and "R --help" gives the usual/expected R "help" text.

Recommended path forward?

Thanks!

Output from:   test_install.pl

Checking the OS
        linux OK

Checking that tree is installed
        tree --help OK

Checking that ruby is installed
        ruby -h OK

Checking that java is installed
        java -h OK

Checking that all the required perl libraries are available in this environment
        perl -e 'use Term::ANSIColor' OK
        perl -e 'use DBI' OK
        perl -e 'use DBD::SQLite::Constants' OK
        perl -e 'use Time::Seconds' OK
        perl -e 'use Tie::IxHash' OK
        perl -e 'use Linux::MemInfo' OK
        perl -e 'use Getopt::Long' OK
        perl -e 'use File::Basename' OK
        perl -e 'use DBD::SQLite' OK
        perl -e 'use Data::Dumper' OK
        perl -e 'use Cwd' OK
        perl -e 'use XML::LibXML' OK
        perl -e 'use XML::Parser' OK
        perl -e 'use Term::ANSIColor' OK

Checking that all the required python libraries are available in this environment
        python3 -h OK
        python3 -c 'import numpy' OK
        python3 -c 'import scipy' OK
        python3 -c 'import matplotlib' OK
        python3 -c 'import dendropy' OK
        python3 -c 'import pysam' OK
        python3 -c 'import Bio.Seq' OK
        python3 -c 'import pandas' OK
        python3 -c 'import sklearn' OK
        python3 -c 'import nose' OK
        python3 -c 'import cython' OK
        python3 -c 'import future' OK

Checking that all the required R libraries are available in this environment
        R -h OK
        R -e 'library(doMC)' NOT OK
                Missing R library "doMC"
        R -e 'library(ggplot2)' NOT OK
                Missing R library "ggplot2"
        R -e 'library(data.table)' NOT OK
                Missing R library "data.table"
        R -e 'library(reshape2)' NOT OK
                Missing R library "reshape2"
        R -e 'library(pathview)' NOT OK
                Missing R library "pathview"
        R -e 'library(DASTool)' NOT OK
                Missing R library "DASTool"
        R -e 'library(SQMtools)' NOT OK
                Missing R library "SQMtools"

Checking that SqueezeMeta is properly configured... checking database in ~/SqueezeMeta150_Databases/db
        nr.db OK
        CheckM manifest OK
        LCA_tax DB OK

------------------------------------------------------------------------------

WARNING: Some SqueezeMeta dependencies could not be found in your environment!
        - Missing R library "doMC"
        - Missing R library "ggplot2"
        - Missing R library "data.table"
        - Missing R library "reshape2"
        - Missing R library "pathview"
        - Missing R library "DASTool"
        - Missing R library "SQMtools"

**Comment by fpusan** [comment]
Does explicitly installing readline in your environments fix the issue? 
`conda install -c anaconda readline`

**Comment by nucleoli2** [comment]
After a conda fumble (below), YES, after installing readline R starts as expected (command line and Tk). 
 
test_install.pl still shows one missing R library:  pathview (below).  

Hadza now runs to completion without warnings or errors.

Many thanks for your quick response.

Best Regards.


----------------------------------------------------------
fyi:  conda 4.11.0
Conda naivete:  did the conda install outside of the Squeezemeta 1.5.0 environment...  conda installs readline...  but no behavior change inside the environment.  Repeated conda readline install inside the 1.5.0 environment... conda updates the certificate...  R now starts as expected for command line and Tk.
------------
test_install.pl after readline install in 1.5.0 conda environment:

Checking the OS
        linux OK

Checking that tree is installed
        tree --help OK

Checking that ruby is installed
        ruby -h OK

Checking that java is installed
        java -h OK

Checking that all the required perl libraries are available in this environment
        perl -e 'use Term::ANSIColor' OK
        perl -e 'use DBI' OK
        perl -e 'use DBD::SQLite::Constants' OK
        perl -e 'use Time::Seconds' OK
        perl -e 'use Tie::IxHash' OK
        perl -e 'use Linux::MemInfo' OK
        perl -e 'use Getopt::Long' OK
        perl -e 'use File::Basename' OK
        perl -e 'use DBD::SQLite' OK
        perl -e 'use Data::Dumper' OK
        perl -e 'use Cwd' OK
        perl -e 'use XML::LibXML' OK
        perl -e 'use XML::Parser' OK
        perl -e 'use Term::ANSIColor' OK

Checking that all the required python libraries are available in this environment
        python3 -h OK
        python3 -c 'import numpy' OK
        python3 -c 'import scipy' OK
        python3 -c 'import matplotlib' OK
        python3 -c 'import dendropy' OK
        python3 -c 'import pysam' OK
        python3 -c 'import Bio.Seq' OK
        python3 -c 'import pandas' OK
        python3 -c 'import sklearn' OK
        python3 -c 'import nose' OK
        python3 -c 'import cython' OK
        python3 -c 'import future' OK

Checking that all the required R libraries are available in this environment
        R -h OK
        R -e 'library(doMC)' OK
        R -e 'library(ggplot2)' OK
        R -e 'library(data.table)' OK
        R -e 'library(reshape2)' OK
        R -e 'library(pathview)' NOT OK
                Missing R library "pathview"
        R -e 'library(DASTool)' OK
        R -e 'library(SQMtools)' OK

Checking that SqueezeMeta is properly configured... checking database in /bio1/cer/SqueezeMeta150_Databases/db
        nr.db OK
        CheckM manifest OK
        LCA_tax DB OK

------------------------------------------------------------------------------

WARNING: Some SqueezeMeta dependencies could not be found in your environment!
        - Missing R library "pathview"

**Comment by fpusan** [comment]
Glad it worked. I will be explicit about installing readline in the conda recipe

**Comment by SanshiroTakahashi** [comment]
Mamba create -n SqueezeMeta -c conda-forge -c bioconda -c fpusan squeezemeta
conda activate SqueezeMeta
download_databases.pl /path/to/store/databases
test_install

The manual does not describe the differences or the reasons for them.
Doing this seems to solve the problem.
They say that any exchange that cannot be resolved above is pointless.
