### ISSUE TITLE
Issue installing SqueezeMeta databases using download_databases.pl

### ISSUE THREAD

**Issue by analopezlopez** [jtamames/SqueezeMeta#414]
Hi!

I erased the SqueezeMeta environment by mistake when I was trying to upgrade to the v 1.5.0 and had to install everything from scratch. Everything went ok but I'm having some troubles with the databases download process. I'm using the `download_databases.pl` recommended option but it gets stuck at some point and crashes. 

> kg/phylo_modelEcOyPk.json
> db/genome_tree/genome_tree_reduced.refpkg/
> db/genome_tree/genome_tree_reduced.refpkg/CONTENTS.json
> db/genome_tree/genome_tree_reduced.refpkg/genome_tree.tre
> db/genome_tree/genome_tree_reduced.refpkg/genome_tree.log
> db/genome_tree/genome_tree_reduced.refpkg/genome_tree.fasta
> db/genome_tree/genome_tree_reduced.refpkg/phylo_modelJqWx6_.json
> db/genome_tree/genome_tree.taxonomy.tsv
> db/genome_tree/genome_tree.metadata.tsv
> db/genome_tree/genome_tree.derep.txt
> db/genome_tree/missing_duplicate_genes_97.tsv
> db/arc.all.faa
> db/euk.hmm
> db/taxon_marker_sets.tsv
> db/arc.hmm
> db/hmms/
> db/hmms/checkm.hmm.ssi
> db/hmms/phylo.hmm.ssi
> db/hmms/phylo.hmm
> db/hmms/checkm.hmm
> db/bac.scg.faa
> db/selected_marker_sets.tsv
> db/arc.scg.lookup
> db/hmms_ssu/
> db/hmms_ssu/createHMMs.py
> db/hmms_ssu/SSU_archaea.hmm
> db/hmms_ssu/SSU_euk.hmm
> db/hmms_ssu/SSU_bacteria.hmm
> db/marker.hmm
> db/ReadMe
> db/.dmanifest
> db/bac.all.faa
> db/bacar_marker.hmm
> db/bac.hmm
> db/silva.nr_v132.align.md5
> db/silva.nr_v132.align
> db/silva.nr_v132.tax.md5
> db/silva.nr_v132.tax
> db/kegg.db.md5
> db/keggdb.dmnd
> db/nr.dmnd
> packet_write_wait: Connection to 89.44.250.83 port 22: Broken pipe

I had a strong connection throughout the whole process, tried a couple of times but it always stops at the same step. Could you give me any hints on what could be going wrong?

Thanks. 
Best, 
Ana

**Comment by fpusan** [comment]
I think your ssh connection to uppmax is dying. Try running the command with `nohup`.

**Comment by analopezlopez** [comment]
Thanks! I'm already on it. 

One quick question though, since the process is now running in the background, how can you check if it has finished correctly?

**Comment by fpusan** [comment]
it should be writing the output to a file named `nohup.out` by default. If it gets to the end without errors and says something like "Updating configuration.. Done" then it should be fine. You can also check that `test_install.pl` reports no errors.

**Comment by analopezlopez** [comment]
I'm afraid it didn't work... I `run test_install.pl ` and it says:

WARNING: Some SqueezeMeta dependencies could not be found in your environment!
	- Missing R library "pathview"
	- Databases were not installed, or are not configured in this installation of SqueezeMeta

Also, I checked the `nohup.out` file and the last row looks like this: 

149817750K .......... ....                                       100% 84,0M=1h52m
2022-01-18 15:33:54 (21,6 MB/s) - “/crex/proj/snic2020-6-60/AnaLopez/squeezemeta/data_bases/SqueezeMetaDB.tar.gz” guardado [153413390559/153413390559]

**Comment by fpusan** [comment]
Did it actually finish? it doesn't look like it started decompressing it, which it was doing before according to the log you pasted.
Did you add an `&` after calling the command? Like `nohup download_databases.pl /path/to/db &` ?

**Comment by analopezlopez** [comment]
No, didn't do that, sorry. Should I add the `&`?

**Comment by fpusan** [comment]
Yes I think that might be the issue. Just double check that the previous process is not still active.

**Comment by analopezlopez** [comment]
Ok, I'm running it again. Apparently, the other process was already dead. I'll let you know.

Thank you for the super fast responses, much appreciated!

**Comment by analopezlopez** [comment]
Hi, I just checked it and after running `test_install.pl`, it seems that it worked. 

I only received this message:

> Checking that SqueezeMeta is properly configured... checking database in /crex/proj/snic2020-6-60/AnaLopez/squeezemeta/data_bases/db
> 	nr.db OK
> 	CheckM manifest OK
> 	The LCA_tax/taxid.db database is not present in /crex/proj/snic2020-6-60/AnaLopez/squeezemeta/data_bases/db, it is malformed, or there is other problem with your SQLite configuration

Other than that, everything OK!

**Comment by fpusan** [comment]
It seems that it didn't fully work.
What do you get with `ls /crex/proj/snic2020-6-60/AnaLopez/squeezemeta/data_bases/db/LCA_tax`

**Comment by analopezlopez** [comment]
(SqueezeMeta) [analopez@rackham2 AnaLopez]$ ll /crex/proj/snic2020-6-60/AnaLopez/squeezemeta/data_bases/db/LCA_tax
total 1579184
-rw-r--r-- 1 analopez snic2020-6-60 383836160 dic 27 02:29 parents.db
-rw-rw-r-- 1 analopez snic2020-6-60 331645307 dic 26 17:03 parents.txt
-rw-r--r-- 1 analopez snic2020-6-60 901579264 dic 27 02:23 taxid.db
-rw-rw-r-- 1 analopez snic2020-6-60        73 dic 27 02:29 taxid.md5

**Comment by fpusan** [comment]
It seems that you have the file, but maybe it is corrupt. Do you have enough disk space? Can you share the `nohup.out` file with me?

**Comment by archanamadhav** [comment]
Hello, I had the same issue yesterday. Attempted again today but I can't seem to reach the website?

**Comment by fpusan** [comment]
Yes, it seems to be down at the moment. You can try running `make_databases_alt.pl` which will use an alternative server and try to get all the data directly from NCBI. Database creation can take potentially more than one day so you'll have to be patient,

**Comment by jtamames** [comment]
Try now, it should work.
Best,

**Comment by fpusan** [comment]
```
db/Pfam-A.hmm
db/LCA_tax/
db/LCA_tax/parents.txt
db/LCA_tax/taxid.db
db/LCA_tax/taxid.md5
db/LCA_tax/parents.db
db/DB_BUILD_DATE
tar: Exiting with failure status due to previous errors
```
So it seems that the download was interrupted. We are having trouble with our servers, so maybe it was because of that. Maybe you can run `make_databases_alt.pl` instead?

**Comment by analopezlopez** [comment]
Ok, I'll try that!
Just out of curiosity, how's `make_databases_alt.pl` different from `make_databases.pl`?

**Comment by fpusan** [comment]
It will use an alternative server. You'll find some more details on database installation in section 3 of the ReadMe

**Comment by archanamadhav** [comment]
This worked for me too, thank you!

**Comment by fpusan** [comment]
Glad to hear! Andes (our second server) is back up so hopefully the normal way will also work now.
