### ISSUE TITLE
versionchange.pl

### ISSUE THREAD

**Issue by analopezlopez** [jtamames/SqueezeMeta#418]
Hi, 

I'm trying to run `versionchange.pl` in order to load an old SqueezeMeta project into the last version of SQMtools but I get this message:

> perl /domus/h1/analopez/.conda/envs/SqueezeMeta/SqueezeMeta/utils/versionchange.pl /domus/h1/analopez/snic2020-6-60/AnaLopez/squeezemeta/coassembly_mode/RUN_1
> Cannot find version number in /domus/h1/analopez/.conda/envs/SqueezeMeta/SqueezeMeta/version.txt
> WARNING: The results you want to re-run happen to be created with an older version of SqueezeMeta (Unknown older version), different from the current one ()
> To make these results compatible with the current version, I would need to make some restructuring and name changes.
> I will keep track of all these changes for you.
> Do you want to proceed? (y/n)? y
> Died at /domus/h1/analopez/.conda/envs/SqueezeMeta/SqueezeMeta/utils/versionchange.pl line 64, <STDIN> line 1.

Am I using the correct syntax here?

Thanks!

**Comment by jtamames** [comment]
Hello
Sorry for the uninformative error message. It is dying there because it is not possible to create a file in the directory you are in. Do you have write permissions, and some disk space? Also, can you check this: `ls -l /domus/h1/analopez/snic2020-6-60/AnaLopez/squeezemeta/coassembly_mode/RUN_1/SqueezeMeta_conf.pl`

Best,

**Comment by analopezlopez** [comment]
Hi, 
This is what I get when I do `ll`:
-rw-rw-r-- 1 analopez snic2020-6-60 7632 dic  3 10:05 /domus/h1/analopez/snic2020-6-60/AnaLopez/squeezemeta/coassembly_mode/RUN_1/SqueezeMeta_conf.pl

I'm using a server to run and storage all the data and, as far as I know, I should have enough space there..

Thanks!

**Comment by jtamames** [comment]
Can you replace line 61 in `versionchange.pl` by this one:
`	open(changes,">$logfile") || die "Cannot open log file in $logfile\n";`
and run the script again?
Best,
J

**Comment by analopezlopez** [comment]
Hi, 
I tried what you suggested and got this error:

> (SqueezeMeta) [analopez@rackham3 squeezemeta]$ perl /domus/h1/analopez/.conda/envs/SqueezeMeta/SqueezeMeta/utils/versionchange.pl /domus/h1/analopez/snic2020-6-60/AnaLopez/squeezemeta/coassembly_mode/RUN_1
> Cannot find version number in /domus/h1/analopez/.conda/envs/SqueezeMeta/SqueezeMeta/version.txt
> WARNING: The results you want to re-run happen to be created with an older version of SqueezeMeta (Unknown older version), different from the current one ()
> To make these results compatible with the current version, I would need to make some restructuring and name changes.
> I will keep track of all these changes for you.
> Do you want to proceed? (y/n)? y
> Cannot open log file in RUN_1/changes.RUN_1.txt

**Comment by jtamames** [comment]
Move to /domus/h1/analopez/snic2020-6-60/AnaLopez/squeezemeta/coassembly_mode/RUN_1 and try again

**Comment by analopezlopez** [comment]
Sorry, didn't work. It displays the same error.

**Comment by analopezlopez** [comment]
Also, I don't see a changes.RUN_1.txt file in this folder. Maybe it hasn't been generated?

(SqueezeMeta) [analopez@rackham2 RUN_1]$ ll
total 244
drwxrwsr-x 6 analopez snic2020-6-60   4096 dic  3 23:19 data
drwxrwsr-x 2 analopez snic2020-6-60   4096 dic  3 23:05 ext_tables
drwxrwsr-x 2 analopez snic2020-6-60   4096 dic  4 00:09 intermediate
-rw-rw-r-- 1 analopez snic2020-6-60   1871 dic  4 00:13 methods.txt
-rw-rw-r-- 1 analopez snic2020-6-60   2964 dic  3 10:05 parameters.pl
-rw-rw-r-- 1 analopez snic2020-6-60    428 dic  4 00:14 progress
drwxrwsr-x 7 analopez snic2020-6-60   4096 ene 10 13:30 results
-rw-rw-r-- 1 analopez snic2020-6-60   7632 dic  3 10:05 SqueezeMeta_conf.pl
-rw-rw-r-- 1 analopez snic2020-6-60 179723 dic  4 00:14 syslog
drwxrwsr-x 3 analopez snic2020-6-60  28672 dic  4 00:13 temp

**Comment by jtamames** [comment]
That is the file to be created. What if you run it from the upper directory, that is, /domus/h1/analopez/snic2020-6-60/AnaLopez/squeezemeta/coassembly_mode/

**Comment by analopezlopez** [comment]
Now it worked! Thank you very much.

**Comment by jtamames** [comment]
Ok, so there is something not working properly with our management of the paths in that script. I will fix it.
Best,
Javier

**Comment by jtamames** [comment]
Fixed issue, feel free to download the new `versionchange.txt` from the repo and replace the one you have in the `utils` directory
