### ISSUE TITLE
CombineSQMlite() with multiple sqm projects

### ISSUE THREAD

**Issue by agg437** [jtamames/SqueezeMeta#419]
Hello,
I ran SqueezeMeta in Sequential mode (I have 89 samples from human microbiome ) and I was wondering how could I subset by function before combine them into an unique object. 
I was trying this code in R:

samples = dir("./stage_0", pattern = "^SRR", full.names = FALSE, ignore.case = TRUE)[1:5] #small subset of sequential projects

SQM_objects = list() #list of projects

for (i in samples){
#for each project subset functional category Pyruvate metabolism
  SQM_objects[[i]] <-  subsetFun(loadSQM(paste('stage_0/',i, sep=''), engine = 'data.table'), fun = 'Pyruvate metabolism',   rescale_copy_number = F) 
}
 #Create combined SQMlite object
COMBINED = combineSQMlite(SQM_objects )
#plot taxonomy
plotTaxonomy(unlist(COMBINED), 'family') #this is failing

Is there an alternative to combine the projects manually in which I can use a for loop?

**Comment by fpusan** [comment]
What happens if you try
`plotTaxonomy(COMBINED, 'family') `

**Comment by agg437** [comment]
It returns the following error:
Error in plotTaxonomy(COMBINED, "family") : The first argument must be a SQM or a SQMlite object

**Comment by fpusan** [comment]
And
```
COMBINED = do.call(combineSQMlite, SQM_objects)
plotTaxonomy(COMBINED, "family")
```
?

**Comment by agg437** [comment]
That works! thanks a lot!
Other related question, it would be correct to compare samples by TPM values inside the COMBINED object ? Or should I consider other metrics?

**Comment by fpusan** [comment]
Glad it works. Anyways I'll make it so that `combineSQM` and `combineSQMlite` can directly accept a single list with all the objects to combine, so that we don't have to resort to `do.call` in the future.
Yeah, I would say it is correct to compare samples by TPM values. Consider also using copy numbers if they are available.

**Comment by agg437** [comment]
Great, thanks a lot for the help
