### ISSUE TITLE
query for a error in sqm2itol.pl

### ISSUE THREAD

**Issue by kinosham** [jtamames/SqueezeMeta#42]
Good day 

I have tried running the sqm2itol.pl with the following command: 

$ sqm2itol.pl -p sandsamples_10hrs_coassembly/ -completion 50 -contamination 10 -classification kegg -function /home/kinosha/functions_10

However I keep getting this same error and I am not sure what is the problem is and how to fix it. 
 
Reading bins in /home/kinosha/sandsamples_10hrs_coassembly/results/19.sandsamples_10hrs_coassembly.bintable...
Found 78 bins
Working with 34 bins with more than 50 % completion and less than 10 % contamination
Reading requested functions from /home/kinosha/functions_10
Reading functions in /home/kinosha/sandsamples_10hrs_coassembly/results/21.sandsamples_10hrs_coassembly.kegg.pathways
Reading sequences in /home/kinosha/sandsamples_10hrs_coassembly/results/03.sandsamples_10hrs_coassembly.faa
Getting sequences for bin metabat2.98.fa.contigs_
Running CompareM: comparem aai_wf --proteins /home/kinosha/sandsamples_10hrs_coassembly/temp/comparem -x faa /home/kinosha/sandsamples_10hrs_coassembly/results/maxbin
Died at /apps/SqueezeMeta/utils/sqm2itol.pl line 213.

Please could someone give me some assistance.

Thanking you in advance

**Comment by jtamames** [comment]
Hello!
We forgot to add CompareM to the third-party list of software that we are distributing. We will fix this soon. In the meantime, it should work if you install CompareM in your system and put it in path (or change line 221 in the script sqm2itol.pl to give it the correct path for CompareM)
Sorry for the inconvenience

Best,
Javier

**Comment by fpusan** [comment]
CompareM has been added to SqueezeMeta in acc096516c10975470d17e6e15da5882b6cca01
