### ISSUE TITLE
Question re: calculation of copy number figure

### ISSUE THREAD

**Issue by biobrad** [jtamames/SqueezeMeta#421]
Hi Squeezemeta people, 

I hope you are all well, thank you again for such a great metagenomic pipeline.

If  I may ask a quick question, how is the copyNumber figure calculated? 
Is it the 'number of ALL functions found' / 'number of that function found in the sample'
so if the sample shows, for example: Total of 200 kegg functions, and that individual function appears 2 times, the figure is 200 kegg functions /  2 individual functions?

Thanks for your time!

cheers
Brad

**Comment by fpusan** [comment]
If you are referring to the copyNumbers appearing in `SQMtools` then this excerpt from [the paper](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-020-03703-2) may help.

> As an alternative to TPM, we also provide copy numbers, calculated as the ratio between the coverage of function of interest and the coverage of the RecA/RadA recombinase universal single-copy gene.

You can also check the documentation for the `USiCGs`, `MGOGs` and `MGKOs` vectors inside `SQMtools` to see some alternatives for calculating copy numbers.

**Comment by vipmenon** [comment]
sorry to tag along here. Is there a normalization step that happens between the samples for sequencing depth. Especially when some of the samples have a higher depth of sequencing? and if there is a normalization step, I am guessing the TPM and the copyNumber is post normalization?

**Comment by fpusan** [comment]
Both the TPM and the copyNumber calculation normalize features by sequencing depth and feature length.

**Comment by vipmenon** [comment]
thank you
