### ISSUE TITLE
An error occurred while running sqm2tables.py

### ISSUE THREAD

**Issue by kinosham** [jtamames/SqueezeMeta#424]
Gooddday

I hope you can help? I am sure this is a format issue, I just dont know how to fix it. 

I am trying to run my squeezemeta data in R. 

I am trying to load the data but get this error:

> SandSQM = loadSQM("E:/kinosha metagnomics solize sand")
Generating tabular outputs for project in E:/kinosha metagnomics solize sand
Error in loadSQM("E:/kinosha metagnomics solize sand") : 
  An error occurred while running sqm2tables.py
In addition: Warning message:
In sprintf("%s/results/tables/%s.superkingdom.%s.abund.tsv", project_path,  :
  one argument not used by format '%s/results/tables/%s.superkingdom.%s.abund.tsv'

Please can you help?

Thank you in advance 

Kinosha

**Comment by kinosham** [comment]
HI yes

So I ran squeezemeta on server then copied over the project onto a hard
drive and I am trying to run in on windows now.

Is the possible to take the outputs and just run the rest on R from the
output files?

I have tried what you sent me but get the same error.

This is what I changed  SqueezeMeta_conf.pl

$installpath = "E:/kinosha metagnomics solize sand/results";
#-- Project dir (calculated dinamically on execution, DO NOT MODIFY)

use File::Basename;
use Cwd 'abs_path';
$projectdir   = abs_path(dirname(__FILE__));


#-- Generic paths

#$databasepath = "E:/kinosha metagnomics solize sand/results";
$databasepath = "E:/kinosha metagnomics solize sand/results";
$extdatapath  = "$installpath/data";
$scriptdir    = "$installpath/scripts";   #-- Scripts directory

The database path? what is this and how do I change this?

I am sorry, I dont know much about this, we get the programs and databases
put on the servers for us.

Thanks

Kinosha

**Comment by kinosham** [comment]
Any suggestions.

I would reallu love to run my oitputa in R to get a bettter picture of my
results.

Thank you

Kinosha

**Comment by fpusan** [comment]
Ah yes, this went under my radar.
`$installpath`  must be set to your local SQM installation, not your results directory.
But maybe you can run sqm2tables inside your server
`sqm2tables.py /path/to/project/ /path/to/project/results/tables`
and then copy the `/path/to/project/results/tables` directory to your windows machine. Place it inside the `project/results/` directory that you already copied. That should do the trick.

**Comment by kinosham** [comment]
Great thank you i will try this.

Just to confirm i should direct it the program to my results folder

**Comment by fpusan** [comment]
You should get the `tables` directory into `E:/kinosha metagnomics solize sand/results`

**Comment by kinosham** [comment]
Thank you so so much I am gonna try this and get back to you

Thanks

Kinosha

**Comment by fpusan** [comment]
Now the program is running but one of the files seems malformed. Is this by any chance an old project?
Can you share the first two lines of the file in `/path/to/project/results/13.*.orftable` file?

**Comment by fpusan** [comment]
Hi, Kinosha,
This is not the file I asked for.
I'm quite sure you are trying to generate tables for an older project with a newer version of SqueezeMeta.
What version of SqueezeMeta did you use for running the original project? You should get a hint by reading the `/path/to/project/syslog` file...

**Comment by fpusan** [comment]
Re-running would be the easiest, yes.
However if re-running would take a lot of time, I can try to help you find a workaround. You could create a new conda environment with an old version of SQM (I think 1.3 might do the trick) and then try to run `sqm2tables.py` and `SQMtools` from there.
Or you can manually edit the headers of some results files so that they will fit into newer versions. It will involve some trial and error but I've done before.

**Comment by kinosham** [comment]
Thank you so so much for your help, I think because I am so new, and not so
great with this,  I will rerun it, I wont be great with the trouble
shooting. I will let you know once it is redone, if it works.

Thank you so much. I appreciate all your help and time.

Regards

Kinosha

**Comment by fpusan** [comment]
Sure! Starting is always hard! It gets easier with time. A bit easier, at least...
Let me know how it goes :)

**Comment by kinosham** [comment]
Thank you so much.

I appreciate it.

Regards

Kinosha

**Comment by kinosham** [comment]
Hi there

So I managed to reproduce my output tables in sqm2tool.py.
I copied over my files onto my windows.
However I am still getting similar issues, if I try direct it to the tables
I am getting an error.
I just don't know what I am doing wrong.

This is from R

>Res_Squeeze = loadSQM("E:/kinosha metagnomics solize sand")
Generating tabular outputs for project in E:/kinosha metagnomics solize sand
Error in loadSQM("E:/kinosha metagnomics solize sand") :
  An error occurred while running sqm2tables.py
In addition: Warning message:
In sprintf("%s/results/tables/%s.superkingdom.%s.abund.tsv", project_path,
 :
  one argument not used by format
'%s/results/tables/%s.superkingdom.%s.abund.tsv'
> Res_Squeeze = loadSQM("E:/kinosha metagnomics solize sand/results/tables")
Error in loadSQM("E:/kinosha metagnomics solize sand/results/tables") :
  Directory "E:/kinosha metagnomics solize sand/results/tables" does not
seem to contain a valid SqueezeMeta project
> Res_Squeeze = loadSQM("E:/kinosha metagnomics solize sand/results")
Error in loadSQM("E:/kinosha metagnomics solize sand/results") :
  Directory "E:/kinosha metagnomics solize sand/results" does not seem to
contain a valid SqueezeMeta project

Regards

Kinosha

**Comment by fpusan** [comment]
Can you show me the content of the `E:/kinosha metagnomics solize sand/results` directory?

**Comment by kinosham** [comment]
[image: image.png]



I hope you can see that .

and my tables folder is

[image: image.png]

**Comment by fpusan** [comment]
Sorry, I can not see things if you attach them when replying via email to github :(
You can answer from the github issue page and I'll be able to see it.

**Comment by kinosham** [comment]
Hi I have added the attachments. pic 1 is the results and pic 2 is the
tables folder in results.

**Comment by fpusan** [comment]
I still can't see them. You can mail them to fernando.puente.sanchez@slu.se

**Comment by kinosham** [comment]
Perfect sent

**Comment by fpusan** [comment]
Ah I think I know what is happening now.
Can you rename the `kinosha metagnomics solize sand` directory to `Kinosha_sand_samples_coassembly_4`? (this is the name present in all the files from the screenshots you sent me, which means this was the original name of that directory)

**Comment by kinosham** [comment]
Its RUNNING!!!!!!!!!

I cant explain how happy I am!!!

Thank you so so much

**Comment by fpusan** [comment]
Nice! Enjoy your data :)
