### ISSUE TITLE
Inability to Create LCA_tax database

### ISSUE THREAD

**Issue by gogol96** [jtamames/SqueezeMeta#425]
There is a persistent problem in downloading new_taxdump.tar.gz because of which the LCA_tax database files are not being able to be created.

After communiting with NCBI , I have downloaded the entire new_taxdump directory individually, however, I am not being able to curating the database.

I need some guidance or if possible a link to the already 
curated file LCA_tax which I can download and straight away use it for processing my data.
![Screenshot_2022-02-09_15-25-27](https://user-images.githubusercontent.com/88103266/153172587-ee6ee9a6-9b37-4a88-8fc1-95f5e3b15b9b.png)

**Comment by fpusan** [comment]
For now I would just download the pre-computed database from our servers using the `download_databases.pl` script. It was created in Dec 27, 2021 so it is quite recent.
Meanwhile I'll see if I can reproduce your issue.

**Comment by gogol96** [comment]
I am trying to download it for quite a few days , but the server is not responding. I am trying again however.
In a previous closed issue, it was mentioned that the database could be downloaded from the browser itself using http://andes.cnb.csic.es/SqueezeMeta/SqueezeMetaDB.tar.gz.
I am trying that also, but it is getting hung after 325 MB. I will try again.

Meanwhile I am also attaching the error log  when I am trying to download New_taxdump from NCBI through FileZilla
[NCBI_Error.docx](https://github.com/jtamames/SqueezeMeta/files/8032801/NCBI_Error.docx)

**Comment by fpusan** [comment]
Yes, it would seem that our servers are down again... we'll try to fix this

**Comment by gogol96** [comment]
Thank You. I will wait.

**Comment by fpusan** [comment]
Our servers are working now for me (checking from two different locations, albeit both in Sweden).
Can you try if it works by quickly running `configure_nodb.pl` and using an arbitrary path as the first argument?
If you manage to download the RDP data, then the connection is working.
Are you inside some sort of VPN?

**Comment by gogol96** [comment]
Thanks . Right now I would not be able to check , as I am out of office. I will do that first thing in the morning tomorrow.


Also, I am not in any VPN.

**Comment by fpusan** [comment]
In parallel I was trying to run the `make_databases.pl` pipeline and I can not reproduce your error.
```
  Running rectaxa.pl
--2022-02-09 18:29:34--  ftp://ftp.ncbi.nih.gov/pub/taxonomy/new_taxdump/new_taxdump.tar.gz
           => ‘/data/fer/SQMfoo/db/LCA_tax/new_taxdump.tar.gz’
Resolving ftp.ncbi.nih.gov (ftp.ncbi.nih.gov)... 130.14.250.7, 165.112.9.229, 2607:f220:41e:250::7, ...
Connecting to ftp.ncbi.nih.gov (ftp.ncbi.nih.gov)|130.14.250.7|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/taxonomy/new_taxdump ... done.
==> SIZE new_taxdump.tar.gz ... 122238669
==> PASV ... done.    ==> RETR new_taxdump.tar.gz ... done.
Length: 122238669 (117M) (unauthoritative)

new_taxdump.tar.gz  100%[===================>] 116,58M  25,2MB/s    in 5,5s    

2022-02-09 18:29:42 (21,3 MB/s) - ‘/data/fer/SQMfoo/db/LCA_tax/new_taxdump.tar.gz’ saved [122238669]
```
The `new_taxdump.tar.gz` file has downloaded successfully for me.

**Comment by gogol96** [comment]
Hello,

The error has been persisting for 2 months almost now. I had tried from two different physical regions of the country with complete different networks.

After your response again yesterday, I tried but the problem has been the same.
![Screenshot_2022-02-10_09-44-57](https://user-images.githubusercontent.com/88103266/153336839-8783ab9e-e5a3-4787-97e0-f405420928c5.png)

With the log from FileZilla I communicated wih NCBI, as the error is coming to be controlled connection closed.
![Screenshot_2022-02-10_09-47-02](https://user-images.githubusercontent.com/88103266/153336937-c37ea299-bec9-4f8a-a4ec-6ca7bb715f27.png)

This is the response from their side.
![Screenshot_2022-02-10_09-48-25](https://user-images.githubusercontent.com/88103266/153337032-afdbdf5f-023d-4935-83b1-ee8b93e83168.png)
 Two days back I could download the new_taxdump using https protocol separatel, but now I dont know how to integrate into the SqueezeMeta database.

make_database.pl  is not even responding.Whatever I am trying, I am trying with make_database.pl.
![Screenshot_2022-02-10_10-01-44](https://user-images.githubusercontent.com/88103266/153338545-3095613a-1680-4437-8b2c-c649c010e47c.png)

I am now trying to download using your server

**Comment by gogol96** [comment]
Your server is probably down again. Can You please confirm?

**Comment by fpusan** [comment]
```
configure_nodb.pl ~/Data/ssd/SQM/db
Make sure that /home/fer/Data/ssd/SQM/db contains all the database files (nr.dmnd, etc...)

Downloading and unpacking RDP classifier...
--2022-02-10 07:49:14--  http://silvani.cnb.csic.es/SqueezeMeta//classifier.tar.gz
Resolving silvani.cnb.csic.es (silvani.cnb.csic.es)... 150.244.82.96
Connecting to silvani.cnb.csic.es (silvani.cnb.csic.es)|150.244.82.96|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 154722472 (148M) [application/x-gzip]
Saving to: ‘/home/fer/.local/opt/miniconda3/envs/SqueezeMeta/SqueezeMeta/lib/classifier.tar.gz’

classifier.tar.gz                                    100%[=====================================================================================================================>] 147,55M  19,6MB/s    in 16s     

2022-02-10 07:49:31 (9,07 MB/s) - ‘/home/fer/.local/opt/miniconda3/envs/SqueezeMeta/SqueezeMeta/lib/classifier.tar.gz’ saved [154722472/154722472]

--2022-02-10 07:49:31--  http://silvani.cnb.csic.es/SqueezeMeta//classifier.md5
Resolving silvani.cnb.csic.es (silvani.cnb.csic.es)... 150.244.82.96
Connecting to silvani.cnb.csic.es (silvani.cnb.csic.es)|150.244.82.96|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 33 [application/x-md5]
Saving to: ‘/home/fer/.local/opt/miniconda3/envs/SqueezeMeta/SqueezeMeta/lib/classifier.md5’

classifier.md5                                       100%[=====================================================================================================================>]      33  --.-KB/s    in 0s      

2022-02-10 07:49:31 (4,97 MB/s) - ‘/home/fer/.local/opt/miniconda3/envs/SqueezeMeta/SqueezeMeta/lib/classifier.md5’ saved [33/33]

classifier/
classifier/classifier.jar
classifier/lib/
classifier/lib/TaxonomyTree.jar
classifier/lib/commons-cli-1.2.jar
classifier/lib/ReadSeq.jar
classifier/lib/jfreechart-1.0.13.jar
classifier/lib/AlignmentTools.jar
classifier/lib/jcommon-1.0.16.jar
classifier/lib/commons-io-2.4.jar

Updating configuration...
Done
```
Sorry, the server is up right now.

You can use `make_databases_alt.pl` to avoid our server entirely.
Please let me know what command you used exactly to get the taxdump file with the https protocol, and perhaps I can guide you on how to modify the make_databases script so that it will use that.

**Comment by gogol96** [comment]
Failted with make_databases_alt.pl.

I used wget --recursive -e robots=off --reject "index.html" --no-host-directories --cut-dirs=6 https://ftp.ncbi.nih.gov/pub/taxonomy/new_taxdump/new_taxdump.tar.gz
I used it right now and was successful.

**Comment by fpusan** [comment]
> Failted with make_databases_alt.pl.

How did it fail exactly?

You can edit the file `/path/to/miniconda3/envs/SqueezeMeta/SqueezeMeta/lib/install_utils/rectaxa.pl`
In line 24 you'll see a wget command. Substitute it for the one that is working for you and run `make_databases_alt.pl`again.

**Comment by gogol96** [comment]
Yes I am trying that
