### ISSUE TITLE
subsetTax fails in a combined SQM object

### ISSUE THREAD

**Issue by analopezlopez** [jtamames/SqueezeMeta#426]
Hi!

I'm trying to use `subsetTax` in SQMtools v0.7.0 to plot a specific family in a SQM object coming from a `combineSQMlite` aggregate. I got this message when I tried to run it:  

>  unclassified_bacteroidales = subsetTax(combined, 'family', tax = 'Unclassified Bacteroidales')
> x <- c("barcode01.run3","barcode02.run3","barcode03.run3","barcode01.run5","barcode02.run5","barcode03.run5","barcode04.run5","barcode05.run5","barcode01.run1","barcode02.run1","barcode05.run1","barcode07.run5","barcode08.run5","barcode09.run5","barcode07.run1","barcode08.run1","barcode12.run1","barcode10.run5","barcode01.run4","barcode02.run4","barcode03.run4","barcode04.run4","barcode07.run4","barcode08.run5","barcode04.run1","barcode06.run1","barcode08.run4","barcode11.run4","barcode05.run4","barcode06.run4","barcode12.run4","barcode06.run5")
> colvec = c('red3')
> svg('ubacteroidales.allsamples.taxa.svg')
> plotTaxonomy(unclassified_bacteroidales, 'family', tax = "Unclassified Bacteroidales", 'percent', rescale = F, others = F, samples = x, base_size = 9, color = colvec) 
> dev.off()
> 
> Error in subsetTax("combined", "family", tax = "Unclassified Bacteroidales") : 
>   The first argument must be a SQM object

Other functions like `plotTaxonomy` worked just fine with the same SQM object. Is it possible to subset in this type of objects?

Thanks!
Ana

**Comment by fpusan** [comment]
No, it is not, as per the documentation. You have to subset the objects before combining them.

**Comment by analopezlopez** [comment]
Oh, ok. 

I tried to subset the objects first but it doesn't seem to be working. I don't know if I did something wrong:

RUN1_subset = subsetTax(RUN1, 'family', tax = 'Unclassified Bacteroidales')
RUN3_subset = subsetTax(RUN3, 'family', tax = 'Unclassified Bacteroidales')
RUN4_subset = subsetTax(RUN4, 'family', tax = 'Unclassified Bacteroidales')
RUN5_subset = subsetTax(RUN5, 'family', tax = 'Unclassified Bacteroidales')

combined = combineSQMlite(RUN1_subset, RUN3_subset, RUN4_subset, RUN5_subset)

And when I try:
unclassified_bacteroidales = subsetTax(combined, 'family', tax = 'Unclassified Bacteroidales')
Error in subsetTax(combined, "family", tax = "Unclassified Bacteroidales") : 
  The first argument must be a SQM object

**Comment by fpusan** [comment]
Yeah, at this point you don't need to subset anymore.
Just do for example `plotTaxonomy(combined)`

**Comment by analopezlopez** [comment]
Oh, I see. Of course!
Thanks.
