### ISSUE TITLE
Error at Step 17

### ISSUE THREAD

**Issue by phagelab** [jtamames/SqueezeMeta#428]
Hello, 
I'm getting this error: 

Storing results for DAS in /home/plzrja/shigella/20220207_shigella/intermediate/17.20220207_shigella.checkM
wc: /home/plzrja/shigella/20220207_shigella/intermediate/17.20220207_shigella.checkM: No such file or directory

Can't find /home/plzrja/shigella/20220207_shigella/intermediate/17.20220207_shigella.checkM

Stopping in STEP18 -> 17.checkM_batch.pl

Died at /home/plzrja/miniconda3/envs/SqueezeMeta/bin/restart.pl line 444.

I've tried restarting, without success. Log attached. Any help would be appreciated.

many thanks.

[log.zip](https://github.com/jtamames/SqueezeMeta/files/8064487/log.zip)

**Comment by phagelab** [comment]
Thanks for replying. 
I ran step 17 alone. This time it runs without error, but the .checkM file is not generated.

**Comment by fpusan** [comment]
Is it showing that it's running checkm for the different bins? Like printing messages in the screen?

**Comment by phagelab** [comment]
Yes - prints messages for 444 bins then prints "Storing results for DAS in ..." but nothing appears in that directory.

**Comment by fpusan** [comment]
Do you have writing permissions in that directory?

**Comment by fpusan** [comment]
And free disk space?

**Comment by jtamames** [comment]
Could you copy some of the screen output please?

**Comment by phagelab** [comment]
Bin 399/444: maxbin.154.fasta_sub.contigs.fa.tax
  Bin 400/444: metabat2.191.fa_sub.contigs.fa.tax
  Bin 401/444: metabat2.275.fa_sub.contigs.fa.tax
  Bin 402/444: maxbin.264.fasta_sub.contigs.fa.tax
  Bin 403/444: maxbin.213.fasta_sub.contigs.fa.tax
  Bin 404/444: metabat2.182.fa_sub.contigs.fa.tax
  Bin 405/444: maxbin.121.fasta_sub.contigs.fa.tax
  Bin 406/444: maxbin.224.fasta_sub.contigs.fa.tax
  Bin 407/444: maxbin.028.fasta.contigs.fa.tax
  Bin 408/444: metabat2.471.fa_sub.contigs.fa.tax
  Bin 409/444: maxbin.313.fasta_sub.contigs.fa.tax
  Bin 410/444: maxbin.014.fasta_sub.contigs.fa.tax
  Bin 411/444: maxbin.125.fasta_sub.contigs.fa.tax
  Bin 412/444: metabat2.12.fa_sub.contigs.fa.tax
  Bin 413/444: metabat2.386.fa_sub.contigs.fa.tax
  Bin 414/444: metabat2.277.fa_sub.contigs.fa.tax
  Bin 415/444: maxbin.095.fasta_sub.contigs.fa.tax
  Bin 416/444: metabat2.229.fa.contigs.fa.tax
  Bin 417/444: metabat2.481.fa_sub.contigs.fa.tax
  Bin 418/444: maxbin.094.fasta_sub.contigs.fa.tax
  Bin 419/444: maxbin.007.fasta.contigs.fa.tax
  Bin 420/444: metabat2.405.fa.contigs.fa.tax
  Bin 421/444: maxbin.221.fasta_sub.contigs.fa.tax
  Bin 422/444: metabat2.389.fa_sub.contigs.fa.tax
  Bin 423/444: metabat2.197.fa_sub.contigs.fa.tax
  Bin 424/444: maxbin.206.fasta_sub.contigs.fa.tax
  Bin 425/444: metabat2.241.fa_sub.contigs.fa.tax
  Bin 426/444: maxbin.269.fasta_sub.contigs.fa.tax
  Bin 427/444: maxbin.199.fasta_sub.contigs.fa.tax
  Bin 428/444: metabat2.330.fa.contigs.fa.tax
  Bin 429/444: metabat2.236.fa_sub.contigs.fa.tax
  Bin 430/444: maxbin.026.fasta.contigs.fa.tax
  Bin 431/444: metabat2.29.fa.contigs.fa.tax
  Bin 432/444: maxbin.133.fasta_sub.contigs.fa.tax
  Bin 433/444: metabat2.113.fa_sub.contigs.fa.tax
  Bin 434/444: metabat2.163.fa.contigs.fa.tax
  Bin 435/444: metabat2.223.fa_sub.contigs.fa.tax
  Bin 436/444: metabat2.8.fa_sub.contigs.fa.tax
  Bin 437/444: metabat2.120.fa.contigs.fa.tax
  Bin 438/444: maxbin.252.fasta_sub.contigs.fa.tax
  Bin 439/444: maxbin.308.fasta.contigs.fa.tax
  Bin 440/444: maxbin.298.fasta_sub.contigs.fa.tax
  Bin 441/444: metabat2.245.fa.contigs.fa.tax
  Bin 442/444: metabat2.20.fa_sub.contigs.fa.tax
  Bin 443/444: maxbin.173.fasta.contigs.fa.tax
  Bin 444/444: maxbin.299.fasta.contigs.fa.tax

  Storing results for DAS in /home/plzrja/shigella/20220207_shigella/intermediate/17.20220207_shigella.checkM

**Comment by jtamames** [comment]
Could you check if you have .tax files in `/home/plzrja/shigella/20220207_shigella/results/bins`? And the content of some of these?

**Comment by phagelab** [comment]
bins contains 888 items (895.3 MB).
Examples of files below:

maxbin.252.fasta_sub.contigs.fa      metabat2.86.fa.contigs.fa
maxbin.252.fasta_sub.contigs.fa.tax  metabat2.86.fa.contigs.fa.tax
maxbin.253.fasta_sub.contigs.fa      metabat2.87.fa_sub.contigs.fa
maxbin.253.fasta_sub.contigs.fa.tax  metabat2.87.fa_sub.contigs.fa.tax
maxbin.254.fasta_sub.contigs.fa      metabat2.88.fa_sub.contigs.fa
maxbin.254.fasta_sub.contigs.fa.tax  metabat2.88.fa_sub.contigs.fa.tax
maxbin.256.fasta.contigs.fa          metabat2.8.fa_sub.contigs.fa
maxbin.256.fasta.contigs.fa.tax      metabat2.8.fa_sub.contigs.fa.tax
maxbin.257.fasta_sub.contigs.fa      metabat2.91.fa_sub.contigs.fa
maxbin.257.fasta_sub.contigs.fa.tax  metabat2.91.fa_sub.contigs.fa.tax
maxbin.258.fasta_sub.contigs.fa      metabat2.96.fa.contigs.fa
maxbin.258.fasta_sub.contigs.fa.tax  metabat2.96.fa.contigs.fa.tax
maxbin.260.fasta_sub.contigs.fa      metabat2.97.fa_sub.contigs.fa
maxbin.260.fasta_sub.contigs.fa.tax  metabat2.97.fa_sub.contigs.fa.tax
maxbin.264.fasta_sub.contigs.fa      metabat2.98.fa.contigs.fa
maxbin.264.fasta_sub.contigs.fa.tax  metabat2.98.fa.contigs.fa.tax
maxbin.268.fasta_sub.contigs.fa      metabat2.9.fa.contigs.fa
maxbin.268.fasta_sub.contigs.fa.tax  metabat2.9.fa.contigs.fa.tax

**Comment by jtamames** [comment]
pleasy copy the contents of one of these tax files, a small one

**Comment by phagelab** [comment]
>megahit_113774 
>megahit_169893 
>megahit_170984 
>megahit_268693 
>megahit_498237 
>megahit_682185 
>megahit_683634 
>megahit_774093 
>megahit_972210 
>megahit_1421676 
Consensus: 	Total size: 213902	Disparity: 0.000
List of taxa (abundance >= 1%): k:;p:;c:;o:;f:;g:;s:;

**Comment by jtamames** [comment]
Ok, there is definitely a problem there, there are no taxonomic annotations for the bin. CheckM failure stems from that. I am checking it.

**Comment by jtamames** [comment]
Could you please copy some lines of file `/home/plzrja/shigella/20220207_shigella/intermediate/09.20220207_shigella.contiglog`?

**Comment by phagelab** [comment]
#- Created by /home/plzrja/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/09.summarycontigs3.pl with data from /home/plzrja/shigella/20220207_shigella/results/06.20220207_shigella.fun3.tax.wranks, mingenes=1, minconsperc_asig=0.7, minconsperc_total=0.5, euknofilter=0,Sun Feb 13 06:56:56 2022
megahit_1		Unknown	Disparity: 0.000	Genes: 1
megahit_2		Unknown	Disparity: 0.000	Genes: 1
megahit_3		Unknown	Disparity: 0.000	Genes: 1
megahit_4		Unknown	Disparity: 0.000	Genes: 1
megahit_6		Unknown	Disparity: 0.000	Genes: 1
megahit_7		Unknown	Disparity: 0.000	Genes: 1
megahit_8		Unknown	Disparity: 0.000	Genes: 1
megahit_9		Unknown	Disparity: 0.000	Genes: 1
megahit_10		Unknown	Disparity: 0.000	Genes: 1
megahit_11		Unknown	Disparity: 0.000	Genes: 2
megahit_12		Unknown	Disparity: 0.000	Genes: 1
megahit_13		Unknown	Disparity: 0.000	Genes: 2
megahit_14		Unknown	Disparity: 0.000	Genes: 1
megahit_15		Unknown	Disparity: 0.000	Genes: 1
megahit_16		Unknown	Disparity: 0.000	Genes: 4
megahit_17		Unknown	Disparity: 0.000	Genes: 2
megahit_18		Unknown	Disparity: 0.000	Genes: 1
megahit_19		Unknown	Disparity: 0.000	Genes: 1
megahit_20		Unknown	Disparity: 0.000	Genes: 1
megahit_21		Unknown	Disparity: 0.000	Genes: 1
megahit_23		Unknown	Disparity: 0.000	Genes: 1
megahit_25		Unknown	Disparity: 0.000	Genes: 1
megahit_26		Unknown	Disparity: 0.000	Genes: 1
megahit_27		Unknown	Disparity: 0.000	Genes: 1
megahit_29		Unknown	Disparity: 0.000	Genes: 2
megahit_30		Unknown	Disparity: 0.000	Genes: 2
megahit_31		Unknown	Disparity: 0.000	Genes: 1
megahit_32		Unknown	Disparity: 0.000	Genes: 1
megahit_33		Unknown	Disparity: 0.000	Genes: 1

**Comment by enormandeau** [comment]
Just chiming in as I got the same error yesterday, about the same time as the OP.
```
Can't find /media/data/Projects/.../sample1/intermediate/17.sample1.checkM
Stopping in STEP18 -> 17.checkM_batch.pl
```

**Comment by jtamames** [comment]
Ok, that is also incomplete. Could you copy now `/home/plzrja/shigella/20220207_shigella/results/06.20220207_shigella.fun3.tax.wranks`?

**Comment by fpusan** [comment]
I can't help much with this one, but is the problem also happening with the test data we provideç'

**Comment by phagelab** [comment]
first 20 lines....

0220207_shigella.fun3.tax.wranks 
megahit_3_4-342	
megahit_4_2-376	
megahit_6_18-278	
megahit_8_65-712	
megahit_9_215-367	
megahit_10_1-237	
megahit_11_287-571	
megahit_12_2-361	
megahit_13_3-125	
megahit_13_340-486	
megahit_15_3-359	
megahit_16_2-268	
megahit_16_280-642	
megahit_16_632-862	
megahit_21_1-351	
megahit_29_1-318	
megahit_31_1-366	
megahit_32_57-416	
megahit_33_1-282	
megahit_34_1-282

**Comment by jtamames** [comment]
Ok, so the problem is there. I see now that step 6 just took five minutes to run, and it did not provide taxonomic annotations. Just to be sure that he Diamond ran correctly (it seems so since it took several days to complete), can you `ls -l /home/plzrja/shigella/20220207_shigella/intermediate/04.20220207_shigella.nr.diamond`?

Then, can you run step 6 by itself? Just do `06.lca.pl 20220207_shigella`. And copy the result here, let's see if we find out why it failed

@enormandeau is this the same for you?

Best,
Javier

**Comment by enormandeau** [comment]
Here is what my intermediate folder looks like:
```
    1.4 MiB [          ]         01.sample1.lon
    4.0 KiB [          ]         01.sample1.stats
   37.0 MiB [##########]         02.sample1.maskedrna.fasta
   33.5 MiB [######### ]         04.sample1.eggnog.diamond
   20.6 MiB [#####     ]         04.sample1.kegg.diamond
   32.0 MiB [########  ]         04.sample1.nr.diamond
    3.4 MiB [          ]         05.sample1.pfam.hmm
    5.9 MiB [#         ]         09.sample1.contiglog
    6.0 MiB [#         ]         09.sample1.contiglog.noidfilter
   10.2 MiB [##        ]         09.sample1.contiglog_allranks
   11.4 MiB [###       ]         09.sample1.contiglog_allranks.noidfilter
    4.0 MiB [#         ]         10.sample1.contigcov
    3.3 MiB [          ]         10.sample1.mapcount
    4.0 KiB [          ]         16.sample1.bintax
    4.0 KiB [          ]         DB_BUILD_DATE
   27.2 MiB [#######   ]     15 /binners
```

**Comment by enormandeau** [comment]
And the command I had used, in case:
```
SqueezeMeta.pl -f 02_data/ -s fof.4.txt -m sequential --cleaning -t 32
```

**Comment by jtamames** [comment]
Did you check that your installation was correct using `test_install.pl`? It looks like a database malfunction problem

**Comment by enormandeau** [comment]
I get an "All checks successful". Here is the end of the output from the `test_install.pl` script.
```
...
Checking that SqueezeMeta is properly configured... checking database in /home/eric/Desktop/squeezemeta_dbs/db
        nr.db OK
        CheckM manifest OK
        LCA_tax DB OK

All checks successful
```

**Comment by enormandeau** [comment]
I installed SqueezeMeta using conda as described on the website. The databases are installed somewhere else but using the `install_databases.sh` or some such script.

**Comment by jtamames** [comment]
Ok, and now can you please `ls -ltr /home/plzrja/shigella/20220207_shigella/temp`? Sorry for all this.

**Comment by phagelab** [comment]
No need to apologise! Very happy if you can help me sort this out.

total 4554928
-rw-rw-r-- 1 plzrja plzrja    1413464 Feb  9 06:01 bac.gff
-rw-rw-r-- 1 plzrja plzrja    1640689 Feb  9 06:01 bac.gff.mod
-rw-rw-r-- 1 plzrja plzrja       3076 Feb  9 06:07 arc.gff
-rw-rw-r-- 1 plzrja plzrja       3586 Feb  9 06:07 arc.gff.mod
-rw-rw-r-- 1 plzrja plzrja      17134 Feb  9 06:14 euk.gff
-rw-rw-r-- 1 plzrja plzrja      19813 Feb  9 06:14 euk.gff.mod
-rw-rw-r-- 1 plzrja plzrja     114642 Feb  9 06:17 mito.gff
-rw-rw-r-- 1 plzrja plzrja     132946 Feb  9 06:17 mito.gff.mod
-rw-rw-r-- 1 plzrja plzrja    2209469 Feb  9 06:18 16S.fasta
-rw-rw-r-- 1 plzrja plzrja     755513 Feb  9 06:18 16S.out
-rw-rw-r-- 1 plzrja plzrja   73032972 Feb  9 06:27 trnas.aragorn
-rw-rw-r-- 1 plzrja plzrja    1509681 Feb  9 06:27 trna.gff.mod
-rw-rw-r-- 1 plzrja plzrja    3306715 Feb  9 06:27 02.20220207_shigella.rna.gff
-rw-rw-r-- 1 plzrja plzrja 1233190087 Feb  9 08:53 02.20220207_shigella.cds.gff.temp
-rw-rw-r-- 1 plzrja plzrja 1276701539 Feb  9 08:54 02.20220207_shigella.cds.gff
-rw-rw-r-- 1 plzrja plzrja   46899933 Feb 13 06:57 09.20220207_shigella.allorfs
-rw-rw-r-- 1 plzrja plzrja   46899944 Feb 13 06:57 09.20220207_shigella.allorfs.noidfilter
-rw-rw-r-- 1 plzrja plzrja 1858045695 Feb 14 16:48 bincontigs.fasta
drwxrwxr-x 2 plzrja plzrja       4096 Feb 14 18:11 checkm_batch
-rw-rw-r-- 1 plzrja plzrja         94 Feb 15 14:48 wc
-rw-rw-r-- 1 plzrja plzrja    4775489 Feb 15 14:57 fun3tax_1.wranks
-rw-rw-r-- 1 plzrja plzrja    4775489 Feb 15 14:57 fun3tax_1.noidfilter.wranks
-rw-rw-r-- 1 plzrja plzrja    4899312 Feb 15 14:57 fun3tax_2.wranks
-rw-rw-r-- 1 plzrja plzrja    4899312 Feb 15 14:57 fun3tax_2.noidfilter.wranks
-rw-rw-r-- 1 plzrja plzrja    4881665 Feb 15 14:57 fun3tax_3.wranks
-rw-rw-r-- 1 plzrja plzrja    4881665 Feb 15 14:57 fun3tax_3.noidfilter.wranks
-rw-rw-r-- 1 plzrja plzrja    4874169 Feb 15 14:57 fun3tax_4.wranks
-rw-rw-r-- 1 plzrja plzrja    4874169 Feb 15 14:57 fun3tax_4.noidfilter.wranks
-rw-rw-r-- 1 plzrja plzrja    4851042 Feb 15 14:57 fun3tax_5.wranks
-rw-rw-r-- 1 plzrja plzrja    4851042 Feb 15 14:57 fun3tax_5.noidfilter.wranks
-rw-rw-r-- 1 plzrja plzrja    4894060 Feb 15 14:57 fun3tax_6.wranks
-rw-rw-r-- 1 plzrja plzrja    4894060 Feb 15 14:57 fun3tax_6.noidfilter.wranks
-rw-rw-r-- 1 plzrja plzrja    4995181 Feb 15 14:57 fun3tax_7.wranks
-rw-rw-r-- 1 plzrja plzrja    4995181 Feb 15 14:57 fun3tax_7.noidfilter.wranks
-rw-rw-r-- 1 plzrja plzrja    5003049 Feb 15 14:58 fun3tax_8.wranks
-rw-rw-r-- 1 plzrja plzrja    5003049 Feb 15 14:58 fun3tax_8.noidfilter.wranks
-rw-rw-r-- 1 plzrja plzrja    5001529 Feb 15 14:58 fun3tax_9.wranks
-rw-rw-r-- 1 plzrja plzrja    5001529 Feb 15 14:58 fun3tax_9.noidfilter.wranks
-rw-rw-r-- 1 plzrja plzrja    4996406 Feb 15 14:58 fun3tax_10.wranks
-rw-rw-r-- 1 plzrja plzrja    4996406 Feb 15 14:58 fun3tax_10.noidfilter.wranks
-rw-rw-r-- 1 plzrja plzrja    4957692 Feb 15 14:58 fun3tax_11.wranks
-rw-rw-r-- 1 plzrja plzrja    4957692 Feb 15 14:58 fun3tax_11.noidfilter.wranks
-rw-rw-r-- 1 plzrja plzrja    4960708 Feb 15 14:58 fun3tax_12.wranks
-rw-rw-r-- 1 plzrja plzrja    4960708 Feb 15 14:58 fun3tax_12.noidfilter.wranks

**Comment by jtamames** [comment]
Ok... please copy some lines of `/home/plzrja/shigella/20220207_shigella/temp/fun3tax_1.wranks`

**Comment by jtamames** [comment]
@enormandeau if you run step 6 alone, are you having the same messages than @phagelab?

**Comment by jtamames** [comment]
@phagelab, please also copy the end of the file, for instance with `tail /home/plzrja/shigella/20220207_shigella/temp/fun3tax_1.wranks`

**Comment by enormandeau** [comment]
I'm running step 6 and also a run on the test dataset that comes with the databases.

**Comment by enormandeau** [comment]
It seems step 6 worked. Here is an NCDU output for the folder
[squeezemeta_run.ncdu.txt](https://github.com/jtamames/SqueezeMeta/files/8072337/squeezemeta_run.ncdu.txt)

**Comment by phagelab** [comment]
head:
megahit_3_4-342	
megahit_4_2-376	
megahit_6_18-278	
megahit_8_65-712	
megahit_9_215-367	
megahit_10_1-237	
megahit_11_287-571	
megahit_12_2-361	
megahit_13_3-125	
megahit_13_340-486	
megahit_15_3-359	
megahit_16_2-268	
megahit_16_280-642	
megahit_16_632-862	
megahit_21_1-351	
megahit_29_1-318	
megahit_31_1-366	
megahit_32_57-416	
megahit_33_1-282	
megahit_34_1-282

tail:
megahit_170626_1-318	
megahit_170627_3-443	
megahit_170628_3-128	
megahit_170628_299-403	
megahit_170634_46-315	
megahit_170636_1-144	
megahit_170637_2-763	
megahit_170637_906-1118	
megahit_170639_2-325	
megahit_170640_1-519

**Comment by jtamames** [comment]
Ok. Let's check if the queries to the database are being done correctly. In the script 06.lca.pl, change line 50:
`my $verbose=0;`
to 
`my $verbose=1;`
And run the script again. It will likely produce a lot of output. You can stop it after a while and copy here some 100 lines or so, that will let us see if the database is ok.
Best,
Javier

**Comment by enormandeau** [comment]
Here is what I get with `verbose=1`:
[06.output.txt](https://github.com/jtamames/SqueezeMeta/files/8072632/06.output.txt)

**Comment by enormandeau** [comment]
@jtamames If it feels like my problem is a different one, just tell me and I'll open another issue. Thanks for the amazing in-real-time debugging 🙏🏽

**Comment by enormandeau** [comment]
They seem to have hits:
```
megahit_76455_342-788   k_Eukaryota;n_Opisthokonta;n_Metazoa;n_Eumetazoa;n_Bilateria;n_Deuterostomia;p_Chordata
megahit_76458_2-265     k_Eukaryota;n_Opisthokonta;n_Metazoa;n_Eumetazoa;n_Bilateria;n_Deuterostomia;p_Chordata
megahit_76467_177-509   k_Eukaryota;n_Opisthokonta;n_Metazoa;n_Eumetazoa;n_Bilateria;n_Deuterostomia;p_Chordata;n_Craniata;n_Vertebrata;n_Gnathostomata;n_Teleostomi;n_Euteleostomi;superc_Actinopterygii;n_Actinopteri;n_Neopterygii;n_Teleost
megahit_76468_246-407   k_Eukaryota;n_Opisthokonta;n_Metazoa;n_Eumetazoa;n_Bilateria;n_Deuterostomia;p_Chordata;n_Craniata;n_Vertebrata;n_Gnathostomata;n_Teleostomi;n_Euteleostomi;superc_Actinopterygii;n_Actinopteri;n_Neopterygii;n_Teleost
megahit_76480_3-212     k_Eukaryota;n_Opisthokonta;n_Metazoa;n_Eumetazoa;n_Bilateria;n_Deuterostomia;p_Chordata;n_Craniata;n_Vertebrata;n_Gnathostomata;n_Teleostomi;n_Euteleostomi;superc_Actinopterygii;n_Actinopteri;n_Neopterygii;n_Teleost
megahit_76485_1-348     k_Eukaryota;n_Opisthokonta;n_Metazoa;n_Eumetazoa;n_Bilateria;n_Deuterostomia;p_Chordata;n_Craniata;n_Vertebrata;n_Gnathostomata;n_Teleostomi;n_Euteleostomi;superc_Actinopterygii;n_Actinopteri;n_Neopterygii;n_Teleost
megahit_76488_3-869     k_Eukaryota;n_Opisthokonta;n_Metazoa;n_Eumetazoa;n_Bilateria;n_Deuterostomia;p_Chordata;n_Craniata;n_Vertebrata;n_Gnathostomata;n_Teleostomi;n_Euteleostomi;superc_Actinopterygii;n_Actinopteri;n_Neopterygii;n_Teleost
megahit_76496_86-568    k_Eukaryota;n_Opisthokonta;n_Metazoa;n_Eumetazoa;n_Bilateria;n_Deuterostomia;p_Chordata;n_Craniata;n_Vertebrata;n_Gnathostomata;n_Teleostomi;n_Euteleostomi;superc_Actinopterygii;n_Actinopteri
megahit_76502_2-292     k_Eukaryota;n_Opisthokonta;n_Metazoa;n_Eumetazoa;n_Bilateria;n_Deuterostomia;p_Chordata;n_Craniata;n_Vertebrata;n_Gnathostomata;n_Teleostomi;n_Euteleostomi;superc_Actinopterygii;n_Actinopteri;n_Neopterygii;n_Teleost
megahit_76506_58-471    k_Eukaryota;n_Opisthokonta;n_Metazoa;n_Eumetazoa;n_Bilateria;n_Deuterostomia;p_Chordata;n_Craniata;n_Vertebrata;n_Gnathostomata;n_Teleostomi;n_Euteleostomi;superc_Actinopterygii;n_Actinopteri;n_Neopterygii;n_Teleost
megahit_76507_1-348     k_Eukaryota;n_Opisthokonta;n_Metazoa;n_Eumetazoa;n_Bilateria;n_Deuterostomia;p_Chordata;n_Craniata;n_Vertebrata;n_Gnathostomata;n_Teleostomi;n_Euteleostomi;superc_Actinopterygii;n_Actinopteri;n_Neopterygii;n_Teleost
megahit_76514_342-509   k_Eukaryota;n_Opisthokonta;n_Metazoa;n_Eumetazoa;n_Bilateria;n_Deuterostomia;p_Chordata;n_Craniata;n_Vertebrata;n_Gnathostomata;n_Teleostomi;n_Euteleostomi;superc_Actinopterygii;n_Actinopteri;n_Neopterygii;n_Teleost
megahit_76517_1-300     k_Eukaryota;n_Opisthokonta;n_Metazoa;n_Eumetazoa;n_Bilateria;n_Deuterostomia;p_Chordata
```

**Comment by phagelab** [comment]
megahit_2360248_1179-1439	
refscore: 106 refiden: 98.1
*select * from taxid where (id="GFI68202.1" or id="GFI17021.1" or id="MBE7725077.1" or id="GFI22019.1" or id="NBH82588.1" or id="EOS20534.1" or id="NBH29092.1" or id="RKI88362.1" or id="GFI46457.1" or id="MBD5464602.1" or id="MBD5556520.1" or id="EOS44218.1" or id="GFI31023.1" or id="MBQ4523159.1" or id="MBS6557476.1" or id="HBM02345.1" or id="QNM01956.1" or id="MBS5464220.1" or id="MBR5800127.1" or id="MBQ2882321.1" or id="RHU91155.1" or id="WP_227732354.1" or id="CUN32367.1" or id="CUP31388.1" or id="RGW85086.1");*
megahit_2360251_1-162 Hits: 25; Valid: 0; Min: 2; Required: 0
   species
   genus
   family
   order
   class
   phylum
   superkingdom
NOFILTER megahit_2360251_1-162 Hits: 25; Valid: 0; Min: 2; Required: 0
   NOFILTER species
   NOFILTER genus
   NOFILTER family
   NOFILTER order
   NOFILTER class
   NOFILTER phylum
   NOFILTER superkingdom
megahit_2360251_1-162	
refscore: 323 refiden: 70.8
*select * from taxid where (id="WP_054339429.1" or id="WP_204885501.1" or id="WP_009260224.1" or id="WP_007492719.1" or id="WP_021629770.1" or id="HJB98906.1" or id="WP_204858327.1" or id="WP_087341004.1" or id="WP_130869519.1" or id="WP_207740432.1" or id="WP_207735027.1" or id="WP_154250244.1" or id="WP_207738072.1" or id="HJB69341.1" or id="HIZ94870.1" or id="WP_204704612.1" or id="HJB81247.1" or id="WP_087270647.1" or id="HIY15729.1" or id="WP_204882763.1" or id="HIW16493.1" or id="WP_087336355.1" or id="WP_087329370.1" or id="WP_087238411.1" or id="HJC41368.1");*
megahit_2360252_2-679 Hits: 25; Valid: 0; Min: 2; Required: 0
   species
   genus
   family
   order
   class
   phylum
   superkingdom
NOFILTER megahit_2360252_2-679 Hits: 25; Valid: 0; Min: 2; Required: 0
   NOFILTER species
   NOFILTER genus
   NOFILTER family
   NOFILTER order
   NOFILTER class
   NOFILTER phylum
   NOFILTER superkingdom
megahit_2360252_2-679	
refscore: 173 refiden: 53.9
*select * from taxid where (id="MBD5473803.1" or id="WP_227078317.1" or id="WP_230104495.1" or id="HIZ74086.1" or id="WP_233440722.1" or id="WP_004606855.1" or id="WP_009248801.1" or id="HJC89708.1" or id="WP_205153793.1" or id="CUO17996.1" or id="HJD45869.1" or id="CRL43538.1" or id="HJC39664.1" or id="WP_227970465.1" or id="MBR4983400.1" or id="WP_002588955.1" or id="GEA39478.1" or id="RKI39755.1" or id="WP_065551797.1" or id="WP_205151208.1" or id="WP_002585681.1" or id="EOS70248.1" or id="WP_112481589.1" or id="MCD7870016.1");*
megahit_2360253_3-464 Hits: 25; Valid: 0; Min: 2; Required: 0
   species
   genus
   family
   order
   class
   phylum
   superkingdom
NOFILTER megahit_2360253_3-464 Hits: 25; Valid: 0; Min: 2; Required: 0
   NOFILTER species
   NOFILTER genus
   NOFILTER family
   NOFILTER order
   NOFILTER class
   NOFILTER phylum
   NOFILTER superkingdom
megahit_2360253_3-464	
refscore: 79.3 refiden: 47.7
*select * from taxid where (id="MBO5070688.1" or id="MBO5055872.1" or id="MBO5338012.1" or id="WP_227054271.1" or id="EOS34800.1");*
megahit_2360253_731-1099 Hits: 8; Valid: 0; Min: 2; Required: 0
   species
   genus
   family
   order
   class
   phylum
   superkingdom
NOFILTER megahit_2360253_731-1099 Hits: 8; Valid: 0; Min: 2; Required: 0
   NOFILTER species
   NOFILTER genus
   NOFILTER family
   NOFILTER order
   NOFILTER class
   NOFILTER phylum
   NOFILTER superkingdom
megahit_2360253_731-1099	
refscore: 295 refiden: 75.0
*select * from taxid where (id="WP_019240276.1" or id="WP_006716124.1" or id="WP_006716129.1" or id="WP_146836058.1" or id="NLI91288.1" or id="WP_098460600.1" or id="WP_222171778.1" or id="WP_018306246.1" or id="WP_072771791.1" or id="WP_015943152.1" or id="WP_014792867.1" or id="WP_018214070.1" or id="WP_005813463.1" or id="MBU4214970.1");*
megahit_2360254_3-566 Hits: 25; Valid: 0; Min: 2; Required: 0
   species
   genus
   family
   order
   class
   phylum
   superkingdom
NOFILTER megahit_2360254_3-566 Hits: 25; Valid: 0; Min: 2; Required: 0
   NOFILTER species
   NOFILTER genus
   NOFILTER family
   NOFILTER order
   NOFILTER class
   NOFILTER phylum
   NOFILTER superkingdom
megahit_2360254_3-566	
refscore: 65.9 refiden: 97.1
*select * from taxid where (id="GFI68202.1" or id="GFI46457.1" or id="MBE7725077.1" or id="GFI22019.1" or id="NBH82588.1" or id="MBD5556520.1" or id="EOS20534.1" or id="NBH29092.1" or id="MBQ4523159.1" or id="GFI17021.1" or id="RKI88362.1" or id="HBM02345.1" or id="QNM01956.1" or id="MBD5464602.1" or id="WP_118097655.1" or id="MBS5464220.1" or id="MBR5800127.1" or id="MBQ2882321.1" or id="EOS44218.1" or id="RHU91155.1" or id="WP_227732354.1" or id="GFI31023.1" or id="CUN32367.1" or id="WP_227248903.1" or id="CUP31388.1");*
megahit_2360255_2-103 Hits: 25; Valid: 0; Min: 2; Required: 0
   species
   genus
   family
   order
   class
   phylum
   superkingdom
NOFILTER megahit_2360255_2-103 Hits: 25; Valid: 0; Min: 2; Required: 0
   NOFILTER species
   NOFILTER genus
   NOFILTER family
   NOFILTER order
   NOFILTER class
   NOFILTER phylum
   NOFILTER superkingdom
megahit_2360255_2-103	
refscore: 267 refiden: 97.0
*select * from taxid where (id="WP_217960084.1" or id="NBJ03830.1" or id="RJV74856.1" or id="BCT45519.1" or id="WP_065535482.1" or id="NBK80438.1" or id="WP_018593278.1" or id="WP_173892408.1" or id="WP_117473339.1" or id="MCD8325954.1" or id="WP_065550902.1" or id="AMN85514.1" or id="WP_117658867.1" or id="NSK74428.1" or id="WP_208061942.1" or id="WP_118651050.1" or id="WP_005361105.1" or id="WP_055156915.1" or id="RGC17051.1" or id="WP_025577928.1" or id="WP_118595120.1" or id="WP_154252912.1");*
megahit_2360256_2-400 Hits: 25; Valid: 0; Min: 2; Required: 0
   species
   genus
   family
   order
   class
   phylum
   superkingdom
NOFILTER megahit_2360256_2-400 Hits: 25; Valid: 0; Min: 2; Required: 0
   NOFILTER species
   NOFILTER genus
   NOFILTER family
   NOFILTER order
   NOFILTER class
   NOFILTER phylum
   NOFILTER superkingdom
megahit_2360256_2-400	
refscore: 63.9 refiden: 81.3
*select * from taxid where (id="WP_160664134.1");*
megahit_2360257_1-105 Hits: 1; Valid: 0; Min: 2; Required: 0
   species
   genus
   family
   order
   class
   phylum
   superkingdom
NOFILTER megahit_2360257_1-105 Hits: 1; Valid: 0; Min: 2; Required: 0
   NOFILTER species
   NOFILTER genus
   NOFILTER family
   NOFILTER order
   NOFILTER class
   NOFILTER phylum
   NOFILTER superkingdom

**Comment by jtamames** [comment]
Ok, the database is not working. Please do the following: open the sqlite command line by typing:
`sqlite3`
Then, load the database LCA_tax/taxid.db that must be in the directory where you stored it. In my case:
`.open databases/db/LCA_tax/taxid.db`
(don't forget the initial dot, that is the syntax of sqlite commands)
and then, type 
`select * from taxid where (id="MBO5070688.1" or id="MBO5055872.1" or id="MBO5338012.1" or id="WP_227054271.1" or id="EOS34800.1");`
Let me know the result.
Best,
J

**Comment by phagelab** [comment]
Nothing seems to happen:

sqlite> .open /home/plzrja/databases/db/LCA_tax/taxid.db
sqlite> select * from taxid where (id="MBO5070688.1" or id="MBO5055872.1" or id="MBO5338012.1" or id="WP_227054271.1" or id="EOS34800.1");
sqlite>

**Comment by fpusan** [comment]
Did you use the `make_databases.pl` or the `download_databases.pl` to create the databases?

**Comment by phagelab** [comment]
I tried both and ran into problems when running test_install.pl. It seems that the download of nr.gz was interrupted - but it did get to 100%. However, the next step of creating the diamond databases did not work and I then got errors with test_install.pl. I then created the diamond databases manually, re-ran test_install.pl and everything tested ok.

**Comment by fpusan** [comment]
I see. Then maybe try downloading again with `download_databases.pl`.
The `test_install.pl` currently checks that the sqlite databases are present an can be queried, but I should probably think on something more strict.

**Comment by phagelab** [comment]
Thanks. I'll try that and see if I run into the same problems.

**Comment by phagelab** [comment]
I downloaded the databases again and re-ran SqueezeMeta and it worked fine this time, both with your test and my data so it must have been a database issue as you suggested. Thanks for your help.
