### ISSUE TITLE
information on bincontigs.fasta

### ISSUE THREAD

**Issue by GiangLeN** [jtamames/SqueezeMeta#429]
Hi,

I noticed that for the binning step 14 was using temp/bincontigs.fasta instead of the assembled contig from flye.
In my case there is a different of 114 contigs.
Could you provide more information on how the bincontigs.fasta was generated ?
I looked into the syslog but the information was not there.

Many thanks

**Comment by GiangLeN** [comment]
The missing contigs are not smaller than 200 bases as I did not specify any value for `-contiglen`.
Looking at the dropped contigs size, they ranged from 500bp to 1,400 Mb.

**Comment by jtamames** [comment]
Hello
Which version of SqueezeMeta are you running?
Also, can you upload the syslog file for us to take a look at it?
Best,
J

**Comment by GiangLeN** [comment]
I reuploaded the file becase the previous one was incorrect.

Please find attached syslog file
[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/8069280/syslog.zip)

Best,
G
