### ISSUE TITLE
Issue with SQMtools File names

### ISSUE THREAD

**Issue by kinosham** [jtamames/SqueezeMeta#431]
Good day 

We spoke recently and you helped me get my data on to my windows so that I could R it off my computer. It started running but not for long. I now get an issue as it is saying files are not there. I see similar files but the ones its looking for. I did see a similar problem come up where you said the version of R may have been to new and to try Git Clone and manually add SQMtools. I have done this but it doesn't work. 

This was my error 
Res_Squeeze = loadSQM("E:/Kinosha_sand_samples_coassembly_4")
Loading orfs
    table...
    abundances...
    sequences
    taxonomy...
Loading contigs
    table...
    abundances...
    sequences...
    taxonomy...
Error in file(file, "rt") : cannot open the connection
In addition: Warning messages:
1: In sprintf("%s/results/tables/%s.superkingdom.%s.abund.tsv", project_path,  :
  one argument not used by format '%s/results/tables/%s.superkingdom.%s.abund.tsv'
2: In file(file, "rt") :
  cannot open file 'E:/Kinosha_sand_samples_coassembly_4/results/tables/Kinosha_sand_samples_coassembly_4.contig.tax.tsv': No such file or directory

Would changing the file names work? if so which ones should I try? 

Thanks in advance 

Kinosha

**Comment by fpusan** [comment]
Yeah, it is a problem with the version of SqueezeMeta.
You should install SQMtools in your windows computer so that it matches the version that you originally used for running the project.

**Comment by kinosham** [comment]
How would I be able to check which version I need for my computer?

**Comment by fpusan** [comment]
You also had to install an older version in your server, right? I would use that one

**Comment by kinosham** [comment]
I dont have access to my server, We have someone who does that with the
programs we use. But I will ask them and try get that version. Should I try
copy the the squeezemeta files off the server?

**Comment by fpusan** [comment]
Ah ok. Just try installing version 1.3 in your computer then. I think it might be that one.

**Comment by kinosham** [comment]
Squeezemeta version 1.3?

**Comment by fpusan** [comment]
Don't worry about the server now. You just need to download SqueezeMeta v1.3 into your Windows machine and use the SQMtools that comes with it.

**Comment by kinosham** [comment]
Hi

So I have downloaded the version 1.3. I installed the SQMtools from that
version, but when I load the version on R it just tells me invalid package.
Yet when I load your version SQMtools.tar.gz it loads and R is picking it
up, but it's not compatible.

**Comment by fpusan** [comment]
Can you post here that "invalid package" message you get?

**Comment by kinosham** [comment]
The error just says invalid package.

And i wont come up in my library. But when. I go to the directory with all
my packages i do see it there.

**Comment by kinosham** [comment]
> install.packages("E:/Kinosha_sand_samples_coassembly_4/SQMtools.zip",
repos = NULL, type = "win.binary")
> library(SQMtools.zip)
Error in library(SQMtools.zip) :
  there is no package called ‘SQMtools.zip.

or sometimes it says invalid package

**Comment by fpusan** [comment]
1) Does `install.packages("E:/Kinosha_sand_samples_coassembly_4/SQMtools.zip", repos = NULL, type = "win.binary")` emit any error message?

2) When trying to load the library it should just be `library(SQMtools)`

**Comment by fpusan** [comment]
What happens if you remove the type="win.binary" when trying to install?

What's the output of `libPaths() `

**Comment by kinosham** [comment]
Same issues

> install.packages("E:/Kinosha_sand_samples_coassembly_4/SQMtools.zip",
repos = NULL, type = "")
> library(SQMtools)
Error in library(SQMtools) : ‘SQMtools’ is not a valid installed package
> install.packages("E:/Kinosha_sand_samples_coassembly_4/SQMtools.zip",
repos = NULL)
> library(SQMtools)
Error in library(SQMtools) : ‘SQMtools’ is not a valid installed package

> libPaths()
Error in libPaths() : could not find function "libPaths"

**Comment by fpusan** [comment]
Sorry, it had a dot at the beggining, like in `.libPaths()`

**Comment by kinosham** [comment]
> .libPaths()
[1] "C:/Program Files/R/R-4.1.2/library"

**Comment by fpusan** [comment]
I think I know what could be happening.
It says it installs the package in `C:/Users/Kinosha/Documents/R/win-library/3.5`
But then it's only looking for packages in `C:/Program Files/R/R-4.1.2/library`. It's weird because it doesn't even seem like the same R version (from 3.5 to 4.1.2).
Let's try telling R to look in the right place

```
.libPaths("C:/Users/Kinosha/Documents/R/win-library/3.5")
library(SQMtools)
```
Does this work?

**Comment by kinosham** [comment]
> .libPaths("C:/Users/Kinosha/Documents/R/win-library/3.5")
> library(SQMtools)
Error in library(SQMtools) : ‘SQMtools’ is not a valid installed package

but the C';/ pathway is not on this computer , I installed
from E:\Kinosha_sand_samples_coassembly_4
and I do see the SQMtools package  in C:/Program Files/R/R-4.1.2/library

**Comment by fpusan** [comment]
Ok, then this is weird.
Can you install the whole conda package for SqueezeMeta version 1.3?

**Comment by kinosham** [comment]
Okay yes I have the whole squeezemeta  version 1.3.1package on my windows.

**Comment by kinosham** [comment]
>
install.packages("E:/Kinosha_sand_samples_coassembly_4/SqueezeMeta-1.3.1.zip",
repos = NULL, type = "win.binary")
Warning in install.packages :
  cannot open compressed file 'SqueezeMeta-1.3.1/DESCRIPTION', probable
reason 'No such file or directory'
Error in install.packages : cannot open the connection

**Comment by fpusan** [comment]
You can not install it that way. You should install the whole conda environment, but maybe that doesn't work in Windows...
Can you open R as an adminstrator and try to install SQMtools again with `install.packages("E:/Kinosha_sand_samples_coassembly_4/SQMtools.zip`

**Comment by kinosham** [comment]
I tried and get this

> install.packages("E:/Kinosha_sand_samples_coassembly_4/SQMtools.zip")
Warning in install.packages :
  package ‘E:/Kinosha_sand_samples_coassembly_4/SQMtools.zip’ is not
available for this version of R

A version of this package for your version of R might be available
elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

**Comment by fpusan** [comment]
Ok, now we are getting somewhere.
You will have to edit the `DESCRIPTION` file inside the zipped directory.
Where it says `Depends: R (>= 3.2.0)` change it to `Depends: R (>= 4.0.0)`
Save and try installing it again.

**Comment by kinosham** [comment]
Error

> install.packages("E:/Kinosha_sand_samples_coassembly_4/SQMtools.zip")
Warning in install.packages :
  package ‘E:/Kinosha_sand_samples_coassembly_4/SQMtools.zip’ is not
available for this version of R

A version of this package for your version of R might be available
elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

And I did change it

Package: SQMtools
Title: Analyze results generated by the SqueezeMeta pipeline
Version: 0.6.1
***@***.***: c(
             person("Fernando", "Puente-Sánchez", email = "
***@***.***", role = c("aut", "cre")),
             person("Natalia", "García-García", email = ***@***.***",
role = c("aut"))
            )
Description: SqueezeMeta is a versatile pipeline for the automated analysis
of metagenomics/metatranscriptomics data (
http://github.com/jtamames/SqueezeMeta). This package provides functions
loading SqueezeMeta results into R, filtering them based on different
criteria, and visualizing the results using basic plots. The SqueezeMeta
project (and any subsets of it generated by the different filtering
functions) is parsed into a single object, whose different components (e.g.
tables with the taxonomic or functional composition across samples,
contig/gene abundance profiles) can be easily analyzed using other R
packages such as vegan or DESeq2
Author: Fernando Puente-Sánchez, Natalia García-García
Maintainer: Fernando Puente-Sánchez ***@***.***>
Depends: R (>= 4.0.0)
Imports: reshape2, ggplot2, pathview, data.table
Suggests: vegan, DESeq2
License: GPLv3
Encoding: UTF-8
LazyData: true
RoxygenNote: 7.1.1
BugReports: https://github.com/jtamames/SqueezeMeta/issues
URL: https://github.com/jtamames/SqueezeMeta

**Comment by fpusan** [comment]
Ok...
How did you install SQMtools in your windows machine in the first place???

**Comment by kinosham** [comment]
I downloaded the file directly and save it on my harddrive
https://github.com/jtamames/SqueezeMeta/releases version  SqueezeMeta v1.3,
then I took SQMtools form there.

**Comment by fpusan** [comment]
Sorry, I meant the SQMtools that you had before (the one that was failing for this dataset)

**Comment by kinosham** [comment]
SQMtools (1).tar

I got it from a file that was left in a comment from another issue. this
installs and and starts working but the file names were different.

**Comment by fpusan** [comment]
Ok, please share that file with me (send it to fernando.puente.sanchez@slu.se) and let me know what command did you use to install that one

**Comment by fpusan** [comment]
I received your email.
Can you try to install the SQMtools (1).tar file again, using the command you just sent me? Does it work?

**Comment by kinosham** [comment]
I get this error

>
install.packages("E:/Kinosha_sand_samples_coassembly_4/SQMtools.0.6.1.tar.gz",
repos = NULL, type = "source")
ERROR: dependency 'data.table' is not available for package 'SQMtools'
* removing 'C:/Program Files/R/R-4.1.2/library/SQMtools'
Warning in install.packages :
  installation of package
‘E:/Kinosha_sand_samples_coassembly_4/SQMtools.0.6.1.tar.gz’ had non-zero
exit status

**Comment by kinosham** [comment]
So I did as you said. It loaded this time and started running but stopped
at the same point

>
install.packages("E:/Kinosha_sand_samples_coassembly_4/SQMtools.0.6.1.tar.gz",
repos = NULL, type = "source")
* installing *source* package 'SQMtools' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'SQMtools'
    finding HTML links ... done
    Hadza                                   html
    MGKOs                                   html
    MGOGs                                   html
    RecA                                    html
    USiCGs                                  html
    combineSQM                              html
    combineSQMlite                          html
    exportKrona                             html
    exportPathway                           html
    exportTable                             html
    loadSQM                                 html
    loadSQMlite                             html
    mostAbundant                            html
    plotBars                                html
    plotFunctions                           html
    plotHeatmap                             html
    plotTaxonomy                            html
    rowMaxs                                 html
    rowMins                                 html
    subsetBins                              html
    subsetContigs                           html
    subsetFun                               html
    subsetORFs                              html
    subsetRand                              html
    subsetTax                               html
    summary.SQM                             html
    summary.SQMlite                         html
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation
path
* DONE (SQMtools)
> library(SQMtools)
> Res_Squeeze = loadSQM("E:/Kinosha_sand_samples_coassembly_4")
Loading orfs
    table...
    abundances...
    sequences
    taxonomy...
Loading contigs
    table...
    abundances...
    sequences...
    taxonomy...
Error in file(file, "rt") : cannot open the connection
In addition: Warning messages:
1: In sprintf("%s/results/tables/%s.superkingdom.%s.abund.tsv",
project_path,  :
  one argument not used by format
'%s/results/tables/%s.superkingdom.%s.abund.tsv'
2: In file(file, "rt") :
  cannot open file
'E:/Kinosha_sand_samples_coassembly_4/results/tables/Kinosha_sand_samples_coassembly_4.contig.tax.tsv':
No such file or directory

My file names in my tables folder are like
this Kinosha_sand_samples_coassembly_4.contig.tax.allfilter.tsv

**Comment by fpusan** [comment]
My bad! I gave you the wrong version
Let's try earlier versions
[SQMtools.0.6.0.tar.gz](https://github.com/jtamames/SqueezeMeta/files/8081943/SQMtools.0.6.0.tar.gz)

**Comment by kinosham** [comment]
Thank you

Oh no same problem


>
install.packages("E:/Kinosha_sand_samples_coassembly_4/SQMtools.0.6.0.tar.gz",
repos = NULL, type = "source")
* installing *source* package 'SQMtools' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'SQMtools'
    finding HTML links ... done
    Hadza                                   html
    MGKOs                                   html
    MGOGs                                   html
    RecA                                    html
    USiCGs                                  html
    combineSQM                              html
    combineSQMlite                          html
    exportKrona                             html
    exportPathway                           html
    exportTable                             html
    loadSQM                                 html
    loadSQMlite                             html
    mostAbundant                            html
    plotBars                                html
    plotFunctions                           html
    plotHeatmap                             html
    plotTaxonomy                            html
    rowMaxs                                 html
    rowMins                                 html
    subsetBins                              html
    subsetContigs                           html
    subsetFun                               html
    subsetORFs                              html
    subsetRand                              html
    subsetTax                               html
    summary.SQM                             html
    summary.SQMlite                         html
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation
path
* DONE (SQMtools)
> Res_Squeeze = loadSQM("E:/Kinosha_sand_samples_coassembly_4")
Loading orfs
    table...
    abundances...
    sequences
    taxonomy...
Loading contigs
    table...
    abundances...
    sequences...
    taxonomy...
Error in file(file, "rt") : cannot open the connection
In addition: Warning messages:
1: In sprintf("%s/results/tables/%s.superkingdom.%s.abund.tsv",
project_path,  :
  one argument not used by format
'%s/results/tables/%s.superkingdom.%s.abund.tsv'
2: In file(file, "rt") :
  cannot open file
'E:/Kinosha_sand_samples_coassembly_4/results/tables/Kinosha_sand_samples_coassembly_4.contig.tax.tsv':
No such file or directory

And I did remove the previous version

**Comment by fpusan** [comment]
[SQMtools.0.5.0.tar.gz](https://github.com/jtamames/SqueezeMeta/files/8082097/SQMtools.0.5.0.tar.gz)
And this one?

**Comment by fpusan** [comment]
Nevermind, I think I know what the problem is. Lemme check some things

**Comment by fpusan** [comment]
What is the output of `sessionInfo()`?

**Comment by kinosham** [comment]
That version didnt work.

Okay so sessioninfo

sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_South Africa.1252  LC_CTYPE=English_South
Africa.1252
[3] LC_MONETARY=English_South Africa.1252 LC_NUMERIC=C

[5] LC_TIME=English_South Africa.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] SQMtools_0.5.0    reshape2_1.4.4    ggplot2_3.3.5     data.table_1.14.2

loaded via a namespace (and not attached):
 [1] KEGGREST_1.34.0        tidyselect_1.1.1       purrr_0.3.4
 [4] colorspace_2.0-2       vctrs_0.3.8            generics_0.1.1
 [7] stats4_4.1.2           utf8_1.2.2             blob_1.2.2
[10] XML_3.99-0.8           rlang_0.4.12           pillar_1.6.4
[13] glue_1.5.0             withr_2.4.3            DBI_1.1.1
[16] Rgraphviz_2.38.0       BiocGenerics_0.40.0    bit64_4.0.5
[19] GenomeInfoDbData_1.2.7 lifecycle_1.0.1        plyr_1.8.6
[22] stringr_1.4.0          zlibbioc_1.40.0        Biostrings_2.62.0
[25] munsell_0.5.0          gtable_0.3.0           memoise_2.0.1
[28] Biobase_2.54.0         fastmap_1.1.0          IRanges_2.28.0
[31] GenomeInfoDb_1.30.0    fansi_0.5.0            AnnotationDbi_1.56.2
[34] Rcpp_1.0.7             scales_1.1.1           cachem_1.0.6
[37] S4Vectors_0.32.3       graph_1.72.0           XVector_0.34.0
[40] bit_4.0.4              png_0.1-7              stringi_1.7.6
[43] dplyr_1.0.7            grid_4.1.2             tools_4.1.2
[46] bitops_1.0-7           magrittr_2.0.1         RCurl_1.98-1.5
[49] tibble_3.1.6           RSQLite_2.2.8          crayon_1.4.2
[52] pkgconfig_2.0.3        ellipsis_0.3.2         KEGGgraph_1.54.0
[55] assertthat_0.2.1       httr_1.4.2             rstudioapi_0.13
[58] R6_2.5.1               compiler_4.1.2

**Comment by fpusan** [comment]
Ok. I assume that you keep having the same problem...
Please go to the `results/tables` file and change the name of the `Kinosha_sand_samples_coassembly_4.contig.tax.prokfilter.tsv` file to `Kinosha_sand_samples_coassembly_4.contig.tax.tsv`.
Then try again

**Comment by kinosham** [comment]
Which version of SQMtools should I use with the modification of the file
name

**Comment by fpusan** [comment]
Try this one but maybe you can upgrade later. Let's see if it works or the error changes...

**Comment by kinosham** [comment]
It ran a little further. YAY. But still stopped

Res_Squeeze = loadSQM("E:/Kinosha_sand_samples_coassembly_4")
Loading orfs
    table...
    abundances...
    sequences
    taxonomy...
Loading contigs
    table...
    abundances...
    sequences...
    taxonomy...
    binning info...
Loading bins
    table...
    abundances...
    taxonomy...
Loading taxonomies
Loading functions
Loading total reads
Warning messages:
1: In sprintf("%s/results/tables/%s.superkingdom.%s.abund.tsv",
project_path,  :
  one argument not used by format
'%s/results/tables/%s.superkingdom.%s.abund.tsv'
2: In sprintf("%s/results/tables/%s.superkingdom.%s.abund.tsv",
project_path,  :
  one argument not used by format
'%s/results/tables/%s.superkingdom.%s.abund.tsv'

or is this message fine?

**Comment by kinosham** [comment]
YEEEESSSSSSSSSSS!!!!!!!!

It worked. Thank you so so so much. I appreciate it so much, and all you
patience.

Kinosha

**Comment by fpusan** [comment]
Phew! Ok, then you can try upgrading versions of SQMtools until it stops working.
Anyways this is a bit irregular so it would be safer if you repeat the analyses with the latest version. But at least this works now.
