### ISSUE TITLE
Move project directory

### ISSUE THREAD

**Issue by shawndoyle** [jtamames/SqueezeMeta#432]
Due to a harddrive space issue, I have had to kill a job mid run (~step 10).

Is it possible to move the current project directory and all of it's contents to a new directory and then restart the pipeline with restart.pl?

I ask because the SqueezeMeta_conf.pl file specifically has a comment to not modify the Project directory.

**Comment by fpusan** [comment]
I'm pretty sure it will work. Otherwise let me know.

**Comment by shawndoyle** [comment]
Thanks. So far so good.

I didn't adjust the conf file. I simply mv'd the whole project directory and restart.pl <ProjectName> restarted on Step10 as expected.

I will report back if any hiccups occur downstream.
