### ISSUE TITLE
toAmos

### ISSUE THREAD

**Issue by alper1976** [jtamames/SqueezeMeta#434]
Hi. When running toamos to curate the afg file I et follwoing error message

Use of uninitialized value $_ in pattern match (m//) at /cluster/projects/nn9745k/scripts/conda_envs/squeezemeta/SqueezeMeta/bin/AMOS/toAmos line 452, <TMPSEQ> line 243240673.

Seems like this refers to the while loop at line 452. 
while ($_ !~ /^\#/){
        print OUT;
        $_ = <TMPSEQ>;
    }

It curates a # at the end of the afg file and keeps being stuck in the while loop forever.

Any ideas what the issue could be?

Thanks

Alexander

**Comment by jtamames** [comment]
Hello
My `toAmos` file reads this way:

```
    while ($_ !~ /^\#/){
        print OUT;
        $_ = <TMPSEQ>;
    }
```
Perhaps you changed it accidentally?
Best,
Javier

**Comment by alper1976** [comment]
My toAmos reads the same way as yours. Must be a copying error.

Alex

**Comment by jtamames** [comment]
I recommend you to download again the script, the error you list does not make sense to me..
Best,
J
