### ISSUE TITLE
SQMtools 'Aggregation function missing' error with loadSQM

### ISSUE THREAD

**Issue by phagelab** [jtamames/SqueezeMeta#437]
Hello. I'm encountering an error both with the test 'Hadza' dataset and my own when trying to load the data from SqueezeMeta for analysis in SQMTools. 

I have activated the SqueezeMeta environment, start R and enter:

data = loadSQM('/home/plzrja/shigella/20220217_shigella')

Output with error below:

Loading orfs
    table...
    abundances...
    sequences
    taxonomy...
Loading contigs
    table...
    abundances...
    sequences...
    taxonomy...
    binning info...
Aggregation function missing: defaulting to length
Error in dim(ordered) <- ns : 
  dims [product 160848] do not match the length of object [643389]

could you help please?

**Comment by fpusan** [comment]
Hi!
Is this with SQM version 1.5.1 and SQMtools version 0.7.0?
I've found that bug a few times in the past, but I have had troubles reproducing it. Last time it fixed itself just by repeating the SQM run.
What were your binning options? Can you check the `syslog` file to check if all the binning steps worked ok?

**Comment by phagelab** [comment]
Hi,
Yes SQM 1.5.1 and SQMtools 0.7.0.
Binning options were left as default, and seem to have worked. 
Step 14 took approx 14 hours for my own dataset and 10 min for the Hazda dataset looking at syslog.

**Comment by fpusan** [comment]
So is this error happening with the test data too?

**Comment by phagelab** [comment]
yes.

**Comment by phagelab** [comment]
Just tried running loadSQM repeatedly with the test data. 
Very odd as it worked once but not again. I'm trying to do this with my own data but it takes much longer to run. So far it hasn't worked but it could do.

**Comment by fpusan** [comment]
What is your R version and the output of `sessionInfo()`?

**Comment by phagelab** [comment]
R is version 3.6.3

> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Ubuntu 20.04.3 LTS

Matrix products: default
BLAS/LAPACK: /home/plzrja/miniconda3/envs/SqueezeMeta/lib/libmkl_rt.so.2

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] SQMtools_0.7.0

loaded via a namespace (and not attached):
[1] compiler_3.6.3 magrittr_2.0.1 plyr_1.8.6     tools_3.6.3    reshape2_1.4.4
[6] Rcpp_1.0.6     stringi_1.6.2  stringr_1.4.0

**Comment by phagelab** [comment]
Tried running loadSQM repeatedly with my own data and it eventually worked - once. Tried again in a new session and it goes back to the original error again.

**Comment by fpusan** [comment]
Well, at least it works eventually...
This is the same behavior I've experienced (only a couple of times, though). It seems to happen for some runs or some SQM installations, as most of the time it works perfectly fine.
If your project is not very big maybe you can share it via dropbox/wetransfer, etc? Now it's grant application season in Sweden so I won't be able to look at this right away, but it annoys me and would like to fix it at some point...

**Comment by phagelab** [comment]
Thanks, yes would be happy to share if it helps you to fix it. Like I said, it still occurs with the Hazda dataset (though perhaps not as often). Very odd. Thanks for the helpful suggestions, at least I can get on with my work now!
