### ISSUE TITLE
Running samples in parallel

### ISSUE THREAD

**Issue by timyerg** [jtamames/SqueezeMeta#438]
Dear developers,
I have a question regarding parallelization of SquezeMeta pipeline.
I just started a run on server with sequential mode for about 200 samples and alocated a lot of RAM and time.
Now I realized that SquezeMeta is processing samples 1 by 1, but not in the parallel mode, so I suppose it will take a lot of time for large amount of samples.
Is it a better approach to launch each sample separately with less amount of time and memory and then pool annotations (I am not interested in bins for this project).

**Comment by jtamames** [comment]
Hello!
Yes, it won't be a difference in the results if you run each of the samples separately. Later you can combine the results with SQMtools.
Best,
J

**Comment by timyerg** [comment]
Thank you for confirmation!
Already launched it in parallel.

Best,
Timur
