### ISSUE TITLE
output directory

### ISSUE THREAD

**Issue by SamLambrechtsUGent** [jtamames/SqueezeMeta#44]
Hello,

I was wondering whether there is an option to specify an output directory where all the files SqueezeMeta would output are written? I'm asking this question because I am trying to run SqueezeMeta on an HPC cluster, and I am not allowed to write files where I execute the command.

Best regards,

Sam

**Comment by fpusan** [comment]
Hi,

Right now part of the code assumes that the project results are stored in the same directory from which the scripts are run (however you can just move to that directory before running SqueezeMeta). We will add support for custom output directories in the not-so-distant future.

For now, just `cd` to the directory you want to write into before running SqueezeMeta, like in

```
cd $RESULTSPATH
/path/to/SqueezeMeta/scripts/SqueezeMeta.pl -p myprojectname [OTHER OPTIONS]
```

This way results will be stored in the `$RESULTSPATH/myprojectname` directory.

**Comment by SamLambrechtsUGent** [comment]
Hi,

Thank you. I tried, but received the following error message:

Unknown option: extassembly
Died at /data/gent/423/vsc42339/Squeezemeta/software/SqueezeMeta/0.4.3-foss-2018b-Python-2.7.15/scripts/SqueezeMeta.pl line 407.

Not sure if this is related or a new different issue?

**Comment by fpusan** [comment]
Yes, there are actually two new problems there, both unrelated to the original problem.
1) You seem to be using version 0.4.3, which did not support the extassembly option. Please consider switching to version 1.0.0
2) The error in line 407 suggests that there is some kind of problem with your sample file. Version 1.0.0 should be more verbose about what's actually happening, but double check that the samples file is truly present in `/user/scratch/gent/gvo000/gvo00043/vsc42339/pilot.samples` and that you have proper read permissions.

Let me know if this works for you!

**Comment by SamLambrechtsUGent** [comment]
Ok thank you, that seemed to fix this issue. I have ran into another issue, but I will open a new thread if I'm unable to fix that one myself.

Thanks!

**Comment by fpusan** [comment]
Ok, closing this one, let me know if you find further issues
