### ISSUE TITLE
Can't locate strict.pm in perl dependencies of SqueezeMeta

### ISSUE THREAD

**Issue by marius44** [jtamames/SqueezeMeta#440]
Hi there!

I'm using SqueezeMeta v 1.4.0 on an Ubuntu 20.04.4 LTS x86_64 server, and I was trying to rerun: 

```
perl /home/user/miniconda3/envs/SqueezeMeta/bin/09.summarycontigs3.pl .
```
And I got a weird error that I hadn't gotten before. Here is the whole thing:

```
(base) user@nautilus:/home/adesales/SQUEEZE_META$ conda activate SqueezeMeta

(SqueezeMeta) user@nautilus:/home/adesales/SQUEEZE_META$ perl /home/user/miniconda3/envs/SqueezeMeta/bin/09.summarycontigs3.pl .
Can't locate strict.pm in @INC (you may need to install the strict module) (@INC contains: /home/user/miniconda3/envs/SqueezeMeta/lib/site_perl/5.26.2/ /home/user/miniconda3/envs/SqueezeMeta/lib/site_perl/5.26.2/x86_64-linux-thread-multi/ /home/user/miniconda3/envs/SqueezeMeta/lib/5.26.2/ /home/user/miniconda3/envs/SqueezeMeta/lib/5.26.2/x86_64-linux-thread-multi/ /home/user/miniconda3/envs/SqueezeMeta/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home/user/miniconda3/envs/SqueezeMeta/lib/site_perl/5.26.2 /home/user/miniconda3/envs/SqueezeMeta/lib/5.26.2/x86_64-linux-thread-multi /home/user/miniconda3/envs/SqueezeMeta/lib/5.26.2 .) at /home/user/miniconda3/envs/SqueezeMeta/bin/09.summarycontigs3.pl line 8.
BEGIN failed--compilation aborted at /home/user/miniconda3/envs/SqueezeMeta/bin/09.summarycontigs3.pl line 8.
```
So I decided to run the test_install.pl, and I got something similar.
```
(SqueezeMeta) user@nautilus:/home/adesales/DeSalesMetaG/raws$ perl /home/user/miniconda3/envs/SqueezeMeta/SqueezeMeta/utils/install_utils/test_install.pl
Can't locate strict.pm in @INC (you may need to install the strict module) (@INC contains: /home/user/miniconda3/envs/SqueezeMeta/lib/site_perl/5.26.2/ /home/user/miniconda3/envs/SqueezeMeta/lib/site_perl/5.26.2/x86_64-linux-thread-multi/ /home/user/miniconda3/envs/SqueezeMeta/lib/5.26.2/ /home/user/miniconda3/envs/SqueezeMeta/lib/5.26.2/x86_64-linux-thread-multi/ /home/user/miniconda3/envs/SqueezeMeta/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home/user/miniconda3/envs/SqueezeMeta/lib/site_perl/5.26.2 /home/user/miniconda3/envs/SqueezeMeta/lib/5.26.2/x86_64-linux-thread-multi /home/user/miniconda3/envs/SqueezeMeta/lib/5.26.2 .) at /home/user/miniconda3/envs/SqueezeMeta/SqueezeMeta/utils/install_utils/test_install.pl line 3.
BEGIN failed--compilation aborted at /home/user/miniconda3/envs/SqueezeMeta/SqueezeMeta/utils/install_utils/test_install.pl line 3.
```
I was reading about the error and I started to suspect that our perl version was the problem. I tried to test with another perl script that we use without any problem as a routine in our lab, getting the same result.

```
(SqueezeMeta) user@nautilus:/home/adesales/DeSalesMetaG/raws$ perl concat_lanes.pl DM20_S90_L00*.fastq.gz -p 23
Can't locate warnings.pm in @INC (you may need to install the warnings module) (@INC contains: /home/user/miniconda3/envs/SqueezeMeta/lib/site_perl/5.26.2/ /home/user/miniconda3/envs/SqueezeMeta/lib/site_perl/5.26.2/x86_64-linux-thread-multi/ /home/user/miniconda3/envs/SqueezeMeta/lib/5.26.2/ /home/user/miniconda3/envs/SqueezeMeta/lib/5.26.2/x86_64-linux-thread-multi/ /home/user/miniconda3/envs/SqueezeMeta/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home/user/miniconda3/envs/SqueezeMeta/lib/site_perl/5.26.2 /home/user/miniconda3/envs/SqueezeMeta/lib/5.26.2/x86_64-linux-thread-multi /home/user/miniconda3/envs/SqueezeMeta/lib/5.26.2 .) at concat_lanes.pl line 3.
BEGIN failed--compilation aborted at concat_lanes.pl line 3.
```
It was kind of scary, and I realized that I still was in the SqueezeMeta environment. So, I run the perl script in the base environment, getting the correct result from it.

```
(base) user@nautilus:/home/adesales/DeSalesMetaG/raws$ perl concat_lanes.pl DM20_S90_L00*.fastq.gz -p 23
cat DM20_S90_L001_R1_001.fastq.gz DM20_S90_L002_R1_001.fastq.gz DM20_S90_L003_R1_001.fastq.gz DM20_S90_L004_R1_001.fastq.gz > .//DM20_S90_R1.fastq.gz
cat DM20_S90_L001_R2_001.fastq.gz DM20_S90_L002_R2_001.fastq.gz DM20_S90_L003_R2_001.fastq.gz DM20_S90_L004_R2_001.fastq.gz > .//DM20_S90_R2.fastq.gz
```

How could I solve this? If I need to update SqueezeMeta, how do I do it?

Thanks!

Mario.

**Comment by fpusan** [comment]
Sorry for the late delay! Grant writing season... :(
Please activate the SqueezeMeta environment and type
`which perl`
`perl -e "print qq(@INC)"`
Then do the same with the environment deactivated. Let me know the output of the four commands.

**Comment by marius44** [comment]
No worries. I know how is the deal. Hope the grant will be accepted.

I run the commands you asked for.

Here we have the output of the activated environment:

`(SqueezeMeta) user@nautilus:~$ which perl
/home/user/miniconda3/envs/SqueezeMeta/bin/perl

(SqueezeMeta) user@nautilus:~$ perl -e "print qq(@INC)"
/home/user/miniconda3/envs/SqueezeMeta/lib/site_perl/5.26.2/ /home/user/miniconda3/envs/SqueezeMeta/lib/site_perl/5.26.2/x86_64-linux-thread-multi/ /home/user/miniconda3/envs/SqueezeMeta/lib/5.26.2/ /home/user/miniconda3/envs/SqueezeMeta/lib/5.26.2/x86_64-linux-thread-multi/ /home/user/miniconda3/envs/SqueezeMeta/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home/user/miniconda3/envs/SqueezeMeta/lib/site_perl/5.26.2 /home/user/miniconda3/envs/SqueezeMeta/lib/5.26.2/x86_`

And here with the environment deactivated:

`(base) user@nautilus:~$ which perl
/home/user/miniconda3/bin/perl

(base) user@nautilus:~$ perl -e "print qq(@INC)"
/home/user/miniconda3/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home/user/miniconda3/lib/site_perl/5.26.2 /home/user/miniconda3/lib/5.26.2/x86_64-linux-thread-multi /home/user/miniconda3/lib/5.26.2 .`

Thanks!

M

**Comment by marius44** [comment]
I had to make a fresh installation from Anaconda dashboard. It seems to be corrected this time.
