### ISSUE TITLE
Multiple external assemblies

### ISSUE THREAD

**Issue by rubmc97** [jtamames/SqueezeMeta#441]
Hello,

I´d like to know if in case of having multiple external assemblies referenced in the metadata file (either sequential or coassembly modes would work for me), they can be indicated in the tag -extassembly mentioning the folder in which they are. Or if each of the assemblies´files has to be mentioned after the tag.

Many thanks in advance,
Ruben Martinez Cuesta

**Comment by jtamames** [comment]
Hello Rubén
You can specify different external assemblies in the samples file. Page 10 in the manual says:

> "extassembly" indicates the external assemblies for each of the samples, if they are to
> be used. This allows to specify different external assemblies for each sample when
> running in sequential mode. For coassembly, merged or seqmerge modes, use the
> SqueezeMeta -extassembly option instead (see Section 5).

Take a look there for more details.
Best,
J

**Comment by rubmc97** [comment]
Thanks a lot for the fast response. 
Unfortunately in the sequential mode it´s not recognizing the external assemblies indicated in the metadata as specified in the instructions "extassemmbly=/project/genomics/sample1.fastq"and goes directly into megahit assembler. Any clues? 

Ruben

**Comment by jtamames** [comment]
Ok, let me check

**Comment by jtamames** [comment]
btw, are you putting it like that, "extassemmbly"? If so, please try "extassembly"

**Comment by rubmc97** [comment]
Indeed... Thanks a lot! Sorry for the silly mistake
