### ISSUE TITLE
Exportable file from a combined SQM object

### ISSUE THREAD

**Issue by analopezlopez** [jtamames/SqueezeMeta#443]
Hi, 

Is there any way to create some sort of exportable tsv file from a combined SQM object coming from different SqueezeMeta projects? The idea is to use this metadata table for further analyses.

Thanks, 
Ana

**Comment by fpusan** [comment]
There is literally a function called `exportTable` (which is just a very basic wrapper around R's `write.table`)

**Comment by analopezlopez** [comment]
Oh, of course! Sorry for the silly question, I missed this function. 
I was just wondering if it would work on a combined SQM object but it did. So thanks for the prompt response!

**Comment by fpusan** [comment]
Glad to help!
