### ISSUE TITLE
Problem with Taxonomy

### ISSUE THREAD

**Issue by gogol96** [jtamames/SqueezeMeta#444]
I was trying to make a Krona chart from the output results of my project. However, no output was being received. Something like this:
![Screenshot_2022-03-16_11-23-02](https://user-images.githubusercontent.com/88103266/158525525-380749bf-8a3a-4940-a790-91568f9edcd1.png)
I was confused.

I re-run the project:
And I found this : 
![Error](https://user-images.githubusercontent.com/88103266/158525605-5eba448c-c471-48a2-a9d8-10841234f7ac.png)
Can you help shed some light in what is happening?

**Comment by jtamames** [comment]
Hello
#428  reported an issue regarding this step that had to do with database installation. Could that be true also for you?
Please send me the syslog file, and to check database functioning, do the following:

> open the sqlite command line by typing:
> sqlite3
> Then, load the database LCA_tax/taxid.db that must be in the directory where you stored it. In my case:
> .open databases/db/LCA_tax/taxid.db
> (don't forget the initial dot, that is the syntax of sqlite commands)
> and then, type
> select * from taxid where (id="MBO5070688.1" or id="MBO5055872.1" or id="MBO5338012.1" or id="WP_227054271.1" or id="EOS34800.1");
> Let me know the result.

Best,
J

**Comment by gogol96** [comment]
Its showing Ok from test install. Let me run again and get back. I am closing the issue as of now.
