### ISSUE TITLE
Updating Silva to V138

### ISSUE THREAD

**Issue by MaxRubinBlum** [jtamames/SqueezeMeta#445]
Hi! Is it feasible to update Silva to 138?  Could I format properly the database and overwrite the files in the db folder?

**Comment by fpusan** [comment]
Hi! I think that should work! Note also that silva is not really used by the main SqueezeMeta pipeline, only by the `cover.pl` utility script.

**Comment by MaxRubinBlum** [comment]
Great, thanks! Will give it a try.
