### ISSUE TITLE
No space left on device error in 10.mapsamples.pl;  sort defaults?

### ISSUE THREAD

**Issue by nucleoli2** [jtamames/SqueezeMeta#447]
Found that our datasets were failing in 10.mapsamples.pl with errors of the form:  

sort: write failed: /tmp/sortVGT5KP: No space left on device

Turns out the root partition size (which we are not able to influence) on this particular server is pretty small; a different partition is used for datasets.  

I note that the call to the Linux command line "sort" utility in 10.mapsamples.pl implicitly uses sort's default location for its temporary files:   /tmp.

Pointing sort's temporary directory location to that of the SqueezeMeta project temp directory appears to remedy this issue as measured by the SqueezeMeta jobs running to completion.   

Accomplished by adding the parameter to the sort call "-T $tempdir".

In context, line 218 of 10.mapsamples.pl version 1.5.0 became:
my $command="sort -T $tempdir -t _ -k 2 -k 3 -n $mapcountfile > $tempdir/mapcount.temp; mv $tempdir/mapcount.temp $mapcountfile";

Sincere apologies for any confusion on my part as I browse the code and show this possible remedy.

I also apologize for the delay in reporting the issue.  Found it and implemented the above in 1.3.0... forgot to log it with you here... then stumbled into the issue again with update to 1.5.0.

Many thanks to the SqueezeMeta team, a great assemblage!

**Comment by fpusan** [comment]
Good catch!
We can incorporate this fix I think (what do you think, @jtamames). Pretty sure `/tmp` is being used somewhere else (we have so many dependencies) but at least it will fix what seemed to be the larger source of `/tmp` usage for you...

**Comment by jtamames** [comment]
Hello!
Thanks for digging into this! It is a nice solution that one you found, we will add it into our code. 
Best,
J

**Comment by nucleoli2** [comment]
Delighted the suggestion was useful....

Thanks!

Best regards....
