### ISSUE TITLE
10.mapsamples.pl. Program finished abnormally:  consumes all RAM/SWAP while counting sequences...

### ISSUE THREAD

**Issue by nucleoli2** [jtamames/SqueezeMeta#448]
Apologies, again 10.mapsamples.pl.

Squeezemeta 1.5.0 cranks away for >5 days on a dataset then emits the "Program finished abnormally" message  in Step 10, the "Counting with sqm_counter:" phase, eg:
.
.
.
  22519761 reads counted
  23009321 reads counted
  23498881 reads counted
  23988441 reads counted
Stopping in STEP10 -> 10.mapsamples.pl. Program finished abnormally

Looked for a bread crumb trail, did not find anything that I understood to link back to the issue.  Used SqueezeMeta "restart" command and just watched it crank away in step 10...  happened to catch it in "top" while the restart was emitting the "nnnnnn reads counted" messages and noticed the job was using all of the RAM on the server (392 GB) and it quickly over-ran the SWAP space, at which point it was terminated.  The Linux "messages" file on the server had an entry like this one:

Dec 27 12:15:25 kernel: Out of memory: Kill process 21403 (perl) score 951 or sacrifice child
Dec 27 12:15:25 kernel: Killed process 21403 (perl), UID 1000, total-vm:393117756kB, anon-rss:379099320kB, file-rss:344kB, shmem-rss:0kB

Browsed the code.  Per usual I may be quite confused (and am Perl naive), but a form of resource usage lock was not obvious to me... by which I mean that I did not seem to see the parallel threads or their dispatcher regulating the amount of memory that could be devoted to the files which were having their sequences counted in sqm_counter.

My hypothesis became:  try fewer threads to stay within the amount of RAM available.  This server is a dual Xeon 6242R with 40 hyperthreaded cores.  This SqueezeMeta run was launched with 70 threads (hyperthreads seem to perform nicely for us with tools like MegaHit). Did not want to wait the 5 days to get back to this point, so iteratively attempted different thread counts by editing $numthreads in the project's SqueezeMeta_conf.pl file and using "restart".

With $numthreads = 20, the job ran to completion (and the results make sense).

I don't have enough Perl specific insight to presume to offer a programmatic fix for this issue... and fully grant that I may be sufficiently confused about what is going on that the reduction of threads and the job running to completion is merely coincidental.

Syslog provided.

Thanks and best regards!

[syslog20220323.zip](https://github.com/jtamames/SqueezeMeta/files/8336264/syslog20220323.zip)

**Comment by jtamames** [comment]
Hello!
A higher number of threads will surely increase the RAM usage since each one has to load a good amount of data into memory (for instance, the positions of each of the genes to map the reads against). This will be exacerbated when analyzing big metagenomes with many genes and reads. Still, I am surprised that it consumed your whole 392 Gb. Clearly better monitoring and management of RAM is needed here. We had a similar issue when running step 4 (Diamond runs), which is also very RAM-hungry, and solved it checking the available memory previously and setting related parameters accordingly. Perhaps we can do it also in this case, to adjust the number of threads that can be run safely.
Again thank you very much for your detailed report and your catch on this!
Best,
Javier

**Comment by jtamames** [comment]
Also, 5 days running is way too much, but not surprising if the machine was swapping all along.

**Comment by nucleoli2** [comment]
Re: 5 days.
Not for sure on this, but I get the impression that our datasets may be larger than some.  
We know these samples types rather well from our 16S work over the years;  this sample type has a very high microbial diversity.  Thus, we know pretty well that the number of sequences that are needed to get the coverage of the diversity in these sample has to be what you see in the syslog file. (more on sequences/sample in a subsequent comment).  

All things considered I think the system is working as intended.  I monitor each pipestep very closely to make sure that if swapping happens at all, it is only as each pipestep is getting to steady state.  I observe that swapping is infrequent and quite constrained (until the flagrant failure in step 10 while counting sam sequences).  I also watch carefully to see how efficiently each pipe step uses the number of threads specified on the SqueezeMeta command line.  Once the pipesteps have reached steady state, the threads used versus the threads requested matches up very nicely.   
I have also manually emulated a couple of the pipesteps, eg, step one with MegaHit.  With the same thread count, I get, within tolerance, the same elapsed time as the corresponding SqueezeMeta pipe step.
Per all things with these sorts of datasets and software assemblages I may have well have missed something, but lacking new information I have concluded:
1.  you guys have done a great job of making efficient use of the computer resources requested by the user.
2.  The 5 days is the 5 days... it is just a big, diverse, data set relative to a dual socket 6242R Xeon server... and that is just fine for our situation... it is a "captive" machine devoted to these sorts of tasks for our group.
Thanks!
Best Regards,

**Comment by nucleoli2** [comment]
Re: sequences, sizes of files, and possible fixes...
Apologies if I have this wrong, but in step 10 we seem to be at the point of counting the sequences in the sam directory.  The sam directory for this dataset consists of 971 GB in 96 files, makeing the "average" sam file about 10.1 GB;  when sqm_counter runs to completion it reports ~600 million sequences (599,711,049).
If I am reading the Perl correctly it seems that each spawned counting subprocess opens a sam file, loads it up, and starts counting.   Let's say that the OS, OS buffers/overhead, whatever SqueezeMeta step 10 has in memory comes to, maybe sorta/kinda 60 GB.  So 392-60 = 332 GB should be available to 10.mapsamples.  

So, 332 GB/10.1 GB per sam file = ~33 sam files and the RAM is full.

The swap file on this system is pretty small.  (If you are swapping vigorously you are dead anyway, so why tie up the space?)

This crude estimate suggests that filling up RAM + swap with sam files may not be hard to do with this dataset.

This seems to match what I see.  The sequence-dataset-SqueezeMeta-run resides on a very high speed silicon storage device to give rapid throughput,  but it still shocks me how quickly the job is killed by the OS once the "nnnn reads counted" messages start appearing...  just a very few seconds elapse before the SqueezeMeta job is terminated.

For what it is worth, in my opinion your suggested path to resolving the issue at hand in 10.mapsamples.pl seems right on the dot...  certainly the path that I would take.  Something like have the dispatching routine inquire of the OS as to the total memory available to the application, add some margin headroom to that number just to be sure, then file by file spawn subprocesses (staying below the max threadcount requested by the user) until the next process to be spawned would exceed the computed memory use target;  as the counting subprocesses finish, spawn more staying below that memory use target based on actual file sizes.  The number of threads in use at a given time would dynamically vary by the sizes of the files being processed at that time, just as you would want it.  For this dataset it seems unlikely that it would ever use all, eg, 70 threads, but it would still use as many threads as files fit in memory would allow, maximizing throughput.

Happy to test if that is useful to you (or just remain quiet if that helps more).

Again, many thanks for all of your hard work on SqueezeMeta.  Very much appreciated!

Best regards,

**Comment by jtamames** [comment]
Thank you very much @nucleoli2, your benchmarking is very appreciated and will help us to improve SqueezeMeta. I will start working on that memory check for step 10 as soon as I finish the implementation of refurnished assembly for version 1.6. 
Best,
Javier

**Comment by nucleoli2** [comment]
Excellent.

I am at your service as things develop...

Thanks!!

Best regards

**Comment by luernerliu** [comment]
Hi Developers，
     I also got  the  similar problem when I ran the individual perl scripts `10.mapsamples.pl` . The RAM of HPC cluster node was bout 4T, but the "sqm_countert" step used almost  all the memory(87.7%mem, percentage still rising). I also tried to chang the threads number as @nucleoli2 mentioned and the mapper. But it seems to take up the entire memory, so i have to kill the process . 
    Here is the info of my data:
    The 01.SoMeta.fasta was 76G in total to build reference .
   The first sample SO001A.sam: 75G
    Threads number: 60 threads
    the syslog as below
[10.mapsamples.sh.log](https://github.com/jtamames/SqueezeMeta/files/8552847/10.mapsamples.sh.log)
![image](https://user-images.githubusercontent.com/26041248/165051152-ad19c2d6-088f-4fd8-a4d3-adca6c105655.png)

 Thanks your hard working and hope it helps you to improve the program

Best regards

**Comment by fpusan** [comment]
This has been alleviated in 45b1817, which will be included in the upcoming v1.6.3. Memory usage will still increase with the number of threads, but it should be much more controlled now.
