### ISSUE TITLE
finding gene into a metagenome data

### ISSUE THREAD

**Issue by ghazalaziz** [jtamames/SqueezeMeta#450]
Hi friends!
I have metagenome data of probiotics. I want to search for the probiotic genes How could i do that? recently i am using the blastX option in NCBI, but I am failing to. 
Further,
the genes that i am trying to find in them need to be species specific or i can use them as general genes across multiple generas.??
can I have some helping material for that?

**Comment by ghazalaziz** [comment]
do we have any option for the windows?

**Comment by fpusan** [comment]
Not oficially, the main pipeline must be ran on Linux.

Afterwards, the analysis using R and `SQMtools` can be done in windows if you copy the right files...
