### ISSUE TITLE
Step 1 error reading inputs

### ISSUE THREAD

**Issue by phagelab** [jtamames/SqueezeMeta#452]
Hello, 
I've tried running SqueezeMeta for a dataset of 50 samples through both coassembly and sequential modes and encountered errors with Step 1 in both cases. There appears to be a problem reading the input files but I'm unsure why this is. I've attached the log files for the coassembly and sequential runs. Any help would be appreciated.

The error message from the latest run (sequential):
  Sample IG-2-2
  Running Megahit (Li et al 2015, Bioinformatics 31(10):1674-6) for IG-2-2
Error running command:    /home/plzrja/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/megahit/megahit  -1 /home/plzrja/shigella/20220326_shigella_merged/temp/par1..gz -2 /home/plzrja/shigella/20220326_shigella_merged/temp/par2..gz --k-list 29,39,59,79,99,119,141 -t 12 -o /home/plzrja/shigella/20220326_shigella_merged/data/megahit >> /home/plzrja/shigella/20220326_shigella_merged/syslog 2>&1 at /home/plzrja/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/01.run_assembly_merged.pl line 94.
Stopping in STEP1 -> 01.run_assembly_merged.pl. Program finished abnormally

  If you don't know what went wrong or want further advice, please look for similar issues in https://github.com/jtamames/SqueezeMeta/issues
  Feel free to open a new issue if you don't find the answer there. Please add a brief description of the problem and upload the /home/plzrja/shigella/20220326_shigella_merged/syslog file (zip it first)
Died at /home/plzrja/miniconda3/envs/SqueezeMeta/bin/SqueezeMeta.pl line 1381.

[syslog (merged).txt](https://github.com/jtamames/SqueezeMeta/files/8355595/syslog.merged.txt)
[syslog (coassembly).txt](https://github.com/jtamames/SqueezeMeta/files/8355596/syslog.coassembly.txt)

**Comment by fpusan** [comment]
Can you check whether
`/home/plzrja/shigella/20220323_shigella_merged/data/raw_fastq/IG-2-2.01.fastp.hisat.1.fq.gz `
and
`/home/plzrja/shigella/20220323_shigella_merged/data/raw_fastq/IG-2-2.01.fastp.hisat.2.fq.gz`
are ok?

**Comment by phagelab** [comment]
could you be more specific about what to check for please? The only difference I can see from other files where there weren't errors is that the file size is quite small (79.2 Mb and 95.9 Mb respectively). The files appear to be readable though.

**Comment by fpusan** [comment]
Can you gunzip them?
The message you get for the coassembly is `gzip: /home/plzrja/shigella/20220323_shigella_merged/temp/par1..gz: unexpected end of file`
This, combined with what you say about them being quite small makes me wonder whether they can be truncated.
I assume you don't have disk space problems?

**Comment by phagelab** [comment]
I see, thanks. 

There is an error with gunzip for both files

gzip: IG-2-2.01.fastp.hisat.1.fq.gz: unexpected end of file
gzip: IG-2-2.01.fastp.hisat.2.fq.gz: unexpected end of file

Looking at the original fastq files for these samples, they are smaller than for other samples (about 1/5th the size approximately).

**Comment by phagelab** [comment]
Also, no disk space problems - I recently upgraded to at 17Tb HD.

**Comment by fpusan** [comment]
The problem clearly lies with those files then. Hopefully you have a backup somewhere, otherwise you can remove them from the analysis

**Comment by phagelab** [comment]
Looks that way. Many thanks for your help.
