### ISSUE TITLE
Anyone is having trouble loading DESeq2 in SqueezeMeta R environment?

### ISSUE THREAD

**Issue by agg437** [jtamames/SqueezeMeta#455]
Hello there,
I was trying to install DESeq2 with BiocManager along with SQMtools (so having both libraries in SqueezeMeta environment) but I am not being lucky, it seems to be missing locfit package dependency (which it is not available for R 3.6.3 any more). I looked for in blogs but I did not find a solution, anyone knows a workaround about this?  
Best regards,
Ana

**Comment by fpusan** [comment]
Try an older version of locfit from
https://cran.r-project.org/src/contrib/Archive/locfit/

**Comment by agg437** [comment]
For me seems to work with locfit_1.5-9.2.tar.gz version, in case anyone else need it, this is the code:

```
install.packages('devtools')
library(devtools)
devtools::install_version("locfit", version = "1.5-9.2", repos = "http://cran.us.r-project.org")
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("DESeq2")
library(DESeq2)

```

**Comment by fpusan** [comment]
Thanks for the input! Glad it works now
