### ISSUE TITLE
Problem loading SQMtools with Rstudio Server

### ISSUE THREAD

**Issue by LunavdL** [jtamames/SqueezeMeta#457]
Hi,

I am running my first SqueezeMeta run and I wanted to check the test samples in R using SQMtools. 
I installed SqueezeMeta with conda on our server. Running test_install.py gave no problems:

```
Checking that all the required R libraries are available in this environment
        R -h OK
        R -e 'library(doMC)' OK
        R -e 'library(ggplot2)' OK
        R -e 'library(data.table)' OK
        R -e 'library(reshape2)' OK
        R -e 'library(pathview)' OK
        R -e 'library(DASTool)' OK
        R -e 'library(SQMtools)' OK

Checking that SqueezeMeta is properly configured... checking database in /home/lvdrloos/Documents/SqueezeMeta_db/db
        nr.db OK
        CheckM manifest OK
        LCA_tax DB OK

All checks successful
```

I am trying to load the library in Rstudio Server (on the same server that has SqueezeMeta installed) with `library(SQMtools)`, but this gives the following error: 
`Error in library(SQMtools) : there is no package called ‘SQMtools’`

I tried to use R CMD INSTALL as in issue [#265](https://github.com/jtamames/SqueezeMeta/issues/265), which gave no errors, but I still can't load the library in Rstudio Server.

Is there something I need to do additionally to get SQMtools working in Rstudio Server?

Best regards,
Luna

**Comment by fpusan** [comment]
Hi!
So I think Rstudio will be using a different version of R than conda, hence the libraries there won't be available in RStudio.
You should first get the dependencies (data.table, reshape2, ggplot2 and pathview, if I recall correctly) and then install SQMtools manually within Rstudio, like shown in https://stackoverflow.com/questions/43150738/installing-an-r-package-from-local-unzipped-folder

**Comment by LunavdL** [comment]
Yes, this worked perfectly! Thank you for your super fast reply.
