### ISSUE TITLE
Optimising storage

### ISSUE THREAD

**Issue by mradz19** [jtamames/SqueezeMeta#464]
Would it be possible to run squeezemeta without copying the fastq files to the /data/rawfastq directory? It doubles the amount of storage required which can cause issues when analysing a lot of samples.

Is there a reason why squeezemeta can't just read and use the files from the directory provided by the -f flag when starting a run?

**Comment by jtamames** [comment]
Hello!
Yep, that's true. There were some technical issues but I will not bore you with that. Upcoming version 1.6, due in the coming weeks, will fix that. It does not copy anything and works with user's files.
Best,
J
