### ISSUE TITLE
kegg.funcover is empty!

### ISSUE THREAD

**Issue by aalkin2001** [jtamames/SqueezeMeta#466]
I'm running metagenomic analysis with Sqeezemeta on data generated from nanopore minion sequence and using flye as the assembler. I got the error message below: How do I solve this issue?  

Stopping in STEP12 -> 12.funcover.pl. /SqueezeMeta/metagenome_analysis/trial/trial_output/results/12.trial_output.cog.funcover and/or /home/akinola/mnt/data/tblab/working_dir/TFRI_Microbiome_analysis/SqueezeMeta/metagenome_analysis/trial/trial_output/results/12.trial_output.[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/8521969/syslog.zip)

**Comment by jtamames** [comment]
This is because you only have 4 contigs resulting from the assembly. Flye is a very strict assembler, but nevertheless you just have 244 Mb of sequence. If this is a metagenome, no way this can produce an usable assembly. Use sqm_longreads.pl to analyze the reads instead.
