### ISSUE TITLE
Taxonomic assignment

### ISSUE THREAD

**Issue by anacristinareis** [jtamames/SqueezeMeta#467]
Hello, 

I have a question considering the taxonomic assignment of one of my samples, where the % of contigs classified until the species level is higher than the % of classification at the genus and family levels. 

Contigs at superkingdom (k) rank	142907 (82.1%), in 4 superkingdoms
Contigs at phylum (p) rank	124046 (71.3%), in 119 phyla
Contigs at class (c) rank	79321 (45.6%), in 94 classes
Contigs at order (o) rank	59038 (33.9%), in 149 orders
Contigs at family (f) rank	38412 (22.1%), in 245 families
Contigs at genus (g) rank	19400 (11.1%), in 460 genera
Contigs at species (s) rank	47639 (27.4%), in 540 species

I don't understand how is this possible. Can you, please, provide some explanation.

Best regards,
Ana Reis

**Comment by jtamames** [comment]
Hello
Weird indeed... Could you share your 06*wranks file with me?

**Comment by anacristinareis** [comment]
Hello,

Thanks for the quick reply. The requested file is attached.
[06.GL4.fun3.tax.txt](https://github.com/jtamames/SqueezeMeta/files/8531095/06.GL4.fun3.tax.txt)

Ana Reis

**Comment by anacristinareis** [comment]
Considering the nature of my samples, the uncultured/unclassified bacteria results are expected.
 
Thanks for your help.

Best regards,
Ana Reis

**Comment by jtamames** [comment]
Closing issue, feel free to reopen if you need further help
