### ISSUE TITLE
Permission error in a mounted folder

### ISSUE THREAD

**Issue by SungUk** [jtamames/SqueezeMeta#468]
Hello, I got an error when I run SqueezeMeta in a mounted folder.
When I run SqueezeMeta in a non-mounted folder, I could finish the job, although I used only one sample due to little free space.
Can you handle it?
##############syslog

SqueezeMeta v1.5.1, Jan 2022 - (c) J. Tamames, F. Puente-SÃ¡nchez CNB-CSIC, Madrid, SPAIN

Please cite: Tamames & Puente-Sanchez, Frontiers in Microbiology 10.3389 (2019). doi: https://doi.org/10.3389/fmicb.2018.03349

Run started Fri Apr 22 10:43:47 2022 in coassembly mode
Command: /home/phyzen/anaconda3/envs/SqueezeMeta/bin/SqueezeMeta.pl -m coassembly -p TestProject -s TestSample2.txt -f /home/phyzen/data5/metagenome/wgs/2020metagenome/rawdata -t 20
Project: TestProject
Map file: TestSample2.txt
Fastq directory: /home/phyzen/data5/metagenome/wgs/2020metagenome/rawdata
Options: threads=20; contiglen=200; assembler=megahit; mapper=bowtie; COGS; KEGG; PFAM;
[0 seconds]: STEP0 -> SqueezeMeta.pl
Coppying files: cp /home/phyzen/data5/metagenome/wgs/2020metagenome/rawdata/1_SuWon_M_1.fastq.gz /home/phyzen/data5/metagenome/wgs/2020metagenome/TestProject/data/raw_fastq/1_SuWon_M_1.fastq.gz
Coppying files: cp /home/phyzen/data5/metagenome/wgs/2020metagenome/rawdata/1_SuWon_M_2.fastq.gz /home/phyzen/data5/metagenome/wgs/2020metagenome/TestProject/data/raw_fastq/1_SuWon_M_2.fastq.gz
Coppying files: cp /home/phyzen/data5/metagenome/wgs/2020metagenome/rawdata/2_HwaSeong_M_1.fastq.gz /home/phyzen/data5/metagenome/wgs/2020metagenome/TestProject/data/raw_fastq/2_HwaSeong_M_1.fastq.gz
Coppying files: cp /home/phyzen/data5/metagenome/wgs/2020metagenome/rawdata/2_HwaSeong_M_2.fastq.gz /home/phyzen/data5/metagenome/wgs/2020metagenome/TestProject/data/raw_fastq/2_HwaSeong_M_2.fastq.gz
Coppying files: cp /home/phyzen/data5/metagenome/wgs/2020metagenome/rawdata/3_GiHeung_M_1.fastq.gz /home/phyzen/data5/metagenome/wgs/2020metagenome/TestProject/data/raw_fastq/3_GiHeung_M_1.fastq.gz
Coppying files: cp /home/phyzen/data5/metagenome/wgs/2020metagenome/rawdata/3_GiHeung_M_1.fastq.gz /home/phyzen/data5/metagenome/wgs/2020metagenome/TestProject/data/raw_fastq/3_GiHeung_M_1.fastq.gz
Coppying files: cp /home/phyzen/data5/metagenome/wgs/2020metagenome/rawdata/4_GuGal_M_1.fastq.gz /home/phyzen/data5/metagenome/wgs/2020metagenome/TestProject/data/raw_fastq/4_GuGal_M_1.fastq.gz
Coppying files: cp /home/phyzen/data5/metagenome/wgs/2020metagenome/rawdata/4_GuGal_M_2.fastq.gz /home/phyzen/data5/metagenome/wgs/2020metagenome/TestProject/data/raw_fastq/4_GuGal_M_2.fastq.gz
Coppying files: cp /home/phyzen/data5/metagenome/wgs/2020metagenome/rawdata/5_AnPyeong_M_1.fastq.gz /home/phyzen/data5/metagenome/wgs/2020metagenome/TestProject/data/raw_fastq/5_AnPyeong_M_1.fastq.gz
Coppying files: cp /home/phyzen/data5/metagenome/wgs/2020metagenome/rawdata/5_AnPyeong_M_2.fastq.gz /home/phyzen/data5/metagenome/wgs/2020metagenome/TestProject/data/raw_fastq/5_AnPyeong_M_2.fastq.gz
Coppying files: cp /home/phyzen/data5/metagenome/wgs/2020metagenome/rawdata/6_OCheon_M_1.fastq.gz /home/phyzen/data5/metagenome/wgs/2020metagenome/TestProject/data/raw_fastq/6_OCheon_M_1.fastq.gz
Coppying files: cp /home/phyzen/data5/metagenome/wgs/2020metagenome/rawdata/6_OCheon_M_2.fastq.gz /home/phyzen/data5/metagenome/wgs/2020metagenome/TestProject/data/raw_fastq/6_OCheon_M_2.fastq.gz
Samples:6
Mode:coassembly
Merging files for coassembly: cat /home/phyzen/data5/metagenome/wgs/2020metagenome/TestProject/data/raw_fastq/1_SuWon_M_1.fastq.gz /home/phyzen/data5/metagenome/wgs/2020metagenome/TestProject/data/raw_fastq/2_HwaSeong_M_1.fastq.gz /home/phyzen/data5/metagenome/wgs/2020metagenome/TestProject/data/raw_fastq/4_GuGal_M_1.fastq.gz /home/phyzen/data5/metagenome/wgs/2020metagenome/TestProject/data/raw_fastq/5_AnPyeong_M_1.fastq.gz /home/phyzen/data5/metagenome/wgs/2020metagenome/TestProject/data/raw_fastq/6_OCheon_M_1.fastq.gz  > /home/phyzen/data5/metagenome/wgs/2020metagenome/TestProject/data/raw_fastq/par1.fastq.gz; cat /home/phyzen/data5/metagenome/wgs/2020metagenome/TestProject/data/raw_fastq/1_SuWon_M_2.fastq.gz /home/phyzen/data5/metagenome/wgs/2020metagenome/TestProject/data/raw_fastq/2_HwaSeong_M_2.fastq.gz /home/phyzen/data5/metagenome/wgs/2020metagenome/TestProject/data/raw_fastq/3_GiHeung_M_1.fastq.gz /home/phyzen/data5/metagenome/wgs/2020metagenome/TestProject/data/raw_fastq/4_GuGal_M_2.fastq.gz /home/phyzen/data5/metagenome/wgs/2020metagenome/TestProject/data/raw_fastq/5_AnPyeong_M_2.fastq.gz /home/phyzen/data5/metagenome/wgs/2020metagenome/TestProject/data/raw_fastq/6_OCheon_M_2.fastq.gz  > /home/phyzen/data5/metagenome/wgs/2020metagenome/TestProject/data/raw_fastq/par2.fastq.gz; 

[48 minutes, 34 seconds]: STEP1 -> 01.run_assembly.pl (megahit)
Stopping in STEP1 -> 01.run_assembly.pl. Program finished abnormally
_____________

System information:
_____________

Tree for the project:
2020metagenome/TestProject/data/raw_fastq/par1.fastq.gz -2 /home/phyzen/data5/metagenome/wgs/2020metagenome/TestProject/data/raw_fastq/par2.fastq.gz -t 20 -o /home/phyzen/data5/metagenome/wgs/2020metagenome/TestProject/data/megahit >> /home/phyzen/data5/metagenome/wgs/2020metagenome/TestProject/syslog 2>&1
2022-04-22 11:32:22 - MEGAHIT v1.2.9
2022-04-22 11:32:22 - Using megahit_core with POPCNT and BMI2 support
Traceback (most recent call last):
  File "/home/phyzen/anaconda3/envs/SqueezeMeta/SqueezeMeta/bin/megahit/megahit", line 1039, in <module>
    main()
  File "/home/phyzen/anaconda3/envs/SqueezeMeta/SqueezeMeta/bin/megahit/megahit", line 989, in main
    build_library()
  File "/home/phyzen/anaconda3/envs/SqueezeMeta/SqueezeMeta/bin/megahit/megahit", line 265, in checked_or_call
    func(*args, **kwargs)
  File "/home/phyzen/anaconda3/envs/SqueezeMeta/SqueezeMeta/bin/megahit/megahit", line 724, in build_library
    create_fifo('pe1', i, inpipe_cmd(opt.pe1[i]))
  File "/home/phyzen/anaconda3/envs/SqueezeMeta/SqueezeMeta/bin/megahit/megahit", line 711, in create_fifo
    os.mkfifo(fifo_path)
PermissionError: [Errno 1] Operation not permitted
Linux Sever107 5.13.0-39-generic #44~20.04.1-Ubuntu SMP Thu Mar 24 16:43:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
[4.0K Apr 22 10:43]  /home/phyzen/data5/metagenome/wgs/2020metagenome/TestProject
├── [  81 Apr 22 11:32]  data
│   ├── [ 506 Apr 22 10:43]  00.TestProject.samples
│   ├── [ 118 Apr 22 11:32]  megahit
│   │   ├── [   7 Apr 22 11:32]  checkpoints.txt
│   │   ├── [  10 Apr 22 11:32]  intermediate_contigs
│   │   ├── [ 107 Apr 22 11:32]  log
│   │   ├── [1.0K Apr 22 11:32]  options.json
│   │   └── [  30 Apr 22 11:32]  tmp
│   │       └── [ 365 Apr 22 11:32]  reads.lib
│   └── [4.0K Apr 22 11:22]  raw_fastq
│       ├── [5.2G Apr 22 10:46]  1_SuWon_M_1.fastq.gz
│       ├── [5.8G Apr 22 10:50]  1_SuWon_M_2.fastq.gz
│       ├── [4.8G Apr 22 10:52]  2_HwaSeong_M_1.fastq.gz
│       ├── [5.4G Apr 22 10:55]  2_HwaSeong_M_2.fastq.gz
│       ├── [4.5G Apr 22 10:59]  3_GiHeung_M_1.fastq.gz
│       ├── [4.7G Apr 22 11:01]  4_GuGal_M_1.fastq.gz
│       ├── [5.2G Apr 22 11:04]  4_GuGal_M_2.fastq.gz
│       ├── [4.6G Apr 22 11:07]  5_AnPyeong_M_1.fastq.gz
│       ├── [5.0G Apr 22 11:10]  5_AnPyeong_M_2.fastq.gz
│       ├── [4.1G Apr 22 11:12]  6_OCheon_M_1.fastq.gz
│       ├── [4.5G Apr 22 11:15]  6_OCheon_M_2.fastq.gz
│       ├── [ 23G Apr 22 11:22]  par1.fastq.gz
│       └── [ 30G Apr 22 11:32]  par2.fastq.gz
├── [  10 Apr 22 10:43]  ext_tables
├── [  28 Apr 22 10:43]  intermediate
│   └── [  10 Apr 22 10:43]  binners
├── [ 193 Apr 22 11:32]  methods.txt
├── [2.9K Apr 22 10:43]  parameters.pl
├── [  59 Apr 22 11:32]  progress
├── [  10 Apr 22 10:43]  results
├── [8.1K Apr 22 10:43]  SqueezeMeta_conf.pl
├── [5.8K Apr 22 11:32]  syslog
└── [  10 Apr 22 10:43]  temp

10 directories, 23 files

**Comment by fpusan** [comment]
What OS are you using? I've seen this happen in windows WSL2, see #308.
Maybe you can try adding `-assembly_options "--tmp-dir /tmp/"` when running SqueezeMeta.

**Comment by SungUk** [comment]
I am using Ubuntu and the mounted folder is in Redhat system. I tried adding -assembly_options "--tmp-dir /tmp/" when running SM. I just worry that the size of files can reach the limit of the HDD. After checking the result, I will edit this comment.

**Comment by fpusan** [comment]
Closing this issue, we'll continue in the other one
