### ISSUE TITLE
DAStool did not generate results

### ISSUE THREAD

**Issue by aalkin2001** [jtamames/SqueezeMeta#470]
Hi,

I ran Squeezemeta on data generated from the Nanopore Minion sequencer using the flye assembler option. The run was completed successfully but steps 17, 18, and 19 were missed in the resulting output. Below is the error message, and I am also attaching the Syslog.

/miniconda3/lib/R/bin/exec/R: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory
Can't open /home/akinola/mnt/data/tblab/working_dir/TFRI_Microbiome_analysis/SqueezeMeta/complete_data/complete_output/results/DAS/complete_output_DASTool_bins directory, no DAStool results
[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/8541700/syslog.zip)

WARNING: File /home/akinola/mnt/data/tblab/working_dir/TFRI_Microbiome_analysis/SqueezeMeta/complete_data/complete_output/results/DAS/complete_output_DASTool_bins/ is empty!. DAStool did not generate results
Skipping BIN TAX ASSIGNMENT: DAS_Tool did not predict bins.
Skipping CHECKM: DAS_Tool did not predict bins.
Skipping BIN TABLE CREATION: (You already know: DAS_Tool did not predict bins.)

**Comment by fpusan** [comment]
Try running
`conda install -c conda-forge readline=6.2`
inside the SqueezeMeta environment, and then restarting the project from step 14.

**Comment by aalkin2001** [comment]
The Squeezemeta script was not run in a conda environment, It was installed with sudo, but it is R that I have in conda environment.

**Comment by fpusan** [comment]
Then the problem is possibly related to how you installed it. Maybe installing readline will still fix your R in conda.
Otherwise I might not be able to help you

**Comment by aalkin2001** [comment]
Also, what could be the possible cause of this error message as well?
UNRECOGNIZED binner maxbin (valid ones are )

**Comment by jtamames** [comment]
Your SqueezeMeta_conf.pl file is not correct. Which version of SqueezeMet are you using?

**Comment by aalkin2001** [comment]
SqueezeMeta v1.4.0, May 2021

**Comment by jtamames** [comment]
Could you copy here the SqueezeMeta_conf.pl file?

**Comment by aalkin2001** [comment]
[SqueezeMeta_conf.zip](https://github.com/jtamames/SqueezeMeta/files/8543797/SqueezeMeta_conf.zip)

**Comment by jtamames** [comment]
Did you mix vesrsions somehow? Because the error message you cite only appears in version 1.5

**Comment by aalkin2001** [comment]
Okay, I will uninstall the current SqueezeMeta, and re-install it again with conda. I hope that will solve the whole issue. Thank you for your time. This issue can now be closed.
