### ISSUE TITLE
SQMtools for R  on Windows 

### ISSUE THREAD

**Issue by ewelinarubin** [jtamames/SqueezeMeta#471]
I am following your instructions on downloading the SQMtools. I am using R. v 4.1.3 for windows 
I got the SQMtools.zip file but when I tried to but when I got Packages --> install packages from local file ... -- I select the zip folder and nothing happens.
I also tried the following:

setwd("C:/Users/eweli/Documents/R")
install.packages("SQMtools.zip", repos = NULL, type = "win.binary")

The response was:
Installing package into ‘C:/Users/eweli/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)

But the package was unavailable 

And I tried this as well :

> install.packages("SQMtools.zip", repos = NULL, type = "win.binary", lib="C:/Users/eweli/Documents/R/R-4.1.2/library")
Warning in install.packages("SQMtools.zip", repos = NULL, type = "win.binary",  :
  'lib = "C:/Users/eweli/Documents/R/R-4.1.2/library"' is not writable
> library(SQMtool)
Error in library(SQMtool) : there is no package called ‘SQMtool’

Any ideas what else to try to install it ?

**Comment by fpusan** [comment]
Try running RStudio as an administrator.

**Comment by jtamames** [comment]
Also, notice that the name of the library is "SQMtools"

**Comment by ewelinarubin** [comment]
Thank you for your response 
I did start the Rstudio and an administrator and tried again: (I fixed the typo too -- sorry about that) 


setwd("C:/Users/eweli/Documents/R")
install.packages("SQMtools.zip", repos = NULL, type = "win.binary", lib="C:/Users/eweli/Documents/R/R-4.1.3/library")
Warning in install.packages :
 'lib = "C:/Users/eweli/Documents/R/R-4.1.3/library"' is not writable
 library(SQMtools)
Error in library(SQMtools) : ‘SQMtools’ is not a valid installed package


Still does not seem to work.

I found someone had a similar problem with a package written for Mac -- see here 
https://stat.ethz.ch/pipermail/r-help/2013-June/355302.html

**You haven't shown us any error, but if the package doesn't work, it 
might be because it wasn't built properly.  A .zip file that works on a 
Mac is unlikely to also work on Windows:  Windows uses the .zip 
extension for *binary* installs.**


Is there any chance that the package will never work with windows ?

**Comment by fpusan** [comment]
As a note, the package can definitely be installed in windows

**Comment by ewelinarubin** [comment]
If I do not specify "lib=" I get the message below "(as lib is unspecified") but it does not matter because it is trying to install to a local library (see below) but then nothing happens  (no error and no ability to load the library) 

> setwd("C:/Users/eweli/Documents/R")
> install.packages("SQMtools.zip", repos = NULL, type = "win.binary")
Installing package into ‘C:/Users/eweli/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
> library(SQMtools)
Error in library(SQMtools) : ‘SQMtools’ is not a valid installed package


So that is why I tried to give it to the library directory like this 

setwd("C:/Users/eweli/Documents/R")
install.packages("SQMtools.zip", repos = NULL, type = "win.binary", lib="C:/Users/eweli/Documents/R/win-library/4.1")

There is no errors and nothing happens 

library(SQMtools)
Error in library(SQMtools) : ‘SQMtools’ is not a valid installed package

**Comment by fpusan** [comment]
I wonder if this is because of the R version, SQMtools needs R>3.2 but might fail with R>4.0
Just in case try the following.
Edit the `DESCRIPTION` file inside the zip file and change line 11 to say
`Depends: R (>= 4.0.0)`
Then try to reinstall.

**Comment by ewelinarubin** [comment]
Thanks so much for troubleshooting this with me. I unzip the file, change the DESCRIPTION, then zipped the folder and tried everything as above. 
Still, nothing happens. 
I could try installing the old R version and see if that works?

**Comment by fpusan** [comment]
Before that, check
`.libPaths()`
in your R environment

**Comment by ewelinarubin** [comment]
Ok when I type 

.libPaths()

I get this 


[1] "C:/Users/eweli/Documents/R/win-library/4.1"
[2] "C:/Program Files/R/R-4.1.3/library"

**Comment by ewelinarubin** [comment]
Yes the SQMtools folder is in the above directory (it was unzipped) 
And yes -- I just did install all the dependencies.
Do you think I can just try running the commands ? and see if it works?

**Comment by fpusan** [comment]
Can you try the following?
`install.packages("SQMtools.zip", repos = NULL, type = "source")`

**Comment by ewelinarubin** [comment]
I am sorry - still the same problem 

setwd("C:/Users/eweli/Documents/R")
install.packages("SQMtools.zip", repos = NULL, type = "source")
Installing package into ‘C:/Users/eweli/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
> library(SQMtools)
Error in library(SQMtools) : ‘SQMtools’ is not a valid installed package
>

**Comment by ewelinarubin** [comment]
[SQMtools.zip](https://github.com/jtamames/SqueezeMeta/files/8556586/SQMtools.zip)

I am attaching the zip file that I downloaded - -can you check if it looks oK-- maybe the problem happens during download

**Comment by fpusan** [comment]
Alternatively try with this
[SQMtools_0.7.1.tar.gz](https://github.com/jtamames/SqueezeMeta/files/8556632/SQMtools_0.7.1.tar.gz)
`install.packages("/path/to/uncompressed/SQMtools_0.7.1.tar.gz", repos = NULL, type = "source")`

**Comment by ewelinarubin** [comment]
the installation of the uncompressed folder worked!! 

install.packages("/path/to/uncompressed/SQMtools", repos = NULL, type = "source")

Thank you so much for sticking with me until it got solved

**Comment by fpusan** [comment]
Glad to hear! Closing issue

**Comment by Rohit-Satyam** [comment]
It would be great if this can be updated in the documentation.
