### ISSUE TITLE
database configuration not working

### ISSUE THREAD

**Issue by danfrks** [jtamames/SqueezeMeta#472]
Hello jtamames,

I am struggling to configure my database, downloaded as per #246  

The SqueezeMeta_conf.pl and SqueezeMeta_conf_original.pl files are not getting updated. Both are **empty files** after the below code was run.

Do you know what the issue might be?

------------------------------------------------

(SqueezeMeta) danielfarkas@urlws00002:~/databases/SqueezeMeta$ sudo perl /home/danielfarkas/miniconda3/envs/SqueezeMeta/SqueezeMeta/utils/install_utils/configure_nodb.pl /home/danielfarkas/databases/SqueezeMeta/db
Make sure that /home/danielfarkas/databases/SqueezeMeta/db contains all the database files (nr.dmnd, etc...)

Downloading and unpacking RDP classifier...
--2022-04-25 13:14:19--  http://silvani.cnb.csic.es/SqueezeMeta//classifier.tar.gz
Resolving silvani.cnb.csic.es (silvani.cnb.csic.es)... 150.244.82.96
Connecting to silvani.cnb.csic.es (silvani.cnb.csic.es)|150.244.82.96|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 154722472 (148M) [application/x-gzip]
Saving to: ‘/home/danielfarkas/miniconda3/envs/SqueezeMeta/SqueezeMeta/lib/classifier.tar.gz’

classifier.tar.gz                                    100%[=====================================================================================================================>] 147.55M  3.50MB/s    in 44s     

2022-04-25 13:15:02 (3.38 MB/s) - ‘/home/danielfarkas/miniconda3/envs/SqueezeMeta/SqueezeMeta/lib/classifier.tar.gz’ saved [154722472/154722472]

--2022-04-25 13:15:02--  http://silvani.cnb.csic.es/SqueezeMeta//classifier.md5
Resolving silvani.cnb.csic.es (silvani.cnb.csic.es)... 150.244.82.96
Connecting to silvani.cnb.csic.es (silvani.cnb.csic.es)|150.244.82.96|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 33 [application/x-md5]
Saving to: ‘/home/danielfarkas/miniconda3/envs/SqueezeMeta/SqueezeMeta/lib/classifier.md5’

classifier.md5                                       100%[=====================================================================================================================>]      33  --.-KB/s    in 0s      

2022-04-25 13:15:02 (2.97 MB/s) - ‘/home/danielfarkas/miniconda3/envs/SqueezeMeta/SqueezeMeta/lib/classifier.md5’ saved [33/33]

classifier/
classifier/classifier.jar
classifier/lib/
classifier/lib/TaxonomyTree.jar
classifier/lib/commons-cli-1.2.jar
classifier/lib/ReadSeq.jar
classifier/lib/jfreechart-1.0.13.jar
classifier/lib/AlignmentTools.jar
classifier/lib/jcommon-1.0.16.jar
classifier/lib/commons-io-2.4.jar

Updating configuration...
Done

**Comment by danfrks** [comment]
Here is the output of test_install.pl 

------------------------------

(SqueezeMeta) danielfarkas@urlws00002:~/databases/SqueezeMeta$ sudo perl /home/danielfarkas/miniconda3/envs/SqueezeMeta/SqueezeMeta/utils/install_utils/test_install.pl

Checking the OS
	linux OK

Checking that tree is installed
	tree --help OK

Checking that ruby is installed
	ruby -h OK

Checking that java is installed
	java -h OK

Checking that all the required perl libraries are available in this environment
	perl -e 'use Term::ANSIColor' OK
	perl -e 'use DBI' OK
	perl -e 'use DBD::SQLite::Constants' OK
	perl -e 'use Time::Seconds' OK
	perl -e 'use Tie::IxHash' OK
	perl -e 'use Linux::MemInfo' OK
	perl -e 'use Getopt::Long' OK
	perl -e 'use File::Basename' OK
	perl -e 'use DBD::SQLite' OK
	perl -e 'use Data::Dumper' OK
	perl -e 'use Cwd' OK
	perl -e 'use XML::LibXML' OK
	perl -e 'use XML::Parser' OK
	perl -e 'use Term::ANSIColor' OK

Checking that all the required python libraries are available in this environment
	python3 -h OK
	python3 -c 'import numpy' OK
	python3 -c 'import scipy' OK
	python3 -c 'import matplotlib' OK
	python3 -c 'import dendropy' OK
	python3 -c 'import pysam' OK
	python3 -c 'import Bio.Seq' OK
	python3 -c 'import pandas' OK
	python3 -c 'import cython' OK
	python3 -c 'import future' OK

Checking that all the required R libraries are available in this environment
	R -h OK
	R -e 'library(doMC)' OK
	R -e 'library(ggplot2)' OK
	R -e 'library(data.table)' OK
	R -e 'library(reshape2)' OK
	R -e 'library(pathview)' OK
	R -e 'library(DASTool)' NOT OK
		Missing R library "DASTool"
	R -e 'library(SQMtools)' NOT OK
		Missing R library "SQMtools"

Use of uninitialized value $databasepath in concatenation (.) or string at /home/danielfarkas/miniconda3/envs/SqueezeMeta/SqueezeMeta/utils/install_utils/test_install.pl line 129.
Checking that SqueezeMeta is properly configured... checking database in 
Use of uninitialized value $databasepath in concatenation (.) or string at /home/danielfarkas/miniconda3/envs/SqueezeMeta/SqueezeMeta/utils/install_utils/test_install.pl line 130.
Use of uninitialized value $databasepath in concatenation (.) or string at /home/danielfarkas/miniconda3/envs/SqueezeMeta/SqueezeMeta/utils/install_utils/test_install.pl line 132.
	SqueezeMeta_conf.pl says that databases are located in  but we can't find nr.db there, or it is corrupted

------------------------------------------------------------------------------

WARNING: Some SqueezeMeta dependencies could not be found in your environment!
	- Missing R library "DASTool"
	- Missing R library "SQMtools"
	SqueezeMeta_conf.pl says that databases are located in  but we can't find nr.db there, or it is corrupted

**Comment by danfrks** [comment]
> 

Thanks! I also had to delete and re-download configure_nodb.pl, otherwise it would overwrite the original configuration to an empty file every time I ran configure.

Solved.

**Comment by jtamames** [comment]
Nice to hear! Closing issue then.
Best,
J
