### ISSUE TITLE
Error occurs when reading inputs

### ISSUE THREAD

**Issue by SungUk** [jtamames/SqueezeMeta#473]
Hello, I got an error when I run SqueezeMeta.
Can you handle it?
Is it OK that </home/phyzen/WGSmeta/test2/TestProject/data/megahit/tmp/reads.lib> repeated two times in /data/log?
I might not encounter any errors when I tested only one sample for a test.
################syslog

SqueezeMeta v1.5.1, Jan 2022 - (c) J. Tamames, F. Puente-SÃ¡nchez CNB-CSIC, Madrid, SPAIN

Please cite: Tamames & Puente-Sanchez, Frontiers in Microbiology 10.3389 (2019). doi: https://doi.org/10.3389/fmicb.2018.03349

Run started Tue Apr 26 11:34:52 2022 in coassembly mode
Command: /home/phyzen/anaconda3/envs/SqueezeMeta/bin/SqueezeMeta.pl -m coassembly -p TestProject -s TestSample2.txt -f /home/phyzen/WGSmeta/test2/rawdata -t 20
Project: TestProject
Map file: TestSample2.txt
Fastq directory: /home/phyzen/WGSmeta/test2/rawdata
Options: threads=20; contiglen=200; assembler=megahit; mapper=bowtie; COGS; KEGG; PFAM;
[0 seconds]: STEP0 -> SqueezeMeta.pl
Coppying files: cp /home/phyzen/WGSmeta/test2/rawdata/1_SuWon_M_1.fastq.gz /home/phyzen/WGSmeta/test2/TestProject/data/raw_fastq/1_SuWon_M_1.fastq.gz
Coppying files: cp /home/phyzen/WGSmeta/test2/rawdata/1_SuWon_M_2.fastq.gz /home/phyzen/WGSmeta/test2/TestProject/data/raw_fastq/1_SuWon_M_2.fastq.gz
Coppying files: cp /home/phyzen/WGSmeta/test2/rawdata/2_HwaSeong_M_1.fastq.gz /home/phyzen/WGSmeta/test2/TestProject/data/raw_fastq/2_HwaSeong_M_1.fastq.gz
Coppying files: cp /home/phyzen/WGSmeta/test2/rawdata/2_HwaSeong_M_2.fastq.gz /home/phyzen/WGSmeta/test2/TestProject/data/raw_fastq/2_HwaSeong_M_2.fastq.gz
Coppying files: cp /home/phyzen/WGSmeta/test2/rawdata/3_GiHeung_M_1.fastq.gz /home/phyzen/WGSmeta/test2/TestProject/data/raw_fastq/3_GiHeung_M_1.fastq.gz
Coppying files: cp /home/phyzen/WGSmeta/test2/rawdata/3_GiHeung_M_1.fastq.gz /home/phyzen/WGSmeta/test2/TestProject/data/raw_fastq/3_GiHeung_M_1.fastq.gz
Coppying files: cp /home/phyzen/WGSmeta/test2/rawdata/4_GuGal_M_1.fastq.gz /home/phyzen/WGSmeta/test2/TestProject/data/raw_fastq/4_GuGal_M_1.fastq.gz
Coppying files: cp /home/phyzen/WGSmeta/test2/rawdata/4_GuGal_M_2.fastq.gz /home/phyzen/WGSmeta/test2/TestProject/data/raw_fastq/4_GuGal_M_2.fastq.gz
Coppying files: cp /home/phyzen/WGSmeta/test2/rawdata/5_AnPyeong_M_1.fastq.gz /home/phyzen/WGSmeta/test2/TestProject/data/raw_fastq/5_AnPyeong_M_1.fastq.gz
Coppying files: cp /home/phyzen/WGSmeta/test2/rawdata/5_AnPyeong_M_2.fastq.gz /home/phyzen/WGSmeta/test2/TestProject/data/raw_fastq/5_AnPyeong_M_2.fastq.gz
Coppying files: cp /home/phyzen/WGSmeta/test2/rawdata/6_OCheon_M_1.fastq.gz /home/phyzen/WGSmeta/test2/TestProject/data/raw_fastq/6_OCheon_M_1.fastq.gz
Coppying files: cp /home/phyzen/WGSmeta/test2/rawdata/6_OCheon_M_2.fastq.gz /home/phyzen/WGSmeta/test2/TestProject/data/raw_fastq/6_OCheon_M_2.fastq.gz
Samples:6
Mode:coassembly
Merging files for coassembly: cat /home/phyzen/WGSmeta/test2/TestProject/data/raw_fastq/1_SuWon_M_1.fastq.gz /home/phyzen/WGSmeta/test2/TestProject/data/raw_fastq/2_HwaSeong_M_1.fastq.gz /home/phyzen/WGSmeta/test2/TestProject/data/raw_fastq/4_GuGal_M_1.fastq.gz /home/phyzen/WGSmeta/test2/TestProject/data/raw_fastq/5_AnPyeong_M_1.fastq.gz /home/phyzen/WGSmeta/test2/TestProject/data/raw_fastq/6_OCheon_M_1.fastq.gz  > /home/phyzen/WGSmeta/test2/TestProject/data/raw_fastq/par1.fastq.gz; cat /home/phyzen/WGSmeta/test2/TestProject/data/raw_fastq/1_SuWon_M_2.fastq.gz /home/phyzen/WGSmeta/test2/TestProject/data/raw_fastq/2_HwaSeong_M_2.fastq.gz /home/phyzen/WGSmeta/test2/TestProject/data/raw_fastq/3_GiHeung_M_1.fastq.gz /home/phyzen/WGSmeta/test2/TestProject/data/raw_fastq/4_GuGal_M_2.fastq.gz /home/phyzen/WGSmeta/test2/TestProject/data/raw_fastq/5_AnPyeong_M_2.fastq.gz /home/phyzen/WGSmeta/test2/TestProject/data/raw_fastq/6_OCheon_M_2.fastq.gz  > /home/phyzen/WGSmeta/test2/TestProject/data/raw_fastq/par2.fastq.gz; 

[19 minutes, 32 seconds]: STEP1 -> 01.run_assembly.pl (megahit)
Stopping in STEP1 -> 01.run_assembly.pl. Program finished abnormally
_____________

System information:
_____________

Tree for the project:
ject/data/raw_fastq/par1.fastq.gz -2 /home/phyzen/WGSmeta/test2/TestProject/data/raw_fastq/par2.fastq.gz -t 20 -o /home/phyzen/WGSmeta/test2/TestProject/data/megahit >> /home/phyzen/WGSmeta/test2/TestProject/syslog 2>&1
2022-04-26 11:54:30 - MEGAHIT v1.2.9
2022-04-26 11:54:30 - Using megahit_core with POPCNT and BMI2 support
2022-04-26 11:54:30 - Convert reads to binary library
2022-04-26 12:11:38 - b'INFO  sequence/io/sequence_lib.cpp  :   77 - Lib 0 (/home/phyzen/WGSmeta/test2/TestProject/data/raw_fastq/par1.fastq.gz,/home/phyzen/WGSmeta/test2/TestProject/data/raw_fastq/par2.fastq.gz): pe, 567149242 reads, 151 max length'
2022-04-26 12:11:38 - b'INFO  utils/utils.h                 :  152 - Real: 1028.0340\tuser: 577.7984\tsys: 76.4404\tmaxrss: 245532'
2022-04-26 12:11:39 - Error occurs when reading inputs
Linux Sever107 5.13.0-40-generic #45~20.04.1-Ubuntu SMP Mon Apr 4 09:38:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
[4.0K Apr 26 11:34]  /home/phyzen/WGSmeta/test2/TestProject
├── [4.0K Apr 26 11:54]  data
│   ├── [ 506 Apr 26 11:34]  00.TestProject.samples
│   ├── [4.0K Apr 26 11:54]  megahit
│   │   ├── [   7 Apr 26 11:54]  checkpoints.txt
│   │   ├── [4.0K Apr 26 11:54]  intermediate_contigs
│   │   ├── [ 847 Apr 26 12:11]  log
│   │   ├── [ 977 Apr 26 11:54]  options.json
│   │   └── [4.0K Apr 26 12:11]  tmp
│   │       ├── [ 277 Apr 26 11:54]  reads.lib
│   │       ├── [ 23G Apr 26 12:11]  reads.lib.bin
│   │       └── [ 176 Apr 26 12:11]  reads.lib.lib_info
│   └── [4.0K Apr 26 11:49]  raw_fastq
│       ├── [5.2G Apr 26 11:35]  1_SuWon_M_1.fastq.gz
│       ├── [5.8G Apr 26 11:36]  1_SuWon_M_2.fastq.gz
│       ├── [4.8G Apr 26 11:37]  2_HwaSeong_M_1.fastq.gz
│       ├── [5.4G Apr 26 11:38]  2_HwaSeong_M_2.fastq.gz
│       ├── [4.5G Apr 26 11:39]  3_GiHeung_M_1.fastq.gz
│       ├── [4.7G Apr 26 11:40]  4_GuGal_M_1.fastq.gz
│       ├── [5.2G Apr 26 11:41]  4_GuGal_M_2.fastq.gz
│       ├── [4.6G Apr 26 11:42]  5_AnPyeong_M_1.fastq.gz
│       ├── [5.0G Apr 26 11:43]  5_AnPyeong_M_2.fastq.gz
│       ├── [4.1G Apr 26 11:43]  6_OCheon_M_1.fastq.gz
│       ├── [4.5G Apr 26 11:44]  6_OCheon_M_2.fastq.gz
│       ├── [ 23G Apr 26 11:49]  par1.fastq.gz
│       └── [ 30G Apr 26 11:54]  par2.fastq.gz
├── [4.0K Apr 26 11:34]  ext_tables
├── [4.0K Apr 26 11:34]  intermediate
│   └── [4.0K Apr 26 11:34]  binners
├── [ 193 Apr 26 11:54]  methods.txt
├── [2.9K Apr 26 11:34]  parameters.pl
├── [  59 Apr 26 11:54]  progress
├── [4.0K Apr 26 11:34]  results
├── [8.1K Apr 26 11:34]  SqueezeMeta_conf.pl
├── [4.6K Apr 26 12:11]  syslog
└── [4.0K Apr 26 11:34]  temp

10 directories, 25 files
#####################data/megahit/log
2022-04-26 11:54:30 - MEGAHIT v1.2.9
2022-04-26 11:54:30 - Using megahit_core with POPCNT and BMI2 support
2022-04-26 11:54:30 - Convert reads to binary library
2022-04-26 11:54:30 - command /home/phyzen/anaconda3/envs/SqueezeMeta/SqueezeMeta/bin/megahit/megahit_core buildlib /home/phyzen/WGSmeta/test2/TestProject/data/megahit/tmp/reads.lib /home/phyzen/WGSmeta/test2/TestProject/data/megahit/tmp/reads.lib
2022-04-26 12:11:38 - b'INFO  sequence/io/sequence_lib.cpp  :   77 - Lib 0 (/home/phyzen/WGSmeta/test2/TestProject/data/raw_fastq/par1.fastq.gz,/home/phyzen/WGSmeta/test2/TestProject/data/raw_fastq/par2.fastq.gz): pe, 567149242 reads, 151 max length'
2022-04-26 12:11:38 - b'INFO  utils/utils.h                 :  152 - Real: 1028.0340\tuser: 577.7984\tsys: 76.4404\tmaxrss: 245532'
2022-04-26 12:11:39 - Error occurs when reading inputs

**Comment by jtamames** [comment]
Hello
Please check your samples file. Perphaps, by mistake, you have put 
`3_GiHeung_M_1.fastq.gz  pair1`
instead of
`3_GiHeung_M_2.fastq.gz  pair2`
Could that be?
Best,
J

**Comment by jtamames** [comment]
No problem, I am very sympathetic with all that. Closing issue, feel free to reopen if you need more assistance
Best,
J
