### ISSUE TITLE
Installing SQMtools in Windows or Mac (including RStudio)

### ISSUE THREAD

**Issue by fpusan** [jtamames/SqueezeMeta#474]
1) Download and uncompress the source code for the latest version of SqueezeMeta from https://github.com/jtamames/SqueezeMeta/releases/latest

2) Inside R, install the dependencies `reshape2`, `ggplot2`, `pathview`, and `data.table`.
 
3) Inside R, install SQMtools with `install.packages("/path/to/uncompressed/SqueezeMeta/lib/SQMtools", repos = NULL, type = "source")`

**Comment by vmevada102** [comment]
I am getting error during installation in Rstudio installed in ubuntu 20.04

Installing package into ‘/home/user/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
ERROR: dependency ‘pathview’ is not available for package ‘SQMtools’

**Comment by fpusan** [comment]
Hi!
You will need to install the required dependencies.

**Comment by fpusan** [comment]
Just a reminder that this is no longer needed for newer SQMtools versions, just go to R and type
`if (!require("BiocManager", quietly = TRUE)) { install.packages("BiocManager")}; BiocManager::install("SQMtools")`
