### ISSUE TITLE
Raw Abundances PAIRED vs SINGLE reads

### ISSUE THREAD

**Issue by sarpiens** [jtamames/SqueezeMeta#476]
Hello, 

I have a question about how the pipeline treats the raw counts depending on whether the samples are SINGLE or PAIRED. From what I've seen if I have a paired sample the counts are counted as independent reads(2X). For example, sample with 1 Million paired reads, are counted as 2 Million raw abundances, when exploring SMQtools plot with plotTaxonomy(). This has surprised me a bit, because the typical classifiers would normally count them once.

So I wonder, to what extent would they be comparable when combining PAIRED and SINGLE datasets?

Thanks in advance!

**Comment by fpusan** [comment]
You are right, reads are counted independently regardless or whether they are paired or not. I don't see a problem with comparing results from single and paired datasets. Having paired reads will of course be better for assembly, so there's a source of bias there, but I don't think it will make a large difference when mapping reads back to the contigs.

**Comment by sarpiens** [comment]
All right, thanks for your quick response!
Best regards
