### ISSUE TITLE
Getting lot of reads with No CDS when running Squeezemeta

### ISSUE THREAD

**Issue by Rohit-Satyam** [jtamames/SqueezeMeta#481]
Hi Authors.

We were trying to use Squeezemeta with Selective Whole genome amplification (SWGA) data that we generated for plasmodium. Since we were getting a lot of unmapped reads when aligned with reference, we suspected some contamination in our samples and so thought of using your tool. We understand that since our samples were clinical there could be few reads coming from some bacteria even after we selectively amplified the Plasmodium genome but to our surprise, after running Squeezemeta we get a lot of reads unassigned (which technically should go to apicomplexa) and with no CDS. Can you help??

```bash

SqueezeMeta.pl -t 40 -m sequential -s SqueezeMeta/test_original_data/test.samples -f SqueezeMeta/test_original_data/raw --nopfam --euk --D
```
I ran the code without `--euk --D` flag (see left bar plot) and with `--euk --D` but couldn't see any improvement.

How to know what these reads going to NO CDS or Unassigned reads are?
![image](https://user-images.githubusercontent.com/55479480/167380958-193742f0-cca7-4bbb-92e9-822f6cc28f9c.png)

Also tried running `sqm_reads.pl` but don't know how to visualize it's results.

```bash
sqm_reads.pl -t 30 -p original_results -s SqueezeMeta/sqm_reads_test/test.samples -f SqueezeMeta/sqm_reads_test/raw --nocog --nokegg --euk
```

**Comment by fpusan** [comment]
The No_CDS tag just indicates reads mapping to non-protein-coding features. You can search for them after loading your results in SQMtools

```
SQM = loadSQM('/path/to/your/project', engine='data.table')
noCDSorfs = rownames(SQM$orfs$tax)[SQM$orfs$tax[,'superkingdom']=='No CDS']
noCDScontigs = rownames(SQM$contigs$tax)[SQM$contigs$tax[,'superkingdom']=='No CDS']
# check the first noCDS orf
SQM$orfs$table[noCDSorfs[1],] # annotation/abundance table
SQM$orfs$seqs[noCDSorfs[1]] # sequence
```

You can load `sqm_reads.pl` results in `SQMtools` by using `sqmreads2tables.py` and the `loadSQMlite` function. Both are documented in the PDF manuals.

**Comment by Rohit-Satyam** [comment]
Thanks, @fpusan. I will try that and get back. Thanks for your prompt reply.
