### ISSUE TITLE
Illegal division by zero at 10.mapsamples.pl line 434

### ISSUE THREAD

**Issue by LunavdL** [jtamames/SqueezeMeta#483]
Hello,

I'm sorry to bother you with a question again so soon. I'm running a subset of my data in coassembly mode and the pipeline stopped at step 10 with a warning about an illegal division by zero.

Attached the syslog file: [syslog.gz](https://github.com/jtamames/SqueezeMeta/files/8685813/syslog.gz)

I checked previous issues at GitHub, but couldn't find the solution there. 
I uncommented line 245 in script 10, and ran it again. This was the output: 
```
[0 seconds]: STEP10 -> MAPPING READS: 10.mapsamples.pl
  Reading samples from /home/lvdrloos/Documents/metagenomics_Baltic/Baltic_Blidingia/data/00.Baltic_Blidingia.samples
  Metagenomes found: 10
  Mapping with Bowtie2 (Langmead and Salzberg 2012, Nat Methods 9(4), 357-9)
  Found reference in /home/lvdrloos/Documents/metagenomics_Baltic/Baltic_Blidingia/data/Baltic_Blidingia.bowtie.1.bt2, skipping
  Working with sample 1: DK_040
  Getting raw reads
  Aligning to reference with bowtie
  SAM file already found in /home/lvdrloos/Documents/metagenomics_Baltic/Baltic_Blidingia/data/sam/Baltic_Blidingia.DK_040.sam, skipping
  Calculating contig coverage
  Reading contig length from /home/lvdrloos/Documents/metagenomics_Baltic/Baltic_Blidingia/intermediate/01.Baltic_Blidingia.lon
Illegal division by zero at /home/lvdrloos/bin/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/10.mapsamples.pl line 434.
Stopping in STEP10 -> 10.mapsamples.pl. Program finished abnormally
```

I also attach the .lon file here, but I can't find anything very strange: [01.Baltic_Blidingia.lon.gz](https://github.com/jtamames/SqueezeMeta/files/8685873/01.Baltic_Blidingia.lon.gz)

The .sam file seems to be copied properly to the folder /data/sam, but perhaps there is something wrong with the file? These are the last lines of the .sam file:
```
@SQ	SN:megahit_986521	LN:285
@SQ	SN:megahit_986522	LN:270
@SQ	SN:megahit_986523	LN:285
@SQ	SN:megahit_986524	LN:304
@SQ	SN:megahit_986525	LN:312
@PG	ID:bowtie2	PN:bowtie2	VN:2.3.4.1	CL:"/home/lvdrloos/bin/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/bowtie2/bowtie2-align-s --wrapper basic-0 -x /home/lvdrloos/Documents/metagenomics_Baltic/Baltic_Blidingia/data/Baltic_Blidingia.bowtie --very-sensitive-local --quiet -p 12 -S /home/lvdrloos/Documents/metagenomics_Baltic/Baltic_Blidingia/data/sam/Baltic_Blidingia.DK_040.sam -1 /home/lvdrloos/Documents/metagenomics_Baltic/Baltic_Blidingia/temp/Baltic_Blidingia.DK_040.current_1.gz -2 /home/lvdrloos/Documents/metagenomics_Baltic/Baltic_Blidingia/temp/Baltic_Blidingia.DK_040.current_2.gz"
```

Cheers,
Luna

**Comment by jtamames** [comment]
Hello Luna
The problem is in your fastq files. If you check the ones copied in the data/raw_fastq directory, you will see that most of them are (almost) empty (just 20 bytes from a header or something). The coassembly ran ok because a few files have valid sequences, but the problem comes when mapping these empty files. The SAM files indeed contain just the contig info and nothing else. Could you please check your input data files?
Best,
J

**Comment by LunavdL** [comment]
Hmm, OK. The raw fastq files were copied in full to data/raw_fastq at the start of the pipeline, but they were changed/removed during the filtering with trimmomatic (default settings). If I run the pipeline without "--cleaning", this doesn't happen. I hope this doesn't mean the quality of the reads is very low, but for now I will run it without"--cleaning". 

Thank you again for your very fast reply!
