### ISSUE TITLE
nr.nb missing

### ISSUE THREAD

**Issue by kalonji08** [jtamames/SqueezeMeta#484]
Hi!
If the `nr.db` file is not there then something went wrong during the database downloading step.

Can you list the contents of the `/BioII/wangjb/Backup/SequencingRuns/SqueezeMeta_db/db` directory with `ls` and paste them here?

As an alternative, you can try running `make_databases.pl` instead of `download_databases.pl`. This downloads the data directly from NCBI instead of from our server, this will take longer but might fix the issue if the problem was on our side.

_Originally posted by @fpusan in https://github.com/jtamames/SqueezeMeta/issues/146#issuecomment-683629553_

**Comment by kalonji08** [comment]
Hi I have the same issue as above. this what i have in my db folder when i do ls:

arc.all.faa  arc.scg.lookup    bac.hmm         DB_BUILD_DATE  euk.hmm      hmms_ssu    LCA_tax     nr.gz   Pfam-A.hmm                silva.nr_v132.align    test_data
arc.hmm      bac.all.faa       bac.scg.faa     distributions  genome_tree  img         marker.hmm  nr.md5  ReadMe                    silva.nr_v132.tax
arc.scg.faa  bacar_marker.hmm  bac.scg.lookup  eggnog.dmnd    hmms         kegg.db.gz  mito.hmm    pfam    selected_marker_sets.tsv  taxon_marker_sets.tsv

**Comment by kalonji08** [comment]
I downloaded data using make_databases_alt.pl

**Comment by fpusan** [comment]
Something went wrong during database creation. I see that you have the `nr.gz` file. This should have gotten decompressed to `nr.faa`, which would then have been the input to create `nr.dmnd`.
Maybe you ran out of disk space? Do you have the output of the `make_databases_alt.pl`.
Otherwise can you try running `download_databases.pl` instead?

**Comment by kalonji08** [comment]
Hi @fpusan i didn't copy the output but it said that the set up was complete. I have about 908GB space left on the computer.
I'm re-downloading with : make_databases.pl. The first one took about 3 days to download I'll notify you of the outcomes. Thanks a lot

**Comment by kalonji08** [comment]
Hi @fpusan i got the same error with make_databases.pl.

**here is the output:**
 zip: stdin: invalid compressed data--format violated
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
Died at /home/kalonjilab/miniconda3/envs/SqueezeMeta/SqueezeMeta/lib/install_utils/rectaxa.pl line 31.

  Running nrindex.pl
Cannot open /mnt/hdd2/SqueezeMeta/kaloDB/db/nr.faa

  Running taxid_tree.pl
File created: /mnt/hdd2/SqueezeMeta/kaloDB/db/LCA_tax/taxid_tree.txt

  Creating sqlite databases

Error: cannot open "/mnt/hdd2/SqueezeMeta/kaloDB/db/LCA_tax/parents.txt"
rm: cannot remove '/mnt/hdd2/SqueezeMeta/kaloDB/db/nr.faa': No such file or directory
Make sure that /mnt/hdd2/SqueezeMeta/kaloDB/db contains all the database files (nr.dmnd, etc...)

Downloading and unpacking RDP classifier...
--2022-05-15 01:03:17--  http://andes.cnb.csic.es/SqueezeMeta//classifier.tar.gz
Resolving andes.cnb.csic.es (andes.cnb.csic.es)... 150.244.85.58
Connecting to andes.cnb.csic.es (andes.cnb.csic.es)|150.244.85.58|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 154722472 (148M) [application/x-gzip]
Saving to: ‘/home/kalonjilab/miniconda3/envs/SqueezeMeta/SqueezeMeta/lib/classifier.tar.gz’

classifier.tar.gz                                  100%[===============================================================================================================>] 147.55M  1.19MB/s    in 2m 27s

2022-05-15 01:05:45 (1.00 MB/s) - ‘/home/kalonjilab/miniconda3/envs/SqueezeMeta/SqueezeMeta/lib/classifier.tar.gz’ saved [154722472/154722472]

--2022-05-15 01:05:45--  http://andes.cnb.csic.es/SqueezeMeta//classifier.md5
Resolving andes.cnb.csic.es (andes.cnb.csic.es)... 150.244.85.58
Connecting to andes.cnb.csic.es (andes.cnb.csic.es)|150.244.85.58|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 33
Saving to: ‘/home/kalonjilab/miniconda3/envs/SqueezeMeta/SqueezeMeta/lib/classifier.md5’

classifier.md5                                     100%[===============================================================================================================>]      33  --.-KB/s    in 0s

2022-05-15 01:05:45 (1.56 MB/s) - ‘/home/kalonjilab/miniconda3/envs/SqueezeMeta/SqueezeMeta/lib/classifier.md5’ saved [33/33]

classifier/
classifier/classifier.jar
classifier/lib/
classifier/lib/TaxonomyTree.jar
classifier/lib/commons-cli-1.2.jar
classifier/lib/ReadSeq.jar
classifier/lib/jfreechart-1.0.13.jar
classifier/lib/AlignmentTools.jar
classifier/lib/jcommon-1.0.16.jar
classifier/lib/commons-io-2.4.jar

Updating configuration...
Done

**Comment by fpusan** [comment]
What about `download_databases.pl`?

**Comment by kalonji08** [comment]
@fpusan It didn't work either, it only downloaded the tets file and dopped.
Is it possible to download the nr database outside squeeze and manually copy it in the folder?

**Comment by fpusan** [comment]
Try to download it from here
http://andes.cnb.csic.es/SqueezeMeta/SqueezeMetaDB.md5
http://andes.cnb.csic.es/SqueezeMeta/SqueezeMetaDB.tar.gz

The md5sum of the `SqueezeMetaDB.tar.gz` file should be the one stated in the `http://andes.cnb.csic.es/SqueezeMeta/SqueezeMetaDB.md5` file

**Comment by kalonji08** [comment]
Thank you very much, I have started the download process

**Comment by fpusan** [comment]
Let me know if you manage to finish successfully and then we can move on to the next steps

**Comment by fpusan** [comment]
Is the md5sum the same as stated in the `http://andes.cnb.csic.es/SqueezeMeta/SqueezeMetaDB.md5` file?

**Comment by fpusan** [comment]
Nice. Then uncompress the tar.gz file
You should end up with a directory `db` that contains the file `nr.dmnd` (so the file `/path/to/db/nr.dmnd` exists).
Now activate your SqueezeMeta environment and run `configure_nodb.pl /path/to/db`. This should link your SqueezeMeta installation to the databases directory.
Finally run `test_install.pl` to check that the process was correct. Let me know if this works.

**Comment by kalonji08** [comment]
Thanks I'm on it

**Comment by kalonji08** [comment]
Hi @fpusan Thank you so much it worked


Checking that ruby is installed
        ruby -h OK

Checking that java is installed
        java -h OK

Checking that all the required perl libraries are available in this environment
        perl -e 'use Term::ANSIColor' OK
        perl -e 'use DBI' OK
        perl -e 'use DBD::SQLite::Constants' OK
        perl -e 'use Time::Seconds' OK
        perl -e 'use Tie::IxHash' OK
        perl -e 'use Linux::MemInfo' OK
        perl -e 'use Getopt::Long' OK
        perl -e 'use File::Basename' OK
        perl -e 'use DBD::SQLite' OK
        perl -e 'use Data::Dumper' OK
        perl -e 'use Cwd' OK
        perl -e 'use XML::LibXML' OK
        perl -e 'use XML::Parser' OK
        perl -e 'use Term::ANSIColor' OK

Checking that all the required python libraries are available in this environment
        python3 -h OK
        python3 -c 'import numpy' OK
        python3 -c 'import scipy' OK
        python3 -c 'import matplotlib' OK
        python3 -c 'import dendropy' OK
        python3 -c 'import pysam' OK
        python3 -c 'import Bio.Seq' OK
        python3 -c 'import pandas' OK
        python3 -c 'import sklearn' OK
        python3 -c 'import nose' OK
        python3 -c 'import cython' OK
        python3 -c 'import future' OK

Checking that all the required R libraries are available in this environment
        R -h OK
        R -e 'library(doMC)' OK
        R -e 'library(ggplot2)' OK
        R -e 'library(data.table)' OK
        R -e 'library(reshape2)' OK
        R -e 'library(pathview)' OK
        R -e 'library(DASTool)' OK
        R -e 'library(SQMtools)' OK

Checking that SqueezeMeta is properly configured... checking database in /mnt/hdd2/SqueezeMeta/db
        nr.db OK
        CheckM manifest OK
        LCA_tax DB OK

All checks successful

**Comment by kalonji08** [comment]
I have a few questions:
- can i skip assembly if i already have assembled meta-genome reads?
- Is it possible for me to pass my MAGs (generated using Concot, MaxBIn and MetaBat from metaWRAP) on Squeeze for annotation using Pfam, Kegg etc.. ?

**Comment by fpusan** [comment]
> can i skip assembly if i already have assembled meta-genome reads?

Yes, use the `-extassembly` option.

> Is it possible for me to pass my MAGs (generated using Concot, MaxBIn and MetaBat from metaWRAP) on Squeeze for annotation using Pfam, Kegg etc.. ?

Also yes, but then you should use the `--nobins` option so that it doesn't try to bin again.

**Comment by kalonji08** [comment]
Thanks a lot I'm really grateful for your help. I'll let you how it goes.

**Comment by fpusan** [comment]
Sure!

**Comment by jtamames** [comment]
For annotating the MAGs, you can use the sqm_annot.pl script in the utils directory. It is intended to do exactly so.

**Comment by SanshiroTakahashi** [comment]
Sorry for the interruption from Japan.

I have found that test_install.pl
is now working with the
nr.db
is not able to find the

I tried the same thing with SqueezeMeta-1.4.0
does the same thing, but the error does not occur in
SqueezeMeta-1.5.2
but the error occurs in SqueezeMeta-1.5.2.

This error is caused by a bug in
SqueezeMeta-1.5.2
(I haven't had time to track down the details).

One way to fix it is to contact
https://github.com/jtamames/SqueezeMeta
One way to fix it is to look at the end of
License and third-party software
in the "License and third-party software" section.
trimmomatic
Megahit
Spades
canu
prinseq
kmer-db
cd-hit
amos
mummer
hmmer
barrnap
aragorn
prodigal
DIAMOND
bwa
minimap2
bowtie2
MaxBin
MetaBAT
CONCOCT
DAS tool
checkm
comparem
MinPath
RDP classifier
pullseq
Short-Pair
SAMtools
Mothur
Flye
If you install these first
test_install.pl

can find nr.db and it works fine.
Many similar problems have been posted, but all can be solved in the same way.

Sorry for the sidebar from Japan.


Translated with www.DeepL.com/Translator (free version)

**Comment by SanshiroTakahashi** [comment]
Mamba create -n SqueezeMeta -c conda-forge -c bioconda -c fpusan squeezemeta
conda activate SqueezeMeta
download_databases.pl /path/to/store/databases
test_install

The manual does not describe the differences or the reasons for them.
Doing this seems to solve the problem.
They say that any exchange that cannot be resolved above is pointless.
