### ISSUE TITLE
re-arrange sample order in the data

### ISSUE THREAD

**Issue by ewelinarubin** [jtamames/SqueezeMeta#485]
I just started using SQMtools -- it is a super nice tool. I imported my data and I am making first taxonomy plots. 
How do I reorder my samples ?

**Comment by fpusan** [comment]
Pass a vector with the desired sample order to the "samples" parameter in plotTaxonomy or plotFunctions

**Comment by H1889** [comment]
Sorry, but I have tried several options in the "samples" field and none worked:
samples names are 71,71,73 etc
samples = "71" worked
samples = "71,72,73" not worked
samples = "71","72","73" not worked...
how can I pass the character vector with the names of the samples I want to plot?
Thanks

**Comment by H1889** [comment]
It worked.
Thanks
