### ISSUE TITLE
Best way to treat MTG and MTT data independently?

### ISSUE THREAD

**Issue by sarpiens** [jtamames/SqueezeMeta#487]
I am wondering what would be the best way to analyze a sample set with Metagenomics(MTG) and Metatranscriptomics(MTT) data, if you intend to analyze their functions independently. The following options come to mind:

a) Using squeezemeta in co-assembly mode independently.
b) Using squeezemeta in merged mode together as in the wiki tutorial, and subset the data in MTG and MTT.

My hunch will be that the second option would be better for taxonomic profiles, due to the contigs obtained from MTG data, but I am not sure if the function profiling would improve, or it would be indistinct to use a) or b). What do you think?

Thanks in advance. Best regards!

**Comment by jtamames** [comment]
Hello
MTT data breaks the assumption of random sequencing assumed by the assembly of MTG, therefore I would not mix both datasets. Therefore I would go for the second option.
Best,
J
