### ISSUE TITLE
SqueezeMeta samples file query

### ISSUE THREAD

**Issue by kalonji08** [jtamames/SqueezeMeta#488]
Hi @fpusan I'm back again

I have one more query 
I would like to annotate my MAGs

So i ran the following code on my MAGs folder:
SqueezeMeta.pl -m sequential -s hc3sq.samples -extassembly --nobins -t 25 -f reassembled_bins/

but I'm getting this error :
Samples file, line bin.10.strict.fa     pair1   nobinning,extassembly=/mnt/hdd2/metagenomesPHD/HC3/squeezeHC3/HC3_final_assembly.fasta: file label must be "pair1" or "pair2". For single reads, use "pair1"

My samples file looks like this:
bin.10.strict.fa	pair1	nobinning,extassembly=/mnt/hdd2/metagenomesPHD/HC3/squeezeHC3/HC3_final_assembly.fasta
bin.11.orig.fa	pair1	nobinning,extassembly=/mnt/hdd2/metagenomesPHD/HC3/squeezeHC3/HC3_final_assembly.fasta
bin.12.orig.fa	pair1	nobinning,extassembly=/mnt/hdd2/metagenomesPHD/HC3/squeezeHC3/HC3_final_assembly.fasta
bin.13.strict.fa	pair1	nobinning,extassembly=/mnt/hdd2/metagenomesPHD/HC3/squeezeHC3/HC3_final_assembly.fasta
bin.14.orig.fa	pair1	nobinning,extassembly=/mnt/hdd2/metagenomesPHD/HC3/squeezeHC3/HC3_final_assembly.fasta
bin.15.orig.fa	pair1	nobinning,extassembly=/mnt/hdd2/metagenomesPHD/HC3/squeezeHC3/HC3_final_assembly.fasta
bin.1.permissive.fa	pair1	nobinning,extassembly=/mnt/hdd2/metagenomesPHD/HC3/squeezeHC3/HC3_final_assembly.fasta
bin.2.orig.fa	pair1	nobinning,extassembly=/mnt/hdd2/metagenomesPHD/HC3/squeezeHC3/HC3_final_assembly.fasta
bin.3.strict.fa	pair1	nobinning,extassembly=/mnt/hdd2/metagenomesPHD/HC3/squeezeHC3/HC3_final_assembly.fasta
bin.4.orig.fa	pair1	nobinning,extassembly=/mnt/hdd2/metagenomesPHD/HC3/squeezeHC3/HC3_final_assembly.fasta
bin.5.orig.fa	pair1	nobinning,extassembly=/mnt/hdd2/metagenomesPHD/HC3/squeezeHC3/HC3_final_assembly.fasta
bin.6.orig.fa	pair1	nobinning,extassembly=/mnt/hdd2/metagenomesPHD/HC3/squeezeHC3/HC3_final_assembly.fasta
bin.7.strict.fa	pair1	nobinning,extassembly=/mnt/hdd2/metagenomesPHD/HC3/squeezeHC3/HC3_final_assembly.fasta
bin.8.strict.fa	pair1	nobinning,extassembly=/mnt/hdd2/metagenomesPHD/HC3/squeezeHC3/HC3_final_assembly.fasta
bin.9.orig.fa	pair1	nobinning,extassembly=/mnt/hdd2/metagenomesPHD/HC3/squeezeHC3/HC3_final_assembly.fasta

**Comment by fpusan** [comment]
You are missing the first column with the sample name, right?
Also, if you want to just annotate the bins without mapping any reads back to them, I think there is an utility script for that names `sqm_annot.pl`. But maybe @jtamames can help with this better than me

**Comment by kalonji08** [comment]
Thanks i have added a column name, no problem I will wait for @jtamames

**Comment by jtamames** [comment]
Sure, better use `sqm_annot.pl` for annotating genomes, bins, etc. It is in the `utils` directory.
Best,
J

**Comment by jtamames** [comment]
Hello
You are probably using an old version of the script. Can you download the latest one from the repo and try again?
Best,
J

**Comment by kalonji08** [comment]
Thanks i'm still a novice, i have a few questions:
- Will i get the script under util? (https://github.com/jtamames/SqueezeMeta/tree/master/utils)

-I have installed squeeze using conda, would you please direct me on how to update sqm_annot.pl?

**Comment by jtamames** [comment]
Yes, you can get it from there. 
For finding out where conda stored the files, you can type `conda info --envs`. Look for the SqueezeMeta environment and the script must be there, in the `SqueezeMeta/utils` directory. Just replace the old sqm_annot with the new one
Best,
J

**Comment by kalonji08** [comment]
Hi @jtamames I replaced but i'm still getting the same error. Is perhaps the way i'm writting my files.samples?

Would you please inspect my the format of my file.sample here below and let me know if i need to specify nobinning and noassembly for MAGs annotation?

bin.10.strict	bin.10.strict.fa	pair1	nobinning	noassembly
bin.11.orig	bin.11.orig.fa	pair1	nobinning	noassembly
bin.12.orig	bin.12.orig.fa	pair1	nobinning	noassembly
bin.13.strict	bin.13.strict.fa	pair1	nobinning	noassembly
bin.14.orig	bin.14.orig.fa	pair1	nobinning	noassembly
bin.15.orig	bin.15.orig.fa	pair1	nobinning	noassembly
bin.1.permissive	bin.1.permissive.fa	pair1	nobinning	noassembly
bin.2.orig	bin.2.orig.fa	pair1	nobinning	noassembly
bin.3.strict	bin.3.strict.fa	pair1	nobinning	noassembly
bin.4.orig	bin.4.orig.fa	pair1	nobinning	noassembly
bin.5.orig	bin.5.orig.fa	pair1	nobinning	noassembly
bin.6.orig	bin.6.orig.fa	pair1	nobinning	noassembly
bin.7.strict	bin.7.strict.fa	pair1	nobinning	noassembly
bin.8.strict	bin.8.strict.fa	pair1	nobinning	noassembly
bin.9.orig	bin.9.orig.fa	pair1	nobinning	noassembly

**Comment by kalonji08** [comment]
Hi @jtamames Thanks a lot it worked!
