### ISSUE TITLE
STEP4 -> HOMOLOGY SEARCHES: 04.rundiamond.pl is stopping abnormally

### ISSUE THREAD

**Issue by PuspenduSardar** [jtamames/SqueezeMeta#489]
Hello,

I am coassembling 140 samples in a server with 490GB of available memory and 88 dedicated threads using SqueezeMeta v1.5.1. SqueezeMeta stops abruptly at step 4 while running diamond. I was wondering if this is a memory issue. I have seen that v1.5.2 has some bug fixes and during the diamond search, it doesn't crash due to memory.

I used conda for SqueezeMeta installation. Is there a way to update the conda environment or do I need to install a fresh copy? And, if I update the environment (with v1.5.2) do I need to update the databases as well (due to diamond compatibility)?

Many thanks for your help.
Puspendu

**Comment by fpusan** [comment]
Just create a new environment with the latest version and link it to the databases using `configure_nodb.pl`. You don't need to update the databases.
Let me know if the new version does the trick!

**Comment by PuspenduSardar** [comment]
Many thanks, @fpusan. I'll try that and let you know.
Can I use `restart.pl` to restart the pipeline (partially finished up to step 3 using v1.5.1)?

Regards,
Puspendu

**Comment by fpusan** [comment]
Yes, `restart.pl` should work with the new version even if the project was started with v1.5.1

**Comment by PuspenduSardar** [comment]
> Yes, `restart.pl` should work with the new version even if the project was started with v1.5.1

Many thanks.
It seems like v1.5.2 is not available in conda. Would it be possible to add that in conda?

**Comment by fpusan** [comment]
This is a bug, I think. v1.5.2 is available in conda but when you run SqueezeMeta it will keep saying its 1.5.1. When creating the conda environment, see if the package version for SqueezeMeta (as stated by conda) is v1.5.2. In that case you will be right.

**Comment by PuspenduSardar** [comment]
I tried `SqueezeMeta.pl -v` in the newly installed environment and it printed SqueezeMeta 1.5.1.

**Comment by fpusan** [comment]
Yes. that is what I said above. There is a mistake in the printed version name.
When you are running `conda create` and get the list of packages to be installed by conda, what version is SqueezeMeta showing there?

**Comment by PuspenduSardar** [comment]
Many thanks!
I am sorry, I didn't pay attention to that during installation. But, you might be right. I just checked the shipped diamond version, and it is 2.0.14. diamond version of 1.5.1 was 2.0.8. I'll start my analysis with this new version and let you know.

Regards,
Puspendu
