### ISSUE TITLE
sqm_reads.pl subset to kingdom level

### ISSUE THREAD

**Issue by tsa4a12** [jtamames/SqueezeMeta#491]
Thank you so much for developing such a great tool and I'm having a great time using it!
My data did have varying coverage and high percentage unclassified so I wanted to improve it using sqm_reads.py.

It ran smoothly and generated tables with sqmreads2tables.py with seemingly better identification of bacterial taxa but unluckily these counts cannot be subsetted to only include bacteria counts like we can using standard pipeline and loadSQM() 

However, threoretically the *.out.allreads and *.out.allreads.mcount files should have the information required to subset/ correlate taxa with functions and read abundances, so i guess it is possible to get specific subsets of data (either by taxa or by function), or make sqm objects with read data?

I am currently using the SQMtools attached with the 1.4.0 version of SqueezeMeta so idk if it is updated with such utility... or if it is needed to reinvent the subsetTax function with the reads output?

Best,
Tom

**Comment by fpusan** [comment]
It is indeed possible, and it was indeed updated! From v1.5.0 onwards, the `sqmreads2tables.py` script can subset the data based on different requirements prior to generating the tables.

**Comment by tsa4a12** [comment]
Great! Can i just use the new version of the python script or do i need to rerun the sqm_reads using v1.5.0 due to compatibility?

**Comment by fpusan** [comment]
Quite sure you don't need to rerun sqm_reads.pl, just the new sqmreads2tables.py script

**Comment by tsa4a12** [comment]
Thank you so much for your prompt answer! saved my day *again* 👯
