### ISSUE TITLE
lca_reads.pl doesn't respect set path and filenames

### ISSUE THREAD

**Issue by gromain** [jtamames/SqueezeMeta#496]
`lca_reads.pl` doesn't respect set file path and doesn't behave properly when launched in a [Singularity container](https://github.com/gromain/SqueezeMeta-singularity/). Issue starts with this https://github.com/jtamames/SqueezeMeta/blob/20955bbc8430a20c4d2f1e371b2d90a5184f0b71/lib/SQM_reads/lca_reads.pl#L22

The problem is that `lca_reads` tries to creates files in the `$resultpath=.` folder which is not writable in a singularity container.

- `sqm_reads.pl` is calling `lca_reads.pl` with an already defined path for the wranks file
https://github.com/jtamames/SqueezeMeta/blob/20955bbc8430a20c4d2f1e371b2d90a5184f0b71/utils/sqm_reads.pl#L256
  With outfile being defined: https://github.com/jtamames/SqueezeMeta/blob/20955bbc8430a20c4d2f1e371b2d90a5184f0b71/utils/sqm_reads.pl#L228

- `lca_reads.pl` then creates the complete file path for the `.wranks` file: https://github.com/jtamames/SqueezeMeta/blob/20955bbc8430a20c4d2f1e371b2d90a5184f0b71/lib/SQM_reads/lca_reads.pl#L40

- Thus there is no need for a `$resultpath` variable to be prepended to the filepath: https://github.com/jtamames/SqueezeMeta/blob/20955bbc8430a20c4d2f1e371b2d90a5184f0b71/lib/SQM_reads/lca_reads.pl#L81
  Same is true for `_nofilter.wranks`: https://github.com/jtamames/SqueezeMeta/blob/20955bbc8430a20c4d2f1e371b2d90a5184f0b71/lib/SQM_reads/lca_reads.pl#L88

As a general rule, it's also best not to reuse variables names for different purposes (seen just before in lines 81 and 88 where `$wrankfile` is reused for different file path.
Moreover, the usage string for `lca_reads.pl` is not correct at https://github.com/jtamames/SqueezeMeta/blob/20955bbc8430a20c4d2f1e371b2d90a5184f0b71/lib/SQM_reads/lca_reads.pl#L49

**Workaround for existing Singularity users is to set a `--home /` option when launching the container with `singularity exec`, however, it would be better if this issue is solved directly in `lca_reads.pl`.**

**Comment by gromain** [comment]
Also, we are having more issues because of https://github.com/jtamames/SqueezeMeta/blob/20955bbc8430a20c4d2f1e371b2d90a5184f0b71/lib/SQM_reads/lca_reads.pl#L21

Please use `/tmp` for temporary files. This breaks a lot of things.

@jtamames do you think you can fix this?

**Comment by fpusan** [comment]
Would having absolute paths instead of `.` work inside the singularity container?

**Comment by fpusan** [comment]
Closed due to lack of activity, feel free to reopen
