### ISSUE TITLE
exportKrona

### ISSUE THREAD

**Issue by aalkin2001** [jtamames/SqueezeMeta#501]
Hi there,
I am trying to generate a Krona plot from my SqueezeMeta result and as described in the SQMtools manual, I ran the exportKrona() script but I got the following error: 
 ktImportText (from KronaTools) is not present in your PATH. KronaTools can be downloaded from https://github.com/marbl/Krona
In addition: Warning message:
In system("ktImportText", ignore.stdout = T, ignore.stderr = T) :
  error in running command
Would you please guide me to resolve this issue?

**Comment by fpusan** [comment]
Sure! Download KronaTools and install it as described in https://github.com/marbl/Krona/wiki/Installing
Once it is properly installed and the executables are available in your $PATH environmental variable, the `exportKrona` function should work.
