### ISSUE TITLE
Step 14 - SqueezeMeta_conf.pl not found

### ISSUE THREAD

**Issue by danfrks** [jtamames/SqueezeMeta#502]
Hello,

I have an issue where SM does not run the binning algorithms because it does not find the config file. I am sure it is something simple I am missing, thank you in advance for taking a look.
```

(SqueezeMeta) danielfarkas@urlws00002:~/Metagenomics/Atrazine/raw_data/Atrazine$ sudo perl /home/danielfarkas/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/restart.pl /home/danielfarkas/Metagenomics/Atrazine/raw_data/Atrazine/ -step 14
[0 seconds]: STEP14 -> BINNING: 14.runbinning.pl
  Running maxbin from /home/danielfarkas/miniconda3/envs/SqueezeMeta/SqueezeMeta/lib/SqueezeMeta/bin_maxbin.pl
Can't find SqueezeMeta_conf.pl in Atrazine. Is the project path ok? at /home/danielfarkas/miniconda3/envs/SqueezeMeta/SqueezeMeta/lib/SqueezeMeta/bin_maxbin.pl line 15.
ERROR in STEP14 -> /home/danielfarkas/miniconda3/envs/SqueezeMeta/SqueezeMeta/lib/SqueezeMeta/bin_maxbin.pl
wc: /home/danielfarkas/Metagenomics/Atrazine/raw_data/Atrazine/intermediate/binners/maxbin/: Is a directory
WARNING in STEP14 -> /home/danielfarkas/miniconda3/envs/SqueezeMeta/SqueezeMeta/lib/SqueezeMeta/bin_maxbin.pl. No maxbin results!
```

The conf.pl file is indeed in the project folder.
```

`$version = "1.4.0, May 2021";
$mode = "seqmerge";
$date = "Mon May  9 11:47:12 2022";

$installpath = "/home/danielfarkas/miniconda3/envs/SqueezeMeta/SqueezeMeta";
#-- Project dir (calculated dinamically on execution, DO NOT MODIFY)

use File::Basename;
use Cwd 'abs_path';
$projectdir   = abs_path(dirname(__FILE__));
```

Best,

Daniel

**Comment by fpusan** [comment]
Why are you running this with sudo? Not 100% what is happening but I can imagine how this could lead to problems.

**Comment by danfrks** [comment]
The error was displayed without the sudo command as well. I was thinking it is a perl issue with calling the ARVG variable and I tried with sudo. I have no experience with perl and limited experience with bash/Linux in general, and I was trying to figure out what's going on before opening a thread. The result is the same with and without sudo anyway. The program was running from step 7 to 13 with no problems before the error in step 14,which makes it more baffling.

**Comment by fpusan** [comment]
Assuming the `SqueezeMeta_conf.pl` file is in `/home/danielfarkas/Metagenomics/Atrazine/raw_data/Atrazine`

Try
```
cd ~/Metagenomics/Atrazine/raw_data/Atrazine$ sudo perl /home/danielfarkas/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/restart.pl /home/danielfarkas/Metagenomics/Atrazine/raw_data/

perl /home/danielfarkas/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/restart.pl Atrazine -step 14
```

**Comment by danfrks** [comment]
I have tried to run from within the directory of the project, and from the home directory. Same error both times.

However, it asks me if I want to remove the log file; either way (y or n), the error persists.
```

SqueezeMeta) danielfarkas@urlws00002:~/Metagenomics/Atrazine/raw_data/Atrazine$ perl /home/danielfarkas/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/restart.pl /home/danielfarkas/Metagenomics/Atrazine/raw_data/Atrazine -step 14
rm: remove write-protected regular file '/home/danielfarkas/Metagenomics/Atrazine/raw_data/Atrazine/temp/Atrazine.log'? y
[1 seconds]: STEP14 -> BINNING: 14.runbinning.pl
  Running maxbin from /home/danielfarkas/miniconda3/envs/SqueezeMeta/SqueezeMeta/lib/SqueezeMeta/bin_maxbin.pl
Can't find SqueezeMeta_conf.pl in Atrazine. Is the project path ok? at /home/danielfarkas/miniconda3/envs/SqueezeMeta/SqueezeMeta/lib/SqueezeMeta/bin_maxbin.pl line 15.
ERROR in STEP14 -> /home/danielfarkas/miniconda3/envs/SqueezeMeta/SqueezeMeta/lib/SqueezeMeta/bin_maxbin.pl
wc: /home/danielfarkas/Metagenomics/Atrazine/raw_data/Atrazine/intermediate/binners/maxbin/: Is a directory
WARNING in STEP14 -> /home/danielfarkas/miniconda3/envs/SqueezeMeta/SqueezeMeta/lib/SqueezeMeta/bin_maxbin.pl. No maxbin results!
```

![image](https://user-images.githubusercontent.com/62805426/172372407-8c74e81e-fe65-4786-a784-e77745b133c5.png)
[config_and_syslog.zip](https://github.com/jtamames/SqueezeMeta/files/8852883/config_and_syslog.zip)

**Comment by fpusan** [comment]
By looking at the syslog file it seems that the program died several times, but it shouldn't be a problem per se...

Can you try running the latest version of SqueezeMeta (without sudo) on the test data we provide when downloading the databases? Let's see if the issue persists.

**Comment by danfrks** [comment]
Solved. The correctt directory was ~/Metagenomics/Atrazine/raw_data

**Comment by danfrks** [comment]
Solved. The correct directory was ~/Metagenomics/Atrazine/raw_data. 

Thank you and sorry for bothering you with this.
