### ISSUE TITLE
 gzip invalid compressed data--format violated (fastp.fastq.gz)

### ISSUE THREAD

**Issue by astromecki** [jtamames/SqueezeMeta#503]
Hello! I am having issues with gzip in megahit. I am wondering if this is because my files are fastp.fastq.gz? Any help greatly appreciated! Thanks.
[syslog.gz](https://github.com/jtamames/SqueezeMeta/files/8864156/syslog.gz)
[log.o126191.gz](https://github.com/jtamames/SqueezeMeta/files/8864167/log.o126191.gz)

**Comment by astromecki** [comment]
Resolved by rerunning in merged mode

**Comment by astromecki** [comment]
Was able to assemble a number of contigs in merged mode, then received similar error
[syslog.gz](https://github.com/jtamames/SqueezeMeta/files/8865487/syslog.gz)

**Comment by jtamames** [comment]
Hello
The megahit error "unexpected end of file" indicates that it is very likely that some of your files are not correct (truncated possibly). You can check, for instance,  W08-P0003_S910_L002_R1_001.fastp.fastq.gz and W08-P0003_S910_L002_R2_001.fastp.fastq.gz
Best,
J

**Comment by astromecki** [comment]
Thank you! I re-uploaded my files and this seems to have resolved the issue. I have 358 metagenomes and the coassembly mode failed, I expect due to memory shortage. Fingers crossed that merged mode will work.

Thank you for the excellent tools and quick response!
Amanda
