### ISSUE TITLE
Rename X axis labels in SQMtools

### ISSUE THREAD

**Issue by analopezlopez** [jtamames/SqueezeMeta#508]
Hi,

Is there a way to rename the X axis labels when using the `plotTaxonomy` function? If not, can they be removed? I can't seem to find it in the R documentation.

Thank you in advance!

**Comment by fpusan** [comment]
You can create custom plots from tables using `plotBars` and `plotHeatmap`.
Otherwise you will have to manually create them as you want with ggplot2 or another package.

**Comment by analopezlopez** [comment]
Understood. Thanks!
