### ISSUE TITLE
re-arrange samples order reach to limit

### ISSUE THREAD

**Issue by linux51** [jtamames/SqueezeMeta#510]
Hi, 
I used plotTaxonomy(SQM, samples=c('1','2','3',...'256')) it's work perfect

but when i added 1-257 of my samples the plotTaxonomy didn't work
![image](https://user-images.githubusercontent.com/104193395/175907512-12b68764-c52e-4f7e-85e4-d05536353c5f.png)

Would you please provide me the solution?

**Comment by fpusan** [comment]
It would seem like there is an unclosed string on parenthesis somewhere in that line

**Comment by linux51** [comment]
I don't think so. If you look to the first plotTaxonomy function the last sample is ERS436720_crc  the function plot perfect.  The second plotTaxonomy function i added one more (ERS436721_crc) but can't plot the taxonomy. Would you please suggest another solution?

Best,

**Comment by jtamames** [comment]
But you realize that the command didn´t fail, instead R is prompting for more input, as it can be seen by that "+" response when you type the command. This indicates that indeed there is a missing parenthesis or quotes or something

**Comment by linux51** [comment]
Thank you
