### ISSUE TITLE
run error input file for -fasta is in UNKNOWN format not in FASTA format

### ISSUE THREAD

**Issue by pedres** [jtamames/SqueezeMeta#511]
Hi,
I have tried a run of SequeezeMeta with the following command:
- raw fastqs (obtained with fastq-dump from sra) are in an external disc, from where I run SqueezeMeta
- output files are directed to an internal disc

SqueezeMeta.pl -m merged -p /media/fulgencio/DATOS/grapes_vcs_merged -s test.samples -f fastqs -t 20, but the program exit with the following error:
Run started Tue Jun 28 12:47:23 2022 in merged mode
Now creating directories
Reading configuration from /media/fulgencio/DATOS/grapes_vcs_merged/SqueezeMeta_conf.pl
Reading samples from /media/fulgencio/DATOS/grapes_vcs_merged/data/00.grapes_vcs_merged.samples
cp: el objetivo '/media/fulgencio/DATOS/grapes_vcs_merged/data/raw_fastq/SRR16797976_pass_1.fastq' no es un directorio
cp: el objetivo '/media/fulgencio/DATOS/grapes_vcs_merged/data/raw_fastq/SRR16797976_pass_2.fastq' no es un directorio
cp: el objetivo '/media/fulgencio/DATOS/grapes_vcs_merged/data/raw_fastq/SRR16797977_pass_1.fastq' no es un directorio
cp: el objetivo '/media/fulgencio/DATOS/grapes_vcs_merged/data/raw_fastq/SRR16797977_pass_2.fastq' no es un directorio
cp: el objetivo '/media/fulgencio/DATOS/grapes_vcs_merged/data/raw_fastq/SRR16797978_pass_1.fastq' no es un directorio
cp: el objetivo '/media/fulgencio/DATOS/grapes_vcs_merged/data/raw_fastq/SRR16797978_pass_2.fastq' no es un directorio
cp: el objetivo '/media/fulgencio/DATOS/grapes_vcs_merged/data/raw_fastq/SRR16797979_pass_1.fastq' no es un directorio
cp: el objetivo '/media/fulgencio/DATOS/grapes_vcs_merged/data/raw_fastq/SRR16797979_pass_2.fastq' no es un directorio
cp: el objetivo '/media/fulgencio/DATOS/grapes_vcs_merged/data/raw_fastq/SRR16797980_pass_1.fastq' no es un directorio
cp: el objetivo '/media/fulgencio/DATOS/grapes_vcs_merged/data/raw_fastq/SRR16797980_pass_2.fastq' no es un directorio
cp: el objetivo '/media/fulgencio/DATOS/grapes_vcs_merged/data/raw_fastq/SRR16797981_pass_1.fastq' no es un directorio
cp: el objetivo '/media/fulgencio/DATOS/grapes_vcs_merged/data/raw_fastq/SRR16797981_pass_2.fastq' no es un directorio
cp: el objetivo '/media/fulgencio/DATOS/grapes_vcs_merged/data/raw_fastq/SRR16797988_pass_1.fastq' no es un directorio
cp: el objetivo '/media/fulgencio/DATOS/grapes_vcs_merged/data/raw_fastq/SRR16797988_pass_2.fastq' no es un directorio
cp: el objetivo '/media/fulgencio/DATOS/grapes_vcs_merged/data/raw_fastq/SRR16797999_pass_1.fastq' no es un directorio
cp: el objetivo '/media/fulgencio/DATOS/grapes_vcs_merged/data/raw_fastq/SRR16797999_pass_2.fastq' no es un directorio
cp: el objetivo '/media/fulgencio/DATOS/grapes_vcs_merged/data/raw_fastq/SRR16798008_pass_1.fastq' no es un directorio
cp: el objetivo '/media/fulgencio/DATOS/grapes_vcs_merged/data/raw_fastq/SRR16798008_pass_2.fastq' no es un directorio
cp: el objetivo '/media/fulgencio/DATOS/grapes_vcs_merged/data/raw_fastq/SRR16798009_pass_1.fastq' no es un directorio
cp: el objetivo '/media/fulgencio/DATOS/grapes_vcs_merged/data/raw_fastq/SRR16798009_pass_2.fastq' no es un directorio
cp: el objetivo '/media/fulgencio/DATOS/grapes_vcs_merged/data/raw_fastq/SRR16798010_pass_1.fastq' no es un directorio
cp: el objetivo '/media/fulgencio/DATOS/grapes_vcs_merged/data/raw_fastq/SRR16798010_pass_2.fastq' no es un directorio
cp: el objetivo '/media/fulgencio/DATOS/grapes_vcs_merged/data/raw_fastq/SRR16798011_pass_1.fastq' no es un directorio
cp: el objetivo '/media/fulgencio/DATOS/grapes_vcs_merged/data/raw_fastq/SRR16798011_pass_2.fastq' no es un directorio
12 samples found: SRR16797980 SRR16798009 SRR16797978 SRR16797988 SRR16798008 SRR16797999 SRR16797976 SRR16798011 SRR16797977 SRR16797981 SRR16798010 SRR16797979

[0 seconds]: STEP1 -> RUNNING ASSEMBLY: 01.run_assembly_merged.pl (megahit)

  Sample SRR16797976
cat: /media/fulgencio/DATOS/grapes_vcs_merged/data/raw_fastq/SRR16797976_pass_1.fastq: No existe el archivo o el directorio
cat: /media/fulgencio/DATOS/grapes_vcs_merged/data/raw_fastq/SRR16797976_pass_2.fastq: No existe el archivo o el directorio
  Running Megahit (Li et al 2015, Bioinformatics 31(10):1674-6) for SRR16797976
  Running prinseq (Schmieder et al 2011, Bioinformatics 27(6):863-4) for selecting contigs longer than 200

ERROR: input file for -fasta is in UNKNOWN format not in FASTA format.

Try 'perl prinseq-lite.pl -h' for more information.
Exit program.

**Comment by pedres** [comment]
Javier Tamames ***@***.***> escribió:

>  
>
>   Hello
> Notice that the project name must be a name, not a directory. Try  
> changing to -p grapes_vcs_merged
> Best,
> J
>
>   —
> Reply to this email directly, view it on GitHub[1], or unsubscribe[2].
> You are receiving this because you authored the thread.Message ID:  
> ***@***.***>

Thanks for your fast answer.

It works,

Vínculos:
---------
[1] https://github.com/jtamames/SqueezeMeta/issues/511#issuecomment-1168477081
[2]

**Comment by jtamames** [comment]
Glad to hear. Closing issue
