### ISSUE TITLE
Running "sqm_annot.pl"

### ISSUE THREAD

**Issue by mars188** [jtamames/SqueezeMeta#512]
Dear developer, 

I want to run "sqm_annot.pl" script for functional and taxonomic annotation and gene abundance estimation from each bin/metagenome. Help menu shows the following message:

`Usage: SQM_annot.pl -f <faa directory> -s <samples file> [options]`

I believe -s samples is the file that should contain the sample names but what "faa directory" is supposed to contain? fastq/fasta files?

I tried with -s samples and -f directory containing fasta or fastq files but it doesn't run. It just creates the directories for all the samples and dies. Error shows it expects `results/{sample}.faa` file for each sample but it's not there. 

`Error: Error calling stat on file /scratch/gencore/ma5877/metaphlan/environ_analysis/original/metawrap/squeezemeta/anno/bin10/results/03.bin10.faa
Error running command:    /scratch/gencore/conda3/envs/SqueezeMeta/SqueezeMeta/bin/diamond blastp -q /scratch/gencore/ma5877/metaphlan/environ_analysis/original/metawrap/squeezemeta/anno/bin10/results/03.bin10.faa -p 12 -d /scratch/gencore/ma5877/metaphlan/environ_analysis/original/metawrap/database/db/nr.dmnd -e 0.001 --id 40 -f tab -b 16 --quiet -o /scratch/gencore/ma5877/metaphlan/environ_analysis/original/metawrap/squeezemeta/anno/bin10/intermediate/04.bin10.nr.diamond at /scratch/gencore/conda3/envs/SqueezeMeta/SqueezeMeta/scripts/04.rundiamond.pl line 72.
Died at /scratch/gencore/conda3/envs/SqueezeMeta/SqueezeMeta/utils/sqm_annot.pl line 223, <in> line 17.`

Do I need to run any other step before running the sqm_annot.pl or how can I make it run? I need to estimate gene abundance in each genome. I will really appreciate any help!

Best regards,

**Comment by jtamames** [comment]
Hello
It is a good idea to take a look at the manual. This and other questions can find a quick answer there. Quoting the part referring to sqm_annot.pl:

> sqm_annot.pl
> This script performs functional and taxonomic annotation for a set of genes or genomes.
> Genomes must be nucleotide sequences, while gene sequences can be either nucleotides
> or amino acids. All sequence files must be in fasta format.
> For a genome, the script will call SqueezeMeta to predict RNAs and CDS, and then
> proceeds to run Diamond searches against the usual taxonomic (GenBank nr) and
> functional (COGs and KEGG) databases and annotate the genes according the same
> procedures used in the main SqueezeMeta pipeline (LCA for taxa, best hit/best average
> for functions. Please refer to the “Explanation of SqueezeMeta Algorithms'' section for
> details). For gene sequences, it is assumed that each sequence corresponds to an
> already identified ORF, and then RNA and CDS prediction is skipped.
> Diamond searches are automatically set to “blastp” for amino acids, and “blastx” for
> nucleotides.
> The scripts needs a sample file following the format:
` <sample name> <fasta file name> <genome|aa|nt>`

> The first field corresponds to the project name. The script will create a project
> directory with that name, where all results will be placed. The second field is the name
> of the genome, amino acid or nucleotide fasta file containing the sequences. And the
> third field specifies the type of data: genome, aa or nt. As explained above, genome will
> trigger gene prediction and run Diamond blastp on the predicted peptides, aa will run
> Diamond blastp for the provided sequences, and nt will run Diamond blastx for the
> provided sequences.

> Mandatory parameters
> ● -f: Directory in which the sequence files specified in the samples file are located
> (REQUIRED). The sequence files MUST be in FASTA format.
> ● -s: Samples file (REQUIRED)

Best,
J

**Comment by mars188** [comment]
Thank you for the detailed response. I have read the manual but when I run the script I get the error. My script is here:

`sqm_annot.pl -f bins -s genomes.samples`

bins: directory contains 17 fasta files
`bin10.fa  
bin17.fa  
bin24.fa`
genomes.samples: this files contains the names of all the 17 bins
bin10   bin10.fa        pair1
bin17   bin17.fa        pair1
bin24   bin24.fa        pair1

But I get the following error. 

`Error: Error calling stat on file /scratch/gencore/ma5877/metaphlan/environ_analysis/original/metawrap/squeezemeta/anno/bin10/results/03.bin10.faa
Error running command:    /scratch/gencore/conda3/envs/SqueezeMeta/SqueezeMeta/bin/diamond blastp -q /scratch/gencore/ma5877/metaphlan/environ_analysis/original/metawrap/squeezemeta/anno/bin10/results/03.bin10.faa -p 12 -d /scratch/gencore/ma5877/metaphlan/environ_analysis/original/metawrap/database/db/nr.dmnd -e 0.001 --id 40 -f tab -b 16 --quiet -o /scratch/gencore/ma5877/metaphlan/environ_analysis/original/metawrap/squeezemeta/anno/bin10/intermediate/04.bin10.nr.diamond at /scratch/gencore/conda3/envs/SqueezeMeta/SqueezeMeta/scripts/04.rundiamond.pl line 72.
Died at /scratch/gencore/conda3/envs/SqueezeMeta/SqueezeMeta/utils/sqm_annot.pl line 223, <in> line 17.`

It does create the directories for all the mentioned samples but then dies with the above error. Am I missing something?

Many thanks,

**Comment by jtamames** [comment]
Glad to hear! Closing issue
