### ISSUE TITLE
ERROR: input file for -fasta is in UNKNOWN format not in FASTA format calling the prinseq-lite.pl from 01.run_assembly.pl

### ISSUE THREAD

**Issue by imbmanna** [jtamames/SqueezeMeta#516]
I was trying to analyze some FASTQ files using the coassembly mode. I got the following error. 

> [0 seconds]: STEP1 ->  RUNNING ASSEMBLY: 01.run_assembly.pl (megahit)
>   Running assembly with megahit
>   Running prinseq (Schmieder et al 2011, Bioinformatics 27(6):863-4) for selecting contigs longer than 200 
> 
> ERROR: input file for -fasta is in UNKNOWN format not in FASTA format.
> 
> Try 'perl prinseq-lite.pl -h' for more information.
> Exit program.
> 
> Stopping in STEP1 -> 01.run_assembly.pl. Program finished abnormally
> 

I could find that in the 01.run_assembly.pl file on line 126, only the -fasta input is specified when calling the prinseq-lite.pl. 
     

> `$command="$prinseq_soft -fasta $outassembly -min_len $mincontiglen -out_good $resultpath/prinseq; mv $resultpath/prinseq.fasta $contigsfna > /dev/null 2>&1";`

Please help to troubleshoot the issue. I can't modify the prinseq-lite.pl as I don't have the admin privileges.

**Comment by jtamames** [comment]
Hello
Syslog, please?
Best,

**Comment by imbmanna** [comment]
Hi Javier,

It is resolved by changing the extension from file.fastq.gz to file.fastq; I am closing the thread. 

Thank you.
