### ISSUE TITLE
invalid 'row.names' length

### ISSUE THREAD

**Issue by analopezlopez** [jtamames/SqueezeMeta#518]
Hi, 

I'm trying to reproduce a NMDS run with vegan using your Supplementary Material document as a guide, but I keep getting this error:

```
library('vegan')
metadata = as.data.frame(c(rep('Control', 8), rep('Pulmon', 5), rep('Ovario', 4), rep('Mama', 6)))
rownames(metadata) = colnames(combined$taxa$genus$percent)
colnames(metadata) = 'condition'

genus_pc = t(combined$taxa$genus$percent)
MDS = metaMDS(genus_pc)
colvec = c('#0c0900','#ffc020','#a1caf1',"#cd5c5c")
svg('combinedMDS.svg')
plot(MDS, display = 'sites')
with(metadata, points(MDS, display = 'sites', col = colvec[condition], pch = 19))
with(metadata, legend('topright', legend = levels(condition), col = colvec, pch = 21,
pt.bg = colvec))
dev.off()
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length
```
Also, is there a way to reorder the samples to be plotted with this function? (something like x <- c, and then samples = x, maybe?)

Thanks!

**Comment by fpusan** [comment]
@ggnatalia could you help with this?

**Comment by ggnatalia** [comment]
Sure! Could you check please that the number of samples in your  project is the same that the number of samples in your metadata?
To do that run:
    
    length(colnames(combined$taxa$genus$percent)) -> samples in your SQM project
    dim(metadata)

In addition, could you run the code block line by line to know in which line it fails?

**Comment by analopezlopez** [comment]
Hi, 
Sorry, I finally found what the issue was. It was indeed complaining because I was trying to plot only a cohort of samples and therefore, the number of samples didn't match the ones from the project. I ended up plotting everything but, since we are on the subject, would it be any possibility of just plotting a certain group of samples within the metadata? Maybe by generating a subset? I tried a couple of things but none of them worked.

Thank you both!

**Comment by fpusan** [comment]
At this point you don't need SQMtools anymore, just basic object manipulation using R.
You can e.g. just select certain rows from the `genus_pc` matrix, or tell vegan to plot certain samples only when calling `plot` over the MDS object.

**Comment by analopezlopez** [comment]
OK, thank you again!

**Comment by analopezlopez** [comment]
Hi, sorry to bother you again.

I went through the script that I ran to recreate the NMDS figure from your supplementary material documentation and it seems that my problem was not regarding the `plot` calling functions but from the order of the samples within the SQM object in the first place. 

So the thing is: I created a combined object from different SQM projects and as I result I get this matrix with all the samples in the order in which they were sequenced, which is random. Is there a way to rearrange this order in the `combined$taxa$genus$percent` matrix so that when I use the `rownames` and `colnames` functions they'd be already in the right place? 

I'm sure this is basic R.. but I'm a newbie here and I've been trying a lot of things that unfortunately didn't work, so I would really appreciate if you could give me a hand! @ggnatalia

**Comment by ggnatalia** [comment]
Hi!

If I understand your problem, your metadata matrix has rows in a different order than the columns of your dataframe from SQM (combined$taxa$genus$percent).

As you create your metadata table from scratch, you can decide the order of your rows. So, imagine

If you have this metadata (1):
   
    'S1' = 'blue', 'S2' = 'green', 'S3' = 'blue'

And your df with counts is like:

    df = as.data.frame(matrix(c(30, 60, 35, 10, 30, 5, 40, 5, 45, 20, 5, 15), nrow = 4, ncol = 3))
    colnames(df) = c('S1','S2','S3')
    rownames(df) = c('Genus1', 'Genus2','Genus3','Genus4')
    df
                     S1 S2 S3
               Genus1 30 30 45
               Genus2 60  5 20
               Genus3 35 40  5
               Genus4 10  5 15


   A) Your metadata would be:

     metadata = as.data.frame(c('blue', 'green', 'blue')) # same order than your df columns ('S1','S2','S3')
     rownames(metadata) = colnames(df) 
     colnames(metadata) = 'condition'
     metadata
                     condition
               S1      blue
               S2      green
               S3      blue


Therefore, when you define your metadata [metadata = as.data.frame(c(rep('Control', 8), rep('Pulmon', 5), rep('Ovario', 4), rep('Mama', 6))) ], you can write them in the same order than your df (combined$taxa$genus$percent).

B) If you have a big number of metadata, and some of them are the same, you can use the R function rep

In the previous example:

    metadata = as.data.frame(c(rep('blue', 2), rep('green', 1)))
    colnames(metadata) = 'condition'
    If you try to assign the rownames as in your df, they will be wrong:
    rownames(metadata) = colnames(df) # not do it
   
                     condition
               S1      blue 
               S2      blue #They are wrong, S2 is supposed to be green, not blue!
               S3      green

The right order in this case would be:
     
     rownames(metadata) = c('S1', 'S3', 'S2') # As it has been defined in (1)
                     condition
               S1      blue 
               S3      blue 
               S2      green


In this case, you can do 2 different things, order the metadata (as in example A) or order the dataframe (see below):

You need to know the new order, as I do not know if you have it defined in a previous df or vector with the order, I create one:

    metadata = as.data.frame(c(rep('blue', 2), rep('green', 1)))
    colnames(metadata) = 'condition'
    rownames(metadata) = c('S1', 'S3', 'S2')
    df = df[ , rownames(metadata)]
    df
                        S1 S3 S2
                Genus1 30 45 30
                Genus2 60 20  5
                Genus3 35  5 40
                Genus4 10 15  5

There are other alternatives to sort datafames. The point is that the samples order is the same in metadata and in your df so you can plot them with the proper columns.

Moreover, I recommend you when you do the plot to be sure that the point color is the right color according to the metadata.

**Comment by analopezlopez** [comment]
Hi, @ggnatalia 

Thank you so much for your thorough explanation. 

Just to clarify one last thing. So, if I followed your instruction correctly, I did as it follows:

```
metadata = as.data.frame(c(rep('Control', 8), rep('Pulmon', 5), rep('Ovario', 4), rep('Mama', 6), rep('Otros tumores', 6), rep('EII',5)))
colnames(metadata) = 'condition'
rownames(metadata) = c("barcode01.run3","barcode02.run3","barcode03.run3","barcode01.run5","barcode02.run5","barcode03.run5","barcode04.run5","barcode05.run5","barcode02.run1","barcode03.run1","barcode05.run1","barcode08.run5","barcode09.run5","barcode07.run1","barcode08.run1","barcode12.run1","barcode01.run4","barcode02.run4","barcode03.run4","barcode04.run4","barcode07.run4","barcode07.run5","barcode10.run5","barcode06.run1","barcode12.run4","barcode06.run5","barcode05.run4","barcode06.run4","barcode10.run4","barcode04.run1","barcode08.run4","barcode11.run4","barcode01.run1","barcode09.run4")
```

And this way I got the desired order for the barcodes in the metadata:
```
metadata
                   condition
barcode01.run3       Control
barcode02.run3       Control
barcode03.run3       Control
barcode01.run5       Control
barcode02.run5       Control
barcode03.run5       Control
barcode04.run5       Control
barcode05.run5       Control
barcode02.run1        Pulmon
barcode03.run1        Pulmon
barcode05.run1        Pulmon
barcode08.run5        Pulmon
barcode09.run5        Pulmon
barcode07.run1        Ovario
barcode08.run1        Ovario
barcode12.run1        Ovario
barcode01.run4        Ovario
barcode02.run4          Mama
barcode03.run4          Mama
barcode04.run4          Mama
barcode07.run4          Mama
barcode07.run5          Mama
barcode10.run5          Mama
barcode06.run1 Otros tumores
barcode12.run4 Otros tumores
barcode06.run5 Otros tumores
barcode05.run4 Otros tumores
barcode06.run4 Otros tumores
barcode10.run4 Otros tumores
barcode04.run1           EII
barcode08.run4           EII
barcode11.run4           EII
barcode01.run1           EII
barcode09.run4           EII
```

However, if I keep going with the rest of the script: 

```
genus_pc = t(combined$taxa$genus$percent)
MDS = metaMDS(genus_pc)
colvec = c(rep('#0c0900', 8), rep('#90ee90', 5), rep('#cd5c5c', 4), rep('#a9a9a9', 6), rep('#a1caf1', 8), rep('#ffc020', 5))
plot(MDS, display = 'sites')
with(metadata, points(MDS, display = 'sites', col = colvec[condition], pch = 19))
with(metadata, legend('topright', legend = levels(condition), col = colvec, pch = 21,
pt.bg = colvec))
with(metadata, ordiellipse(MDS, condition, col = colvec, alpha = 70, draw = 'polygon', border = colvec))
```
Since `combined$taxa$genus$percent` has a different sample order and the MDS object is created using this matrix, isn't this going to substitute again the order I arranged earlier in "metadata"?

**Comment by ggnatalia** [comment]
You can do 2 different things:

A) Order your metadata samples as they are in your genus_pc matrix

    metadata = as.data.frame(c(rep('blue', 2), rep('green', 1)))
    colnames(metadata) = 'condition'
    rownames(metadata) = c('S1', 'S3', 'S2')
    metadata_sorted = metadata[colnames(genus_df),, drop = F] # Drop = F is because when your df has only one column R convert it into vector, with drop = F it is still a dataframe.

B) Order your genus_pc matrix columns as in your metadata samples

    metadata = as.data.frame(c(rep('blue', 2), rep('green', 1)))
    colnames(metadata) = 'condition'
    rownames(metadata) = c('S1', 'S3', 'S2')
    genus_pc = genus_pc[ , rownames(metadata)]
    genus_pc

Moreover, your vector color must have the colors in the same order as your metadata (and sort them after if your change the order of your metadata to agree with the order of the genus_pc). The point is that the order of your genus_px == order metadata & colors.

Finally, your are not going to substitute the order of anything, genus_pc matrix, MDS, metadata and colvec. They are different objects and unless you change the order manually, the things that you do in one of them are not going to affect the rest of the objects. In fact, that is the reason why you have to order them in the same way before doing things, so when you do the plot you take the right colors. 

Whe you do something like this:

    genus_pc = genus_pc[ , rownames(metadata)]

you are using one the order of one of the objects (rownames(metadata)) to do a subset in the other object (you're doing the subset in genus_pc, and as you 're selecting all the rows, it takes them one by one in the order they are in the metadata object). 

But if you do not do this, you'll have each object with each order, and you can order them independently (although we do not want it in this example).

I suggest you to write a simple dataframe in R (like in the example), create a metadata example, a color vector and play sorting them, subsetting them to understand how they work. There are different ways of getting the same result, and the code can be adapted to meet the particular needs, the important thing is to check the results and adapt it if it does not do what you want.
