### ISSUE TITLE
Stopping in STEP10 -> 10.mapsamples.pl. Program finished abnormally

### ISSUE THREAD

**Issue by MonicaMN9** [jtamames/SqueezeMeta#520]
Hello! I have the following error:

[6 hours, 43 minutes, 3 seconds]: STEP10 -> MAPPING READS: 10.mapsamples.pl
  Reading samples from /home/rizouser/users/mmn/consorcio_tomate/Run_005_Monica/consorcio_tomate/data/00.consorcio_tomate.samples
  Metagenomes found: 1
  Mapping with Minimap2 (Li 2018, Bioinformatics 34(18), 3094-3100)
  Working with sample 1: consorcio_tomate
  Getting raw reads
  Aligning to reference with [minimap2-ont]
  Calculating contig coverage
  Reading contig length from /home/rizouser/users/mmn/consorcio_tomate/Run_005_Monica/consorcio_tomate/intermediate/01.consorcio_tomate.lon
Can't open /home/rizouser/users/mmn/consorcio_tomate/Run_005_Monica/consorcio_tomate/data/sam/consorcio_tomate.consorcio_tomate.sam
Stopping in STEP10 -> 10.mapsamples.pl. Program finished abnormally

  If you don't know what went wrong or want further advice, please look for similar issues in https://github.com/jtamames/SqueezeMeta/issues
  Feel free to open a new issue if you don't find the answer there. Please add a brief description of the problem and upload the /home/rizouser/users/mmn/consorcio_tomate/Run_005_Monica/consorcio_tomate/syslog file (zip it first)
Died at /home/condapython/anaconda3/envs/SqueezeMeta/bin/SqueezeMeta.pl line 1381.

I think the problem is that the file "consorcio_tomate.consorcio_tomate.sam" has not been created. How can I solve the error?

Thanks in advance,
Mónica

**Comment by jtamames** [comment]
Hello
Syslog, please?

**Comment by MonicaMN9** [comment]
[syslog.txt](https://github.com/jtamames/SqueezeMeta/files/9250250/syslog.txt)

**Comment by jtamames** [comment]
I see that the command you issued was:
`/home/condapython/anaconda3/envs/SqueezeMeta/bin/SqueezeMeta.pl -m sequential -a [flye] -s sample_tomate.txt -f ./ -map [minimap2-ont] -t 8 --lowmem`
Please remove the brackets from the assembler and mapper names. Try:
`/home/condapython/anaconda3/envs/SqueezeMeta/bin/SqueezeMeta.pl -m sequential -a flye -s sample_tomate.txt -f ./ -map minimap2-ont -t 8 --lowmem`
Best,
J

**Comment by MonicaMN9** [comment]
Ok, thanks. I am trying it.

Regards,
M
