### ISSUE TITLE
Canu Assembly on cluster

### ISSUE THREAD

**Issue by aalkin2001** [jtamames/SqueezeMeta#522]
Hi,
I am running the SqueezeMeta script on the cluster HPC on minion data, but the assembly step (step 1) has been running for days without completing or giving any error message. I am using 30 threads machine and I don't expect that the analysis would be this long. Ordinary the whole pipeline should be completed within 24 hrs.

I am not sure if I am missing something. Do you have an idea why this is happening?

Thank you.

**Comment by fpusan** [comment]
This is weird, considering that it worked for you using other samples. When it worked, were you also using canu as the assembler?
What is the output of canu so far? It should say something in the syslog file. If the problem is within canu itself, I might not be able to provide much help...
