### ISSUE TITLE
Diamond BlastX error with sqm_longreads.pl

### ISSUE THREAD

**Issue by bgregs94** [jtamames/SqueezeMeta#529]
Hi,

I am running the `sqm_longread.pl` script on Oxford Nanopore MinION reads. I use the following command:

`sqm_longreads.pl -p africanponds_sqm -s /home/bgregs/african_ponds.samples -f /home/bgregs/African_ponds_nanopore_fastq/pass/ -t 40`

I get the following error:

`SqueezeMeta on Long Reads v1.4.0, May 2021 - (c) J. Tamames, F. Puente-Sánchez CNB-CSIC, Madrid, SPAIN

This is part of the SqueezeMeta distribution (https://github.com/jtamames/SqueezeMeta)
Please cite: Tamames & Puente-Sanchez, Frontiers in Microbiology 10.3389 (2019). doi: https://doi.org/10.3389/fmicb.2018.03349

Setting block size for Diamond
  AVAILABLE (free) RAM memory: 1248.30 Gb
We will set Diamond block size to 8 (Gb RAM/5, Max 8). You can override this setting using the -b option when starting the project.

----/home/bgregs/africanponds_sqm---
Now reading samples from /home/bgregs/african_ponds.samples
1 metagenomes found

SAMPLE 1/1: African_ponds_nanopore

   File: all_guppy.fastq.gz
[1 minutes, 19 seconds]: Starting taxonomic annotation
[1 minutes, 19 seconds]: Running Diamond (Buchfink et al 2015, Nat Methods 12, 59-60) for taxa (GenBank nr, Clark et al 2016, Nucleic Acids Res 44, D67-D72)
  Running Diamond BlastX (Buchfink et al 2015, Nat Methods 12, 59-60)
**Error: --top and --max-target-seqs are mutually exclusive.**
  Collapsing hits with blastxcollapse.pl
wc: /home/bgregs/africanponds_sqm/African_ponds_nanopore/African_ponds_nanopore.nr.blastx: No such file or directory
Can't open Diamond file /home/bgregs/africanponds_sqm/African_ponds_nanopore/African_ponds_nanopore.nr.blastx
  Merging splitted hits with mergehits.pl
  Getting nt sequences from /home/bgregs/africanponds_sqm/African_ponds_nanopore/all_guppy.fasta
  Sequences stored in /home/bgregs/africanponds_sqm/African_ponds_nanopore/African_ponds_nanopore.nt.fasta
[1 minutes, 30 seconds]: Running LCA
`

Is there a way to resolve this, such as adjusting --top or --max-target-seqs, or is there a problem with the input files etc?

Ben

**Comment by jtamames** [comment]
Hello!
Could you update to version 1.5, please? All these issues are solved in that version.
Best,
J
