### ISSUE TITLE
issue with sqm2tables.py

### ISSUE THREAD

**Issue by obiwanlopez1986** [jtamames/SqueezeMeta#53]
Hi Javier, I'm having problems with the sqm2tables.py script. I've just upgraded the old script with the one that reads the trnas with aragorn and also change the util.py to the latest one in your git. 
It runs well until the end where it shows this error:

File "/home/install/SqueezeMeta-1.0.0/utils//sqm2tables.py", line 164, in <module>
    main(parse_args())
  File "/home/install/SqueezeMeta-1.0.0/utils//sqm2tables.py", line 128, in main
    write_orf_seqs(orfs['abundances'].keys(), perlVars['$aafile'], fna_blastx, perlVars['$rnafile'], perlVars['$trnafile'] + '.fasta', prefix + 'orf.sequences.tsv') 
KeyError: '$trnafile'

All the tables are made except for orfs.sequences.tsv, prokfilter.abund.tsv and allfilter.abund.tsv.
Thank you and have a nice day!
Rafa

**Comment by fpusan** [comment]
Hi!
It seems that you are running the new script in a project created with an older version of SqueezeMeta.
There should be a line in the `<project>/SqueezeMeta_conf.pl` file pointing to the aragorn results, which is missing.

**Comment by obiwanlopez1986** [comment]
Thanks a lot Fernando, already upgraded all the SqueezeMeta and it's working!
Have a nice day!

**Comment by fpusan** [comment]
Cheers! Closing issue
