### ISSUE TITLE
Taxa Bar plot

### ISSUE THREAD

**Issue by aalkin2001** [jtamames/SqueezeMeta#531]
[Taxa bar plot.pdf](https://github.com/jtamames/SqueezeMeta/files/9473233/Taxa.bar.plot.pdf)
Hello,
I ran SqueezeMeta script on microbial DNA enriched and unenriched samples and generated the bar plot for the percentage abundance at phylum and species levels. But I noticed from the bar plot generated that there are more unmapped reads in the microbial DNA enriched (HN65S1_mc) sample. 

Here are my questions:

1. I just want to know what the unmapped reads in the bar chart represent.
2. Why do we have more unmapped reads in the enriched sample, technically, since there is more microbial DNA present in the enriched sample, we should have more reads mapped not the other way. 

I am kind of confused with the result generated. Would you please shed more light on why the bar result is like this?

Thank you.

**Comment by jtamames** [comment]
Hello
The unmapped reads are not unclassified taxa, but reads that were not assembled in the assembly step. These reads are therefore not represented in the analysis. You can check the 10.mappingstat files, and you should see that the percentage of reads not in the assembly matches that number. The reasons for this may be many, usually related to the sequencing depth and the diversity and richness of the microbiome. Did you sequence less for the enriched sample than for the other?
Best,
J

**Comment by aalkin2001** [comment]
Hi,

Thank you for your response and clarifications. Yes, I did sequence less of the enriched sample.
