### ISSUE TITLE
Stopping in STEP1 -> 01.run_assembly.pl. Program finished abnormally

### ISSUE THREAD

**Issue by Haq5** [jtamames/SqueezeMeta#532]
Hi, 
I am running SqueezeMeta for test reads available in SqueezeMeta, however, program finished abnormally. Could you please guid me how to resolve this issue. Thanks in anticipation.

Secondly, I am doing these analysis using Mac terminal and when I passed the script "test_install.pl" it gives me the following message. How I can convert my Mac terminal bash to Linux for running SqueezeMeta.

"Checking the OS
The "darwin" OS was detected, but SqueezeMeta only runs on Linux!!"

(base) Abduls-MBP:install_utils abdulhaq$ conda activate SqueezeMeta
(SqueezeMeta) Abduls-MBP:install_utils abdulhaq$ test_install.pl

Checking the OS
The "darwin" OS was detected, but SqueezeMeta only runs on Linux!!

(SqueezeMeta) Abduls-MBP:install_utils abdulhaq$ cd /Volumes/MacOS/opt/miniconda3/envs/SqueezeMeta/SqueezeMeta/utils/install_utils/download/path/db/test
(SqueezeMeta) Abduls-MBP:test abdulhaq$ SqueezeMeta.pl -m coassembly -p test -s test.samples -f raw --nopfam -miniden 50

SqueezeMeta v1.4.0, May 2021 - (c) J. Tamames, F. Puente-Sánchez CNB-CSIC, Madrid, SPAIN

Please cite: Tamames & Puente-Sanchez, Frontiers in Microbiology 9, 3349 (2019). doi: https://doi.org/10.3389/fmicb.2018.03349

Run started Thu Sep  1 14:32:55 2022 in coassembly mode
Now creating directories
Reading configuration from /Volumes/MacOS/opt/miniconda3/envs/SqueezeMeta/SqueezeMeta/utils/install_utils/download/path/db/test/test/SqueezeMeta_conf.pl
Reading samples from /Volumes/MacOS/opt/miniconda3/envs/SqueezeMeta/SqueezeMeta/utils/install_utils/download/path/db/test/test/data/00.test.samples
2 samples found: SRR1929485 SRR1927149

Now merging files
[1 minutes, 54 seconds]: STEP1 -> RUNNING CO-ASSEMBLY: 01.run_assembly.pl (megahit)
  Running assembly with megahit
Error running command:    /Users/abdulhaq/opt/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/megahit/megahit  -1 /Volumes/MacOS/opt/miniconda3/envs/SqueezeMeta/SqueezeMeta/utils/install_utils/download/path/db/test/test/data/raw_fastq/par1.fastq.gz -2 /Volumes/MacOS/opt/miniconda3/envs/SqueezeMeta/SqueezeMeta/utils/install_utils/download/path/db/test/test/data/raw_fastq/par2.fastq.gz -t 12 -o /Volumes/MacOS/opt/miniconda3/envs/SqueezeMeta/SqueezeMeta/utils/install_utils/download/path/db/test/test/data/megahit >> /Volumes/MacOS/opt/miniconda3/envs/SqueezeMeta/SqueezeMeta/utils/install_utils/download/path/db/test/test/syslog 2>&1 at /Users/abdulhaq/opt/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/01.run_assembly.pl line 119.
Stopping in STEP1 -> 01.run_assembly.pl. Program finished abnormally

**Comment by fpusan** [comment]
The main SqueezeMeta pipeline is designed to work on Linux only. Some users have actually managed to make it work on MacOS (see #97) but we can not provide support for that. Note that you can still analyze your results using R and SQMtools in your Mac computer, but the main pipeline has to be run on Linux.
