### ISSUE TITLE
Stopping in STEP1 -> 01.run_assembly.pl. Program finished abnormally

### ISSUE THREAD

**Issue by NataliHB** [jtamames/SqueezeMeta#533]
Hi,

I've been trying to run some samples in coassembly mode  with spades and I've tried with 24 and 32 threads , however it keeps stopping showing " mmap(2) failed. Reason: Cannot allocate memory. Error code: 12" . Here are the two syslog files. 

[syslog 32.txt](https://github.com/jtamames/SqueezeMeta/files/9477817/syslog.32.txt)
[syslog 24.txt](https://github.com/jtamames/SqueezeMeta/files/9477828/syslog.24.txt)

I am wondering how much memory is needed? Do you have any suggestions of what I might be doing wrong here?  

Thank you so much for the help!

Best,
Natali

**Comment by fpusan** [comment]
How many available memory do you have?
It is hard to predict how much memory will you need for a coassembly, as it will depend on the number of samples, the sequencing depth and the complexity of the sample.
An option would be to run SqueezeMeta in the sequential mode instead.

**Comment by NataliHB** [comment]
Hi,

Thank you so much for your suggestions. It is running smoothly in sequential mode with Spades and it also ran successfully in merged mode with Megahit. I'm trying to figure it out how much memory is available since I am using shared space that has 692TB in total (to be fair, I've never ran out of space before...).

Many thanks!

Cheers,
Natali
