### ISSUE TITLE
modifying defaults option of concoct

### ISSUE THREAD

**Issue by pedres** [jtamames/SqueezeMeta#535]
Hi, 

I would like to modify the default contig length that concoct uses (-l LENGTH_THRESHOLD), which is 1000 to 2500. I was looking the 14.runbinning.pl and the documentation of https://github.com/jtamames/SqueezeMeta/tree/master/bin/CONCOCT-1.1.0. However, I did not found how to do it. I would like to do it because I am running SqueezeMeta with -c 1000 and -miniden 80 but I am losing mapping percentages from a previous run with defaults for -c and -miniden

					200/50	1000/80
CT_21_SRR16797976	88.78	82.02
CT_21_SRR16797980	89.18	82.57
CT_21_SRR16798010	85.69	76.66
CT_63_SRR16797977	88.43	82.18
CT_63_SRR16797981	88.04	80.1
CT_63_SRR16798011	83.66	75.85
EW_21_SRR16797978	91.2	       86.79
EW_21_SRR16797988	91.71	86.4
EW_21_SRR16798008	93.78	88.13
EW_63_SRR16797979	92.87	86.59
EW_63_SRR16797999	91.58	84.61
EW_63_SRR16798009	92.38	88.06

Thank you very much for your help

Manuel

**Comment by fpusan** [comment]
You can modify the file
`/path/to/SqueezeMeta/lib/SqueezeMeta/bin_concoct.pl`
The call to concoct is in L107, you should be able to edit that in order to add custom parameters.

**Comment by pedres** [comment]
Ok,

Thanks a lot
