### ISSUE TITLE
Large dataset computing power needed.

### ISSUE THREAD

**Issue by BOASE-Kate** [jtamames/SqueezeMeta#538]
Hello, this isn't so much an issue but a request for advice. 
We are planning to get three to 4 runs of metagenome sequencing done on the Novaseq 6000 S4 Flow cell type. 
This should be roughly around 9000 to 12000Gb of data and we were planning on using SqueezeMeta for the analysis. 
We need to ask for specific computing power from a supercomputer cluster and was wondering if anyone would have any idea how much RAM and CPUs should be sufficient to process a such a large amount of data in coassembly mode, preferably within a week or two.

Any recommendations or advice would be greatly appreciated!

**Comment by fpusan** [comment]
I have honestly no idea. I don't think it will be possible to coassemble everything.
You will possibly have to do individual assemblies, or group samples based on their origin and/or minhash distances and perform several smaller coassemblies.

**Comment by jtamames** [comment]
Same here, never dealt with such sizes and no idea how it will work. Take into account that in any case you can do the assembly externally and then provide the contigs to SqueezeMeta using the -extassembly option to carry on the rest of the analysis
Good luck!
