### ISSUE TITLE
sqmreads2tables.py -q with !=

### ISSUE THREAD

**Issue by bojusemo** [jtamames/SqueezeMeta#539]
Hello,

I'm using sqmreads2tables.py to filter the results obtained with sqm_longreads.pl. I must discard a list of clades plus unclassified families and the "superkingdom" Viruses. To do so, I'm using the command below.

sqmreads2tables.py <project> <output> -q "GENUS != <Genus1> AND PHYLUM != <Phylum1> AND ... AND FAMILY != Unclassified AND SUPERKINGDOM != Viruses"

Maybe I misunderstand the results. However, as I see, not all the filters are being applied. See for example the following result, where Viruses are still present: 

$ cat <output>/<sample>.superkingdom.allfilter.abund.tsv
k_Archaea       845
k_Bacteria      59558
k_Eukaryota     2915
k_Unclassified  1985
k_Viruses       1        

And I still see some unclassified families
grep Unclassified <output>/<sample>.family.allfilter.abund.tsv | head -1
k_Archaea;p_Candidatus Thermoplasmatota;c_Thermoplasmata;o_Methanomassiliicoccales;f_Unclassified Methanomassiliicoccales       29

Could you please let me know how I discard all unclassified families and the "superkingdom" Viruses?

Thank you

Boris

**Comment by fpusan** [comment]
Maybe `-q SUPERKINGDOM != Viruses AND FAMILY DOES NOT CONTAIN "Unclassified"`?
I just realized that `DOES NOT CONTAIN` was not documented in the script, I fixed that.
Also look at the `prokfilter` results rather than the `allfilter` results. The filter is performed over those.
Let me know if this works!

**Comment by bojusemo** [comment]
Hi @fpusan,

Thank you so much for your quite quick reply.

It solved the issue.

Regards

Boris
