### ISSUE TITLE
"sqm_annot.pl" doesn't use optional parameters

### ISSUE THREAD

**Issue by PuspenduSardar** [jtamames/SqueezeMeta#540]
Hello!

I have used the `sqm_annot.pl` script for functional annotation of an assembly file. The script runs fine, but the problem is it uses the default parameters ONLY. For example, I wanted to use 86 threads with no COG annotation. According to the `sqm_annot.pl` help message, I used `-t 86 --nocog ` flags. SqueezeMeta still uses the default 12 threads and produces COG annotation. Could you please let me know if there is a way to make use of these non-default parameters? It would be great if there is a way to declare the percentage of identity for the diamond and evalue.

I am using SqueezeMeta v1.5.2

Many thanks!
Regards,
Puspendu

**Comment by jtamames** [comment]
Hello Puspendu
You are right, there is not a straightforward way to specify these parameters in sqm_annot.pl. I am taking this into account to fix in in upcoming version. What sqm_annot.pl does is calling SqueezeMeta and some SqueezeMeta scripts. SqueezeMeta uses the file parameters.txt to define its settings. You can find there the ones controlling the behavior of the Diamond homology search:

```$evaluetax4=1e-03;	  #-- STEP4: evalue for Diamond, for tax only (also for STEP8)
$minidentax4=40;	  #-- STEP4: Minimum identity for Diamond, for tax only (also for STEP8)
$evaluefun4=1e-03;	  #-- STEP4: evalue for Diamond, for functions only (also for STEP8)
$minidenfun4=30;	  #-- STEP4: Minimum identity for Diamond, for functions only (also for STEP8)
```
Change these accordingly.
Best,
J

**Comment by PuspenduSardar** [comment]
Hello @jtamames,

Thank you very much for your reply and the suggestion.
I have already started an analysis, and it's running for 3 days now. Would you recommend stopping it and using `restart.pl `script after editing the `SqueezeMeta_conf.pl` that has been generated during the run? (I am not sure though if restart would work in this case).
Many thanks,

Regards,
Puspendu

**Comment by jtamames** [comment]
No, restart will not work for sqm_annot. Which step it is now in, 04?

**Comment by PuspenduSardar** [comment]
Yes. blastx is running with nr db.

**Comment by jtamames** [comment]
Unfortunately there is no good way to know the progress of the blastx step. That is the most demanding step (blastx/nr), the rest of the pipeline will take less time. Consider if you want to wait a bit or rerun it setting higher number of threads.

**Comment by PuspenduSardar** [comment]
Thank you very much, @jtamames.
I'll close the issue now.
