### ISSUE TITLE
Encountered problems while solving: perl

### ISSUE THREAD

**Issue by fairquestion** [jtamames/SqueezeMeta#541]
Hi there,

when using mamba as you suggested:

mamba create -n SqueezeMeta -c conda-forge -c bioconda -c fpusan squeezemeta

I am getting this error:
Looking for: ['squeezemeta']

fpusan/linux-64          [====================] (00m:00s) Done
fpusan/noarch            [====================] (00m:00s) Done
bioconda/noarch          [====================] (00m:01s) Done
bioconda/linux-64        [====================] (00m:01s) Done
conda-forge/noarch       [====================] (00m:02s) Done
pkgs/r/linux-64          [====================] (00m:00s) No change
pkgs/r/noarch            [====================] (00m:00s) No change
pkgs/main/noarch         [====================] (00m:00s) Done
pkgs/main/linux-64       [====================] (00m:01s) Done
conda-forge/linux-64     [====================] (00m:06s) Done

**Encountered problems while solving:
  - package squeezemeta-1.1.0rc1-pl526r36_0 requires perl 5.26.*, but none of the providers can be installed**

Any advice?

**Comment by fpusan** [comment]
Weird it is trying to install version 1.1.0.
Can you try with `mamba create -n test -c conda-forge -c bioconda -c fpusan squeezemeta=1.6`
?

**Comment by fairquestion** [comment]
Hi, yes, `mamba create -n test -c conda-forge -c bioconda -c fpusan squeezemeta=1.6` installs it perfectly.

**Comment by fpusan** [comment]
Glad to hear! closing issue

**Comment by fpusan** [comment]
Hard to tell, I just tried and it is working in my side.
Maybe there is something weird with your channel priorities.
Can you try on a fresh miniconda installation?
https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
