### ISSUE TITLE
POSTED UNDER WRONG TOPIC, PLEASE DELETE: Das_Tool does not produce PDF plots

### ISSUE THREAD

**Issue by BostjanMurovec** [jtamames/SqueezeMeta#544]
Hello,

I am struggling to obtain PDF plots in relation to directive --create_plots.
The plots are not produced and no solution seems to work.
I have installed Das_Tool from Conda (updated today) with channels:
defaults, conda-forge, cyclus, bioconda, pytorch-lts.

I have noticed that package r-ggplot2 is missing from Das_Tool environment, and I tried to install it manually through a conda package as well as from within R system by command install.packages("ggplot2", repos="http://cran.us.r-project.org"). Both ways seem to succeed, but PDF plots are still not produced.

Any help is appreciated. I am attaching Das_Tool log file and list of packages in Das_Tool Conda environment.
Kindest regards,

Bostjan Murovec

[das_tool_environment.txt](https://github.com/jtamames/SqueezeMeta/files/9594989/das_tool_environment.txt)
[DASTool.log](https://github.com/jtamames/SqueezeMeta/files/9594990/DASTool.log)

**Comment by fpusan** [comment]
Closing as requested
