### ISSUE TITLE
Running SqueezeMeta Co-assembly by keeping both pair end and single end reads from trimmomatic

### ISSUE THREAD

**Issue by imbmanna** [jtamames/SqueezeMeta#546]
Hi @jtamames

I have a similar issue as #99 , I have a sample where after performing the Trimmomatic quality control, reads survived both R1 + R2 were ~50% of the original reads. The survived unpaired forward (U1) and reverse reads (U2) had about ~40% and ~6%, respectively. So, proceeding with only the paired end reads will loose ~46% of the sequence data. As per your suggestion in #99,

"...What you can do is using the merged or seqmerge modes.There each sample is assembled separately so you can use any combination of single and paired reads."

I tried something like below:

Sample1 sample1_1P.fq.gz pair1
Sample1 sample1_2P.fq.gz pair2
Sample1 sample1_1U.fq.gz pair1
Sample1 sample1_2U.fq.gz pair1
Sample2 sample2_1P.fq.gz pair1
Sample2 sample2_2P.fq.gz pair2
Sample2 sample2_1U.fq.gz pair1
Sample2 sample2_2U.fq.gz pair1

I tried both the merged or seqmerge modes but the run is aborted during the

[31mStopping in STEP1 -> 01.run_assembly_merged.pl. Program finished abnormally

with the following error.

2022-09-20 14:02:52 - Error occurs when reading inputs during the

Can you please suggest if I am using the combination of single end and paired end correctly?

Thank you,
BM.

**Comment by jtamames** [comment]
Hello
It won't work as you intend. Any of the modes will merge all "pair1" files into one file, and all "pair2" into another. As you have more files (and reads) for pair1 in Sample1, the assembler will not work. The only way you can run it is the following:

Sample1 sample1_1P.fq.gz pair1
Sample1 sample1_2P.fq.gz pair2
Sample1_1 sample1_1U.fq.gz pair1
Sample1_2 sample1_2U.fq.gz pair1
Sample2 sample2_1P.fq.gz pair1
Sample2 sample2_2P.fq.gz pair2
Sample2_1 sample2_1U.fq.gz pair1
Sample2_2 sample2_2U.fq.gz pair1

That will result in 4 different samples in your analysis. I guess you could merge samples later on using combineSQM in SQMtools. But, what I  really recommend to do is to carefully inspect your reads to know why are they being dropped by quality. It looks like something went wrong on the sequencing, and that is not a good start.
Best,
J

**Comment by imbmanna** [comment]
Hi Javier,

Thank you so much for the help. I will try your suggestion and check for any improvement. I will also contact the sequencing facility to get some insight. 

Thank you,
BM.

**Comment by imbmanna** [comment]
Hi Javier,

I followed your suggestion for creating the sample file and performed the run. Now, I am confused how to merge the samples. I get total six samples after using combineSQM. i.e., Sample1, Sample1_1, Sample1_2, Sample2, Sample2_1, and Sample2_2. 

Now, for a specific taxa/KO, can I simply take the sum of the Sample1, Sample1_1 and Sample1_2 to get Abundance (count) for whole Sample1? Would that be a right interpretation of the results? 

Also, would the same be applicable for the TPM values as calculated per sample? 

Thank you,
BM.

**Comment by imbmanna** [comment]
Hi Javier,

I followed your suggestion for creating the sample file and performed the run. Now, I am confused how to merge the samples. I get total six samples after using combineSQM. i.e., Sample1, Sample1_1, Sample1_2, Sample2, Sample2_1, and Sample2_2.

Now, for a specific taxa/KO, can I simply take the sum of the Sample1, Sample1_1 and Sample1_2 to get Abundance (count) for whole Sample1? Would that be a right interpretation of the results?

Also, would the same be applicable for the TPM values as calculated per sample?

Thank you,
BM.

**Comment by fpusan** [comment]
For the abundance, yes, it would be a correct interpretation of the results.
For the TPM it would be a bit more complicated than that. You can not simply add the different TPMs. You need to instead recalculate them from the abundances.

E.g. to recalculate the KO tpms
1) You first get the abundances of every KO term as the sum of its abundances in every "sub-sample".
2) You also get the average length (in kilobases) of every KO term, as shown in `SQM$orfs$table`
3) For each KO, you calculate its rpk as `abundance/lenght_kb`
4) For each KO, you calculate its tpm as `1000000 * rpk/sum_of_all_rpks`

For reference, here's our python code to do it

```

    def tpm(funDict):
        # Calculate reads per kilobase.    
        fun_avgLengths = {fun: funDict['lengths'][fun] / funDict['copies'][fun] for fun in funDict['lengths']} # NaN appears if a fun has no copies in a sample.
        fun_rpk = {fun: funDict['abundances'][fun] / (fun_avgLengths[fun]/1000) for fun in funDict['abundances']}
        if ignore_unclassified_fun:
            fun_rpk = {fun: rpk for fun, rpk in fun_rpk.items() if fun != 'Unclassified'}

        # Remove NaNs.
        for fun, rpk in fun_rpk.items():
            rpk[isnan(rpk)] = 0

        # Get tpm.    
        fun_tpm = normalize_abunds(fun_rpk, 1000000)
        return fun_tpm
```

**Comment by imbmanna** [comment]
Hi Fernando,

Thank you so much for the help and clarification. 

I am closing the issue. I will try your suggestions and get back in case I face any problems. 

Best, 
BM
