### ISSUE TITLE
Error in STEP 14

### ISSUE THREAD

**Issue by EorgeKit** [jtamames/SqueezeMeta#547]
HI there, regarding the problem with failure in STEP 14, I am also getting a similar problem in my analysis and I am not doing a metatranscriptomic analysis. The error I get is as follows:
```bash
============
GENE TABLE CREATED: /srv/data/my_shared_data_folder/amrcattle/metagenome_analysis_results/mgm4754670.3/results/1
3.mgm4754670.3.orftable
============

ESC[34m[36 minutes, 16 seconds]: STEP14 -> BINNING: 14.runbinning.pl
ESC[0mError running command:    perl /opt/SqueezeMeta-1.5.2/bin/MaxBin/run_MaxBin.pl -thread 30 -contig /srv/data/my_shared_data_folder/amrcattle/metagenome_analysis_results/mgm4754670.3/temp/bincontigs.fasta -abund_list /srv/data/my_shared_data_folder/amrcattle/metagenome_analysis_results/mgm4754670.3/intermediate/binners/maxbin/abund.list -out /srv/data/my_shared_data_folder/amrcattle/metagenome_analysis_results/mgm4754670.3/intermediate/binners/maxbin/maxbin -markerpath /opt/SqueezeMeta-1.5.2/db/marker.hmm at /opt/SqueezeMeta-1.5.2/lib/SqueezeMeta/bin_maxbin.pl line 132.
wc: /srv/data/my_shared_data_folder/amrcattle/metagenome_analysis_results/mgm4754670.3/intermediate/binners/maxbin/: Is a directory
wc: /srv/data/my_shared_data_folder/amrcattle/metagenome_analysis_results/mgm4754670.3/intermediate/binners/metabat2/: Is a directory
```
Note that that error started in my second set of samples, a previous set ran just fine and got a lot of bins.also I ran both sets without modifying the code . Could it be an issue with my samples or what could I be about, I also tried with another set of samples and it still failed

**Comment by fpusan** [comment]
What is the output of
`perl /opt/SqueezeMeta-1.5.2/bin/MaxBin/run_MaxBin.pl -thread 30 -contig /srv/data/my_shared_data_folder/amrcattle/metagenome_analysis_results/mgm4754670.3/temp/bincontigs.fasta -abund_list /srv/data/my_shared_data_folder/amrcattle/metagenome_analysis_results/mgm4754670.3/intermediate/binners/maxbin/abund.list -out /srv/data/my_shared_data_folder/amrcattle/metagenome_analysis_results/mgm4754670.3/intermediate/binners/maxbin/maxbin -markerpath /opt/SqueezeMeta-1.5.2/db/marker.hmm`
?

**Comment by fpusan** [comment]
Yep

**Comment by EorgeKit** [comment]
> perl /opt/SqueezeMeta-1.5.2/bin/MaxBin/run_MaxBin.pl -thread 30 -contig /srv/data/my_shared_data_folder/amrcattle/metagenome_analysis_results/mgm4754670.3/temp/bincontigs.fasta -abund_list /srv/data/my_shared_data_folder/amrcattle/metagenome_analysis_results/mgm4754670.3/intermediate/binners/maxbin/abund.list -out /srv/data/my_shared_data_folder/amrcattle/metagenome_analysis_results/mgm4754670.3/intermediate/binners/maxbin/maxbin -markerpath /opt/SqueezeMeta-1.5.2/db/marker.hmm

```bash
MaxBin 2.2.6
Thread: 30
Input contig: /srv/data/my_shared_data_folder/amrcattle/metagenome_analysis_results/mgm4754670.3/temp/bincontigs.fasta
out header: /srv/data/my_shared_data_folder/amrcattle/metagenome_analysis_results/mgm4754670.3/intermediate/binners/maxbin/maxbin
Located abundance file [/srv/data/my_shared_data_folder/amrcattle/metagenome_analysis_results/mgm4754670.3/intermediate/binners/maxbin/mgm4754670.3.abund]
Searching against 107 marker genes to find starting seed contigs for [/srv/data/my_shared_data_folder/amrcattle/metagenome_analysis_results/mgm4754670.3/temp/bincontigs.fasta]...
Try harder to dig out marker genes from contigs.
Marker gene search reveals that the dataset cannot be binned (the medium of marker gene number <= 1). Program stop.

```

**Comment by fpusan** [comment]
Funny enough @jtamames was the one that report this issue in the MaxBin repo...
https://sourceforge.net/p/maxbin2/tickets/6/
What happens if you add `-min_contig_length 200` to the command above?

**Comment by EorgeKit** [comment]
Modified the code to include the option
```bash
#!/usr/bin/env bash

perl /opt/SqueezeMeta-1.5.2/bin/MaxBin/run_MaxBin.pl -thread 30 -contig /srv/data/my_shared_data_folder/\
amrcattle/metagenome_analysis_results/mgm4754670.3/temp/bincontigs.fasta -min_contig_length 200 \
-abund_list /srv/data/my_shared_data_folder/\
amrcattle/metagenome_analysis_results/mgm4754670.3/intermediate/binners/maxbin/abund.list \
-out /srv/data/my_shared_data_folder/amrcattle/metagenome_analysis_results\
/mgm4754670.3/intermediate/binners/maxbin/maxbin \
-markerpath /opt/SqueezeMeta-1.5.2/db/marker.hmm
```
The output was still the same
```bash
MaxBin 2.2.6
Thread: 30
Input contig: /srv/data/my_shared_data_folder/amrcattle/metagenome_analysis_results/mgm4754670.3/temp/bincontigs.fasta
Min contig length: 200
out header: /srv/data/my_shared_data_folder/amrcattle/metagenome_analysis_results/mgm4754670.3/intermediate/binners/maxbin/maxbin
Located abundance file [/srv/data/my_shared_data_folder/amrcattle/metagenome_analysis_results/mgm4754670.3/intermediate/binners/maxbin/mgm4754670.3.abund]
Searching against 107 marker genes to find starting seed contigs for [/srv/data/my_shared_data_folder/amrcattle/metagenome_analysis_results/mgm4754670.3/temp/bincontigs.fasta]...
Try harder to dig out marker genes from contigs.
Marker gene search reveals that the dataset cannot be binned (the medium of marker gene number <= 1). Program stop.
```

**Comment by jtamames** [comment]
Hello
Why don't you use concoct instead of maxbin? It is included since version 1.5. Just edit the SqueezeMeta_conf.pl file, and change the binners to ""metabat2,concoct". The restart from step 14.
Best,
J

**Comment by EorgeKit** [comment]
Is it okay if I use the -binners option instead ?

**Comment by jtamames** [comment]
Of course. But that works when you run a new SqueezeMeta. I suggested the solution above in case you want to use the run that you already did.
Best,
J

**Comment by EorgeKit** [comment]
by the way does squeezemeta operate with python3?

**Comment by EorgeKit** [comment]
[ke_analysis2_out.log](https://github.com/jtamames/SqueezeMeta/files/9632413/ke_analysis2_out.log)

The above file is the nohup output for the analysis I rerun yesterday, I renamed it .log extension because github does not allow .out extension but its still a nohup file.

The code i ran was:
[prepocessing_sq_sh.txt](https://github.com/jtamames/SqueezeMeta/files/9632439/prepocessing_sq_sh.txt)
