### ISSUE TITLE
install error squeezemeta-1.1.0-pl526r36_0 requires perl-dbd-mysql

### ISSUE THREAD

**Issue by luozhy88** [jtamames/SqueezeMeta#550]
<img width="876" alt="image" src="https://user-images.githubusercontent.com/94740863/192136091-f30a1a08-0e41-48e1-969f-87b417be9dc1.png">

**Comment by fpusan** [comment]
Duplicate of #551

**Comment by luozhy88** [comment]
great ! solved  it !
