### ISSUE TITLE
Why didn't this tool remove the genomic information of the host, such as human or mouse?

### ISSUE THREAD

**Issue by luozhy88** [jtamames/SqueezeMeta#552]
1 Why didn't this tool remove the genomic information of the host, such as human or mouse?
2 Why didn't this tool remove  common contaminant ?

**Comment by fpusan** [comment]
1) Because you didn't ask it to. See the manual of v1.6 (option `--filter` in `sqm_mapper.pl`) to see how it's done.
2) You can preprocess your reads with `sqm_mapper.pl` to remove host reads and whatever else you think would be a "common contaminant".  We don't do this by default, since the definition of "common contaminant" is context and researcher-dependent.

**Comment by luozhy88** [comment]
if I want to remove genome about human,the genome is [Homo_sapiens.GRCh38.dna_rm.primary_assembly.fa.gz](http://ftp.ensembl.org/pub/release-107/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna_rm.primary_assembly.fa.gz) and gff is http://ftp.ensembl.org/pub/release-107/regulation/homo_sapiens/homo_sapiens.GRCh38.Regulatory_Build.regulatory_features.20220201.gff.gz , is right?

**Comment by luozhy88** [comment]
if I want to remove "common contaminant" ,it is not gff file. But sqm_mapper.pl require a gff. How can I solve?

**Comment by fpusan** [comment]
You need to define what you want to consider "common contaminants" in the scope of your study, and prepare the files for those yourself. We can not help with that.

**Comment by luozhy88** [comment]
How  can use sqm_annot.pl? can you give an example?
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/94740863/192151146-3bd2a9b3-a79e-42d8-b13e-89bcb944662e.png">

**Comment by jtamames** [comment]
Please read the manual. All your questions can find a solution there.

**Comment by luozhy88** [comment]
I need to host 2 samples by sqm_mapper.pl, but the output is always a filtered sample for fq. Why?
![image](https://user-images.githubusercontent.com/94740863/192244928-322e15a3-6134-451c-aae0-8e3ee1201896.png)

![image](https://user-images.githubusercontent.com/94740863/192244595-00ecaa88-06bc-486e-b057-d6cf5dd2f9ad.png)
![image](https://user-images.githubusercontent.com/94740863/192244634-27756a2f-0520-4e4a-bd6a-afb5045f3d54.png)
![image](https://user-images.githubusercontent.com/94740863/192244731-b234b0e0-0e1f-4771-b588-36f085d06f5b.png)

**Comment by jtamames** [comment]
Could you please include the syslog file?

**Comment by jtamames** [comment]
Anyway, I think I got it. 
Change line 267, reading:
`if($filter) { filter($thissample,$outsam,$outdir,$pairs{$thissample}{pair1},$pairs{$thissample}{pair2}); exit; } `
by:
`if($filter) { filter($thissample,$outsam,$outdir,$pairs{$thissample}{pair1},$pairs{$thissample}{pair2}); next; } `
And run the script again

**Comment by luozhy88** [comment]
I am testing again.
