### ISSUE TITLE
DAS tool issue (SqueezeMeta v1.5)

### ISSUE THREAD

**Issue by pedres** [jtamames/SqueezeMeta#554]
Hi, I have finished a full run of SqueezeMeta pipeline using three binners (-binners metabat2,maxbin,concoct), and when I check the method file I saw that apparently only metabat2 and maxbin2 were used:

Binning was done using Metabat2 (Kang et al 2019, PeerJ 7, e7359)
Binning was done using MaxBin2 (Wu et al 2016, Bioinformatics 32(4), 605-7)
Combination of binning results was done using DAS Tool (Sieber et al 2018, Nat Microbiol 3(7), 836-43)

After checking the syslog I saw that the pipeline also run concoct. Also, I have revised the script 15 to see how DAS tool "works" and I think that it searchs for binners in the folder binners within the intermediate folder. In my project this folder has folder for the three binners, however the concoct folder only have a coverage_table.tsv file (there are not any fasta file). Maybe there was a problem while running concoct, or the problem was with DAS tool?

Thank you very much for your help,

Manuel

RUNNING concoct
  Creating /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/intermediate/binners/concoct directory
  Working for vermi_MAGs_binners.CT21_C.sam
  Creating sorted BAM for vermi_MAGs_binners.CT21_C.sam: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/lib /mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/bin/samtools sort /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/data/sam/vermi_MAGs_binners.CT21_C.sam -o /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/temp/vermi_MAGs_binners.CT21_C.sorted.bam -@128 > /dev/null 2>&1
  Indexing sorted BAM: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/lib /mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/bin/samtools index /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/temp/vermi_MAGs_binners.CT21_C.sorted.bam > /dev/null 2>&1
  Working for vermi_MAGs_binners.EW21_B.sam
  Creating sorted BAM for vermi_MAGs_binners.EW21_B.sam: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/lib /mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/bin/samtools sort /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/data/sam/vermi_MAGs_binners.EW21_B.sam -o /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/temp/vermi_MAGs_binners.EW21_B.sorted.bam -@128 > /dev/null 2>&1
  Indexing sorted BAM: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/lib /mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/bin/samtools index /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/temp/vermi_MAGs_binners.EW21_B.sorted.bam > /dev/null 2>&1
  Working for vermi_MAGs_binners.CT63_C.sam
  Creating sorted BAM for vermi_MAGs_binners.CT63_C.sam: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/lib /mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/bin/samtools sort /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/data/sam/vermi_MAGs_binners.CT63_C.sam -o /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/temp/vermi_MAGs_binners.CT63_C.sorted.bam -@128 > /dev/null 2>&1
  Indexing sorted BAM: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/lib /mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/bin/samtools index /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/temp/vermi_MAGs_binners.CT63_C.sorted.bam > /dev/null 2>&1
  Working for vermi_MAGs_binners.CT63_A.sam
  Creating sorted BAM for vermi_MAGs_binners.CT63_A.sam: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/lib /mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/bin/samtools sort /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/data/sam/vermi_MAGs_binners.CT63_A.sam -o /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/temp/vermi_MAGs_binners.CT63_A.sorted.bam -@128 > /dev/null 2>&1
  Indexing sorted BAM: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/lib /mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/bin/samtools index /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/temp/vermi_MAGs_binners.CT63_A.sorted.bam > /dev/null 2>&1
  Working for vermi_MAGs_binners.EW21_C.sam
  Creating sorted BAM for vermi_MAGs_binners.EW21_C.sam: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/lib /mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/bin/samtools sort /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/data/sam/vermi_MAGs_binners.EW21_C.sam -o /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/temp/vermi_MAGs_binners.EW21_C.sorted.bam -@128 > /dev/null 2>&1
  Indexing sorted BAM: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/lib /mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/bin/samtools index /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/temp/vermi_MAGs_binners.EW21_C.sorted.bam > /dev/null 2>&1
  Working for vermi_MAGs_binners.EW63_B.sam
  Creating sorted BAM for vermi_MAGs_binners.EW63_B.sam: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/lib /mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/bin/samtools sort /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/data/sam/vermi_MAGs_binners.EW63_B.sam -o /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/temp/vermi_MAGs_binners.EW63_B.sorted.bam -@128 > /dev/null 2>&1
  Indexing sorted BAM: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/lib /mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/bin/samtools index /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/temp/vermi_MAGs_binners.EW63_B.sorted.bam > /dev/null 2>&1
  Working for vermi_MAGs_binners.EW63_C.sam
  Creating sorted BAM for vermi_MAGs_binners.EW63_C.sam: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/lib /mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/bin/samtools sort /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/data/sam/vermi_MAGs_binners.EW63_C.sam -o /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/temp/vermi_MAGs_binners.EW63_C.sorted.bam -@128 > /dev/null 2>&1
  Indexing sorted BAM: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/lib /mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/bin/samtools index /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/temp/vermi_MAGs_binners.EW63_C.sorted.bam > /dev/null 2>&1
  Working for vermi_MAGs_binners.EW21_A.sam
  Creating sorted BAM for vermi_MAGs_binners.EW21_A.sam: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/lib /mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/bin/samtools sort /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/data/sam/vermi_MAGs_binners.EW21_A.sam -o /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/temp/vermi_MAGs_binners.EW21_A.sorted.bam -@128 > /dev/null 2>&1
  Indexing sorted BAM: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/lib /mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/bin/samtools index /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/temp/vermi_MAGs_binners.EW21_A.sorted.bam > /dev/null 2>&1
  Working for vermi_MAGs_binners.EW63_A.sam
  Creating sorted BAM for vermi_MAGs_binners.EW63_A.sam: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/lib /mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/bin/samtools sort /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/data/sam/vermi_MAGs_binners.EW63_A.sam -o /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/temp/vermi_MAGs_binners.EW63_A.sorted.bam -@128 > /dev/null 2>&1
  Indexing sorted BAM: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/lib /mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/bin/samtools index /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/temp/vermi_MAGs_binners.EW63_A.sorted.bam > /dev/null 2>&1
  Working for vermi_MAGs_binners.CT63_B.sam
  Creating sorted BAM for vermi_MAGs_binners.CT63_B.sam: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/lib /mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/bin/samtools sort /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/data/sam/vermi_MAGs_binners.CT63_B.sam -o /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/temp/vermi_MAGs_binners.CT63_B.sorted.bam -@128 > /dev/null 2>&1
  Indexing sorted BAM: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/lib /mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/bin/samtools index /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/temp/vermi_MAGs_binners.CT63_B.sorted.bam > /dev/null 2>&1
  Working for vermi_MAGs_binners.CT21_A.sam
  Creating sorted BAM for vermi_MAGs_binners.CT21_A.sam: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/lib /mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/bin/samtools sort /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/data/sam/vermi_MAGs_binners.CT21_A.sam -o /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/temp/vermi_MAGs_binners.CT21_A.sorted.bam -@128 > /dev/null 2>&1
  Indexing sorted BAM: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/lib /mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/bin/samtools index /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/temp/vermi_MAGs_binners.CT21_A.sorted.bam > /dev/null 2>&1
  Working for vermi_MAGs_binners.CT21_B.sam
  Creating sorted BAM for vermi_MAGs_binners.CT21_B.sam: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/lib /mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/bin/samtools sort /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/data/sam/vermi_MAGs_binners.CT21_B.sam -o /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/temp/vermi_MAGs_binners.CT21_B.sorted.bam -@128 > /dev/null 2>&1
  Indexing sorted BAM: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/lib /mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/bin/samtools index /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/temp/vermi_MAGs_binners.CT21_B.sorted.bam > /dev/null 2>&1

  Cutting contigs in pieces!: python3 /mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/bin/CONCOCT-1.1.0/scripts/cut_up_fasta.py /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/results/01.vermi_MAGs_binners.fasta -c 10000 -o 0 --merge_last -b /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/temp/vermi_MAGs_binners.contigs.bed > /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/temp/vermi_MAGs_binners.choppedcontigs.fasta
  Creating abundance table: PATH=/mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/bin:$PATH python3 /mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/bin/CONCOCT-1.1.0/scripts/concoct_coverage_table.py /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/temp/vermi_MAGs_binners.contigs.bed /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/temp/*.sorted.bam > /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/intermediate/binners/concoct/coverage_table.tsv
  Running concoct: OMP_THREAD_LIMIT=128 python3 /mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/bin/CONCOCT-1.1.0/bin/concoct --composition_file /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/temp/vermi_MAGs_binners.choppedcontigs.fasta --coverage_file /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/intermediate/binners/concoct/coverage_table.tsv --threads 128 -m 2500 -b /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/intermediate/binners/concoct/concoct_int/ > /dev/null 2>&1
  Merging clusters: /mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/bin/CONCOCT-1.1.0/scripts/merge_cutup_clustering.py /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/intermediate/binners/concoct/concoct_int/clustering_gt1000.csv > /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/intermediate/binners/concoct/concoct_int/clustering_merged.csv
  Extracting final bins: python3 /mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/bin/CONCOCT-1.1.0/scripts/extract_fasta_bins.py /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/results/01.vermi_MAGs_binners.fasta /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/intermediate/binners/concoct/concoct_int/clustering_merged.csv --output_path /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/intermediate/binners/concoct > /dev/null 2>&1

**Comment by fpusan** [comment]
What happens if you just run
```
OMP_THREAD_LIMIT=128 python3 /mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/bin/CONCOCT-1.1.0/bin/concoct --composition_file /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/temp/vermi_MAGs_binners.choppedcontigs.fasta --coverage_file /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/intermediate/binners/concoct/coverage_table.tsv --threads 128 -m 2500 -b /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/intermediate/binners/concoct/concoct_int/ 
```
?

**Comment by jtamames** [comment]
Hello
Which version are you using? Any chance that you are mixing versions (like re-running an older project with a new version of Squeezemeta)?

**Comment by pedres** [comment]
> What happens if you just run
> 
> ```
> OMP_THREAD_LIMIT=128 python3 /mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/bin/CONCOCT-1.1.0/bin/concoct --composition_file /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/temp/vermi_MAGs_binners.choppedcontigs.fasta --coverage_file /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/intermediate/binners/concoct/coverage_table.tsv --threads 128 -m 2500 -b /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/vermi_MAGs_binners/intermediate/binners/concoct/concoct_int/ 
> ```
> 
> ?

It gives: concoct: error: unrecognized arguments -m 2500
If a remove it gives:

![Captura de pantalla 2022-10-05 143145](https://user-images.githubusercontent.com/26455783/194060957-f658c445-c9b0-4351-865e-caf82b0bbcd5.png)

**Comment by pedres** [comment]
> Hello Which version are you using? Any chance that you are mixing versions (like re-running an older project with a new version of Squeezemeta)?

I am running version 1.5.1. It was a fresh run with only one restart from step 14.

**Comment by fpusan** [comment]
Not necessarily, this is a different bug that was fixed in v1.6.0.
Can you update to v1.6.0 and re-run the project?

**Comment by pedres** [comment]
Hi, I am running version 1.5.1.

It was a "fresh" run. I had to do only a restart , which started from step 14

**Comment by fpusan** [comment]
> I will try it later because in the server that error does not appear when using loadSQM. By now I have run sqm2tables.py and then loadSQMlite pointing to tables directory works without problems.

Yeah, the bug we fixed in 1.6.0 seemed to happen randomly. Anyways, even if the project is loading be aware that you likely don't have the bins from CONCOCT (only those from metabat2 and maxbin)

**Comment by fpusan** [comment]
Sorry I let this slip. No, you don't need to download them again, just activate the new environment and then run
```
configure_nodb.pl /path/to/db
test_install.pl
```

**Comment by pedres** [comment]
> Sorry I let this slip. No, you don't need to download them again, just activate the new environment and then run
> 
> ```
> configure_nodb.pl /path/to/db
> test_install.pl
> ```

No problem, I did it in that way

Regards,

Manuel

**Comment by pedres** [comment]
Re: [jtamames/SqueezeMeta] DAS tool issue (SqueezeMeta v1.5) (Issue #554)




Con fecha miércoles, 26 de octubre de 2022, 13:03:29, escribió:





Sorry I let this slip. No, you don't need to download them again, just activate the new environment and then run
configure_nodb.pl /path/to/db
test_install.pl
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>



No problem. I did it in that way.

Regards,



--


 Manuel Aira
 Grupo Ecoloxía Animal
 Universidade de Vigo
 Spain
