### ISSUE TITLE
process stuck on merging step

### ISSUE THREAD

**Issue by jilldv** [jtamames/SqueezeMeta#556]
I am running 36 samples in seqmerge mode. I started the merging step about 2 weeks ago. But for the last 2 days the process seems stuck. I don't see a change in the syslog file or any other output files. When I check with htop I see one processor running (process state R) and one processor in sleeping state. Is it possible the process is stuck?

If the process is indeed stuck, is there a possibility to restart the merging from the last merging step (and thus not from the beginning again)?

This is the syslog file from the run
[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/9746256/syslog.zip)

**Comment by fpusan** [comment]
Sorry I let this slip. I am pretty sure that your dataset is just too large for minimus2 to process it in a reasonable time. The `merged` and `seqmerge` modes are good alternatives to `coassembly` for making small datasets work with low computational resources, but they really not scale well to larger datasets. So I'm afraid it's either trying a coassembly, or using the sequential mode...

**Comment by jilldv** [comment]
Thank you! 
I just have one more question regarding this. If I use the sequential mode can I merge all the results in R and make comparisons between samples? My concern is mainly if this is statistically ok to do?

**Comment by fpusan** [comment]
You can. See `combineSQMlite` in SQMtools.  You can load the projects with `loadSQM` or `loadSQMlite` (the second will use less memory, but it won't allow you to subset the data).

Combining different processes will difficult making comparisons at the gene/bin level (as the same gene/bin will have different names in different samples), but comparisons of taxonomic/functional aggregates (e.g. which functions are differentially abundant between two experimental groups?) should be fine.
