### ISSUE TITLE
Step 4 restart, looks for an nonexistent directory

### ISSUE THREAD

**Issue by DanCWB** [jtamames/SqueezeMeta#557]
[syslog.txt](https://github.com/jtamames/SqueezeMeta/files/9746680/syslog.txt)

Hello,
My step 4 finished abnormally, in trying to restart the project using 
SqueezeMeta.pl -p Project --lowmem --restart
It finds that Step 1 to 3 have been completed, but then won't start step 4 because it's looking for Project/Project.
Thank you for any help you can provide
![Untitled](https://user-images.githubusercontent.com/115481243/194888125-06730011-431e-483b-9d6e-be5d67c9b842.jpg)

**Comment by jtamames** [comment]
Hello
Move to the upper directory and try again

**Comment by DanCWB** [comment]
![P2](https://user-images.githubusercontent.com/115481243/194893335-82b464ae-7ce8-4f82-b8ab-d38df0d70ef4.jpg)

The same issue occurs.

**Comment by jtamames** [comment]
In line 236, try changing:
`$projectdir = abs_path($projectdir);`
by 
`if(!$restart) { $projectdir = abs_path($projectdir); }`
and try again from the upper directory

**Comment by DanCWB** [comment]
Did I do this correctly? If I did, it's still causing the same issue.

![P4](https://user-images.githubusercontent.com/115481243/194902632-d3ef7559-a154-4bab-85ff-c9afa287e767.jpg)

**Comment by DanCWB** [comment]
Hi,
I wanted to add that I setup SqueezeMeta on a different machine and still encountered the same issue.
The fix in #559 fixes my issue for running diamond, but then when I want to restart the project it can't detect that step 4 is finished due to the same directory issue.

**Comment by jtamames** [comment]
Sorry for my delay on this, we are currently facing a lot of work and cannot respond as quickly as we would like. But rest assured that we will respond all issues as soon as we can
Best,
J

**Comment by fpusan** [comment]
Hi @DanCWB 
Could you share the `A6_Sed/SqueezeMeta_conf.pl` with us?
Also, in case you still have it, the line you used for calling SqueezeMeta in the first place? (not the restart, but the first time you created the project).
Best,
Fernando

**Comment by DanCWB** [comment]
Hi Fernando,

I've found that it's very easy to recreate by starting a run in -m sequential and then have it be interrupted and then try to restart using SqueezeMeta.pl -p (folder name of project) --restart

A work around is to call each step by their name, so **not** SqueezeMeta.pl -p (foldername of project) --restart -step (number)
but instead 

04.rundiamond.pl and then running 05, 06 and so forth.

Using that workaround I've moved on from A6_Sed, however I can share with you another dataset that has the same issue?

The original call for this would have been this:
SqueezeMeta.pl -m sequential --lowmem -s /media/wcvmmycowork/easystore/Master/A7Sed.samples -f /media/wcvmmycowork/easystore/PCRFreeSequencingWaterbowlsamplesAB/

and below the conf file.
[SqueezeMeta_conf.txt](https://github.com/jtamames/SqueezeMeta/files/9900762/SqueezeMeta_conf.txt)

I think the issue is that the restart function is setup to look for the directories as if it was run in coassembly, however the directories generated in sequential mode are of course different.

**Comment by fpusan** [comment]
> A work around is to call each step by their name, so not SqueezeMeta.pl -p (foldername of project) --restart -step (number)

Ah, so this was a sequential project! Then I am a bit less surprised. I think that for a sequential each of the subprojects would need to be restarted individually. There is no way to restart all of them with a single command.

**Comment by DanCWB** [comment]
Yes, I'm not trying to restart all of them with a single command, I'm just trying to restart one.

**Comment by fpusan** [comment]
Ah, sorry. So the workaround happens when you explicitly request restart from a certain step, instead of letting SqueezeMeta.pl figure it out on its own?

**Comment by DanCWB** [comment]
No, sorry I was trying to point out that it also **does not** work when you add --step # to --restart 
The work around is calling each step by their name which is fairly cumbersome as it will only execute that script and then stop.
"04.rundiamond.pl and then running 05, 06 and so forth."

**Comment by fpusan** [comment]
I see that you call it with
`SqueezeMeta.pl -p ./ --restart`

Does the same problem happens if you go one directory below and call it with
`SqueezeMeta.pl -p A7_sed --restart`?

**Comment by DanCWB** [comment]
Yes that's right, the same issue occurs

**Comment by fpusan** [comment]
Can reproduce

**Comment by fpusan** [comment]
Ok, let's see if this works.
1) Edit `SqueezeMeta.pl` (locate it first with `which SqueezeMeta.pl`)
2) Near L318 there should be two lines close to one another:
   - `my $rootdir=$projectdir;`
   - And a bit below: `$projectdir="$rootdir/$thissample";`
3) Comment out both of them and try again

**Comment by DanCWB** [comment]
Hi Fernando,

Yes, this has fixed the issue.
Thank you for your help!
________________________________

**Comment by fpusan** [comment]
Glad to hear! I'll leave this open until we actually commit the fix to the repo
