### ISSUE TITLE
RNA counts

### ISSUE THREAD

**Issue by sakcham** [jtamames/SqueezeMeta#560]
Hi,

I am doing metatrascriptome analysis by aligning reads to the metagenome and counting. However, the function count tables for the RNA samples have very low TPM values, I am guessing cause 99% of the data is rRNA. Is there a way to find out what proportion of reads are non-rRNA?? Same for DNA counts as well, there it is not evident, but still need to be consistent! 
All this is so that I have a good normalization while comparing the data. Currently data looks lopsided. For instance DNA tpm for a gene is 300 and for RNA is 0.9, when the actual raw counts are ~1000 for both DNA and RNA.

If you can suggest something different that solves this issue, would be great help.

**Comment by fpusan** [comment]
This should do it
```
### Assuming your project is loaded into the `SQM` object
# Locate the contigs containing at least one rRNA gene
badContigs   = unique(SQM$orfs$table$`Contig ID`[SQM$orfs$table$Molecule=='rRNA'])
# Get the rest of the contigs
goodContigs = setdiff(rownames(SQM$contigs$table), badContigs)
# Use them to create a new object without rRNA genes and recalculate the tpms
goodSQM     = subsetContigs(SQM = goodContigs, rescale_tpm = T)
```

**Comment by sakcham** [comment]
It is not loaded as an SQM object! Any other way around??

What if there are genes on the same rRNA containing contig?

**Comment by fpusan** [comment]
Regarding the ways around, you could do the same thing manually, but of course then you would have to do the tpm recalculation yourself.
In this case the genes sharing contigs with rRNA genes would be removed from the analysis. Alternatively, you could generate a list of goodORFs
```
### Assuming your project is loaded into the `SQM` object
# Locate the ORFs containing at least one rRNA gene
badORFs   = unique(rownames(SQM$orfs$table)[SQM$orfs$table$Molecule=='rRNA'])
# Get the rest of the ORFs
goodORFs = setdiff(rownames(SQM$orfs$table), badORFs)
# Use them to create a new object without rRNA genes and recalculate the tpms
goodSQM     = subsetORFs(SQM, goodORFs, rescale_tpm = T)
```

**Comment by sakcham** [comment]
Okay! So i ran the codes. 283 bad orfs and 297532  good orfs. I guess I can take that hit xD. One last thing, from this new object, how can i get the rescaled raw/tpm/rpkm file?

**Comment by fpusan** [comment]
In order to get the scaled tpm file (eg for KEGG), just go
`exportTable(goodSQM$functions$KEGG$tpm), 'rescaled_tpm.tsv')`

**Comment by sakcham** [comment]
I dont think this method works very well. Just comparing first few results.. For DNA, TPM OF K00001 changed from 476 to 394, K00001 changed from 316 to 362. For RNA, the TPM changed from 0.3 to 2.8 and from .5 to 4.1. So while I see RNA improve, it has different effects on each KO! Is that reliable? Most likely due to exclusion of some data?

**Comment by sakcham** [comment]
Okay! No you were right! It works well! specially the ORF part. Removing the contigs is not such a good idea though. Removing the ORF resolves the issue considerably. I will close this issue for now!

Thanks, Sakcham
