### ISSUE TITLE
some tax is missing in 19.PJ1.contigtable

### ISSUE THREAD

**Issue by luozhy88** [jtamames/SqueezeMeta#562]
Hi,
When I finished the whole process, I found some problems. some tax is missing in 19.PJ1.contigtable,why?
<img width="1386" alt="image" src="https://user-images.githubusercontent.com/94740863/196330233-06f86433-74f4-4231-872d-86baa092f891.png">

**Comment by jtamames** [comment]
Because the contig could not be assigned to any taxa

**Comment by luozhy88** [comment]
Thanks, a protein will not be assigned to species level if it has no hits above 85% identity in SqueezeMetaManual. 
Can I understand that The protein is invalid and can be deleted in the downstream analysis?

**Comment by fpusan** [comment]
Normally we will treat those as "Unclassified", but not remove them from the analysis.
