### ISSUE TITLE
Some tax is incomplete.

### ISSUE THREAD

**Issue by luozhy88** [jtamames/SqueezeMeta#563]
Hi,
Some tax is incomplete in 19.PJ1.contigtable.
<img width="1371" alt="image" src="https://user-images.githubusercontent.com/94740863/196344368-eb365f9e-268e-4565-a614-1a4512f61e86.png">

**Comment by jtamames** [comment]
Please read the documentation regarding how SqueezeMeta does taxonomic assignments for contigs. You can find int in the manual.
