### ISSUE TITLE
Problems finding SQMtools v 0.7

### ISSUE THREAD

**Issue by mawwwa88** [jtamames/SqueezeMeta#564]
Hi!

I'm trying to analyse the SqueezeMeta results with SQMtools package and I was advised to use SQMtools v 0.7. Yet, I couldn't find this particular version. Could you please send the tar.gz file with it?

Thank you in advance for your kind help!

Best,
Mariia

**Comment by fpusan** [comment]
Sure!
it's in `Squeezemeta/lib/SQMtools`
https://github.com/jtamames/SqueezeMeta/archive/refs/tags/v1.5.2.tar.gz
