### ISSUE TITLE
the result of composition is poor in SqueezeMeta,why?

### ISSUE THREAD

**Issue by luozhy88** [jtamames/SqueezeMeta#566]
The composition about genus and species  is too small,why?
![image](https://user-images.githubusercontent.com/94740863/197663248-820eb69d-4dbe-4df6-8e22-3ac67cd00b8d.png)
![image](https://user-images.githubusercontent.com/94740863/197663271-b80368ed-28d3-406b-8284-7f4a24eac8ad.png)

**Comment by fpusan** [comment]
Hi,
This result is normal, as SqueezeMeta is very conservative when assigning taxonomies.
You can find an extensive discussion on this in #281, #172, #187, and refs therein.

**Comment by fpusan** [comment]
I am not sure how you made that plot, but I also suspect that many of the reads marked there as "Unclassified" could actually be classified at higher levels (e.g. family or order).

**Comment by luozhy88** [comment]
you are right! I would covert 19.PJ1.contigtable into taxnomy table.And I replaced "Unclassified"  with NA in taxnomy table. How to sovle the problem?
<img width="915" alt="image" src="https://user-images.githubusercontent.com/94740863/198044500-e222dbc3-4abe-40f2-8ca5-e8f7524a6c31.png">

**Comment by luozhy88** [comment]
I solved the problm.
<img width="731" alt="image" src="https://user-images.githubusercontent.com/94740863/198057498-47a36787-fbe9-4f9b-8ed0-36af8a04c055.png">

**Comment by fpusan** [comment]
Glad to hear! Closing issue
Note that all these things that you are doing manually would be handled automatically by SQMtools, you can find more info about it in the wiki
