### ISSUE TITLE
can not be able to install due to perl dependency clash

### ISSUE THREAD

**Issue by jahid10** [jtamames/SqueezeMeta#568]
Hi,
I was trying to install SqueezeMeta using conda. I ran the commands as directed by the installation documentation. However when I ran 

$ mamba create -n SqueezeMeta -c conda-forge -c bioconda -c fpusan squeezemeta

I get this error after it initiates pulling
![Screenshot from 2022-11-01 20-58-02](https://user-images.githubusercontent.com/65849689/199198112-3c26cacb-8651-41c7-8504-bf5f0ab877cc.png)

**Comment by fpusan** [comment]
Try
`mamba create -n SqueezeMeta -c conda-forge -c bioconda -c fpusan squeezemeta=1.6`
Hopefully that works
