### ISSUE TITLE
Stopping in STEP4 -> 04.rundiamond.pl. Program finished abnormally

### ISSUE THREAD

**Issue by jahid10** [jtamames/SqueezeMeta#569]
I was just testing the samples provided with the database.
I ran into this error.
![Screenshot from 2022-11-03 22-07-49](https://user-images.githubusercontent.com/65849689/199694302-789a0a5e-0b39-42ac-810e-e8a1831e61d3.png)

**Comment by jtamames** [comment]
Hello
Did you download the databases?
Best,
J

**Comment by fpusan** [comment]
What is the output of test_install.pl?

**Comment by jahid10** [comment]
> Hello Did you download the databases? Best, J

Yes, I have downloaded the databases

**Comment by jahid10** [comment]
> What is the output of test_install.pl?

Can you give a sample command for test_install.pl

**Comment by fpusan** [comment]
Literally just run `test_install.pl` :)

**Comment by jahid10** [comment]
![Screenshot from 2022-11-03 22-36-21](https://user-images.githubusercontent.com/65849689/199699883-72e23446-5ae3-42ef-9936-14dd45e57089.png)


> Literally just run `test_install.pl` :)
Hi, this is the result.

**Comment by jtamames** [comment]
Did you follow the installation instructions that we provide both in the github page and the manual?

**Comment by jahid10** [comment]
> Did you follow the installation instructions that we provide both in the github page and the manual?

Yes, I have followed instructions for installation however, I have used the command make_databases command only to build databases.

**Comment by fpusan** [comment]
Yeah, running `make_databases.pl` should have worked, but the nr download from NCBI probably got interrupted along the way. This has happened to us before. Try removing the corrupted database and running `download_databases.pl` instead.. .

**Comment by jahid10** [comment]
> Yeah, running `make_databases.pl` should have worked, but the nr download from NCBI probably got interrupted along the way. This has happened to us before. Try removing the corrupted database and running `download_databases.pl` instead.. .

Hi, thanks.
Is there a possibility that the problem in the step 4 is caused by corrupted nr database?

**Comment by fpusan** [comment]
Yes, that's what I think happened

**Comment by jahid10** [comment]
Thanks, download_databases.pl really worked instead of make_databases.pl
