### ISSUE TITLE
unable to load -euk -nobins project in SQMTools

### ISSUE THREAD

**Issue by RitaBogorad** [jtamames/SqueezeMeta#570]
Hey:)
I have some metatranscriptome sqm output that I ran using -euk and -nobins flags. I tried loading it as usual to R via SQMTools but it keeps complaining.
The first error I get is:

 File '/2018_metatrans_raw_fastq/results/20.2018_metatrans_raw_fastq.contigtable' does not exist or is non-readable

There is indeed no 20.2018_metatrans_raw_fastq.contigtable in the results folder but there is 19.2018_metatrans_raw_fastq.contigtable. 
As a test, I copy it as 20. instead of 19. and LoadSQM keeps loading further but stops due to this error:

Error in SQM$functions[[method]]$tpm["Unmapped", ] :  subscript out of bounds

I have seen this error in other issues but none of the solutions help. After each attempt, I generated a new set of tables so that should not be the issue (no errors pop up there).
I used SqeezeMeta 1.6.0 and SQMTools 0.6.2

I would appreciate hearing your opinion on what might be happening wrong here

Thanks in advance!

Rita

**Comment by fpusan** [comment]
Hi!
Your project was created with an old version of SqueezeMeta
Running `versionchange.pl /path/to/your/project` may help with this

**Comment by RitaBogorad** [comment]
Thank you for the quick response!
I ran the versionchange command and generated new tables right after. When loading the project in R, the .contigtable error is gone but the second one still pops up

Error in SQM$functions[[method]]$tpm["Unmapped", ] :  subscript out of bounds

**Comment by fpusan** [comment]
Ah, I now noticed that you are using SQMtools 0.6.2 with SqueezeMeta 1.6.0. They are incompatible.
You need to upgrade SQMtool to the latest version (1.6.0).
Then you also should run `19.getcontigs.pl /path/to/project`. Hopefully this will fix things.

**Comment by RitaBogorad** [comment]
Unfortunately, the error is not gone..
I have updated SQMTools to 1.6.0, ran 19.getcontigs.pl (it finished without errors) and generated new tables.
Still the same thing:
Error in SQM$functions[[method]]$tpm["Unmapped", ] : subscript out of bounds

If I delete 20.2018_metatrans_raw_fastq.contigtable (which is literally 19. duplicated because I have --nobins flag on) then I also get this error a bit earlier at LoadSQM:

Error in data.table::fread(sprintf("%s/results/20.%s.contigtable", project_path,  : 
  File 'path/2018_metatrans_raw_fastq//results/20.2018_metatrans_raw_fastq.contigtable' does not exist or is non-readable.

**Comment by fpusan** [comment]
You sure you are using the latest version of SQMtools? What version is stated when loading the package?
It should be trying `data.table::fread(sprintf('%s/results/19.%s.contigtable', project_path,` instead

**Comment by RitaBogorad** [comment]
Here is the snip from the console, getwd() shows my R working directory, it used to be another folder but I changed it into  the sqeezemeta project_path

![image](https://user-images.githubusercontent.com/61075944/200883091-c6aead8c-bc4a-49e4-b832-690583263267.png)

**Comment by fpusan** [comment]
Can you install SqueezeMeta 1.6 into a fresh environment and try loading the project there?

**Comment by fpusan** [comment]
```
# Assuming you are in the base conda environment
mamba create -c SQMtest -c conda-forge -c bioconda -c fpusan squeezemeta=1.6
conda activate SQMtest
R
library(SQMtools)
loadSQM("/path/to/your/project")
```

**Comment by fpusan** [comment]
Also try the following.
`R -e "library(SQMtools);loadSQM" | grep contigtable`
What is your output?
Mine is
```
    if (file.exists(sprintf("%s/results/20.%s.contigtable", project_path, 
        SQM$contigs$table = read.table(sprintf("%s/results/19.%s.contigtable", 
        SQM$contigs$table = data.table::fread(sprintf("%s/results/19.%s.contigtable", 
```

**Comment by RitaBogorad** [comment]
Uff, simply deleting the old environment and restarting the R session helped.. everything works now!
I should never underestimate the magic of turning it off and on again.....
Thanks a lot for the fix!

Rita
