### ISSUE TITLE
Restart keeps adding sample names at the end of contigs in merged mode?

### ISSUE THREAD

**Issue by fpusan** [jtamames/SqueezeMeta#571]
Thanks fpusan, I'll let you know.

Probably unrelated, but I've just noticed that restarting run of the same project keeps adding sample name to already assembled contigs:

`>k141_56693_R1M2RNA_R1M2RNA_R1M2RNA flag=1 multi=22.0000 len=471`

To be sure, I've restarted the whole pipeline.

_Originally posted by @florekem in https://github.com/jtamames/SqueezeMeta/issues/565#issuecomment-1291990318_

**Comment by jtamames** [comment]
Bug found and fixed, hopefully
