### ISSUE TITLE
SQMtools was installed, however, it doesn't work.

### ISSUE THREAD

**Issue by Yunliang81** [jtamames/SqueezeMeta#575]
Hi, 

Thank you very much for your contribution.

I installed the SQMtools following  https://github.com/jtamames/SqueezeMeta/wiki/Using-SQMtools-in-a-Windows-environment, however, it doesn't work. The followings are the details shown in R.

> install.packages("C:/Users/liyun/Downloads/SQMtools.zip",labrepos = NULL, type = "win.binary",dependencies = TRUE)
> library(SQMtools)
Error in library(SQMtools) : ‘SQMtools’ is not a valid installed package

Any ideas?

Thanks.

**Comment by fpusan** [comment]
Try the following:
1) Decompress the zip file
2) You should have a directory called SQMtools with a structure similar to [this](https://github.com/jtamames/SqueezeMeta/tree/master/lib/SQMtools)
3) Inside R, try `install.packages("C:/xxxx/yyy/zzz/SQMtools", repos = NULL, type = "source")`.
Let me know if this works!

**Comment by Yunliang81** [comment]
Hi,

Thank you very much for your suggestion, however, it still doesn't work.
Please see the followings:

> install.packages("D:/SQMTools",repos=NULL, type="source")
'\\cabinet.usask.ca\work$\yul713\My Documents'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
Warning: invalid package 'D:/SQMTools'
Error: ERROR: no packages specified
Warning in install.packages :
  installation of package ‘D:/SQMTools’ had non-zero exit status
> library(SQMtools)
Error in library(SQMtools) : ‘SQMtools’ is not a valid installed package


I was wondering whether library(doMC) and library(DASTool) are required
before the installation of SQMTools?

Thanks,
Yunliang



Fernando Puente-Sánchez ***@***.***> 于2022年11月7日周一 02:08写道：

**Comment by fpusan** [comment]
Thanks! I also updated the instruction in the wiki, to reflect this new method.
