### ISSUE TITLE
Error in loadSQM

### ISSUE THREAD

**Issue by astromecki** [jtamames/SqueezeMeta#577]
Hello,

First off, thank you for the excellent pipeline and documentation. I have run SqueezeMeta on my data and generated tabular outputs, and am now in the analysis phase.

I keep getting this error when trying to load my project into SQMtools in R:

```
> IRL_Moose_2013 = loadSQM('/data/amstromecki/Moose_MG_reads/116195/2013_reads/IRL_Moose_MG_2013/')
Loading total reads
Loading orfs
    table...
|--------------------------------------------------|
|==================================================|
    abundances...
    sequences
|--------------------------------------------------|
|==================================================|
    taxonomy...
|--------------------------------------------------|
|==================================================|
Loading contigs
    table...
    abundances...
Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent
```

Could you please advise?

Thank you!
Amanda

**Comment by astromecki** [comment]
Hi Fernando,

This worked great - I am now able to analyze my data in R. Thanks so much for your help and prompt reply!

All the best,
Amanda

**Comment by fpusan** [comment]
Glad to hear! Closing issue
