### ISSUE TITLE
error when trying sqm2itol.pl

### ISSUE THREAD

**Issue by nutrimol** [jtamames/SqueezeMeta#580]
Dear developers,

We are trying to run sqm2itol.pl to visualize the abundance of bins in our samples. 

We run SqueezeMeta v1.52 in a cluster using co-assembly mode of 6 samples (3 metagenomes and 3 metatranscriptomes). In this analysis, we used -extassembly flag option with the SqueezeMeta command to use a polished co-assembly generated from the same three metagenomes. The analysis included nobinning option for the metatranscriptomes in samples.samples file. 

Now, when we try to run sqm2itol.pl we get this error:

``` bash
sqm2itol.pl -completion 70 -contamination 10 pol_coassembly
Cwd.c: loadable library and perl binaries are mismatched (got handshake key 0xde00080, needed 0xcd00080)
```

It seems to be similar to the error reported in #219 , but I can see the sqm2itol.pl script and starts with 

```bash 
#!/usr/bin/env perl
```

I would very much appreciate some help!
Best regards and congratulations for such a wonderful tool !

Virginia

**Comment by nutrimol** [comment]
Thanks for the response. I will try that and come back to inform. 
Virginia.

**Comment by nutrimol** [comment]
Hello,
I am affraid that I am back with bad news.
I installed SqueezeMeta (1.6) in a new environment in the cluster following the recommended instructions:
``` bash
conda install -c conda-forge mamba
mamba create -n SQM -c conda-forge -c bioconda -c fpusan squeezemeta=1.6
conda activate SQM
```
Then, I linked the database to SqueezeMeta:
``` bash 
/mnt/netapp1/Store_CSIC/home/csic/nmy/vgc/.conda/envs/SQM/SqueezeMeta/utils/install_utils/configure_nodb.pl /mnt/lustre/scratch/nlsas/home/csic/nmy/vgc/squeezemetadb/db
```
Finally, I run the test
``` bash
test_install.pl
```

This is the output:

``` bash
Checking the OS
        linux OK

Checking that tree is installed
        tree --help OK

Checking that ruby is installed
        ruby -h OK

Checking that java is installed
        java -h OK

Checking that all the required perl libraries are available in this environment
        perl -e 'use Term::ANSIColor' OK
        perl -e 'use DBI' OK
        perl -e 'use DBD::SQLite::Constants' OK
        perl -e 'use Time::Seconds' OK
        perl -e 'use Tie::IxHash' OK
        perl -e 'use Linux::MemInfo' OK
        perl -e 'use Getopt::Long' OK
        perl -e 'use File::Basename' OK
        perl -e 'use DBD::SQLite' OK
        perl -e 'use Data::Dumper' OK
        perl -e 'use Cwd' OK
        perl -e 'use XML::LibXML' OK
        perl -e 'use XML::Parser' OK
        perl -e 'use Term::ANSIColor' OK

Checking that all the required python libraries are available in this environment
        python3 -h OK
        python3 -c 'import numpy' OK
        python3 -c 'import scipy' OK
        python3 -c 'import matplotlib' OK
        python3 -c 'import dendropy' OK
        python3 -c 'import pysam' OK
        python3 -c 'import Bio.Seq' OK
        python3 -c 'import pandas' OK
        python3 -c 'import sklearn' OK
        python3 -c 'import nose' OK
        python3 -c 'import cython' OK
        python3 -c 'import future' OK

Checking that all the required R libraries are available in this environment
        R -h OK
        R -e 'library(doMC)' OK
        R -e 'library(ggplot2)' OK
        R -e 'library(data.table)' OK
        R -e 'library(reshape2)' OK
        R -e 'library(pathview)' OK
        R -e 'library(DASTool)' OK
        R -e 'library(SQMtools)' OK

Checking that SqueezeMeta is properly configured... checking database in /mnt/lustre/scratch/nlsas/home/csic/nmy/vgc/squeezemetadb/db
        nr.db OK
        CheckM manifest OK
        LCA_tax DB OK

All checks successful
```
Celebrating at this point!!

Then, before any other execution, I tried the test analysis:
``` bash
SqueezeMeta.pl -m coassembly -p Hadza -s test.samples -f raw
```
The output is the same as above with sqm2itol.pl
``` bash
Cwd.c: loadable library and perl binaries are mismatched (got handshake key 0xde00080, needed 0xcd00080)
```

Now I am totally lost, please, any other suggestion would be apreciated!!

Thank you!!!
Virginia.

**Comment by fpusan** [comment]
Did you also perform a fresh installation of miniconda3?
If so, once the SqueezeMeta environment is activated, what is the output of `echo $PERL5LIB`?

**Comment by nutrimol** [comment]
miniconda3 is in a cluster module. The first thing I do is:
``` bash 
module load miniconda3
```
Then,  I activate my working environment.

Now,  in my old SqueezeMeta environment  I do ``echo $PERL5LIB`` , output:
``` bash
/mnt/netapp1/Store_CSIC/home/csic/nmy/vgc/.conda/envs/SqueezeMeta/lib/site_perl/5.26.2/:/mnt/netapp1/Store_CSIC/home/csic/nmy/vgc/.conda/envs/SqueezeMeta/lib/site_perl/5.26.2/x86_64-linux-thread-multi/:/mnt/netapp1/Store_CSIC/home/csic/nmy/vgc/.conda/envs/SqueezeMeta/lib/5.26.2/:/mnt/netapp1/Store_CSIC/home/csic/nmy/vgc/.conda/envs/SqueezeMeta/lib/5.26.2/x86_64-linux-thread-multi/:/home/csic/nmy/vgc/perl5/lib/perl5
```
and when I do the same thing in the new SQM environment I get: 
``` bash
/mnt/netapp1/Store_CSIC/home/csic/nmy/vgc/.conda/envs/SQM/lib/site_perl/5.26.2/:/mnt/netapp1/Store_CSIC/home/csic/nmy/vgc/.conda/envs/SQM/lib/site_perl/5.26.2/x86_64-linux-thread-multi/:/mnt/netapp1/Store_CSIC/home/csic/nmy/vgc/.conda/envs/SQM/lib/5.26.2/:/mnt/netapp1/Store_CSIC/home/csic/nmy/vgc/.conda/envs/SQM/lib/5.26.2/x86_64-linux-thread-multi/:/home/csic/nmy/vgc/perl5/lib/perl5
```
I do not know if I am allowed to perform a fresh installation of miniconda3. Would it be possible in the cluster? 
Thank you for your time!
Virginia

**Comment by fpusan** [comment]
Does this maybe fix it?
`mamba install -c bioconda perl-pathtools`

**Comment by nutrimol** [comment]
Just did it with the SQM environment activated
Same error when running test and same echo $PERL5LIB output

**Comment by fpusan** [comment]
What about `which perl`?

**Comment by nutrimol** [comment]
``which perl``
/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/bin/perl

**Comment by nutrimol** [comment]
Yes! solved that error !!
``SqueezeMeta.pl -m coassembly -p Hadza -s test.samples -f raw`` is now running

``sqm2itol.pl -completion 70 -contamination 10 pol_coassembly`` did not return the previous error.

However, the output:

Reading bins in /mnt/lustre/scratch/nlsas/home/csic/nmy/vgc/dataANDanalysis/analysis/co-assemblies/best3_coa/pol_coassembly/results/18.pol_coassembly.bintable...
Found  bins
Working with  bins with more than 70% completion and less than 10% contamination
Using RPKM values
Reading functions in /mnt/lustre/scratch/nlsas/home/csic/nmy/vgc/dataANDanalysis/analysis/co-assemblies/best3_coa/pol_coassembly/results/21.pol_coassembly.metacyc.pathways
Died at /mnt/netapp1/Store_CSIC/home/csic/nmy/vgc/.conda/envs/SqueezeMeta/bin/sqm2itol.pl line 147.

I tried to understand what is the script doing at that line and it seems it looks for "21.$project.$funclass.pathways" file in /results, am I wrong? but in my /results folder I only have these:
├──  01.pol_coassembly.fasta
├─  02.pol_coassembly.16S.txt
├── 02.pol_coassembly.rnas
├── 02.pol_coassembly.trnas
├── 02.pol_coassembly.trnas.fasta
├── 03.pol_coassembly.faa
├── 03.pol_coassembly.fna
├── 03.pol_coassembly.gff
├── 06.pol_coassembly.fun3.tax.noidfilter.wranks
├── 06.pol_coassembly.fun3.tax.wranks
├── 07.pol_coassembly.fun3.CaiGbu
├── 07.pol_coassembly.fun3.cog
├── 07.pol_coassembly.fun3.kegg
├── 07.pol_coassembly.fun3.pfam
├── 10.pol_coassembly.mappingstat
├── 11.pol_coassembly.mcount
├── 12.pol_coassembly.CaiGbu.funcover
├── 12.pol_coassembly.cog.funcover
├── 12.pol_coassembly.kegg.funcover
├── 13.pol_coassembly.orftable
├── 18.pol_coassembly.bintable
├── 19.pol_coassembly.contigtable
├── 20.pol_coassembly.kegg.pathways
├── 20.pol_coassembly.metacyc.pathways
├── 21.pol_coassembly.stats
├── bins
└── tables

Could this error be more related with my project?

Thank you for your patience,
Virginia

**Comment by jtamames** [comment]
Yep. I forsot to update file names in the last version. Follow #573 to fix it

**Comment by nutrimol** [comment]
Yes! thank you so much! You are doing a great job keeping this tool alive and active !!!
