### ISSUE TITLE
04.rundiamond.pl. Program finished abnormally

### ISSUE THREAD

**Issue by sawannee** [jtamames/SqueezeMeta#581]
I got an error in step 4. The error is "unexpected end of input". I checked the input file (.faa) already. There is nothing wrong in this file. Could anyone help suggest me? 

This is the command I use: 
Error running command:    /home/sawannee/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/diamond blastp -q /home/sawannee/02.SQM_result/HS01/results/03.HS01.faa -p 8 -d /home/sawannee/nr_db/db/nr.dmnd -e 0.001 --id 40 -f tab -b 1 --quiet -o /home/sawannee/02.SQM_result/HS01/intermediate/04.HS01.nr.diamond at /home/sawannee/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/04.rundiamond.pl line 72.
[31mStopping in STEP4 -> 04.rundiamond.pl. Program finished abnormally
[0m[31m
  If you don't know what went wrong or want further advice, please look for similar issues in https://github.com/jtamames/SqueezeMeta/issues
  Feel free to open a new issue if you don't find the answer there. Please add a brief description of the problem and upload the /home/sawannee/02.SQM_result/HS01/syslog file (zip it first)
[0mDied at /home/sawannee/miniconda3/envs/SqueezeMeta/bin/SqueezeMeta.pl line 1381.
Error: Unexpected end of input.

**Comment by fpusan** [comment]
That's a new one. No useful info about it in the DIAMOND repo either...
Any chance you ran out of disk space either in your main partition or in `/tmp`?

**Comment by sawannee** [comment]
> 

Thank you for your recommendation. I'll try increasing my space first.

**Comment by sawannee** [comment]
![Screen Shot 2565-11-12 at 11 03 52](https://user-images.githubusercontent.com/77879276/201456257-5ce5717e-9691-4830-9ab1-f99fce2d63c9.png)
I tried to run the command of the diamond directly (same as in the pipeline). I got that the error happen in the step of loading the reference sequence.

**Comment by fpusan** [comment]
Thanks for pinning it down! Did you use `make_databases.pl`? If so, try using `download_databases.pl` instead

**Comment by sawannee** [comment]
Thank you for your suggestion. I'll remove the old database, and use only download_database.pl instead.

**Comment by sawannee** [comment]
Finally, it's work. Thank you very much.
