### ISSUE TITLE
Error occurred in the step of 06.lca.pl

### ISSUE THREAD

**Issue by sawannee** [jtamames/SqueezeMeta#582]
I run "sequential mode" using the following command: 

SqueezeMeta.pl -m sequential -s sample_file.txt -t 8 -f ../00.rawdata

and I got that the program was abnormally terminated at the step of 06.lca.pl. The error is shown in the figure below. How should I solve the problem? Thank you very much in advance.    

![Screen Shot 2565-11-14 at 12 29 26](https://user-images.githubusercontent.com/77879276/201582759-8ce4bf6e-8d02-4448-b44d-07d115e2b6a0.png)

(P.S. I already used download_database.pl instead of make_databse.pl).

**Comment by sawannee** [comment]
I found that my LCA_tax is not complete, but I don't know how to solve it. Could you please tell me? 

![Screen Shot 2565-11-14 at 12 50 01](https://user-images.githubusercontent.com/77879276/201585097-b4ba46bb-57e5-436c-a571-e01df9e4015e.png)

**Comment by jtamames** [comment]
This is probably related with the database problems that you had when running the step 04. Apparently the database was not properly downloaded or configured. I assume you did `configure_nodb.pl` when installing the database? If so, you should download it again.
Best,
J

**Comment by sawannee** [comment]
Hi Developer, 

I run download_databases.pl again, but I found that the LCA_tax folder was still empty with parents.db and taxid.md5. Do you think it is due to the space of the HDD? 

![Screen Shot 2565-11-17 at 21 12 43](https://user-images.githubusercontent.com/77879276/202637976-74edd4de-3a8c-4cdb-abeb-836fa594bc17.png)

**Comment by fpusan** [comment]
This is a possibility, yes. How much free space do you have?
