### ISSUE TITLE
Stopping in STEP1 -> 01.run_all_assemblies.pl. Program finished abnormally

### ISSUE THREAD

**Issue by jahid10** [jtamames/SqueezeMeta#583]
Hi, I was running squeezemeta.pl in coassembly mode when I hit this error.
[0 seconds]: STEP1 -> RUNNING ASSEMBLY: 01.run_all_assemblies.pl (megahit)
  Concatenating all samples:  SRW_D_0_1.fastq.gz  SRW_D_0_1.fastq.gz  SRW_D_10_1.fastq.gz  SRW_D_10_2.fastq.gz  SRW_D_16_1.fastq.gz  SRW_D_16_2.fastq.gz  SRW_D_5_1.fastq.gz  SRW_D_5_2.fastq.gz 
    pair1: cat /media/bioinfo/Hilsa/Jahid_NGS_metagenomics/rajbari_water_retting/SRW_D_0_1.fastq.gz /media/bioinfo/Hilsa/Jahid_NGS_metagenomics/rajbari_water_retting/SRW_D_10_1.fastq.gz /media/bioinfo/Hilsa/Jahid_NGS_metagenomics/rajbari_water_retting/SRW_D_16_1.fastq.gz /media/bioinfo/Hilsa/Jahid_NGS_metagenomics/rajbari_water_retting/SRW_D_5_1.fastq.gz > /media/bioinfo/Hilsa/Jahid_NGS_metagenomics/rrw_result/data/raw_fastq/par1.fastq.gz
    pair2: cat /media/bioinfo/Hilsa/Jahid_NGS_metagenomics/rajbari_water_retting/SRW_D_0_1.fastq.gz /media/bioinfo/Hilsa/Jahid_NGS_metagenomics/rajbari_water_retting/SRW_D_10_2.fastq.gz /media/bioinfo/Hilsa/Jahid_NGS_metagenomics/rajbari_water_retting/SRW_D_16_2.fastq.gz /media/bioinfo/Hilsa/Jahid_NGS_metagenomics/rajbari_water_retting/SRW_D_5_2.fastq.gz > /media/bioinfo/Hilsa/Jahid_NGS_metagenomics/rrw_result/data/raw_fastq/par2.fastq.gz
  Running assembly with megahit: perl /home/bioinfo/mambaforge/envs/SqueezeMeta/SqueezeMeta/lib/SqueezeMeta/assembly_megahit.pl /media/bioinfo/Hilsa/Jahid_NGS_metagenomics/rrw_result rrw_result /media/bioinfo/Hilsa/Jahid_NGS_metagenomics/rrw_result/data/raw_fastq/par1.fastq.gz /media/bioinfo/Hilsa/Jahid_NGS_metagenomics/rrw_result/data/raw_fastq/par2.fastq.gz
Error running command:    /home/bioinfo/mambaforge/envs/SqueezeMeta/SqueezeMeta/bin/megahit/megahit  -1 /media/bioinfo/Hilsa/Jahid_NGS_metagenomics/rrw_result/data/raw_fastq/par1.fastq.gz -2 /media/bioinfo/Hilsa/Jahid_NGS_metagenomics/rrw_result/data/raw_fastq/par2.fastq.gz -t 12 -o /media/bioinfo/Hilsa/Jahid_NGS_metagenomics/rrw_result/data/megahit >> /media/bioinfo/Hilsa/Jahid_NGS_metagenomics/rrw_result/syslog 2>&1 at /home/bioinfo/mambaforge/envs/SqueezeMeta/SqueezeMeta/lib/SqueezeMeta/assembly_megahit.pl line 36.
  Running prinseq (Schmieder et al 2011, Bioinformatics 27(6):863-4) for selecting contigs longer than 200 

ERROR: could not find input file "/media/bioinfo/Hilsa/Jahid_NGS_metagenomics/rrw_result/results/01.rrw_result.fasta".

Try 'perl prinseq-lite.pl -h' for more information.
Exit program.
Error running command:    /home/bioinfo/mambaforge/envs/SqueezeMeta/SqueezeMeta/bin/prinseq-lite.pl -fasta /media/bioinfo/Hilsa/Jahid_NGS_metagenomics/rrw_result/results/01.rrw_result.fasta -min_len 200 -out_good /media/bioinfo/Hilsa/Jahid_NGS_metagenomics/rrw_result/results/prinseq; mv /media/bioinfo/Hilsa/Jahid_NGS_metagenomics/rrw_result/results/prinseq.fasta /media/bioinfo/Hilsa/Jahid_NGS_metagenomics/rrw_result/results/01.rrw_result.fasta > /dev/null 2>&1 at /home/bioinfo/mambaforge/envs/SqueezeMeta/SqueezeMeta/scripts/01.run_all_assemblies.pl line 242.
Stopping in STEP1 -> 01.run_all_assemblies.pl. Program finished abnormally

**Comment by jtamames** [comment]
Hello
Please remember attaching the syslog file when you report an error, that will help us to identify the problem.
In this case, I think that you are using the file SRW_D_0_1.fastq.gz both as pair1 and pair2. Could you have a typo in your samples file?
Best,
J

**Comment by jahid10** [comment]
Yes, I'm sorry. It was my typo indeed.
