### ISSUE TITLE
01.run_assembly.pl. Program finished abnormally

### ISSUE THREAD

**Issue by jahid10** [jtamames/SqueezeMeta#592]
Run started Mon Nov 28 10:01:59 2022 in coassembly mode
Now creating directories
Reading configuration from /media/bioinfo/hdd1/Jahid_NGS_metagenomics/rajbari_control_result/SqueezeMeta_conf.pl
Reading samples from /media/bioinfo/hdd1/Jahid_NGS_metagenomics/rajbari_control_result/data/00.rajbari_control_result.samples
4 samples found: RC_d0 RC_d10 RC_d5 RC_d14

Now merging files
[8 minutes, 58 seconds]: STEP1 -> RUNNING CO-ASSEMBLY: 01.run_assembly.pl (megahit)
  Running assembly with megahit
Error running command:    /home/bioinfo/anaconda3/envs/SqueezeMeta/SqueezeMeta/bin/megahit/megahit  -1 /media/bioinfo/hdd1/Jahid_NGS_metagenomics/rajbari_control_result/data/raw_fastq/par1.fastq.gz -2 /media/bioinfo/hdd1/Jahid_NGS_metagenomics/rajbari_control_result/data/raw_fastq/par2.fastq.gz -t 12 -o /media/bioinfo/hdd1/Jahid_NGS_metagenomics/rajbari_control_result/data/megahit >> /media/bioinfo/hdd1/Jahid_NGS_metagenomics/rajbari_control_result/syslog 2>&1 at /home/bioinfo/anaconda3/envs/SqueezeMeta/SqueezeMeta/scripts/01.run_assembly.pl line 119.
Stopping in STEP1 -> 01.run_assembly.pl. Program finished abnormally
[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/10100692/syslog.zip)
[megahit-log.zip](https://github.com/jtamames/SqueezeMeta/files/10100693/megahit-log.zip)

Died at /home/bioinfo/anaconda3/envs/SqueezeMeta/bin/SqueezeMeta.pl line 1381.

**Comment by jtamames** [comment]
Hello
Please check your input files. Do both pairs have the same number of reads? 
Best,
J

**Comment by fconstancias** [comment]
I experienced the same issue which was due to mistake in the pair2 files in the sample_list leading to par2.fastq.gz beeing the same fastq.gz file concatenated several time. Running fastqc on the par*.fastq.gz and the input files helped to resolve the issue.
