### ISSUE TITLE
anvi-load-sqm.py: At least one gene call in your external genes file ('5660473') contains a start position smaller than 0

### ISSUE THREAD

**Issue by jahid10** [jtamames/SqueezeMeta#594]
Hi, I have run the anvi-load-sqm.py with the following command 
`python3 /home/bioinfo/mambaforge/envs/SqueezeMeta/SqueezeMeta/utils/anvio_utils/anvi-load-sqm.py -p /media/bioinfo/Hilsa/Jahid_NGS_metagenomics/rrw_analysis -o /media/bioinfo/Hilsa/Jahid_NGS_metagenomics/rrw_analysis/anvio --num-threads 12 --min-contig-length 2500 --run-scg-taxonomy --run-HMMS`

I found the following error.:
File/Path Error: At least one gene call in your external genes file ('5660473') contains a start
                 position smaller than 0. Anvi'o could extend your contigs with imaginary       
                 nucleotides to make things work. Admittedly it would have been much more fun to
                 do that instead of asking you to go back and correct your external gene calls  
                 file. But we are burdened to act as adults here :(

Please let me know where should I modify the file

**Comment by ggnatalia** [comment]
HI, sorry about the delay (I really did not have time until now to look at it). Could you tell me which version of SQM and anvio are you using? I'm pretty sure to have seen this problem before so I have an idea of what could be happening.

**Comment by jahid10** [comment]
Hello ggnatalia, 
It was a long time ago. My SqueezeMeta version is 1.5.1 and my Anvio version is 7.1. I have successfully used anvio-load-sqm in other projects later without any problems.

**Comment by ggnatalia** [comment]
Ok, thanks!
I'll try to reproduce it.
Just in case (because it is related with your particular data), could you send me the *_anvio_genes* file which is within the sqm2anvio folder to look into (or send me the line from the 5660473 gene entry in this file)?
I'm afraid it has a negative value coming from upstream results.

This should be created within the results folder.

**Comment by jahid10** [comment]
Hello ggnatalia, 
Thanks for looking into the problem. I have attached the zipped the anvio_genes file here. If there anything else you need, please let me know. 
https://doc-0k-0k-docs.googleusercontent.com/docs/securesc/19nk8ghi0dk3vutba56ptqmdm2uk8e0q/65mptsc1gp5gu694nu2lsnoa2b0ma678/1678268025000/12020632922898716723/10845181473800859913/1YX0lxWzOjzMzqdTXjSb8JPQ3OzAweOpo?e=download&authuser=0

**Comment by ggnatalia** [comment]
Hi, I'm afraid I cannot open the link. Could you send the document to ngarcia@cnb.csic.es?
