### ISSUE TITLE
Is it possible to find Antibiotic resistance Genes (ARGs) using Subset or other function?

### ISSUE THREAD

**Issue by yasiromics** [jtamames/SqueezeMeta#599]
Hi!
I have successfully loaded SQM data into R. thank you for all your help. 
I want to study the ARGs present in my metagenomic data. As the example data shows we can study different functions viz. carbohydrate, amino acid biosynthesis pathways, do we have any options for ARGs as well?

**Comment by fpusan** [comment]
Yes, but you need to know what term to search for (e.g. maybe "antibiotic resistance" will work as a search term, but maybe you need to refine and go for something like "beta-lactamase").
Alternatively, you can look for all the KOs in here (https://www.genome.jp/kegg/annotation/br01600.html)
The way to search for several things at once is to use standard regexp syntax
E.g. `subsetFun(SQM, "K00001|K00002")` will look for both terms at once.

**Comment by yasiromics** [comment]
Thanks for the prompt repones. I did try antibiotic resistance and individual KO Ids but to no avail. Can you kindly forward the link 
 or the script to put all KO Ids into the above syntax at once?

**Comment by fpusan** [comment]
Not at the moment, sorry, but just copying all the KO ids into a text editor and replacing `\n` by `|` might do the trick.

**Comment by yasiromics** [comment]
Do you mean like this?

AMR = subsetFun(WWTP, '18698' | '18699' | '18767' | '18797' | '19097' | '19317' | '18796' | '18768' | '18970')

it gives an error
Error in `[.data.frame`(x, i, j, drop) : undefined columns selected

**Comment by yasiromics** [comment]
Thank you. It worked

**Comment by fpusan** [comment]
Glad to hear! Closing issue
