### ISSUE TITLE
SQMtools not available for R 3.5.2

### ISSUE THREAD

**Issue by keckstrom** [jtamames/SqueezeMeta#60]
I'm finishing up my first test run in SqueezeMeta on a remote cluster and am looking to benchmark it against results from other tools in R on my local machine. I tried to install the SQMtools package via BiocManager, but it says it is unavailable in R version 3.5.2. In the manual it only shows loading the library and I can't find another way to install it locally. 

Can you tell me which version it's compatible with, or perhaps another issue that might be happening? The functionality in the vignette looks wonderful so I would love to test it out!

**Comment by fpusan** [comment]
Hi!

The SQMtools package has to be installed manually, as stated in the instructions. Try with

`sudo R CMD INSTALL <installpath>/SqueezeMeta/lib/SQMtools`

Where `<installpath>` would be the place were you installed SqueezeMeta.

Note that the `DAStool` package must be installed the same way in order for DAStool to work during binning.

Let me know if this works for you,

Fernando

**Comment by keckstrom** [comment]
Hi Fernando,

Is there a way to install just the SQMtools package separately? The issue I'm running into is that I ran the rest of the SqueezeMeta pipeline on our University's remote cluster and now want to export just the sqm2tables output to work with in R on my computer. Would I have to install the entirety of the SqueezeMeta library there as well?

**Comment by fpusan** [comment]
You can just copy the `<installpath>/SqueezeMeta/lib/SQMtools` directory to your personal computer and install it there manually. In case you are using Rstudio you probably have to compress the directory in order for it to recognize it as an installable package.

You'll need to copy the whole project, not only the output of `sqm2tables`, as the `loadSQM` function also requires the orf, contigs and bins table.

Just yesterday (47c850a) I added a new function to the SQMtools package names `loadSQMlite`, which will work with just the output of `sqm2tables` (no need for the rest of the project) but will give limited functionality (the different `subset` functions will not work, but you can still use the `plotTaxonomy`, `plotFunctions` and the newly introduced `exportKrona` functionalities.

So if you are interested on those features, be sure to clone or git pull the latest version of the master branch, redo the tables using the latest version of `sqm2tables` and you are good to go.

**Comment by fconstancias** [comment]
Hi @fpusan, do we really need the full SqueezeMeta directory to use the `loadSQM` function? As it contains loads of data, e.g., `data/raw_fastq/` ?

**Comment by fpusan** [comment]
Not really.

Just the `results` and `intermediate` directories should be enough, as long as you respect the directory structure.

**Comment by fconstancias** [comment]
@fpusan , thanks for your prompt reply.

even the big *.fasta and *.diamond files in the `intermediate` directory ?
```
3.2G Jan 19 03:24 02.EZ-squeezemeta.maskedrna.fasta
6.8G Jan 21 05:51 04.EZ-squeezemeta.eggnog.diamond
5.0G Jan 21 07:58 04.EZ-squeezemeta.kegg.diamond
7.1G Jan 21 03:58 04.EZ-squeezemeta.nr.diamond
891M Jan 23 06:58 05.EZ-squeezemeta.pfam.hmm
```

**Comment by fpusan** [comment]
No, just the `*.contigsinbins'  file

**Comment by fconstancias** [comment]
I have just run SqeezeMeta to generate a gene catalog using the following command :
`SqueezeMeta.pl -m coassembly -p EZ-squeezemeta -s EZ_test_sqeezeMeta.samples -f 01_QC --nobins --nomaxbin --nometabat -t 5 -b 20`


Hence, I do not have any *.contigsinbins file. 


```
ls -lh EZ-squeezemeta/intermediate/
total 27G
-rw-rw-r-- 1  73M Jan 19 02:17 01.EZ-squeezemeta.lon
-rw-rw-r-- 1  319 Jan 19 02:17 01.EZ-squeezemeta.stats
-rw-rw-r-- 1 3.2G Jan 19 03:24 02.EZ-squeezemeta.maskedrna.fasta
-rw-rw-r-- 1 6.8G Jan 21 05:51 04.EZ-squeezemeta.eggnog.diamond
-rw-rw-r-- 1 5.0G Jan 21 07:58 04.EZ-squeezemeta.kegg.diamond
-rw-rw-r-- 1 7.1G Jan 21 03:58 04.EZ-squeezemeta.nr.diamond
-rw-rw-r-- 1 891M Jan 23 06:58 05.EZ-squeezemeta.pfam.hmm
-rw-rw-r-- 1 368M Jan 23 22:02 09.EZ-squeezemeta.contiglog
-rw-rw-r-- 1 982M Jan 24 12:08 10.EZ-squeezemeta.contigcov
-rw-rw-r-- 1 2.3G Jan 24 12:13 10.EZ-squeezemeta.mapcount
```

Can I still import using `loadSQM` R function ?

**Comment by fpusan** [comment]
Should be possible in the latest commit ea36380

**Comment by fconstancias** [comment]
working great, thanks !

**Comment by jtamames** [comment]
Just a comment... setting --nobins overrides all binning methods, it is not neccesary to specify --nomaxbin --nometabat
Best,
J

**Comment by fconstancias** [comment]
Thanks for your comment. I was actually wondering if it is possible to continue with binning from a SqueezeMeta analysis folder even if I specified `--nobins` from the first command.

I have tried `restart.pl EZ-squeezemeta/ -step 14` but it didn't work as it was not part of the initial command I guess.

Thanks !

**Comment by jtamames** [comment]
Hello

Edit the Squeezemeta_conf.pl in the project directory, set the $nobins variable to zero (and also the $nomaxbin and $nometabat variables must be set to zero), and then restart as before.

Best,

**Comment by fconstancias** [comment]
Thanks Javier for your prompt reply. I got the following error, I guess al the folders are created at the beginning, that's might be the reason why?
```
restart.pl EZ-squeezemeta/ -step 14
[0 seconds]: STEP14 -> MAXBIN BINNING: 14.bin_maxbin.pl
mkdir: missing operand
Try 'mkdir --help' for more information.
Can't open /abund.list for writing
ERROR in STEP14 -> 14.bin_maxbin.pl
Can't open  directory
```

**Comment by jtamames** [comment]
Yes, it seems so. I will fix that asap. For now, copy these lines into your Squeezemeta_conf.pl file and restart again:

`%bindirs=("maxbin","$resultpath/maxbin","metabat2","$resultpath/metabat2");`
`%dasdir=("DASTool","$resultpath/DAS/$projectname\_DASTool\_bins");	`

**Comment by fconstancias** [comment]
super. it is working. Many thanks for the support during the weekend !
Have a nice weekend.

Best

**Comment by EricRaes** [comment]
Hello,

Hope you are well, and many thanks in advance for your help!

I am trying to have a look at the demo 'data' with the SQMtools package locally in R-studio as well. I downloaded the latest SqueezeMeta files (10/06/2020) and stored these on my laptop. When I open R studio, and set my working directory to  /SqueezeMeta-master/lib/SQMtools/ and try to load the library('SQMtools') I receive the error,  "there is no package called ‘SQMtools’".

I didn't quiet understand how I could fire up SQMtools in R studio from the post above unfortunately.

Would you please have some more info how the SQMtools and the R scripts within the/SqueezeMeta-master/lib/SQMtools/R can be recognized as installable package in R studio?

Many thanks!
Cheers,
Eric

**Comment by fpusan** [comment]
Hi!

Sure, in R studio go to Tools>Install Packages > "Package Archive File" and select the location of SQMtools.

If I remember correctly, you need to compress the whole `../SqueezeMeta/lib/SQMtools` directory into a single file in order for Rstudio to recognize it.

Let me know if this works for you!

Fernando

**Comment by EricRaes** [comment]
Hi Fernando,

Thanks for the quick reply but unfortunately it didn't work. 

I compressed the folder 'SQMtools' (right click in windows and zip it) -> to  'SQMtools.zip'

I then loaded the 'SQMtools.zip' in R Studio via Tools>Install Packages > "Package Archive File" 

I checked and the SQMtools folder is in my R library folder.

But when I load the SQMtools package in R studio -> library(SQMtools) I get the Error ‘SQMtools’ is not a valid installed package.

Any suggestions or help is much appreciated :-) !

**Comment by fpusan** [comment]
Hi,
This question sounds silly, but does it also fail if you compress the directory using *tar.gz rather than zip?
Also what's you OS?
Best,
Fernando

**Comment by EricRaes** [comment]
Hi Fernando,

Unfortunately not, I did: tar -zcvf SQMtools.tar.gz ~/SqueezeMeta-master/SqueezeMeta-master/lib/SQMtools

But received the ERROR:
cannot extract package from 'SQMtools.tar.gz'
Warning in install.packages :  installation of package ‘SQMtools.tar.gz’ had non-zero exit status

OS is Windows 10

**Comment by fpusan** [comment]
Ok, let me try to install R+Rstudio in Win10 and get back to you.

**Comment by EricRaes** [comment]
I ll keep looking here as well and post if I find an update, e.g., https://stackoverflow.com/questions/30989027/how-to-install-a-package-from-a-download-zip-file/30989367  looked promising but didn't work

Thanks a lot!!

**Comment by EricRaes** [comment]
Great that it works! Still struggling here though. R version is R-3.6.1.

Did you zip the ~/SqueezeMeta-master/SqueezeMeta-master/lib/SQMtools directory ?

**Comment by fpusan** [comment]
No, I tar.gz'd it. Find attached.
[SQMtools.tar.gz](https://github.com/jtamames/SqueezeMeta/files/4757229/SQMtools.tar.gz)

**Comment by EricRaes** [comment]
AWESOME!! That worked :-) thank you so much!! not sure why, but computer said ok. Excellent!!
