### ISSUE TITLE
Problem with external database

### ISSUE THREAD

**Issue by pedres** [jtamames/SqueezeMeta#601]
Hi,

I just wanna add an ARG database (MEGARES) but SqueezeMeta seems not to recognize it.
First I formated the database (is a DNA database so I used --ignore-warnings) and put it in the folder dbargs
~/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/diamond makedb -d args.dmnd --in megares_database_v3.00.fasta --ignore-warnings
Then I run SqueezeMeta
SqueezeMeta.pl -m coassembly -p ARGS -s test3.txt -f testing -extdb dblist.txt -t 32 -b 8 -miniden 80 --nobins

My dblist.txt file:
MEGARES dbargs

The syslog file:

[31 seconds]: STEP4 -> 04.rundiamond.pl
Running Diamond for taxa: /mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/bin/diamond blastp -q /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/ARGS/results/03.ARGS.faa -p 32 -d /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/databases/db/nr.dmnd -e 0.001 --id 80 -f tab -b 8 --quiet -o /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/ARGS/intermediate/04.ARGS.nr.diamond
Running Diamond for COGs: /mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/bin/diamond blastp -q /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/ARGS/results/03.ARGS.faa -p 32 -d /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/databases/db/eggnog -e 0.001 --id 80 --quiet -b 8 -f 6 qseqid qlen sseqid slen pident length evalue bitscore qstart qend sstart send -o /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/ARGS/intermediate/04.ARGS.eggnog.diamond
Running Diamond for KEGG: /mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/bin/diamond blastp -q /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/ARGS/results/03.ARGS.faa -p 32 -d /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/databases/db/keggdb -e 0.001 --id 80 --quiet -b 8 -f 6 qseqid qlen sseqid slen pident length evalue bitscore qstart qend sstart send -o /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/ARGS/intermediate/04.ARGS.kegg.diamond
Running Diamond for MEGARES dbargs: /mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/bin/diamond blastp -q /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/ARGS/results/03.ARGS.faa -p 32 -d  -e 0.001 --id 80 --quiet -b 8 -f 6 qseqid qlen sseqid slen pident length evalue bitscore qstart qend sstart send -o /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/ARGS/intermediate/04.ARGS.MEGARES dbargs.diamond
Stopping in STEP4 -> 04.rundiamond.pl. Program finished abnormally
_______

And the error is:
[0m taxa COGS   Running Diamond (Buchfink et al 2015, Nat Methods 12, 59-60) for KEGG
 MEGARES dbargsError: Invalid parameter count for option '--db'
Error running command:    /mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/bin/diamond blastp -q /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/ARGS/results/03.ARGS.faa -p 32 -d  -e 0.001 --id 80 --quiet -b 8 -f 6 qseqid qlen sseqid slen pident length evalue bitscore qstart qend sstart send -o /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/ARGS/intermediate/04.ARGS.MEGARES dbargs.diamond at /mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/SqueezeMeta/scripts/04.rundiamond.pl line 118, <infile1> line 0.000000.
[31mStopping in STEP4 -> 04.rundiamond.pl. Program finished abnormally
[0m[31m
  If you don't know what went wrong or want further advice, please look for similar issues in https://github.com/jtamames/SqueezeMeta/issues
  Feel free to open a new issue if you don't find the answer there. Please add a brief description of the problem and upload the /mnt/lustre/scratch/nlsas/home/uvi/ba/mav/ARGS/syslog file (zip it first)
[0mDied at /mnt/netapp2/Store_uni/home/uvi/ba/mav/conda/envs/SqueezeMeta/bin/SqueezeMeta.pl line 921.

**Comment by pedres** [comment]
Just for checking I have tried it redirecting the extdb to an existing diamong database. I have tried with two different list files but the error is the same
MEGARES databases/db/keggdbdmnd
MEGARES /databases/db/keggdbdmnd

**Comment by pedres** [comment]
Solved. It was a problem with the dblist which it was not tabulated...

**Comment by lisiruisusan** [comment]
> Solved. It was a problem with the dblist which it was not tabulated...

Dear pedres,

I came up with the same problems when adding external ARG database. So what is the tabular format? Is it .tsv? Shall I have a look at the dababase file succesfully added? Moreover, are there any recommended ARG databases that can be used together with squeezemeta? 

Yours sincerely,

Li

March 31st 2023

**Comment by fpusan** [comment]
Hi, yes, the file should have the fields separated by tabs, so a tsv.
Regarding the ARG database I would possibly try CARD (https://card.mcmaster.ca/), but I am not a big expert on that...
