### ISSUE TITLE
subsetTax without rescaling TPM 

### ISSUE THREAD

**Issue by adec37** [jtamames/SqueezeMeta#602]
I am looking to create a heat map of specific genes in my dataset. However, I only want the archaea domain to be mapped. Typically, I would go about this by using the subsetTax function and subsetting the Archaea, but this changes the calculated TPM to be based on the subsetted data, which I do not want.

I want to: 
- create a heat map of just Archaea 
- using the TPM from the original dataset that was not subsetted

Does anyone have any recommendations on how to accomplish this?

**Comment by fpusan** [comment]
Yes! We actually thought of this.
As per the documentation, `subsetTax(SQM, rank, tax, rescale_tpm=F)`

**Comment by adec37** [comment]
Thank you, thank you, thank you!
