### ISSUE TITLE
Should the use of external database (CAZY) produce abundance data for heatmap generattion?

### ISSUE THREAD

**Issue by afsanarupa** [jtamames/SqueezeMeta#605]
Hi, I want to see the abundances of CAZY enzymes in my metagenome data. I am using cazy database as my external db. So, if I run SqueezeMeta conventionally including --extdb, will the result of functional annotation be included in the further analysis? will I be able to see the abundances in tpm value for the cazy enzymes after my run is completed? also will they be amenable for anlaysis in R where I can use plotFunction to generate heatmap?

**Comment by jtamames** [comment]
Hello
Yes, it will.
