### ISSUE TITLE
Changing gradient color and font size in plotFunction SQMtools

### ISSUE THREAD

**Issue by afsanarupa** [jtamames/SqueezeMeta#607]
Hi, 
I want to change the gradient color and font size in plotFunction. Can you suggest me a way to change it in R studio. I tried edit(plotFunction) and trace(plotFunction) but they didn't seem to work

**Comment by fpusan** [comment]
As per the documentation
`plotFunction(SQM, gradient_col =c(color1, color2))`

**Comment by fpusan** [comment]
`plotFunction(SQM, gradient_col = c(color1, color2), base_size = 20)`

**Comment by afsanarupa** [comment]
Hi, sorry for bothering again. I solved the previous one myself. But actually I want to make the gene names in Y axis larger. using larger base_size mingles my sample names on x axis. Is there a way to just increase the font size on Y axis?

**Comment by fpusan** [comment]
No, sorry, for that degree of customization you'll need to make the plot yourself. 
The table is at SQM$functions$KEGG$tpm

**Comment by afsanarupa** [comment]
okay, Thank you

**Comment by afsanarupa** [comment]
Hi, what should I do, If want to export a table containing specific functions?

**Comment by fpusan** [comment]
Use normal R syntax to select the row names with the functions you want. We
provide the convenience function `exportTable` (easier to use than R's
write.table) for actually writing things to a file

**Comment by afsanarupa** [comment]
Thanks, but the problem is SQM$functions$KEGG$tpm has no name/function column, only KEGG id and tpm values.

**Comment by fpusan** [comment]
Yes, the KEGG id / function name relationships are in 
`SQM$functions$KEGG_names`
