### ISSUE TITLE
what is the meaning of percentage in case of subsetting.

### ISSUE THREAD

**Issue by jahid10** [jtamames/SqueezeMeta#608]
Hi, I have subset some specific function using subsetFunction, after combining I plotted the taxonomy. One thing I'm not clear is that what does the percentage in this case means? I have read your paper (figure-4), it says percentage of total reads? But specifically, does it mean percentage of total reads that can be assigned both to those functions and these taxas?
![pectin_tax_with_un](https://user-images.githubusercontent.com/65849689/212892590-b6ea7868-e6fb-4a10-8ba8-e63f28117aaf.png)

**Comment by fpusan** [comment]
The total percentage (height)of each bar is the percent of the total reads assigned to the specific function. The color division on each bar represent how all the reads from your function were assigned to the different taxa.

**Comment by jahid10** [comment]
Thank you very much
