### ISSUE TITLE
Pathway mapping

### ISSUE THREAD

**Issue by fconstancias** [jtamames/SqueezeMeta#61]
Dear SqueezeMeta developers and users,

I have sucessfully run SqeezeMeta to generate a gene catalog and now binning is running on.

I am interested in N cycle pathway and would ultimately like to quantify proportion/abundance of the different genes involved according to my samples.
- so far, my strategy is to filter baed on KO id and look at those genes.
- Is there any R package you are aware of that could help to directly extract genes ID or KEGG/COG id based on their presence in a particular pathway?
- If I can directly put the tpm/count values on the pathway that would be awsome.

Thanks

**Comment by jtamames** [comment]
Hello
Did you check the `12.<project>.funcover` files in sqm results? If we add the pathway info to each of the entries (genes) so that you can grep on them, it would be what you need, rigth?

**Comment by fpusan** [comment]
I think the latest developement version of `SQMtools` keeps track of that.
```
load(SQMtools)
SQM = loadSQM("my/project/path")
SQM$misc$KEGG_paths["K00376"] # KEGG pathways containing nitrous-oxide reductase.
SQM.carbMeta = subsetFun("Metabolism; Energy metabolism; Nitrogen metabolism")
```
`SQM.carbMeta` will be a SQM object containing only the ORFs from the `Nitrogen metabolism` pathway in the KEGG orthology. Ofc it will contain aggregated tpms for each function, in `SQM.carbMeta$functions$KEGG$tpm`.

Is this close to what you'd need? More info (though not from the latest version yet) can be found in the [wiki](https://github.com/jtamames/SqueezeMeta/wiki/Using-R-to-analyze-your-SQM-results).

**Comment by fpusan** [comment]
Actually it becomes trivial to plot the pathway using `pathview`.

```
library(SQMtools)
library(pathview)
SQM = loadSQM("my/project/path")
pathview(gene.data = SQM$functions$KEGG$tpm, pathway.id = "00910", species = "ko", out.suffix = "nitrogen")
```
Where `00910` is the KEGG ID for nitrogen metabolism as per https://www.genome.jp/dbget-bin/www_bget?ko00910.

I guess you'd have to play a bit with the different options of `pathview` to customize the plot.

**Comment by fconstancias** [comment]
Excellent, @fpusan @jtamames, thanks for your help.
