### ISSUE TITLE
ways to reduce contamination from a particular taxon

### ISSUE THREAD

**Issue by afsanarupa** [jtamames/SqueezeMeta#613]
Hello, Im doing a metagenomic coassembly project. My samples are environemental samples concerning a biological process. In taxonomic abundance I see that my RC_d0 and RC_d5 (left two) samples are heavily contaminated with pseudomonas. This is particularly no expected and arise maybe due to sampling or handling errors. Is  there a way to reduce this contamination before or after the assembly is performed?

![phylum_c_03_unmapped_unclassified](https://user-images.githubusercontent.com/118095926/215407345-4489b0a2-5b78-4da2-a519-672c6c0eb0ae.png)
![genus_c_01_unclassified_unmapped](https://user-images.githubusercontent.com/118095926/215407845-36701efd-7f7f-474e-a26e-92a7d5b9b882.png)

**Comment by AlexandreThibodeauUdM** [comment]
Hello, I am a noob here but a veteran of 16S analysis. Can you removed everything classified as Pseudomonas in R?

**Comment by afsanarupa** [comment]
"Hello, I don't want to exclude Pseudomonas completely, but a way to reduce the over representation from pseudomonas? Can I consider normalization (Im a noob on this issue).

**Comment by AlexandreThibodeauUdM** [comment]
Do you have a negative control? You could use it for normalization I guess. Otherwize, I am clueless

**Comment by fpusan** [comment]
As Alexandre says, there is not an easy way to "reduce the overrepresentation" of Pseudomonas, unless you have some understanding on how much the Pseudomonas are actually overrepresented (e.g. by having sequenced a mock community).
