### ISSUE TITLE
pip install?

### ISSUE THREAD

**Issue by AlexandreThibodeauUdM** [jtamames/SqueezeMeta#616]
Hello!

My computer cluster is not using conda for install, but pip. Is there a way to pip install SqueezeMeta or I am forced to clone the git repo?

Thanks!

**Comment by fpusan** [comment]
No, there is no pip option.
Note that you may be able to install miniconda in your home directory and work from there, even if the cluster itself does not have conda installed.
You would just need to activate conda and your environment in the bash script you use for launching your works to the queue like in

```
source /home/user/path/to/miniconda3/bin/activate
conda activate SqueezeMeta
SqueezeMeta.pl ...
```
