### ISSUE TITLE
Problem with loadSQM in local machine

### ISSUE THREAD

**Issue by lokyimandy** [jtamames/SqueezeMeta#617]
Hi, I ran the project at University's cluster, and I ran `sqm2tables.py squeezemeta_sc_dna squeezemeta_sc_dna/results/tables` before transferring the results directory, SqueezeMeta_conf.pl and intermediate/contigsinbins under the project name of squeezemeta_sc_dna to local machine

I followed previous posts about installing SQMtools in local machine by compressing the file SqueezeMeta/lib/SQMtools using `tar- zcvf SQMtools.tar.gz SQMtools`

I have intalled the packages as following:
```
install.packages("doMC")
install.packages("ggplot2")
install.packages("data.table")
install.packages("reshape2")
install.packages("BiocManager")
BiocManager::install("pathview")
BiocManager::install('org.Hs.eg.db')
```

When I ran `install.packages("~/Desktop/Disinfection(Bimonthly_P2)/Result/SQMtools.tar.gz", repos = NULL, type = "source")`, I got the following error:

_Error in rawToChar(info) : 
  embedded nul in string: '30 mtime=1675449930.372204666\n74 LIBARCHIVE.xattr.com.apple.quarantine=MDA4MjswMDAwMDAwMDtmaWxlemlsbGE7\n62 SCHILY.xattr.com.apple.quarantine=0082;00000000;filezilla;\n133 LIBARCHIVE.xattr.com.apple.macl=BQBo6XxUSUBEvac46k0E5r1TAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\n105 SCHILY.xattr.com.apple.macl=\005\0h\xe9|TI@D\xbd\xa78\xeaM\004\xe6\xbdS\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\n'
Warning in install.packages :
  installation of package ‘/Users/lokyitang/Desktop/Disinfection(Bimonthly_P2)/Result/SQMtools.tar.gz’ had non-zero exit status_

Anyway, I tried `devtools::install_local("SQMtools.tar.gz")`, and it seems successful except skipping the pathview package:

Skipping 1 packages not available: pathview
── R CMD build ──────────────
✔  checking for file ‘/private/var/folders/mj/ggsv7h6d4gn6bh7z50nctz480000gn/T/RtmpAhFqZy/remotes13eb774ad8b6/SQMtools/DESCRIPTION’ ...
─  preparing ‘SQMtools’:
✔  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
     NB: this package now depends on R (>= 3.5.0)
     WARNING: Added dependency on R >= 3.5.0 because serialized objects in
     serialize/load version 3 cannot be read in older versions of R.
     File(s) containing such objects:
       ‘SQMtools/data/Hadza.RData’
─  building ‘SQMtools_1.6.0.tar.gz’
* installing *source* package ‘SQMtools’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (SQMtools)

So I started loading the project using SQMtools, unfortunately no matter I run `scd = loadSQM('squeezemeta_sc_dna', engine = 'data.table')` or `scd = loadSQM('squeezemeta_sc_dna')` , it gave me this error:

_Generating tabular outputs for project in squeezemeta_sc_dna
sh: /home/lytangaa/miniconda3/envs/env_mamba/envs/SqueezeMeta/SqueezeMeta/utils/sqm2tables.py: No such file or directory
Error in loadSQM("squeezemeta_sc_dna", engine = "data.table") : 
  An error occurred while running sqm2tables.py
In addition: Warning message:
In system(command) : error in running command_

The path of sqm2table.py is in the cluster.  Previous posts mentioned that there is no need to install Squeezemeta in local machine, so I really don't know how to fix it. Sorry for being so lengthy, just want to provide more information as I am not sure where the problem is. Thank you for offering help.

**Comment by fpusan** [comment]
Hi! 
You need to run sqm2tables.py in your cluster, before copying the project to your local computer

**Comment by lokyimandy** [comment]
Thank you for your prompt reply. Yes, I did. I ran it in the cluster before transferring the files to the local computer.

**Comment by fpusan** [comment]
What is the content of the `squeezemeta_sc_dna/results/tables` directory?

**Comment by lokyimandy** [comment]
metag_stw.COG.abund.tsv
metag_stw.COG.bases.tsv
metag_stw.COG.copyNumber.tsv
metag_stw.COG.cov.tsv
metag_stw.COG.names.tsv
metag_stw.COG.tpm.tsv
metag_stw.KO.abund.tsv
metag_stw.KO.bases.tsv
metag_stw.KO.copyNumber.tsv
metag_stw.KO.cov.tsv
metag_stw.KO.names.tsv
metag_stw.KO.tpm.tsv
metag_stw.PFAM.abund.tsv
metag_stw.PFAM.bases.tsv
metag_stw.PFAM.copyNumber.tsv
metag_stw.PFAM.cov.tsv
metag_stw.PFAM.tpm.tsv
metag_stw.RecA.tsv
metag_stw.bin.tax.tsv
metag_stw.class.allfilter.abund.tsv
metag_stw.class.nofilter.abund.tsv
metag_stw.class.prokfilter.abund.tsv
metag_stw.contig.sequences.tsv
metag_stw.contig.tax.allfilter.tsv
metag_stw.contig.tax.nofilter.tsv
metag_stw.contig.tax.prokfilter.tsv
metag_stw.family.allfilter.abund.tsv
metag_stw.family.nofilter.abund.tsv
metag_stw.family.prokfilter.abund.tsv
metag_stw.genus.allfilter.abund.tsv
metag_stw.genus.nofilter.abund.tsv
metag_stw.genus.prokfilter.abund.tsv
metag_stw.order.allfilter.abund.tsv
metag_stw.order.nofilter.abund.tsv
metag_stw.order.prokfilter.abund.tsv
metag_stw.orf.sequences.tsv
metag_stw.orf.tax.allfilter.tsv
metag_stw.orf.tax.nofilter.tsv
metag_stw.orf.tax.prokfilter.tsv
metag_stw.phylum.allfilter.abund.tsv
metag_stw.phylum.nofilter.abund.tsv
metag_stw.phylum.prokfilter.abund.tsv
metag_stw.species.allfilter.abund.tsv
metag_stw.species.nofilter.abund.tsv
metag_stw.species.prokfilter.abund.tsv
metag_stw.superkingdom.allfilter.abund.tsv
metag_stw.superkingdom.nofilter.abund.tsv
metag_stw.superkingdom.prokfilter.abund.tsv

**Comment by lokyimandy** [comment]
On no, I think I know what the problem is. I changed the project name from metag_stw to squeezemeta_sc_dna in the cluster before, that why it didn't recognise the files. I changed the name to metag_stw again and it works! Thank you for your reply.

**Comment by fpusan** [comment]
Glad to hear! Closing issue
