### ISSUE TITLE
minimum contig length can affect memory requirements?

### ISSUE THREAD

**Issue by Lafmas** [jtamames/SqueezeMeta#618]
Hi,

I'm having trouble analyzing 11 metagenome samples (10gb per sample) in coassembly mode with Megahit. 

Despite having 512GB of memory, the process keeps getting cancelled with exit code -9. 

Since it seems to be a memory issue, I tried to analyze the samples in merged mode, but the process took too long in Minimus2 and had to be stopped after more than 14 days.

My question is: can I lower the memory requirements by adjusting the minimum contig length? I'm currently using the default value of 200, but I plan to try setting it to 1000. 

If this reduces the memory requirements, I'll attempt the coassembly mode analysis again.

Thanks,
Lafmas

**Comment by Lafmas** [comment]
Hi again,

I have one more question. If adjusting the minimum contig length doesn't affect the memory requirements, I'm considering using the minimum contig length of 1000 and either the merged or seqmerged mode.

Is 11 samples a reasonable number for merged mode? If not, would seqmerged mode be a better option?

Overall, if increasing the minimum contig length to 1000 reduces memory requirements, I'll use the coassembly mode. Otherwise, I'll use merged or seqmerged mode.

Thanks,
Lafmas

**Comment by fpusan** [comment]
Adjusting the contig length will not reduce the memory requirements for assembly.
When you say "11 Gb per sample" you mean the size of the `fastq.gz` files? Or the actual number of input gigabases per sample?
You can also try to add `--assembly_options "--presets meta-large"` when calling SqueezeMeta. Maybe it helps

**Comment by Lafmas** [comment]
Thanks for your quick reply!

There are 11 of samples in the analysis (that is each sample consist two `fastq.gz` files pair1, and pair2) and each sample has 10 gigabases input size.

**Comment by fpusan** [comment]
This is on the largish-size, it may or may not be possible to coassemble it with 512Gb depending on how complex the communities are in terms of alpha and beta diversity.
Did the extra assembly options help in this case?

**Comment by Lafmas** [comment]
The contig length was set to 800, and the assembly was performed using seqmerge mode. 

This approach allowed the analysis to be completed relatively quickly!

Best,
Lafmas

**Comment by fpusan** [comment]
Glad to hear.
I am actually surprised that seqmerge worked for this. Probably setting a higher contig length helped with this, by greatly reducing the amount of contigs to be merged. I will update the docs to reflect this possibility.

**Comment by Lafmas** [comment]
> Glad to hear. I am actually surprised that seqmerge worked for this. Probably setting a higher contig length helped with this, by greatly reducing the amount of contigs to be merged. I will update the docs to reflect this possibility.

I`ll upload here my project`s `syslog` for you soon.
