### ISSUE TITLE
run sqm_hmm_reads.pl error!

### ISSUE THREAD

**Issue by luozhy88** [jtamames/SqueezeMeta#619]
SqueezeMeta is very good, thank you very much.
I have such an error when running this, and I need your help to solve it.
![image](https://user-images.githubusercontent.com/94740863/217705839-d5e9cb64-b3c6-4c93-bab3-7afe073dab7f.png)
![image](https://user-images.githubusercontent.com/94740863/217705872-6ddca3fe-3360-4194-b2f9-fd6947e25f44.png)
![image](https://user-images.githubusercontent.com/94740863/217706006-fc34e965-efc2-4853-bc31-ed0f261adaf2.png)

**Comment by luozhy88** [comment]
<img width="952" alt="image" src="https://user-images.githubusercontent.com/94740863/217707069-c3e24d7d-af0f-42c5-8c63-a7cc4e85d7da.png">

**Comment by jtamames** [comment]
Hello
I am currently out of the lab with very poor internet connectivity. I will check this asap

**Comment by jtamames** [comment]
Ok, the problem is that Pfam site (where we were getting the Pfam files) was discontinuated and migrated for integration with Interpro. As a quick fix, you can change lines 162 and 166 in sqm_hmm_reads.pl, substituting pfam.xfam.org by pfam-legacy.xfam.org. 
I will produce a better patch to read interpro instead of Pfam, but that one can work in the meantime.
Best,
J

**Comment by luozhy88** [comment]
Error!!
![image](https://user-images.githubusercontent.com/94740863/218310249-b8fe1b06-00b0-4d2d-a88f-136d73d1bc19.png)
![image](https://user-images.githubusercontent.com/94740863/218310254-6641b5ea-9bc5-40ab-8d98-1515be3324d0.png)

**Comment by luozhy88** [comment]
Thanks,it did work. But I have another bug.
<img width="1227" alt="image" src="https://user-images.githubusercontent.com/94740863/218310914-78430769-936b-4112-b9b2-14bfe5c8cc34.png">

**Comment by luozhy88** [comment]
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/94740863/218479725-34fd39fb-7b9e-4225-b7e5-b6baa4b4ce77.png">
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/94740863/218479784-8e3f8f19-3392-4f01-85b7-61ec6adff226.png">
why?

**Comment by luozhy88** [comment]
Can you help me?

**Comment by luozhy88** [comment]
Can you help me?

**Comment by jtamames** [comment]
Did you check if you have writing permissions in the directory where the files are being created? That is, the `/data_bk/zhiyu/Project/test/rm_host` directory?
