### ISSUE TITLE
KEGG databse version

### ISSUE THREAD

**Issue by fconstancias** [jtamames/SqueezeMeta#621]
Dear SqueezeMeta developpers & community,

Which version of the KEGG databse is part of SqueezeMeta?

Thanks for the info.

**Comment by jtamames** [comment]
Look at issue #321. I will try to put versions of the database in the file methods.txt
Best,
J

**Comment by jtamames** [comment]
Look at issue #367. I will try to put versions of the database in the file methods.txt
Best,
J
