### ISSUE TITLE
Argument checking in SqueezeMeta.pl would prevent the use of custom assemblers?

### ISSUE THREAD

**Issue by fpusan** [jtamames/SqueezeMeta#624]
This line in particular

`if($assembler!~/megahit|spades|rnaspades|canu|flye/i) { $dietext.="UNRECOGNIZED assembler $assembler (valid ones are megahit, spades, canu or flye)\n"; }`

would make the IDBA example in our PDF manual fail, I think. The list of valid assembler names should rather be gathered from the hash keys in `%assemblers` in `SqueezeMeta_conf.pl`.

**Comment by jtamames** [comment]
Hello @fpusan
Thank you for your interest in SqueezeMeta! 
Yep, correct, that line should be corrected
Best,
J
