### ISSUE TITLE
error in loadSQM

### ISSUE THREAD

**Issue by Nykolazzo72** [jtamames/SqueezeMeta#627]
Hello,
We' ve  succesfully processed 6 metagenomic samples with SqueezeMeta (sequential mode), and we are experiencing some troubles while trying to further analyze our results using SQMtools through rstudio.
After invoking rstudio in SqueezeMeta conda environment and loading the SQMtools library, we ran the following command and were greeted with this error message:
> N77 = loadSQM('/home/usuario/N77/', engine = 'data.table')
Loading total reads
Loading orfs
    table...
    abundances...
    sequences
    taxonomy...
Loading contigs
    table...
    abundances...
Error in `[.data.frame`(x, i, j, drop) : undefined columns selected
Además: Warning message:
In sprintf("%s/results/tables/%s.superkingdom.%s.abund.tsv", project_path,  :
  one argument not used by format '%s/results/tables/%s.superkingdom.%s.abund.tsv'

Thanks in advance for your assistance!

**Comment by fpusan** [comment]
I suspect your project was generated with an older version of SqueezeMeta.
What version did you use for generating the project, and what version of SQMtools are you using to load it?

**Comment by Nykolazzo72** [comment]
Hi Fernando,

Thanks for your prompt response. Answering your question, the project was
generated using SqueezeMeta v 1.6.0 and the SQMtools version is 0.8.0.
Greetings,

Nicolás.

**Comment by fpusan** [comment]
Try using SQMtools version 1.6.0 or 1.6.1

**Comment by Nykolazzo72** [comment]
Thanks, I'll check it out.

**Comment by Nykolazzo72** [comment]
Hi Fernando,

I finally reinstalled SqueezeMeta (albeit a newer version) and that did the
trick!
Thanks a bunch for your help!

Nicolás.

**Comment by fpusan** [comment]
glad to hear. clossing issue!
