### ISSUE TITLE
Can I resume a sqm_longreads.pl run?

### ISSUE THREAD

**Issue by jllavin77** [jtamames/SqueezeMeta#630]
Dear all,

I was running an analysis using **sqm_longreads.pl** and at the end of the project mi SDD unit was completely filled with the results, therefore, the final results couldn't be written, and the process halted (after over a week running smoothly).
Is there any way to resume/restart (as there is in the main SqueezeMeta script) the analysis without repeating every individual sample analysis again?

Thanks in advance

**Comment by jllavin77** [comment]
It seems that running the script again with exactly the same options, the program is able to automatically detect which result files are already present. It gives you the option of not overwritting those files and skip that steps, continuing with the whole process, saving the time repeating the analysis would take. 
GREAT FEATURE by the way.
Cheers

**Comment by jtamames** [comment]
Hello

Ouch! Yep, Diamond results require a lot of disk space, especially in 
big project like yours.

Unless the option --force_overwrite is provided, sqm_longreads will NOT 
redo any existing result. Therefore, if you run it again with the very 
same command, it should restart where it ended. Just check if some of 
the last files was left unfinished, and remove just that one to be able 
to redo it.

Best,

J
