### ISSUE TITLE
doublepass post completion

### ISSUE THREAD

**Issue by sheaster** [jtamames/SqueezeMeta#631]
Hi there, 
SqueezeMeta is awesome! 
Is it possible to run the doublepass analysis alone after the pipeline has completed? 
I would ideally like to analyze the "new" orfs that result. 
Thanks!

**Comment by sheaster** [comment]
also, would it be possible to save the raw diamond blastx output?

**Comment by jtamames** [comment]
It should do it, in the intermediate directory

**Comment by sheaster** [comment]
ah I see thank you. Is it possible to run the double pass option independently after completion to see what new ORFs are found?

**Comment by fpusan** [comment]
You can, but you would still need to repeat everything from step 8

**Comment by sheaster** [comment]
thanks for both responses! appreciate it
