### ISSUE TITLE
Stats on reads

### ISSUE THREAD

**Issue by analopezlopez** [jtamames/SqueezeMeta#632]
Hi, 

Just a quick question regarding the stats provided at the last step of the pipeline:

#------------------- Statistics on reads
--
# | Assembly
Number of reads | 5696819
Number of bases | 8644116937

Is "number of reads" (in this case 5696819) here referring to the total number included in bins during the assembly? Or the total number of reads analyzed? Sorry about the silly question, just want to have my facts right.

Thank you!

Best,
Ana

**Comment by jtamames** [comment]
Hello

Not silly at all. That number is the total number of reads analyzed.

Best,

J

**Comment by analopezlopez** [comment]
Great! Thank you very much.
