### ISSUE TITLE
Unknown option 'restart' when restarting a step

### ISSUE THREAD

**Issue by jahid10** [jtamames/SqueezeMeta#634]
Hi, 
I faced an error in step 4. I dont know exactly what went wrong, so I tried to restart the run using the following command:

$ SqueezeMeta.pl -p metagenom_run_final --restart

however I get this message from th prompt.
Unknown option: restart
Usage: SqueezeMeta.pl -m <mode> -p <project name> -s <samples file> -f <sequence dir> [options]

Am I doing the command wrong?

**Comment by jtamames** [comment]
Hello

Which version of SqueezeMeta are you using? The flag --restart was 
introduced in 1.6. If you are using an older version, use the restart.pl 
script.

Best,

J

**Comment by jahid10** [comment]
thanks, it worked with restart.pl
