### ISSUE TITLE
GTDB with SqueezeMeta

### ISSUE THREAD

**Issue by mscarbor** [jtamames/SqueezeMeta#635]
Long time user, first time poster... Thanks for all that you and your team do. 

Are there any suggestions or plans for incorporating GTDB taxonomic classifications with SqueezeMeta? As of now, it looks like a GTDB database is not available. I would love to be able to assign taxonomy to long reads with SqueezeMeta. It's a big ask, I know, but I'm throwing it out there.

**Comment by fpusan** [comment]
You can assign taxonomy to long reads with SqueezeMeta (see the script in `utils/sqm_longreads.pl`) without assembly.
However I actually have plans on incorporatic gtdb for MAG/pangenome analysis, hopefully later this year

**Comment by jtamames** [comment]
Hello Matt

Thanks for being a loyal user! We would love to integrate GTDB into 
SqueezeMeta. For now the enormous size of the databases they are using 
is preventing us to do so. But I promise to rethink this issue and see 
if we can do it somehow. As Fernando likes to say, stay tuned.

Best,

J

**Comment by mscarbor** [comment]
Javier/ Fernando-- Appreciate the quick responses! Makes sense that this would be a significant effort... Reach out if you ever need a letter from a user/PI to support the effort.

**Comment by fpusan** [comment]
Work towards this has started in a0ae6a7, though for now we are using it to classify bins rather than long reads.
I see that you'd like to use it to classify individual long reads. Have you seen it used like that elsewhere?

**Comment by mscarbor** [comment]
No, actually! Since the GTDB is based on just the concatenated sequences of
their marker genes, this wouldn't actually work, would it? Having it for
bins would be amazing though :-)

**Comment by fpusan** [comment]
However someone else seems to be doing what you suggested...
https://www.biorxiv.org/content/10.1101/2023.12.17.572079v1
