### ISSUE TITLE
error at step 4 rundiamond.pl

### ISSUE THREAD

**Issue by jahid10** [jtamames/SqueezeMeta#636]
Hi, I was running SqueezeMeta (v 1.5.1) on coassembly mode with the following command:

>SqueezeMeta.pl -m coassembly -p metagenom_run_final -s /media/bioinfo/hdd2/final.samples -f /media/bioinfo/hdd1/Jahid_NGS_metagenomics/NGS_data_metagenomics  --cleaning -c 300 --D -canumem 64 --extdb /media/bioinfo/hdd1/Metagenome_databases/db/CAZy_db.dmnd

I got error at step 4 during homology searches with DIAMOND. I tried to restart the run from the same step but again I got the same  error message:

Setting block size for Diamond
  AVAILABLE (free) RAM memory: 121.80 Gb
  We will set Diamond block size to 15.2 (Gb RAM/8, Max 16).
  You can override this setting using the -b option when starting the project, or changing
  the $blocksize variable in SqueezeMeta_conf.pl
 taxa COGS   Running Diamond (Buchfink et al 2015, Nat Methods 12, 59-60) for KEGG
 m���J��%���D�W�G0>:��L��{�ۜ�k>���
                                 Error: Invalid parameter count for option '--db'
Error running command:    /home/bioinfo/anaconda3/envs/SqueezeMeta/SqueezeMeta/bin/diamond blastp -q /media/bioinfo/hdd2/Metagenome_jute/metagenom_run_final/results/03.metagenom_run_final.faa -p 12 -d  -e 0.001 --id 30 --quiet -b 15.2 -f 6 qseqid qlen sseqid slen pident length evalue bitscore qstart qend sstart send -o /media/bioinfo/hdd2/Metagenome_jute/metagenom_run_final/intermediate/04.metagenom_run_final.m���J��%���D�W�G0>:��L��{�ۜ�k>���
                                   .diamond at /home/bioinfo/anaconda3/envs/SqueezeMeta/SqueezeMeta/scripts/04.rundiamond.pl line 118, <infile1> line 0.000000.
Stopping in STEP4 -> 04.rundiamond.pl. Program finished abnormally
Died at /home/bioinfo/anaconda3/envs/SqueezeMeta/bin/restart.pl line 562.

[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/10894332/syslog.zip)

**Comment by fpusan** [comment]
From your call to SqueezeMeta
`--extdb /media/bioinfo/hdd1/Metagenome_databases/db/CAZy_db.dmnd`
Is this the actual diamond-formatted database for CAZy?
If so, this would be incorrect, and I am actually quite surprised that SqueezeMeta managed to run that far. 
You instead need to provide a tab separated file with the name and path for the external databases. See the PDF manual for details.
