### ISSUE TITLE
alternative strategy to merged mode

### ISSUE THREAD

**Issue by fconstancias** [jtamames/SqueezeMeta#64]
Dear @fpusan , dear @jtamames ,

I have one question regarrding assembly/binning strategy for metagenomes when co-assembly is not possible/advised.
If I undserstand correctly, in the merged mode of SqueezeMeta, single-assembly is performed and contigs are merged together before mapping and binning.
Could it be possible to use within SqeezeMeta single assembly, mapping of all samples against each of the co-assembly in order to get coverage information which will be used for binning and then per sample binning before checking and collapsing redundancy between MAGs idividualy identified within each sample. This will be similar to what Tom O Delmont et al developped for Tara (see : http://merenlab.org/data/tara-oceans-mags/).

What do you think about this strategy? Would it be feasable to implment it in SqeezeMeta?

Have a great weekend.

**Comment by jtamames** [comment]
Hello @fconstancias 

This is exactly what the co-assembly mode of SqueezeMeta is doing: pooling all samples together, co-assemble them, and estimate coverages via mapping of original reads to the co-assembly. Indeed is the recommended procedure when you have not many samples (see [https://github.com/jtamames/SqueezeMeta/wiki/When-to-use-each-of-the-SqueezeMeta-modes](url)). Merged mode is an alternative when you have that many samples that you cannot co-assemble them. In the soon coming version 1.1.0 we will introduce a new mode "seqmerge", intended to work when you have A LOT of samples (>50). 

Hope it helps
Best,

**Comment by jtamames** [comment]
Closed by inactivity
