### ISSUE TITLE
Error in subsetORFs

### ISSUE THREAD

**Issue by priya-decodeage** [jtamames/SqueezeMeta#641]
#To check taxa for particular functions & plot 
------------------------------------------------------------
dop = subsetFun(Input, fun = 'dopamine' , rescale_copy_number = F)
plotTaxonomy(dop, 'species', 'percent', N = 10, rescale = F, others = T)
plotFunctions(dop, fun_level = 'KEGG',count = 'abund')

Error
-----------------
Error in subsetORFs(SQM, goodORFs, tax_source = "orfs", trusted_functions_only = trusted_functions_only,  : 
  No ORFs were selected. Perhaps the subset query yielded no results?

What does this error mean? How do I overcome this error?

**Comment by fpusan** [comment]
It means that the substring "dopamine" is not present in the functional annotations of the ORFs in object `dop`
