### ISSUE TITLE
Two -miniden cut-off for same Run

### ISSUE THREAD

**Issue by drbmanna** [jtamames/SqueezeMeta#642]
Hi, 

I want to use the default  -miniden 50 cut-off for the KEGG, COG and Pfam databases. However, I have another external database where I want to impose more strict criteria of -miniden 80. Do I need to perform two separate runs with -miniden 50 and -miniden 80 (restarting at Step 4)? Any better way to accomplish this in a time-saving manner? 

Thank you so much.
BM.

**Comment by jtamames** [comment]
Hello

Yes, there is no way to specify different parameters for the different 
databases. But I will try to implement that in upcoming versions.

Best,

J

**Comment by drbmanna** [comment]
Hi Javier, 

Thank you so much. Looking forward to the feature in the future. 

Thanks,
BM.
