### ISSUE TITLE
Error at step 04.rundiamond.pl

### ISSUE THREAD

**Issue by jahid10** [jtamames/SqueezeMeta#643]
Hi,
I was running SqueezeMeta in coassemly mode with the following command:
home/bioinfo/anaconda3/envs/SqueezeMeta/bin/SqueezeMeta.pl -m coassembly -p metagenom_run_final -s /media/bioinfo/hdd2/final.samples -f /media/bioinfo/hdd1/Jahid_NGS_metagenomics/NGS_data_metagenomics --cleaning -c 300 --D --extdb /media/bioinfo/hdd2/Metagenome_jute/Cazy_db.list

during Step 4, I hit the following error, Can you please let me know why I encountered this particular error?

axaError running command:    /home/bioinfo/anaconda3/envs/SqueezeMeta/SqueezeMeta/bin/diamond blastp -q /media/bioinfo/hdd2/Metagenome_jute/metagenom_run_final/results/03.metagenom_run_final.faa -p 12 -d /media/bioinfo/hdd1/Metagenome_databases/db/nr.dmnd -e 0.001 --id 40 -f tab -b 15.4 --quiet -o /media/bioinfo/hdd2/Metagenome_jute/metagenom_run_final/intermediate/04.metagenom_run_final.nr.diamond at /home/bioinfo/anaconda3/envs/SqueezeMeta/SqueezeMeta/scripts/04.rundiamond.pl line 72.
Stopping in STEP4 -> 04.rundiamond.pl. Program finished abnormally

Died at /home/bioinfo/anaconda3/envs/SqueezeMeta/bin/SqueezeMeta.pl line 1381.

[syslog (1).zip](https://github.com/jtamames/SqueezeMeta/files/10954636/syslog.1.zip)

**Comment by fpusan** [comment]
Which version of SqueezeMeta are you using?

**Comment by fpusan** [comment]
This is most likely an issue that was fixed in 1.5.2.
You can use the latest version of SqueezeMeta, or alternatively update SqueezeMeta's DIAMOND to  2.0.14 or higher

**Comment by jahid10** [comment]
Thank you, but I haven't faced this issue in the previous run. The only different thing in this run is the inclusion of external database, everything else is similar, should I update SqueezeMeta to the latest version then?

**Comment by fpusan** [comment]
The issue only triggered for certain datasets and in certain platforms, so I would try updating first just to be sure

**Comment by jtamames** [comment]
In any case, could you paste your `/media/bioinfo/hdd2/Metagenome_jute/Cazy_db.list` file, just to verify it is fine?

**Comment by jahid10** [comment]
Hi, sorry for the delay in response. It was solved after I correceted my db.list file and the rest of the run was went smoothly.
