### ISSUE TITLE
Stuck at "solving enviroment"

### ISSUE THREAD

**Issue by msanchezr99** [jtamames/SqueezeMeta#645]
I tried to update conda, install a package and update the anaconda navigator and none of them worked. The prompt stays forever saying solving enviroment. I read a past thread on the subject and followed the instructions of removing and adding the forge channel (honestly do not really know what a channel is here) and nothing has worked. I also uninstalled (with the uninstall.exe because I can not install clean from prompt), reinstalled it and still does not work.

**Comment by fpusan** [comment]
What exact command have you used to try and install it?
Also, you mention _uninstall.exe_. Is this maybe a Windows computer?

**Comment by msanchezr99** [comment]
I have used conda update conda, conda uptade anaconda-navigator, and this is what it show
>conda update conda
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed
The last statement is failed because I stoped it. It stays in the process indefintely.

**Comment by fpusan** [comment]
These are not the installation instructions. Please check the ReadMe for details.
Also, SqueezeMeta works only in Linux. This is also documented.
I strongly recommend that you get access to a Linux machine. Otherwise, get either WSL2 for windows or a virtual machine with Linux installed.

**Comment by fpusan** [comment]
I mean the installation of SqueezeMeta.
For questions about installing anaconda, refer to their forum and/or documentation.
But as I said, SqueezeMeta won't work in your windows computer, even if you manage to install anaconda there.
