### ISSUE TITLE
SQMtools version and numpy

### ISSUE THREAD

**Issue by HannahBenisty** [jtamames/SqueezeMeta#647]
Hi, 

Could you please help me with this error? I do not find out how to proceed:

> banyuls2 = loadSQM('/users/rg/hbenisty/sqm_09_bis/banyuls2')
Generating tabular outputs for project in /users/rg/hbenisty/sqm_09_bis/banyuls2
Traceback (most recent call last):
  File "/nfs/users/rg/hbenisty/miniconda3/envs/SqueezeMeta/SqueezeMeta/utils/sqm2tables.py", line 36, in <module>
    from utils import parse_conf_file, parse_mappingstat, parse_orf_table, parse_tax_table, parse_contig_table, parse_contig_tax, parse_bin_table, parse_tax_string, read_orf_names, aggregate_tax_abunds, normalize_abunds, write_orf_seqs, write_contig_seqs, write_row_dict, TAXRANKS, TAXRANKS_SHORT 
  File "/nfs/users/rg/hbenisty/miniconda3/envs/SqueezeMeta/SqueezeMeta/utils/../lib/utils.py", line 7, in <module>
    from numpy import array, isnan, seterr
ModuleNotFoundError: No module named 'numpy'
Error in loadSQM("/users/rg/hbenisty/sqm_09_bis/banyuls2") : 
  An error occurred while running sqm2tables.py
In addition: Warning message:
In loadSQM("/users/rg/hbenisty/sqm_09_bis/banyuls2") :
  Your project was created with SqueezeMeta v1.6.1, while this is SQMtools v1.6.2. You can ignore this message if things are working fine for you, but if you experience any issue consider using the right version of SQMtools for this project

Many thanks, 
Hannah

**Comment by fpusan** [comment]
You need to run `sqm2tables.py` before transferring your data to a different computer. 
If you are trying this in the same computer in which you installed SqueezeMeta, then you need to activate the proper conda environment. 

Also... How did you install that version of SQMtools? It is not officially out yet :)

**Comment by HannahBenisty** [comment]
Thanks! It worked :) 

I used BiocManager::install("SQMtools") for the installation.

**Comment by fpusan** [comment]
Well, glad it worked! Hopefully will make this official by the end of the week
