### ISSUE TITLE
SQM Tools 1.6.0 compatability with sqm_longreads.pl?

### ISSUE THREAD

**Issue by mscarbor** [jtamames/SqueezeMeta#649]
Hello! 

I used sqm_longreads.pl to analyze a large time series of nanopore data.  I am using "SqueezeMeta on Long Reads v1.6.0, September 2022 - (c) J. Tamames, F. Puente-Sánchez CNB-CSIC, Madrid, SPAIN" - The SQM job finished successfully, but SQMTools does not like the LoadSQM command:

Error in loadSQM("/users/m/s/mscarbor/Peyton_Landfill_sqm_longreads/") : 
  Directory "/users/m/s/mscarbor/Peyton_Landfill_sqm_longreads/" does not seem to contain a valid SqueezeMeta project

The directory I am pointing loadSQM to contains a directory for each sample as well as:
Peyton_Landfill_sqm_longreads.out.allreads
Peyton_Landfill_sqm_longreads.out.allreads.funcog
Peyton_Landfill_sqm_longreads.out.allreads.funkegg
Peyton_Landfill_sqm_longreads.out.allreads.mcount
Peyton_Landfill_sqm_longreads.out.allreads.stats
Peyton_Landfill_sqm_longreads.out.mappingstat

Should I expect SQMTools to work with output from sqm_longreads.pl?

Thanks!

**Comment by fpusan** [comment]
Yes, but use `sqmreads2tables.py` to generate aggregated taxonomy/function tables (you can also select subsets at this stage) and then load the data into R/SQMtools with `loadSQMlite`.

**Comment by mscarbor** [comment]
Thank you!
