### ISSUE TITLE
A binning issue

### ISSUE THREAD

**Issue by blaizereal** [jtamames/SqueezeMeta#656]
At binning step 14 I experienced the following issues, checked 4-5 samples (I tried using Metabat2 and Maxbin instead of Concoct but it didn't help): 
Also manually create missing "concoct_int" subfolder did not move things forward :(
```
[30 minutes, 15 seconds]: STEP14 -> BINNING: 14.runbinning.pl
sh: 1: cannot create /media/ngs_lab/6.4Tb-NVRAM/SqueezeMeta-1.6.2/scripts/test2/intermediate/binners/concoct/concoct_int/clustering_merged.csv: Directory nonexistent
wc: /media/ngs_lab/6.4Tb-NVRAM/SqueezeMeta-1.6.2/scripts/test2/intermediate/binners/concoct/: Is a directory
wc: /media/ngs_lab/6.4Tb-NVRAM/SqueezeMeta-1.6.2/scripts/test2/intermediate/binners/metabat2/: Is a directory
[30 minutes, 45 seconds]: STEP15 -> DAS_TOOL MERGING: 15.dastool.pl
Error running command:    LD_LIBRARY_PATH=/media/ngs_lab/6.4Tb-NVRAM/SqueezeMeta-1.6.2/lib PATH=/media/ngs_lab/6.4Tb-NVRAM/SqueezeMeta-1.6.2/bin:$PATH /media/ngs_lab/6.4Tb-NVRAM/SqueezeMeta-1.6.2/bin/DAS_Tool/DAS_Tool -i  -l  -c /media/ngs_lab/6.4Tb-NVRAM/SqueezeMeta-1.6.2/scripts/test2/results/01.test2.fasta --write_bins 1 --score_threshold 0 --search_engine diamond -t 32 -o /media/ngs_lab/6.4Tb-NVRAM/SqueezeMeta-1.6.2/scripts/test2/intermediate/binners/DAS/test2 --db_directory /media/ngs_lab/6.4Tb-NVRAM/SqueezeMeta-1.6.2/DB/db at /media/ngs_lab/6.4Tb-NVRAM/SqueezeMeta-1.6.2/scripts/15.dastool.pl line 94.
mv: cannot stat '/media/ngs_lab/6.4Tb-NVRAM/SqueezeMeta-1.6.2/scripts/test2/intermediate/binners/DAS/test2_DASTool_bins/*': No such file or directory
wc: /media/ngs_lab/6.4Tb-NVRAM/SqueezeMeta-1.6.2/scripts/test2/results/bins/: Is a directory
WARNING: File /media/ngs_lab/6.4Tb-NVRAM/SqueezeMeta-1.6.2/scripts/test2/results/bins/ is empty!. DAStool did not generate results
Skipping BIN TAX ASSIGNMENT: DAS_Tool did not predict bins.
Skipping CHECKM: DAS_Tool did not predict bins.
Skipping BIN TABLE CREATION: (You already know: DAS_Tool did not predict bins.)
[30 minutes, 45 seconds]: STEP19 -> CREATING CONTIG TABLE: 19.getcontigs.pl
  Reading taxa for contigs information...done!
  Reading GC & length... done!
  Reading number of genes... done!
  Reading coverages... done!
  Reading bins... done!
  Creating contig table...done!
============
CONTIG TABLE CREATED: /media/ngs_lab/6.4Tb-NVRAM/SqueezeMeta-1.6.2/scripts/test2/results/19.test2.contigtable
============

Skipping MINPATH: DAS_Tool did not predict bins.

[30 minutes, 45 seconds]: STEP21 -> MAKING FINAL STATISTICS: 21.stats.pl
  Output in /media/ngs_lab/6.4Tb-NVRAM/SqueezeMeta-1.6.2/scripts/test2/results/21.test2.stats

Deleting temporary files in /media/ngs_lab/6.4Tb-NVRAM/SqueezeMeta-1.6.2/scripts/test2/temp
[30 minutes, 46 seconds]: FINISHED -> Have fun!

WARNINGS:
DAS Tool abnormal termination: file /media/ngs_lab/6.4Tb-NVRAM/SqueezeMeta-1.6.2/scripts/test2/results/bins/ is empty. There are NO BINS!

```
Thanks in advance for any comments! 
[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/11086761/syslog.zip)

**Comment by fpusan** [comment]
It seems DAStool had a problem.

Can you run 

`LD_LIBRARY_PATH=/media/ngs_lab/6.4Tb-NVRAM/SqueezeMeta-1.6.2/lib PATH=/media/ngs_lab/6.4Tb-NVRAM/SqueezeMeta-1.6.2/bin:$PATH /media/ngs_lab/6.4Tb-NVRAM/SqueezeMeta-1.6.2/bin/DAS_Tool/DAS_Tool -i  -l  -c /media/ngs_lab/6.4Tb-NVRAM/SqueezeMeta-1.6.2/scripts/test2/results/01.test2.fasta --write_bins 1 --score_threshold 0 --search_engine diamond -t 32 -o /media/ngs_lab/6.4Tb-NVRAM/SqueezeMeta-1.6.2/scripts/test2/intermediate/binners/DAS/test2 --db_directory /media/ngs_lab/6.4Tb-NVRAM/SqueezeMeta-1.6.2/DB/db`

and see what the error is?

**Comment by jtamames** [comment]
I think your dataset is not very big and was not able to produce any bins. Could you paste the stats in the 21.stats file? Can you try again the Hadza data?
Best,
J

**Comment by blaizereal** [comment]
> I think your dataset is not very big and was not able to produce any bins. Could you paste the stats in the 21.stats file? Can you try again the Hadza data?
> Best,
> J

Yeah, it is a smaller dataset, but I can generate visuals and tables with the SQMtools (as you can see on the attached images), so there must be something there :) Anyway, I'm going to try a species-rich sample... 

![image](https://user-images.githubusercontent.com/19901573/228223554-e6ed601d-fe0d-4591-a57a-9c156cbddb3c.png)

![image](https://user-images.githubusercontent.com/19901573/228223484-1a75a884-989c-4a80-af3b-ad102a9704c5.png)

![image](https://user-images.githubusercontent.com/19901573/228223604-04622f00-c196-4450-ac2e-b8790d090ef5.png)

**Comment by fpusan** [comment]
Thanks for the info!
I wonder why you don't have writing permissions there. Of course if you don't have writing permissions in the output directory then things are not going to work fine, but if that was the case then the pipeline would have failed before.
Can you check the owner and write permissions in `/media/ngs_lab/6.4Tb-NVRAM/SqueezeMeta-1.6.2/scripts/test2/` and its subdirectories? What kind of drive is this?

**Comment by fpusan** [comment]
Did you by any chance run some of the commands as a super-user?

**Comment by blaizereal** [comment]
> Thanks for the info!
> I wonder why you don't have writing permissions there. Of course if you don't have writing permissions in the output directory then things are not going to work fine, but if that was the case then the pipeline would have failed before.
> Can you check the owner and write permissions in `/media/ngs_lab/6.4Tb-NVRAM/SqueezeMeta-1.6.2/scripts/test2/` and its subdirectories? What kind of drive is this?

Yes, I am a superuser. The problem is that Concoct creates this folder with root permissions (check attached image), what is very interesting. Also it is a local M.2 drive, without any permission issue until now.
![image](https://user-images.githubusercontent.com/19901573/228230302-107ab3a8-d660-4f90-adcd-052f76ddacfe.png)

**Comment by blaizereal** [comment]
OK, I try running SM. as normal user. Also changing permissions Concoct intermediate stuffs to 777 resulted an empty clustering_merged.csv file, this is why bins are empty. Thanks!

**Comment by fpusan** [comment]
Just confirmed that the pipeline (including binning) works ok in a clean Ubuntu 22.04.2 VM, so the issue possibly had to do with running the pipeline as super user

**Comment by blaizereal** [comment]
Thanks for the information, be sure to further test the pipeline with your suggested user settings.
