### ISSUE TITLE
Abundance plots

### ISSUE THREAD

**Issue by phlienhart** [jtamames/SqueezeMeta#660]
Hello! I am trying to make taxonomy abundance plots of my phyla and genus data from my SQMObject. However, I want to include all the taxa that are above 0.1% abundance. How should I go about doing that? Thanks!

**Comment by fpusan** [comment]
Find which taxa are above 0.1% abundance from the `SQM$taxa$phylum$percent` and `SQM$taxa$genus$percent` using basic R. Then pass that vector to `plotTaxonomy` using the `tax` parameter.
Depending on how diverse are your samples, you may find that too many taxa are above the 0.1% abundance threshold, so the plot will be quite difficult to follow.
