### ISSUE TITLE
SqueezeMeta Step 1 Error: Failing in Megahit Assembly 

### ISSUE THREAD

**Issue by Ravi-WSU** [jtamames/SqueezeMeta#661]
Hello, I've had multiple failures at this same point. I am running 3 metagenomics samples, GRID resources are: 1 node, 14 CPUs, and 250 GB memory. I've attached an image of the megahit log where the error is. Any advice would be helpful, thank you. The error is in the 2nd image. 

![image](https://user-images.githubusercontent.com/129990174/230171013-e0b319dc-b20f-4e55-8255-bee1224a83e8.png)

![image](https://user-images.githubusercontent.com/129990174/230171201-e02f7229-7558-4e4c-a86d-82828687b92a.png)

**Comment by fpusan** [comment]
Error 172 may be due to a lack of memory according to https://github.com/voutcn/megahit/issues/282
I am however a bit surprised that this is happening to you with only three samples if you have 250 Gb available.
Does it happen if you reserve a full node instead of only 14 CPUs?

**Comment by Ravi-WSU** [comment]
Apologies, I am running a batch script that requests 14 cores on a single node with 250 GB memory. Do you mean a lack of memory in general on my directory?

**Comment by Ravi-WSU** [comment]
I've also run these exact samples before with lower memory requirements and the entire SqueezeMeta analysis has finished so I'm not sure what is causing it to stop at Megahit this time.

**Comment by fpusan** [comment]
I mean lack of RAM memory. If you are requesting only 14 cores, you may not be getting all the memory available in the node, or other processes in the node may be competing with SqueezeMeta for memory. Try reserving a full node and see if it works now.

**Comment by Ravi-WSU** [comment]
Thank you, I will give it a try and let you know how it goes.

**Comment by Ravi-WSU** [comment]
Sorry, I misspoke. I am requesting 34 cores on a single node, 14 was on my earlier attempts. However, I will still try to request the full node.

**Comment by Ravi-WSU** [comment]
Slightly unrelated question, should the value for -t be equal to the number of threads I am requesting on the GRID? Ex. if I request 34 threads, should I include -t 34 in my bash script?

**Comment by fpusan** [comment]
Yes

**Comment by Ravi-WSU** [comment]
The issues with the analysis were the result of a lack of storage space in my working directory. Everything is working smoothly now, thank you for your help, Fernando.

**Comment by fpusan** [comment]
Glad to hear! Closing issue!
