### ISSUE TITLE
Is it possible to run sqm_annot.pl with external databases?

### ISSUE THREAD

**Issue by PuspenduSardar** [jtamames/SqueezeMeta#663]
Hello!

I was wondering if there is a workaround to include external databases while using the `sqm_annot.pl` script for the functional annotation. Please note that full `SqueezeMeta.pl` is not possible, and therefore I can't use `add_database.pl` either to add the external databases later on.

Any suggestion would be very helpful!

Regards,
PS

**Comment by jtamames** [comment]
Hello
Not actually. But it would be rather easy to implement. I will look into it.
Best,
J

**Comment by PuspenduSardar** [comment]
> 

Hi @jtamames I was wondering if there are any updates on this issue?
Many thanks!

Regards,
Puspendu

**Comment by jtamames** [comment]
Hello
I couldn't work on this yet, but it is in my agenda. Thanks for remind me
Best,
J

**Comment by jtamames** [comment]
Ok, try this one. Replace your sqm_annot.pl with this one (rename the old one for not overwriting it in case this one is not working). Specify your external database as it is described in the manual for SqueezeMeta
[sqm_annot.pl.gz](https://github.com/jtamames/SqueezeMeta/files/11407034/sqm_annot.pl.gz)

**Comment by PuspenduSardar** [comment]
Thanks a lot, @jtamames 

I'll give it a try and let you know soon. Just a quick question, if I remove `--nopfam` from the script, would the PFAM db be used for the annotation?
Thank you once again!

Regards,
PS

**Comment by jtamames** [comment]
No, it will be done.
Best,
J
