### ISSUE TITLE
Could you explain 'Combining metagenomes and metatranscriptomes with SqueezeMeta' wiki more detail?

### ISSUE THREAD

**Issue by Lafmas** [jtamames/SqueezeMeta#664]
Hello

I will be examining metagenome and metatranscriptome data using two different approaches. The first method involves analyzing metagenome and metatranscriptome data independently. The second method involves using the metagenome data as a reference to analyze the metatranscriptome data. 

While researching how to combine these two types of data using SqueezeMeta, I came across its wiki page. 

However, I'm still unsure of how to proceed. Can you suggest a way for me to effectively combine and analyze the metagenome and metatranscriptome data?

Best
Lafmas

**Comment by jtamames** [comment]
Hello
Please read carefully the wiki document. There I explain how to do it, put an example of a possible samples file, and provide the command to run the pipeline.
Best,
J
