### ISSUE TITLE
Error in LoadSQM

### ISSUE THREAD

**Issue by afsanarupa** [jtamames/SqueezeMeta#667]
Hi, I have recently updated R packages which automatically updated SQMtools. After that I'm having this issue. I have tried 19.getcontigs /media/bioinfo/hdd2/Metagenome_jute/metagenom_run_final. I also tried to remove and downgrade the package using "remove.packages("SQMtools")" and "install.packages("SQMtools", version = "0.7.1", repos = "http://cran.us.r-project.org")" but I end up getting version 1.6.2. 

met_jute  = loadSQM('/media/bioinfo/hdd2/Metagenome_jute/metagenom_run_final', engine = 'data.table')
Loading total reads
Loading orfs
    table...
|--------------------------------------------------|
|==================================================|
    abundances...
    sequences...
|--------------------------------------------------|
|==================================================|
    taxonomy...
|--------------------------------------------------|
|==================================================|
Loading contigs
    table...
|--------------------------------------------------|
|==================================================|
    abundances...
Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent
In addition: Warning message:
In loadSQM("/media/bioinfo/hdd2/Metagenome_jute/metagenom_run_final",  :
  Your project was created with SqueezeMeta v1.5, while this is SQMtools v1.6.2. You can ignore this message if things are working fine for you, but if you experience any issue consider using the right version of SQMtools for this project

**Comment by fpusan** [comment]
Hi!
Yes, you can fix it by activating the SqueezeMeta environment and running `19.getcontigs.pl /path/to/project`.
Afterwards the project should load correctly in SQMtools v1.6.2.

**Comment by afsanarupa** [comment]
Hi, I have done that but i'm still getting the same error in R.

**Comment by fpusan** [comment]
Ah yes, I didn't read your first message correctly.
Then you will need to install the latest version of SqueezeMeta in a different environment, activate it and then run the new version of script 19.

**Comment by fpusan** [comment]
(here I am assuming that you ran the script without previously updating your SqueezeMeta version, correct me otherwise)

**Comment by afsanarupa** [comment]
Hi, Thanks. It worked after I ran 19.getcontigs.pl after downloading new version of SqueezeMeta in a different envrionment.
