### ISSUE TITLE
Step 4 Error - Running Diamond

### ISSUE THREAD

**Issue by Ravi-WSU** [jtamames/SqueezeMeta#672]
Hello,
I'm getting an error message in step 4, I'm not sure what to do so I was hoping you could help. This analysis was running on the GRID utilizing 1 node, 15 cpus, and 700 GB memory. I've attached the image of the output file below and the syslog is also attached. 

[syslog.txt](https://github.com/jtamames/SqueezeMeta/files/11311765/syslog.txt)

![image](https://user-images.githubusercontent.com/129990174/234034747-41599f90-6da4-466a-ae73-4983ba5584fa.png)

**Comment by fpusan** [comment]
Can you share the `/nfs/prb/Gut_metagenomics_7202/Renamed/SQM_PE_Subset/temp/diamond.nr.log` file with us?

**Comment by Ravi-WSU** [comment]
Hello Fernando, the file is attached.

[diamond.nr.log](https://github.com/jtamames/SqueezeMeta/files/11311838/diamond.nr.log)

**Comment by fpusan** [comment]
Ok, so you have the following error

```
Computing alignments... terminate called after throwing an instance of 'std::runtime_error'
  what():  Format error: Invalid varint encoding.
```
Apparently this has been fixed in the latest version of DIAMOND as per https://github.com/bbuchfink/diamond/issues/653

So you would need to do the following:

1) Download the latest DIAMOND release (linux 64) from their github repo.
2) Uncompress and get the new `diamond` executable. Copy it to `/wsu/home/fw/fw43/fw4347/.conda/envs/SqueezeMeta/SqueezeMeta/bin/diamond` in order to replace the old executable that we redistribute with SqueezeMeta.
3) Restart the pipeline with the `--restart` flag (it should automatically re-attempt from the failed step).

**Comment by Ravi-WSU** [comment]
That seemed to work, the run has restarted properly. Thanks for your help, Fernando.

**Comment by fpusan** [comment]
Ok, but let's wait until it finishes before celebrating. Please let me know when/if finishes correctly.
If it works, then I will add the new DIAMOND version to SqueezeMeta.

**Comment by Ravi-WSU** [comment]
I guess I got a little too excited! However, it failed again at the same step. The output image is below and the diamond log is also attached.

[diamond.nr.log](https://github.com/jtamames/SqueezeMeta/files/11312764/diamond.nr.log)

![image](https://user-images.githubusercontent.com/129990174/234062688-88ee00e8-2ef1-4f6f-9e2b-f3b9d58ce31d.png)

**Comment by Ravi-WSU** [comment]
I changed the $blocksize variable and restarted the run, will let you know if anything else comes up.

**Comment by Ravi-WSU** [comment]
> Ok, but let's wait until it finishes before celebrating. Please let me know when/if finishes correctly. If it works, then I will add the new DIAMOND version to SqueezeMeta.

Hello, this run has finally been completed and the update to the new version of Diamond was successful. Thank you for all your help Fernando.

**Comment by fpusan** [comment]
It took two weeks to complete? wow. To be fair the blocksize 1 makes thing much slower

**Comment by Ravi-WSU** [comment]
It had stopped on me a few times in the process so I had to restart, so it wasn't two weeks entirely. It actually made it past Diamond fairly quick, but some other steps took time.

**Comment by fpusan** [comment]
Ah ok! Then I don't think the new DIAMOND version made the trick. Rather, in this case what helped was lowering the blocksize.
Anyways, glad to hear it worked eventually!
