### ISSUE TITLE
No DAS directory

### ISSUE THREAD

**Issue by weishwu** [jtamames/SqueezeMeta#673]
The manual says there is a `results/DAS` directory that contains the DAS_tool bins. However my `results/` dir has only `bins/` and the file names under it all say **concoct** (e.g. *concoct.14.fa.contigs.fa.tax*).
And the folder `intermediate/binners/DAS/mock_DASTool_bins/` is empty.
However, the **Method** column in *18.mock.bintable* says **DAS** in all rows.

The "syslog" file is attached.

My command-line:
```
SqueezeMeta.pl \
        -m coassembly \
        --cleaning \
        --doublepass \
        -p {params.project_name} \
        -s {input.sample_file} \
        -f {params.read_dir} \
        -t {threads}
```

[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/11316113/syslog.zip)

**Comment by jtamames** [comment]
Hello
Yes, originally there was a DAS directory in results. But all the binning was restructured in recent versions and now the bins are stored in the bins directory. I will correct that in the manual.
The name of the bins indicate the program that originally created them (concoct in your case). DasTool then combines these bins, that is why the method in 18 is DAS. Thus, all is correct in your project.
Best,
J

**Comment by weishwu** [comment]
Hi @jtamames,
Thanks for the quick reply!
Although the file names only have "concoct", they are actually a combination of Metabat2 and Concoct results by DAS, right? I see the DAS command-line in syslog is
```
DAS_Tool \
-i intermediate/binners/DAS/concoct.table,intermediate/binners/DAS/metabat2.table \
-l concoct,metabat2 \
-c results/01.mock.fasta \
--write_bins 1 \
--score_threshold 0 \
--search_engine diamond \
-t 40 -o intermediate/binners/DAS/mock \
--db_directory /usr/share/squeezemeta_dbs/db
```

**Comment by fpusan** [comment]
Hi! If the file names only have concoct then it means that DAStool selected only CONCOCT bins in its "best bit" set.
This can be normal, as from your syslog I see that metabat2 apparently ran without issues.
However the latest version (v1.6.2) of SqueezeMeta includes improvements on how metabat2 is called, so if you are using an earlier version it may be worth it to update it and re-run your project.
