### ISSUE TITLE
Missing python library "pysam"

### ISSUE THREAD

**Issue by fpusan** [jtamames/SqueezeMeta#677]
Hi!
I'm getting this warning after running the test_install.pl script:

WARNING: Some SqueezeMeta dependencies could not be found in your environment!
	- Missing python library "pysam"

Could somebody help me? Thanks in advanced!

_Originally posted by @emagallong in https://github.com/jtamames/SqueezeMeta/issues/258#issuecomment-1533388417_

**Comment by emagallong** [comment]
Thanks, for your quick response!!
Yes, I used conda and I'm on the SqueezeMeta environment...

**Comment by fpusan** [comment]
pysam should be present in that environment.
What is the output of `which python`?

**Comment by fpusan** [comment]
Ok then it is a bit weird, it should be present.
What happens if you manually install it with `mamba install -c bioconda pysam`

**Comment by emagallong** [comment]
This is the output:
Looking for: ['pysam']

warning  libmamba Could not parse state fileCould not load cache state: [json.exception.type_error.302] type must be number, but is null
warning  libmamba Could not parse state fileCould not load cache state: [json.exception.type_error.302] type must be number, but is null
warning  libmamba Could not parse state fileCould not load cache state: [json.exception.type_error.302] type must be number, but is null
warning  libmamba Could not parse state fileCould not load cache state: [json.exception.type_error.302] type must be number, but is null
warning  libmamba Could not parse state fileCould not load cache state: [json.exception.type_error.302] type must be number, but is null
warning  libmamba Could not parse state fileCould not load cache state: [json.exception.type_error.302] type must be number, but is null
warning  libmamba Could not parse state fileCould not load cache state: [json.exception.type_error.302] type must be number, but is null
warning  libmamba Could not parse state fileCould not load cache state: [json.exception.type_error.302] type must be number, but is null
bioconda/noarch                                      4.2MB @   3.8MB/s  1.7s
bioconda/linux-64                                    4.6MB @   2.8MB/s  2.4s
pkgs/main/linux-64                                   5.6MB @   2.3MB/s  3.6s
pkgs/r/linux-64                                      1.4MB @ 384.1kB/s  1.4s
pkgs/main/noarch                                   822.9kB @ 209.5kB/s  2.8s
pkgs/r/noarch                                        1.3MB @ 312.4kB/s  2.5s
r/linux-64                                         770.6kB @ 183.4kB/s  0.5s
r/noarch                                           864.2kB @ 201.3kB/s  0.6s
conda-forge/noarch                                  12.1MB @   2.7MB/s  6.7s
conda-forge/linux-64                                31.2MB @   3.0MB/s 16.0s

Pinned packages:
  - python 3.6.*


Transaction

  Prefix: /home/usuario/miniconda3/envs/SqueezeMeta

  All requested packages already installed

**Comment by emagallong** [comment]
I already run the test_install.pl and I got the same issue...

**Comment by fpusan** [comment]
So it thinks it is already installed (also there is something weird going on with your conda)
What happens if you open python and type `import pysam`?

**Comment by fpusan** [comment]
Also what is the output of `which python3` (note that now there is a 3 in the end)

**Comment by emagallong** [comment]
This is the output for `which python3` : /home/usuario/miniconda3/envs/SqueezeMeta/bin/python3
This is the output for `import pysam` :

Python 3.6.15 | packaged by conda-forge | (default, Dec  3 2021, 18:49:41) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysam
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/usuario/miniconda3/envs/SqueezeMeta/lib/python3.6/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: libhts.so.2: cannot open shared object file: No such file or directory

**Comment by fpusan** [comment]
Ok, pysam itself is installed, but it is missing a dependency.

I see that pysam was recently updated in bioconda, apparently this broke our package. I expect this to keep happening in the future, so I will look into pinning package versions as suggested to me in #638. I am afraid that not allowing conda to solve packages on its own may also be problematic in a different way, but I'll see what I find out.

In any case, I just made a new release that fixes this particular issue. You will need to reinstall SqueezeMeta, then `pysam` and `test_install.pl` will hopefully work. Let me know what happens.

**Comment by emagallong** [comment]
Ok, I'll try and I'll keep you posted!
Thanks ;)

**Comment by emagallong** [comment]
So far, everything is running pretty good. The issue was fixed.
Thanks a lot, Fernando! I'm excited to run SqueezeMeta!

**Comment by fpusan** [comment]
Excellent! Good luck with your analyses, you know where to find us
