### ISSUE TITLE
Stopped in Step 20

### ISSUE THREAD

**Issue by Ravi-WSU** [jtamames/SqueezeMeta#681]
Hello, 

My SqueezeMeta analysis stopped in Step 20, I'm not sure what to do about this. I've attached the output file from my GRID job and the syslog file below.
Thanks.

Best, 
Ravi

[syslog.gz](https://github.com/jtamames/SqueezeMeta/files/11413101/syslog.gz)
[output_19778773.out.gz](https://github.com/jtamames/SqueezeMeta/files/11413102/output_19778773.out.gz)

**Comment by Ravi-WSU** [comment]
This is the ending of the output file, I know the log itself is quite long.
Thank you.

![image](https://user-images.githubusercontent.com/129990174/236879735-caee5c44-d467-4468-abfe-ad7421806583.png)

**Comment by jtamames** [comment]
Probably your bins are too small. Run the final step 21 and ignore this error: `21.stats.pl SQM_PE_Subset`

**Comment by Ravi-WSU** [comment]
For restarting, would I do SqueezeMeta.pl -p SQM_PE_Subset --restart -step 21?

**Comment by Ravi-WSU** [comment]
Run is completed, thank you again.
