### ISSUE TITLE
Error in dimnames(x) in loadSQM 

### ISSUE THREAD

**Issue by henslerk** [jtamames/SqueezeMeta#685]
Initially, the project would not load due to significant differences in the versions used to run and my SQMtools (the original project was run with v1.3 ) ... I applied versionchange.pl , and the project loaded in R; however, with an error not seen before regarding the dimensions. Now, when I try to make a table with the SQM object (named "test"), it says : Error: object 'test' not found ... 

`> test <- loadSQM("/data/mcm/khensler/jrivas/MP0311/", engine = 'data.table')
Loading total reads;
Loading orfs;
    table...
    abundances...
    sequences...
    taxonomy...
Loading contigs
    table...
    abundances...
Error in dimnames(x) <- dn :
  length of 'dimnames' [1] not equal to array extent
In addition: Warning message:
In loadSQM("/data/mcm/khensler/jrivas/MP0311/", engine = "data.table") :
  Your project was created with SqueezeMeta v1.5, while this is SQMtools v1.6.2. You can ignore this message if things are working fine for you, but if you experience any issue consider using the right version of SQMtools for this project`

**Comment by fpusan** [comment]
Hi!
Looks similar to #577 and #667

**Comment by henslerk** [comment]
Thank you!
