### ISSUE TITLE
Would you change README.md?

### ISSUE THREAD

**Issue by Lafmas** [jtamames/SqueezeMeta#687]
Hello,

Thank you for developing the tool Squeezemeta. I have a minor issue to address (it is a very minor one).

It would be greatly appreciated if you could kindly update the description of the "force_overwrite" section in the "restart" chapter of the README.md file on the main page of the Github repository.

Currently, the suggested command is listed as `force-overwrite`, but it seems that the correct command that actually works is `force_overwrite`.

Thank you very much for your attention and assistance. Your efforts are greatly appreciated.

Best,
Lafmas

![image](https://github.com/jtamames/SqueezeMeta/assets/120089405/0b10b76d-0bae-455f-9b88-7eef52154095)

**Comment by fpusan** [comment]
Done, thanks for reporting!
