### ISSUE TITLE
TPM count

### ISSUE THREAD

**Issue by aalkin2001** [jtamames/SqueezeMeta#690]
Hi Javier,
I  realized you used TPM (Transcript Per Million) as the count for the abundance of each KEGG function, but I'm confused here because we are dealing with the Whole Genome Metagenome Sequence data, which is DNA data, not RNA seq. From my understanding, TPM is used for normalization in RNA seq. Could you please explain the basics of using TPM in Metagenomic functional analysis? The Hadza KEGG functional analysis is an example of what I am talking about. (See attached).

![KEGG_Fun_TPM](https://github.com/jtamames/SqueezeMeta/assets/30750268/07d367c5-fa8e-493a-a6c1-5fcf2c0560b4)

**Comment by fpusan** [comment]
Hi!
TPM can also be used for metagenomics datasets.
See #62 and [the SQMtools paper](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-020-03703-2).
