### ISSUE TITLE
LCA_tax/taxid.db not present

### ISSUE THREAD

**Issue by lilyyycao** [jtamames/SqueezeMeta#691]
Hello,

I am trying to download the databases using the download_databases.pl command and come across the following error:

WARNING: Some SqueezeMeta dependencies could not be found in your environment!
The LCA_tax/taxid.db database is not present in /gpfs/scratch/lyc5319/SqueezeMetaDatabase/db, it is malformed, or there is other problem with your SQLite configuration

I found a few issues bringing up similar errors but was not sure if there was solution to download this missing database.

This is so far what has been downloaded in my db folder.

![image](https://github.com/jtamames/SqueezeMeta/assets/99231558/607a7382-cf07-4a68-ac4d-76052f6098a0)

Thank you!

**Comment by lilyyycao** [comment]
Hello, thank you for your response. I had tried downloading via all 3 methods listed (download, make, and make.alt) but still have consistently run across the same error. All of my files are being saved onto a cluster server and should have plenty of disk space, but it seems to consistently have errors here. I am running this on UBUNTU 22.04.2 and I am mainly looking to take some assemblies I had previously made and use SqueezeMeta to annotate them against the pfam, nr, and kegg databases. I also want to ask if the other files in my db folder look are look fully downloaded and configured and it is just the this one that is an issue. Thank you

**Comment by fpusan** [comment]
Hi!
That is unfortunate, I am now trying to download the databases myself to see if I run into the same error.
Meanwhile can you download directly from here?
http://andes.cnb.csic.es/SqueezeMeta/SqueezeMetaDB.md5
http://andes.cnb.csic.es/SqueezeMeta/SqueezeMetaDB.tar.gz
The md5sum of `SqueezeMetaDB.tar.gz` should be the same as stated in the `SqueezeMetaDB.md5` file.
If this works for you then uncompress the `SqueezeMetaDB.tar.gz` file.
You should get a directory named `db`.
Then you can call `configure_nodb.pl /path/to/db` and it should set things up for you.

**Comment by fpusan** [comment]
Hi again. Just confirming that I managed to successfully run `download_databases.pl` from my workstation in Sweden and it still works ok, so the problem may be related to your conexion/system.
Let me know whether the manual download works
