### ISSUE TITLE
Bin issue with metabat2

### ISSUE THREAD

**Issue by XC-Zhai** [jtamames/SqueezeMeta#692]
Thanks for this nice pipeline with conda env, I had an issue when I run SqueezeMeta v1.6.2, where there are missing library (/lib64/libstdc++.so.6). The test_install.pl didn't give me any error. 

I am using:
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

It would be great to guide me how to solve this
Thanks in advance.

[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/11622041/syslog.zip)

**Comment by fpusan** [comment]
Hi!
CentOS7 is no longer oficially supported since v1.6.2, since some of it's system libraries are too old.
A possible fix would be to run `mamba install -c anaconda libstdcxx-ng` inside the SqueezeMeta environment.
Alternatively, you can recompile `metabat2` and `jgi_summarize_bam_contig_depths` as described in #684

**Comment by XC-Zhai** [comment]
> Hi! CentOS7 is no longer oficially supported since v1.6.2, since some of it's system libraries are too old. A possible fix would be to run `mamba install -c anaconda libstdcxx-ng` inside the SqueezeMeta environment. Alternatively, you can recompile `metabat2` and `jgi_summarize_bam_contig_depths` as described in #684

Thanks a lot.  We are having metabat2 installed at our cluster for anyone to use by using "module load metabat/2.12.1", I am wondering if I can make a link to this and rerun from step14? Or I can run this separately  and restart from next step?

Best,
Xichuan

**Comment by fpusan** [comment]
It may work.
What I would do then would be to copy the `metabat2` and `jgi_summarize_bam_contig_depths` to the `/home/projects/cu_10168/people/xiczha/SqueezeMeta/bin` directory.
You can locate the scripts with `which metabat2` and `which jgi_summarize_bam_contig_depths` after loading the metabat module.

**Comment by XC-Zhai** [comment]
> It may work. What I would do then would be to copy the `metabat2` and `jgi_summarize_bam_contig_depths` to the `/home/projects/cu_10168/people/xiczha/SqueezeMeta/bin` directory. You can locate the scripts with `which metabat2` and `which jgi_summarize_bam_contig_depths` after loading the metabat module.

Yes, it worked with the copy-paste method with --restart  --force_overwrite for the project already finished from step 14 .
And all the further steps could be finished. I had issue with SQM R package, where the data could be loaded and some plot could be generated according to tutorial:https://github.com/jtamames/SqueezeMeta/wiki/Using-R-to-analyze-your-SQM-results.

But I got error when it came to subsetTax: 
archaea=subsetTax(cow_meta,'superkingdom',tax='Archaea',rescale_copy_number=F)
**Error in subSQM$bins$tax[bins, , drop = FALSE] : subscript out of bounds**

I compared the project from 1st finished and current one and found that there are still something keeping even using --force_overwrite, is this parameter means will remove everything from restart step and write new output?
Thanks for your guides.

Best,
Xichuan

**Comment by XC-Zhai** [comment]
> > It may work. What I would do then would be to copy the `metabat2` and `jgi_summarize_bam_contig_depths` to the `/home/projects/cu_10168/people/xiczha/SqueezeMeta/bin` directory. You can locate the scripts with `which metabat2` and `which jgi_summarize_bam_contig_depths` after loading the metabat module.
> 
> Yes, it worked with the copy-paste method: --restart --force_overwrite for the project already finished from step 14 . And all the further steps could be finished. I had issue with SQM R package, where the data could be loaded and some plot could be generated according to tutorial:https://github.com/jtamames/SqueezeMeta/wiki/Using-R-to-analyze-your-SQM-results.
> 
> But I got error when it came to subsetTax: archaea=subsetTax(cow_meta,'superkingdom',tax='Archaea',rescale_copy_number=F) **Error in subSQM$bins$tax[bins, , drop = FALSE] : subscript out of bounds**
> 
> I compared the project from 1st finished and current one and found that there are still something keeping even using --force_overwrite, is this parameter means will remove everything from restart step and write new output? Thanks for your guides.
> 
> Best, Xichuan

Seems like I solved it by using #243 .

**Comment by fpusan** [comment]
Glad to hear everything work out. Closing issue.
For reference, as of now `--force_overwrite` will overwrite results, but not remove the previous ones.
