### ISSUE TITLE
Squeezemeta warning for STEP15

### ISSUE THREAD

**Issue by sarpiens** [jtamames/SqueezeMeta#693]
Hello,

We were using the squeezemeta pipeline(squeezemeta1.6.2post1) with a set of metatranscriptomic samples, using the following parameters: -m coassembly, -a rnaspades --nobins -t 16 -b 25 

However, despite de fact that tables were generated we found and errorr regarding "STEP15 -> DAS_TOOL MERGING: 15.dastool.pl":

![warning_squeezemeta](https://github.com/jtamames/SqueezeMeta/assets/49655743/8d50cda6-bcc8-477f-9f7b-f7abb12f85d0)

In'm wondering if it is okey to continue because the warning makes sense since we used the option --nobins. Is it okey to continue or should we adjust some parameters?

Thanks in advance. 
Best regards.

**Comment by fpusan** [comment]
It is fine to continue, I think. But if you added `--nobins` then it shouldn't have attempted binning in the first place.
What version are you using?

**Comment by jtamames** [comment]
Hello
Yes, it is ok to continue. Did you see any messages regarding step 14 (binning)? Could you send the syslog file to us?
Best,
J

**Comment by sarpiens** [comment]
Hi again, we used squeezemeta1.6.2post1 in a conda env. We did not see any messages regarding step 14. 

I attach the log file of the run: 
[squeezemeta_Alicia_MTT_coassembly.log](https://github.com/jtamames/SqueezeMeta/files/11651581/squeezemeta_Alicia_MTT_coassembly.log)

Thanks in advance. 
Best, Sam

**Comment by jtamames** [comment]
Hello Sam
Oh yes, there is a misplaced bracket in the SqueezeMeta.pl script causing this. My bad. I will correct it asap. But it does not have any influence in your results, which you can trust fully.
Thanks for reporting!

Best,
J
