### ISSUE TITLE
Determining the abundance of bins

### ISSUE THREAD

**Issue by mradz19** [jtamames/SqueezeMeta#698]
How do I go about determining the abundance if bins within samples? I've seen online that some programs calculate this but from what I can see in the bin table it only gives you coverage and TPM stats for the bins per sample.

**Comment by fpusan** [comment]
You can do this within SQMtools.
Once you load your project as a SQM project, you can find different matrices within `SQM$bins`.
E.g. `SQM$bins$percent` will contain the percentage of reads assigned to each bin in each sample.
I personally like to use `cpm` (coverage per million reads) to track the abundance of bins.
We also have a `plotBins` function, similar to `plotTaxonomy`, to quickly make barplots with the abundance of the most abundant bins in each sample.
