### ISSUE TITLE
sqm2anvio.pl: error in subprocesses line 100

### ISSUE THREAD

**Issue by nebfold** [jtamames/SqueezeMeta#70]
Hi,

Sorry for spamming your issues lately 😄 

I'm trying to load my results into `anvi'o` (I did just have to be patient #69). Before I run `anti-load-sqm.py` I need to run `sqm2anvio.pl`:

```
$ sqm2anvio.pl depression anvio_sqm2anvio/
======== sqm2anvio.pl, v1.1 ========
Error running subprocess: /home/ben/.conda/envs/SqueezeMeta/bin/../utils/sqm2tables.py depression anvio_sqm2anvio/ --sqm2anvio at /home/ben/.conda/envs/SqueezeMeta/bin/sqm2anvio.pl line 100.
```

I looked at line 100 of `sqm2anvio.pl` and ran the `sqm2tables.py` command manually, which runs fine:

```
~/.conda/envs/SqueezeMeta/SqueezeMeta/utils/sqm2tables.py depression anvio_manual/ --sqm2anvio
```

Comparing the output:

```
$ ls anvio_manual/
depression.contig.tax.tsv  depression.orf.tax.allfilter.tsv
$ ls anvio_sqm2anvio
bam  depression_anvio_genes.txt  depression_anvio_SQMequivalence.txt
```

Thanks,
Ben

**Comment by nebfold** [comment]
I think I traced the problem to the `$installpath` in line 36 of [`sqm2anvio.pl`](https://github.com/jtamames/SqueezeMeta/blob/master/utils/anvio_utils/sqm2anvio.pl)

On my local version of SqueezeMeta, line 36 of `sqm2anvio.pl` is:

```
our $installpath = "$scriptdir/..";
```

This resolves to `/home/ben/.conda/envs/SqueezeMeta/`:

```
(SqueezeMeta) [ben@asclepius pilot_metagenomic_run]$ which sqm2anvio.pl
~/.conda/envs/SqueezeMeta/bin/sqm2anvio.pl
```

In line 3 of `SqueezeMeta_conf.pl` inside the project directory:

```
$installpath = "/home/ben/.conda/envs/SqueezeMeta/SqueezeMeta";
```

I updated `$installpath` in `sqm2anvio.pl` to match `SqueezeMeta_conf.pl` and everything seems to be working. I installed `SqueezeMeta` with the experimental conda release, and this might have caused the issue (I can see the version on the repository has been updated).

**Comment by fpusan** [comment]
Glad you managed to solve it!

It might be a versioning issue, yes. I tested that part last week in preparation for releasing a new version of SqueezeMeta, and it worked fine with the latest code...

**Comment by yjiakang** [comment]
@nebfold @fpusan Hello, in you comments: "I updated $installpath in sqm2anvio.pl to match SqueezeMeta_conf.pl and everything seems to be working." Do you mean change the line 36 of sqm2anvio.pl to `$installpath = "/home/ben/.conda/envs/SqueezeMeta/SqueezeMeta" ` I met the same problem as yours, and I changed the line 36 of sqm2anvio.pl to the same as line 3 of SqueezeMeta_conf.pl inside my project. 
However, when I reran the `anvi-load-sqm.py` as follows:
` (anvio-6.2) [jkyin@sg15 squeezemeta]$  python3 ~/miniconda2/envs/SqueezeMeta/bin/anvi-load-sqm.py -p PZH -o PZH/results/anvio --num-threads 12 --min-contig-length 2500 --run-scg-taxonomy --run-HMMS`
The same error I got:
PZH/results/sqm2anvio does not exist
Create sqm2anvio directory with all the input files for anvi'o
======== sqm2anvio.pl, v1.1 ========
Error running subprocess: /public/home/jkyin/miniconda2/envs/SqueezeMeta/SqueezeMeta/utils/sqm2tables.py PZH PZH/results/sqm2anvio --sqm2anvio at /public/home/jkyin/miniconda2/envs/SqueezeMeta/SqueezeMeta/utils/anvio_utils/sqm2anvio.pl line 100.
There must be some problem with "/public/home/jkyin/miniconda2/envs/SqueezeMeta/SqueezeMeta/utils/anvio_utils/sqm2anvio.pl PZH PZH/results/sqm2anvio".
It's better to stop and check it
Do you have any ideas about it? Thanks in advance.

**Comment by nebfold** [comment]
@yjiakang Yes, I changed line 36 to fix my error. You'll get a more descriptive error message if you run the command producing the error manually:

```
/public/home/jkyin/miniconda2/envs/SqueezeMeta/SqueezeMeta/utils/sqm2tables.py PZH PZH/results/sqm2anvio --sqm2anvio
```

Also, when I installed SqueezeMeta in a new conda environment (v1.1) the issue went away.
