### ISSUE TITLE
Error in Spades assembly (ver1.6.2 post3)

### ISSUE THREAD

**Issue by RIJP-SU** [jtamames/SqueezeMeta#709]
Hi, I updated SqueezeMeta so that Spades assembly can work.
The newest version of SqueezeMeata (v1.6.2post3) indeed started Spades assembly normally but finished abnormally.
Running Spades alone in conda environment generated error so problem would be on Spades.

Even same version of Spades (3.15.5), running in native environment finished normmaly.

I am attaching spades.log both from conda environment (with error) and naitive environment (normmaly finished).
One difference between conda and naitve environment is version of python, would it be a problem?
Any solution would be appreciated.

[(conda)spades.log](https://github.com/jtamames/SqueezeMeta/files/12035737/conda.spades.log)

[(native) spades.log](https://github.com/jtamames/SqueezeMeta/files/12035744/native.spades.log)

**Comment by fpusan** [comment]
Also how are you installing SPAdes in the "native environment" exactly? Are you compiling from source or using the pre-compiled binaries?

**Comment by RIJP-SU** [comment]
Thanks fpusan,
My OS is Ubuntu 20.04LTS. As same as #1094, I've got "OS return value: -11".
So is this OS dependent problem and is not able to solve so far?

I could proceed next step by manually add contig file to result directory. Is this ok?

I installed Spades by conda, "naitive environement" means "base" environment. Sorry for cofusion.

**Comment by fpusan** [comment]
Weird, I also have Ubuntu 20.04 LTS.
What's the output of `uname -a`?

**Comment by RIJP-SU** [comment]
Sorry what does "uname -a" mean?

**Comment by RIJP-SU** [comment]
Thanks, output of uname -a is follows.
Linux "username" 5.15.0-76-generic #83~20.04.1-Ubuntu SMP Wed Jun 21 20:23:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Regarding
SqueezeMeta.pl -m coassembly -p Hadza2 --extassembly spades_assembly.fasta -f /your/raw/dir -s your.samples -contigid spades

Is "spades_assembly.fasta" name of contig file generated by Spada?

**Comment by fpusan** [comment]
> Is "spades_assembly.fasta" name of contig file generated by Spada?

Yes

**Comment by RIJP-SU** [comment]
I changed path to Spades in SqueezeMeta_conf.pl from
"$installpath/bin/SPAdes/spades.py"
to
"/path/to/minoconda3/bin/spades.py" <-installed via conda to base environment

Then, it worked fine. Thanks.

**Comment by fpusan** [comment]
Glad to hear it works, that's a good workaround. I am trying to find a more permanent solution to some binaries (mainly SPAdes and metabat) not working for some distros/versions... hopefully I'll get this done by the next version. Closing issue, feel free to reopen if needed.
