### ISSUE TITLE
Step6 LCA is quite long

### ISSUE THREAD

**Issue by emilievillar** [jtamames/SqueezeMeta#71]
Hi, 
I used SqueezeMeta step by step on a cluster on 12 libraries. Co-assembly with Megahit took around 22 hours on my cluster, but the lca step seems infinite. I got some results but the process is really long. 
There is 3 G contigs in the co-assembly. The entry file 04.myprojet.nr.diamond is 5.5Gb. Did I do something wrong? Is there a way to parallelize this step (easily)? 
Anyway, thank you so much fr this very useful pipeline!
Many thanks for your help,

**Comment by fpusan** [comment]
Hi! Infinite is perhaps a strong word, but step 6 can indeed take a lot of time :)
I don't think you did anything wrong, and I would not worry unless it really stalls from some days.

It should not be very difficult to parallelize, we'll consider doing that in the future. However the script is also I/O intensive, so parallelization might not help that much.

Just out of curiosity, is the process sitting at 100% CPU usage?

**Comment by jtamames** [comment]
Hi
Please tell us also how many genes do you have. Recent versions of SQM give this number in the trace output, if you don´t find it just count the ">" lines in 03.<project>.faa file in the results dir:

`grep -c ">" 03.<project>.faa`

Thanks!

**Comment by emilievillar** [comment]
Hi 
Thank you for your support, I got 5M ORFs predicted (sorry I would say 3M contigs in the assembly yesterday). CPU usage is near 1% o_O.
For now the script runs for 24h and only 400,000 ORFs have been treated. But, it's OK, if it's normal, I'll wait! I was just wondering if I got a problem as I am running the scripts step by step.

**Comment by fpusan** [comment]
If CPU usage is that low I suspect that the blame is not CPU but I/O.
Are the SqueezeMeta databases in a shared disk experiencing a lot of activity?

**Comment by emilievillar** [comment]
Yes, we've got frequently that kind of problem with our cluster :( Let's wait!
Thank you for your help!

**Comment by jtamames** [comment]
Oh yes, that is pretty slow, usually it should do at least 200.000 ORFs per hour... Maybe there is something related to disk I/O? What kind of disks do you have?

**Comment by emilievillar** [comment]
OK, thank you for the range. I will switch the computation on another disk, with high I/O efficiency.
