### ISSUE TITLE
KEGG database 

### ISSUE THREAD

**Issue by alicegrih** [jtamames/SqueezeMeta#711]
Hi jtamames,

I used Squeezemeta to work with metatranscriptomic data and I followed the tutorial for data visualisation in Rstudio and I would like to ask 2 questions:

The first is that with the exportTable() function, I was able to download a database of KOs coming from the KEGG database, I would like to know if that table that I was able to download are only the KOs that were found in my samples or it is a direct database from KEGG and contains all the KOs registered in it.

And the second one is if you have any code where I can get all the KOs associated to a specific metabolic pathway, because I would like to know if I can perform an ORA and a GSEA, with the data I have. 

Thank you, 
Best regards.

**Comment by fpusan** [comment]
Hi,

1) Hard to answer without knowing what what code did you exactly use. Probably all the KOs found in your samples.

2) See the code below

```
SQM.pwy = subsetFun(SQM, my_metabolic_pathway, columns="KEGGPATH") # create a subset containing only ORFs affiliated to the requested pathway
# `my_metabolic_pathway` can be a substring (no need to have the full pathway name though it will ofc be more specific
# `my_metabolic_pathway` can also be a regexp for more elaborate search patterns

rownames(SQM.pwy$functions$KEGG$abund) # All the KOs from the pathway

# Alternatively
exportPathway(SQM, pathway_id) # to export directly the KEGG map colouring the present reactions
# see the documentation for `subsetFun` and `exportPathway` for more usage details
```
```

**Comment by alicegrih** [comment]
Hi, 

I appreciate your help.

Best regrets.

**Comment by fpusan** [comment]
> Best regrets.

Ominous!
Closing the issue, let me know if you need further help :)
