### ISSUE TITLE
restart

### ISSUE THREAD

**Issue by HannahBenisty** [jtamames/SqueezeMeta#713]
Hi!

I am trying to use --restart with: 
SqueezeMeta.pl --restart -p obs_09 -step 6 

but I get the following error:
Can't open samples file (-s) in obs_09/data/00..samples. Please check that it is the correct file
squeezemeta.e90917011 (END)

Do you know if there is anything I need to change in the files before trying to restart?

Thanks!

**Comment by jtamames** [comment]
Are you in the directory in which you run the project for first time?

**Comment by HannahBenisty** [comment]
Yes. And the sample file indicated by the error looks fine to me.
Can't open samples file (-s) in obs_09/data/00..samples.

**Comment by HannahBenisty** [comment]
[13 hours, 35 minutes, 34 seconds]: STEP2 -> 02.rnas.pl

[13 hours, 53 minutes, 56 seconds]: STEP3 -> 03.run_prodigal.pl

[15 hours, 40 minutes, 4 seconds]: STEP4 -> 04.rundiamond.pl

[2 days, 0 hours, 23 minutes, 58 seconds]: STEP5 -> 05.run_hmmer.pl

[2 days, 20 hours, 42 minutes, 16 seconds]: STEP6 -> 06.lca.pl
syslog (END)

**Comment by jtamames** [comment]
No, I mean the syslog file you will find in the obs_09 directory

**Comment by HannahBenisty** [comment]
[syslog.txt](https://github.com/jtamames/SqueezeMeta/files/12083428/syslog.txt)

**Comment by jtamames** [comment]
Move to directory /nfs/users/rg/hbenisty/HAB23-094_test and try again. Yours is a sequential project, which means that each sample will have its own directory

**Comment by HannahBenisty** [comment]
Thanks a lot, I'll try!

**Comment by HannahBenisty** [comment]
One question, I have only one sample (long read from PacBio) and I used sequential mode. Is this correct or should I use a different mode?

**Comment by HannahBenisty** [comment]
Thanks!

I have tried again and still the same error message as before. Would you restart the pipeline from scratch?

**Comment by jtamames** [comment]
It should work. But if you can, save a copy of the results you already have
