### ISSUE TITLE
Can't open samples file (-s) in /data/00..samples.

### ISSUE THREAD

**Issue by lichen-fungus** [jtamames/SqueezeMeta#714]
Hello, I have trouble restarting SqueezeMeta:

` SqueezeMeta.pl -m sequential -s samples -f /data/scratch/projects/p_citrina_transcriptome/tmp/trimmomatic/ -extassembly /data/scratch/projects/p_citrina_transcriptome/tmp/trinity/P_citrina_metatranscriptome_unfiltered_Trinity.fasta --restart -step 17`

```
***
Can't open samples file (-s) in /data/00..samples. Please check that it is the correct file
```

The samples file is called a bit differently: 00.p-citrina2.samples

I have a single sample and therefore did not specify the -p option when calling SqueezeMeta.

**Comment by jtamames** [comment]
Hello
The restart flag just needs the project name (and optionally, the -step parameter), so you should remove all the rest.
Also, since you are running a sequential project, each sample has its own directory. Then you should go to the project directory (where you should see a `p-citrina2` directory) and run:
`SqueezeMeta.pl  -p p-citrina2 --restart -step 17`

**Comment by lichen-fungus** [comment]
Hello, thanks!
I still get an error message, now regarding the path:

```
--- SAMPLE p-citrina2 ---
[0 seconds]: STEP17 -> CHECKING BINS: 17.checkM_batch.pl
Can't find SqueezeMeta_conf.pl in /data/scratch/projects/p_citrina_transcriptome/tmp/SqueezeMeta/p-citrina2/p-citrina2. Is the project path ok? at /data/home/admin/anaconda3/envs/SqueezeMeta/SqueezeMeta/scripts/17.checkM_batch.pl line 17.
```
It has added an extra "/data" in front of the path which should be /home/admin/anaconda3/envs/SqueezeMeta/SqueezeMeta/scripts/17.checkM_batch.pl

I noticed the same problem (and corrected it) in the CheckM DATA_CONFIG.

Wherelse do I have to correct the path?

Thanks for helping!!
