### ISSUE TITLE
assembly error

### ISSUE THREAD

**Issue by wittney-m** [jtamames/SqueezeMeta#718]
Hi,

I have attempted to run SqueezeMeta using this command:

./SqueezeMeta.pl -m coassembly -p PERMAFROST -s /home/wdmays/samples.file -f /home/wdmays/permafrost_files/ --minion -map minimap2-ont --euk -canumem 32

I have attached the output error:

[0mRun started Mon Jul 31 08:38:34 2023 in coassembly mode
5 metagenomes found: Sample611 Sample551 Sample256 Sample492 Sample273

Now creating directories
Reading configuration from /home/wdmays/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/PERMAFROST/SqueezeMeta_conf.pl
[34m[1 seconds]: STEP1 -> RUNNING ASSEMBLY: 01.run_all_assemblies.pl (canu)
[0m  Concatenating all samples:  PAI33648_pass_barcode01_4bca8ddf_4ac63679_256.fastq.gz  PAI33648_pass_barcode04_4bca8ddf_4ac63679_273.fastq.gz  PAI33648_pass_barcode02_4bca8ddf_4ac63679_492.fastq.gz  PAI33648_pass_barcode03_4bca8ddf_4ac63679_551.fastq.gz  PAI33648_pass_barcode05_4bca8ddf_4ac63679_611.fastq.gz 
    pair1: cat /home/wdmays/permafrost_files//PAI33648_pass_barcode01_4bca8ddf_4ac63679_256.fastq.gz /home/wdmays/permafrost_files//PAI33648_pass_barcode04_4bca8ddf_4ac63679_273.fastq.gz /home/wdmays/permafrost_files//PAI33648_pass_barcode02_4bca8ddf_4ac63679_492.fastq.gz /home/wdmays/permafrost_files//PAI33648_pass_barcode03_4bca8ddf_4ac63679_551.fastq.gz /home/wdmays/permafrost_files//PAI33648_pass_barcode05_4bca8ddf_4ac63679_611.fastq.gz > /home/wdmays/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/PERMAFROST/data/raw_fastq/par1.fastq.gz
  Running assembly with canu: perl /home/wdmays/miniconda3/envs/SqueezeMeta/SqueezeMeta/lib/SqueezeMeta/assembly_canu.pl /home/wdmays/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/PERMAFROST PERMAFROST /home/wdmays/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/PERMAFROST/data/raw_fastq/par1.fastq.gz 
mv: cannot stat ‘/home/wdmays/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/PERMAFROST/data/canu/PERMAFROST.contigs.fasta’: No such file or directory
Error running command:    /home/wdmays/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/canu-2.2/bin/canu  -p PERMAFROST -d /home/wdmays/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/PERMAFROST/data/canu genomeSize=5m corOutCoverage=10000 corMhapSensitivity=high corMinCoverage=0  maxThreads=12 maxMemory=32  -nanopore-raw  /home/wdmays/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/PERMAFROST/data/raw_fastq/par1.fastq.gz > /home/wdmays/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/PERMAFROST/syslog 2>&1;mv /home/wdmays/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/PERMAFROST/data/canu/PERMAFROST.contigs.fasta /home/wdmays/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/PERMAFROST/data/canu/contigs.fasta at /home/wdmays/miniconda3/envs/SqueezeMeta/SqueezeMeta/lib/SqueezeMeta/assembly_canu.pl line 46.
Assembly not present in /home/wdmays/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/PERMAFROST/results/01.PERMAFROST.fasta, exiting
31mStopping in STEP1 -> 01.run_all_assemblies.pl. Program finished abnormally
0m31m

I have also attached the syslog to this post. 
[syslog.gz](https://github.com/jtamames/SqueezeMeta/files/12217097/syslog.gz)

**Comment by jtamames** [comment]
Apparently, your dataset is very small for the assembly to work. I would recommend using sqm_longreads.pl to analyze it.
Best,
J
