### ISSUE TITLE
SQMtools subsetTax error

### ISSUE THREAD

**Issue by mradz19** [jtamames/SqueezeMeta#719]
I performed a squeezemeta run and am now trying to analyze the data in R ( I am running the latest versions of both squeezemeta and SQMtools). I used the loadSQM function to import my project as an SQM object, however when running subsetTax I am getting the following error:
```
bac=subsetTax(new_run, rank="superkingdom", tax="Bacteria", trusted_functions_only=T, ignore_unclassified_functions=T)
Error in subSQM$bins$tax[bins, , drop = FALSE] : subscript out of bounds
```
I've never had this error before.

**Comment by fpusan** [comment]
Can you run `sqm2zip.py` on the project and send the resulting zip file to us?

**Comment by mradz19** [comment]
Sure what is the best way to do that? The .zip filder is 4.16GB

**Comment by fpusan** [comment]
Maybe mega, one drive or something like that?
