### ISSUE TITLE
download_database.pl failed

### ISSUE THREAD

**Issue by yjiakang** [jtamames/SqueezeMeta#720]
Hello, can you be kind to help with the error when I run  download_database.pl? I guess there may be not enough space for building database, but I have no idea on how to deal with it. I think my space is enough. I work on a hpc. Thanks in advance.
<img width="792" alt="image" src="https://github.com/jtamames/SqueezeMeta/assets/49177016/dac70a97-c8ae-4a50-800d-785c581f2300">
<img width="820" alt="image" src="https://github.com/jtamames/SqueezeMeta/assets/49177016/485ae235-6343-4cc4-9ed1-527ad78cc0aa">

**Comment by fpusan** [comment]
The error seems quite clear.
Maybe you need to download the databases on a different partition.
Since this is a cluster, maybe the disk space is there indeed, but you are exceeding your quota.
You should discuss this with the cluster administrators

**Comment by yjiakang** [comment]
Thanks, got it.
