### ISSUE TITLE
Can we analyze the fungal function?

### ISSUE THREAD

**Issue by yjiakang** [jtamames/SqueezeMeta#721]
Hi developers, thanks for you pipeline. As I know, you wonderful pipeline did not analyze the fungal composition and function. If we want to do that, how should we do? Thanks in advance.

**Comment by fpusan** [comment]
I would try to annotate the reads directly using `sqm_reads.pl` or `sqm_longreads.pl`. That way you avoid problems related to assembly and gene calling on prokaryotic genomes.

**Comment by yjiakang** [comment]
oooh, thanks.
