### ISSUE TITLE
Can you remove outdated flags for metabat2?

### ISSUE THREAD

**Issue by mkbwang** [jtamames/SqueezeMeta#722]
Hi, I notice that your [metabat2 command](https://github.com/jtamames/SqueezeMeta/blob/4e8d1c9ce598fde0dfe679f47f7f05f70c5cf948/lib/SqueezeMeta/bin_metabat2.pl#L134) still has "saveTNF" and "saveDistance" flags. However the latest version of metabat2 has dropped these two flags (see the [README](https://bitbucket.org/berkeleylab/metabat/src/master/)). Can you update your perl scripts accordingly? Thank you! FYI, I had to recompile metabat2 and jgi_summarize_bam_contig_depths because of binary mismatch mentioned in [previous issues](https://github.com/jtamames/SqueezeMeta/issues/684).

**Comment by fpusan** [comment]
Noted. We will shortly release v1.6.3, which will (hopefully) not need users to recompile anything.
Why do you say  "saveTNF" and "saveDistance" have been deprecated? They seem to be present in the README you linked

**Comment by mkbwang** [comment]
Thanks for your reply! I mean "saveTNF" and "saveDistance" have been ditched in metabat2. They are only available in metabat1.

**Comment by fpusan** [comment]
Done in 7d862f9.
