### ISSUE TITLE
SPECIFICATION ENQUIRY FOR SQUEEZEMETA

### ISSUE THREAD

**Issue by Michaelijesse** [jtamames/SqueezeMeta#723]
Hi, I wish to know whether the following specifications is enough to run metagenome analysis
CPU core : 8
Ram : 32 GB
SSD : 1 TB

**Comment by fpusan** [comment]
Hi, it depends on the complexity of the datasets. You should be fine for individual metagenomes or a few samples (<10) using the coassembly or seqmerge modes...
