### ISSUE TITLE
Stopping in STEP10 -> 10.mapsamples.pl. Program finished abnormally

### ISSUE THREAD

**Issue by Michaelijesse** [jtamames/SqueezeMeta#724]
This is SYSLOG out

[17 hours, 18 minutes, 44 seconds]: STEP10 -> 10.mapsamples.pl
Creating Bowtie reference: python3 /home/ec2-user/han/20230828_WMS_test_2/SqueezeMeta/bin/bowtie2/bowtie2-build --quiet /home/ec2-user/han/20230828_WMS_test_2/output/Samples/results/01.Samples.fasta /home/ec2-user/han/20230828_WMS_test_2/output/Samples/data/Samples.bowtie
Getting raw reads for SRR1927149: cp /home/ec2-user/han/20230828_WMS_test_2/input/raw/SRR1927149_1.fastq.gz /home/ec2-user/han/20230828_WMS_test_2/output/Samples/temp/Samples.SRR1927149.current_1.gz; cp /home/ec2-user/han/20230828_WMS_test_2/input/raw/SRR1927149_2.fastq.gz /home/ec2-user/han/20230828_WMS_test_2/output/Samples/temp/Samples.SRR1927149.current_2.gz; 
Aligning with bowtie: /home/ec2-user/han/20230828_WMS_test_2/SqueezeMeta/bin/bowtie2/bowtie2 -x /home/ec2-user/han/20230828_WMS_test_2/output/Samples/data/Samples.bowtie  -1 /home/ec2-user/han/20230828_WMS_test_2/output/Samples/temp/Samples.SRR1927149.current_1.gz -2 /home/ec2-user/han/20230828_WMS_test_2/output/Samples/temp/Samples.SRR1927149.current_2.gz --quiet -p 12 -S /home/ec2-user/han/20230828_WMS_test_2/output/Samples/data/bam/Samples.SRR1927149.sam --very-sensitive-local
Stopping in STEP10 -> 10.mapsamples.pl. Program finished abnormally

**Comment by Michaelijesse** [comment]
Could you please sort this out. why its happening. Even this is sample dataset

**Comment by Michaelijesse** [comment]
This is Terminal Out
---------------------
[0 seconds]: STEP10 -> MAPPING READS: 10.mapsamples.pl
  Reading samples from /home/ec2-user/han/20230828_WMS_test_2/output/Samples/data/00.Samples.samples
  Metagenomes found: 2
  Mapping with Bowtie2 (Langmead and Salzberg 2012, Nat Methods 9(4), 357-9)
  Creating reference from contigs
  Working with sample 1: SRR1927149
  Getting raw reads
  Aligning to reference with bowtie
  BAM file already found in /home/ec2-user/han/20230828_WMS_test_2/output/Samples/data/bam/Samples.SRR1927149.bam, skipping
  Calculating contig coverage
  Reading contig length from /home/ec2-user/han/20230828_WMS_test_2/output/Samples/intermediate/01.Samples.lon
Illegal division by zero at /home/ec2-user/han/20230828_WMS_test_2/SqueezeMeta/scripts/10.mapsamples.pl line 445.
Stopping in STEP10 -> 10.mapsamples.pl. Program finished abnormally

  If you don't know what went wrong or want further advice, please look for similar issues in https://github.com/jtamames/SqueezeMeta/issues
  Feel free to open a new issue if you don't find the answer there. Please add a brief description of the problem and upload the /home/ec2-user/han/20230828_WMS_test_2/output/Samples/syslog file (zip it first)

**Comment by fpusan** [comment]
What's your OS and version?
Can you share the `/home/ec2-user/han/20230828_WMS_test_2/output/Samples/syslog` file with us here?

**Comment by Michaelijesse** [comment]
I am working in ec2 server. Instance type : M5.2xlarge 
[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/12473002/syslog.zip)

**Comment by fpusan** [comment]
So what OS and version are you running there?

**Comment by fpusan** [comment]
Can you run manually the command following command and let me know what error is raised?

 `/home/ec2-user/han/20230828_WMS_test_2/SqueezeMeta/bin/bowtie2/bowtie2 -x /home/ec2-user/han/20230828_WMS_test_2/output/Samples/data/Samples.bowtie  -1 /home/ec2-user/han/20230828_WMS_test_2/output/Samples/temp/Samples.SRR1927149.current_1.gz -2 /home/ec2-user/han/20230828_WMS_test_2/output/Samples/temp/Samples.SRR1927149.current_2.gz --quiet -p 12 -S /home/ec2-user/han/20230828_WMS_test_2/output/Samples/data/bam/Samples.SRR1927149.sam --very-sensitive-local`

**Comment by Michaelijesse** [comment]
Sure I will run and post the output here. Thank you.

**Comment by Michaelijesse** [comment]
I tried it successfully. No Error.

$ cd /home/ec2-user/han/20230828_WMS_test_2/
$ /home/ec2-user/han/20230828_WMS_test_2/SqueezeMeta/bin/bowtie2/bowtie2 -x /home/ec2-user/han/20230828_WMS_test_2/output/Samples/data/Samples.bowtie  -1 /home/ec2-user/han/20230828_WMS_test_2/output/Samples/temp/Samples.SRR1927149.current_1.gz -2 /home/ec2-user/han/20230828_WMS_test_2/output/Samples/temp/Samples.SRR1927149.current_2.gz --quiet -p 12 -S /home/ec2-user/han/20230828_WMS_test_2/output/Samples/data/bam/Samples.SRR1927149.sam --very-sensitive-local
$

**Comment by fpusan** [comment]
Ok, then can you run
` /home/ec2-user/han/20230828_WMS_test_2/SqueezeMeta/bin/samtools sort /home/ec2-user/han/20230828_WMS_test_2/output/Samples/data/bam/Samples.SRR1927149.sam -o /home/ec2-user/han/20230828_WMS_test_2/output/Samples/data/bam/Samples.SRR1927149.bam -@ 12`

`$/home/ec2-user/han/20230828_WMS_test_2/SqueezeMeta/bin/samtools index /home/ec2-user/han/20230828_WMS_test_2/output/Samples/data/bam/Samples.SRR1927149.bam -@ 12 `

It should fail in one of these two

**Comment by Michaelijesse** [comment]
![image](https://github.com/jtamames/SqueezeMeta/assets/111333701/eda599fc-3275-4e09-9e70-634339fabe18)

**Comment by Michaelijesse** [comment]
OS : amazon-linux (centos)

**Comment by Michaelijesse** [comment]
I have chosen this tool for metagenomic assembly for multiple good reasons. but due to errors at some steps, I cant able to come to conclusion. Could you please sort this out.?

**Comment by Michaelijesse** [comment]
Lines 445,446,447
my $mapperc=($mappedreads/$totalreadcount)*100;
	if($mapperc<50) { $warnmes=1; }
	printf outfile1 "$thissample\t$totalreadcount\t$mappedreads\t%.2f\t$totalreadlength\n",$mapperc;		#-- Mapping statistics

**Comment by fpusan** [comment]
Hi again

Did you run these two specific commands as I suggested above?

`/home/ec2-user/han/20230828_WMS_test_2/SqueezeMeta/bin/samtools sort /home/ec2-user/han/20230828_WMS_test_2/output/Samples/data/bam/Samples.SRR1927149.sam -o /home/ec2-user/han/20230828_WMS_test_2/output/Samples/data/bam/Samples.SRR1927149.bam -@ 12`

`/home/ec2-user/han/20230828_WMS_test_2/SqueezeMeta/bin/samtools index /home/ec2-user/han/20230828_WMS_test_2/output/Samples/data/bam/Samples.SRR1927149.bam -@ 12`

If so, which one of those failed?

**Comment by fpusan** [comment]
Also was this installed through conda? In the screenshot above I can see that you are in the `(base)` environment, which suggests that you installed it manually.
SqueezeMeta has not been tested in amazon linux so certain binaries may not work properly there. I pretty much suspect that samtools is failing in your case. If we confirm that (see my post above to test it) we can start testing for solutions.

**Comment by Michaelijesse** [comment]
Error raised in first commandline, but second one run well.

(base) [ec2-user@ip-172-31-51-208 20230828_WMS_test_2]$ /home/ec2-user/han/20230828_WMS_test_2/SqueezeMeta/bin/samtools sort /home/ec2-user/han/20230828_WMS_test_2/output/Samples/data/bam/Samples.SRR1927149.sam -o /home/ec2-user/han/20230828_WMS_test_2/output/Samples/data/bam/Samples.SRR1927149.bam -@ 12
[E::hts_open_format] Failed to open file /home/ec2-user/han/20230828_WMS_test_2/output/Samples/data/bam/Samples.SRR1927149.sam
samtools sort: can't open "/home/ec2-user/han/20230828_WMS_test_2/output/Samples/data/bam/Samples.SRR1927149.sam": No such file or directory
(base) [ec2-user@ip-172-31-51-208 20230828_WMS_test_2]$ /home/ec2-user/han/20230828_WMS_test_2/SqueezeMeta/bin/samtools index /home/ec2-user/han/20230828_WMS_test_2/output/Samples/data/bam/Samples.SRR1927149.bam -@ 12

**Comment by Michaelijesse** [comment]
Hello,
Output from bowtie2

![image](https://github.com/jtamames/SqueezeMeta/assets/111333701/314986a1-e0b3-4534-aa7a-b773ec6fb647)
![image](https://github.com/jtamames/SqueezeMeta/assets/111333701/7ad5a60d-b17b-4fb8-aef5-fb1ea07258e5)

**Comment by Michaelijesse** [comment]
Helllo,
Output from Bowtie2.
![image](https://github.com/jtamames/SqueezeMeta/assets/111333701/fdf87e6c-fd83-40be-9abb-5ae30aab9f18)
![image](https://github.com/jtamames/SqueezeMeta/assets/111333701/61531e57-c4a3-454d-bf14-fa8713be9d39)
![image](https://github.com/jtamames/SqueezeMeta/assets/111333701/6707e104-6220-41c8-b63f-8c1edf8d5936)

**Comment by fpusan** [comment]
Ok, I have uploaded a dev version that may fix this issue
Try
`mamba create -n SqueezeMeta_dev -c conda-forge -c bioconda -c anaconda -c fpusan  squeezemeta-dev=1.6.3.beta1 --no-channel-priority`
And then
`conda activate SqueezeMeta_dev` and run the test data again using the `SqueezeMeta.pl` executable present in your PATH

**Comment by fpusan** [comment]
Note that you will need to start a new project, restarting won't work in this case since the run was bugged

**Comment by fpusan** [comment]
And of course after making the new install you'll need to link it to the old databases using `configure_nodb.pl` (check the ReadMe for details)

**Comment by fpusan** [comment]
`configure_nodb.pl` will also trigger a series of tests, including some tests to check that certain binaries can be executed in your system. Can you share with me the output of that after running it on the new SQM install?

**Comment by Michaelijesse** [comment]
Hello,

Running configure_nodb.pl, failed mothur configuration. Even I installed Mothur through conda but Test failed. 

![image](https://github.com/jtamames/SqueezeMeta/assets/111333701/32a519ae-ae25-4862-9b50-55e6dc762258)

**Comment by Michaelijesse** [comment]
Installed mothur.
![image](https://github.com/jtamames/SqueezeMeta/assets/111333701/bc0b39d2-3659-4645-a476-11433ff95bad)

**Comment by fpusan** [comment]
That's encouraging. mothur is not needed for the main SqueezeMeta pipeline (though I see you made It work regardless)
Then can you try running the pipeline again using the conda version?

**Comment by Michaelijesse** [comment]
Hello, 
Thank you for your guidance and support. The whole process completed successfully.

**Comment by Michaelijesse** [comment]
So closing the issue

**Comment by fpusan** [comment]
Great! We will release a new version incorporating these changes shortly
