### ISSUE TITLE
SQMtools version

### ISSUE THREAD

**Issue by HannahBenisty** [jtamames/SqueezeMeta#729]
Hi, 

I am trying to run SQMtools but I have a problem with the versions and I am not able to load the tables. "_Your project was created with SqueezeMeta v1.5, while this is SQMtools v1.6.2. You can ignore this message if things are working fine for you, but if you experience any issue consider using the right version of SQMtools for this project_". So, I would like to use the correct version of SQMtools. How can I do it?

Thanks.

**Comment by fpusan** [comment]
If on windows/Mac, follow the install instructions here
https://github.com/jtamames/SqueezeMeta/wiki/Using-SQMtools-(pre-1.6.2)-in-a-Windows-environment
You need to make sure to download the tarball for SqueezeMeta v1.5

If on linux, just install SqueezeMeta v1.5. via conda, the right SQMtools version will be shipped within the environment

**Comment by HannahBenisty** [comment]
Thanks! I am on Mac and I have followed all the steps. Could please help with this one:
1-Download the file SQMtools - For instance, go to [downgit](https://downgit.github.io/) and put the URL https://github.com/jtamames/SqueezeMeta/tree/master/lib/SQMtools to download the package as a zip file. 
Which would be the link I should use to download the SQMtools from v1.5?

In parallel I have been trying to install the package directly in RStudio, but I keep getting this error:
> install.packages("~/Downloads/SqueezeMeta-1.5.0-post2.tar.gz", repos = NULL, type = "source")
Warning in untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
ERROR: cannot extract package from ‘/Users/hbenisty/Downloads/SqueezeMeta-1.5.0-post2.tar.gz’
Warning in install.packages :
  installation of package ‘/Users/hbenisty/Downloads/SqueezeMeta-1.5.0-post2.tar.gz’ had non-zero exit status

Thanks again

**Comment by HannahBenisty** [comment]
Hi, 

I have managed to install the library from the v1.5.0 version. However, when loading the tables in RStudio I get this message: 

Error in SQM$functions[[method]]$tpm["Unmapped", ] : 
  subscript out of bounds
In addition: Warning message:
In sprintf("%s/results/tables/%s.superkingdom.%s.abund.tsv", project_path,  :
  one argument not used by format '%s/results/tables/%s.superkingdom.%s.abund.tsv'

I have used the same structure and names in my local computer. Do you know where could be the problem? 

Thanks

**Comment by fpusan** [comment]
Did you run `sqm2tables.py` using the same environment in which you ran the main pipeline?

**Comment by fpusan** [comment]
Well 1.6.3 is not officially out yet, if everything goes fine I will release it by the end of this when week/beggining of the next.

**Comment by HannahBenisty** [comment]
Great, thanks! Then, I will wait for it.

**Comment by HannahBenisty** [comment]
Hi, I have re-run my sample with the new version. Could you please indicate me what would the steps I should follow to use SQMtools on these results (with Mac). Should I still follow this steps that you recommended? https://github.com/jtamames/SqueezeMeta/wiki/Using-SQMtools-(pre-1.6.2)-in-a-Windows-environment

Thanks!

**Comment by fpusan** [comment]
No, it's easier now.
See https://github.com/jtamames/SqueezeMeta#15-analyzing-squeezemeta-results-in-your-desktop-computer

**Comment by HannahBenisty** [comment]
Thanks, everything worked perfect.

**Comment by fpusan** [comment]
Glad to hear!
