### ISSUE TITLE
install squeezemeta on high performance computing without sudo 

### ISSUE THREAD

**Issue by yjiakang** [jtamames/SqueezeMeta#73]
hello, is there any way to install squeezemeta on high performance computing without sudo

**Comment by fpusan** [comment]
Hi!
You can get an experimental (but increasingly stable) conda version:
```
conda create -n SqueezeMeta -c bioconda -c fpusan squeezemeta
conda activate SqueezeMeta
```

**Comment by yjiakang** [comment]
@fpusan Thanks for reply, I have tried it, but when I download databases for analyses, the speed is very slow. Is there any alternative to do it? Thanks in advance.

Here is my code and output: 
(SqueezeMeta) [jkyin@mn02 ~]$ download_databases.pl biosoft/database/squeezemeta
rm: cannot remove ‘/public/home/jkyin/biosoft/database/squeezemeta/test.tar.gz’: No such file or directory
rm: cannot remove ‘/public/home/jkyin/biosoft/database/squeezemeta/SqueezeMetaDB.tar.gz’: No such file or directory

Downloading and unpacking test data...

--2020-03-06 10:26:55--  http://wwwuser.cnb.csic.es/~squeezem/test.tar.gz
Resolving wwwuser.cnb.csic.es (wwwuser.cnb.csic.es)... 161.111.70.130
Connecting to wwwuser.cnb.csic.es (wwwuser.cnb.csic.es)|161.111.70.130|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3903775708 (3.6G) [application/x-gzip]
Saving to: ‘/public/home/jkyin/biosoft/database/squeezemeta/test.tar.gz’

100%[=============================================================================================================>] 3,903,775,708  149KB/s   in 7h 38m

2020-03-06 18:05:13 (139 KB/s) - ‘/public/home/jkyin/biosoft/database/squeezemeta/test.tar.gz’ saved [3903775708/3903775708]

test/
test/test.samples
test/raw/
test/raw/SRR1927149_2.fastq.gz
test/raw/SRR1929485_1.fastq.gz
test/raw/SRR1929485_2.fastq.gz
test/raw/SRR1927149_1.fastq.gz
Downloading and unpacking RDP classifier...
--2020-03-06 18:05:48--  http://wwwuser.cnb.csic.es/~squeezem/classifier.tar.gz
Resolving wwwuser.cnb.csic.es (wwwuser.cnb.csic.es)... 161.111.70.130
Connecting to wwwuser.cnb.csic.es (wwwuser.cnb.csic.es)|161.111.70.130|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 154722472 (148M) [application/x-gzip]
Saving to: ‘/public/home/jkyin/miniconda2/envs/SqueezeMeta/SqueezeMeta/lib/classifier.tar.gz’

100%[===============================================================================================================>] 154,722,472  147KB/s   in 18m 21s

2020-03-06 18:24:14 (137 KB/s) - ‘/public/home/jkyin/miniconda2/envs/SqueezeMeta/SqueezeMeta/lib/classifier.tar.gz’ saved [154722472/154722472]

classifier/
classifier/classifier.jar
classifier/lib/
classifier/lib/TaxonomyTree.jar
classifier/lib/commons-cli-1.2.jar
classifier/lib/ReadSeq.jar
classifier/lib/jfreechart-1.0.13.jar
classifier/lib/AlignmentTools.jar
classifier/lib/jcommon-1.0.16.jar
classifier/lib/commons-io-2.4.jar
ln: failed to create symbolic link ‘./classifier.jar’: File exists
Downloading and unpacking database tarball...
--2020-03-06 18:24:19--  http://silvani.cnb.csic.es/SqueezeMeta/SqueezeMetaDB.tar.gz
Resolving silvani.cnb.csic.es (silvani.cnb.csic.es)... 150.244.82.96
Connecting to silvani.cnb.csic.es (silvani.cnb.csic.es)|150.244.82.96|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 89920184085 (84G) [application/x-gzip]
Saving to: ‘/public/home/jkyin/biosoft/database/squeezemeta/SqueezeMetaDB.tar.gz’

 0% [                                                                                                                ] 598,985,164 7.57KB/s  eta 89d 23h

**Comment by fpusan** [comment]
Yep, that speed is really bad.
I have tested it right now (using the WiFi of the hotel I'm currently at) and I got transfer speeds over 1Mb/s
Maybe there's a problem with your connection?

You can maybe try to use `make_databases.pl` instead of `download_databases.pl`
It will download the nr database from NCBI instead of from our own server, you might get more speed?

**Comment by yjiakang** [comment]
Yeah， make_databases.pl worked better. Thank you

**Comment by yjiakang** [comment]
@fpusan hello， sorry to disturb you again. However, something went wrong when I run make_databases.pl, so I  tried to re-install SqueezeMeta with conda. Problems came again,here is the commonds:
conda remove -n SqueezeMeta --all
conda create -n SqueezeMeta -c bioconda -c fpusan squeezemeta
-------------------------------  here error comes  in the end of the installation -------------------------------------------------------
Downloading and Extracting Packages
glib-2.58.3          | 3.3 MB    | ############################################################################################################################## | 100%
Preparing transaction: done
Verifying transaction: |
CondaMultiError: SafetyError: The package for r-base located at /public/home/jkyin/miniconda2/pkgs/r-base-3.6.2-h7ed4ef7_1
appears to be corrupted. The path 'lib/R/doc/html/packages.html'
has an incorrect size.
  reported size: 2946 bytes
  actual size: 22407 bytes
Can you tell me how to solve it.

**Comment by yjiakang** [comment]
@fpusan When I am running make_databases.pl, the internet were blocked. For example,  
http://wwwuser.cnb.csic.es/~squeezem/test.tar.gz
Resolving wwwuser.cnb.csic.es (wwwuser.cnb.csic.es)... 161.111.70.130
Connecting to wwwuser.cnb.csic.es (wwwuser.cnb.csic.es)|161.111.70.130|:80... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2020-03-14 09:45:43 ERROR 500: Internal Server Error.
Is there something wrong about it?

**Comment by fpusan** [comment]
Hi!
The server (wwwuser.cnb.csic.es) is reachable for me as of right now. Maybe there was some network problem before?
