### ISSUE TITLE
cluster_protein.pl missing and SqueezeMeta.pl missing clustered request in v1.6.3

### ISSUE THREAD

**Issue by stonyang** [jtamames/SqueezeMeta#731]
I really appreciate your great work. In the repo, i cannot see cluster_protein.pl in the utils, as well as the option for clustered assembly in SqueezeMeta.pl. 
Thanks for your help

**Comment by fpusan** [comment]
The clustered mode is being tested and has not been released officially yet. We included the entry in the PDF manual by mistake

**Comment by stonyang** [comment]
well understood and thanks for your response.
