### ISSUE TITLE
SQM to Phyloseq

### ISSUE THREAD

**Issue by megberryman** [jtamames/SqueezeMeta#732]
Do you have a suggested method for converting the taxa abundance file to a phyloseq object?

**Comment by fpusan** [comment]
Nuneric matrices can be found under `SQM$taxa`. Eg `SQM$taxa$phylum$abund` for the number of reads assigned to each phylum per sample. From there It should be reasonably straightforward as per https://joey711.github.io/phyloseq/import-data
