### ISSUE TITLE
anvio does not go until end

### ISSUE THREAD

**Issue by Azimdine** [jtamames/SqueezeMeta#735]
dear all,
i have run anvi-load-sqm.py on my SqueezeMeta outputs.
 After 21:07:16 of runs , it stops after sometime and is unable to create the PROFILE.db and throws an error.
When I check the sqm2anvio results directory, 
I can see that the bam files have been correcty created in sqm2anvio file but empty and the CONTIGS.db has also been created in anvio results file ,
 but the tool fails to create PROFILES.db.
**i get this on my error file:** 

✓ anvi-run-scg-taxonomy took 3:53:25.663034
Gene functions ...............................: 44,387,844 function calls from 4 sources (COG, KEGG, KEGGPATH, COGPATH) for 13,322,741 unique gene calls have been added to the contigs database.
usage: anvi-profile [-h] [-i INPUT_BAM] [-c CONTIGS_DB] [--blank-profile]
                    [-S NAME] [--description TEXT_FILE] [-M INT]
                    [--max-contig-length INT] [--contigs-of-interest FILE]
                    [--list-contigs] [--min-percent-identity PERCENT_IDENTITY]
                    [--fetch-filter FILTER] [--report-variability-full]
                    [-V INT] [--skip-SNV-profiling] [--skip-INDEL-profiling]
                    [--profile-SCVs] [--cluster-contigs]
                    [--skip-hierarchical-clustering]
                    [--distance DISTANCE_METRIC] [--linkage LINKAGE_METHOD]
                    [-o DIR_PATH] [-W] [-T NUM_THREADS] [--queue-size INT]
                    [--write-buffer-size-per-thread INT] [--force-multi]
                    [--version] [--debug] [--force] [--fix-sad-tables]
                    [--quiet] [--no-progress] [--as-markdown]
                    [--display-db-calls] [--force-use-my-tree]
                    [--force-overwrite] [--tmp-dir TMP_DIR]
                    [--I-know-this-is-not-a-good-idea]
anvi-profile: error: unrecognized arguments: --min-mean-coverage 0

**And this on my output batch**

Result/results/sqm2anvio does not exist
Creating sqm2anvio directory with all the input files for anvi'o
/pasteur/zeus/projets/p02/Biomics/Bioinfo/projet_Ariane/Result/results/sqm2anvio
Preparing contigs database: loading contigs, genes, functions and taxonomy!
Contigs database is CONTIGS.db. Contigs and genes have been loaded
Running HMMS to detect SCGs
We have noticed that SCG taxonomy databases required to run anvi-run-scg-taxonomy are missing.
We assume that this is due to it is the first time you run it in your anvi'o environment, so we decided to run anvi-setup-scg-databases (anvio-6) or anvi-setup-scg-taxonomy (anvio-7) and build them automatically for you.
If you do not like this alternative, please, feel free to run this command on your own with your databases
Check anvi'o documentation for more help:
http://merenlab.org/software/anvio/vignette/#anvi-setup-scg-databases
http://merenlab.org/software/anvio/vignette/#anvi-run-scg-taxonomy
Functions have been loaded
Taxonomy has been loaded
Loading bam files
Processing Result.B17.bam
Profiling Result.B17.bam
There must be some problem with "anvi-profile -i Result/data/bam/Result.B17.bam -o /pasteur/zeus/projets/p02/Biomics/Bioinfo/projet_Ariane/Result/results/anvio/Result.B17_temp -c /pasteur/zeus/projets/p02/Biomics/Bioinfo/projet_Ariane/Result/results/anvio/CONTIGS.db --min-contig-length 2500 --min-mean-coverage 0 --num-threads 12 --skip-hierarchical-clustering".
It's better to stop and check it

Any help, suggestions, corrections...
find attached out, err and lod-g file
Cordially
Azim
[anvi-load-sqm.logfile.zip](https://github.com/jtamames/SqueezeMeta/files/12818247/anvi-load-sqm.logfile.zip)
[batch.err.zip](https://github.com/jtamames/SqueezeMeta/files/12818254/batch.err.zip)
[batch.out.zip](https://github.com/jtamames/SqueezeMeta/files/12818255/batch.out.zip)

**Comment by fpusan** [comment]
This may be broken for anvio8, try using anvio7 instead.
