### ISSUE TITLE
Incorporate MetaGeneMark in ORF prediction

### ISSUE THREAD

**Issue by tboonf** [jtamames/SqueezeMeta#736]
SqueezeMeta has been an awesome tool. The default option for ORF prediction is prodigal. However, some papers have suggested that MetaGeneMark may produce better results compared to (meta)prodigal. Would there be a chance that MetaGeneMark can be implemented as part of SqueezeMeta pipeline, or how may one go about doing it manually. 

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8153819/#:~:text=It%20was%20observed%20that%20MetaGeneMark,%E2%80%8B2%2C%20bottom%20panel).

**Comment by jtamames** [comment]
Hello!
Thanks for the suggestion, we will look into it. In the meantime, you can use the predictions of MetaGeneMark or any other software. You just need that the names of the genes are compliant with SqueezeMeta naming schema, in the form:
`contigname_initpositon-endposition`
for instance, contig1_1-150.
Just replace the 03.projectname.faa file in the results directory with the new one (keeping the name as 03.projectname.faa) and restart the project from step 4.
Best,
J
