### ISSUE TITLE
identify genenames annotated with one database with other.

### ISSUE THREAD

**Issue by afsanarupa** [jtamames/SqueezeMeta#738]
Hello, I have performed co-assembly of a whole metagenome consisting 8 samples. 
I have gathered the orfs associated with my external database like following:
# get the information of GH families annotated with CazyDb
GH <- subsetFun(met_jute, fun = '^GH', rescale_copy_number = F)
However, it comes out that it also gathers information for ORFs and annotation associated with all other default databases which
doesnot start with GH. 
Can you help me with identifying ORFs which are annotated with CazyDb as "GH", then I want to identify whether they are also annotated with Pfam or KEGG database and if so what are their identity. 

Thank you very much.

**Comment by fpusan** [comment]
You can use the option `columns` to limit the columns in which `subsetFun` searches for patterns.
You can list all the columns in the table with `colnames(met_jute$orfs$table)`
So e.g. if the CAZY identifiers are in a column named `CAZY ID` you should try
`GH <- subsetFun(met_jute, fun = '^GH', rescale_copy_number = F, columns = 'CAZY ID')`
Hope this helps

**Comment by afsanarupa** [comment]
Thanks, It helped. I was wondering if there is a way to get the ORFs associated with CAzy Families and have them annotated with KEGG or PFAM database to get both the KEGG and PFAM name and abundance of the ORFs
