### ISSUE TITLE
make_databases.pl failed

### ISSUE THREAD

**Issue by yjiakang** [jtamames/SqueezeMeta#74]
Hi! Thanks for this pipeline, I have installed it successfully using conda on our HPC (centos). However, when I run make_databases.pl to prepare databases for it, internet error just happened. Do you maybe know what can I do for it? Is the server unavailable or my internet is corrupted? Thank you for reading and replying.
The error messages are as follows:
```
rm: cannot remove ‘/public/home/jkyin/biosoft/database/squzeemeta/test.tar.gz’: No such file or directory
rm: cannot remove ‘/public/home/jkyin/miniconda2/envs/SqueezeMeta/SqueezeMeta/lib/classifier.tar.gz’: No such file or directory
rm: cannot remove ‘/public/home/jkyin/biosoft/database/squzeemeta/db.tar.gz’: No such file or directory
rm: cannot remove ‘/public/home/jkyin/biosoft/database/squzeemeta/kegg.dmnd.gz’: No such file or directory

Downloading and unpacking test data...

--2020-03-17 14:47:15--  http://wwwuser.cnb.csic.es/~squeezem/test.tar.gz
Resolving wwwuser.cnb.csic.es (wwwuser.cnb.csic.es)... 161.111.70.130
Connecting to wwwuser.cnb.csic.es (wwwuser.cnb.csic.es)|161.111.70.130|:80... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2020-03-17 14:47:22 ERROR 500: Internal Server Error.

tar (child): /public/home/jkyin/biosoft/database/squzeemeta/test.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
rm: cannot remove ‘/public/home/jkyin/biosoft/database/squzeemeta/test.tar.gz’: No such file or directory
Downloading and unpacking RDP classifier...
--2020-03-17 14:47:22--  http://wwwuser.cnb.csic.es/~squeezem/classifier.tar.gz
Resolving wwwuser.cnb.csic.es (wwwuser.cnb.csic.es)... 161.111.70.130
Connecting to wwwuser.cnb.csic.es (wwwuser.cnb.csic.es)|161.111.70.130|:80... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2020-03-17 14:47:24 ERROR 500: Internal Server Error.

tar (child): /public/home/jkyin/miniconda2/envs/SqueezeMeta/SqueezeMeta/lib/classifier.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
rm: cannot remove ‘/public/home/jkyin/miniconda2/envs/SqueezeMeta/SqueezeMeta/lib/classifier.tar.gz’: No such file or directory
Downloading and unpacking general database tarball...
--2020-03-17 14:47:24--  http://wwwuser.cnb.csic.es/~squeezem/db.tar.gz
Resolving wwwuser.cnb.csic.es (wwwuser.cnb.csic.es)... 161.111.70.130
Connecting to wwwuser.cnb.csic.es (wwwuser.cnb.csic.es)|161.111.70.130|:80... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2020-03-17 14:47:25 ERROR 500: Internal Server Error.

tar (child): /public/home/jkyin/biosoft/database/squzeemeta/db.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
rm: cannot remove ‘/public/home/jkyin/biosoft/database/squzeemeta/db.tar.gz’: No such file or directory

Downloading and creating kegg database...

--2020-03-17 14:47:25--  http://wwwuser.cnb.csic.es/~squeezem/kegg.db.gz
Resolving wwwuser.cnb.csic.es (wwwuser.cnb.csic.es)... 161.111.70.130
Connecting to wwwuser.cnb.csic.es (wwwuser.cnb.csic.es)|161.111.70.130|:80... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2020-03-17 14:47:25 ERROR 500: Internal Server Error.

gzip: /public/home/jkyin/biosoft/database/squzeemeta/db/kegg.db.gz: No such file or directory
diamond v0.9.22.123 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU AGPL <https://www.gnu.org/licenses/agpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 8
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Database file: /public/home/jkyin/biosoft/database/squzeemeta/db/kegg.db
Opening the database file... No such file or directory
 [0.003918s]
Error: Error opening file /public/home/jkyin/biosoft/database/squzeemeta/db/kegg.db
rm: cannot remove ‘/public/home/jkyin/biosoft/database/squzeemeta/db/kegg.db’: No such file or directory
Downloading and creating nr database. This may take a several hours...
--2020-03-17 14:47:25--  ftp://ftp.ncbi.nlm.nih.gov/blast/db/FASTA/nr.gz
```

**Comment by fpusan** [comment]
Hi!

The error 500 seems to indicate that something is wrong in our server. However, I have just tested `make_databases.pl` and `download_databases.pl` from my home computer and it works just fine.

I honestly don't know what could be making the difference, and at some point it actually worked for you, right?

The data is hosted in a server from our institution, I can try to contact the IT guys but with the CoV everything is kind of crazy right now.

Let me try to upload the databases to an alternative place and get back to you.

**Comment by yjiakang** [comment]
Thanks for your quick reply. Indeed I can download the databases just a week ago, but my local net brokedown during the process. However, when I rerun it, the above occurred. 
Thanks in advance for uploading the databases for me.

**Comment by fpusan** [comment]
Hi again,

Let's see if these instructions work. Normally all this process would be automated by the install script, but its not that complicated to do it manually.

1) First download the files we need by following these links:
```
https://saco.csic.es/index.php/s/RKQNjYYHWGn6Z3W
https://saco.csic.es/index.php/s/s8S9xosiLKMeMJT
https://saco.csic.es/index.php/s/kLtH4gFJNJTX4ed
```

2) The md5sum of the `SqueezeMetaDB.tar.gz` file should be `2d02374c7053a625bb7fc47aa85b839d`.

3) Place the `classifier.tar.gz` file into the `SqueezeMeta/lib` directory (in your case this should be inside the SqueezeMeta environment in miniconda, `/public/home/jkyin/miniconda2/envs/SqueezeMeta/SqueezeMeta/lib/`). Don't uncompress the file.

4) Uncompress the "SqueezeMetaDB.tar.gz" and "test.tar.gz" files in the directory in which you want to place the databases (let's sat it's called `/path/to/SQMdata/`).

5) There should now be two directories called `/path/to/SQMdata/db` and `/path/to/SQMdata/test`. Within the `/path/to/SQMdata/db` directory there should be a lot of files, including one named `nr.dmnd`.

6) Now run `configure_nodb.pl /path/to/SQMdata/db`. It will complain about the error 500, but should be able to find the `classifier.tar.gz` file in the right place nonetheless.

7) Finally, run `test_install.pl` to check that the dependencies and databases are all properly installed.

**Comment by yjiakang** [comment]
Yeah! I have configured the databases following your guides above. Everything is OK. Thank you again.

**Comment by fpusan** [comment]
Glad to hear! Closing issue
