### ISSUE TITLE
Can I obtain the latest version of the KEGG database using make.download.pl?

### ISSUE THREAD

**Issue by Lafmas** [jtamames/SqueezeMeta#740]
Hello, 

I came across your mention in #665. (`make_databases.pl` _will download the raw data from different sources (our servers, but also NCBI's servers, for example) and compile the database in your computer. This can take a long time, but will be more up-to-date. However I personally don't think it makes a large impact, since we keep the pre-compiled databases reasonably updated._) 

Nevertheless, I've observed that the KEGG database seems relatively outdated when using `download_databases.pl`. Is it possible to obtain the latest version of the KEGG database when using `make_databases.pl`? 

Best, 
Lafmas

**Comment by fpusan** [comment]
No, we distribute the latest free version. AFAIK newer versions are subscription-only.
