### ISSUE TITLE
The pipeline stopped without finishing megahit

### ISSUE THREAD

**Issue by feixiang1209** [jtamames/SqueezeMeta#745]
After almost 24 hours, the analysis stopped. Please see below error message. Can you please help?

Error running command:    /home/zhaox0b/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/megahit/megahit  -1 /home/zhaox0b/metagenomics/test2/test2/data/raw_fastq/par1.fastq.gz -2 /home/zhaox0b/metagenomics/test2/test2/data/raw_fastq/par2.fastq.gz -t 12 -o /home/zhaox0b/metagenomics/test2/test2/data/megahit >> /home/zhaox0b/metagenomics/test2/test2/syslog 2>&1 at /home/zhaox0b/miniconda3/envs/SqueezeMeta/SqueezeMeta/lib/SqueezeMeta/assembly_megahit.pl line 36.
Assembly not present in /home/zhaox0b/metagenomics/test2/test2/results/01.test2.fasta, exiting
Stopping in STEP1 -> 01.run_all_assemblies.pl. Program finished abnormally

  If you don't know what went wrong or want further advice, please look for similar issues in https://github.com/jtamames/SqueezeMeta/issues
  Feel free to open a new issue if you don't find the answer there. Please add a brief description of the problem and upload the /home/zhaox0b/metagenomics/test2/test2/syslog file (zip it first)
Died at /home/zhaox0b/miniconda3/envs/SqueezeMeta/bin/SqueezeMeta.pl line 941.

**Comment by feixiang1209** [comment]
[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/13234623/syslog.zip)

Upload the syslog file. Thanks

**Comment by fpusan** [comment]
Exit code -9 means that the process was killed, probably because it exceeded the memory limit. If running on a computing cluster, please allocate more memory to the job.
