### ISSUE TITLE
read counts

### ISSUE THREAD

**Issue by zhenzhao123** [jtamames/SqueezeMeta#756]
Hello, Is there an upper limit on the sample size per assembly, I tried 12 samples, but except for the first sample, the read counts result of all other samples are 0.    I don't know why  other samples are 0 read counts.  
BASE
ZHAO

**Comment by fpusan** [comment]
Hi,
Is this happening with a dev version of SqueezeMeta?
Can you share your syslog with us?

**Comment by zhenzhao123** [comment]
[syslog.gz](https://github.com/jtamames/SqueezeMeta/files/13448426/syslog.gz)

**Comment by jtamames** [comment]
Hello!
Yep, something happened in the mapping step. It maps correctly the first sample, starts the mapping of the second, but it gets interrupted by some reason.
Could you run again the step 10, see if it happens again, and paste here the screen output? Simply do:
`10.mapsamples.pl low_salt`
in your /home/lmb600/work_space/li/raw_data/yandu directory
Best,
J

**Comment by jtamames** [comment]
Could you please copy your samples file here?

**Comment by zhenzhao123** [comment]
[sample2_back.TXT](https://github.com/jtamames/SqueezeMeta/files/13457035/sample2_back.TXT)
This is my samples file, please check.

**Comment by zhenzhao123** [comment]
The terminal print result is : 
9d20ppt1        9d20ppt1-LEK8540_L1_1.fq.gz     pair1
9d20ppt1        9d20ppt1-LEK8540_L1_2.fq.gz     pair2
9d20ppt2        9d20ppt2-LEK8541_L1_1.fq.gz     pair1
9d20ppt2        9d20ppt2-LEK8541_L1_2.fq.gz     pair2
9d20ppt3        9d20ppt3-LEK8542_L1_1.fq.gz     pair1
9d20ppt3        9d20ppt3-LEK8542_L1_1.fq.gz     pair2
9d25ppt1        9d25ppt1-LEK8543_L1_1.fq.gz     pair1
9d25ppt1        9d25ppt1-LEK8543_L1_2.fq.gz     pair2
9d25ppt2        9d25ppt2-LEK8544_L1_1.fq.gz     pair1
9d25ppt2        9d25ppt2-LEK8544_L1_2.fq.gz     pair2
9d25ppt3        9d25ppt3-LEK8545_L1_1.fq.gz     pair1
9d25ppt3        9d25ppt3-LEK8545_L1_2.fq.gz     pair2
9d30ppt1        9d30ppt1-LEK8546_L1_1.fq.gz     pair1
9d30ppt1        9d30ppt1-LEK8546_L1_2.fq.gz     pair2
9d30ppt2        9d30ppt2-LEK8547_L1_1.fq.gz     pair1
9d30ppt2        9d30ppt2-LEK8547_L1_2.fq.gz     pair2
9d30ppt3        9d30ppt3-LEK8548_L1_1.fq.gz     pair1
9d30ppt3        9d30ppt3-LEK8548_L1_2.fq.gz     pair2
9d35ppt1        9d35ppt1-LEK8549_L1_1.fq.gz     pair1
9d35ppt1        9d35ppt1-LEK8549_L1_2.fq.gz     pair2
9d35ppt2        9d35ppt2-LEK8550_L1_1.fq.gz     pair1
9d35ppt2        9d35ppt2-LEK8550_L1_2.fq.gz     pair2
9d35ppt3        9d35ppt3-LEK8551_L1_1.fq.gz     pair1
9d35ppt3        9d35ppt3-LEK8551_L1_2.fq.gz     pair2

**Comment by jtamames** [comment]
Hum.. You have duplicated read files. For instance 9d20ppt3-LEK8542_L1_1.fq.gz is listed both as pair1 and pair2 for sample 9d20ppt3. It that correct, or is it a mistake?

**Comment by zhenzhao123** [comment]
Oh, my God, I didn't see it. I'm so sorry for the trouble!
