### ISSUE TITLE
10.mapsamples.pl

### ISSUE THREAD

**Issue by zhenzhao123** [jtamames/SqueezeMeta#757]
Hello!
I got a location error when I ran Squeezemeta, and the feedback is as follows:
stat: No such file or directory
Warning: Could not open read file "/home/lmb600/work_space/li/raw_data/yandu/low_salt/temp/low_salt.9d20ppt3.current_1" for reading; skipping...
Error: No input read files were valid
(ERR): bowtie2-align exited with value 1
An error occurred during mapping with command       /home/lmb600/anaconda3/envs/SqueezeMeta/SqueezeMeta/bin/bowtie2/bowtie2 -x /home/lmb600/work_space/li/raw_data/yandu/low_salt/data/low_salt.bowtie  -1 /home/lmb600/work_space/li/raw_data/yandu/low_salt/temp/low_salt.9d20ppt3.current_1 -2 /home/lmb600/work_space/li/raw_data/yandu/low_salt/temp/low_salt.9d20ppt3.current_2.gz --quiet -p 100 -S /home/lmb600/work_space/li/raw_data/yandu/low_salt/data/bam/low_salt.9d20ppt3.sam --very-sensitive-local! at /home/lmb600/anaconda3/envs/SqueezeMeta/SqueezeMeta/scripts/10.mapsamples.pl line 267.
Stopping in STEP10 -> 10.mapsamples.pl. Program finished abnormally

  If you don't know what went wrong or want further advice, please look for similar issues in https://github.com/jtamames/SqueezeMeta/issues
  Feel free to open a new issue if you don't find the answer there. Please add a brief description of the problem and upload the /home/lmb600/work_space/li/raw_data/yandu/low_salt/syslog file (zip it first)
Died at /home/lmb600/anaconda3/envs/SqueezeMeta/bin/SqueezeMeta.pl line 941.
This is my syslog file. 
[syslog.gz](https://github.com/jtamames/SqueezeMeta/files/13456747/syslog.gz)

**Comment by jtamames** [comment]
Hello
Is this the same issue that you opened yesterday?

**Comment by zhenzhao123** [comment]
Yes, I re-ran the Step 10 script as you requested yesterday and found that the problem still exists. Today I re-ran it from scratch and found that the problem still occurs.

**Comment by jtamames** [comment]
Ok,then please do not open two issues for the same problem
