### ISSUE TITLE
Error creating taxid.db, please contact us!

### ISSUE THREAD

**Issue by DeniRibicic** [jtamames/SqueezeMeta#760]
Hi,

As the title says I have problems creating `taxid.db` after running  `make_databases.pl`.

Seems there is certain files/databases successfully created, but not the mentioned one.
```
arc.all.faa     bacar_marker.hmm  eggnog.dmnd  img          mito.hmm    ReadMe                    silva.nr_v132.tax.md5
arc.hmm         bac.hmm           euk.hmm      keggdb.dmnd  nr.dmnd     selected_marker_sets.tsv  taxon_marker_sets.tsv
arc.scg.faa     bac.scg.faa       genome_tree  kegg.db.md5  nr.faa      silva.nr_v132.align       test_data
arc.scg.lookup  bac.scg.lookup    hmms         LCA_tax      pfam        silva.nr_v132.align.md5
bac.all.faa     distributions     hmms_ssu     marker.hmm   Pfam-A.hmm  silva.nr_v132.tax
```
Equivalently, when running check `test_install.pl`, the warning pops up as it cannot find `nr.db`, which generation, I guess, is dependent on `taxid.db`?

Could it be `sudo` rights?

**Comment by fpusan** [comment]
No need for sudo rights.
You may have run out of disk space.
You can run `download_databases.pl` instead, this will download a pre-compiled database (the last one is only a few months old)

**Comment by pedrosepre** [comment]
Hello, I had a problem, all the DBs were downloaded except taxid.db. How can I download only this DB without repeating the entire download?

**Comment by fpusan** [comment]
See the beginning of the `make_databases.pl` script
https://github.com/jtamames/SqueezeMeta/blob/master/utils/install_utils/make_databases.pl
Starting from line 7, there is a set of flags that control which steps will be executed. You can set the initial ones to zero to make the script restart from the desired step.
What exact error did you get?

**Comment by DeniRibicic** [comment]
Should probably read better the instructions. Thanks, this works.
