### ISSUE TITLE
Problems with anvio-load-sqm (in the run-HMMs step)

### ISSUE THREAD

**Issue by jahid10** [jtamames/SqueezeMeta#761]
Hello,

I have recently tried to parse my SQM project (coassembled) into anvi'o databases with the anvi-load-sqm.py script. My project is run with Squeezemeta 1.5 and anvi'o version is 7.1

Here is the snippet of the problem: 
![Screenshot_18](https://github.com/jtamames/SqueezeMeta/assets/65849689/f0f61047-e113-4e2d-a380-8a280f32c841)

Here's the command I used to load my project:
python3 /home/bioinfo/anaconda3/envs/SqueezeMeta/SqueezeMeta/utils/anvio_utils/anvi-load-sqm.py -p /media/bioinfo/hdd2/Metagenome_jute/metagenom_run_final --run-HMMS --min-contig-length 1200 -o /media/bioinfo/hdd2/Metagenome_jute/metagenom_run_final/anvio_result

**Comment by fpusan** [comment]
What's the output when you run directly the command written at the end of your message? anvi-run-hmms... etc

**Comment by fpusan** [comment]
Also what's the output of `anvi-self-test`?

**Comment by fpusan** [comment]
Can confirm this works for me with anvio v7 and the latest SqueezeMeta release.
However the anvio7 conda package didn't work out of the box and I had to fiddle around with several package versions in order to get `anvi-self-test` working
