### ISSUE TITLE
Problem running the anvi-filter-sqm.py script SMQ2anvio

### ISSUE THREAD

**Issue by apazminov** [jtamames/SqueezeMeta#763]
Hello, 
I am having issues running the anvi-filter-sqm.py script, the previous script (anvi-load-sqm.py) ran succesfully and the CONTIGS.db, PROFILE.db and Taxonomy.txt were created. The issue is as follows: 

Config Error: Something went wrong during subsetting :/ Table names in the parent db (/home/bi
              otechlab/2TB_2/Proyecto_Almohadillas/Samples/Squeezemeta/Squeezemeta_Almohadilla
              s2/anvio/antibiotic_YOLO/CONTIGS.db) and the child db (/home/biotechlab/2TB_2/Pr
              oyecto_Almohadillas/Samples/Squeezemeta/Squeezemeta_Almohadillas2/anvio/antibiot
              ic/SqueezeMeta/CONTIGS.db) does not seem to be identical. The following tables  
              are found in the source, but missing in the target database: ''
Running anvi-interactive with:
anvi-interactive -c /home/biotechlab/2TB_2/Proyecto_Almohadillas/Samples/Squeezemeta/Squeezemeta_Almohadillas2/anvio/antibiotic/SqueezeMeta/CONTIGS.db -p /home/biotechlab/2TB_2/Proyecto_Almohadillas/Samples/Squeezemeta/Squeezemeta_Almohadillas2/anvio/antibiotic/SqueezeMeta/PROFILE.db -t /home/biotechlab/2TB_2/Proyecto_Almohadillas/Samples/Squeezemeta/Squeezemeta_Almohadillas2/anvio/antibiotic/Taxonomy.nwk
Contigs DB ...................................: Initialized:                                             
                                                /home/biotechlab/2TB_2/Proyecto_Almohadillas/Samples/Squeezemeta/Squeezemeta_Almohadillas2/anvio/antibiotic/SqueezeMeta/CONTIGS.db
                                                (v. 21)
Splits taxonomy ..............................: Initiated for taxonomic level for "t_genus"              

Config Error: There is nothing at '/home/biotechlab/2TB_2/Proyecto_Almohadillas/Samples/Squeez
              emeta/Squeezemeta_Almohadillas2/anvio/antibiotic/SqueezeMeta/PROFILE.db' :/

I didn't find any previous thread related to this issue, if you could please help me with this?
The packages specifications are as follows:
SQMtools_1.6.3
anvio-8
SqueezeMeta 1.6.3

Thank you,
Miguel

**Comment by fpusan** [comment]
Probably because you are using anvio v8, as our last supported version is anvio v7.

I can confirm `anvi-filter-sqm.py` works for me with anvio v7 and the latest SqueezeMeta release.

However the anvio7 conda package didn't work out of the box and I had to fiddle around with several package versions in order to get `anvi-self-test` working, Even after doing that, I needed to downgrade the `mistune` package to version 0.8 in order to make everything work.

**Comment by apazminov** [comment]
Hello Fernando,

Thanks for the quick response! I am trying to install anvio v7 following the steps in the anvio installation page but with v7. But I am having problems installing anvio with pip as there are problems builidng the wheels for pandas due to some deprecated packages (pkg_resources is deprecated). If you could please let me know how you were able to install it, it would be really helpful.

Thanks again!

Miguel
________________________________

**Comment by fpusan** [comment]
I started from the bioconda anvio7 package version but then I had to manually update/downgrade several packages until I made It work. I'm many cases I couldn't do It from conda so I used pip instead (but inside the conda environment, of course)
Sorry I can not provide more details, I didn't document the process.
If you still can not manage maybe you can ask the anvio people...

**Comment by apazminov** [comment]
No problem,

Thanks again for all the help!

Greetings,
Miguel
________________________________
