### ISSUE TITLE
Error en los inputs (Please do not use blank spaces in the samples file)

### ISSUE THREAD

**Issue by inej90** [jtamames/SqueezeMeta#765]
Buenas tardes,

Estoy intentando correr el SQM pero tengo un problema respecto a los archivos que contienen las secuencias. Mis archivos tienen nombre como este ejemplo H10_2_7_2022.fastq.gz (son 16 archivos en total). El archivo que contiene los nombres de las muestras está separado por tabulador y lleva el nombre de la muestra, el nombre del archivo que contiene las secuencias y pair1 (dado que son de MinIon).

Cuando pongo el comando para correr el SQM, me sale el mensaje siguiente:

 **Please do not use blank spaces in the samples file** y no sé ¿a qué se debe esto?. Cambié los nombres de los archivos varias veces, pero sigue con el mismo error.

Muchas gracias de antemano.

Un saludo.

**Comment by jtamames** [comment]
Hola
Seguramente has editado o copiado el fichero en un editor de Windows, que mete algunos códigos de control propios que no se ven pero están ahi.
Hay una herramienta que se llama dos2unix que limpia esos códigos extraños. Puedes pasarlos a tu fichero y seguramente solucione el problema. Si no, abre el fichero en un editor, y en cada tabulador borralo e insértalo de nuevo. Eso eliminiará cualquier otro código que haya.
Saludos

**Comment by inej90** [comment]
El fichero lo he creado en linux mediante el comando vim. 

Hice lo que me ha recomendado borrando todo y poniendo de nuevo los nombres y parece que ha funcionado.

Muchas gracias por su ayuda.

Saludos.

**Comment by inej90** [comment]
Muchas gracias Javier.

Saludos.
