### ISSUE TITLE
Visualizar gráficos generados con R y SQMtools

### ISSUE THREAD

**Issue by inej90** [jtamames/SqueezeMeta#768]
Buenos días y feliz año nuevo,

Después de haber corrido el SQM y generado las tablas con el SQMtools, no se pude visualizar los gráficos y me sale el mensaje siguiente:

Warning message:
In doTryCatch(return(expr), name, parentenv, handler) :
  unable to load shared object '/pipe/soft/miniconda/miniconda3/envs/SqueezeMeta/lib/R/modules//R_X11.so':
  libXt.so.6: cannot open shared object file: No such file or directory

¿A qué se debe esto?

Muchas gracias de antemano.

Un saludo.

**Comment by fpusan** [comment]
Qué sistema operativo / distribución / versión estás usando?

**Comment by inej90** [comment]
Buenos días,

Estoy trabajando con windows, cuyo procesador es : 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz. Sin embargo, estoy usando putty para el acceso al servidor que está con Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-89-generic x86_64). La versión del R es 3.6.3 (2020-02-29).

Gracias.

**Comment by fpusan** [comment]
Perdón por el retraso! Puedes sacar otros gráficos? (ejemplo `plot(c(1,2,3), c(1,2,3))`)
Es posible que necesites instalar libXt
https://github.com/tschaffter/rstudio/issues/11
También asegurarte que tienes un tunel X11 funcionando del servidor a tu laptop

**Comment by fpusan** [comment]
Cierro esto por falta de actividad, entiendo que lo pudiste solucionar. En caso contrario reábrelo y lo intentamos arreglar :)

**Comment by inej90** [comment]
Hola,

Al final, el problema era efectivamente la falta del tunel X11 que tenía que plantear. Dejó aquí unos enlaces que me han ayudado a resolverlo mediante la instalación de xming:

https://es.linux-console.net/?p=8933
https://www.youtube.com/watch?v=QRsma2vkEQE

Muchas gracias por mencionarlo.

Un saludo.
