### ISSUE TITLE
Why does sequential mode does not include binning

### ISSUE THREAD

**Issue by slambrechts** [jtamames/SqueezeMeta#77]
Hi,

I would like to compare binning results between co-assembly mode and sequential mode, but the manual states that sequential mode does not include binning. Could you share the reason why? And is this something that might be implemented in the future?

**Comment by jtamames** [comment]
Hello Sam
Yes, it does. Maybe you have a very old version of SqeezeMeta? If so, please update to the current v1.1.
Best,
Javier

**Comment by jtamames** [comment]
Notice that you can install it via conda, that will ease installation and allow it even if you do not have admin privileges

**Comment by slambrechts** [comment]
Hi Javier,

Thank you for your answer. I did not actually try sequential mode yet. I'm only referring to the README.md file where it states "Sequential mode: All samples are treated individually and analysed sequentially. This mode does not include binning."

Glad this has changed, will try!

Best,
Sam

**Comment by jtamames** [comment]
Oh yes, you are rigth! We missed that one. Thank you very much for pointing it out to us. It is fixed now.
Best,
Javier
