### ISSUE TITLE
SqueezeMeta crashes when running on Ubuntu 22 virtualbox computer

### ISSUE THREAD

**Issue by dutchscientist** [jtamames/SqueezeMeta#774]
I am trying to run SqueezeMeta on virtualbox virtual computers, using up-todate Linux 22.04 with up to 14 cores and 98 GB of memory. These virtual computers run Mambaforge/Conda, and have had clean installs of SqueezeMeta in its own environment.

When running SqueezeMeta, we get regular crashes of the virtual computers with errors like:
"The instruction at 0x00007FFBE3236DB2 references memory at 0x0000000000000000. The memory could not be written."

Has not happened before installing/using SqueezeMeta and they have been extensively and heavily used.

Will test the memory and try it on another computer, but any thoughts what this could be? Thanks :)

**Comment by fpusan** [comment]
That one is new to me.
At what step of the pipeline is this happening?
This seems to be related to virtualbox itself eg
https://forums.virtualbox.org/viewtopic.php?t=100002
https://forums.virtualbox.org/viewtopic.php?t=102527
Not sure we can be of help with this...

**Comment by dutchscientist** [comment]
Thanks! Yes, I am beginning to think so as well, it's just that it never happened before on these virtual computers, even when they were stressed and all memory/processors used. Wil test further,, just wanted you to be aware and maybe others have the same.

**Comment by dutchscientist** [comment]
It also starts crashing during file transfers now, so yes, I am afraid it is Virtualbox or the RAM itself. 

I'll close it as it is not related to SqueezeMeta :)

**Comment by fpusan** [comment]
Glad to hear it's not my fault, and good luck solving that one out!

**Comment by dutchscientist** [comment]
Just to let you know, it was Virtualbox indeed. Moved to Hyper-V and it works absolutely fine. My co-worker is happy to start analyzing his data :)

**Comment by fpusan** [comment]
Good to know, glad it works now! :)
