### ISSUE TITLE
Mac installation of SqueezeMeta

### ISSUE THREAD

**Issue by luisymbio** [jtamames/SqueezeMeta#777]
Hi!

I'm trying to install it on conda on a Macbook Pro (using mamba set), but is not able to find some dependencies in the channel fpusan (as perl-dbd-mysql and samtools 1.1)...how I can solve that?

**Comment by fpusan** [comment]
Hi!
We do not support MacOS.
Some people have actually managed to run SqueezeMeta on Mac by manually satisfying all the dependencies and recompiling binaries from source (there are some old issues mentioning that), but this is not something we can help you with.
