### ISSUE TITLE
test_install.pl I got many error

### ISSUE THREAD

**Issue by fpeti11** [jtamames/SqueezeMeta#779]
Hello,

I installed SqueezeMeta to a HPC cluster. But after running  test_install.pl I got many error:

WARNING: Some SqueezeMeta dependencies could not be found in your environment or failed to execute!
	- ERROR: Error running cd /tmp/tmp.VBHvBwvxAR;  --test
	- ERROR: Error running  -h
	- ERROR: Error running  -h
	- ERROR: Error running  --version
	- ERROR: Error running  mem /project/c_ito/anaconda3/envs/SqueezeMeta/SqueezeMeta/utils/install_utils/test_data/ctgs.fasta /project/c_ito/anaconda3/envs/SqueezeMeta/SqueezeMeta/utils/install_utils/test_data/seqs.fq
	- ERROR: Error running  --version
	- ERROR: Error running  version
	- ERROR: Error running  -h
	- ERROR: Error running  -i /project/c_ito/anaconda3/envs/SqueezeMeta/SqueezeMeta/utils/install_utils/test_data/ctgs.fasta -o /tmp/tmp.VBHvBwvxAR/foo.fasta
	- ERROR: Error running  -h
	- ERROR: Error running  -h
	- ERROR: Error running  -h
	SqueezeMeta_conf.pl says that databases are located in  but we can't find nr.db there, or it is corrupted

Can you give me some advice how to solve this problem?

Thank you for your help
Peter

**Comment by fpusan** [comment]
This is weird, it seems that it is not properly reading the configuration file, but it should have died in case it didn't find it...
How did you install it exactly?

**Comment by fpeti11** [comment]
Thank you for the comment. I tried to reinstall the program from zero. The cluster now under maintaince so I could not run now. I will let you know soon if it works properly.

**Comment by fpeti11** [comment]
Hello,
Sorry for the late response, but after reinstall the program I had some difficulties with database. 
I managed to solve them, now the program works fine. Thank you for the help.

**Comment by fpusan** [comment]
Glad to hear! Closing issue
