### ISSUE TITLE
Error in STEP 1 - 01.run_all_assemblies.pl.

### ISSUE THREAD

**Issue by Manso002** [jtamames/SqueezeMeta#780]
Hello,
I just started my very first run on squeezemeta and it failed on step 1. I have seen other issues posted here and I am not sure if it is a memory problem. I am running with 128gB RAM memory and 1.4TB free disk space. 
I've attached syslog file and megahit file as well.

[log.file.zip](https://github.com/jtamames/SqueezeMeta/files/14061905/log.file.zip)
[syslog.file.zip](https://github.com/jtamames/SqueezeMeta/files/14061906/syslog.file.zip)

**Comment by fpusan** [comment]
The exit code -9 in the megahit code would suggest that you ran out of memory.
A bit surprising since you have 128G RAM and not that many samples.
Is this a workstation or a node within a computing cluster?

**Comment by Manso002** [comment]
It is a workstation. 
The fasta files I'm working with occupy about 80gb, could that be an issue?

**Comment by fpusan** [comment]
If by this you mean the total size of the input fastq.gz files, then I suspect this may be indeed the problem. You may want to try using the sequential mode instead

**Comment by Manso002** [comment]
I'll try that out and keep you updated.
Thanks!
