### ISSUE TITLE
Stopped at Step 9/10, 29-01-24

### ISSUE THREAD

**Issue by RM9717** [jtamames/SqueezeMeta#783]
Hi there
I have been using SqueezeMeta v 1.6.3 for a metagenomic analysis for some bacterial samples in fasta format.
Using the guide for the pipeline, I have been using a linux server to do the analysis with the "SqueezeMeta" environment.
I ran the ./test_install.pl command in the environment with the following issue appearing:
![DASTool error](https://github.com/jtamames/SqueezeMeta/assets/158037221/58dac0f3-9940-44d9-8eab-2dd39aa1ee56)

I tried to install using conda, case-sensitive according to the printout, and this appeared:
![notinstallingDASTool](https://github.com/jtamames/SqueezeMeta/assets/158037221/a3b1cc6a-b173-4171-98e0-19a7f4cf1324)

So this time, I used the input provided by the anaconda url, and it says the following:
![alreadyinstalleddas_tool](https://github.com/jtamames/SqueezeMeta/assets/158037221/db2de369-b850-4e87-9815-94733cf0f8aa)
However it is not located when running the "test_install.pl" command. 

I did try to install directly in the R environment in the console itself with devtools installed but this appeared again:
![devtoolsRDASToolnotworking](https://github.com/jtamames/SqueezeMeta/assets/158037221/e02c1384-2683-483d-a560-341247167e02)

I am aware that I changed and installed a new environment you recommended to another user whom had an issue with the SqueezeMeta step 10 where the environment created was "SqueezeMeta_dev", so i tried it and all the dependencies were installed, even DAStool, but not mothur -h .
However it only managed to reach step 4 of the procedure when using it.

Now when i used the original SqueezeMeta environment for 2 different projects, "Biofilm2" and "Biofilm3"
I was halted at Steps 9 and 10 in this procedure, respectively.

The following printouts were given

Biofilm2, Step 9
**/mnt/shared_data/RajeshMali/SqueezeMeta/scripts/SqueezeMeta.pl -m merged -p Biofilm2 -extassembly Biofilm2.1.fasta Biofilm2.2.fasta -s samples.txt -f ./ --minion -t 8 -lowmem**
samples.txt 
**Biofilm2        Biofilm2.1.fasta       pair1
Biofilm2        Biofilm2.2.fasta       pair2**

![Meta2 1](https://github.com/jtamames/SqueezeMeta/assets/158037221/1c154593-9c92-40f1-b932-691f9f4fbdde)
![Meta2 2](https://github.com/jtamames/SqueezeMeta/assets/158037221/3799167e-13ba-4161-8e81-fe98031c0953)

Biofilm3, Step 10
**/mnt/shared_data/RajeshMali/SqueezeMeta/scripts/SqueezeMeta.pl -m merged -p Biofilm3 -extassembly Biofilm3.1a.fasta Biofilm3.1b.fasta Biofilm3.2a.fasta Biofilm3.2b.fasta -s samples.txt -f ./ --minion -t 8 -lowmem**
samples.txt 
**Biofilm3        Biofilm3.1a.fasta       pair1
Biofilm3        Biofilm3.2a.fasta       pair2
Biofilm3        Biofilm3.1b.fasta       pair1
Biofilm3        Biofilm3.2b.fasta       pair2**

![Meta1](https://github.com/jtamames/SqueezeMeta/assets/158037221/9b23452f-bcd3-44da-b403-cdb40a8cbb61)
![Meta2](https://github.com/jtamames/SqueezeMeta/assets/158037221/9a196099-be30-461d-942a-e8787a78d64d)
![Meta3](https://github.com/jtamames/SqueezeMeta/assets/158037221/159681f6-f8ec-49b2-9d09-4c25ddee1828)

Is there any way to resolve these conflicts?

Many thanks for your help!

**Comment by RM9717** [comment]
So the issue is I cannot download the entirety of the databases from github using the gitclone feature as there are some connection issues when try to fetch the files directly from the URL.

The way I did it was to install those first on a Linux computer. I ran the gitclone, and it worked after using noconfiguredb.pl, but after converting to fasta, adding the samples.txt file accordingly, the analysis took very long to operate (nearly 3 weeks to reach that step, and it failed). So i transferred those large files, such as Diamond etc., onto an external SSD and uploaded them using WinSCP to access and configure using Putty in the Linux server with the latest versions of 1.6.3.
Therefore, I had to manually install the dependencies one by one, according to the library requirements.

**Comment by fpusan** [comment]
You don't use git clone to install the databases, we have a script for that.
Can't you just use conda as recommended in our ReadMe? Of course you'll need to do this in your Linux server

**Comment by RM9717** [comment]
My mistake I meant I could not install the databases directly from the terminal using either make_databases.pl or download_databases.pl in the command line as this server has sudo restrictions, so i tried to use conda, but it didn't work.
![makedbfail](https://github.com/jtamames/SqueezeMeta/assets/158037221/02dfa97a-ea69-40ac-aff6-2f2e5e9c873b)
![downloaddbfail](https://github.com/jtamames/SqueezeMeta/assets/158037221/65596807-29b6-4978-9d0d-e7114d00dce4)
I also tried using conda to install DASTool but its not working.

**Comment by fpusan** [comment]
You also need sudo access also for doing the manual installation (see the `INSTALL-CENTOS7` or `INSTALL-UBUNTU20` files)
You will need to discuss this with your server administrator (I'd recommend that they do it using conda if possible).
