### ISSUE TITLE
erro in step1 coassembly~

### ISSUE THREAD

**Issue by zhangbenbenchina** [jtamames/SqueezeMeta#785]
<img width="740" alt="image" src="https://github.com/jtamames/SqueezeMeta/assets/143200215/61958797-a713-42f5-9de8-e80ece72636f">
<img width="764" alt="image" src="https://github.com/jtamames/SqueezeMeta/assets/143200215/c40fe56d-8a38-4b17-a8f8-d3af402aec40">
 
Hello Professor, I have five samples here that have been individually spliced. I want to mix and splice them again, but I only have spliced data in FASTA format. I'm not sure if the 'extassembly' parameter is set incorrectly.
[Shotgun_samplefiles1.txt](https://github.com/jtamames/SqueezeMeta/files/14110289/Shotgun_samplefiles1.txt)
[squeezemeta1-slurmtxt.txt](https://github.com/jtamames/SqueezeMeta/files/14110300/squeezemeta1-slurmtxt.txt)

**Comment by zhangbenbenchina** [comment]
/public/home/zhanglj/miniconda3/envs/squeezeMeta/SqueezeMeta/scripts/SqueezeMeta.pl -m coassembly -p shotgun1 -s Shotgun_samplefiles1.txt -f /public/home/zhanglj/Squeezemeta_20240108/assmblydata/ --euk -taxbinmode s+c -t 64

**Comment by jtamames** [comment]
Hello
Looks good to me.. are you running in any error?

**Comment by zhangbenbenchina** [comment]
> 你好， 我觉得不错..你运行时有什么错误吗？

Thank you for your response, Professor. Here is the error message I encountered.
[syslog.txt](https://github.com/jtamames/SqueezeMeta/files/14110409/syslog.txt)

step1:I have two sets of parallel samples. In each set, there are two files, such as FQ11 and FQ12 in the first set (FQ1 group). Initially, I merge the data from these two individual files within each set, and then I use the resulting combined data as input for further analysis.

step2: run pipline

**Comment by jtamames** [comment]
I don´t know if I understand correctly what you want to do. Do you want to analyze your five samples separately? If so, then specify mode sequential (-m sequential) and try again, it should work.
Best,
J

**Comment by zhangbenbenchina** [comment]
Professor, i want to five smaples mix as one sample to analysis (coassembly)

**Comment by jtamames** [comment]
Then just run the coassembly, but don´t specify the extassembly in the samples file

**Comment by zhangbenbenchina** [comment]
Thank you very much for your guidance. I understand now, and I will continue with my attempts accordingly.

**Comment by zhangbenbenchina** [comment]
STEP10 -> 10.mapsamples.pl  [erro]([url]([url]([Uploading syslog.txt…]())))

Hello professor, I was able to run it normally under your guidance yesterday, but today I found an error in step 10 stopping;


[19 hours, 13 minutes, 34 seconds]: STEP10 -> 10.mapsamples.pl
Creating Bowtie reference: python3 /mnt/hpc/home/zhanglj/miniconda3/envs/squeezeMeta/SqueezeMeta/bin/bowtie2/bowtie2-build --quiet /mnt/hpc/home/zhanglj/Squeezemeta_20240108/shotgun1/results/01.shotgun1.fasta /mnt/hpc/home/zhanglj/Squeezemeta_20240108/shotgun1/data/shotgun1.bowtie
Getting raw reads for FQ1: cp /public/home/zhanglj/Squeezemeta_20240108/assmblydata//FQ1.fasta /mnt/hpc/home/zhanglj/Squeezemeta_20240108/shotgun1/temp/shotgun1.FQ1.current_1; 
Aligning with bowtie: /mnt/hpc/home/zhanglj/miniconda3/envs/squeezeMeta/SqueezeMeta/bin/bowtie2/bowtie2 -x /mnt/hpc/home/zhanglj/Squeezemeta_20240108/shotgun1/data/shotgun1.bowtie -f -U /mnt/hpc/home/zhanglj/Squeezemeta_20240108/shotgun1/temp/shotgun1.FQ1.current_1  --quiet -p 64 -S /mnt/hpc/home/zhanglj/Squeezemeta_20240108/shotgun1/data/bam/shotgun1.FQ1.sam --very-sensitive-local
Stopping in STEP10 -> 10.mapsamples.pl. Program finished abnormally

**Comment by jtamames** [comment]
Try running this command and see if it works:

`/mnt/hpc/home/zhanglj/miniconda3/envs/squeezeMeta/SqueezeMeta/bin/bowtie2/bowtie2 -x /mnt/hpc/home/zhanglj/Squeezemeta_20240108/shotgun1/data/shotgun1.bowtie -f /mnt/hpc/home/zhanglj/Squeezemeta_20240108/shotgun1/temp/shotgun1.FQ1.current_1 -U /mnt/hpc/home/zhanglj/Squeezemeta_20240108/shotgun1/temp/shotgun1.FQ1.current_1 --quiet -p 64 -S /mnt/hpc/home/zhanglj/Squeezemeta_20240108/shotgun1/data/bam/shotgun1.FQ1.sam --very-sensitive-local`

**Comment by zhangbenbenchina** [comment]
no results。 
<img width="1212" alt="image" src="https://github.com/jtamames/SqueezeMeta/assets/143200215/b1ca6f1d-caf4-4b28-84f2-3f55e4da2dc2">

**Comment by jtamames** [comment]
The command is a single line. You typed it as several separated lines

**Comment by zhangbenbenchina** [comment]
<img width="827" alt="image" src="https://github.com/jtamames/SqueezeMeta/assets/143200215/a890034e-5cc5-4298-8728-39729a18335a">

**Comment by zhangbenbenchina** [comment]
> 该命令是一行。您将其输入为几行分隔的行

Hello professor, it seems that there is a problem with my input file. Is it because I use the spliced (fasta file) as input? In this case, how should I modify it?

**Comment by jtamames** [comment]
This is because you are using a single unpaired fasta file, which is rather unusual. Try this:

`/mnt/hpc/home/zhanglj/miniconda3/envs/squeezeMeta/SqueezeMeta/bin/bowtie2/bowtie2 -x /mnt/hpc/home/zhanglj/Squeezemeta_20240108/shotgun1/data/shotgun1.bowtie -f /mnt/hpc/home/zhanglj/Squeezemeta_20240108/shotgun1/temp/shotgun1.FQ1.current_1 --quiet -p 64 -S /mnt/hpc/home/zhanglj/Squeezemeta_20240108/shotgun1/data/bam/shotgun1.FQ1.sam --very-sensitive-local`

in a single line, as above. This should produce a `/mnt/hpc/home/zhanglj/Squeezemeta_20240108/shotgun1/data/bam/shotgun1.FQ1.sam` file.

**Comment by zhangbenbenchina** [comment]
> 这是因为您使用的是单个未配对的 fasta 文件，这是相当不寻常的。尝试这个：
> 
> `/mnt/hpc/home/zhanglj/miniconda3/envs/squeezeMeta/SqueezeMeta/bin/bowtie2/bowtie2 -x /mnt/hpc/home/zhanglj/Squeezemeta_20240108/shotgun1/data/shotgun1.bowtie -f /mnt/hpc/home/zhanglj/Squeezemeta_20240108/shotgun1/temp/shotgun1.FQ1.current_1 --quiet -p 64 -S /mnt/hpc/home/zhanglj/Squeezemeta_20240108/shotgun1/data/bam/shotgun1.FQ1.sam --very-sensitive-local`
> 
> 在一行中，如上所述。这应该会生成一个`/mnt/hpc/home/zhanglj/Squeezemeta_20240108/shotgun1/data/bam/shotgun1.FQ1.sam`文件。

Yes, it can run when I change the parameter to -f. How should I modify it in script.pl? (The reason is: there was insufficient memory when coassembly splicing the 100G original data; I could only splice a single piece first and then use it as input to continue the mixed assembly)

**Comment by zhangbenbenchina** [comment]
meighit results is a （.fasta ）type, so i used the results  as input.

**Comment by jtamames** [comment]
Ok, then do the following:
1) Locate where your SqueezeMeta is installed. You can know this using the command `conda info --envs`. Look for "SqueezeMeta". The listed path is where all the scripts from SqueezeMeta are stored.
2) Edit the script 10.mapsamples.pl in the scripts directory. Look for the following lines (lines 242-243 in the latest version)
```
if(-e "$tempdir/$par2name") { $command="$bowtie2_x_soft -x $bowtieref $formatoption -1 $tempdir/$par1name -2 $tempdir/$par2name --quiet -p $numthreads -S $samfile $mapping_options"; }
else { $command="$bowtie2_x_soft -x $bowtieref $formatoption -U $tempdir/$par1name  --quiet -p $numthreads -S $samfile $mapping_options"; } }
```
3) Modify these in this way:
```
if(-e "$tempdir/$par2name") { $command="$bowtie2_x_soft -x $bowtieref $formatoption -1 $tempdir/$par1name -2 $tempdir/$par2name --quiet -p $numthreads -S $samfile $mapping_options"; }
elsif($formatseq eq "fasta")  { $command="$bowtie2_x_soft -x $bowtieref $formatoption $tempdir/$par1name  --quiet -p $numthreads -S $samfile $mapping_options"; } 
else { $command="$bowtie2_x_soft -x $bowtieref $formatoption -U $tempdir/$par1name  --quiet -p $numthreads -S $samfile $mapping_options"; } }
```
4) Restart SqueezeMeta from step 10: 
`/public/home/zhanglj/miniconda3/envs/squeezeMeta/SqueezeMeta/scripts/SqueezeMeta.pl -p shotgun1 --restart -step 10`

This should do it

**Comment by zhangbenbenchina** [comment]
Thank you very much for the professor's guidance. I have modified it and it is running now.

**Comment by jtamames** [comment]
Nice to hear. Closing issue

**Comment by zhangbenbenchina** [comment]
I'm very sorry, Professor, it didn't work after re-running~ Is it because of memory? (Single node is 520G, I set it to 480G memory) Or is it because of other reasons?

[syslog.txt](https://github.com/jtamames/SqueezeMeta/files/14124750/syslog.txt)
[squeezemeta1.slurm.txt](https://github.com/jtamames/SqueezeMeta/files/14124751/squeezemeta1.slurm.txt)

![image](https://github.com/jtamames/SqueezeMeta/assets/143200215/739c364b-339c-45d2-96d6-7c8c4cea67d8)

**Comment by zhangbenbenchina** [comment]
> 很高兴听到结题
 
still not run successfuly~

**Comment by jtamames** [comment]
According to the picture, I see that you didn´t do the changes that I suggested. Please follow the instructions above and try again.

**Comment by jtamames** [comment]
What happens if you run:
/mnt/hpc/home/zhanglj/miniconda3/envs/squeezeMeta/SqueezeMeta/bin/bowtie2/bowtie2 -x /mnt/hpc/home/zhanglj/Squeezemeta_20240108/shotgun1/data/shotgun1.bowtie -f /mnt/hpc/home/zhanglj/Squeezemeta_20240108/shotgun1/temp/shotgun1.FQ1.current_1 -p 64 -S /mnt/hpc/home/zhanglj/Squeezemeta_20240108/shotgun1/data/bam/shotgun1.FQ1.sam --very-sensitive-local

**Comment by zhangbenbenchina** [comment]
> What happens if you run: `/mnt/hpc/home/zhanglj/miniconda3/envs/squeezeMeta/SqueezeMeta/bin/bowtie2/bowtie2 -x /mnt/hpc/home/zhanglj/Squeezemeta_20240108/shotgun1/data/shotgun1.bowtie -f /mnt/hpc/home/zhanglj/Squeezemeta_20240108/shotgun1/temp/shotgun1.FQ1.current_1 -p 64 -S /mnt/hpc/home/zhanglj/Squeezemeta_20240108/shotgun1/data/bam/shotgun1.FQ1.sam --very-sensitive-local`

I try it now
