### ISSUE TITLE
Error running Sequential mode with external assemblies 

### ISSUE THREAD

**Issue by Riccardo-Frizzo** [jtamames/SqueezeMeta#790]
Hello! I have found an issue when running the pipeline in sequential mode with external assemblies.

I've fixed [issue #743](https://github.com/jtamames/SqueezeMeta/issues/743) as you suggested, but then ran into another problem:

The external assembly path provided in the "_samples_" file is recognized, prompting the message:
`"External assembly provided: . Overriding assembly" `
then the path information is somehow lost, resulting in the message:
`"Can't find assembly file"`

I think the error is around the if statement at line 71 of 01.run_all_assemblies.pl.
I've changed line 72 from 
``` 
$outassembly=$extassembly; 
```
to
```
$extassembly=$extassemblies{$asamples}; $outassembly=$extassembly;
```
and managed to get the pipeline going.

Would this work or would you suggest a better fix?

Thank you and have a nice evening,
Riccardo

![Screenshot from 2024-02-07 17-35-58](https://github.com/jtamames/SqueezeMeta/assets/155966437/2f171ec6-53dc-4be7-a41a-57e49809f45c)

[sequential_extassembly.zip](https://github.com/jtamames/SqueezeMeta/files/14196705/sequential_extassembly.zip)

**Comment by jtamames** [comment]
Hello!
I myself run into this but last week, and corrected just as you did. Thank you for this!
Best,
J

**Comment by Riccardo-Frizzo** [comment]
Awesome! Thank you!
