### ISSUE TITLE
Some SqueezeMeta dependencies could not be found

### ISSUE THREAD

**Issue by Manso002** [jtamames/SqueezeMeta#792]
Hello.
I am trying to use SQMtools for the first time but i cant install it, i have tried everything.
I run /home/meridian/miniconda3/envs/SqueezeMeta/SqueezeMeta/utils/install_utils/test_install.pl and get the following message:

WARNING: Some SqueezeMeta dependencies could not be found in your environment or failed to execute!
	- Missing R library "doMC"
	- Missing R library "ggplot2"
	- Missing R library "data.table"
	- Missing R library "reshape2"
	- Missing R library "pathview"
	- Missing R library "DASTool"
	- Missing R library "SQMtools"

I tried to install them using sudo R and everything worked except pathview and SQMtools.
Based on others issues (#258), i tried running configure_nodb.pl after succesfully installing some packages with sudo R but i keep getting the same message when running test_install.pl

Thanks in advance.
Greetings

**Comment by fpusan** [comment]
You shouldn't be needing sudo for this. Are you using out conda package for installation?

**Comment by Manso002** [comment]
Thanks for the fast response.
Yes, I am using conda package for installation and working under squeezemeta environment.

**Comment by fpusan** [comment]
Try creating an environment from scratch without sudo.
What is your OS distribution and version?

**Comment by Manso002** [comment]
Im working with ubuntu 20+ v.6.1.0-1029-oem

**Comment by Manso002** [comment]
That was the problem! I created a new enviroment without sudo and everything works fine.
Thanks a lot.

**Comment by fpusan** [comment]
Glad to hear! Closing issue
