### ISSUE TITLE
rna sqmtools erro

### ISSUE THREAD

**Issue by zhangbenbenchina** [jtamames/SqueezeMeta#793]
<img width="591" alt="image" src="https://github.com/jtamames/SqueezeMeta/assets/143200215/c1e85718-c2ad-4a86-83af-0460d701e444">
<img width="498" alt="image" src="https://github.com/jtamames/SqueezeMeta/assets/143200215/7370f181-ca35-4da4-8ae0-f6e0f95c1e7d">

hello， jtamames ~ After running squeezemeta successfully ends, when using sqmtools to load data() for analysis, it is not recognized.

[syslog.txt](https://github.com/jtamames/SqueezeMeta/files/14331139/syslog.txt)

**Comment by fpusan** [comment]
This seems correct. There are no binning results (you can't get bins from metatranscriptomic data) but this is just a warning. The data should be loaded correctly.

**Comment by zhangbenbenchina** [comment]
> 这似乎是正确的。没有分箱结果（您无法从元转录组数据中获取分箱），但这只是一个警告。数据应该正确加载。
![image](https://github.com/jtamames/SqueezeMeta/assets/143200215/7bd98eb3-e713-4978-a98b-7071042ab16d)
ERRO as 
<img width="355" alt="image" src="https://github.com/jtamames/SqueezeMeta/assets/143200215/3aa58e28-e5e9-4fbd-9006-b6abcb7f201c">

**Comment by fpusan** [comment]
Don't know what you mean with this screenshot.
But `summary(metatrans)` should show that your project was loaded correctly.

**Comment by zhangbenbenchina** [comment]
<img width="772" alt="image" src="https://github.com/jtamames/SqueezeMeta/assets/143200215/f855bdc8-50fe-4df5-8481-1ed07c671f4f">

I want to refer to this step for analysis, but the data() data cannot be loaded correctly, causing subsequent analysis to fail.

<img width="517" alt="image" src="https://github.com/jtamames/SqueezeMeta/assets/143200215/fd5fcd87-705d-4d1e-b6e9-0fd2bfb9ed5c">

**Comment by zhangbenbenchina** [comment]
<img width="541" alt="image" src="https://github.com/jtamames/SqueezeMeta/assets/143200215/a1e7ba2a-488f-4795-94e2-75da2bb4a135">

now i stay at /mnt/hpc/home/zhanglj/Squeezemeta_20240108/FQ1toDJ，project name is： allshotgun

**Comment by fpusan** [comment]
The `data` command is used to load our example data, but you don't need it since you have your own data (loaded under the variable name `shotgun` according to your screenshot above).
Your idea was right but there is a typo in your code:
`shotgun.carb == subsetFun(shotgun, "Carbohydrate metabolism")`
You used the `==` operator (tests for equality) rather than `=` (used to assign variables). So it should be
`shotgun.carb = subsetFun(shotgun, "Carbohydrate metabolism")`

**Comment by zhangbenbenchina** [comment]
Thank you very much for the professor's answer. The problem has been solved~
