### ISSUE TITLE
--nocog --nokegg --nopfam

### ISSUE THREAD

**Issue by slambrechts** [jtamames/SqueezeMeta#80]
Hi,

For a specific project I'm interested in using SqueezeMeta purely for assembly, binning and bin refinement of a large amount of samples in sequential mode. Specifically, I don't need taxonomic and functional annotation this time. Therefore I tried running SqueezeMeta like so:

`SqueezeMeta.pl -m sequential -t 10 -s oxford.samples -f CLEAN_READS/ -a spades -c 500 --nocog --nokegg --nopfam`

But when I do, SqueezeMeta exits because of the following:

```
Stopping in STEP7 -> 07.fun3assign.pl. Files /home/slambrecht/oxford/R77258/results/07.R77258.fun3.cog, /home/slambrecht/oxford/R77258/results/07.R77258.fun3.kegg and /home/slambrecht/oxford/R77258/results/07.R77258.fun3.pfam are empty!
Died at /home/slambrecht/miniconda2/envs/SqueezeMeta/bin/SqueezeMeta.pl line 788.
```
Is there a way of skipping functional and taxonomic annotation?

Best,
Sam

**Comment by jtamames** [comment]
Hello again
That is indeed a malfunction  of the program, we will fix it asap.
In the meantime, you can simply comment the lines 787 and 788 in SqueezeMeta.pl, the ones that read:

if(($wsizeCOG<2) && ($wsizeKEGG<2) && ($wsizePFAM<2) && ($optdbsw<2)) {
	print RED; print "Stopping in STEP7 -> $scriptname. Files $fun3cog, $fun3kegg and $fun3pfam are empty!\n"; print RESET; die; }

That will skip the check for presence of functional annotations.
Thank you for reporting this.

Best,
Javier

**Comment by jtamames** [comment]
If you want to restart your run instead of running it again, the corresponing lines in the restart.pl script are number 265 and 266. Then restart it as usual.
Best,

**Comment by slambrechts** [comment]
Thank you, will try!

**Comment by slambrechts** [comment]
Later in the pipeline this causes:

```
Stopping in STEP21 -> 21.minpath.pl. File /home/slambrecht/oxford/R77258/results/21.R77258.kegg.pathways is empty!
Died at /home/slambrecht/miniconda2/envs/SqueezeMeta/bin/SqueezeMeta.pl line 1081.
```
I'm guessing commenting line 1081 might solve this? Will try!

Best,
Sam

**Comment by jtamames** [comment]
Closing issue, adding --notax flag in upcoming versions
