### ISSUE TITLE
Assemble stopped abnormally.

### ISSUE THREAD

**Issue by RIJP-SU** [jtamames/SqueezeMeta#801]
Hi, I really enjoy SqueezeMeta, this makes us possible to analyze variety of sleeping shot-gun data.
This time, I tried to analayze relatively bigger data (total size of fastq.gz files is about 100GB).
First, I got an error while assembling the files from one sample by spade (let's say the name of sample is "sampleA").
Error meessage is "finished abnormally, OS return value: -6".

But when I restart the analysis by SqueezeMeta, it proceeds the assembles to next file keeping the assmebled file "01.SampleA.fasta" and "01.SampleA.fasta.prov" as 0 MB.

After finishing spade step, I got an error again at the step of "Getting overlaps".
The error message shown is

"Error running command:    /home/username/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/AMOS/minimus2 /media/username/DATA-Disk2/2024Virome/Combined_Analysis/Virome/temp/mergedassemblies.Virome.99 -D OVERLAP=100 -D MINID=95 -D THREADS=30 >> /media/username/DATA-Disk2/2024Virome/Combined_Analysis/Virome/syslog 2>&1 at /home/username/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/01.merge_assemblies.pl line 71.
Stopping in STEP1 -> 01.merge_assemblies.pl. Program finished abnormally
Died at /home/username/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/01.run_all_assemblies.pl line 233.
Stopping in STEP1 -> 01.run_all_assemblies.pl. Program finished abnormally

  If you don't know what went wrong or want further advice, please look for similar issues in https://github.com/jtamames/SqueezeMeta/issues
  Feel free to open a new issue if you don't find the answer there. Please add a brief description of the problem and upload the /media/username/DATA-Disk2/2024Virome/Combined_Analysis/Virome/syslog file (zip it first)
Died at /home/username/miniconda3/envs/SqueezeMeta/bin/SqueezeMeta.pl line 941."
 

Error message in runAmos.log is 
"terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)".

I would be grateful if any of solution can be given.
Is the problem on the first error by spade?

**Comment by fpusan** [comment]
Hi!
Check the "Choosing an assembly strategy" section in the readme. Your data is probably too big for the `merged` or `seqmerge` modes. You could try doing a coassembly (but it is likely to also run out of memory). Otherwise try using the `sequential` mode
