### ISSUE TITLE
anvi-filter-sqm.py Config Error

### ISSUE THREAD

**Issue by DioufMouss0** [jtamames/SqueezeMeta#806]
Hello Professor, I am trying to use the  anvi-filter-sqm.py for filtering and vizualize with anvio but I am having thi serror (picture attached).

could you please help with this.

thanks

![Screenshot from 2024-03-04 09-28-28](https://github.com/jtamames/SqueezeMeta/assets/108735497/9e7a3381-f2b8-49ef-b379-28f94deacd7f)

**Comment by fpusan** [comment]
What version of anvi'o are you using?
Is `anvi-self-test` working ok?

**Comment by DioufMouss0** [comment]
I am using anvio 8
yes anvi-self-test is working (attached picture)
![Screenshot from 2024-03-04 11-13-43](https://github.com/jtamames/SqueezeMeta/assets/108735497/6d8484dd-608b-424b-9319-4b547c5df374)

**Comment by fpusan** [comment]
Try using anvio7, sqm2anvio is not compatible with anvio8

**Comment by DioufMouss0** [comment]
Working now thanks

**Comment by fpusan** [comment]
Glad to hear, closing issue!
