### ISSUE TITLE
cazy -extdb

### ISSUE THREAD

**Issue by Panda-smile** [jtamames/SqueezeMeta#807]
教授您好，我在添加cazy数据库时遇到问题，不知道如何解决？（将cazy注释到现有项目shotguntrans中），期待您的回复。（微笑~）

[CAZyDB.Annotation.txt](https://github.com/jtamames/SqueezeMeta/files/14480816/CAZyDB.Annotation.txt)
[db.list.txt](https://github.com/jtamames/SqueezeMeta/files/14480820/db.list.txt)

运行： /public/home/zhanglj/miniconda3/envs/squeezeMeta/SqueezeMeta/utils/add_database.pl shotguntrans db.list

 CazyDB /public/home/zhanglj/squeezemetatrans/Squeezemetacazy /public/home/zhanglj/squeezemetatrans/Squeezemetacazy/CAZyDB.AnnotationError: Invalid parameter count for option '--db'
Error running command:    /mnt/hpc/home/zhanglj/miniconda3/envs/squeezeMeta/SqueezeMeta/bin/diamond blastp -q /mnt/hpc/home/zhanglj/squeezemetatrans/shotguntrans/results/03.shotguntrans.faa -p 8 -d  -e 0.001 --id 30 --quiet -b NF -f 6 qseqid qlen sseqid slen pident length evalue bitscore qstart qend sstart send -o /mnt/hpc/home/zhanglj/squeezemetatrans/shotguntrans/intermediate/04.shotguntrans.CazyDB /public/home/zhanglj/squeezemetatrans/Squeezemetacazy /public/home/zhanglj/squeezemetatrans/Squeezemetacazy/CAZyDB.Annotation.diamond at /public/home/zhanglj/miniconda3/envs/squeezeMeta/SqueezeMeta/utils/add_database.pl line 71, <infile1> line 0.000000.

**Comment by Panda-smile** [comment]
Thanks for professor, I just finally solved it

**Comment by jtamames** [comment]
Glad to hear!
