### ISSUE TITLE
restart.pl for sequential mode

### ISSUE THREAD

**Issue by slambrechts** [jtamames/SqueezeMeta#81]
Hi,

For sequential mode the name under which all results and data is saved is taken from the samples file, so one map for each sample in the samples file. Is it possible to use the -p parameter in sequential mode, and later use that name to restart a complete sequential mode project, instead of just the sample that was running at the time of the error/interruption?

To clarify, I was running a project in sequential mode without the -p parameter, and I'm wondering whether I can restart the whole project? I can see a global_progress file in the working directory but I'm not sure how to use it

Best,
Sam

**Comment by jtamames** [comment]
Hello Sam
That is indeed a limitation in the actual setting. We will restructure the sequential mode as to be able to restart individual projects. Rigth now the -p option is not working in sequential mode.
Best,
Javier

**Comment by slambrechts** [comment]
Hi Javier,

Ok. I can manage ofcourse, by removing the samples that already finished from the samples file. Nevertheless, looking forward to it!
Best,
Sam
