### ISSUE TITLE
SQM for genomics

### ISSUE THREAD

**Issue by inej90** [jtamames/SqueezeMeta#817]
Dear Javier,

I would like to know if I can use SQM also for genomic analysis. If so, do I need to choose any specific tool to do it.

Thank you in advance.

**Comment by jtamames** [comment]
Hello
Sorry for my late response. The SqueezeMeta suite has a script for annotating genomes. It is named sqm_annot.pl Could that suit your needs?
Best,
J

**Comment by inej90** [comment]
Hello, 

This is actually what I was looking for. So to launch the analysis on genomes, just by using this script we can obtain results?

Thank you for your response.

**Comment by jtamames** [comment]
Yes. It does the same than SqueezeMeta, but for sets of sequences, including genomes. It skips the binning steps (nosense if just trying to annotate a bunch of genomic sequences)
Best,
J

**Comment by inej90** [comment]
Great. Thank you for your answer.
