### ISSUE TITLE
Error when in step 1 Assembly with megahit

### ISSUE THREAD

**Issue by gallegobq** [jtamames/SqueezeMeta#818]
Hi, i did run a work with coassembly mode but this, after than hours give a error

SqueezeMeta.pl -m coassembly -s samples.txt -p Lixiviados -f /media/metagenomica/HDD/F22FTSUSAT1160-01_ENVkxwbM/soapnuke/clean/ --extdb my-dblist.txt 
***
SqueezeMeta v1.6.3, September 2023 - (c) J. Tamames, F. Puente-SÃ¡nchez CNB-CSIC, Madrid, SPAIN

Please cite: Tamames & Puente-Sanchez, Frontiers in Microbiology 9, 3349 (2019). doi: https://doi.org/10.3389/fmicb.2018.03349

Run started Sat Mar 23 02:59:29 2024 in coassembly mode
6 metagenomes found: NM1 NM2 PAT1 PAT2 PATT1 PATT2

[0 seconds]: STEP1 -> RUNNING ASSEMBLY: 01.run_all_assemblies.pl (megahit)
  Concatenating all samples:  NM1_1.fq.gz  NM1_2.fq.gz  NM2_1.fq.gz  NM2_2.fq.gz  PAT1_1.fq.gz  PAT1_2.fq.gz  PAT2_1.fq.gz  PAT2_2.fq.gz  PATT1_1.fq.gz  PATT1_2.fq.gz  PATT2_1.fq.gz  PATT2_2.fq.gz 
    pair1: cat /media/metagenomica/HDD/F22FTSUSAT1160-01_ENVkxwbM/soapnuke/clean//NM1_1.fq.gz /media/metagenomica/HDD/F22FTSUSAT1160-01_ENVkxwbM/soapnuke/clean//NM2_1.fq.gz /media/metagenomica/HDD/F22FTSUSAT1160-01_ENVkxwbM/soapnuke/clean//PAT1_1.fq.gz /media/metagenomica/HDD/F22FTSUSAT1160-01_ENVkxwbM/soapnuke/clean//PAT2_1.fq.gz /media/metagenomica/HDD/F22FTSUSAT1160-01_ENVkxwbM/soapnuke/clean//PATT1_1.fq.gz /media/metagenomica/HDD/F22FTSUSAT1160-01_ENVkxwbM/soapnuke/clean//PATT2_1.fq.gz > /media/metagenomica/HDD/F22FTSUSAT1160-01_ENVkxwbM/soapnuke/clean/Lixiviados/data/raw_fastq/par1.fastq.gz
    pair2: cat /media/metagenomica/HDD/F22FTSUSAT1160-01_ENVkxwbM/soapnuke/clean//NM1_2.fq.gz /media/metagenomica/HDD/F22FTSUSAT1160-01_ENVkxwbM/soapnuke/clean//NM2_2.fq.gz /media/metagenomica/HDD/F22FTSUSAT1160-01_ENVkxwbM/soapnuke/clean//PAT1_2.fq.gz /media/metagenomica/HDD/F22FTSUSAT1160-01_ENVkxwbM/soapnuke/clean//PAT2_2.fq.gz /media/metagenomica/HDD/F22FTSUSAT1160-01_ENVkxwbM/soapnuke/clean//PATT1_2.fq.gz /media/metagenomica/HDD/F22FTSUSAT1160-01_ENVkxwbM/soapnuke/clean//PATT2_2.fq.gz > /media/metagenomica/HDD/F22FTSUSAT1160-01_ENVkxwbM/soapnuke/clean/Lixiviados/data/raw_fastq/par2.fastq.gz
  Running assembly with megahit: perl /home/metagenomica/anaconda3/envs/sqm/SqueezeMeta/lib/SqueezeMeta/assembly_megahit.pl /media/metagenomica/HDD/F22FTSUSAT1160-01_ENVkxwbM/soapnuke/clean/Lixiviados Lixiviados /media/metagenomica/HDD/F22FTSUSAT1160-01_ENVkxwbM/soapnuke/clean/Lixiviados/data/raw_fastq/par1.fastq.gz /media/metagenomica/HDD/F22FTSUSAT1160-01_ENVkxwbM/soapnuke/clean/Lixiviados/data/raw_fastq/par2.fastq.gz
Error running command:    /home/metagenomica/anaconda3/envs/sqm/SqueezeMeta/bin/megahit/megahit  -1 /media/metagenomica/HDD/F22FTSUSAT1160-01_ENVkxwbM/soapnuke/clean/Lixiviados/data/raw_fastq/par1.fastq.gz -2 /media/metagenomica/HDD/F22FTSUSAT1160-01_ENVkxwbM/soapnuke/clean/Lixiviados/data/raw_fastq/par2.fastq.gz -t 12 -o /media/metagenomica/HDD/F22FTSUSAT1160-01_ENVkxwbM/soapnuke/clean/Lixiviados/data/megahit >> /media/metagenomica/HDD/F22FTSUSAT1160-01_ENVkxwbM/soapnuke/clean/Lixiviados/syslog 2>&1 at /home/metagenomica/anaconda3/envs/sqm/SqueezeMeta/lib/SqueezeMeta/assembly_megahit.pl line 36.
Assembly not present in /media/metagenomica/HDD/F22FTSUSAT1160-01_ENVkxwbM/soapnuke/clean/Lixiviados/results/01.Lixiviados.fasta, exiting
Stopping in STEP1 -> 01.run_all_assemblies.pl. Program finished abnormally

  If you don't know what went wrong or want further advice, please look for similar issues in https://github.com/jtamames/SqueezeMeta/issues
  Feel free to open a new issue if you don't find the answer there. Please add a brief description of the problem and upload the /media/metagenomica/HDD/F22FTSUSAT1160-01_ENVkxwbM/soapnuke/clean/Lixiviados/syslog file (zip it first)
Died at /home/metagenomica/anaconda3/envs/sqm/bin/SqueezeMeta.pl line 941.

can you help me please

**Comment by fpusan** [comment]
Please attach the `/media/metagenomica/HDD/F22FTSUSAT1160-01_ENVkxwbM/soapnuke/clean/Lixiviados/syslog` file here (zip It first)

**Comment by gallegobq** [comment]
Hello Fernando, thank you for your response, I was able to solve this problem, it was a matter of disk space. However, when I am at step 4 (04.rundiamond.pl) it stops abnormally, do I post a new thread?

greetings,

**Comment by fpusan** [comment]
Yes please, you can open a new issue for that. But checking the logs (stdout, stderr, syslog and `temp/diamond.nr.log`) will probably reveal that you ran out of RAM memory.
