### ISSUE TITLE
Can't download the classifier.jar 

### ISSUE THREAD

**Issue by GuoHao150** [jtamames/SqueezeMeta#82]
I installed SqueezeMeta with this commond `conda create -n SqueezeMeta -c bioconda -c fpusan squeezemeta` and it works fine but when I configure the database with `configure_nodb.pl /path/to/db` it tells me as follow
```
Downloading and unpacking RDP classifier...
--2020-04-02 01:56:39--  http://wwwuser.cnb.csic.es/~squeezem/classifier.tar.gz
Resolving wwwuser.cnb.csic.es (wwwuser.cnb.csic.es)... 161.111.70.130
Connecting to wwwuser.cnb.csic.es (wwwuser.cnb.csic.es)|161.111.70.130|:80... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2020-04-02 01:56:40 ERROR 500: Internal Server Error.

tar (child): /opt/miniconda3/SqueezeMeta/lib/classifier.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
rm: cannot remove '/opt/miniconda3/SqueezeMeta/lib/classifier.tar.gz': No such file or directory
ln: failed to create symbolic link './classifier.jar': File exists
```
Looks like I can't download the classifier.jar file with the url and how am I suppose to fix this

**Comment by fpusan** [comment]
Hi,

This is a known issue, some of our users can not connect to the server at our institution and we are yet not sure why.

The `configure_nodb.pl` will not download the databases, just configure a new version of SQM to use the databases present in the system. Do you already have the databases?

If you don't,  please follow the instructions in #74 to download everything from an alternative mirror.

If you do have the databases and only need to run `configure_nodb.pl`, please follow these steps:
1) Get the RDP classifier tarball from `https://saco.csic.es/index.php/s/RKQNjYYHWGn6Z3W`
2) Place it in `/opt/miniconda3/SqueezeMeta/lib/`
3) Run `configure_nodb.pl /path/to/db`. It will still complain about the ERROR 500, but then it should find the `classifier.tar.gz` that you put in the lib directory. To check that it worked, you can try to run `java -jar /opt/miniconda3/SqueezeMeta/lib/classifier.jar`. It should return the help screen from the RDP classifier.

Let me know if this works for you,

Fernando

**Comment by GuoHao150** [comment]
Hi there,

Thanks for your help and with your advice it works now. For someone who might encounter the same problem you may need to remove the part of code `wget -U '' -P $libpath http://wwwuser.cnb.csic.es/~squeezem/classifier.tar.gz;` in the configure_nodb.pl.

really appreciate your work
