### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by jmpe77** [jtamames/SqueezeMeta#822]
I am trying to install SqueezeMeta in Ubuntu 22.04.4. Installation using mamba did not work so I tried downloading the latest release from the repository. After following all the instructions for the installation, I run the test_install.pl and it showed the following errors

WARNING: Some SqueezeMeta dependencies could not be found in your environment or failed to execute!
	- ERROR: Error running cd /tmp/tmp.pYvG3LSJSL; spades.py --test
	- ERROR: Error running metabat2 -h
	- ERROR: Error running jgi_summarize_bam_contig_depths -h
	- ERROR: Error running samtools --version
	- ERROR: Error running kmer-db -h
	- ERROR: Error running mothur -h

**Comment by jmpe77** [comment]
Checking binaries
	spades.py NOT OK
		ERROR: Error running cd /tmp/tmp.MeXsEdvJY1; spades.py --test
	metabat2 NOT OK
		ERROR: Error running metabat2 -h
	jgi_summarize_bam_contig_depths NOT OK
		ERROR: Error running jgi_summarize_bam_contig_depths -h
	samtools NOT OK
		ERROR: Error running samtools --version
	bwa OK
	minimap2 OK
	diamond OK
	hmmsearch OK
	cd-hit-est OK
	kmer-db NOT OK
		ERROR: Error running kmer-db -h
	aragorn OK
	mothur NOT OK
		ERROR: Error running mothur -h

**Comment by fpusan** [comment]
If possible, create a conda environment with spades, metabat2, samtools, kmer-db and mothur, and try to run `test_install.pl` from there.

We used to redistribute those binaries (we still do, technically) but they were creating compatibility issues with newer versions of Ubuntu and other distros so we switched to conda in order to have a "one size fits all" solution.

If conda is not possible for you, you will need to install those manually (possible compiling from source) and make then available in your path.

**Comment by jmpe77** [comment]
I see, then maybe it is better to figure out what happened with my installation with conda.

This is what I got when trying to install it with conda

Looking for: ['squeezemeta']

anaconda/linux-64                                             No change
bioconda/linux-64                                             No change
conda-forge/linux-64                                          No change
bioconda/noarch                                               No change
conda-forge/noarch                                            No change
pkgs/r/linux-64                                               No change
pkgs/main/noarch                                              No change
anaconda/noarch                                               No change
pkgs/main/linux-64                                            No change
fpusan/linux-64                                               No change
fpusan/noarch                                                 No change
pkgs/r/noarch                                                 No change
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
Could not solve for environment specs
The following packages are incompatible
└─ squeezemeta is not installable because there are no viable options
   ├─ squeezemeta [1.1.0|1.1.1|...|1.6.2post1] would require
   │  └─ ruby 2.5.*  but there are no viable options
   │     ├─ ruby [2.5.1|2.5.5|2.5.7] conflicts with any installable versions previously reported;
   │     └─ ruby 2.5.1 would require
   │        └─ openssl >=1.1.1,<1.1.2.0a0 , which does not exist (perhaps a missing channel);
   └─ squeezemeta [1.6.2post2|1.6.2post3|1.6.3] would require
      └─ biopython 1.81 , which conflicts with any installable versions previously reported.

**Comment by fpusan** [comment]
What's your OS/distros/version?
What exact command are you using?
Do you have a `~/.condarc` file in place?

**Comment by jmpe77** [comment]
I have Ubuntu 2.04

I am using this command
mamba create -n SqueezeMeta -c bioconda -c conda-forge -c anaconda -c fpusan squeezemeta -no-channel-priority

i don't think I have a .condarc file

**Comment by jmpe77** [comment]
Thank you very much. Now the test_install sows everything OK.

**Comment by fpusan** [comment]
Glad to hear. Closing issue
