### ISSUE TITLE
link to kegg database

### ISSUE THREAD

**Issue by bresyd** [jtamames/SqueezeMeta#824]
Hi,

I am currently preparing the final submission of a paper for which I have used the SQM pipeline. I was contacted by the journal that I need to provide links to all databases that were used during the anlysis in a reporting summary document. For nr, eggnog and pfam I found links to download the respective databases. However, I can not find the kegg database v58 anywhere to download. So I wanted to ask if you guys maybe had a link available that points to this database, and that I can include in the reporting summary?

Thanks a lot for your help

**Comment by fpusan** [comment]
We host it ourselves.
http://andes.cnb.csic.es/SqueezeMeta/kegg.db.gz
http://silvani.cnb.csic.es/SqueezeMeta/kegg.db.gz
Pretty sure it is ok to include it in your submission. Not fully sure it is version 58 though, @jtamames can you confirm this?

**Comment by jtamames** [comment]
See #367

**Comment by bresyd** [comment]
Hi Fernando and Javier,

thanks a lot for both of your replies and for allowing to use one of the above links, that should certainly meet the requirements I was asked for.

As always, your support for SQM is outstanding.

Cheers
