### ISSUE TITLE
unable to down load databases

### ISSUE THREAD

**Issue by zuriashm** [jtamames/SqueezeMeta#830]
I am encountered problem while I am trying to download the data bases. the error that i have observed was the following. Thus I kindly request you solve the aforementioned issues. Thank you for your help. 
(SqueezeMeta) root@metagenomic:~# download_databases.pl  ./pl
No host could be reached! at /root/anaconda3/envs/SqueezeMeta/SqueezeMeta/lib/install_utils/get_host.pl line 11.

**Comment by jtamames** [comment]
Hello
Is it possible you are behind a firewall or similar? The server is up and running, this seems to be related to your internet connection or configuration

**Comment by zuriashm** [comment]
Thank you very much for your immediate response. I will try to fix it.
