### ISSUE TITLE
Issue with download of database

### ISSUE THREAD

**Issue by abhirajnair2002** [jtamames/SqueezeMeta#832]
![image_2024-04-25_165729163](https://github.com/jtamames/SqueezeMeta/assets/168075366/ce954ee8-7f6d-47d7-89db-a3093ba27f56)
this error pops up each time i give the command to set up the database

**Comment by fpusan** [comment]
Both our servers at `andes.cnb.csic.es` and `silvani.cnb.csic.es` are reachable to me right now (and I am connecting from a different country). Maybe this is a firewall issue?
