### ISSUE TITLE
Program ending abruptly

### ISSUE THREAD

**Issue by abhirajnair2002** [jtamames/SqueezeMeta#834]
![image_2024-04-27_091456111](https://github.com/jtamames/SqueezeMeta/assets/168075366/6a6ac0a4-93b5-4c36-b383-9e119313c2ab)

How should i proceed after this error.

**Comment by fpusan** [comment]
You had only 3.17 GB of RAM available. This is simply too low RAM to run the pipeline. You can try setting the `-b` parameter to a very low value (eg 0.2) when launching SqueezeMeta, but It may still not be enough to make it work.
