### ISSUE TITLE
server not reachable

### ISSUE THREAD

**Issue by abhirajnair2002** [jtamames/SqueezeMeta#835]
![image](https://github.com/jtamames/SqueezeMeta/assets/168075366/e217abfc-fa8e-47d7-a73e-bc032bfecf1c)
how do i proceed

**Comment by abhirajnair2002** [comment]
150.244.85.58 is not pinging

**Comment by fpusan** [comment]
I can not help you with that, you should discuss with your network administrator.

**Comment by jtamames** [comment]
Btw, why are you opening a new issue when you have one opened already with the very same question?
