### ISSUE TITLE
Illegal division by zero in step 18.getbins.pl

### ISSUE THREAD

**Issue by mradz19** [jtamames/SqueezeMeta#836]
My project is stopping at step 18 with the error:
```
[0 seconds]: STEP18 -> CREATING BIN TABLE: 18.getbins.pl
  Method:DAS
  Reading checkM results in /data/full_project_2/intermediate/17.full_project_2.checkM
  Looking for bins in /data/full_project_2/results/bins
  Reading data for bin concoct.386.fa_sub.contigs           
  Calculating coverages
Illegal division by zero at /data/anaconda3/envs/SqueezeMeta/SqueezeMeta/scripts/18.getbins.pl line 168.
Stopping in STEP18 -> 18.getbins.pl
Died at /kusers/ancillary/anaconda3/envs/SqueezeMeta/bin/SqueezeMeta.pl line 831.
```
I saw that #815 had the same issue but I r
[syslog.txt](https://github.com/jtamames/SqueezeMeta/files/15172838/syslog.txt)
eally don't want to start the binning again is this is a very large project. I have confirmed that none of the bins in results/bins are 0 bytes in size, they are all at least 1MB.

I have also attached the syslog file

**Comment by fpusan** [comment]
Can you go to the `results/bins` directory and run the following code?
```
python3 -c """
from glob import glob
fs = glob('*tax')
for f in fs:
    for line in open(f):
         if line.startswith('Consensus'):
             print(f, line.split('\t')[1])
             break
    else:
        print(f, 'NO RESULT')
"""
```
You should get the size for each bin. Let me know if some bin shows `NO RESULT` instead of the size.

**Comment by mradz19** [comment]
Thanks for your help! The very last bin says no result:
```
concoct.386.fa_sub.contigs.fa.tax NO RESULT
```

**Comment by fpusan** [comment]
Can you share that file with us?

**Comment by mradz19** [comment]
Sure here is a link to the file:

https://we.tl/t-8KInNTDveF

**Comment by fpusan** [comment]
Any change that step 16 (`16.addtax2.pl`) died midway?
Can you check whether all the fasta files for the bins in `/data/full_project_2/results/bins` have an equivalence `*.fa.tax` file?

**Comment by mradz19** [comment]
Most don't have an associated tax file, about 25% of them do. Will I have to repeat from step 16?

**Comment by fpusan** [comment]
Try running step 16 alone (`16.addtax2.pl /path/to/project`) then we double check whether everything looks correct and, if so, restart from step 17.

**Comment by mradz19** [comment]
Ok I will run that and update when it is finished

**Comment by mradz19** [comment]
Ok it ran for a little while and stopped part way through:

```Calculating consensus taxonomy using mode s
  Adding SqueezeMeta taxonomy for concoct.381.fa.contigs.fa
  Calculating consensus taxonomy using mode s
  Adding SqueezeMeta taxonomy for concoct.382.fa_sub.contigs.fa
  Calculating consensus taxonomy using mode s
  Adding SqueezeMeta taxonomy for concoct.383.fa_sub.contigs.fa
  Calculating consensus taxonomy using mode s
  Adding SqueezeMeta taxonomy for concoct.386.fa_sub.contigs.fa
Killed
```

It seems to be stopping at the same bin:

```
concoct.386.fa_sub.contigs.fa.tax NO RESULT
```

**Comment by fpusan** [comment]
How many contigs are there in that Bin?

**Comment by mradz19** [comment]
It seems the tax file for this bin is predominantly chordata, could I try just deleting this bin then re-running step 16 or would that cause issues?

**Comment by fpusan** [comment]
Not 100% sure but will probably work.
The error happens because the Bin is too large for our disparity calculation algorithm.
We actually added a check for this a while ago, but the fix hasn't made an official release yet.
https://raw.githubusercontent.com/jtamames/SqueezeMeta/binonly/scripts/16.addtax2.pl
This would be the link to the updated code, in case you want to replace your script by the fixed one.

**Comment by mradz19** [comment]
Just an update. I used the new code you attached and step 16 completed successfully, it just skipped the larger bin. I then restarted from step 18 and the run finished without issue. Thanks for your help.

**Comment by fpusan** [comment]
Glad to hear, closing issue!

**Comment by bgruening** [comment]
@fpusan can we please have a new release with this fix?

**Comment by fpusan** [comment]
@bgruening there you go!

**Comment by bgruening** [comment]
Thanks a lot!
