### ISSUE TITLE
nrdmnd database issue

### ISSUE THREAD

**Issue by abhirajnair2002** [jtamames/SqueezeMeta#841]
![image](https://github.com/jtamames/SqueezeMeta/assets/168075366/cb3b80b1-f4a4-49b2-89cb-0444f1e236df)

On running test_install.pl, all checks come out successful including nrdmnd but while trying to configure the database it says nrdmnd doesnt exist? How to fix this

**Comment by fpusan** [comment]
Because you are searching for the database in `/.` (system root) instead of `./` (current directory).
