### ISSUE TITLE
Stopping in STEP1 -> 01.run_all_assemblies.pl. Program finished abnormally

### ISSUE THREAD

**Issue by Shivabrahmam** [jtamames/SqueezeMeta#846]
Died at /home/miniconda3/envs/SqueezeMeta/bin/SqueezeMeta.pl line 941.

I was performing the coassembly then it gave this error, earlier to this i have even performed the sequential analysis it did not show any error.

**Comment by fpusan** [comment]
If things worked well using the sequential mode then it looks like you don't have enough RAM for the coassembly.

**Comment by Shivabrahmam** [comment]
I have around 100 GB of free RAM

**Comment by fpusan** [comment]
This may look like a lot but it is often far from enough depending on the number of samples, their depth and the complexity of your metagenomes.
Can you share the syslog file inside the project directory with us?

**Comment by Shivabrahmam** [comment]
[syslog.txt](https://github.com/jtamames/SqueezeMeta/files/15433754/syslog.txt)

**Comment by fpusan** [comment]
From the file I can see that MEGAHIT is failing with `Exit code -9` which happens indeed due to a lack of memory (maybe you are working in a cluster and didn't ask for the right amount?)
https://github.com/voutcn/megahit/issues/272#issuecomment-643017856

**Comment by Shivabrahmam** [comment]
Thank you for the help, I will try to run with the few samples and check for the results

**Comment by Shivabrahmam** [comment]
It worked with decreasing the number of samples as input, but I have one more doubt, in results I could only see the assembly against bacteria, I want to know that will it not identify any other like protozoa, fungi, viruses, etc. Because I am working on plant meta genomics it is required to identify them as well.

**Comment by fpusan** [comment]
It should identify viruses and eukaryotes too, if present, although the taxonomic resolution will be poorer, and eukaryotes may also fail to assemble and/or annotate. What's your percentage of mapped reads?

**Comment by Shivabrahmam** [comment]
For all the samples it is below 50%, highest I have seen is 35% and rest all the samples are in between 20 to 30%

**Comment by jtamames** [comment]
That is rather low. You could consider using sqm_reads.pl instead, to work with reads

**Comment by Shivabrahmam** [comment]
Thank you, I will try it for once.
