### ISSUE TITLE
loadSQM error

### ISSUE THREAD

**Issue by DRM-CPQBA** [jtamames/SqueezeMeta#85]
Hi Javier!!

I am trying to load the SQM project but I get the following error não foi possível abrir o arquivo 

```
Nat = loadSQM('/data/Kelly/Sequenciamento_Kelly/Metagenomica/squeezeMeta/Bactraps/')
Loading orfs
    table...
    abundances...
    sequences
Error in file(file, "rt") : não é possível abrir a conexão
Além disso: Warning message:
In file(file, "rt") :
  não foi possível abrir o arquivo '/data/Kelly/Sequenciamento_Kelly/Metagenomica/squeezeMeta/Bactraps//results/tables/Bactraps.orf.sequences.tsv': Arquivo ou diretório inexistente
```

Could you help me please?

Also I would like to install SQMtools in RStudio on my local pc, but i don´t know how, heelp please!

Best regards

Kelly Hidalgo

**Comment by DRM-CPQBA** [comment]
I forgot to say that im MacOS Catalina user

**Comment by fpusan** [comment]
Hi!

This seems like a versioning problem. What version are you using?
I recommend that you install version 1.1 (including the SQMtools package provided with it), remove the `/data/Kelly/Sequenciamento_Kelly/Metagenomica/squeezeMeta/Bactraps/results/tables/` directory, and try loading the project again.

Let me know if this works for you,

Fernando

**Comment by DRM-CPQBA** [comment]
Im installing by conda, on the last friday.
I had a mistake in the name of the project. Bactraps was a project processing 6 months ago, but yesterday I processed again with the name test. I am trying to load in the SQMtools but has the same error.

`> Hadza = loadSQM('~/Sequenciamento_Kelly/Metagenomica/squeezeMeta/test')
Loading orfs
    table...
    abundances...
    sequences
Error in file(file, "rt") : não é possível abrir a conexão
Além disso: Warning message:
In file(file, "rt") :
  não foi possível abrir o arquivo '/data/Kelly/Sequenciamento_Kelly/Metagenomica/squeezeMeta/test/results/tables/test.orf.sequences.tsv': Arquivo ou diretório inexistente`


Im looking for the `~/results/tables/`, but doesn't exists. 
`kelly@metagenoma:~/Sequenciamento_Kelly/Metagenomica/squeezeMeta/test/results$ ls
01.test.fasta			    10.test.mappingstat
02.test.16S.txt			    11.test.mcount
02.test.rnas			    12.test.cog.funcover
02.test.trnas			    12.test.kegg.funcover
02.test.trnas.fasta		    13.test.orftable
03.test.faa			    19.test.bintable
03.test.fna			    20.test.contigtable
03.test.gff			    21.test.kegg.pathways
06.test.fun3.tax.noidfilter.wranks  21.test.metacyc.pathways
06.test.fun3.tax.wranks		    22.test.stats
07.test.fun3.cog		    DAS
07.test.fun3.kegg		    maxbin
07.test.fun3.pfam		    metabat2`


`kelly@metagenoma:~/Sequenciamento_Kelly/Metagenomica/squeezeMeta/test$ ls
SqueezeMeta_conf.pl  ext_tables    methods.txt	  progress  syslog
data		     intermediate  parameters.pl  results   temp`

Do you know what happen?


Thanks


Kelly

**Comment by fpusan** [comment]
Are you sure that you have version 1.1.0, and that the conda environment is activated?

Can you run (within R) `packageVersion("SQMtools")` and let me know what version do you get?

**Comment by DRM-CPQBA** [comment]
Javier,

Thanks, i think that the error was that SqueezeMeta environment isnt activated. Although the version of SQMtools is 0.4.0, its ok?

Thanks

Kelly

**Comment by fpusan** [comment]
Yes, it's 0.4.0 for the R package.

**Comment by RaulLanda** [comment]
> Javier,
> 
> Thanks, i think that the error was that SqueezeMeta environment isnt activated. Although the version of SQMtools is 0.4.0, its ok?
> 
> Thanks
> 
> Kelly

How did you solve your problem? I have the same issue.

**Comment by fpusan** [comment]
Hi! This issue is quite old and we've updated many things since then.
It might be better if you open a new one, and give us some details on what were you doing, what happened exactly, the SqueezeMeta / SQMtools versions you're using, whether you are using conda or not, etc :)

**Comment by RaulLanda** [comment]
My project is quite old too.  I was trying to load it to R with SQMtools 0.3.4 (I'm working in a cluster). I've already run a newer project but im having problems running some SQM steps due to not enough cores available at the moment.  That's why I wanted to "recycle" the old run.

**Comment by fpusan** [comment]
Ok, let's give it a try. Which SqueezeMeta version did you use to create the project?
What's the actual error message you are getting?

**Comment by RaulLanda** [comment]
I used the v1.0.0
The error is this :

Error in file(file, "rt") : no se puede abrir la conexión
Calls: loadSQM -> read.namedvector -> read.table -> file
Además: Warning message:
In file(file, "rt") :
  no fue posible abrir el archivo '/scratch/cesarla/coatzacoalcos_WGS/SQM/coatza_ext//results/tables/coatza_ext.orf.sequences.tsv': No existe el fichero o el directorio
Ejecución interrumpida

I don't have a "/result/tables" directory

**Comment by fpusan** [comment]
I see. Did you run `sqm2tables.py`?

`sqm2tables.py /scratch/cesarla/coatzacoalcos_WGS/SQM/coatza_ext/ /scratch/cesarla/coatzacoalcos_WGS/SQM/coatza_ext/results/tables`

**Comment by RaulLanda** [comment]
yes, i did, but also got an error

Traceback (most recent call last):
  File "/share/apps/SqueezeMeta//utils/sqm2tables.py", line 164, in <module>
    main(parse_args())
  File "/share/apps/SqueezeMeta//utils/sqm2tables.py", line 59, in main
    sampleNames, orfs, kegg, cog, pfam = parse_orf_table(perlVars['$mergedfile'], nokegg, nocog, nopfam, args.trusted_functions, args.ignore_unclassified)
  File "/share/apps/SqueezeMeta/utils/../lib/utils.py", line 101, in parse_orf_table
    with open(orf_table) as infile:
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/landa/coatzacoalcos_WGS/SQM/coatza_ext/results/13.coatza_ext.orftable'

**Comment by fpusan** [comment]
what is the content of the `/scratch/landa/coatzacoalcos_WGS/SQM/coatza_ext/results/` directory?

**Comment by RaulLanda** [comment]
01.coatza_ext.fasta
02.coatza_ext.16S.txt
02.coatza_ext.rnas
02.coatza_ext.trnas
02.coatza_ext.trnas.fasta
03.coatza_ext.faa
03.coatza_ext.fna
07.coatza_ext.fun3.pfam
08.coatza_ext.fun3.cog
08.coatza_ext.fun3.kegg
08.coatza_ext.fun3.tax.noidfilter.wranks
08.coatza_ext.fun3.tax.wranks
08.coatza_ext.gff
10.coatza_ext.mappingstat
11.coatza_ext.mcount
12.coatza_ext.cog.funcover
12.coatza_ext.kegg.funcover
13.coatza_ext.orftable
19.coatza_ext.bintable
20.coatza_ext.contigtable
21.coatza_ext.kegg.pathways
21.coatza_ext.metacyc.pathways
22.coatza_ext.stats
DAS
maxbin
metabat2

**Comment by fpusan** [comment]
So running `head /scratch/landa/coatzacoalcos_WGS/SQM/coatza_ext/results/13.coatza_ext.orftable` works for you? Is the file present in that exact path?

**Comment by RaulLanda** [comment]
yes, i have it here  

#--Created by /share/apps/SqueezeMeta/scripts/13.mergeannot2.pl, Thu Apr  9 14:55:51 2020
ORF ID	Contig ID	Molecule	Method	Length NT	Length AA	GC perc	Gene name	Tax	KEGG ID	KEGGFUN	KEGGPATH	COG ID	COGFUN	COGPATH	PFAM	TPM Dia0	TPM Dia1	TPM Dia2	Coverage Dia0	Coverage Dia1	Coverage Dia2	Raw read count Dia0	Raw read count Dia1	Raw read count Dia2	RAW base count Dia0	RAW base count Dia1	RAW base count Dia2	Hits
megahit_1_1-567	megahit_1	CDS	Prodigal	568	190	66.31		k_Bacteria;p_Proteobacteria							PF09985 [C-terminal binding-module, SLH-like, of glucodextranase]	0.443	0.051	0	4.388	0.702	0	19	3	0	2488	398	0	25
megahit_2_3-530	megahit_2	CDS	Prodigal	529	177	45.08		k_Bacteria;p_Proteobacteria;n_delta/epsilon subdivisions;c_Deltaproteobacteria		0.100	0.109	0	0.633	1.517	0	4	6	0	334	8010	9
megahit_3_3-317	megahit_3	CDS	Prodigal	316	106	66.35		00	0.484	0	0	5.105	0	0	17	0	0	1608	0

**Comment by fpusan** [comment]
Then it is hard to tell what's happening. The error you showed above

`
 FileNotFoundError: [Errno 2] No such file or directory: '/scratch/landa/coatzacoalcos_WGS/SQM/coatza_ext/results/13.coatza_ext.orftable'
`
should happen only if the file is missing. Are you running that script in interactive mode or are you sending the job to the queue? Maybe it is a problem of file permissions?

**Comment by RaulLanda** [comment]
I send it to the job queue
I have reading permission. I will change it and see what happens.

**Comment by RaulLanda** [comment]
Still the same error :(
