### ISSUE TITLE
SqueezeMeta_conf.pl

### ISSUE THREAD

**Issue by AntonioPuriel** [jtamames/SqueezeMeta#857]
Hello, I started to work with my data in a cluster; but when I submit the script it dies immediatly. 
Thanks in advance for your help :)

SqueezeMeta v1.6.3, September 2023 - (c) J. Tamames, F. Puente-SÃ¡nchez CNB-CSIC, Madrid, SPAIN

Please cite: Tamames & Puente-Sanchez, Frontiers in Microbiology 9, 3349 (2019). doi: https://doi.org/10.3389/fmicb.2018.03349

[0mRun started Fri Jun 28 14:16:21 2024 in coassembly mode
4 metagenomes found: HC_T0 Oxico Oscil Anoxi

[31mCan't open conf file /zfs/softs/contrib/apps/anaconda/3/envs/squeezemeta-1.6.3/SqueezeMeta/scripts/SqueezeMeta_conf.pl
[0mDied at /softs/contrib/apps/anaconda/3/envs/squeezemeta-1.6.3/bin/SqueezeMeta.pl line 961.

[SqueezeMeta.log](https://github.com/user-attachments/files/16029884/SqueezeMeta.log)

**Comment by mingxues2024** [comment]
> Seems that you didn't download the databases (or you did, but you didn't run `configure_nodb.pl` after updating SqueezeMeta)

Hi, i met the same error, and also I run the configure_nodb.pl. Is there any else things I need to do ?
