### ISSUE TITLE
Error running minion option

### ISSUE THREAD

**Issue by stanikae** [jtamames/SqueezeMeta#86]
Hi,

I keep getting the following error when i run SqueezeMeta on a minion metagenomic sample.

`Running jobs.  First attempt out of 2.
Starting 'obtovl' concurrent execution on Wed Mar 18 14:25:55 2020 with 21216.638 GB free disk space (6 processes; 4 concurrently)
`
`    cd trimming/1-overlapper `
`
    ./overlap.sh 1 > ./overlap.000001.out 2>&1
    ./overlap.sh 2 > ./overlap.000002.out 2>&1
    ./overlap.sh 3 > ./overlap.000003.out 2>&1
    ./overlap.sh 4 > ./overlap.000004.out 2>&1
    ./overlap.sh 5 > ./overlap.000005.out 2>&1
`
`
Killed
`

The command i ran is:
`SqueezeMeta.pl -m coassembly --minion -p minion_sqm -s minion_sampleFile.txt -f minion_test`

Thanks,
Stan

**Comment by fpusan** [comment]
The canu assembler is being killed, but it's hard to tell why. Can you send me the `minion_sqm/syslog` file?

**Comment by jtamames** [comment]
Hello Stan
Could you also try to run canu independently of SqueezeMeta? 
Best,

**Comment by stanikae** [comment]
Hi @fpusan you can find the syslog file at this link: https://drive.google.com/file/d/1n7HH9QkKDYfOVoGTYjbbgnoFa_ESQ9ld/view?usp=sharing

@jtamames i will try running canu independently in the meantime - I will update u.

Thanks,
Stan

**Comment by jtamames** [comment]
Stan, we are also having problems when running canu using big datasets.  It is known that is substantially slower than other assemblers (see for instance  [(https://f1000research.com/articles/8-2138/v1](url)). It apparently struggles when dealing with these big files. We will include some other long read assemblers (possibly flye and raven) soon. In the meantime, you can assemble your data set using any of these softwares and provide it to SqueezeMeta using the --extassembly option.

**Comment by fpusan** [comment]
It doesn't seem like a problem with canu, more like the process was killed by OS / queue manager.

Are you running this in a cluster? Could it be that the job was killed because it exceeded memory/time allocation?

**Comment by stanikae** [comment]
@fpusan no i am running SqueezeMeta on a single node server

**Comment by fpusan** [comment]
How much available RAM memory does the server have?

**Comment by stanikae** [comment]
About 503G
`
free -ht
              total        used        free      shared  buff/cache   available
Mem:           503G         31G         12G        375M        459G        471G
Swap:          511G        348M        511G
Total:         1.0T         31G        524G
`

**Comment by fpusan** [comment]
Ok, it looks like there's plenty. Let us know how the individual run of canu works out.

**Comment by stanikae** [comment]
Hi again,

I re-ran SqueezeMeta successfully using lowmem option for canu
```` 
SqueezeMeta.pl -m coassembly --lowmem --minion -p minion_sqm -s minion_sampleFile.txt -f minion_test 
````
But just keen to pick your brain on something, we did both Illumina and MinIon metagenomic sequencing for this sample, when i ran SqueezeMeta on the short reads data, we got many taxonomic classifications (3282) but with the MinIon data, only 9. Any idea why the big disparity between the two outputs?

````
wc -l 11.illumina.mcount
3282 11.illumina.mcount

wc -l 11.minion.mcount
9 11.minion.mcount
````
Thanks,
Stan

**Comment by jtamames** [comment]
Hello
Wow, that is a big difference. Maybe the canu assembly was not very good? Did you check the 10.project.mappingstat file and the 22.project.stats for both runs? That could clarify whatis going on there
Best,

**Comment by stanikae** [comment]
It looks like less data was generated using the minion. But the canu assembly looks gr8, based on the mapped reads
````
# Illumina
Sample        Total reads     Mapped reads    Mapping perc    Total bases
sample3 6768726 5277056 77.96   1515808290

# MinIon
Sample        Total reads     Mapped reads    Mapping perc    Total bases
sample3 113902  108865  95.58   510236405
````


````
# **illumina**
#------------------- Statistics on contigs
#       Assembly
Number of contigs       432855
Total length    249140148
Longest contig  42595
Shortest contig 200
N50     578
N90     349
Contigs at superkingdom (k) rank        396784 (91.7%), in 4 superkingdoms
Contigs at phylum (p) rank      384741 (88.9%), in 70 phyla
Contigs at class (c) rank       345901 (79.9%), in 79 classes
Contigs at order (o) rank       311757 (72.0%), in 142 orders
Contigs at family (f) rank      280698 (64.8%), in 264 families
Contigs at genus (g) rank       200653 (46.4%), in 843 genera
Contigs at species (s) rank     61532 (14.2%), in 1310 species
Congruent       432548 (99.9%)
Disparity >0    308 (0.1%)
Disparity >= 0.25       298 (0.1%)

Most abundant taxa      sample3
superkingdom    Bacteria
phylum  Proteobacteria
class   Betaproteobacteria
order   Burkholderiales
family  Comamonadaceae
genus   Acinetobacter
species Escherichia coli

# **minion**
#------------------- Statistics on reads
#       Assembly        sample3
Number of reads 113902  113902
Number of bases 510236405       510236405

#------------------- Statistics on contigs
#       Assembly
Number of contigs       12
Total length    6066626
Longest contig  4983314
Shortest contig 6064
N50     4983314
N90     111328
Contigs at superkingdom (k) rank        11 (91.7%), in 1 superkingdoms
Contigs at phylum (p) rank      11 (91.7%), in 1 phyla
Contigs at class (c) rank       11 (91.7%), in 1 classes
Contigs at order (o) rank       10 (83.3%), in 1 orders
Contigs at family (f) rank      10 (83.3%), in 1 families
Contigs at genus (g) rank       8 (66.7%), in 1 genera
Contigs at species (s) rank     5 (41.7%), in 1 species
Congruent       6 (50.0%)
Disparity >0    7 (58.3%)
Disparity >= 0.25        (0.0%)

Most abundant taxa      sample3
superkingdom    Bacteria
phylum  Proteobacteria
class   Gammaproteobacteria
order   Enterobacterales
family  Enterobacteriaceae
genus   Escherichia
species Escherichia coli
````
Don't know if there is anything you can advice based on these stats.

Thanks,
Stan

**Comment by fpusan** [comment]
You have so little taxonomic assignments with MinION because you actually got only 11 contigs.

The contigs themselves are very long, it seems like the represent mostly one genome. The mapping percentage is also great, so the assembly is a very good representation of the MinION reads you generated.

On the other hand, total assembly size is much larger in Illumina (249Mb vs 6 Mb) and the mapping percentage much lower.

Are you sure the two datasets come from the same sample? It honestly looks that the MinION one is from a pure culture, and the Illumina one from a complex metagenome.

Anyways, as I said, the MinION assembly is a good representation of the MinION reads, so any potential issue would be happening before running SqueezeMeta.

**Comment by stanikae** [comment]
Thanks @jtamames  and @fpusan for the awesome tool and all the help.
