### ISSUE TITLE
Error Encountered in SqueezeMeta with PacBio data 

### ISSUE THREAD

**Issue by Meeenakshipari** [jtamames/SqueezeMeta#860]
I am using SqueezeMeta to analyze PacBio data. The first step in SqueezeMeta is to run Canu because it is suited for PacBio data. However, I encountered an error during this step. Here are the details: I am using SqueezeMeta with PacBio data from SRR IDs SRR5219184 and SRR5219191 (human gut metagenome). Canu was chosen for assembly due to its compatibility with PacBio data, but the assembly process failed during the Canu step, displaying an error message related to low coverage. I have referred to Canu issue #1795, which suggested setting corOutCoverage=10000, corMhapSensitivity=high, and corMinCoverage=0. Despite these changes, the low coverage issue persists. Could you provide additional suggestions or parameter adjustments to resolve this low coverage issue and ensure successful assembly of the metagenomes?

Any help would be greatly appreciated.

I have attached the syslog file and error also,
<img width="801" alt="canu_error" src="https://github.com/jtamames/SqueezeMeta/assets/60251541/d340b82e-2451-4faa-bdb8-4b813bff7178">

[syslog.zip](https://github.com/user-attachments/files/16093533/syslog.zip)

**Comment by fpusan** [comment]
This seems like a canu issue and we might not be the best people to ask. By reading the message, adding `stopOnLowCoverage=8` should probably make it work. Alternatively, `flye`, which is also distributed together with SqueezeMeta, should be able to take PacBio reads too.

**Comment by Meeenakshipari** [comment]
Thank you for your reply . I tried using Flye for the assembly, but unfortunately, it also stopped due to low coverage. Consequently, I have decided to select a different dataset for my analysis and it worked well for Flye for pacbio reads
