### ISSUE TITLE
bining after running SqueezeMeta with --nobins option

### ISSUE THREAD

**Issue by fconstancias** [jtamames/SqueezeMeta#87]
Dear SqueezeMeta developers,

I have run SqueezeMeta with --nobins option and would like to now perform binning on the same project. I have tried `restart.pl` or calling the scripts `14.bin_maxbin.pl` but it didn't work. I think I have to change the on the project folder to be able to do it, right? Any other trick?

Thanks again for that amazing tool.
Stay safe.

Florentin

**Comment by jtamames** [comment]
Hello!
Just edit the SqueezeMeta_conf.pl file and change the  $nobins variable to zero. Then restart the project from step 14.
Best,
Javier

**Comment by jtamames** [comment]
Closing inactive issue

**Comment by fconstancias** [comment]
sorry for the late follow up. 
I encountered the follwoing error, related to the output directory for the binning results I guess.

> restart.pl DYVR2-SM -step 14                                                                                                                                                                           
> [0 seconds]: STEP14 -> MAXBIN BINNING: 14.bin_maxbin.pl
> mkdir: missing operand
> Try 'mkdir --help' for more information.
> Can't open /abund.list for writing
> ERROR in STEP14 -> 14.bin_maxbin.pl
> Can't open  directory
>

**Comment by jtamames** [comment]
Could you send us your `syslog` file?
Thanks!

**Comment by fconstancias** [comment]
[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/4786371/syslog.zip)

**Comment by jtamames** [comment]
Ok, you ran SqueezeMeta with the `--nobinning` option (plus `--nometabat` and `--nomaxbin`, just in case lol), so it didn´t create the binning directories and, more importantly, didn´t define the binning variables. Then when you restart in step 14, the variables are not set, the directories cannot be created, and it returns the error you see.
Try the following: edit the `SqueezeMeta_conf.pl` in the project directory, and add the following lines, wherever:

`%bindirs     = ("maxbin","$resultpath/maxbin","metabat2","$resultpath/metabat2"); ` 
`%dasdir      = ("DASTool","$resultpath/DAS/$projectname\_DASTool\_bins");`

Then you can restart again in step 14 and it should work.
I will correct the code as to put these variables in the conf file even if binning was not selected.

Finally, notice that `--nobinning` overrides all binning stuff, so it is not needed to specify the other flags
Best,
Javier

**Comment by fconstancias** [comment]
Hi @jtamames,

Sorry for the late follow up, but I got the following error:
(SqueezeMetaConda)$ restart.pl DYVR2-SM --step 14
[0 seconds]: STEP14 -> MAXBIN BINNING: 14.bin_maxbin.pl
mkdir: missing operand
Try 'mkdir --help' for more information.
Can't open /abund.list for writing
ERROR in STEP14 -> 14.bin_maxbin.pl
Can't open  directory

Please find enclosed the modified SqueezeMeta_conf.pl.


[SqueezeMeta_conf.pl.zip](https://github.com/jtamames/SqueezeMeta/files/4873915/SqueezeMeta_conf.pl.zip)

Thanks

**Comment by jtamames** [comment]
Hello
Ok, your SqueezeMeta_conf.pl is defining the directory for metabat:

`%bindirs = ("metabat2","$resultpath/metabat2");`

but you forgot to do it for maxbin. Just replace that line for:

`%bindirs = ("maxbin","$resultpath/maxbin","metabat2","$resultpath/metabat2");`

and it should work.

Best,
Javier
