### ISSUE TITLE
Can't open conf file 

### ISSUE THREAD

**Issue by mingxues2024** [jtamames/SqueezeMeta#870]
Dear sir,

SqueezeMeta.pl -m coassembly -p L39 -s /lustre/BIF/nobackup/sun091/metagenome/coassembly_per_accession/L39.txt -f /lustre/BIF/nobackup/sun091/metagenome/4_assembly/
***

SqueezeMeta v1.6.3, September 2023 - (c) J. Tamames, F. Puente-SÃ¡nchez CNB-CSIC, Madrid, SPAIN

Please cite: Tamames & Puente-Sanchez, Frontiers in Microbiology 9, 3349 (2019). doi: https://doi.org/10.3389/fmicb.2018.03349

Run started Wed Jul 24 15:08:26 2024 in coassembly mode
6 metagenomes found: A19 A20 A21 A22 A23 A24

Can't open conf file /lustre/BIF/nobackup/sun091/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/SqueezeMeta_conf.pl

I have checked the L39 file  and SqueezeMeta_conf.pl file content was empy. 
When I run other samples, There is no error.
Could you give me some suggestions?

Thanks for you attention

Best,
mingxue

**Comment by fpusan** [comment]
Have you downloaded the databases?

**Comment by mingxues2024** [comment]
yes, I did
________________________________
发件人: Fernando Puente-Sánchez ***@***.***>
发送时间: 2024年7月27日 12:10
收件人: jtamames/SqueezeMeta ***@***.***>
抄送: Sun, Mingxue ***@***.***>; Author ***@***.***>
主题: Re: [jtamames/SqueezeMeta] Can't open conf file (Issue #870)


Have you downloaded the databases?

―

**Comment by fpusan** [comment]
Closing this as I see that you have posted another issue in which the pipeline had run to completion, so I assume that you managed to configure it properly in the end. Feel free to reopen otherwise
