### ISSUE TITLE
Stopping in STEP10 -> 10.mapsamples.pl. Program finished abnormally

### ISSUE THREAD

**Issue by Ayush09-cmd** [jtamames/SqueezeMeta#871]
i am beginner and analyzing my data for first time. i am at step 10 of squeezemeta analysis and getting this error  "Error, fewer reads in file specified with -2 than in file specified with -1". can anyone specify what is the issue, is it with the raw reads of paired ends being not equals size and do i have to rerun the squeezemeta from scratch. kindly find my syslog attached
[syslog.zip](https://github.com/user-attachments/files/16398867/syslog.zip)

**Comment by Ayush09-cmd** [comment]
Reading samples from /media/ham/HAM_lab/Ayush/Files/MDS_Squeezmeta_Results/data/00.MDS_Squeezmeta_Results.samples
  Metagenomes found: 9
  Reading contig length from /media/ham/HAM_lab/Ayush/Files/MDS_Squeezmeta_Results/intermediate/01.MDS_Squeezmeta_Results.lon
  Reading orf info from /media/ham/HAM_lab/Ayush/Files/MDS_Squeezmeta_Results/results/03.MDS_Squeezmeta_Results.gff
  Mapping with Bowtie2 (Langmead and Salzberg 2012, Nat Methods 9(4), 357-9)
  Creating reference from contigs
  Working with sample 1: Mandi_1
  Getting raw reads
  Aligning to reference with bowtie
Error, fewer reads in file specified with -2 than in file specified with -1
terminate called after throwing an instance of 'int'
Aborted (core dumped)
(ERR): bowtie2-align exited with value 134
An error occurred during mapping with command       /home/ham/Desktop/Metagenome/NGS_Tools/SqueezeMeta/bin/bowtie2/bowtie2 -x /media/ham/HAM_lab/Ayush/Files/MDS_Squeezmeta_Results/data/MDS_Squeezmeta_Results.bowtie  -1 /media/ham/HAM_lab/Ayush/Files/MDS_Squeezmeta_Results/temp/MDS_Squeezmeta_Results.Mandi_1.current_1 -2 /media/ham/HAM_lab/Ayush/Files/MDS_Squeezmeta_Results/temp/MDS_Squeezmeta_Results.Mandi_1.current_2 --quiet -p 10 -S /media/ham/HAM_lab/Ayush/Files/MDS_Squeezmeta_Results/data/bam/MDS_Squeezmeta_Results.Mandi_1.sam --very-sensitive-local! at /home/ham/Desktop/Metagenome/NGS_Tools/SqueezeMeta/scripts/10.mapsamples.pl line 267, <infile2> line 0.000000.
Stopping in STEP10 -> 10.mapsamples.pl. Program finished abnormally

  If you don't know what went wrong or want further advice, please look for similar issues in https://github.com/jtamames/SqueezeMeta/issues
  Feel free to open a new issue if you don't find the answer there. Please add a brief description of the problem and upload the /media/ham/HAM_lab/Ayush/Files/MDS_Squeezmeta_Results/syslog file (zip it first)
Died at /home/ham/Desktop/Metagenome/NGS_Tools/SqueezeMeta/scripts/SqueezeMeta.pl line 941.
here is the description of error

**Comment by fpusan** [comment]
`Error, fewer reads in file specified with -2 than in file specified with -1`
Please check that you specified the right files in your samples file, and that they are properly paired (i.e. they have the same number of forward reads and reverse reads)

**Comment by Ayush09-cmd** [comment]
i have checked the files they are properly paired for example one of the files has forward reads 12502813 and reverse reads 12301365 is this a significant difference

**Comment by fpusan** [comment]
Yes, as they are not identical. This often happens if you run quality filtering independently on the fwd and rev files

**Comment by Ayush09-cmd** [comment]
okay thank you for the response. i guess i will have to refilter and rerun the pipeline

**Comment by fpusan** [comment]
Yes, that's probably the solution. Make sure that you filter fwd and rev at the same time. Closing this
