### ISSUE TITLE
For the results from sqm2table 

### ISSUE THREAD

**Issue by mingxues2024** [jtamames/SqueezeMeta#872]
Dear sir,
I have finished the metagenome analysis by using SqueezeMeta ( assembly per sample strategy) . I have some questions for downstream analysis:

In each sample result file, there is a file named such as 12. A11.Kegg.funcover and contained results about each KO term TPM, RAW READS….. 

And I want to summarize all results of all samples together. So run sqm2tables.py. Then, I  got the desperate results for each sample. There is also a file named such as“ A11.KO.tpm”  for A11 sample.

But I found that the TPM results of same KO term in same sample were different. So I want to know which one I should use for next downstream analysis and why they are differences?

Could you give me some suggestions?
thanks!

Best,
Mingxue

**Comment by fpusan** [comment]
Can you post the exact commands you used to run SqueezeMeta and `sqm2tables.py`, and an example of the differences?

**Comment by fpusan** [comment]
Hi again,

The difference is that the `12.*.funcover` files ignore unclassified reads for TPM calculation, while the tables created with `sqm2tables.py` will by default consider them. You can control this behaviour by adding the flag `--ignore-unclassified` when calling `sqm2tables.py`. This will produce results that are almost identical (save some rounding errors) to the ones in the `12.*.funcover` files.

Hope this helps,

Fernando
