### ISSUE TITLE
died at line 969

### ISSUE THREAD

**Issue by Biotrinf** [jtamames/SqueezeMeta#874]
Hi,

I have an error message like below. I have attached the syslog file. Could you give me any advice ?

"Died at /home/bioinftr/anaconda3/envs/SqueezeMeta/bin/SqueezeMeta.pl line 969."

[syslog.zip](https://github.com/user-attachments/files/16480674/syslog.zip)

**Comment by fpusan** [comment]
Looks like DIAMOND running out of memory. Can you check the `/home/bioinftr/mku/temp/diamond.nr.log` file?
How much memory is available in your system? It looks like you tried to use the `--lowmem` mode but it may not be enough.

**Comment by Biotrinf** [comment]
Yes, I run the program with the --lowmem mode but it does not work. The system has 32GM RAM and I rearrange the free space 24GB for wsl2. I change the mode and try again now.

Thanks a lot.
