### ISSUE TITLE
Died at line 941

### ISSUE THREAD

**Issue by Selucote82** [jtamames/SqueezeMeta#876]
Dear SqueezeMeta developers, 

It's my first time using this amazing tool and I got the followed error launching SqueezeMeta in sequential mode for ONT reads:

"Stopping in STEP1 -> 01.run_all_assemblies.pl. Program finished abnormally
[...]
Died at /home/jlgonzalez/.conda/envs/squeezemeta-1.6.3/bin/SqueezeMeta.pl line 941"

The specific parameters I used were (I also used --minion flag):

SqueezeMeta.pl -m sequential -s resultados/SqueezeMeta/Biodiversidad/muestras.samples -f RawReads/ -map minimap2-ont -a flye

The error seems to appear in the minimap2 step as far as I saw in minimap.stderr file:

"[M::mm_idx_gen::26.036*1.46] collected minimizers
[M::mm_idx_gen::28.177*2.25] sorted minimizers
/bin/bash: línea 1: 831367 Tubería rota           flye-minimap2 '/lustre/home/jlgonzalez/CA1/data/flye/00-assembly/draft_assembly.fasta' '/lustre/home/jlgonzalez/CA1/data/raw_fastq/par1.fastq.gz' -x map-ont -t 12 -a -p 0.5 -N 10 --sam-hit-only -L -K 5G -z 1000 -Q --secondary-seq -I 64G
     831368 Violación de segmento  | flye-samtools view -T '/lustre/home/jlgonzalez/CA1/data/flye/00-assembly/draft_assembly.fasta' -u -
     831369 Violación de segmento  | flye-samtools sort -T '/lustre/home/jlgonzalez/CA1/data/flye/10-consensus/sort_240806_204616' -O bam -@ 4 -l 1 -m 4G -o '/lustre/home/jlgonzalez/CA1/data/flye/10-consensus/minimap.bam'"

The thing is that I'm able to launch every command by CLI, but in stand alone mode fail, as you can see.

Is it possible to restart the pipeline after manually running the failed command?

(test_install.pl was Ok for every thing)

Thank you for your support!

**Comment by fpusan** [comment]
Seems to be related to the `flye-minimap2` or `flye-samtools` binaries.
Let's try using conda's version of flye instead.
1. Install flye with `mamba install -c bioconda flye`7scripts
2. Edit the `/home/jlgonzalez/.conda/envs/squeezemeta-1.6.3/SqueezeMeta/scripts/SqueezeMeta_conf.pl` file.
3. Change the line starting with `$flye_soft` so that it reads `flye_soft          = "flye";`
Launch SqueezeMeta again. The pipeline can restart from a failed step, but in your case the error was in the first step.

**Comment by Selucote82** [comment]
Thanks for your quick reply.

I'm using a compute cluster that already has a flye v2.9.4 environment installed, so I'll request flye installation in my profile.

I assume the same should happen with canu, since SqueezeMeta also fails with the --minion flag (even earlier than with flye).

**Comment by fpusan** [comment]
Just install flye using conda, you should be able to do it yourself since the environment is in your own home (`/home/jlgonzalez/.conda/envs`). Just activate your environment first.
And the problem with canu is probably related to something different, I don't think they use the same binaries.

**Comment by Selucote82** [comment]
Yes, that's true. Finally I also installed canu, as done with flye, and, as you mentioned before, It has nothing to do with it.

I will let you know if this issue (flye) was solved with your directions.

Thank you!

**Comment by Selucote82** [comment]
Just to update, the problem was solved. Thank you for your support!
