### ISSUE TITLE
cores and ram allocated to Squeezemeta

### ISSUE THREAD

**Issue by Alexa2279** [jtamames/SqueezeMeta#878]
Hello.
How can I increase the number of cores and ram allocated to Squeezemeta?
Thank you very much in advance.

**Comment by fpusan** [comment]
You can control the number of threads used by SqueezeMeta and the different programs it calls with the `-t` parameter.
There is no way to easily control the RAM used in some of the steps. Assembly will use more RAM the more complex the metagenomes are, and the more metagenomes you try to coassemble. DIAMOND also tends to use a lot of RAM, but this can be controlled with the `-b` parameter.

If you are working in a computing cluster, you will need to ensure that you get assigned enough threads and memory. The specifics depend on the cluster you're working on, but they usually have good guides on how to achieve this.

**Comment by Alexa2279** [comment]
Thank you very much!
