### ISSUE TITLE
SqueezeMeta manual unavailable

### ISSUE THREAD

**Issue by emgiles** [jtamames/SqueezeMeta#879]
Could someone share the SqueezeMeta manual pdf, it is unavailable from the link...

**Comment by fpusan** [comment]
It is still in the repo
https://github.com/jtamames/SqueezeMeta/blob/master/SqueezeMetaManual_1.6.3.pdf
What broken link are you referring to?

**Comment by emgiles** [comment]
Hi Fernando

See attached screenshot. The pdf is not accessible from the link when I
click it... Could you send me a pdf? I am sorry for the inconvenience.
Thank you!
Emily Giles

[image: Screenshot 2024-08-15 at 7.23.02 AM.png]

**Comment by fpusan** [comment]
No problem!
I can't see the screenshot in GitHub.
Can you access from this link instead?
https://raw.githubusercontent.com/jtamames/SqueezeMeta/master/SqueezeMetaManual_1.6.3.pdf
Otherwise I'll send It by email

**Comment by emgiles** [comment]
Yes, thank you! I now have the 1.6 manual.
When trying to access the link from github I get the error "Error rendering
embedded code Invalid PDF"

**Comment by fpusan** [comment]
Oh, it works for me. What web browser are you using?

**Comment by emgiles** [comment]
Safari. It does not work for me if I am connected to VPN or not connected,
so it should not be a network issue I don't think. Also, if I deselect
privacy controls for github via Safari, it is still not available. I am
just seeing that the 1.6 manual is also in the conda environment, so I (or
others) could have just gotten it there.

**Comment by fpusan** [comment]
Weird, it has always worked well for me on Firefox.
I will try to move the manual to readthedocs for the new version.
Good luck with your analyses!
