### ISSUE TITLE
error running sqm2anvio.pl line 99 when running anvi-load-sqm.py

### ISSUE THREAD

**Issue by yjiakang** [jtamames/SqueezeMeta#88]
Sorry to disturb you again. I met a problem when running anvi-load-sqm.py with the latest version of SqueezeMeta.
```
(anvio-6.2) [jkyin@sg15 squeezemeta]$ python3 /public/home/jkyin/miniconda2/envs/SqueezeMeta/SqueezeMeta/utils/anvio_utils/anvi-load-sqm.py -p PZH -o PZH/results/anvio --num-threads 12 --min-contig-length 2500 --run-scg-taxonomy --run-HMMS
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Loading results from SQM in anvi'o.
Anvi'o is an advanced analysis and visualization platform for 'omics data.
Citation: Eren AM, Ozcan E, Quince C, Vineis JH, Morrison HG, Sogin ML, Delmont TO. (2015) Anvi'o: an advanced analysis and visualization platform for 'omics data. PeerJ 3:e1319
This script calls to sqm2anvio.pl and then runs a set of pre-defined commands to create an anvio database.
If you want to explore ways to manually create the database, and other cool stuff that you can do with anvi'o
please consider checking the anvi'o project page for information, tutorials and more details (http://merenlab.org/software/anvio/).
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
PZH/results/sqm2anvio does not exist
Create sqm2anvio directory with all the input files for anvi'o
======== sqm2anvio.pl, v1.1 ========
Error running subprocess: /public/home/jkyin/miniconda2/envs/SqueezeMeta/SqueezeMeta/utils/anvio_utils/../../utils/sqm2tables.py PZH PZH/results/sqm2anvio --sqm2anvio at /public/home/jkyin/miniconda2/envs/SqueezeMeta/SqueezeMeta/utils/anvio_utils/sqm2anvio.pl line 99.
There must be some problem with "/public/home/jkyin/miniconda2/envs/SqueezeMeta/SqueezeMeta/utils/anvio_utils/sqm2anvio.pl PZH PZH/results/sqm2anvio".
It's better to stop and check it
```
line 99 in sqm2anvio.pl is `if($ecode!=0) { die("Error running subprocess: $installpath/utils/sqm2tables.py $project $outdir --sqm2anvio"); }
`
The results/anvio dir is empty ,but in the results/sqm2anvio dir:
```
(anvio-6.2) [jkyin@mn02 sqm2anvio]$ ll
total 833793
drwxr-xr-x 2 jkyin LFRuan      4096 Apr 19 10:06 bam
-rw-r--r-- 1 jkyin LFRuan 546206415 Apr 19 10:09 PZH_anvio_genes.txt
-rw-r--r-- 1 jkyin LFRuan 307411096 Apr 19 10:09 PZH_anvio_SQMequivalence.txt
```

**Comment by fpusan** [comment]
Hi!

What error message do you get when running

`/public/home/jkyin/miniconda2/envs/SqueezeMeta/SqueezeMeta/utils/anvio_utils/../../utils/sqm2tables.py PZH PZH/results/sqm2anvio --sqm2anvio`

?

**Comment by yjiakang** [comment]
```
(anvio-6.2) [jkyin@sg15 squeezemeta]$ /public/home/jkyin/miniconda2/envs/SqueezeMeta/SqueezeMeta/utils/anvio_utils/../../utils/sqm2tables.py PZH PZH/results/sqm2anvio --sqm2anvio
Bus error (core dumped)

```

**Comment by fpusan** [comment]
A bus error is a really weird thing to happen, specially in python code.
If I had to guess, I'd say it's related to how the C extensions used by pandas were compiled in your system.
What is your OS? Can you try again using a fresh conda installation? I would reinstall conda, then add SqueezeMeta and anvi'o in the same environment (SqueezeMeta first). This worked for me when running tests.

**Comment by yjiakang** [comment]
Hi!

- My OS info: 
```
(base) [jkyin@mn02 script]$ cat /proc/version
Linux version 3.10.0-862.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) ) #1 SMP Fri Apr 20 16:44:24 UTC 2018

```

- I did as you suggested. However, the same error I got. 

- I run anvi-load-sqm.py in ain interactive mode with hpc that the RAM is limited, I guess anvi-load-sqm.py needs much RAM, so I submit my job to a node with enough RAM. New error I got as follows:

```
Resource usage summary:

    CPU time :                                   88429.77 sec.
    Max Memory :                                 76274 MB
    Average Memory :                             22986.02 MB
    Total Requested Memory :                     10000.00 MB
    Delta Memory :                               -66274.00 MB
    Max Swap :                                   2 MB
    Max Processes :                              17
    Max Threads :                                94
    Run time :                                   38575 sec.
    Turnaround time :                            38574 sec.
`The output (if any) follows:
======== sqm2anvio.pl, v1.1 ========
Created anvio gene file (import with anvi-gene-contigs-database): PZH/results/sqm2anvio/PZH_anvio_genes.txt
Created anvio contig file (import with anvi-gene-contigs-database): PZH/results/sqm2anvio/PZH_anvio_contigs.txt
Created anvio functions file (import with anvi-import-functions): PZH/results/sqm2anvio/PZH_anvio_functions.txt
Created anvio taxonomy file (import with anvi-import-taxonomy-for-genes): PZH/results/sqm2anvio/PZH_anvio_taxonomy.txt
Created anvio-SQM equivalence (just for reference, don't import this): PZH/results/sqm2anvio/PZH_anvio_SQMequivalence.tx
t
Added SAM files: PZH.PZHH79.sam PZH.PZHH78.sam PZH.PZHD26.sam PZH.PZHH76.sam PZH.PZHD28.sam PZH.PZHD27.sam
 and converted them to the BAM format
Config Error: OK. It is very likley that if you run `anvi-setup-scg-databases` first you will
              be golden. Because even though anvi'o found the directory for taxonomy
              headquarters, your setup seems to be missing 22 of 22 databases required for
              everything to work with the current genes configuration of this class (sources
              say this is a record, FYI).
Loading results from SQM in anvi'o.
Anvi'o is an advanced analysis and visualization platform for 'omics data.
Citation: Eren AM, Ozcan E, Quince C, Vineis JH, Morrison HG, Sogin ML, Delmont TO. (2015) Anvi'o: an advanced analysis and visualization platform for 'omics data. PeerJ 3:e1319
This script calls to sqm2anvio.pl and then runs a set of pre-defined commands to create an anvio database.
If you want to explore ways to manually create the database, and other cool stuff that you can do with anvi'o
please consider checking the anvi'o project page for information, tutorials and more details (http://merenlab.org/software/anvio/).
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
PZH/results/sqm2anvio does not exist
Create sqm2anvio directory with all the input files for anvi'o
/public/home/jkyin/yjk/PZH_meta/squeezemeta/PZH/results/sqm2anvio
Preparing contigs database: loading contigs, genes, functions and taxonomy!
Contigs database is CONTIGS.db. Contigs and genes have been loaded
Running HMMS to detect SCGs
PS:
Read file <PZH_anvi-load-sqm.err> for stderr output of this job.

```

**Comment by fpusan** [comment]
Hi!
We're looking into it.
Can you confirm whether the `PZH/results/sqm2anvio` directory was created? The process that creates it seems to have finished correctly, but then `anvi-load-sqm` complains about it being missing.

**Comment by fpusan** [comment]
Ok, I think we figured it out. It was a bit misleading because the output log was in the wrong order (since it was piped into a file, the main python process was storing its output into a buffer before writing to the file, but the subprocesses wrote to the file as they ended...).

Try dropping the `--run-scg-taxonomy `, or configuring anvi'o with `anvi-setup-scg-databases`.

Also we have only tested our scripts with anvi'o 6.1, @ggnatalia is currently checking if there are any issues with anvi'o 6.2.

Let us know if this works for you.

**Comment by yjiakang** [comment]
Hi! I dropped the `--run-scg-taxonomy` and working with  anvi'o 6.1. No error occurred, but `anvi-load-sqm.py` had run a loooong time (about 5 days). Is it normal? By the way, in the directory `/PZH/results/anvio`，there is only one temp directory — PZHD27 that is one of my project sample, and totally I have 6 samples in my project. Does this means that I need to wait till all my samples been processed completely?
 Thanks for reply. Have a nice day.
Best!
```
(base) [jkyin@mn02 anvio]$ ll
total 16055681
-rw-r--r-- 1 jkyin LFRuan 15457017856 Apr 25 05:12 CONTIGS.db
-rw-r--r-- 1 jkyin LFRuan   983943132 Apr 25 00:05 PZH_anvio_contig_taxonomy.txt
drwxr-xr-x 2 jkyin LFRuan        4096 Apr 27 16:33 PZHD27_temp
```

**Comment by fpusan** [comment]
Hi!

Yes, `anvi-load-sqm.py` can take a long time to run with long metagenomes.  The limiting step are the calls to anvio's  `anvi-profile`, in which bam files containing the alignments of the reads to the contigs are loaded into the anvi'o database. There's not much we can do about it, but the anvi'o developers will likely keep optimizing their software.

I see that you are already discarding shorter contigs with  `--min-contig-length 2500`. You can set that to an even higher value, or maybe remove `--run-HMMS` if you are not interested in bin refining. That step is multithreaded, you can of course just throw more cores to the problem.

Best,

Fernando

**Comment by yjiakang** [comment]
Hi!

Thanks for your prompt reply. I will try as your suggestions. Before doing this, there is a question needed to be checked by you. Because I have no idea before your reply, I refered to  #72 and rerun step2,3 and 13. all they run successfully. However, when rerun step 2 and 3 I used the script `restart.pl PZH -step 2`, it run to step 4 till I found that. And step 4 had some wrong info. I try to deal with it by running `04.rundiamond.pl my/project/`, here is the output:
```
(SqueezeMeta) [jkyin@sg33 scripts]$ ./04.rundiamond.pl /public/home/jkyin/yjk/PZH_meta/squeezemeta/PZH
  Setting block size for Diamond
  AVAILABLE (free) RAM memory: 240.66 Gb
  We will set Diamond block size to 8 (Gb RAM/5, Max 8).
  You can override this setting using the -b option when starting the project, or changing
  the $blocksize variable in SqueezeMeta_conf.pl
  Running Diamond (Buchfink et al 2015, Nat Methods 12, 59-60) for taxaError running command:    /public/home/jkyin/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/diamond blastp -q /public/home/jkyin/yjk/PZH_meta/squeezemeta/PZH/results/03.PZH.faa -p 32 -d /public/home/jkyin/biosoft/database/squeezemeta/db/nr.dmnd -e 0.001 --id 40 -f tab -b 8 --quiet -o /public/home/jkyin/yjk/PZH_meta/squeezemeta/PZH/intermediate/04.PZH.nr.diamond at ./04.rundiamond.pl line 57.
```
I wonder if I ignore this error and run anvi-load-sqm.py, is there any negative effect? By the way, I successfully completed SqueezeMeta.pl with my project. And I made a comparison of  the taxa and function results that obtained before I rerun step 2,3 and 13 and after that, there are no differences.

**Comment by fpusan** [comment]
The error in 04 might have happened due to a lack of memory, depending on what you requested in your cluster.
If you get the same resuls in taxa and functions, I'd say it's alright (but problems may appear if you try to re-run a step that directly relies on the results from the broken `04.rundiamond.pl` run).

**Comment by yjiakang** [comment]
Yes, indeed. The memory question has been solved. Thanks~ 👍
Have a nice day.
Best!

**Comment by fpusan** [comment]
Great, closing issue.
Let me know if you have further issues.
