### ISSUE TITLE
SQMtools for functional analysis

### ISSUE THREAD

**Issue by Alexa2279** [jtamames/SqueezeMeta#890]
Hello. 
I am using Squeezemeta for the analysis of shotgun metagenomics data. 
After the analysis is over, I use the SQMtools to explore the results of the analysis.

For the results of functional analysis, I can create figures but with very specific categories of KEGG and COG. 

I want to create figures focusing on the most general categories of KEGG (e.g. transport and catabolism, carbohydrate metabolism, etc.) and of COG (e.g. RNA processing and modification, amino acid transport and metabolism, etc.).

Could you please advise how I can do it using the SQMtools? 

Thank you very much in advance.

**Comment by fpusan** [comment]
After loading the data in SQMtools, the general categories to which each COG/KEGG belongs to are present within the resulting SQM object.
```
library(SQMtools)
data(Hadza)
Hadza$misc$KEGG_paths
Hadza$misc$COG_paths
```
So you can use this information together with COG/KEGG TPMs abundances (e.g. in `Hadza$functions$KEGG$abund`) and aggregate them to get read counts from more general categories.

However I don't think that this is generally a good or very informative idea, see my previous answer in https://github.com/jtamames/SqueezeMeta/issues/212#issuecomment-765576249.

**Comment by Alexa2279** [comment]
Dear fernando,

Thank you very much for your reply!
