### ISSUE TITLE
Duplicate row.names when using loadSQM

### ISSUE THREAD

**Issue by SamBrutySci** [jtamames/SqueezeMeta#893]
Hi,

I have a project which I recently exported using sqm2zip and I'm trying to load into R, but whether I use the zip file or the original project folder I get this:

Proj1 <- loadSQM("Proj1.zip",tax_mode = "prokfilter",engine = "data.table")
Loading total reads
Loading orfs
    table...
|--------------------------------------------------|
|==================================================|
Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed
In addition: Warning message:
non-unique values when setting 'row.names': ‘megahit_1_1-411’, ‘megahit_1_424-639’, ‘megahit_10_37-309’, ‘megahit_100_25-276’, ‘megahit_100_280-432’, ‘megahit_1000_2-532’, ‘megahit_10000_2-646’, ‘megahit_10000_713-838’, ‘megahit_100000_3-1235’, ‘megahit_1000000_1-378’, ‘megahit_1000001_2-457’, ‘megahit_1000002_2-370’, ‘megahit_1000003_287-439’, ‘megahit_1000004_2-448’, ‘megahit_1000005_1-318’, ‘megahit_1000006_3-536’, ‘megahit_1000007_1-423’, ‘megahit_1000008_2-409’, ‘megahit_1000009_136-345’, ‘megahit_100001_3-626’, ‘megahit_1000010_1-207’, ‘megahit_1000011_1140-1634’, ‘megahit_1000011_254-1132’, ‘megahit_1000011_3-257’, ‘megahit_1000012_1-630’, ‘megahit_1000013_2-673’, ‘megahit_1000014_12-560’, ‘megahit_1000015_114-527’, ‘megahit_1000015_3-113’, ‘megahit_1000016_3-398’, ‘megahit_1000017_1-309’, ‘megahit_1000018_3-308’, ‘megahit_1000019_3-410’, ‘megahit [... truncated] 

Any ideas?

Thanks!

**Comment by fpusan** [comment]
Can you share the zip file with me? I can check

**Comment by SamBrutySci** [comment]
Thanks! Here's a link to the zip file in google drive, hopefully that works! I couldn't think of an easier way.

https://drive.google.com/file/d/1vqtEVuPLnbpq1MeksIrSayr2PiZEJX5y/view?usp=sharing

**Comment by fpusan** [comment]
Ok, somehow all orfs are present 4 times in your table, instead of one...
Each line seems to contain reads for only one sample. An example for one ORF would look like:
```
                  Raw.read.count.JI0015.1 Raw.read.count.JI0015.2
megahit_1_1-411                         3                       0
megahit_1_1-411.1                       0                       2
megahit_1_1-411.2                       0                       0
megahit_1_1-411.3                       0                       0
                  Raw.read.count.JI0015.3 Raw.read.count.JI0015.4
megahit_1_1-411                         0                       0
megahit_1_1-411.1                       0                       0
megahit_1_1-411.2                       1                       0
megahit_1_1-411.3                       0                       1
                  Raw.read.count.JI0015.5 Raw.read.count.JI0015.6
megahit_1_1-411                         0                       0
megahit_1_1-411.1                       0                       0
megahit_1_1-411.2                       0                       0
megahit_1_1-411.3                       0                       0
```
Other elements of the table (e.g. taxonomic and functional annotation) are identical for the repeated ORFs ( as they should )
This is my first time seeing this, and it seems that the project was ran with the latest version...
@SamBrutySci did you do stop and restart this run somehow, or changed the parameters midway?
@jtamames any insight on why this may be happening?

**Comment by SamBrutySci** [comment]
Yes the run was interrupted a couple of times by HPC upgrades taking nodes down! Parameters should have all been consistent when restarting each time however.

Is this fixable with the current run or shall I just re-run from a certain step?

**Comment by fpusan** [comment]
Samples JI0015.5 and JI0015.6 have no counts assigned to any ORF, so I suspect the run got interrupted during the mapping step.
To be safe I would maybe restart from step 10, forcing overwrite.

**Comment by SamBrutySci** [comment]
Thanks so much for your help! Restarting at step 10 forcing overwrite has fixed the issue!

**Comment by ernesfranco** [comment]
Hi! Thank you very much for developing and maintaining SqueezeMeta and SQMTools!

We are experiencing an issue I think related to this issue #893 .

We ran SqueezeMeta v1.7.0 without any apparent errors, using the following commands:
```
SqueezeMeta.pl \
-m coassembly \
-p 2025-04-11_-_xw \
-s sample_file.tsv \
-f path/reads \
-binners "maxbin,metabat2,concoct" \
--gtdbtk \
-gtdbtk_data_path gtdbtk_r220_data/release220 \
--euk \
--doublepas \
-extdb mydb.list \
-b 3 \
-t 32
```

Unfortunately, the execution was interrupted. So, we resume it from the last step:

```
SqueezeMeta.pl \
-m coassembly \
-p 2025-04-11_-_xw \
--restart \
-step 8 \
--force_overwrite
```

Then, we encountered a RAM issue, so we reduced the number of threads to 16 and resumed the run from step 10 (mapping).

```
SqueezeMeta.pl \
-m coassembly \
-p 2025-04-11_-_xw \
--restart \
-step 10 \
--force_overwrite
```

However, when loading the results into SQMTools v1.7.0 (RStudio 2024.12.1 Build 563), we get the following error:

```
project = loadSQM("2025-04-11_-_xw/sqmtools/2025-04-11_-_xw.zip")
Loading total reads
Loading orfs
    table...
|--------------------------------------------------|
|==================================================|
Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed
In addition: Warning messages:
1: In loadSQM_(project_path, tax_mode, trusted_functions_only, single_copy_genes,  :
  You are trying to load a zipped project. If this doesn't work, see workaround in https://github.com/jtamames/SqueezeMeta/issues/755.
2: non-unique values when setting 'row.names': ‘2025-04-11_-_xw_141656_1-114’, ‘2025-04-11_-_xw_1540_2-241’, ‘2025-04-11_-_xw_1720_1-342’, ‘2025-04-11_-_xw_90031_1-126’, ‘2025-04-11_-_xw_900311_1-261’
```

We confirmed that these are the only repeated lines in 13.2025-04-11_-_xw.orftable:

```
cut -f 1 13.2025-04-11_-_xw.orftable | sort | uniq -ic | sort | tail

      ...
      1 2025-04-11_-_xw_999999_521-592
      2 2025-04-11_-_xw_141656_1-114
      2 2025-04-11_-_xw_1540_2-241
      2 2025-04-11_-_xw_1720_1-342
      2 2025-04-11_-_xw_900311_1-261
      3 2025-04-11_-_xw_90031_1-126

```
Then, when searching for them in the ORF table:

```
head -3 13.2025-04-11_-_xw.orftable >> out.tsv

rg "2025-04-11_-_xw_141656_1-114\t|2025-04-11_-_xw_1540_2-241\t|2025-04-11_-_xw_1720_1-342\t|2025-04-11_-_xw_900311_1-261\t|2025-04-11_-_xw_90031_1-126\t" 13.2025-04-11_-_xw.orftable >> out.tsv
```

We got the attached file. We can see that the duplicated ORFs have different TPM, coverage, and count values for some samples.

I was wondering if there is any way to make use of these results without having to rerun the entire pipeline, as I have three large coassemblies affected by the same issue. For instance, would it be possible to simply remove or collapse the duplicated rows? If so, which file(s) should I edit and then load into SQMTools?

Thank you so much!

[out.zip](https://github.com/user-attachments/files/19759404/out.zip)

**Comment by fpusan** [comment]
Glad to hear. Still, it's not great that this happens. There's other issue with the same problem, I'll try to look for ways to fix it
