### ISSUE TITLE
COG Paths

### ISSUE THREAD

**Issue by NatiTs** [jtamames/SqueezeMeta#894]
Hello, 

I am working with three independent SqueezeMeta runs, which I later combined into a single SQMobject. For each run, I have SqueezeMeta output files named my_sample.COG.names containing the "Name" and "Path" of each COG entry. Does the "Path" correspond to the "COG CATEGORIES" from Database of Clusters of Orthologous Genes (COGs)? In case it indeed represent the COG categories, I have encountered several issues:

- Some COG entries are assigned to paths that do not exactly match the standard COG categories. For example, COG0001 is assigned to the path "Coenzyme metabolism," whereas the correct category in the COG database is "Coenzyme transport and metabolism." However, the correct path "Coenzyme transport and metabolism" is present in the same file for other entries (e.g., ENOG410XUTZ). Should I assume that both "Coenzyme metabolism" and "Coenzyme transport and metabolism" refer to the same path, i.e., "Coenzyme transport and metabolism"?

- Some COG entries are marked with "no path available." For instance, COG4790 is missing a path, yet it is listed under "Intracellular trafficking, secretion, and vesicular transport" in the COG database. Is there a reason why some COGs are not assigned a path despite their classification in the COG database?

- Some COGs appear to be assigned to the wrong path/category. For example, COG0037 is placed under "Cell division and chromosome partitioning" in the output file, whereas the COG database assigns it to "Translation, ribosomal structure and biogenesis."

- When exporting the COG function abundance table from SQMxplore, some COG function names are listed as "NA." For example, COG0833 is marked as "NA" in the abundance table, yet both the "Name" ("Amino acid transporters") and the "Path" ("Amino acid transport and metabolism") are correctly presented in the individual my_sample.COG.names output files from the SqueezeMeta run.
Is this a bug in the export process?

I would greatly appreciate any guidance on how to address these issues.
Thank you very much in advance!

**Comment by jtamames** [comment]
Hello!
I think most of your questions point to the fact that we are using a previous version of the COG database, not the current eggNOG 5 database. Therefore some annotations do differ between the two versions. I have been trying to update to eggNOG v5 but found a lot of problems regarding file formats, which so far I could not fix. Still trying tho. 
Last question regarding SQMtools maybe can be answered by @fpusan 
Best,
J

**Comment by NatiTs** [comment]
Dear Javier,
Thank you very much for your reply!

**Comment by fpusan** [comment]
Sorry for the late answer.
How are you exporting the COG function abundance table from SQMtools exactly?

**Comment by fpusan** [comment]
Continuing this, the names / paths for each COG are stored in `SQM$misc$COG_names` and `SQM$misc$COG_paths`. These are named vectors (COG as keys, COG names/paths as values) and should contain entries for all the COGs in your dataset.

So something like

```
ta = SQM$functions$COG$abund # this table has COG IDs in rows, samples in columns
rownames(ta) = paste(rownames(ta), SQM$misc$COG_names[rownames(ta)]) # now we have also added the name for each COG
exportTable(ta, 'output.tsv')
```
should work.

**Comment by NatiTs** [comment]
Dear Fernando, 

Thank you for getting back to me!

To clarify, I'm exporting the COG functions abundance table using SQMxplore. Specifically, after combining the three runs into a single SQM object, I save the .RDS file and work within SQMxplore which contains the "Tables" tab that allows to display and download the COG abundance table for the combined SQM object.

I also tried the following command using SQMtools: exportTable(Combined_SQM_object$functions$COG$abund, "cog.tsv")
However, this only exports the COG IDs without their associated names and paths. 

If I understand correctly, the "combine-sqm-tables.py" script in Squeezemeta is no longer available. Is there an equivalent tool at the moment that provides the same functionality?
Is there an alternative way to export the combined COG table containing COG ids, names and paths?

Any advice would be greatly appreciated!

**Comment by fpusan** [comment]
You keep saying SQMxplore... I assume you mean SQMtools or am I missing something?

**Comment by fpusan** [comment]
`combine-sqm-tables.py` is no longer maintained but it is still available and will probably still work.
But anyways I think my example from above should work with your current dataset

```
ta = Combined_SQM_object$functions$COG$abund
rownames(ta) = paste(rownames(ta), Combined_SQM_object$misc$COG_names[rownames(ta)]) # now we have also added the name for each COG
exportTable(ta, 'output.tsv')
```

**Comment by NatiTs** [comment]
Thank you very much, I tried what you suggested, and it works perfectly!

Regarding SQMxplore, it's an interactive data visualization tool integrated into the SqueezeMeta environment. 
https://github.com/redondrio/SQMxplore

Thanks again for your help!

**Comment by fpusan** [comment]
Ah right! I had forgotten that existed 😅
Glad to hear It worked, closing issue!
