### ISSUE TITLE
Issue downloading 

### ISSUE THREAD

**Issue by ameliarmcclure** [jtamames/SqueezeMeta#896]
I am trying to run the package to download the databases with the code provided (pasted below) and am getting a lot of errors (also pasted below).

Could anyone give any tips or point me in the direction of a source that explains the syntax of perl so I can troubleshoot?

`use strict;

if(!$ARGV[0]) { die /gpfs1/home/a/m/amcclure }

use Cwd 'abs_path';
my $download_dir = /gpfs1/home/a/m/amcclure;
my $database_dir = "$download_dir/db";

if(!$download_dir) { die "Usage: perl download_databases.pl <download dir>\n"; }

###scriptdir patch v2, Fernando Puente-Sánchez, 18-XI-2019
use File::Basename;

my $dbscriptdir;
if(-l __FILE__)
        {
        my $symlinkpath = dirname(__FILE__);
 my $symlinkpath = dirname(__FILE__);
        my $symlinkdest = readlink(__FILE__);
        $dbscriptdir = dirname(abs_path("$symlinkpath/$symlinkdest"));
        }
else
        {
        $dbscriptdir = abs_path(dirname(__FILE__));
        }
my $installpath = abs_path("$dbscriptdir/../..");
my $libpath = "$installpath/lib";
require "$libpath/install_utils/download_confirm.pl";
require "$libpath/install_utils/get_host.pl";
###

my $host = get_host();

system("rm $download_dir/test.tar.gz $libpath/classifier.tar.gz $download_dir/SqueezeMetaDB.tar.gz > /dev/null 2>&1");

### Download test data (-U '' so that we give the server an user agent string, it complains otherwise).
print "\nDownloading and unpacking test data...\n\n";
download_confirm("test.tar.gz", "test.md5", "$host/SqueezeMeta/", $download_dir);

### Download db tarball. (-U '' so that we give the server an user agent string, it complains otherwise)
print "Downloading and unpacking database tarball...\n";
download_confirm("SqueezeMetaDB.tar.gz", "SqueezeMetaDB.md5", "$host/SqueezeMeta/", $download_dir);

### Finish configuration.
system("perl $installpath/utils/install_utils/configure_nodb.pl $database_dir");`

Errors:
Having no space between pattern and following word is deprecated at /var/spool/slurm/d/job20733658/slurm_script line 25.Bareword found where operator expected at /var/spool/slurm/d/job20733658/slurm_script line 25, near "/gpfs1/home"
        (Missing operator before home?)
Having no space between pattern and following word is deprecated at /var/spool/slurm/d/job20733658/slurm_script line 28.Having no space between pattern and following word is deprecated at /var/spool/slurm/d/job20733658/slurm_script line 29.String found where operator expected at /var/spool/slurm/d/job20733658/slurm_script line 31, near "if(!$download_dir) { die ""
  (Might be a runaway multi-line "" string starting on line 29)
        (Missing semicolon on previous line?)
String found where operator expected at /var/spool/slurm/d/job20733658/slurm_script line 41, near "$dbscriptdir = dirname(abs_path(""
  (Might be a runaway multi-line "" string starting on line 31)
        (Missing semicolon on previous line?)
String found where operator expected at /var/spool/slurm/d/job20733658/slurm_script line 47, near "my $installpath = abs_path(""
  (Might be a runaway multi-line "" string starting on line 41)
        (Missing semicolon on previous line?)
Having no space between pattern and following word is deprecated at /var/spool/slurm/d/job20733658/slurm_script line 48.String found where operator expected at /var/spool/slurm/d/job20733658/slurm_script line 49, near "require ""
  (Might be a runaway multi-line "" string starting on line 48)
        (Missing semicolon on previous line?)
Scalar found where operator expected at /var/spool/slurm/d/job20733658/slurm_script line 49, near "require "$libpath"
        (Do you need to predeclare require?)
String found where operator expected at /var/spool/slurm/d/job20733658/slurm_script line 50, near "require ""
  (Might be a runaway multi-line "" string starting on line 49)
        (Missing semicolon on previous line?)
Scalar found where operator expected at /var/spool/slurm/d/job20733658/slurm_script line 50, near "require "$libpath"
        (Do you need to predeclare require?)
String found where operator expected at /var/spool/slurm/d/job20733658/slurm_script line 55, near "system(""
"download_database1.out" 60L, 5221C

**Comment by jtamames** [comment]
Hello
The problem is that somebody messed with the code here, and broke it in the process. I don´t know what you intended to do, but it is not necessary. The script must be run specifying a directory to download, no need to put it in the code.
I suggest reinstalling this script, and taking a look at the manual for usage. Should you changed the code because you found any problems with downloads, feel free to reopen the issue.
Best,
J
