### ISSUE TITLE
An error occurred during mapping with bowtie, Stopping in STEP10 -> 10.mapsamples.pl.

### ISSUE THREAD

**Issue by rachel1898** [jtamames/SqueezeMeta#897]
Hello,

I have encountered the issue "reference file not found: path/to/_current_1" for bowtie, while running 10.mapsamples.pl in two paired end metagenome files in merged mode (also tried it in coassembly and sequential mode and crashes at the same step). Here I attached syslog file
[syslog.txt](https://github.com/user-attachments/files/17555677/syslog.txt)
I am not pretty sure but it looks like it might be something related to the fact that in syslog line 216 the copy command doesn't correctly get the path for the input file and crashes later due to the lack of the expected file. Curiously, it happens when searching path for the second sample since first sample got path correctly and results are perfectly created. I have run squeezemeta many times before, following the same preprocessing steps without any mayor problem, in fact squeezemeta is fantastic. However, i am not confident about how to solve this bug or what might be happening. Any help would be great. Many thanks in advance!

**Comment by jtamames** [comment]
Hello
I think you may have an error in your samples file, and the file HLC1B_R1.fastq.gz is listed both as pair1 and pair2 in one of the samples, could it be?
Best,
J

**Comment by rachel1898** [comment]
That was it!! Sorry it didn't occur to me to check samples file. 
Thank you very much! I close the issue

Best,
Rachel
