### ISSUE TITLE
Errno 2 with sqm2zip

### ISSUE THREAD

**Issue by kmarr037** [jtamames/SqueezeMeta#902]
Hello! I'm having an issue with sqm2zip.py where I run the following script: 

_sqm2zip.py /home/username/scripts/my_project /home/username/scripts/my_project.zip_

And I get the following error: 

_Traceback (most recent call last):
  File "/home/username/.conda/envs/SqueezeMeta/bin/sqm2zip.py", line 103, in <module>
    main(parse_args())
  File "/home/username/.conda/envs/SqueezeMeta/bin/sqm2zip.py", line 42, in main
    perlVars = parse_conf_file(args.project_path, override = {'$projectdir': args.project_path})
  File "/home/username/.conda/envs/SqueezeMeta/SqueezeMeta/utils/../lib/utils.py", line 22, in parse_conf_file
    for line in open('{}/SqueezeMeta_conf.pl'.format(project_path)):
FileNotFoundError: [Errno 2] No such file or directory: '/home/username/scripts/my_project/SqueezeMeta_conf.pl'_ 

I saw that another issue had been resolved by making sure the output directory exists, but mine does, so this is not the issue for me. I have also tried changing directories to run this, and I get the same error. Any thoughts would help so I can finish my analysis. Thank you in advance! :)

**Comment by fpusan** [comment]
Is `/home/username/scripts/my_project/` a project generated with SqueezeMeta.pl?

Also the second argument to `sqm2zip.py` is just the path an output directory (not the actual name of the output file)

**Comment by kmarr037** [comment]
Hi, thank you for your reply! Yes, `/home/username/scripts/my_project` is the SqueezeMeta project that I made with the -p command. 

And for the second argument, even when I change it to just `/home/username/scripts` I'm still getting the same error.

**Comment by kmarr037** [comment]
Hi! I apologize for the inconvenience but I got it to work. I copy/pasted the pwd rather than typing it out and that satisfied it. (Even though there were no typo's when I typed it out.) 

Anyway, thank you for trying to help with my issue! :)

**Comment by fpusan** [comment]
Glad to hear it's fixed! Closing issue
