### ISSUE TITLE
sqm2tables.py:too many values to unpack

### ISSUE THREAD

**Issue by mingxues2024** [jtamames/SqueezeMeta#903]
Hi,
I met an error when I was running sqm2tables. "sqm2tables.py C16 summary/C16_output  --trusted-functions --ignore-unclassified"The error showed below:
Traceback (most recent call last):
  File "/lustre/miniforge3/envs/SqueezeMeta/bin/sqm2tables.py", line 223, in <module>
    main(parse_args())
  File "/lustre/miniforge3/envs/SqueezeMeta/bin/sqm2tables.py", line 123, in main
    orf_tax_nofilter, orf_tax_nofilter_wranks = parse_tax_table(fun_prefix + '.noidfilter.wranks', noCDS = noCDSorfs)
  File "/lustre/miniforge3/envs/SqueezeMeta/SqueezeMeta/utils/../lib/utils.py", line 278, in parse_tax_table
    orf, tax = line
ValueError: too many values to unpack (expected 2)
Could you give some suggestions to avoid this error?

Best.

**Comment by fpusan** [comment]
Can you share with me the file that is present in the the ends with `.tax.noidfilter.wrank`

**Comment by fpusan** [comment]
Posting again as I updated my previous answer

**Comment by mingxues2024** [comment]
> Posting again as I updated my previous answer

Dear sir,

I think I could not upload the file because it was bigger than the limitation(25 MB)
Is there any other way I could upload?

Best

**Comment by fpusan** [comment]
Yes, can you maybe use something like wetransfer, onedrive, mega, etc?
