### ISSUE TITLE
Stopping in STEP1 -> 01.run_all_assemblies.pl. Program finished abnormally

### ISSUE THREAD

**Issue by JackDettoLoco** [jtamames/SqueezeMeta#904]
[syslog.zip](https://github.com/user-attachments/files/17666982/syslog.zip)

Hello. I’m running SqueezeMeta on a remote PC. I initially tried running it in co-assembly mode, but I encountered an error during the Megahit step with error code -6. After researching online, I suspected it could be a memory issue since the remote PC has 180 GB of RAM and my 6 files (3 samples - pair 1|2) total 140 GB.

So, I deleted the previous run and launched it again using the "merged" method with the same options. I received the same Megahit error (-6), and it also appears that SqueezeMeta is unable to access the folders it created.

Could there be a permissions issue? I don’t have sudo privileges on this terminal.

Problem Description: I'm encountering an error during assembly with Megahit in "merged" mode using SqueezeMeta v1.6.5. The process stops in STEP1 -> 01.run_all_assemblies.pl, with a message indicating that the program cannot locate the contig file /project/6040904/giampi98/Giacomo/Shotgun/AN1011PosWGS3/intermediate/01.AN1011PosHCH.fasta, which prevents the assembly from continuing.

Execution Setup:

Command used: SqueezeMeta.pl -m merged -p AN1011PosWGS3 -s /project/6040904/giampi98/Giacomo/Shotgun/Sample_file.tsv -f /project/6040904/giampi98/Giacomo/Shotgun/DNA -t 45
SqueezeMeta Version: v1.6.5
Assembly Program: Megahit
Runtime Environment: Conda environment for SqueezeMeta

**Comment by fpusan** [comment]
I don't think it is a permissions issue. I think SqueezeMeta can't locate the file because MEGAHIT failed without producing it.

Any more information in `/project/6040904/giampi98/Giacomo/Shotgun/AN1011PosWGS3/data/megahit/log`

It's true that the exit code -6 in MEGAHIT has been related to lack of memory. I've also seen at least on issue in which the user claimed that it was fixed after reducing the number of threads. https://github.com/voutcn/megahit/issues/315

Another alternative would be normalizing the libraries as described in https://github.com/voutcn/megahit/issues/239#issuecomment-534373589

**Comment by JackDettoLoco** [comment]
I also tried running the same command with only one thread, and the Megahit error changed to -1.

[log2.zip](https://github.com/user-attachments/files/17680529/log2.zip)
[syslog2.zip](https://github.com/user-attachments/files/17680530/syslog2.zip)

**Comment by fpusan** [comment]
According to the last MEGAHIT log you are trying to assemble 2115033784 reads. That's simply too much for 180 Gb. You can try in a bigger machine, or maybe try digital normalization to make it more tractable.

**Comment by JackDettoLoco** [comment]
I can request additional resources from my provider. In your opinion, how much RAM should I ask for? The processor is an Intel(R) Xeon(R) Gold 6230R CPU @ 2.10GHz.

**Comment by fpusan** [comment]
Sorry for the late response. Honestly as much RAM as you can get, and I'm still not sure it would assemble...

**Comment by JackDettoLoco** [comment]
Hi,

Thank you for your support. I managed to resolve the issue by running the pipeline on the gelmn partition of the GREX cluster (https://um-grex.github.io/grex-docs/).

The partition provided sufficient resources, and with 1400 GB of RAM, the process completed successfully.

Thanks again!
