### ISSUE TITLE
COVERAGE IN 19.CONTIGS.TABLE

### ISSUE THREAD

**Issue by inej90** [jtamames/SqueezeMeta#911]
Dear Fernando and Javier,

I would like to know how the coverage is calculated in the following table:

![Captura de pantalla 2024-11-28 171442](https://github.com/user-attachments/assets/c8e0e4b8-d159-40d1-9b6a-e44673c00be3)

Thank you in advance.

**Comment by fpusan** [comment]
Total bases mapped to the contig divided by the contig length. This tells you, on average, how many reads are covering each base of the contig.

**Comment by inej90** [comment]
Dear Fernando, now it's clear for me. Thank you for your answer.

Best regards.
