### ISSUE TITLE
Why does "03.*.fna" not contain blastx predictions?

### ISSUE THREAD

**Issue by weishwu** [jtamames/SqueezeMeta#913]
It seems that none of the "Diamond BlastX" predictions present in 08.\*.gff is in "03.\*.fna/faa". "03.\*.fna/faa" has only prodigal and barrnap predictions. Is this expected?
Are blastx predictions used in the searches agaist genbank, pfam, cog and kegg?

**Comment by jtamames** [comment]
If you are running step 8 with the -D option, the files in 03 are replaced by the ones in 08, because new gene predictions were done.
Best,
J

**Comment by weishwu** [comment]
Got it. I see that I can get 08.*.blastx.fna from the intermediate/ folder. Thanks!
