### ISSUE TITLE
Download database

### ISSUE THREAD

**Issue by zhaosq2022** [jtamames/SqueezeMeta#914]
Hi,
When i tried to download and configure the database using download_databases.pl, it didn't work.
I tried two links in get_host.pl in multiple ways, but none of them worked. Is it a problem with the links?
Thanks in advance.

**Comment by fpusan** [comment]
Yes it seems to be down, me and @jtamames will look into it

**Comment by jtamames** [comment]
Hello
This should be working now. Could you please check?
Best,
J

**Comment by jtamames** [comment]
Glad to hear. Closing issue.
