### ISSUE TITLE
How should I handle duplicated reads?

### ISSUE THREAD

**Issue by weishwu** [jtamames/SqueezeMeta#915]
I'm new to metagenomics analysis and wonder how duplicated reads are handled in the Squeezemeta workflow or the general metagenomics analysis best practice:
- Is it recommended to dedup the reads (the ones with identical sequences) before running metagenome assembly? This was evaluated in this [paper](https://pubmed.ncbi.nlm.nih.gov/36744896/) and the conclusion was that removing dups improved binning yields and accuracy. Deduping is included in QC in the [Atlas pipeline](https://github.com/metagenome-atlas/atlas) which uses [clumpify.sh](https://github.com/BioInfoTools/BBMap/blob/master/sh/clumpify.sh) to remove exact and near-exact (allowing 2 mismatches) reads. 
- In the taxa abundance outputs from SqueezeMeta, the read counts are based on the Bowtie2 alignments on the assembled contigs. At this step, duplicates can be defined as the reads that have identical mapping coordinates. Is it recommended to calculate the abundance based on dedupped read counts?
- Is there any potential disadvantage/caveat to remove read duplicates in metagenomics analysis? For example, can deduping the reads distort the abundance measurement (such as underestimating a highly abundant strain/gene)?

Thanks.

**Comment by fpusan** [comment]
This is an interesting question!

We do not do replicate removal in SqueezeMeta (incidentally, we also don't do quality filtering by default).
In our experience this has little effect in assembly or binning when working with Illumina reads (ONT reads ofc will have more errors, but also use different assemblers that will be aware of this). This is also consistent to what other researchers are doing (see eg this [data paper](https://www.nature.com/articles/sdata2017203) and the [accompanying methods](https://www.protocols.io/view/assembly-procedure-applied-to-tara-oceans-data-ex-5jyl8eprl2wp/v1) a data paper on Tara Oceans bins, in which they also don't seem to do any read trimming or deduplication).

Now in principle one could indeed argue that removing duplicates (if assumed to be artifacts, which probably is not an unfair assumption) would help with assembly and particularly binning (as duplicates may distort coverage profiles). I wasn't aware of the [reference](https://pubmed.ncbi.nlm.nih.gov/36744896/) you shared with us (thanks!). After looking at it it seems that deduplication may have an effect, but it is generally quite weak except for the soil metagenomes (and even there it only shows when using MEGAHIT).

I would love to see what difference it makes to your dataset, if you are willing to try.

**Comment by weishwu** [comment]
Thanks @fpusan for sharing your knowledge and insights! Deduplication is also covered in this review paper: https://pmc.ncbi.nlm.nih.gov/articles/PMC6153607/. There is indeed some debate about it. Right now I'm using deduped reads to run SqueezeMeta. I used the `addcount=t` flag in `clumpify.sh` to keep a record of the duplicate counts so that I may be able to expand them if needed in the downstream read counting.

**Comment by fpusan** [comment]
That second review also makes a good point, which is that duplicates should only be removed when using a PCR library prep method. If using a PCR-free method (such as Illumina TruSeq DNA PCR-Free) then you should not do it.
