### ISSUE TITLE
itol labels.txt empty 

### ISSUE THREAD

**Issue by yjiakang** [jtamames/SqueezeMeta#93]
Hi! sorry to distrub you again. I met some questions during running sqm2itol.pl. 
First, no info in the labels.txt after running sqm2itol.pl, and everything seems to be fine from the out.
```
(SqueezeMeta) [jkyin@sg04 squeezemeta]$ sqm2itol.pl -completion 70 -contamination 10 -functions kegg_selected.txt PZH
Reading bins in /public/home/jkyin/yjk/PZH_meta/squeezemeta/PZH/results/19.PZH.bintable...
Found 209 bins
Working with 63 bins with more than 70% completion and less than 10% contamination
Using RPKM values
Reading requested functions from kegg_selected.txt
Reading functions in /public/home/jkyin/yjk/PZH_meta/squeezemeta/PZH/results/21.PZH.metacyc.pathways
Reading sequences in /public/home/jkyin/yjk/PZH_meta/squeezemeta/PZH/results/03.PZH.faa
Getting sequences for bin metabat2.93.fa.contigs_Bacteroidetes
Running CompareM: PATH=/public/home/jkyin/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin:$PATH comparem aai_wf --proteins /public/home/jkyin/yjk/PZH_meta/squeezemeta/PZH/temp/comparem -x faa /public/home/jkyin/yjk/PZH_meta/squeezemeta/PZH/results/DAS/PZH_DASTool_bins
[2020-04-25 10:07:24] INFO: CompareM v0.0.23
[2020-04-25 10:07:24] INFO: comparem aai_wf --proteins /public/home/jkyin/yjk/PZH_meta/squeezemeta/PZH/temp/comparem -x faa /public/home/jkyin/yjk/PZH_meta/squeezemeta/PZH/results/DAS/PZH_DASTool_bins
[2020-04-25 10:07:24] INFO: Appending genome identifiers to query genes.
[2020-04-25 10:07:26] INFO: Creating DIAMOND database (be patient!).
[2020-04-25 10:07:46] INFO: Performing self similarity sequence between genomes (be patient!).
[2020-04-25 10:25:12] INFO: Sorting table with hits (be patient!).
[2020-04-25 10:25:49] INFO: Sequence similarity results written to: /public/home/jkyin/yjk/PZH_meta/squeezemeta/PZH/results/DAS/PZH_DASTool_bins/similarity
[2020-04-25 10:25:49] INFO: Calculating length of genes.
[2020-04-25 10:25:51] INFO: Indexing sorted hit table.
[2020-04-25 10:25:58] INFO: Calculating AAI between all 1953 pairs of genomes:
  Finished processing 1953 of 1953 (100.00%) pairs.
[2020-04-25 10:27:06] INFO: Summarizing AAI results.
[2020-04-25 10:27:06] INFO: AAI between genomes written to: /public/home/jkyin/yjk/PZH_meta/squeezemeta/PZH/results/DAS/PZH_DASTool_bins/aai/aai_summary.tsv
[2020-04-25 10:27:08] INFO: CompareM v0.0.23
[2020-04-25 10:27:08] INFO: comparem hclust /public/home/jkyin/yjk/PZH_meta/squeezemeta/PZH/results/DAS/PZH_DASTool_bins/aai/dist.out /public/home/jkyin/yjk/PZH_meta/squeezemeta/PZH/ext_tables/PZH.nw
[2020-04-25 10:27:08] INFO: Performing hierarchical clustering.
[2020-04-25 10:27:08] INFO: Hierarchical cluster tree written to: /public/home/jkyin/yjk/PZH_meta/squeezemeta/PZH/ext_tables/PZH.nw
Tree created in /public/home/jkyin/yjk/PZH_meta/squeezemeta/PZH/ext_tables/PZH.nw
Dataset 1 (abundances) created in /public/home/jkyin/yjk/PZH_meta/squeezemeta/PZH/ext_tables/heatmap_abund.txt
Dataset 2 (pathways) created in /public/home/jkyin/yjk/PZH_meta/squeezemeta/PZH/ext_tables/heatmap_pathways.txt
Dataset 3 (Completion) created in /public/home/jkyin/yjk/PZH_meta/squeezemeta/PZH/ext_tables/heatmap_completion.txt
Dataset 4 (Labels) created in /public/home/jkyin/yjk/PZH_meta/squeezemeta/PZH/ext_tables/labels.txt
tar file created in /public/home/jkyin/yjk/PZH_meta/squeezemeta/PZH/ext_tables/plot.tar
Now upload tree and datasets in https://itol.embl.de
```
labels.txt
TREE_COLORS
SEPARATOR TAB
DATA
Second question: is it possible to assign level-2 kegg pathway (e.g. Carbohydrate   metabolism) or level-3 kegg pathway (e.g. Streptomycin biosynthesis) with the -functions parameter to select some function we focus? 
Thanks in advance.

**Comment by jtamames** [comment]
Hello!
Not a disturbance, anything that let us improve the software is welcomed.
Could you please send me the bin table ( file 19.project.bintable)?
Best,
Javier

**Comment by yjiakang** [comment]
[19.PZH.bintable.zip](https://github.com/jtamames/SqueezeMeta/files/4534471/19.PZH.bintable.zip)
Hi! Here is the file. Thanks~

**Comment by jtamames** [comment]
Hello
There was a bug in the parsing of taxa in sqm2itol.pl. I fixed it, please download the script from the repo and replace the one you have. Then run the script again, and the labels should be ok. Please tell me otherwise
Regarding the specification of additional pathway levels, I am looking into it. 
Best,

**Comment by jtamames** [comment]
Hello
I am attaching here two files: first is a modified version of `sqm2itol.pl`. You must replace the one you have with this one (the bug commented above is also fixed). The other one, `pathwaylist.dat`, must replace the one you have in `<installdir>/data`, where installdir is your SqueezeMeta installation directory. You would see that this new file contains the full KEGG ontology.
Now, you can put any of the ontology levels to the file you will provide with the -functions argument, and the selection will be done accordingly. Labels for the pathways remain unchanged tho, being them the deepest level in the ontology (3rd level in KEGG).

Let me know if it works
Best,
Javier

[pathwaylist.dat.gz](https://github.com/jtamames/SqueezeMeta/files/4539102/pathwaylist.dat.gz)
[sqm2itol.pl.gz](https://github.com/jtamames/SqueezeMeta/files/4539103/sqm2itol.pl.gz)

**Comment by yjiakang** [comment]
Hi
Yeah! The labels question solved properly. However, when I filter my focused functions, the pathway info is too much to display. And the colnames of `heatmap_pathways.txt` produced by different focused functions seem to be uniform. 

The script is the same as before:`sqm2itol.pl -completion 70 -contamination 10 -functions kegg_selected.txt PZH
`
No error produced.



Here I am attaching two files named `heatmap_pathways_antibiotic.txt` and `heatmap_pathways_strepmycin.txt` that are produced by providing `-functions /file/including/antibiotic/key/word` and `-functions /file/including/strepmycin/key/word`, respectively. I think there may be sth set improperly. Need your help, thank you veeeery much.
[heatmap_pathways_strepmycin.txt](https://github.com/jtamames/SqueezeMeta/files/4543465/heatmap_pathways_strepmycin.txt)
[heatmap_pathways_antibiotic.txt](https://github.com/jtamames/SqueezeMeta/files/4543466/heatmap_pathways_antibiotic.txt)

**Comment by jtamames** [comment]
Hi
Can you send me the actual keyword files you are using, so that I can reproduce the results?

**Comment by yjiakang** [comment]
Hi
May be I know what is wrong——I used the same file name of the argument -functions. Everything looks good. Sorry for disturbance. 
Best!

**Comment by yjiakang** [comment]
Hi again
Is there any way to get a table in which the rownames are level3 kegg pathway name, and the file content is tpm of pathway. Just like this:

![XB$NIZ5(HF${XH7C@E H2 W](https://user-images.githubusercontent.com/49177016/80596691-57eb9200-8a59-11ea-9c1d-454d86af7336.png)
Because I intend to do statistical analysis for filtering functions with differential abundance. Thanks a lot.

**Comment by jtamames** [comment]
Closing issue

**Comment by RitaBogorad** [comment]
Hey,
Could you please let me know what exactly this "pathwaylist.dat" table is and how did you make it?
I am studying KEGG pathways in my environmental bacteria results and I noticed that this table represents a collection of useful ko ids without all the human ones. 
I would like to know the origin of this table and if you think that I can use those ko ids for the enrichment analysis on my data so I don't see enriched cancer pathways in my marine bacteria:)
Thank you in advance!
