### ISSUE TITLE
ERROR in STEP15 with test dataset

### ISSUE THREAD

**Issue by bresyd** [jtamames/SqueezeMeta#94]
Hi Javier,

I am getting an error at step 15 when I run squeezemeta on the test dataset.
```
STEP15 -> METABAT BINNING: 15.bin_metabat2.pl
Error running command:    /home/btschits/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/metabat2 -t 8 -i /scratch/btschits/so245/squeezemeta/test/Hadza/temp/bincontigs.fasta -a /scratch/btschits/so245/squeezemeta/test/Hadza/results/metabat2/contigs.depth.txt -o /scratch/btschits/so245/squeezemeta/test/Hadza/results/metabat2/metabat2 --saveTNF saved_1500.tnf --saveDistance saved_1500.dist at /home/btschits/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/15.bin_metabat2.pl line 117.
ERROR in STEP15 -> 15.bin_metabat2.pl
wc: /scratch/btschits/so245/squeezemeta/test/Hadza/results/metabat2/: Is a directory
WARNING in STEP15 -> 15.bin_metabat2.pl. File /scratch/btschits/so245/squeezemeta/test/Hadza/results/metabat2/ is empty, no Metabat2 results!
```

All the other steps finished successfully without issues. I installed squeezemeta (v1.1.1) using conda. Repeating the pipeline with  `restart.pl Hadza -step 15` gives the same error.  There are no files produced in the 'Hadza/results/metabat2/' directory other than contigs.depth.txt.

Any idea about what is going wrong?

Thanks a lot for your help,

cheers

benni

**Comment by fpusan** [comment]
Hi,

What exact command did you use to run SqueezeMeta?

What is the output of running:

`/home/btschits/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/metabat2 -t 8 -i /scratch/btschits/so245/squeezemeta/test/Hadza/temp/bincontigs.fasta -a /scratch/btschits/so245/squeezemeta/test/Hadza/results/metabat2/contigs.depth.txt -o /scratch/btschits/so245/squeezemeta/test/Hadza/results/metabat2/metabat2 --saveTNF saved_1500.tnf --saveDistance saved_1500.dist`

**Comment by bresyd** [comment]
Hi,

thanks for your reply.

The command I used was `SqueezeMeta.pl -m coassembly -p Hadza -s test.samples -f raw`

The output of running
`/home/btschits/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/metabat2 -t 8 -i /scratch/btschits/so245/squeezemeta/test/Hadza/temp/bincontigs.fasta -a /scratch/btschits/so245/squeezemeta/test/Hadza/results/metabat2/contigs.depth.txt -o /scratch/btschits/so245/squeezemeta/test/Hadza/results/metabat2/metabat2 --saveTNF saved_1500.tnf --saveDistance saved_1500.dist`
is
`MetaBAT 2 (v2.12.1) using minContig 2500, minCV 1.0, minCVSum 1.0, maxP 95%, minS 60, and maxEdges 200. 
Segmentation fault`

**Comment by fpusan** [comment]
I'm running that test in a fresh conda environment, to see whether I can reproduce the error.
What is your operating system?

**Comment by bresyd** [comment]
Thanks again.

`uname -srm
Linux 4.19.0-8-amd64 x86_64`
and
`cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"`

**Comment by fpusan** [comment]
We have not tested SqueezeMeta in Debian, it might be that some binaries compiled in Ubuntu are not working there.

Can you compile metabat2 from source (https://bitbucket.org/berkeleylab/metabat/src/master/) in your system, and re-run the last command you tried using the newly compiled version?

Anyways I'll keep running the test on my part to see if the problem is not distribution-related.

**Comment by fpusan** [comment]
Just a quick update, I have re-checked that the v1.1.1 from conda (including the metabat step) works with the test data.

So the problem indeed seems limited to some Linux distributions. We routinely test SqueezeMeta in Ubuntu and CentOS. I will try setting up a Debian VM for testing, maybe its not difficult to make it work there too.

Meanwhile, can you try compiling metabat2 in debian and see if that fixes the issue?

**Comment by bresyd** [comment]
Hi again,

thanks for your efforts.

I installed the metabat binaries directly and when I use this binary installation for 
`~/apps/metabat/matbat_bin/bin/metabat2 -t 8 -i /scratch/btschits/so245/squeezemeta/test/Hadza/temp/bincontigs.fasta -a /scratch/btschits/so245/squeezemeta/test/Hadza/results/metabat2/contigs.depth.txt -o /scratch/btschits/so245/squeezemeta/test/Hadza/results/metabat2/metabat2`
I get
`MetaBAT 2 (GIT-NOTFOUND) using minContig 2500, minCV 1.0, minCVSum 1.0, maxP 95%, minS 60, maxEdges 200 and minClsSize 200000. with random seed=1588167502
53 bins (31322376 bases in total) formed.`
This produces 53 fasta files (one for each bin) in the Hadza/results/metabat2/ directory. So I guess it worked.
However, I had to remove the `--saveTNF saved_1500.tnf --saveDistance saved_1500.dist` arguments since they are not recognized by metabat2 (they are metabat1 arguments I believe) to make this work.
So when I replaced the metabat2 executable in the `/home/btschits/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/` directory with the new installed one, and then run  
`restart.pl Hadza -step 15` I get an error for those arguments it can't recognize
`terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::unknown_option> >'
  what():  unrecognised option '--saveTNF'
Error running command:    /home/btschits/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/metabat2 -t 8 -i /scratch/btschits/so245/squeezemeta/test/Hadza/temp/bincontigs.fasta -a /scratch/btschits/so245/squeezemeta/test/Hadza/results/metabat2/contigs.depth.txt -o /scratch/btschits/so245/squeezemeta/test/Hadza/results/metabat2/metabat2 --saveTNF saved_1500.tnf --saveDistance saved_1500.dist at /home/btschits/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/15.bin_metabat2.pl line 117.
ERROR in STEP15 -> 15.bin_metabat2.pl
`
Any ideas?

**Comment by fpusan** [comment]
We are using metabat version 2.12.1, but it is true that those options are deprecated.

It seems that they recently disabled the passing of unknown options in the argument parser
https://bitbucket.org/berkeleylab/metabat/commits/ca8c2165b2a45cd0ee0c618b24d9e6f3cb1c9934

so that might explain why our version works but yours doesn't.

If that's the only problem, you can easily hack your way out of it.
Just edit file `/home/btschits/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/15.bin_metabat2.pl` and remove the offending parameters in line 113.

Let me know if that works. Anyways, this is a bug on our part so we'll look into it a bit more,.

**Comment by fpusan** [comment]
Could reproduce the issue in a fresh Debian10 VM

**Comment by bresyd** [comment]
Thanks for testing this. I am somewhat glad to here that the issue is not due to my incompetence.

I also did what you suggested previously, namely removing the offending arguments from the script `/home/btschits/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/15.bin_metabat2.pl`. 
Then I started the test run again with `restart.pl Hadza -step 15` I think metabat ran successfully (there was no error and I found fasta files for 54 bins in the metabat result directory). However, I then got a new error at the checkM step (which initially had no issues).
```
Evaluating bins with CheckM (Parks et al 2015, Genome Res 25, 1043-55)

  Reading /home/btschits/miniconda3/envs/SqueezeMeta/SqueezeMeta/data/alltaxlist.txt
  Looking for DASTool bins in /scratch/btschits/so245/squeezemeta/test/Hadza/results/DAS/Hadza_DASTool_bins
  27 bins found

  Bin 1/27: maxbin.007.fasta.contigs.fa.tax
  Using profile for domain rank : Bacteria
Error running command:    PATH=/home/btschits/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin:/home/btschits/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/pplacer:/home/btschits/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/hmmer:$PATH /home/btschits/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/checkm analyze -t 12 -x maxbin.007.fasta.contigs.fa /scratch/btschits/so245/squeezemeta/test/Hadza/data/checkm_markers/Bacteria.ms /scratch/btschits/so245/squeezemeta/test/Hadza/results/DAS/Hadza_DASTool_bins /scratch/btschits/so245/squeezemeta/test/Hadza/temp/checkm_batch > /dev/null 2>&1 at /home/btschits/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/18.checkM_batch.pl line 159.
Stopping in STEP18 -> 18.checkM_batch.pl
Died at /home/btschits/miniconda3/envs/SqueezeMeta/bin/restart.pl line 463.
```

Do you have any suggestions where to go from here? Do you think you will be able to fix the debian issue in the near future? Because if that was the case, it might be better for me to wait until you can provide a fixed metasqueeze version instead of continuing troubleshooting the issues on my side.

Thanks again

**Comment by fpusan** [comment]
I'll look into it and get back to you

**Comment by fpusan** [comment]
Finished the run succesfully in my Debian10 VM.
Might it be that at some point you reinstalled SQM and didn't reconfigure it?

Please run

`PATH=/home/btschits/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin:/home/btschits/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/pplacer:/home/btschits/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/hmmer:$PATH /home/btschits/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/checkm analyze -t 12 -x maxbin.007.fasta.contigs.fa /scratch/btschits/so245/squeezemeta/test/Hadza/data/checkm_markers/Bacteria.ms /scratch/btschits/so245/squeezemeta/test/Hadza/results/DAS/Hadza_DASTool_bins /scratch/btschits/so245/squeezemeta/test/Hadza/temp/checkm_batch`

If it complains with a `FileNotFoundError` and says that it can't load the CheckM config file, please reconfigure SQM with `configure_nodb.pl /path/to/database`. Then restart from step 18, it should work.

If the error message is different, let me know.

**Comment by bresyd** [comment]
Hi again,

I don't recall reinstalling SQM but I did remove the conda environment and then reinstalled it, could that have caused the issue?

I got the `FileNotFoundError` you predicted and then ran the `configure_nodb.pl /path/to/database` script and restarted with `restart.pl Hadza -step 18`. It seems to be working now, this is the output that is currently produced on the terminal:
```
[0 seconds]: STEP18 -> CHECKING BINS: 18.checkM_batch.pl
  Evaluating bins with CheckM (Parks et al 2015, Genome Res 25, 1043-55)

  Reading /home/btschits/miniconda3/envs/SqueezeMeta/SqueezeMeta/data/alltaxlist.txt
  Looking for DASTool bins in /scratch/btschits/so245/squeezemeta/test/Hadza/results/DAS/Hadza_DASTool_bins
  27 bins found

  Bin 1/27: maxbin.007.fasta.contigs.fa.tax
  Using profile for domain rank : Bacteria
  Bin 2/27: metabat2.40.fa.contigs.fa.tax
  Using profile for genus rank : Treponema
  Bin 3/27: maxbin.001.fasta.contigs.fa.tax
  Using profile for order rank : Aeromonadales
  Bin 4/27: maxbin.039.fasta.contigs.fa.tax
  Using profile for domain rank : Bacteria
  Bin 5/27: maxbin.023.fasta.contigs.fa.tax
  Using profile for domain rank : Bacteria
  Bin 6/27: maxbin.048.fasta.contigs.fa.tax
  Using profile for genus rank : Escherichia
```
Thank you so much for helping me solving this issue, much appreciated!

I have one more question though: I was wondering is if 27 is the correct number of bins after DAS_tool? This is because maxbin gets 51 bins and metabat gets 54 bins, hence I find it strange that the number of bins is only 27 after integration with DAS_tool. Or this this the corrected results, since DAS_tool removes bins below a certain score threshold?

**Comment by fpusan** [comment]
It seems that SQM works in Debian without too much hassle. Those are good news for us.

Yes, these are the non-redundant bins above a certain score threshold.
27 bins seems similar to the values we get in the test data. The number will vary between runs, but anything between 20 and 30 is normal for us.

**Comment by bresyd** [comment]
Great, thanks a lot. Looking forward to applying the squeezemeta pipeline to my own data now. Will let you know how that goes.

Cheers
