### ISSUE TITLE
SQMtools not installed 

### ISSUE THREAD

**Issue by ssunil48** [jtamames/SqueezeMeta#95]
sudo R CMD INSTALL /home/******/SqeezeMeta/lib/SQMtools
**Warning: invalid package ‘/home/osboxes/SqeezeMeta/lib/SQMtools’
Error: ERROR: no packages specified**

**Comment by jtamames** [comment]
Wow, that was succint
Could you be missing an "u" in "SqueezeMeta" in path specification? I mean, wouldn´t it be /home/osboxes/SqueezeMeta/lib/SQMtools?

**Comment by ssunil48** [comment]
Thank you Sir, It's Done.
