### ISSUE TITLE
missing functions by sqm2itol.pl

### ISSUE THREAD

**Issue by yjiakang** [jtamames/SqueezeMeta#96]
Hello!
I met a problem when filter functions by using sqm2itol.pl. The functions I provide can not be correctly selected, some functions like _Bacterial chemotaxis_ and _Benzoate degradation_ were missing. Here I attach [pathway_select.txt](https://github.com/jtamames/SqueezeMeta/files/4564169/pathway_select.txt) for your help. 
Best! Have a nice day.

**Comment by jtamames** [comment]
Hello
Sorry for the delay in my response. Are you using KEGG or Metacyc?
Could you please upload the file 21*pathways in your results directory (the one that corresponds to KEGG or Metacyc)? Also upload the heatmap_pathways.txt created by sqm2itol.pl
Best,
Javier

**Comment by yjiakang** [comment]
Hi, thanks for reply. I am using  KEGG. Actually, I have completed my selection manually.
Here is my commond and the files you request.
```
(SqueezeMeta) [jkyin@mn02 squeezemeta]$ sqm2itol.pl -completion 70 -contamination 10 -classification kegg -functions pathway_select.txt PZH
```

[21.PZH.kegg.zip](https://github.com/jtamames/SqueezeMeta/files/4627265/21.PZH.kegg.zip)
[21.PZH.metacyc.zip](https://github.com/jtamames/SqueezeMeta/files/4627268/21.PZH.metacyc.zip)
[heatmap_pathways.txt](https://github.com/jtamames/SqueezeMeta/files/4627213/heatmap_pathways.txt)
Have a nice day, and thanks for trying to fix this.
Best!

**Comment by jtamames** [comment]
Hello
Actually, neither Bacterial chemotaxis nor Benzoate degradation are listed in the 21*pathways file, what means that MinPath was not reporting them to be present in the data set. Why do you think they must be plotted?

Best,

**Comment by yjiakang** [comment]
Yeah, I did not noticed that before your reply. Sorry for disturbance.
