### ISSUE TITLE
lack of .lon file in intermediate folder

### ISSUE THREAD

**Issue by LCrossman** [jtamames/SqueezeMeta#97]
Hi, I'm running long reads minion investigation, using sequential mode on MacOSX and have run through most of the pipeline but I'm stuck on step 21 where the pipeline is failing with unable to find the .lon file in the intermediate folder.  Is that just a file of contig lengths?

**Comment by fpusan** [comment]
Yes, it is a tab-delimited file with contig IDs and contig lenghts.

This said, I'm actually amazed you got that far in a MacOSX system. Did you had to recompile some binaries or did it work out of the box for you?

**Comment by LCrossman** [comment]
Thanks!! I can just make that then.
Well I started with the ext assembly anyway and I had aragorn, barrnap, diamond, hmmer prodigal elsewhere already then I brew installed metabat2.  MinPath: conda installed glpk and minpath.  I needed a perl library. 
Main problem was the same in each step running external dependencies, like in:
 my $wc=qx(wc -l $contigsfna); - this caused every step to fail with no file but the file is there, and it seems to be because there's an extra space in the output so I now have
my($miss,$wsize,$rest)=split(/\s+/,$wc); in every step which works, but i don't really know perl, more python and R.

**Comment by jtamames** [comment]
Awesome!
The script you are missing is created at the end of the 01 step (assembly). I wonder why it is not being created. I will take a look.
Best,
Javier

**Comment by jtamames** [comment]
It is also very surprising that the file is also needed in step 11 (and intended to die if it is not present), but you got past that point.

**Comment by LCrossman** [comment]
Just to comment that I got this to run fine on Mojave Mac (sequential)! It was mainly a matter of compiling the trickier dependencies for Mac with conda, brew or pip, the lon file formation I think was being skipped in the first step, not moving the reads into the right directory for the later stages (maybe a permissions issue?) so needed to be manually placed, and the spaces in the output as mentioned previously.  Great, Thanks

**Comment by jtamames** [comment]
Thanks to you! Knowing that you succeeded maybe we should give a shot at a Mac version.

Best,
Javier
