### ISSUE TITLE
running SqueezeMeta with pair end reads and single end 

### ISSUE THREAD

**Issue by fconstancias** [jtamames/SqueezeMeta#99]
Dear SqueezeMeta,

Thanks again for your work developping SqueezeMeta.

I am working on a public dataset on for some reasons I ignore, 10% of the reads have a mate : pair1 and pair2 but the rest of the data are singles reads. How could I run SqueezeMeta with those?

Best,

Florentin

**Comment by jtamames** [comment]
Hello
Dropping one of the pairs is usually the result of running some quality filtering tools, in which one of the mates is passing the criteria but the other does not. I think you can use Trimmomatic for removing these instances. Also check prinseq, cutadapt, probably some of these tools can do the job. In any case, just keeping 10% of the reads is pretty extreme. Why don´t you contact the authors to understand what happened there?
Best,

**Comment by fconstancias** [comment]
Many thanks Javier for your quick answer. 
The authors subsampled the sequences to a limited number of reads in order to 'rarefy' sequencing depth and lost most of the pair-end information at that step. Then they used read level 'blast' strategy to infer taxonomy. They are not willing to share the original raw fastq files, as they might be also re-analyzing using an assembly based strategy.
Considering only the single-end reads would do the trick to run SqueezeMeta?

**Comment by jtamames** [comment]
If you just have 10% of the original reads probably it is not worth it. You can always try and see the results, especially the mapping percentage in the mappingstat file. If you see that it is low (below 50%), you can switch to analyse the raw reads using sqm_reads.
Best,

**Comment by jtamames** [comment]
Hello
Do you mean that you didi it using SqueezeMeta, or running megahit by itself? You can use single end in SqueezeMeta, just label it as "pair1" in the samples file. No way to use a mixture of single and paired reads. Megahit demands an equal number of reads in both pairs. What you can do is using the merged or seqmerge modes.There each sample is assembled separately so you can use any combination of single and paired reads.
Best,
Javier

**Comment by fconstancias** [comment]
Hey,
Thanks for your reply.
I have used megahit by itself using -1 -2 and -s (pair1, pair2 and single-end reads, respectively).
I am planning to combine pair1 and single-end reads as pair1 and use SqueezeMeta. providing the assembly run with megahit using -1 -2 and -s reads.
Thanks again for your tool and support!

**Comment by jtamames** [comment]
Sounds great. Good luck, and tell us about the result
Best,
Javier

**Comment by fconstancias** [comment]
Hi Javier,
It worked perfectly.

Best,

Florentin

**Comment by imbmanna** [comment]
Hi @jtamames 

I have a simular issue as @fconstancias , I have a sample where after performing the Trimmomatic quality control, reads survived both R1 + R2 were ~50% of the original reads. The unpaired forward (U1) and reverse reads (U2) had about 40% and 10%, respectively. So, proceeding with only the paired end reads will loose ~50% of the sequence data. As per your suggestion above, 

"._..What you can do is using the merged or seqmerge modes.There each sample is assembled separately so you can use any combination of single and paired reads._"

I tried somethings like below: 

Sample1       sample1_1P.fq.gz      pair1
Sample1       sample1_2P.fq.gz      pair2
Sample1       sample1_1U.fq.gz      pair1
Sample1       sample1_2U.fq.gz      pair1
Sample2       sample2_1P.fq.gz      pair1
Sample2       sample2_2P.fq.gz      pair2
Sample2       sample2_1U.fq.gz      pair1
Sample2       sample2_2U.fq.gz      pair1

I tried both the merged or seqmerge modes but the run is aborted during the 

[31mStopping in STEP1 -> 01.run_assembly_merged.pl. Program finished abnormally

with the following error. 

2022-09-20 14:02:52 - Error occurs when reading inputs during the 

Can you please suggest if I am using the combination of single end and paired end correctly?

Thank you,
BM.
